### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by harvey1673** [akfamily/akshare#1320]
DCE前20期货公司排名目前的接口只能拿到2020年7月20日以后的数据，我看了下2020年7月17日之前的数据可以从batch接口拿到，这个batch接口直接可以下载压缩的zip文件可以直接拿到有品种的，不知道能否增加这个接口的功能
http://www.dce.com.cn/publicweb/quotesdata/exportMemberDealPosiQuotesBatchData.html?memberDealPosiQuotes.variety=all&memberDealPosiQuotes.trade_type=0&contract.contract_id=all&contract.variety_id=all&year=2020&month=6&day=17&batchExportFlag=batch

**Comment by jindaxiang** [comment]
> DCE前20期货公司排名目前的接口只能拿到2020年7月20日以后的数据，我看了下2020年7月17日之前的数据可以从batch接口拿到，这个batch接口直接可以下载压缩的zip文件可以直接拿到有品种的，不知道能否增加这个接口的功能
> http://www.dce.com.cn/publicweb/quotesdata/exportMemberDealPosiQuotesBatchData.html?memberDealPosiQuotes.variety=all&memberDealPosiQuotes.trade_type=0&contract.contract_id=all&contract.variety_id=all&year=2020&month=6&day=17&batchExportFlag=batch

期货接口会在近期调整
