### ISSUE TITLE
关于IP代理池设置功能添加建议

### ISSUE THREAD

**Issue by yuxuechao** [akfamily/akshare#1678]
**Is your feature request related to a problem? Please describe.**

一个功能不加time.sleep，ip很容易被封掉，考虑添加IP代理池功能

**Describe the solution you'd like**

比如我有几个代理IP:port，ak有个setProxy方法的话，在引用后用户可以主动设置一个IP代理池使用，随机或者依次读取
使用如下
import akshare as ak
PROXYS = [
    {'http': 'http://192.168.1.1:8888'},
     {'http': 'http://192.168.1.2:8888'},
]
ak.setProxy(PROXYS, ‘random’)

以上建议，希望作者大大能够采纳-v-
**Describe alternatives you've considered**

**Additional context**

**Comment by jindaxiang** [comment]
> **Is your feature request related to a problem? Please describe.**
> 
> 一个功能不加time.sleep，ip很容易被封掉，考虑添加IP代理池功能
> 
> **Describe the solution you'd like**
> 
> 比如我有几个代理IP:port，ak有个setProxy方法的话，在引用后用户可以主动设置一个IP代理池使用，随机或者依次读取
> 使用如下
> import akshare as ak
> PROXYS = [
> {'http': 'http://192.168.1.1:8888'},
> {'http': 'http://192.168.1.2:8888'},
> ]
> ak.setProxy(PROXYS, ‘random’)
> 
> 以上建议，希望作者大大能够采纳-v-
> **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.
> 
> **Additional context**
> Add any other context or screenshots about the feature request here.

由于是函数式的代码，暂时不能采用这种模型，近期正在考虑增加代理接口
