### ISSUE TITLE
有个参数的含义可否解释一下？

### ISSUE THREAD

**Issue by yufeiluo** [akfamily/akshare#1700]
url = "http://16.push2.eastmoney.com/api/qt/clist/get"
params = {
    "pn": "1",
    "pz": "5000",
    "po": "1",
    "np": "1",
    "ut": "bd1d9ddb04089700cf9c27f6f7426281",
    "fltt": "2",
    "invt": "2",
    "fid": "f243",
    "fs": "b:MK0354",
    "fields": "f1,f152,f2,f3,f12,f13,f14,f227,f228,f229,f230,f231,f232,f233,f234,f235,f236,f237,f238,f239,f240,f241,f242,f26,f243",
    "_": "1590386857527",
}

请问，最后一个参数，    "_": "1590386857527",  它的含义是什么呢？请解释一下，谢谢，我确信它不是时间戳。

**Comment by jindaxiang** [comment]
这个是时间参数 timestamp
