### ISSUE TITLE
希望能够在象申万一级sw_index_daily_indicator中追加市场表征的各个代码查询

### ISSUE THREAD

**Issue by xnw176** [akfamily/akshare#1701]
![1632280344307](https://user-images.githubusercontent.com/82297022/134277647-7ea65c8a-52aa-4560-a965-9c2b274df439.jpg)
非常感谢！

**Comment by jindaxiang** [comment]
> ![1632280344307](https://user-images.githubusercontent.com/82297022/134277647-7ea65c8a-52aa-4560-a965-9c2b274df439.jpg)
> 非常感谢！

感谢反馈，升级到 AKShare 1.1.33，已新增 sw_index_representation_spot，详情查看文档：https://www.akshare.xyz/data/index/index.html?highlight=%E7%94%B3%E4%B8%87#id22

**Comment by xnw176** [comment]
非常感谢！

读取第3个指数的时候发生问题，应该是千分位符的问题吧。
<img width="916" alt="Screen Shot 2021-09-23 at 2 12 48 PM" src="https://user-images.githubusercontent.com/82297022/134461926-6a73bda4-6dd6-4ff3-bbbd-696fccd8bc70.png">

**Comment by jindaxiang** [comment]
> 非常感谢！
> 
> 读取第3个指数的时候发生问题，应该是千分位符的问题吧。
> <img alt="Screen Shot 2021-09-23 at 2 12 48 PM" width="916" src="https://user-images.githubusercontent.com/82297022/134461926-6a73bda4-6dd6-4ff3-bbbd-696fccd8bc70.png">

已修复，升级到 AKShare 1.1.36

**Comment by xnw176** [comment]
可以用了, many thanks~
