### ISSUE TITLE
ETF日频行情接口建议

### ISSUE THREAD

**Issue by scanfyu** [akfamily/akshare#1706]
**Is your feature request related to a problem? Please describe.**
ETF基金行情数据；

**Describe the solution you'd like**
数据接口地址：http://quote.eastmoney.com/center/gridlist.html#fund_etf

**Describe alternatives you've considered**
最好可以包含获取数据所对应的交易日信息

**Additional context**
无

**Comment by jindaxiang** [comment]
> ETF基金行情

通过新浪接口获取

**Comment by xungeer** [comment]
> 
1.6.57版本新浪接口(fund_etf_hist_sina())获取的ETF日频交易数据不含复权信息，能否考虑通过stock_zh_a_hist接口实现？
