### ISSUE TITLE
建议部分接口添加历史信息

### ISSUE THREAD

**Issue by LiXirong** [akfamily/akshare#1708]
建议以下接口添加日期选项，可以获得历史数据。

交易所信息：
stock_sse_summary, stock_szse_summary

指数信息：
stock_zh_index_spot

**Comment by jindaxiang** [comment]
> 建议以下接口添加日期选项，可以获得历史数据。
> 
> 交易所信息：
> stock_sse_summary, stock_szse_summary
> 
> 指数信息：
> stock_zh_index_spot

数据源并没有相关数据提供，如果您这边有相关的数据源，可以在后面留言
