### ISSUE TITLE
是否可以考虑获取晨星网的基金数据，非常感谢🙏

### ISSUE THREAD

**Issue by xnw176** [akfamily/akshare#1711]
网址：
https://www.morningstar.cn/quickrank/default.aspx

<img width="974" alt="Screen Shot 2021-09-23 at 2 21 52 PM" src="https://user-images.githubusercontent.com/82297022/134462600-1673cbda-0b31-44e3-977c-0d5772bb2b33.png">
<img width="974" alt="Screen Shot 2021-09-23 at 2 22 15 PM" src="https://user-images.githubusercontent.com/82297022/134462613-b79015fb-c8e9-4462-808b-90c25f538775.png">
<img width="974" alt="Screen Shot 2021-09-23 at 2 22 32 PM" src="https://user-images.githubusercontent.com/82297022/134462636-20e730b6-9590-49db-b789-b985dde0840a.png">
<img width="974" alt="Screen Shot 2021-09-23 at 2 22 47 PM" src="https://user-images.githubusercontent.com/82297022/134462643-636b96ec-6366-438c-bb99-d3e0fbfcd07f.png">

**Comment by jindaxiang** [comment]
> 网址：
> https://www.morningstar.cn/quickrank/default.aspx
> 
> <img alt="Screen Shot 2021-09-23 at 2 21 52 PM" width="974" src="https://user-images.githubusercontent.com/82297022/134462600-1673cbda-0b31-44e3-977c-0d5772bb2b33.png">
> 
> <img alt="Screen Shot 2021-09-23 at 2 22 15 PM" width="974" src="https://user-images.githubusercontent.com/82297022/134462613-b79015fb-c8e9-4462-808b-90c25f538775.png">
> 
> <img alt="Screen Shot 2021-09-23 at 2 22 32 PM" width="974" src="https://user-images.githubusercontent.com/82297022/134462636-20e730b6-9590-49db-b789-b985dde0840a.png">
> 
> <img alt="Screen Shot 2021-09-23 at 2 22 47 PM" width="974" src="https://user-images.githubusercontent.com/82297022/134462643-636b96ec-6366-438c-bb99-d3e0fbfcd07f.png">

需要登录信息的网站暂时不考虑

**Comment by xnw176** [comment]
感谢回复～
