### ISSUE TITLE
交易日历失效

### ISSUE THREAD

**Issue by nigo81** [akfamily/akshare#1721]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本
ArcoLinux x86_64
2. Python 版本
Python 3.9.7
3. AKShare 版本
1.1.43
4. 接口的名称和代码
交易日历  tool_trade_date_hist_sina
5. 接口报错的截图或代码
![image](https://user-images.githubusercontent.com/38601513/134846045-48389f9e-a0a2-42a6-a54e-65474d1261fb.png)
执行后一直没有反应，没有获取到交易日历数据。
6. 期望获得的正确结果
能返回交易日历数据。

**Comment by jindaxiang** [comment]
> 4\. tool_trade_date_hist_sina

可以正常获取！
![image](https://user-images.githubusercontent.com/18234520/134854703-d4c9f28f-b9fa-4fd5-87bd-91fad91d7c1f.png)

**Comment by jindaxiang** [comment]
可以看下是不是你的操作系统问题
