### ISSUE TITLE
AKShare 质押式回购接口问无法查询到正确值

### ISSUE THREAD

**Issue by Seanid** [akfamily/akshare#1728]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本:win10
2. Python 版本:3.9.2
3. AKShare 版本:1.1.49
4. 接口的名称和代码:质押式回购-成交明细(bond_repo_zh_tick)
5. 接口报错的截图或代码
```
bond_repo_zh_tick_df = ak.bond_repo_zh_tick(code="sz131802", trade_date="20210120")
print(bond_repo_zh_tick_df)
```
![image](https://user-images.githubusercontent.com/10057641/135086887-48c83d23-ed59-4ada-8f90-e815581e3a6e.png)

**Comment by jindaxiang** [comment]
> bond_repo_zh_tick

感谢反馈问题，数据源没有提供该数据
