### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by quanplex** [akfamily/akshare#1731]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
操作系统版本 Mac OS 10.13
Python 版本 3.8.5
AKShare 版本 1.1.50
接口的名称和代码 stock_wc_hot_rank
接口报错的截图或代码

hot <-  ak$stock_wc_hot_rank(date="20210929") %>%  py_to_r()

Error in py_call_impl(callable, dots$args, dots$keywords) : 
 KeyError: "['个股热度排名基数', '个股热度排名名次'] not in index"

6. 期望获得的正确结果

正确结果是2021年9月29日的问财全部热股数据

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> **描述遇到的问题** 操作系统版本 Mac OS 10.13 Python 版本 3.8.5 AKShare 版本 1.1.50 接口的名称和代码 stock_wc_hot_rank 接口报错的截图或代码
> 
> hot <- ak$stock_wc_hot_rank(date="20210929") %>% py_to_r()
> 
> Error in py_call_impl(callable, dots$args, dots$keywords) : KeyError: "['个股热度排名基数', '个股热度排名名次'] not in index"
> 
> 1. 期望获得的正确结果
> 
> 正确结果是2021年9月29日的问财全部热股数据

感谢反馈问题，已修复，升级到 AKShare 1.1.51 使用
