### ISSUE TITLE
请求一下，是否有接口可以单独或批量获取股票的基本信息，比如上市时间？

### ISSUE THREAD

**Issue by flftfqwxf** [akfamily/akshare#1737]
我需要使用公司的上市时间，
目前使用过：stock_ipo_info 这个接口，但是这个在调用几次后就会报错，应该是有限制
请问有没有接口可以单独或指获取股票的基本信息，比如上市日期，并且不会被限制的，谢谢！

**Comment by jindaxiang** [comment]
> 我需要使用公司的上市时间， 目前使用过：stock_ipo_info 这个接口，但是这个在调用几次后就会报错，应该是有限制 请问有没有接口可以单独或指获取股票的基本信息，比如上市日期，并且不会被限制的，谢谢！

stock_info_sz_name_code

**Comment by flftfqwxf** [comment]
@jindaxiang 多谢，另外是否有接口可以获取股票的其他动态信息比如：市值，流通市值这些，我只找到 stock_zh_kcb_spot 科创板的 市值字段 makcap，其他的没有找到，历史行情和实时行情都没有找到相应字段,谢谢

**Comment by flftfqwxf** [comment]
@jindaxiang 深市[stock_info_sz_name_code]有一个流通总股本，可以计算流通市值，但是上证中没有这样的字段

**Comment by xnw176** [comment]
如果仅需要上市时间这个数据我有，而且这个数据并不需要频繁更新，留个email地址我发你excel格式的文件。

**Comment by flftfqwxf** [comment]
@xnw176 这个我已经获取到了，现在我想获取股票的流通股本这些数据，请问有么
