### ISSUE TITLE
能否增加alpha101和alpha191因子的接口

### ISSUE THREAD

**Issue by liiitleboy** [akfamily/akshare#1759]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jindaxiang** [comment]
> **Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> 
> **Describe the solution you'd like** A clear and concise description of what you want to happen.
> 
> **Describe alternatives you've considered** A clear and concise description of any alternative solutions or features you've considered.
> 
> **Additional context** Add any other context or screenshots about the feature request here.

请问有相关的目标网站吗？
