### ISSUE TITLE
请考虑增长开放式基金规模读取接口🙏~

### ISSUE THREAD

**Issue by xnw176** [akfamily/akshare#1765]
数据地址：
http://vip.stock.finance.sina.com.cn/fund_center/index.html#jjgmgpx

截图：
<img width="987" alt="image" src="https://user-images.githubusercontent.com/82297022/137612192-0b715ffe-6794-43c1-9252-025b0e6bbe57.png">

万分感谢🙏

**Comment by jindaxiang** [comment]
> 数据地址： http://vip.stock.finance.sina.com.cn/fund_center/index.html#jjgmgpx
> 
> 截图： <img alt="image" width="987" src="https://user-images.githubusercontent.com/82297022/137612192-0b715ffe-6794-43c1-9252-025b0e6bbe57.png">
> 
> 万分感谢🙏

感谢提供信息，已更新升级到 AKShare 1.1.69 查看 fund_scale_open_sina，详情查看文档
