### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by noword** [akfamily/akshare#1769]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本
windows 10

2. Python 版本
3.8

3. AKShare 版本
最新

4. 接口的名称和代码
ak.fund_em_open_fund_info(fund='000009', indicator="累计净值走势")

5. 接口报错的截图或代码
  File "C:\Python38\lib\site-packages\akshare\utils\demjson.py", line 4957, in decode
    raise errors[0]
akshare.utils.demjson.JSONDecodeError: Missing value for object property, expected ":"

6. 期望获得的正确结果
期望获得正确结果

**Comment by jindaxiang** [comment]
> https://fund.eastmoney.com/000009.html
> 
> 这个页面上有，不知道算不算是000009的基金。

货币型基金
