### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by huxuwei** [akfamily/akshare#1776]
场内交易基金-历史数据
fund_em_etf_fund_info_df

每次返回所有数据太麻烦，而且很慢。
接口参数可以添加时间，目标地址查询有时间的入参

**Comment by jindaxiang** [comment]
> 场内交易基金-历史数据 fund_em_etf_fund_info_df
> 
> 每次返回所有数据太麻烦，而且很慢。 接口参数可以添加时间，目标地址查询有时间的入参

感谢反馈问题，升级到 AKShare 1.1.74 已更新该接口
