### ISSUE TITLE
公募基金获取持仓数据部分数据获取不正确

### ISSUE THREAD

**Issue by w38351479** [akfamily/akshare#1817]
代码中的“akshare/akshare/fund/fund_em_portfolio.py”的45行“.astype(str).str.zfill(6)”指定了获取代码为6位数，不足的时候自动填充0，在A股没问题。但是挺多基金持有部分港股的，这样导致输出的股票代码不正确，例如获取基金代码001371的持仓就会不正确了

**Comment by w38351479** [comment]
44行指定转换数据类型就可以了，不需要后面截取数据，暂未发现有什么不良后果
temp_df = pd.read_html(data_json["content"], converters={"股票代码": str})[item]

**Comment by jindaxiang** [comment]
> converters={"股票代码": str}

感谢反馈问题，这个方法不错，已经修复，升级到 AKShare 1.1.94
