### ISSUE TITLE
还请能够支持可转债的分钟级别历史行情数据，可转债市场也有很多关注度，谢谢了

### ISSUE THREAD

**Issue by tzmdaming** [akfamily/akshare#1820]
尊敬的官方人员您们好，
Akshare是我用过的非常好的一个获取金融数据的项目，在此感谢项目组成员的辛苦付出，谢谢你们！
目前Akshare支持新浪接口的日线级别可转债历史行情数据，不过新浪的接口质量不够高，不知道是否能够采用东方财富网的可转债数据？目前用下来，东方财富网接口质量较高
另外一个是，是否可以支持可转债历史行情数据的分钟级别数据呢？目前可转债属于T+0交易，我认识的较多投资可转债的朋友，往往是日内操作，所以分钟级别的数据用处也很大，比如1分钟，5分钟，15分钟，60分钟这种，还请项目组也能考虑支持该接口~
再次谢谢项目组的辛勤付出~

**Comment by tzmdaming** [comment]
比如这个网址：
http://quote.eastmoney.com/concept/sz128131.html
最后是“.html”之前是转债代码

**Comment by jindaxiang** [comment]
> 尊敬的官方人员您们好， Akshare是我用过的非常好的一个获取金融数据的项目，在此感谢项目组成员的辛苦付出，谢谢你们！ 目前Akshare支持新浪接口的日线级别可转债历史行情数据，不过新浪的接口质量不够高，不知道是否能够采用东方财富网的可转债数据？目前用下来，东方财富网接口质量较高 另外一个是，是否可以支持可转债历史行情数据的分钟级别数据呢？目前可转债属于T+0交易，我认识的较多投资可转债的朋友，往往是日内操作，所以分钟级别的数据用处也很大，比如1分钟，5分钟，15分钟，60分钟这种，还请项目组也能考虑支持该接口~ 再次谢谢项目组的辛勤付出~

感谢反馈问题和提供接口地址，升级到 AKShare 1.1.96 版本，已新增 bond_zh_hs_cov_min 接口，详情查看文档
