### ISSUE TITLE
这里能删掉tqdm吗

### ISSUE THREAD

**Issue by windblood** [akfamily/akshare#1834]
https://github.com/akfamily/akshare/blob/8e30e014a9d33f96bf26afdd7edf9b9fe6b7e4a3/akshare/fund/fund_em_portfolio.py#L45

一年最多4个表，速度很快，加进度条没意义。
因为通常会抓取很多个基金，我在这一层加了tqdm，就两个了，输出很难看。

**Comment by jindaxiang** [comment]
> https://github.com/akfamily/akshare/blob/8e30e014a9d33f96bf26afdd7edf9b9fe6b7e4a3/akshare/fund/fund_em_portfolio.py#L45
> 
> 一年最多4个表，速度很快，加进度条没意义。 因为通常会抓取很多个基金，我在这一层加了tqdm，就两个了，输出很难看。

感谢反馈问题，请升级到 AKShare 1.2.4，已修复
