### ISSUE TITLE
AKShare 接口问题报告  指数历史成份 index_stock_hist 获取数据不全，只获取了一页

### ISSUE THREAD

**Issue by chenandjian** [akfamily/akshare#1835]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本 win 10
2. Python 版本 3.9.1
3. AKShare 版本 1.2.3
4. 接口的名称和代码 指数历史成份 index_stock_hist
5. 接口报错的截图或代码
例如：抓取沪深300的历史成分，只抓取了1页
![image](https://user-images.githubusercontent.com/2405009/140596178-4cd42c57-b5ac-4ad7-9b98-c6812a31e86a.png)

6. 期望获得的正确结果 获取所有数据
7. 临时修改
删除红框内的代码即可显示全部 
![image](https://user-images.githubusercontent.com/2405009/140596421-9cc18b26-3ef1-4708-bbe2-15cc37d481df.png)

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本 win 10
> 2. Python 版本 3.9.1
> 3. AKShare 版本 1.2.3
> 4. 接口的名称和代码 指数历史成份 index_stock_hist
> 5. 接口报错的截图或代码
>    例如：抓取沪深300的历史成分，只抓取了1页
>    ![image](https://user-images.githubusercontent.com/2405009/140596178-4cd42c57-b5ac-4ad7-9b98-c6812a31e86a.png)
> 6. 期望获得的正确结果 获取所有数据
> 7. 临时修改
>    删除红框内的代码即可显示全部
>    ![image](https://user-images.githubusercontent.com/2405009/140596421-9cc18b26-3ef1-4708-bbe2-15cc37d481df.png)

感谢反馈问题，请升级 AKShare 1.2.5，已修复该问题
