### ISSUE TITLE
增加股东户数接口申请，非常感谢🙏

### ISSUE THREAD

**Issue by xnw176** [akfamily/akshare#1842]
以凯迪股份605288为例
目标地址：
http://data.eastmoney.com/gdhs/detail/605288.html

数据区域截图（成立时间长的股票包含多页）
<img width="875" alt="image" src="https://user-images.githubusercontent.com/82297022/140672202-10f2ec45-d221-4854-a559-0f7d7dd0e140.png">

非常感谢🙏。

**Comment by jindaxiang** [comment]
> 以凯迪股份605288为例 目标地址： http://data.eastmoney.com/gdhs/detail/605288.html
> 
> 数据区域截图（成立时间长的股票包含多页） <img alt="image" width="875" src="https://user-images.githubusercontent.com/82297022/140672202-10f2ec45-d221-4854-a559-0f7d7dd0e140.png">
> 
> 非常感谢🙏。

感谢反馈问题，升级到 AKShare 1.2.9 版本，已新增

**Comment by xnw176** [comment]
many thanks
