### ISSUE TITLE
bond_zh_hs_daily接口会返回已停牌的可转债交易信息

### ISSUE THREAD

**Issue by zlh1992** [akfamily/akshare#1843]
aks.bond_zh_hs_daily(symbol="sh110033")
2021-11-03 00:00:00+00:00 102.1500000 102.2800000 101.7100000 101.8600000   403660.0000000
2021-11-04 00:00:00+00:00 101.9500000 102.3000000 101.5600000 101.6400000  1574560.0000000
该转债11月4日停牌了

也希望补充转债的停牌信息查询接口，谢谢！

**Comment by jindaxiang** [comment]
> sh110033

目前已经对该接口进行一定的修正，升级到 AKShare 1.2.10 使用；
你反映的问题可以参考如下
![image](https://user-images.githubusercontent.com/18234520/140722896-451aac45-3c4c-47d4-95b3-006f219eafbb.png)

**Comment by zlh1992** [comment]
谢谢 了解了！



At 2021-11-08 18:09:42, "Albert King" ***@***.***> wrote:

Closed #1843.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
