### ISSUE TITLE
stock_zh_a_gdhs()返回数据错误

### ISSUE THREAD

**Issue by xnw176** [akfamily/akshare#1847]
**Describe the bug**
stock_zh_a_gdhs()接口返回数据全部错误

**Screenshots**
实际数据
<img width="880" alt="image" src="https://user-images.githubusercontent.com/82297022/140842813-1950eaeb-a696-42d6-b1f8-34e520e260e1.png">

获取的数据
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/82297022/140842863-6fc21a59-7f79-4241-99a2-ef9a6b89dad1.png">

**Desktop (please complete the following information):**
 - OS: MAC OS 12
 - Browser: Microsoft Edge
 - Python Version: 3.8
 - Akshare Version: 1.2.11

**Comment by jindaxiang** [comment]
> **Describe the bug** stock_zh_a_gdhs()接口返回数据全部错误
> 
> **Screenshots** 实际数据 <img alt="image" width="880" src="https://user-images.githubusercontent.com/82297022/140842813-1950eaeb-a696-42d6-b1f8-34e520e260e1.png">
> 
> 获取的数据 <img alt="image" width="1000" src="https://user-images.githubusercontent.com/82297022/140842863-6fc21a59-7f79-4241-99a2-ef9a6b89dad1.png">
> 
> **Desktop (please complete the following information):**
> 
> * OS: MAC OS 12
> * Browser: Microsoft Edge
> * Python Version: 3.8
> * Akshare Version: 1.2.11

已经在改函数新增参数，请阅读文档后调用
