### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by Bazinga28** [akfamily/akshare#1861]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本 Anaconda3
2. Python 版本 Python3.9.1
3. AKShare 版本 更新到最新版了
4. 接口的名称和代码 ak.amac_fund_info  total_df = ak.amac_fund_info()
5. 接口报错的截图或代码 数据集大小只有100个
6. 期望获得的正确结果 AMAC网站一个页面允许的最大行数100，所以这个接口只爬出100条数据，应该返回所有历史数据的

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本 Anaconda3
> 2. Python 版本 Python3.9.1
> 3. AKShare 版本 更新到最新版了
> 4. 接口的名称和代码 ak.amac_fund_info  total_df = ak.amac_fund_info()
> 5. 接口报错的截图或代码 数据集大小只有100个
> 6. 期望获得的正确结果 AMAC网站一个页面允许的最大行数100，所以这个接口只爬出100条数据，应该返回所有历史数据的

感谢反馈问题，主要是因为 AMAC 网站更改了数据获取的方式，已修复，升级到 AKShare 1.2.17 使用，本次只能遍历获取数据，需要较长的获取时间

**Comment by Bazinga28** [comment]
感谢！但我只能获取到1.2.16版本该怎么办？

**Comment by jindaxiang** [comment]
> 感谢！但我只能获取到1.2.16版本该怎么办？

`pip install akshare --upgrade -i https://pypi.org/simple`
