### ISSUE TITLE
AKShare 接口问题报告， stock_zh_a_gdhs_detail_em

### ISSUE THREAD

**Issue by chinobing** [akfamily/akshare#1862]
![image](https://user-images.githubusercontent.com/27722028/141441470-7ee4d644-0f4a-4999-9afd-cee7e958e9e9.png)
![image](https://user-images.githubusercontent.com/27722028/141441492-7857ee6f-5c63-4da3-9a0a-bb105145fa55.png)

![image](https://user-images.githubusercontent.com/27722028/141441532-047f5c9d-36e1-4a51-9743-a76b7614f726.png)

东方财富的数据源头好像不全

**Comment by jindaxiang** [comment]
> ![image](https://user-images.githubusercontent.com/27722028/141441470-7ee4d644-0f4a-4999-9afd-cee7e958e9e9.png) ![image](https://user-images.githubusercontent.com/27722028/141441492-7857ee6f-5c63-4da3-9a0a-bb105145fa55.png)
> 
> ![image](https://user-images.githubusercontent.com/27722028/141441532-047f5c9d-36e1-4a51-9743-a76b7614f726.png)
> 
> 东方财富的数据源头好像不全

感谢反馈问题，关于数据源的问题猜想可能是因素是每家的计算方式不同，建议不混用数据

**Comment by chinobing** [comment]
![image](https://user-images.githubusercontent.com/27722028/141446208-2fffec8d-f195-41bf-b6fb-c90bc85b90dd.png)


感觉是网页端的数据问题
