### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by Bankgit** [akfamily/akshare#1869]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. windows 10 64bit
2. Python 版本:3.8.5
3. AKShare 版本:1.2.19
4. 接口的名称和代码 fund_portfolio_hold_em(code="270014", year="2021")
5. 接口报错的截图或代码
![image](https://user-images.githubusercontent.com/26592375/141667629-1eaf6f86-70fc-4fad-8433-7f6756c8d4d9.png)
 
6. 期望获得的正确结果
fixed this issue.

**Comment by jindaxiang** [comment]
> 4\. 270014

请查看源网页，是没有数据的
