### ISSUE TITLE
AKShare 接口问题报告 -- 东方财富股票后复权数据

### ISSUE THREAD

**Issue by aforwardz** [akfamily/akshare#1878]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本
Ubuntu 18.04
2. Python 版本
3. AKShare 版本
1.2.25
4. 接口的名称和代码
ak.stock_zh_a_hist
5. 接口报错的截图或代码
![image](https://user-images.githubusercontent.com/19967761/141807118-d59b93e9-6c26-458d-a9f8-cc461d0db44c.png)
复权估计由复权因子相乘得到，怎么会是负值，看了东财官网，后复权也是错的（不确定是否只有该股票错误）
6. 期望获得的正确结果
![image](https://user-images.githubusercontent.com/19967761/141808044-9062e5e4-b40b-4201-960f-a18fffe9b5b4.png)
新浪的后复权才是对的

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本
>    Ubuntu 18.04
> 2. Python 版本
> 3. AKShare 版本
>    1.2.25
> 4. 接口的名称和代码
>    ak.stock_zh_a_hist
> 5. 接口报错的截图或代码
>    ![image](https://user-images.githubusercontent.com/19967761/141807118-d59b93e9-6c26-458d-a9f8-cc461d0db44c.png)
>    复权估计由复权因子相乘得到，怎么会是负值，看了东财官网，后复权也是错的（不确定是否只有该股票错误）
> 6. 期望获得的正确结果
>    ![image](https://user-images.githubusercontent.com/19967761/141808044-9062e5e4-b40b-4201-960f-a18fffe9b5b4.png)
>    新浪的后复权才是对的

感谢反馈问题，后复权数据如果返回是负数的，就是源数据有问题，可以在东财的网站上反馈问题。注意数据风险，建议用多个数据源的数据进行对比
