### ISSUE TITLE
AKShare 接口问题报告 ak.currency_hist 历史汇率数据接口出现问题

### ISSUE THREAD

**Issue by SeikeGS** [akfamily/akshare#1891]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本：windows 10 64bit
2. Python 版本：v3.9.2
3. AKShare 版本：1.2.33
4. 接口的名称和代码：外币对历史数据 ak.currency_hist
5. 接口报错的截图或代码：
![image](https://user-images.githubusercontent.com/57160840/142592360-775d0e33-1f1b-4b5c-b39e-a3c867c7eaa5.png)

6. 期望获得的正确结果
![image](https://user-images.githubusercontent.com/57160840/142592410-289b93c8-b0fc-46df-98c1-7634ee579a14.png)

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本：windows 10 64bit
> 2. Python 版本：v3.9.2
> 3. AKShare 版本：1.2.33
> 4. 接口的名称和代码：外币对历史数据 ak.currency_hist
> 5. 接口报错的截图或代码：
>    ![image](https://user-images.githubusercontent.com/57160840/142592360-775d0e33-1f1b-4b5c-b39e-a3c867c7eaa5.png)
> 6. 期望获得的正确结果
>    ![image](https://user-images.githubusercontent.com/57160840/142592410-289b93c8-b0fc-46df-98c1-7634ee579a14.png)

该接口需要使用代理后才能访问，文档有说明

**Comment by SeikeGS** [comment]
> 该接口需要使用代理后才能访问，文档有说明

不好意思。请问代理接口具体应该如何配置呢？

**Comment by jindaxiang** [comment]
> > 该接口需要使用代理后才能访问，文档有说明
> 
> 不好意思。请问代理接口具体应该如何配置呢？

由于法律法规问题，无法具体说明，请在网上搜索下
