### ISSUE TITLE
AKShare 接口问题报告-futures_zh_minute_sina-<Response [456]>

### ISSUE THREAD

**Issue by morin0706** [akfamily/akshare#1901]
操作系统版本：win10
Python 版本：3.8.5
AKShare 版本：1.2.38
接口的名称和代码：期货分时数据接口：futures_zh_minute_sina
程序代码：
import akshare as ak
futures_zh_minute_sina_df = ak.futures_zh_minute_sina(symbol="v2201", period="5")
print(futures_zh_minute_sina_df)
运行时，报错：
Traceback (most recent call last):
  File "E:/Python/Trade/Futures/main_contract_list/t.py", line 10, in <module>
    futures_zh_minute_sina_df = ak.futures_zh_minute_sina(symbol="v2201", period="5")
  File "C:\Users\zengr\AppData\Local\Programs\Python\Python38\lib\site-packages\akshare\futures\futures_zh_sina.py", line 386, in **futures_zh_minute_sina**
    temp_df = pd.DataFrame(json.loads(r.text.split("=(")[1].split(");")[0]))
**IndexError: list index out of range**
通过查询运行脚本futures_zh_sina.py发现：
    url = "https://stock2.finance.sina.com.cn/futures/api/jsonp.php/=/InnerFuturesNewService.getFewMinLine"
    params = {
        "symbol": symbol,
        "type": period,
    }
    **r = requests.get(url, params=params)**
    print(r)
    temp_df = pd.DataFrame(json.loads(r.text.split("=(")[1].split(");")[0]))
  报错是打印r返回：<Response [456]>
  运行成功时r的返回是：<Response [200]>
  目前尚未找到原因及解决方案！

**Comment by jindaxiang** [comment]
> 操作系统版本：win10 Python 版本：3.8.5 AKShare 版本：1.2.38 接口的名称和代码：期货分时数据接口：futures_zh_minute_sina 程序代码： import akshare as ak futures_zh_minute_sina_df = ak.futures_zh_minute_sina(symbol="v2201", period="5") print(futures_zh_minute_sina_df) 运行时，报错： Traceback (most recent call last): File "E:/Python/Trade/Futures/main_contract_list/t.py", line 10, in futures_zh_minute_sina_df = ak.futures_zh_minute_sina(symbol="v2201", period="5") File "C:\Users\zengr\AppData\Local\Programs\Python\Python38\lib\site-packages\akshare\futures\futures_zh_sina.py", line 386, in **futures_zh_minute_sina** temp_df = pd.DataFrame(json.loads(r.text.split("=(")[1].split(");")[0])) **IndexError: list index out of range** 通过查询运行脚本futures_zh_sina.py发现： url = "https://stock2.finance.sina.com.cn/futures/api/jsonp.php/=/InnerFuturesNewService.getFewMinLine" params = { "symbol": symbol, "type": period, } **r = requests.get(url, params=params)** print(r) temp_df = pd.DataFrame(json.loads(r.text.split("=(")[1].split(");")[0])) 报错是打印r返回：<Response [456]> 运行成功时r的返回是：<Response [200]> 目前尚未找到原因及解决方案！

品种代码需要大写
![image](https://user-images.githubusercontent.com/18234520/143021357-df1a3fc5-a976-4a39-b560-c664393f07b8.png)

**Comment by morin0706** [comment]
> > 操作系统版本：win10 Python 版本：3.8.5 AKShare 版本：1.2.38 接口的名称和代码：期货分时数据接口：futures_zh_minute_sina 程序代码： import akshare as ak futures_zh_minute_sina_df = ak.futures_zh_minute_sina(symbol="v2201", period="5") print(futures_zh_minute_sina_df) 运行时，报错： Traceback (most recent call last): File "E:/Python/Trade/Futures/main_contract_list/t.py", line 10, in futures_zh_minute_sina_df = ak.futures_zh_minute_sina(symbol="v2201", period="5") File "C:\Users\zengr\AppData\Local\Programs\Python\Python38\lib\site-packages\akshare\futures\futures_zh_sina.py", line 386, in **futures_zh_minute_sina** temp_df = pd.DataFrame(json.loads(r.text.split("=(")[1].split(");")[0])) **IndexError: list index out of range** 通过查询运行脚本futures_zh_sina.py发现： url = "https://stock2.finance.sina.com.cn/futures/api/jsonp.php/=/InnerFuturesNewService.getFewMinLine" params = { "symbol": symbol, "type": period, } **r = requests.get(url, params=params)** print(r) temp_df = pd.DataFrame(json.loads(r.text.split("=(")[1].split(");")[0])) 报错是打印r返回：<Response [456]> 运行成功时r的返回是：<Response [200]> 目前尚未找到原因及解决方案！
> 
> 品种代码需要大写 ![image](https://user-images.githubusercontent.com/18234520/143021357-df1a3fc5-a976-4a39-b560-c664393f07b8.png)

多谢提醒！
我改了代码：
import akshare as ak
futures_zh_minute_sina_df = ak.futures_zh_minute_sina(symbol="V2201", period="5")
print(futures_zh_minute_sina_df)
运行结果如下：
"C:\Program Files\JetBrains\PyCharm Community Edition 2021.2.3\Futures\Scripts\python.exe" E:/Python/Trade/Futures/main_contract_list/t.py
456
456
456
456
456
456
456
456
456
200
<Response [200]>
                 datetime    open    high     low   close  volume    hold
0     2021-11-02 22:05:00  8666.0  8669.0  8619.0  8631.0   28827  336836
1     2021-11-02 22:10:00  8631.0  8663.0  8617.0  8663.0   19837  337304
2     2021-11-02 22:15:00  8665.0  8665.0  8608.0  8632.0   19102  338177
3     2021-11-02 22:20:00  8631.0  8678.0  8629.0  8641.0   17734  336690
4     2021-11-02 22:25:00  8640.0  8647.0  8616.0  8627.0   13332  337347
...                   ...     ...     ...     ...     ...     ...     ...
1018  2021-11-23 14:40:00  8890.0  8892.0  8860.0  8867.0    4747  353682
1019  2021-11-23 14:45:00  8866.0  8890.0  8866.0  8866.0    3499  353777
1020  2021-11-23 14:50:00  8866.0  8867.0  8810.0  8810.0   11443  353624
1021  2021-11-23 14:55:00  8808.0  8829.0  8788.0  8801.0   13000  353442
1022  2021-11-23 15:00:00  8804.0  8808.0  8792.0  8808.0    7807  352899

[1023 rows x 7 columns]

Process finished with exit code 0

依旧会有Response [456]出现，我疑惑的是http的状态码似乎没有456的存在！
![20211123204235](https://user-images.githubusercontent.com/47621240/143026771-83f5ebd8-f708-4264-a667-c29dda5f644c.jpg)
