### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by Kinghts** [akfamily/akshare#1907]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本
2. Python 版本
3. AKShare 版本
4. 接口的名称和代码
get_futures_daily
5. 接口报错的截图或代码
获取郑商所的数据时2015-09-19 至 2017-12-27数据缺失
手动下载郑商所txt数据时发现：
2015-09-21 至 2015-11-11  CZCE_DAILY_URL_3  CZCE_DAILY_URL_2地址都可访问
2015-11-12 至 2017-12-27  CZCE_DAILY_URL_3地址获取到的txt文件为GBK编码，需要处理

自行修改了akshare/futures/futures_daily_bar.py文件：

184行开始
```
if day > datetime.date(2015, 11, 11):
            u = cons.CZCE_DAILY_URL_3
            url = u % (day.strftime("%Y"), day.strftime("%Y%m%d"))
        elif day <= datetime.date(2015, 11, 11):
            u = cons.CZCE_DAILY_URL_2
            url = u % (day.strftime("%Y"), day.strftime("%Y%m%d"))
        listed_columns = cons.CZCE_COLUMNS
        output_columns = cons.OUTPUT_COLUMNS
        try:
            r = requests.get(url)
            html = ""
            if (datetime.date(2015, 11, 12) <= day and day <= datetime.date(2017, 12, 27)):
                html = str(r.content, encoding="gbk")
            else:
                html = r.text
```
211行
```
if day > datetime.date(2015, 11, 11):
```
238行
```
elif day <= datetime.date(2015, 11, 11):
```
6. 期望获得的正确结果
正常获取到数据

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本
> 2. Python 版本
> 3. AKShare 版本
> 4. 接口的名称和代码
>    get_futures_daily
> 5. 接口报错的截图或代码
>    获取郑商所的数据时2015-09-19 至 2017-12-27数据缺失
>    手动下载郑商所txt数据时发现：
>    2015-09-21 至 2015-11-11  CZCE_DAILY_URL_3  CZCE_DAILY_URL_2地址都可访问
>    2015-11-12 至 2017-12-27  CZCE_DAILY_URL_3地址获取到的txt文件为GBK编码，需要处理
> 
> 自行修改了akshare/futures/futures_daily_bar.py文件：
> 
> 184行开始
> 
> ```
> if day > datetime.date(2015, 11, 11):
>             u = cons.CZCE_DAILY_URL_3
>             url = u % (day.strftime("%Y"), day.strftime("%Y%m%d"))
>         elif day <= datetime.date(2015, 11, 11):
>             u = cons.CZCE_DAILY_URL_2
>             url = u % (day.strftime("%Y"), day.strftime("%Y%m%d"))
>         listed_columns = cons.CZCE_COLUMNS
>         output_columns = cons.OUTPUT_COLUMNS
>         try:
>             r = requests.get(url)
>             html = ""
>             if (datetime.date(2015, 11, 12) <= day and day <= datetime.date(2017, 12, 27)):
>                 html = str(r.content, encoding="gbk")
>             else:
>                 html = r.text
> ```
> 
> 211行
> 
> ```
> if day > datetime.date(2015, 11, 11):
> ```
> 
> 238行
> 
> ```
> elif day <= datetime.date(2015, 11, 11):
> ```
> 
> 6. 期望获得的正确结果
>    正常获取到数据

感谢反馈问题及提供解决方案，请升级到 AKShare 1.2.43 版本，已修复
