### ISSUE TITLE
AKShare 接口问题报告  

### ISSUE THREAD

**Issue by pdwjzyjy** [akfamily/akshare#1909]
接口stock_us_hist   美股历史行情数据-东财  
查询105.LCID 这个股票的时候数据只有2021-7-26之后的数据

**Comment by jindaxiang** [comment]
> 

请查看数据源数据起止时间

**Comment by pdwjzyjy** [comment]
> > 
> 
> 请查看数据源数据起止时间

源数据是从2020年9月18日开始的

**Comment by jindaxiang** [comment]
> LCID

http://quote.eastmoney.com/us/LCID.html#fullScreenChart
