### ISSUE TITLE
ak.stock_individual_fund_flow

### ISSUE THREAD

**Issue by liusw02** [akfamily/akshare#1917]
stock_individual_fund_flow_df = ak.stock_individual_fund_flow(stock=Rd_C, market=St_E)
  File "C:\Users\aDmIn\AppData\Local\Programs\Python\Python36\lib\site-packages\akshare\stock\stock_fund.py", line 44, in stock_individual_fund_flow
    content_list = json_data["data"]["klines"]
TypeError: 'NoneType' object is not subscriptable

**Comment by jindaxiang** [comment]
> stock_individual_fund_flow_df = ak.stock_individual_fund_flow(stock=Rd_C, market=St_E) File "C:\Users\aDmIn\AppData\Local\Programs\Python\Python36\lib\site-packages\akshare\stock\stock_fund.py", line 44, in stock_individual_fund_flow content_list = json_data["data"]["klines"] TypeError: 'NoneType' object is not subscriptable

提供源代码

**Comment by liusw02** [comment]
运行 ak.stock_individual_fund_flow 示例 也错误

**Comment by jindaxiang** [comment]
> stock_individual_fund_flow

![image](https://user-images.githubusercontent.com/18234520/143578764-69949973-4881-45ad-96ec-47da75a3a86d.png)
