### ISSUE TITLE
其他应用可以调用这个项目的接口吗

### ISSUE THREAD

**Issue by hrj5032188** [akfamily/akshare#1932]
比如我用java或者go
能通过http请求的方式
来请求这个项目
获得相应的数据吗

**Comment by jindaxiang** [comment]
> 比如我用java或者go 能通过http请求的方式 来请求这个项目 获得相应的数据吗

需要在本地搭建一个 http 服务

**Comment by hrj5032188** [comment]
> > 比如我用java或者go可以通过http请求的方式来请求这个项目获得相应的数据吗
> 
> 需要在本地搭建一个http服务

如何搭建? 有文档吗
