### ISSUE TITLE
AKShare 接口问题报告：同花顺行业和概念两个接口失效

### ISSUE THREAD

**Issue by xnw176** [akfamily/akshare#1935]
**描述遇到的问题**
1. 操作系统版本：MAC OS 12.0.1
2. Python 版本：3.8
3. AKShare 版本：1.2.53
4. 接口的名称和代码
    1. stock_fund_flow_industry
    2. stock_fund_flow_concept
5. 接口报错的截图或代码
<img width="995" alt="image" src="https://user-images.githubusercontent.com/82297022/144335876-e26a808e-8975-4ec4-b6b6-9b316b52746d.png">

**Comment by jindaxiang** [comment]
> 1. stock_fund_flow_industry

经测试，该接口可以正常获取数据

**Comment by xnw176** [comment]
感谢，恢复了，估计是我早上时间段对方网站的问题。
