### ISSUE TITLE
AKShare 接口问题报告：乐估网相关接口因为乐估网证书过期导致无法调用如何破解。

### ISSUE THREAD

**Issue by xnw176** [akfamily/akshare#1936]
接口报错的截图或代码

<img width="703" alt="image" src="https://user-images.githubusercontent.com/82297022/144339801-f28f50ee-7a49-4f0a-bb18-2a304d96db3d.png">

<img width="981" alt="image" src="https://user-images.githubusercontent.com/82297022/144339841-4f8faac0-75a8-4802-9e4c-1a7db9b44a9c.png">

**Comment by jindaxiang** [comment]
> 接口报错的截图或代码
> 
> <img alt="image" width="703" src="https://user-images.githubusercontent.com/82297022/144339801-f28f50ee-7a49-4f0a-bb18-2a304d96db3d.png">
> 
> <img alt="image" width="981" src="https://user-images.githubusercontent.com/82297022/144339841-4f8faac0-75a8-4802-9e4c-1a7db9b44a9c.png">

该接口可以正常调用，并不存在您反馈问题。
![image](https://user-images.githubusercontent.com/18234520/144352639-7501c265-d87f-433b-9ecc-0d6110ee8c18.png)

**Comment by xnw176** [comment]
感谢，可以用了，看来今天的故障都是暂时性由对方网站造成的。
