### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by markzhang001** [akfamily/akshare#1940]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本
win10
2. Python 版本
3.8.8
3. AKShare 版本
1.1.82
4. 接口的名称和代码
stock_zh_a_tick_163
5. 接口报错的截图或代码
stock_zh_a_tick_tx_df = ak.stock_zh_a_tick_163(code="sh600848", trade_date="20211201")

返回结果如下：
C:\Anaconda3\envs\ak_test\python.exe D:/30_Python/ak_test/test.py
Empty DataFrame
Columns: [时间, 成交价, 价格变动, 成交量, 成交额, 性质]
Index: []

Process finished with exit code 0
6. 期望获得的正确结果
深市的code能返回数据，沪市的code都无数据（不管带不带sh字符）

**Comment by jindaxiang** [comment]
> 

建议您在数据源核对下是否数据源有数据，该接口目前是可以运行的
