### ISSUE TITLE
增加股票回购接口

### ISSUE THREAD

**Issue by markzhang001** [akfamily/akshare#1941]
**Is your feature request related to a problem? Please describe.**
是否能增加股票回购接口，谢谢！
**Describe the solution you'd like**
链接：https://data.eastmoney.com/gphg/
**Describe alternatives you've considered**

**Additional context**

**Comment by jindaxiang** [comment]
> **Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is. Ex. I'm always frustrated when [...] 是否能增加股票回购接口，谢谢！ **Describe the solution you'd like** A clear and concise description of what you want to happen. 链接：https://data.eastmoney.com/gphg/ **Describe alternatives you've considered** A clear and concise description of any alternative solutions or features you've considered.
> 
> **Additional context** Add any other context or screenshots about the feature request here.

感谢反馈数据源，已新增该接口 stock_repurchase_em，升级到 AKShare 1.2.55 使用
