### ISSUE TITLE
商品期货合约日期

### ISSUE THREAD

**Issue by edwardsun** [akfamily/akshare#1946]
您好，
首先非常感谢能提供akshare这样一个优秀的数据产品。
我想请问一下，有没有api函数提供期货合约（包括未退市合约）的上市日期/最后交易日/交割日等信息。比如：

symbol        listed date          last trading date
IF2206        2021-06-01        2022-06-01
JM0909      2008-09-01         2009-09-01

非常感谢

**Comment by jindaxiang** [comment]
> 您好， 首先非常感谢能提供akshare这样一个优秀的数据产品。 我想请问一下，有没有api函数提供期货合约（包括未退市合约）的上市日期/最后交易日/交割日等信息。比如：
> 
> symbol listed date last trading date IF2206 2021-06-01 2022-06-01 JM0909 2008-09-01 2009-09-01
> 
> 非常感谢

目前还没有，因为还没有合适的数据源提供这种数据
