### ISSUE TITLE
AKShare 接口问题报告  stock_board_concept_hist_ths

### ISSUE THREAD

**Issue by chenandjian** [akfamily/akshare#1948]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本 win10
2. Python 版本 3.8.8
3. AKShare 版本 1.2.57
4. 接口的名称和代码 stock_board_concept_hist_ths
5. 接口报错的截图或代码
Traceback (most recent call last):
  File "d:\work\pystockkiller\ak.py", line 202, in <module>
    df = ak.stock_board_concept_hist_ths(symbol=symbol)
  File "D:\software\ANACONDA3\lib\site-packages\akshare\stock_feature\stock_board_concept_ths.py", line 244, in stock_board_concept_hist_ths
    big_df.columns = [
  File "D:\software\ANACONDA3\lib\site-packages\pandas\core\generic.py", line 5478, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas\_libs\properties.pyx", line 66, in pandas._libs.properties.AxisProperty.__set__
  File "D:\software\ANACONDA3\lib\site-packages\pandas\core\generic.py", line 670, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "D:\software\ANACONDA3\lib\site-packages\pandas\core\internals\managers.py", line 220, in set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 12 elements, new values have 11 elements
6. 期望获得的正确结果 正确返回概念指数

![image](https://user-images.githubusercontent.com/2405009/144709128-2d6f7e05-5ec3-46ee-9003-5a280d825f13.png)

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本 win10
> 2. Python 版本 3.8.8
> 3. AKShare 版本 1.2.57
> 4. 接口的名称和代码 stock_board_concept_hist_ths
> 5. 接口报错的截图或代码
>    Traceback (most recent call last):
>    File "d:\work\pystockkiller\ak.py", line 202, in 
>    df = ak.stock_board_concept_hist_ths(symbol=symbol)
>    File "D:\software\ANACONDA3\lib\site-packages\akshare\stock_feature\stock_board_concept_ths.py", line 244, in stock_board_concept_hist_ths
>    big_df.columns = [
>    File "D:\software\ANACONDA3\lib\site-packages\pandas\core\generic.py", line 5478, in **setattr**
>    return object.**setattr**(self, name, value)
>    File "pandas_libs\properties.pyx", line 66, in pandas._libs.properties.AxisProperty.**set**
>    File "D:\software\ANACONDA3\lib\site-packages\pandas\core\generic.py", line 670, in _set_axis
>    self._mgr.set_axis(axis, labels)
>    File "D:\software\ANACONDA3\lib\site-packages\pandas\core\internals\managers.py", line 220, in set_axis
>    raise ValueError(
>    ValueError: Length mismatch: Expected axis has 12 elements, new values have 11 elements
> 6. 期望获得的正确结果 正确返回概念指数
> 
> ![image](https://user-images.githubusercontent.com/2405009/144709128-2d6f7e05-5ec3-46ee-9003-5a280d825f13.png)

感谢反馈问题，已修复该问题，请升级到 AKShare 1.2.58 使用

**Comment by chenandjian** [comment]
问题描述：这个数据源 是动态的，字段名长度 有11和12的
接口：stock_board_concept_hist_ths
重现： “EDR概念” 测试下

Traceback (most recent call last):
  File "g:\working\gitee\pystockkiller\ak.py", line 231, in <module>
    df_hist_ths = ak.stock_board_concept_hist_ths(symbol=symbol)
  File "D:\anaconda3\envs\test\lib\site-packages\akshare\stock_feature\stock_board_concept_ths.py", line 280, in stock_board_concept_hist_ths
    big_df.columns = [
  File "D:\anaconda3\envs\test\lib\site-packages\pandas\core\generic.py", line 5500, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas\_libs\properties.pyx", line 70, in pandas._libs.properties.AxisProperty.__set__
  File "D:\anaconda3\envs\test\lib\site-packages\pandas\core\generic.py", line 766, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "D:\anaconda3\envs\test\lib\site-packages\pandas\core\internals\managers.py", line 216, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "D:\anaconda3\envs\test\lib\site-packages\pandas\core\internals\base.py", line 57, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 11 elements, new values have 12 elements

**Comment by chenandjian** [comment]
> > **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> > ```
> > pip install akshare --upgrade  # Python 版本需要大于 3.7
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **描述遇到的问题**
> > 
> > 1. 操作系统版本 win10
> > 2. Python 版本 3.8.8
> > 3. AKShare 版本 1.2.57
> > 4. 接口的名称和代码 stock_board_concept_hist_ths
> > 5. 接口报错的截图或代码
> >    Traceback (most recent call last):
> >    File "d:\work\pystockkiller\ak.py", line 202, in
> >    df = ak.stock_board_concept_hist_ths(symbol=symbol)
> >    File "D:\software\ANACONDA3\lib\site-packages\akshare\stock_feature\stock_board_concept_ths.py", line 244, in stock_board_concept_hist_ths
> >    big_df.columns = [
> >    File "D:\software\ANACONDA3\lib\site-packages\pandas\core\generic.py", line 5478, in **setattr**
> >    return object.**setattr**(self, name, value)
> >    File "pandas_libs\properties.pyx", line 66, in pandas._libs.properties.AxisProperty.**set**
> >    File "D:\software\ANACONDA3\lib\site-packages\pandas\core\generic.py", line 670, in _set_axis
> >    self._mgr.set_axis(axis, labels)
> >    File "D:\software\ANACONDA3\lib\site-packages\pandas\core\internals\managers.py", line 220, in set_axis
> >    raise ValueError(
> >    ValueError: Length mismatch: Expected axis has 12 elements, new values have 11 elements
> > 6. 期望获得的正确结果 正确返回概念指数
> > 
> > ![image](https://user-images.githubusercontent.com/2405009/144709128-2d6f7e05-5ec3-46ee-9003-5a280d825f13.png)
> 
> 感谢反馈问题，已修复该问题，请升级到 AKShare 1.2.58 使用



> > **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> > ```
> > pip install akshare --upgrade  # Python 版本需要大于 3.7
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **描述遇到的问题**
> > 
> > 1. 操作系统版本 win10
> > 2. Python 版本 3.8.8
> > 3. AKShare 版本 1.2.57
> > 4. 接口的名称和代码 stock_board_concept_hist_ths
> > 5. 接口报错的截图或代码
> >    Traceback (most recent call last):
> >    File "d:\work\pystockkiller\ak.py", line 202, in
> >    df = ak.stock_board_concept_hist_ths(symbol=symbol)
> >    File "D:\software\ANACONDA3\lib\site-packages\akshare\stock_feature\stock_board_concept_ths.py", line 244, in stock_board_concept_hist_ths
> >    big_df.columns = [
> >    File "D:\software\ANACONDA3\lib\site-packages\pandas\core\generic.py", line 5478, in **setattr**
> >    return object.**setattr**(self, name, value)
> >    File "pandas_libs\properties.pyx", line 66, in pandas._libs.properties.AxisProperty.**set**
> >    File "D:\software\ANACONDA3\lib\site-packages\pandas\core\generic.py", line 670, in _set_axis
> >    self._mgr.set_axis(axis, labels)
> >    File "D:\software\ANACONDA3\lib\site-packages\pandas\core\internals\managers.py", line 220, in set_axis
> >    raise ValueError(
> >    ValueError: Length mismatch: Expected axis has 12 elements, new values have 11 elements
> > 6. 期望获得的正确结果 正确返回概念指数
> > 
> > ![image](https://user-images.githubusercontent.com/2405009/144709128-2d6f7e05-5ec3-46ee-9003-5a280d825f13.png)
> 
> 感谢反馈问题，已修复该问题，请升级到 AKShare 1.2.58 使用




问题描述：这个数据源 是动态的，字段名长度 有11和12的
接口：stock_board_concept_hist_ths
重现：概念名称： “EDR概念” 

Traceback (most recent call last):
File "g:\working\gitee\pystockkiller\ak.py", line 231, in
df_hist_ths = ak.stock_board_concept_hist_ths(symbol=symbol)
File "D:\anaconda3\envs\test\lib\site-packages\akshare\stock_feature\stock_board_concept_ths.py", line 280, in stock_board_concept_hist_ths
big_df.columns = [
File "D:\anaconda3\envs\test\lib\site-packages\pandas\core\generic.py", line 5500, in setattr
return object.setattr(self, name, value)
File "pandas_libs\properties.pyx", line 70, in pandas._libs.properties.AxisProperty.set
File "D:\anaconda3\envs\test\lib\site-packages\pandas\core\generic.py", line 766, in _set_axis
self._mgr.set_axis(axis, labels)
File "D:\anaconda3\envs\test\lib\site-packages\pandas\core\internals\managers.py", line 216, in set_axis
self._validate_set_axis(axis, new_labels)
File "D:\anaconda3\envs\test\lib\site-packages\pandas\core\internals\base.py", line 57, in _validate_set_axis
raise ValueError(

**Comment by jindaxiang** [comment]
> > > **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> > > ```
> > > pip install akshare --upgrade  # Python 版本需要大于 3.7
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > **描述遇到的问题**
> > > 
> > > 1. 操作系统版本 win10
> > > 2. Python 版本 3.8.8
> > > 3. AKShare 版本 1.2.57
> > > 4. 接口的名称和代码 stock_board_concept_hist_ths
> > > 5. 接口报错的截图或代码
> > >    Traceback (most recent call last):
> > >    File "d:\work\pystockkiller\ak.py", line 202, in
> > >    df = ak.stock_board_concept_hist_ths(symbol=symbol)
> > >    File "D:\software\ANACONDA3\lib\site-packages\akshare\stock_feature\stock_board_concept_ths.py", line 244, in stock_board_concept_hist_ths
> > >    big_df.columns = [
> > >    File "D:\software\ANACONDA3\lib\site-packages\pandas\core\generic.py", line 5478, in **setattr**
> > >    return object.**setattr**(self, name, value)
> > >    File "pandas_libs\properties.pyx", line 66, in pandas._libs.properties.AxisProperty.**set**
> > >    File "D:\software\ANACONDA3\lib\site-packages\pandas\core\generic.py", line 670, in _set_axis
> > >    self._mgr.set_axis(axis, labels)
> > >    File "D:\software\ANACONDA3\lib\site-packages\pandas\core\internals\managers.py", line 220, in set_axis
> > >    raise ValueError(
> > >    ValueError: Length mismatch: Expected axis has 12 elements, new values have 11 elements
> > > 6. 期望获得的正确结果 正确返回概念指数
> > > 
> > > ![image](https://user-images.githubusercontent.com/2405009/144709128-2d6f7e05-5ec3-46ee-9003-5a280d825f13.png)
> > 
> > 
> > 感谢反馈问题，已修复该问题，请升级到 AKShare 1.2.58 使用
> 
> > > **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> > > ```
> > > pip install akshare --upgrade  # Python 版本需要大于 3.7
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > **描述遇到的问题**
> > > 
> > > 1. 操作系统版本 win10
> > > 2. Python 版本 3.8.8
> > > 3. AKShare 版本 1.2.57
> > > 4. 接口的名称和代码 stock_board_concept_hist_ths
> > > 5. 接口报错的截图或代码
> > >    Traceback (most recent call last):
> > >    File "d:\work\pystockkiller\ak.py", line 202, in
> > >    df = ak.stock_board_concept_hist_ths(symbol=symbol)
> > >    File "D:\software\ANACONDA3\lib\site-packages\akshare\stock_feature\stock_board_concept_ths.py", line 244, in stock_board_concept_hist_ths
> > >    big_df.columns = [
> > >    File "D:\software\ANACONDA3\lib\site-packages\pandas\core\generic.py", line 5478, in **setattr**
> > >    return object.**setattr**(self, name, value)
> > >    File "pandas_libs\properties.pyx", line 66, in pandas._libs.properties.AxisProperty.**set**
> > >    File "D:\software\ANACONDA3\lib\site-packages\pandas\core\generic.py", line 670, in _set_axis
> > >    self._mgr.set_axis(axis, labels)
> > >    File "D:\software\ANACONDA3\lib\site-packages\pandas\core\internals\managers.py", line 220, in set_axis
> > >    raise ValueError(
> > >    ValueError: Length mismatch: Expected axis has 12 elements, new values have 11 elements
> > > 6. 期望获得的正确结果 正确返回概念指数
> > > 
> > > ![image](https://user-images.githubusercontent.com/2405009/144709128-2d6f7e05-5ec3-46ee-9003-5a280d825f13.png)
> > 
> > 
> > 感谢反馈问题，已修复该问题，请升级到 AKShare 1.2.58 使用
> 
> 问题描述：这个数据源 是动态的，字段名长度 有11和12的 接口：stock_board_concept_hist_ths 重现：概念名称： “EDR概念”
> 
> Traceback (most recent call last): File "g:\working\gitee\pystockkiller\ak.py", line 231, in df_hist_ths = ak.stock_board_concept_hist_ths(symbol=symbol) File "D:\anaconda3\envs\test\lib\site-packages\akshare\stock_feature\stock_board_concept_ths.py", line 280, in stock_board_concept_hist_ths big_df.columns = [ File "D:\anaconda3\envs\test\lib\site-packages\pandas\core\generic.py", line 5500, in setattr return object.setattr(self, name, value) File "pandas_libs\properties.pyx", line 70, in pandas._libs.properties.AxisProperty.set File "D:\anaconda3\envs\test\lib\site-packages\pandas\core\generic.py", line 766, in _set_axis self._mgr.set_axis(axis, labels) File "D:\anaconda3\envs\test\lib\site-packages\pandas\core\internals\managers.py", line 216, in set_axis self._validate_set_axis(axis, new_labels) File "D:\anaconda3\envs\test\lib\site-packages\pandas\core\internals\base.py", line 57, in _validate_set_axis raise ValueError(

Ok，我测试了几次是有这个问题，已修复该问题，请升级到 AKShare 1.2.61 使用
