### ISSUE TITLE
“中国-香港-宏观经济指标“接口名称拼写问题

### ISSUE THREAD

**Issue by shiningalehxb** [akfamily/akshare#1951]
**描述遇到的问题**
1. 操作系统版本 Windows 11
2. Python 版本 3.10.0
3. AKShare 版本 1.2.58
4. 接口的名称和代码  "marco_china_hk_cpi"  
 "marco_china_hk_cpi_ratio"
 "marco_china_hk_rate_of_unemployment" 
 "marco_china_hk_gbp" 
 "marco_china_hk_gbp_ratio"
 "marco_china_hk_building_volume" 
 "marco_china_hk_building_amount"
 "marco_china_hk_trade_diff_ratio" 
 "marco_china_hk_ppi"
5. 接口报错的截图或代码
![issue](https://user-images.githubusercontent.com/29780144/144777564-22cb342a-b257-4c18-81d8-8f8117104174.jpg)

6. 期望获得的正确结果 上述接口中的marco是否应变更为macro

**Comment by jindaxiang** [comment]
> **描述遇到的问题**
> 
> 1. 操作系统版本 Windows 11
> 2. Python 版本 3.10.0
> 3. AKShare 版本 1.2.58
> 4. 接口的名称和代码  "marco_china_hk_cpi"
>    "marco_china_hk_cpi_ratio"
>    "marco_china_hk_rate_of_unemployment"
>    "marco_china_hk_gbp"
>    "marco_china_hk_gbp_ratio"
>    "marco_china_hk_building_volume"
>    "marco_china_hk_building_amount"
>    "marco_china_hk_trade_diff_ratio"
>    "marco_china_hk_ppi"
> 5. 接口报错的截图或代码
>    ![issue](https://user-images.githubusercontent.com/29780144/144777564-22cb342a-b257-4c18-81d8-8f8117104174.jpg)
> 6. 期望获得的正确结果 上述接口中的marco是否应变更为macro

感谢反馈问题，已修复该问题，请升级到 AKShare 1.2.59 版本使用
