### ISSUE TITLE
AKShare 接口问题报告：同花顺技术指标接口stock_rank_cxd_ths问题报告～

### ISSUE THREAD

**Issue by xnw176** [akfamily/akshare#1961]
4. 接口的名称和代码
技术指标创新低接口stock_rank_cxd_ths，使用参数历史新低时，由于网页无返回数据直接出错，而不返回空字段，相关一系列的接口都可能存在相同问题。

5. 接口报错的截图或代码
网页
<img width="1156" alt="image" src="https://user-images.githubusercontent.com/82297022/145323774-388e69b8-4387-45ec-b2d9-e11b67217015.png">

<img width="1101" alt="image" src="https://user-images.githubusercontent.com/82297022/145324766-c47dc196-5b87-417b-801e-05bcb92dd14d.png">

报错代码
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/opt/anaconda3/lib/python3.8/site-packages/pandas/core/arrays/datetimes.py in objects_to_datetime64ns(data, dayfirst, yearfirst, utc, errors, require_iso8601, allow_object, allow_mixed)
   2186         try:
-> 2187             values, tz_parsed = conversion.datetime_to_datetime64(data.ravel("K"))
   2188             # If tzaware, these values represent unix timestamps, so we

~/opt/anaconda3/lib/python3.8/site-packages/pandas/_libs/tslibs/conversion.pyx in pandas._libs.tslibs.conversion.datetime_to_datetime64()

TypeError: Unrecognized value type: <class 'str'>

During handling of the above exception, another exception occurred:

ParserError                               Traceback (most recent call last)
/var/folders/dv/g2mblx1j2vx266qf70vnpvym0000gp/T/ipykernel_42197/4270130665.py in <module>
----> 1 hist_record_low_df = ak.stock_rank_cxd_ths(symbol = '历史新低')

~/opt/anaconda3/lib/python3.8/site-packages/akshare/stock_feature/stock_technology_ths.py in stock_rank_cxd_ths(symbol)
    143     big_df["涨跌幅"] = big_df["涨跌幅"].str.strip("%")
    144     big_df["换手率"] = big_df["换手率"].str.strip("%")
--> 145     big_df["前期低点日期"] = pd.to_datetime(big_df["前期低点日期"]).dt.date
    146     big_df["涨跌幅"] = pd.to_numeric(big_df["涨跌幅"])
    147     big_df["换手率"] = pd.to_numeric(big_df["换手率"])

~/opt/anaconda3/lib/python3.8/site-packages/pandas/core/tools/datetimes.py in to_datetime(arg, errors, dayfirst, yearfirst, utc, format, exact, unit, infer_datetime_format, origin, cache)
    885             result = arg.map(cache_array)
    886         else:
--> 887             values = convert_listlike(arg._values, format)
    888             result = arg._constructor(values, index=arg.index, name=arg.name)
    889     elif isinstance(arg, (ABCDataFrame, abc.MutableMapping)):

~/opt/anaconda3/lib/python3.8/site-packages/pandas/core/tools/datetimes.py in _convert_listlike_datetimes(arg, format, name, tz, unit, errors, infer_datetime_format, dayfirst, yearfirst, exact)
    399     assert format is None or infer_datetime_format
    400     utc = tz == "utc"
--> 401     result, tz_parsed = objects_to_datetime64ns(
    402         arg,
    403         dayfirst=dayfirst,

~/opt/anaconda3/lib/python3.8/site-packages/pandas/core/arrays/datetimes.py in objects_to_datetime64ns(data, dayfirst, yearfirst, utc, errors, require_iso8601, allow_object, allow_mixed)
   2191             return values.view("i8"), tz_parsed
   2192         except (ValueError, TypeError):
-> 2193             raise err
   2194 
   2195     if tz_parsed is not None:

~/opt/anaconda3/lib/python3.8/site-packages/pandas/core/arrays/datetimes.py in objects_to_datetime64ns(data, dayfirst, yearfirst, utc, errors, require_iso8601, allow_object, allow_mixed)
   2173     order: Literal["F", "C"] = "F" if flags.f_contiguous else "C"
   2174     try:
-> 2175         result, tz_parsed = tslib.array_to_datetime(
   2176             data.ravel("K"),
   2177             errors=errors,

~/opt/anaconda3/lib/python3.8/site-packages/pandas/_libs/tslib.pyx in pandas._libs.tslib.array_to_datetime()

~/opt/anaconda3/lib/python3.8/site-packages/pandas/_libs/tslib.pyx in pandas._libs.tslib.array_to_datetime()

~/opt/anaconda3/lib/python3.8/site-packages/pandas/_libs/tslib.pyx in pandas._libs.tslib._array_to_datetime_object()

~/opt/anaconda3/lib/python3.8/site-packages/pandas/_libs/tslib.pyx in pandas._libs.tslib._array_to_datetime_object()

~/opt/anaconda3/lib/python3.8/site-packages/pandas/_libs/tslibs/parsing.pyx in pandas._libs.tslibs.parsing.parse_datetime_string()

~/opt/anaconda3/lib/python3.8/site-packages/dateutil/parser/_parser.py in parse(timestr, parserinfo, **kwargs)
   1366         return parser(parserinfo).parse(timestr, **kwargs)
   1367     else:
-> 1368         return DEFAULTPARSER.parse(timestr, **kwargs)
   1369 
   1370 

~/opt/anaconda3/lib/python3.8/site-packages/dateutil/parser/_parser.py in parse(self, timestr, default, ignoretz, tzinfos, **kwargs)
    641 
    642         if res is None:
--> 643             raise ParserError("Unknown string format: %s", timestr)
    644 
    645         if len(res) == 0:

ParserError: Unknown string format: 无当前条件数据

**Comment by jindaxiang** [comment]
> 4\. stock_rank_cxd_ths

可以在获取数据时候加 try...except 来处理
