### ISSUE TITLE
期货收盘价 = 0

### ISSUE THREAD

**Issue by edwardsun** [akfamily/akshare#1971]
有很多日期，期货合约收盘价=0, 尽管成交量 > 0
get_futures_daily_df = ak.get_futures_daily(start_date='20211112', end_date='20211112', market='CZCE', index_bar=False)
bad_close = (get_futures_daily_df['close'] < 1 ) & ((get_futures_daily_df['volume'] > 0 ) )
print(get_futures_daily_df.loc[bad_close])

![image](https://user-images.githubusercontent.com/359830/145718174-2eee07d7-61c3-4a80-b09f-531280777ba3.png)

**Comment by jindaxiang** [comment]
> 20211112

是的，跟交易所数据是一致的；应该是该期货合约要到期了，比如 CF 是到期月的第十个交易日
