### ISSUE TITLE
AKShare 接口问题报告 sw_index_spot只获取部分申万一级行业数据

### ISSUE THREAD

**Issue by EdumndAra** [akfamily/akshare#1974]
1. 操作系统版本 win10 
2. Python 版本 3.83
3. AKShare 版本 1.2.69
4. 接口的名称和代码 sw_index_spot
import akshare as ak
sw_index_spot_df=ak.sw_index_spot()
sw_index_spot_df

	指数代码	指数名称	昨收盘	今开盘	成交额	最高价	最低价	最新价	成交量
0	801010	农林牧渔	3537.94	3527.57	15891964556.0	3558.07	3513.12	3537.5	1407036103
1	801030	基础化工	5098.16	5091.72	77299773985.0	5092.92	5050.13	5063.36	5225612479
2	801040	钢铁	3008.85	2998.38	14923076938.0	3002.66	2951.93	2953.7	2744984048
3	801050	有色金属	6129.97	6101.7	67182058185.0	6101.71	5970.01	5987.81	4430429149
4	801080	电子	5581.39	5571.29	88613872641.0	5600.16	5545.67	5581.49	4700859434
5	801110	家用电器	8180.35	8147.04	15341214550.0	8147.06	8011.19	8020.42	1017012168
6	801120	食品饮料	28492.4	28402.34	58770803861.0	28840.84	28339.09	28661.23	1375894984
7	801130	纺织服饰	1816.5	1813.72	6746480760.0	1813.72	1806.05	1809.0	962242118
8	801140	轻工制造	2773.47	2770.66	15145910707.0	2784.74	2765.13	2777.1	1508147141
9	801150	医药生物	11201.85	11205.9	67259075496.0	11324.48	11205.78	11282.76	3020728414
10	801160	公用事业	2543.33	2529.7	40740387358.0	2559.08	2515.67	2556.48	4804423889
11	801170	交通运输	2408.02	2396.98	21117305719.0	2396.98	2372.19	2375.63	2363665713
12	801180	房地产	3306.4	3299.05	16495188257.0	3299.08	3262.73	3267.78	2357090279
13	801200	商贸零售	3119.27	3106.51	11352993476.0	3117.13	3096.04	3113.13	1161678122
14	801210	社会服务	10583.47	10533.95	9349837635.0	10612.8	10526.29	10593.99	789266220
15	801230	综合	2591.51	2588.32	2042688762.0	2618.16	2585.95	2606.29	317981848
16	801710	建筑材料	8010.93	7968.84	15930513509.0	7968.91	7821.6	7827.68	993714365
17	801720	建筑装饰	2198.4	2194.83	25170278655.0	2194.83	2165.7	2170.41	3716690631
18	801730	电力设备	13380.86	13344.79	112973800585.0	13366.17	13246.23	13287.93	5280274800
19	801740	国防军工	1922.55	1918.17	37536127120.0	1961.57	1914.2	1947.26	1789907521
20	801750	计算机	5140.79	5129.44	71770247727.0	5210.81	5124.2	5209.68	5125210644
21	801760	传媒	690.14	690.66	59372582765.0	704.54	688.01	697.38	6637086516
22	801770	通信	2149.16	2144.09	22980114552.0	2171.91	2144.09	2171.9	1827787741
23	801780	银行	3636.68	3628.56	19335179885.0	3629.6	3577.88	3583.8	2170204827
24	801790	非银金融	1892.05	1881.71	41319338758.0	1890.94	1877.96	1881.54	3117554618
25	801880	汽车	7007.84	6975.49	58501480964.0	6975.49	6883.35	6910.15	4006450974
26	801890	机械设备	1771.98	1765.45	57656158475.0	1774.62	1762.05	1771.96	4437291605

**问题：只显示了27个行业，事实上由于申万一级行业调整，目前有31个行业**
解决方案：
更新
akshare.index.cons.sw_payload

**Comment by jindaxiang** [comment]
> 1. 操作系统版本 win10
> 2. Python 版本 3.83
> 3. AKShare 版本 1.2.69
> 4. 接口的名称和代码 sw_index_spot
>    import akshare as ak
>    sw_index_spot_df=ak.sw_index_spot()
>    sw_index_spot_df
>    指数代码	指数名称	昨收盘	今开盘	成交额	最高价	最低价	最新价	成交量
>    0	801010	农林牧渔	3537.94	3527.57	15891964556.0	3558.07	3513.12	3537.5	1407036103
>    1	801030	基础化工	5098.16	5091.72	77299773985.0	5092.92	5050.13	5063.36	5225612479
>    2	801040	钢铁	3008.85	2998.38	14923076938.0	3002.66	2951.93	2953.7	2744984048
>    3	801050	有色金属	6129.97	6101.7	67182058185.0	6101.71	5970.01	5987.81	4430429149
>    4	801080	电子	5581.39	5571.29	88613872641.0	5600.16	5545.67	5581.49	4700859434
>    5	801110	家用电器	8180.35	8147.04	15341214550.0	8147.06	8011.19	8020.42	1017012168
>    6	801120	食品饮料	28492.4	28402.34	58770803861.0	28840.84	28339.09	28661.23	1375894984
>    7	801130	纺织服饰	1816.5	1813.72	6746480760.0	1813.72	1806.05	1809.0	962242118
>    8	801140	轻工制造	2773.47	2770.66	15145910707.0	2784.74	2765.13	2777.1	1508147141
>    9	801150	医药生物	11201.85	11205.9	67259075496.0	11324.48	11205.78	11282.76	3020728414
>    10	801160	公用事业	2543.33	2529.7	40740387358.0	2559.08	2515.67	2556.48	4804423889
>    11	801170	交通运输	2408.02	2396.98	21117305719.0	2396.98	2372.19	2375.63	2363665713
>    12	801180	房地产	3306.4	3299.05	16495188257.0	3299.08	3262.73	3267.78	2357090279
>    13	801200	商贸零售	3119.27	3106.51	11352993476.0	3117.13	3096.04	3113.13	1161678122
>    14	801210	社会服务	10583.47	10533.95	9349837635.0	10612.8	10526.29	10593.99	789266220
>    15	801230	综合	2591.51	2588.32	2042688762.0	2618.16	2585.95	2606.29	317981848
>    16	801710	建筑材料	8010.93	7968.84	15930513509.0	7968.91	7821.6	7827.68	993714365
>    17	801720	建筑装饰	2198.4	2194.83	25170278655.0	2194.83	2165.7	2170.41	3716690631
>    18	801730	电力设备	13380.86	13344.79	112973800585.0	13366.17	13246.23	13287.93	5280274800
>    19	801740	国防军工	1922.55	1918.17	37536127120.0	1961.57	1914.2	1947.26	1789907521
>    20	801750	计算机	5140.79	5129.44	71770247727.0	5210.81	5124.2	5209.68	5125210644
>    21	801760	传媒	690.14	690.66	59372582765.0	704.54	688.01	697.38	6637086516
>    22	801770	通信	2149.16	2144.09	22980114552.0	2171.91	2144.09	2171.9	1827787741
>    23	801780	银行	3636.68	3628.56	19335179885.0	3629.6	3577.88	3583.8	2170204827
>    24	801790	非银金融	1892.05	1881.71	41319338758.0	1890.94	1877.96	1881.54	3117554618
>    25	801880	汽车	7007.84	6975.49	58501480964.0	6975.49	6883.35	6910.15	4006450974
>    26	801890	机械设备	1771.98	1765.45	57656158475.0	1774.62	1762.05	1771.96	4437291605
> 
> **问题：只显示了27个行业，事实上由于申万一级行业调整，目前有31个行业** 解决方案： 更新 akshare.index.cons.sw_payload

感谢反馈问题，已修复该问题，请升级到 AKShare 1.2.70 版本使用
