### ISSUE TITLE
AKShare 接口问题报告：nh_price_index南华指数部分无返回值

### ISSUE THREAD

**Issue by xnw176** [akfamily/akshare#2001]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本：MAC OS 12
2. Python 版本：3.8
3. AKShare 版本：1.2.87
4. 接口的名称和代码：nh_price_index
5. 接口报错的截图或代码
<img width="379" alt="image" src="https://user-images.githubusercontent.com/82297022/146722149-ee190c6b-3bbf-42d4-8c01-ca1875c2b1fb.png">

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本：MAC OS 12
> 2. Python 版本：3.8
> 3. AKShare 版本：1.2.87
> 4. 接口的名称和代码：nh_price_index
> 5. 接口报错的截图或代码
> 
> <img alt="image" width="379" src="https://user-images.githubusercontent.com/82297022/146722149-ee190c6b-3bbf-42d4-8c01-ca1875c2b1fb.png">

哪部分，麻烦提供下代码

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本：MAC OS 12
> 2. Python 版本：3.8
> 3. AKShare 版本：1.2.87
> 4. 接口的名称和代码：nh_price_index
> 5. 接口报错的截图或代码
> 
> <img alt="image" width="379" src="https://user-images.githubusercontent.com/82297022/146722149-ee190c6b-3bbf-42d4-8c01-ca1875c2b1fb.png">

已经对南华指数的接口做相关的修改，升级到 AKShare 1.2.88 使用。更新文档如下：https://www.akshare.xyz/data/futures/futures.html#id56
