### ISSUE TITLE
AKShare 接口问题报告 - fund_etf_hist_sina

### ISSUE THREAD

**Issue by scanfyu** [akfamily/akshare#2006]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本
2. Python 版本
3.9.5 
3. AKShare 版本
1.2.90
4. 接口的名称和代码

symbol = 'sh516690'
df = ak.fund_etf_hist_sina(symbol=symbol)

5. 接口报错的截图或代码
temp_df["date"] = pd.to_datetime(temp_df["date"]).dt.date
6. 期望获得的正确结果
无法取到etf hist时，直接返回None或者空的dataframe

**Comment by scanfyu** [comment]
建议直接返回None

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本
> 2. Python 版本
>    3.9.5
> 3. AKShare 版本
>    1.2.90
> 4. 接口的名称和代码
> 
> symbol = 'sh516690' df = ak.fund_etf_hist_sina(symbol=symbol)
> 
> 5. 接口报错的截图或代码
>    temp_df["date"] = pd.to_datetime(temp_df["date"]).dt.date
> 6. 期望获得的正确结果
>    无法取到etf hist时，直接返回None或者空的dataframe

已修复，升级到 AKShare 1.2.91 版本使用
