### ISSUE TITLE
希望开发同花顺个股行情接口～🙏

### ISSUE THREAD

**Issue by xnw176** [akfamily/akshare#2012]
链接：
http://q.10jqka.com.cn

截图：
![image](https://user-images.githubusercontent.com/82297022/147018137-6c707719-6c55-44a1-a248-060f18868acb.png)

需求说明：比目前的东财和新浪接口多了流通股数量，目前akshare还没有任何接口可以获取，非常感谢。

**Comment by jindaxiang** [comment]
> 链接： http://q.10jqka.com.cn
> 
> 截图： ![image](https://user-images.githubusercontent.com/82297022/147018137-6c707719-6c55-44a1-a248-060f18868acb.png)
> 
> 需求说明：比目前的东财和新浪接口多了流通股数量，目前akshare还没有任何接口可以获取，非常感谢。

升级到 AKShare 1.2.95，新增 stock_individual_info_em 接口来获取个股的流通股及市值，参考文档：https://www.akshare.xyz/data/stock/stock.html?highlight=stock_individual_info_em#id5

**Comment by xnw176** [comment]
您好，新增的stock_individual_info_em接口只能获取单只股票的相关信息。需要循环4000多次才能取完所有股票。
是否可以考虑开发同花顺的接口，这样仅需要调用一次接口。
万分感谢～

**Comment by jindaxiang** [comment]
同花顺接口也需要循环多次，暂不考虑
