### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by zfdcode** [akfamily/akshare#2013]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本 win10
2. Python 版本 3.8.11
3. AKShare 版本 1.2.94
4. 接口的名称和代码 ak.currency_hist(symbol="usd-jpy", start_date="20050101", end_date="20200117")
5. 接口报错的截图或代码 
59行
soup = BeautifulSoup(res.text, "lxml")
title = soup.find("h2", attrs={"class": "float_lang_base_1"}).get_text()

soup主要内容为 Please turn JavaScript on and reload the page
soup.find("h2", attrs={"class": "float_lang_base_1"}).get_text()因此报错

6. 期望获得的正确结果 无报错

**Comment by jindaxiang** [comment]
> 

按文档操作，该接口需要使用代理访问
