### ISSUE TITLE
AKShare 接口问题报告：stock_profit_forecast

### ISSUE THREAD

**Issue by xnw176** [akfamily/akshare#2017]
**描述遇到的问题**
1. 操作系统版本： MAC OS
2. Python 版本：3.8
3. AKShare 版本：1.2.96
4. 接口的名称和代码：stock_profit_forecast
5. 接口报错的截图或代码
取出数据和网页实际不符
网页截图
<img width="873" alt="image" src="https://user-images.githubusercontent.com/82297022/147179355-2e6520d7-f4f0-4128-a913-ba82a32adac1.png">
代码和取得数据
<img width="1005" alt="image" src="https://user-images.githubusercontent.com/82297022/147179474-3d82ec40-c39c-4c39-b3d5-624d828ac18d.png">

**Comment by jindaxiang** [comment]
> 4\. stock_profit_forecast

感谢反馈问题，已修复该问题，请升级到 AKShare 1.2.97 版本使用
