### ISSUE TITLE
是否能新增东财场内基金分时行情以及债转分时行情？

### ISSUE THREAD

**Issue by xingfukun** [akfamily/akshare#2024]
是否能新增东财场内基金分时行情以及债转分时行情？

**Comment by jindaxiang** [comment]
> 是否能新增东财场内基金分时行情以及债转分时行情？

没有合适的数据源

**Comment by jindaxiang** [comment]
> 是否能新增东财场内基金分时行情以及债转分时行情？

债转分时行情：bond_zh_hs_cov_min
