### ISSUE TITLE
生猪出厂价数据

### ISSUE THREAD

**Issue by lianghaoqiang** [akfamily/akshare#2028]
https://zhujia.zhuwang.cc/api/chartData?areaId=-1&aa=1640441920103 
这个接口是有提供生猪出场价数据的，能否提供下这个接口

**Comment by jindaxiang** [comment]
> https://zhujia.zhuwang.cc/api/chartData?areaId=-1&aa=1640441920103 这个接口是有提供生猪出场价数据的，能否提供下这个接口

提供下 web 具体的页面？我确认下数据

**Comment by lianghaoqiang** [comment]
https://zhujia.zhuwang.cc/  这个页面上的，生猪(外三元)、生猪(内三元)、生猪(土杂猪)这几个的图表数据，好像是最近一年的数据，不过日期好像只提供了起始日期。

**Comment by lianghaoqiang** [comment]
> > https://zhujia.zhuwang.cc/api/chartData?areaId=-1&aa=1640441920103 这个接口是有提供生猪出场价数据的，能否提供下这个接口
> 
> 提供下 web 具体的页面？我确认下数据

https://zhujia.zhuwang.cc/ 这个页面上的，生猪(外三元)、生猪(内三元)、生猪(土杂猪)这几个的图表数据，好像是最近一年的数据，不过日期好像只提供了起始日期。

**Comment by jindaxiang** [comment]
> > > https://zhujia.zhuwang.cc/api/chartData?areaId=-1&aa=1640441920103 这个接口是有提供生猪出场价数据的，能否提供下这个接口
> > 
> > 
> > 提供下 web 具体的页面？我确认下数据
> 
> https://zhujia.zhuwang.cc/ 这个页面上的，生猪(外三元)、生猪(内三元)、生猪(土杂猪)这几个的图表数据，好像是最近一年的数据，不过日期好像只提供了起始日期。

https://www.akshare.xyz/data/futures/futures.html?highlight=%E7%94%9F%E7%8C%AA#id61

**Comment by lianghaoqiang** [comment]
> > > > https://zhujia.zhuwang.cc/api/chartData?areaId=-1&aa=1640441920103 这个接口是有提供生猪出场价数据的，能否提供下这个接口
> > > 
> > > 
> > > 提供下 web 具体的页面？我确认下数据
> > 
> > 
> > https://zhujia.zhuwang.cc/ 这个页面上的，生猪(外三元)、生猪(内三元)、生猪(土杂猪)这几个的图表数据，好像是最近一年的数据，不过日期好像只提供了起始日期。
> 
> https://www.akshare.xyz/data/futures/futures.html?highlight=%E7%94%9F%E7%8C%AA#id61

出厂价和批发价不是一个数据。。
