### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by Jack-RiskMCode** [akfamily/akshare#2029]
在所有版本最新情况下，接口ak.stock_dzjy_sctj()出错了，显示akshare.utils.demjson.JSONDecodeError: Unexpected text after end of JSON value

**Comment by jindaxiang** [comment]
> 在所有版本最新情况下，接口ak.stock_dzjy_sctj()出错了，显示akshare.utils.demjson.JSONDecodeError: Unexpected text after end of JSON value

感谢反馈问题，已修复
