### ISSUE TITLE
AKShare 接口问题报告: stock_zh_a_hist_min_em

### ISSUE THREAD

**Issue by warscape** [akfamily/akshare#2040]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本
macOS 12.0.1

2. Python 版本
3.9

3. AKShare 版本
1.3.12

4. 接口的名称和代码
stock_zh_a_hist_min_em

5. 接口报错的截图或代码
6. 期望获得的正确结果
这个接口已不能正常获取数据，看了一下，貌似是东财只会返回最近一个半月的数据，超出这个范围的就取不到了。

**Comment by jindaxiang** [comment]
> 4\. stock_zh_a_hist_min_em

该接口只能获取近期的分时数据
