### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by callcter** [akfamily/akshare#2047]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本
macos
2. Python 版本
3.7.5
3. AKShare 版本
1.3.16
4. 接口的名称和代码
stock_sse_deal_daily
5. 接口报错的截图或代码
![image](https://user-images.githubusercontent.com/8223244/147709207-96bd5261-dbce-4c2c-bca5-94f5f6353aa3.png)

6. 期望获得的正确结果
正确返回数据

上交所好像是改版了，成交情况分成了两块
新数据（2021-12-27开始，http://www.sse.com.cn/market/stockdata/overview/day/），变成这样，列少了，所以报错
![image](https://user-images.githubusercontent.com/8223244/147709318-678d7796-4a43-476e-85ae-95fe45054246.png)

旧数据（2021-12-24及以前，http://www.sse.com.cn/market/stockdata/overview/day/index_his.shtml），跟接口格式一样，但是地址换了
![image](https://user-images.githubusercontent.com/8223244/147709387-2e5142dd-c254-405b-afa4-401184c689d5.png)

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本
>    macos
> 2. Python 版本
>    3.7.5
> 3. AKShare 版本
>    1.3.16
> 4. 接口的名称和代码
>    stock_sse_deal_daily
> 5. 接口报错的截图或代码
>    ![image](https://user-images.githubusercontent.com/8223244/147709207-96bd5261-dbce-4c2c-bca5-94f5f6353aa3.png)
> 6. 期望获得的正确结果
>    正确返回数据
> 
> 上交所好像是改版了，成交情况分成了两块 新数据（2021-12-27开始，[http://www.sse.com.cn/market/stockdata/overview/day/），变成这样，列少了，所以报错](http://www.sse.com.cn/market/stockdata/overview/day/%EF%BC%89%EF%BC%8C%E5%8F%98%E6%88%90%E8%BF%99%E6%A0%B7%EF%BC%8C%E5%88%97%E5%B0%91%E4%BA%86%EF%BC%8C%E6%89%80%E4%BB%A5%E6%8A%A5%E9%94%99) ![image](https://user-images.githubusercontent.com/8223244/147709318-678d7796-4a43-476e-85ae-95fe45054246.png)
> 
> 旧数据（2021-12-24及以前，[http://www.sse.com.cn/market/stockdata/overview/day/index_his.shtml），跟接口格式一样，但是地址换了](http://www.sse.com.cn/market/stockdata/overview/day/index_his.shtml%EF%BC%89%EF%BC%8C%E8%B7%9F%E6%8E%A5%E5%8F%A3%E6%A0%BC%E5%BC%8F%E4%B8%80%E6%A0%B7%EF%BC%8C%E4%BD%86%E6%98%AF%E5%9C%B0%E5%9D%80%E6%8D%A2%E4%BA%86) ![image](https://user-images.githubusercontent.com/8223244/147709387-2e5142dd-c254-405b-afa4-401184c689d5.png)

感谢反馈问题，已修复该问题，请升级 AKShare 到 1.3.17 版本使用

**Comment by callcter** [comment]
> 

2021-12-27 及之后的确是不行，已更新到最新版本，并且再次确认

**Comment by callcter** [comment]
> > **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> > ```
> > pip install akshare --upgrade  # Python 版本需要大于 3.7
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **描述遇到的问题**
> > 
> > 1. 操作系统版本
> >    macos
> > 2. Python 版本
> >    3.7.5
> > 3. AKShare 版本
> >    1.3.16
> > 4. 接口的名称和代码
> >    stock_sse_deal_daily
> > 5. 接口报错的截图或代码
> >    ![image](https://user-images.githubusercontent.com/8223244/147709207-96bd5261-dbce-4c2c-bca5-94f5f6353aa3.png)
> > 6. 期望获得的正确结果
> >    正确返回数据
> > 
> > 上交所好像是改版了，成交情况分成了两块 新数据（2021-12-27开始，[http://www.sse.com.cn/market/stockdata/overview/day/），变成这样，列少了，所以报错](http://www.sse.com.cn/market/stockdata/overview/day/%EF%BC%89%EF%BC%8C%E5%8F%98%E6%88%90%E8%BF%99%E6%A0%B7%EF%BC%8C%E5%88%97%E5%B0%91%E4%BA%86%EF%BC%8C%E6%89%80%E4%BB%A5%E6%8A%A5%E9%94%99) ![image](https://user-images.githubusercontent.com/8223244/147709318-678d7796-4a43-476e-85ae-95fe45054246.png)
> > 旧数据（2021-12-24及以前，[http://www.sse.com.cn/market/stockdata/overview/day/index_his.shtml），跟接口格式一样，但是地址换了](http://www.sse.com.cn/market/stockdata/overview/day/index_his.shtml%EF%BC%89%EF%BC%8C%E8%B7%9F%E6%8E%A5%E5%8F%A3%E6%A0%BC%E5%BC%8F%E4%B8%80%E6%A0%B7%EF%BC%8C%E4%BD%86%E6%98%AF%E5%9C%B0%E5%9D%80%E6%8D%A2%E4%BA%86) ![image](https://user-images.githubusercontent.com/8223244/147709387-2e5142dd-c254-405b-afa4-401184c689d5.png)
> 
> 感谢反馈问题，已修复该问题，请升级 AKShare 到 1.3.17 版本使用

2021-12-27 及之后的确是不行，已更新到最新版本，并且再次确认

**Comment by jindaxiang** [comment]
> 

![image](https://user-images.githubusercontent.com/18234520/147737625-bea6d49f-8cec-4132-aa11-08ad26a52b04.png)

**Comment by callcter** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/18234520/147737625-bea6d49f-8cec-4132-aa11-08ad26a52b04.png)

![image](https://user-images.githubusercontent.com/8223244/147834693-4317ba38-e047-42c3-8b9f-cc89d9b3d65d.png)
