### ISSUE TITLE
AKShare 接口问题报告 (stock_zh_index_daily_em)

### ISSUE THREAD

**Issue by tongkl1** [akfamily/akshare#2067]
https://github.com/akfamily/akshare/blob/1b9b1929bf9abf7d4fee62f6f1df0f181285ff98/akshare/index/zh_stock_index_sina.py#L244

stock_zh_index_daily_em请求的最后一天是20220101, 2022年的行情拉取不到

**Comment by jindaxiang** [comment]
> https://github.com/akfamily/akshare/blob/1b9b1929bf9abf7d4fee62f6f1df0f181285ff98/akshare/index/zh_stock_index_sina.py#L244
> 
> stock_zh_index_daily_em请求的最后一天是20220101, 2022年的行情拉取不到

感谢反馈问题，请升级到 AKShare 1.3.30 使用
