### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by minipower123** [akfamily/akshare#2069]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```
import akshare as ak
ak.get_futures_daily(start_date='2021-12-31', end_date='2022-01-04', market='SHFE', index_bar=False)
return nothing

ak.option_shfe_daily(trade_date='2022-01-04', symbol='原油期权')
C:\Software\Miniconda3\lib\site-packages\akshare\option\option_commodity.py:146: UserWarning: 20220104非交易日
  warnings.warn("%s非交易日" % day.strftime("%Y%m%d"))

**描述遇到的问题**
1. 操作系统版本
2. Python 版本
3. AKShare 版本
4. 接口的名称和代码
5. 接口报错的截图或代码
6. 期望获得的正确结果

**Comment by jindaxiang** [comment]
> 

感谢反馈问题，已修复该问题，请升级到 AKShare 1.3.30 使用
