### ISSUE TITLE
请求读取天天基金基金申购状态列表

### ISSUE THREAD

**Issue by xnw176** [akfamily/akshare#2075]
网页地址：
http://fund.eastmoney.com/Fund_sgzt_bzdm.html

页面截图：
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/82297022/148473174-c2715eb4-b332-476c-92ca-8a01400b8754.png">

需求说明：
获取基金起购点，限额，开放日等目前akshare库没有涵盖到的公募基金数据。

**Comment by jindaxiang** [comment]
> 网页地址： http://fund.eastmoney.com/Fund_sgzt_bzdm.html
> 
> 页面截图： <img alt="image" width="1004" src="https://user-images.githubusercontent.com/82297022/148473174-c2715eb4-b332-476c-92ca-8a01400b8754.png">
> 
> 需求说明： 获取基金起购点，限额，开放日等目前akshare库没有涵盖到的公募基金数据。

感谢反馈问题，已新增接口 fund_purchase_em，升级到 AKShare 1.3.35 使用
