### ISSUE TITLE
AKShare 接口问题报告：关于stock_financial_analysis_indicator

### ISSUE THREAD

**Issue by xiedane** [akfamily/akshare#2081]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```
你好！
我在使用“stock_financial_analysis_indicator”接口时，发现返回的数据参数与AKSHARE说明文档不符
文档中说明：（第一列“日期”参数）
“输出参数”：名称：“日期”，但输出数据中，该列没有列名（原来应该是“日期”）

**描述遇到的问题**
1. 操作系统版本
2. Python 版本
3. AKShare 版本
4. 接口的名称和代码
5. 接口报错的截图或代码
6. 期望获得的正确结果

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> 你好！ 我在使用“stock_financial_analysis_indicator”接口时，发现返回的数据参数与AKSHARE说明文档不符 文档中说明：（第一列“日期”参数） “输出参数”：名称：“日期”，但输出数据中，该列没有列名（原来应该是“日期”）
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本
> 2. Python 版本
> 3. AKShare 版本
> 4. 接口的名称和代码
> 5. 接口报错的截图或代码
> 6. 期望获得的正确结果

要升级到 AKShare 最新版
