### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by cp2phi** [akfamily/akshare#2097]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本：big sur
2. Python 版本：3.9.7
3. AKShare 版本：1.3.47
4. 接口的名称和代码

名称：fund_em_open_fund_info
代码
> fund_em_open_fund_info_df = ak.fund_em_open_fund_info(fund="000002", indicator="单位净值走势")
> print(fund_em_open_fund_info_df)

5. 接口报错的截图或代码

> Traceback (most recent call last):
>   File "/Users/chengping/PycharmProjects/pythonProject/test.py", line 4, in <module>
>     fund_em_open_fund_info_df = ak.fund_em_open_fund_info(fund="000002", indicator="单位净值走势")
>   File "/Users/chengping/PycharmProjects/pythonProject/venv/lib/python3.6/site-packages/akshare/fund/fund_em.py", line 136, in fund_em_open_fund_info
>     - 15
>   File "/Users/chengping/PycharmProjects/pythonProject/venv/lib/python3.6/site-packages/demjson.py", line 5699, in decode
>     return_stats=(return_stats or write_stats) )
>   File "/Users/chengping/PycharmProjects/pythonProject/venv/lib/python3.6/site-packages/demjson.py", line 4915, in decode
>     raise errors[0]
> demjson.JSONDecodeError: ('Unknown identifier', 'ml')

6. 期望获得的正确结果

应该是"000002"的数据找不到“Data_netWorthTrend”“Data_ACWorthTrend”，然后拼接jason出错。

**Comment by jindaxiang** [comment]
> 9\. 
> 
> >

感谢反馈问题，升级到 AKShare 1.3.49 版本，对没有数据的基金返回空 pd.DataFrame
