### ISSUE TITLE
申请东方财富沪深港通个股持有明细

### ISSUE THREAD

**Issue by xnw176** [akfamily/akshare#2103]
网址：（以兴业银行601166为例）
https://data.eastmoney.com/hsgtcg/StockHdDetail/601166.html

截图：（最长可统计60天的数据）
![image](https://user-images.githubusercontent.com/82297022/149270383-53181478-067b-464a-a6e2-4afbde5ba94e.png)

目的：明细可区分出真假外资实际加减仓情况。

万分感谢！

**Comment by jindaxiang** [comment]
> 网址：（以兴业银行601166为例） https://data.eastmoney.com/hsgtcg/StockHdDetail/601166.html
> 
> 截图：（最长可统计60天的数据） ![image](https://user-images.githubusercontent.com/82297022/149270383-53181478-067b-464a-a6e2-4afbde5ba94e.png)
> 
> 目的：明细可区分出真假外资实际加减仓情况。
> 
> 万分感谢！

该接口已经存在 ：stock_hsgt_individual_detail_em
