### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by wapffu** [akfamily/akshare#2105]
环境都没有问题  其他功能都正常 

就遇到一个申万行业成分股接口获取不了

这是一个二级行业代码
sw_index_cons_df = ak.sw_index_cons(index_code="801193")
print(sw_index_cons_df)

**Comment by jindaxiang** [comment]
> 环境都没有问题 其他功能都正常
> 
> 就遇到一个申万行业成分股接口获取不了
> 
> 这是一个二级行业代码 sw_index_cons_df = ak.sw_index_cons(index_code="801193") print(sw_index_cons_df)

该问题是数据源没有数据
