### ISSUE TITLE
希望增加新冠疫情历史高中低风险疫情地区数据

### ISSUE THREAD

**Issue by shyuan2019** [akfamily/akshare#2115]
您好，请问可以添加covid-19的隔离政策数据吗？现在的AKShare数据库内最接近的数据是事件数据-病患轨迹数据-下的风险等级项，该项记录了病患轨迹所处地区的高中低风险，但是该数据并没有包括当日所有的高中低风险地区。该病患数据对应的腾讯新冠疫情信息页是含有这些信息的。不知道您是否可以找到这些数据的历史数据，最好是2020年底及2021年全年的。

非常感谢您的帮助！

**Comment by jindaxiang** [comment]
> 腾讯新冠疫情信息页

目前没有找到合适的数据源，来汇聚各地的隔离政策数据

**Comment by shyuan2019** [comment]
您好，网上应该比较多信息源， 比如说这里：
http://www.gov.cn/fuwu/2021-10/23/content_5644511.htm
