### ISSUE TITLE
新冠疫情高中低风险地区数据源

### ISSUE THREAD

**Issue by shyuan2019** [akfamily/akshare#2117]
您好，以下地址可以找到新冠疫情的高中低风险地区数据。不知道是否可以加入到事件数据中。
http://bmfw.www.gov.cn/yqfxdjcx/risk.html
该网站也可以找到历史数据，比如
http://www.gov.cn/fuwu/2021-10/23/content_5644511.htm

非常感谢您的帮助！

**Comment by jindaxiang** [comment]
> 您好，以下地址可以找到新冠疫情的高中低风险地区数据。不知道是否可以加入到事件数据中。 http://bmfw.www.gov.cn/yqfxdjcx/risk.html 该网站也可以找到历史数据，比如 http://www.gov.cn/fuwu/2021-10/23/content_5644511.htm
> 
> 非常感谢您的帮助！

感谢反馈问题，升级到 AKShare 1.3.59 版本，新增 covid_19_risk_area 接口，查询最新的高中低风险地区数据，历史数据暂不能获取
