### ISSUE TITLE
郑州和大连交易所行情数据获取失败

### ISSUE THREAD

**Issue by honphenc** [akfamily/akshare#2118]
![image](https://user-images.githubusercontent.com/48957021/150259551-09369bde-4905-4a4d-8f04-42ea973beeb6.png)
![image](https://user-images.githubusercontent.com/48957021/150259642-13edb511-568f-41b9-8ea2-c55d3a23faa7.png)

**Comment by jindaxiang** [comment]
> ![image](https://user-images.githubusercontent.com/48957021/150259551-09369bde-4905-4a4d-8f04-42ea973beeb6.png) ![image](https://user-images.githubusercontent.com/48957021/150259642-13edb511-568f-41b9-8ea2-c55d3a23faa7.png)

可以正常获取数据
![image](https://user-images.githubusercontent.com/18234520/150304906-2c029ebe-02dd-4338-8473-504c9e594266.png)
