### ISSUE TITLE
AKShare 接口问题报告：stock_gdfx_free_holding_statistics_em  历史数据

### ISSUE THREAD

**Issue by wujiajie1110** [akfamily/akshare#2122]
**描述遇到的问题**
1. 操作系统版本 Windows
2. Python 版本 3.7
3. AKShare 版本 1.3.57
4. 接口的名称和代码: stock_gdfx_free_holding_statistics_em 
5. 接口报错的截图或代码
当我用 20210930 时我获得了超过 40000 条数据。
而当我运行
`ak.stock_gdfx_free_holding_statistics_em(date="20210630")`
我只得到了 4781 行数据，这跟我在网页端看到的数据条数是不同的，应该是有数据缺失。

6. 期望获得的正确结果
应该也有超过40000条结果

**Comment by jindaxiang** [comment]
> **描述遇到的问题**
> 
> 1. 操作系统版本 Windows
> 2. Python 版本 3.7
> 3. AKShare 版本 1.3.57
> 4. 接口的名称和代码: stock_gdfx_free_holding_statistics_em
> 5. 接口报错的截图或代码
>    当我用 20210930 时我获得了超过 40000 条数据。
>    而当我运行
>    `ak.stock_gdfx_free_holding_statistics_em(date="20210630")`
>    我只得到了 4781 行数据，这跟我在网页端看到的数据条数是不同的，应该是有数据缺失。
> 6. 期望获得的正确结果
>    应该也有超过40000条结果

该接口是正常的，请升级到最新版使用

**Comment by wujiajie1110** [comment]
已经升级到最新版1.3.68。

我把问题截图发一下吧：

![image](https://user-images.githubusercontent.com/9449362/150711289-e7ab88aa-bce9-4d3e-bd7c-c1756abb76d1.png)
首先我们可以看到，条数是远少于最新日期的，其次我们看统计次数最多的那一行，只有2次。

我们来看一下东方财富官方网站的截图：
![image](https://user-images.githubusercontent.com/9449362/150711381-5de290b7-75af-40b4-81a5-1fd67f5e8896.png)
![image](https://user-images.githubusercontent.com/9449362/150711412-13fe05ff-d74d-4abc-b8c1-f915f3180ebd.png)
总的应该是30660条数据。

**Comment by jindaxiang** [comment]
已修复，升级到 最新版 使用
