### ISSUE TITLE
stock_hsgt_board_rank_em接口失效

### ISSUE THREAD

**Issue by xnw176** [akfamily/akshare#2132]
skshare版本为最新
截图：
<img width="991" alt="image" src="https://user-images.githubusercontent.com/82297022/150664719-e4c8a2f6-d3da-4895-8d4d-3d3e320c8549.png">

**Comment by jindaxiang** [comment]
> skshare版本为最新 截图： <img alt="image" width="991" src="https://user-images.githubusercontent.com/82297022/150664719-e4c8a2f6-d3da-4895-8d4d-3d3e320c8549.png">

感谢反馈问题，升级到 AKShare 1.3.68 版本使用，已修复
