### ISSUE TITLE
stock_zh_index_daily返回结果没有amount， stock_zh_index_daily_tx返回结果没有volume

### ISSUE THREAD

**Issue by Twilightlee** [akfamily/akshare#2134]
**描述遇到的问题**
**stock_zh_index_daily返回结果没有amount**,
**stock_zh_index_daily_tx返回结果没有volume**,

1. 操作系统版本   **Window11 21H2**
2. Python 版本    **Python 3.10.2**
3. AKShare 版本 **1.3.60**

是数据源的问题么？

**Comment by jindaxiang** [comment]
> 

是的，跟数据源统一

**Comment by Twilightlee** [comment]
明白了，谢谢指点。
