### ISSUE TITLE
stock_history_dividend_detail() occurs an Error with the symbol "600032"

### ISSUE THREAD

**Issue by colin-woodson** [akfamily/akshare#2135]
**Describe the bug**
A error would be returned by function "stock_history_dividend_detail()".

**To Reproduce**
1. import akshare as ak
2. stock_history_dividend_detail_df = ak.stock_history_dividend_detail(symbol="600032", indicator="分红")
3. Occur the Error "dateutil.parser._parser.ParserError: Unknown string format: 暂时没有数据！"

**Expected behavior**
Error

**Screenshots**
![image](https://user-images.githubusercontent.com/8923065/150720638-a00f2665-c6f4-45f3-82c7-4e74d64ac3e0.png)

**Desktop (please complete the following information):**
 - OS: OpenEuler/Ubuntu
 - Version: akshare-1.3.68

**Comment by jindaxiang** [comment]
> **Describe the bug** A error would be returned by function "stock_history_dividend_detail()".
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. import akshare as ak
> 2. stock_history_dividend_detail_df = ak.stock_history_dividend_detail(symbol="600032", indicator="分红")
> 3. Occur the Error "dateutil.parser._parser.ParserError: Unknown string format: 暂时没有数据！"
> 
> **Expected behavior** Error
> 
> **Screenshots** ![image](https://user-images.githubusercontent.com/8923065/150720638-a00f2665-c6f4-45f3-82c7-4e74d64ac3e0.png)
> 
> **Desktop (please complete the following information):**
> 
> * OS: OpenEuler/Ubuntu
> * Version: akshare-1.3.68

感谢反馈问题，该股票暂无分红数据，已经在接口增加异常检测，升级到 AKShare 1.3.71 版本使用

**Comment by colin-woodson** [comment]
I'm looking forward to it. 
Thanks~
