### ISSUE TITLE
sw_index_daily_indicator接口失效

### ISSUE THREAD

**Issue by xnw176** [akfamily/akshare#2145]
截图：
<img width="501" alt="image" src="https://user-images.githubusercontent.com/82297022/151090999-27cb3094-a548-48c4-a9c1-d52102a67924.png">

**Comment by jindaxiang** [comment]
> 截图： <img alt="image" width="501" src="https://user-images.githubusercontent.com/82297022/151090999-27cb3094-a548-48c4-a9c1-d52102a67924.png">

申万指数的数据源网站暂时无法获取到数据
