### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by andongyan95** [akfamily/akshare#2166]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本 'Windows-10-10.0.19041-SP0'
2. Python 版本 '3.8.8 (default, Apr 13 2021, 15:08:03) [MSC v.1916 64 bit (AMD64)]'
3. AKShare 版本 akshare-1.3.94
4. 接口的名称和代码 ak.covid_19_risk_area()
5. 接口报错的截图或代码 AttributeError: module 'akshare' has no attribute 'covid_19_risk_area'
###
>>> import akshare as ak
>>> covid_19_risk_area_df = ak.covid_19_risk_area(symbol="高风险等级地区")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'akshare' has no attribute 'covid_19_risk_area'
###
6. 期望获得的正确结果 正常读取数据

**Comment by jindaxiang** [comment]
> 4\. covid_19_risk_area

感谢反馈问题，请升级到 AKShare 1.3.95 版本使用，已修复该问题

**Comment by andongyan95** [comment]
感谢修复，但是升级后仍不能正常读取数据

>>> import akshare as ak
>>> covid_19_risk_area_df = ak.covid_19_risk_area(symbol="高风险等级地区")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\akshare\event\covid.py", line 97, in covid_19_risk_area
    temp_df = temp_df.explode(['communitys'])
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py", line 7278, in explode
    raise ValueError("column must be a scalar")
ValueError: column must be a scalar
