### ISSUE TITLE
bond_china_close_return 接口错误

### ISSUE THREAD

**Issue by freelancerhc** [akfamily/akshare#2174]
bond_china_close_return() 接口返回数据里，没有日期数据，还有NaN，望修一下，谢谢！（已升级到最新的1.3.95了)
<img width="578" alt="Screen Shot 2022-02-02 at 16 48 15" src="https://user-images.githubusercontent.com/13825798/152121557-c9bba512-f312-4414-a843-4ce52c504737.png">

**Comment by jindaxiang** [comment]
> bond_china_close_return() 接口返回数据里，没有日期数据，还有NaN，望修一下，谢谢！（已升级到最新的1.3.95了) <img alt="Screen Shot 2022-02-02 at 16 48 15" width="578" src="https://user-images.githubusercontent.com/13825798/152121557-c9bba512-f312-4414-a843-4ce52c504737.png">

感谢反馈问题，已修复该问题，请升级到 AKShare 1.3.96 版本使用
