### ISSUE TITLE
能不能提供一个本地化的接口或者方案

### ISSUE THREAD

**Issue by neillee1991** [akfamily/akshare#2196]
大佬好，能不能提供一个数据本地化的方案？

**Comment by danielbill** [comment]
别作妖

**Comment by jindaxiang** [comment]
> 大佬好，能不能提供一个数据本地化的方案？

AKShare 只提供数据接口，本地化方案需要根据您的业务需求定制；后期会在文档更新数据存储的案例仅供参考
