### ISSUE TITLE
AKShare 接口问题报告  - 还是期货价格接口问题 futures_spot_price

### ISSUE THREAD

**Issue by danielbill** [akfamily/akshare#2198]
**描述遇到的问题**
1. 操作系统版本  win10
2. Python 版本  3.10
3. AKShare 版本 1.4.9
4. 接口的名称和代码 
生猪期货的价格和基差对调了,是不是生意社接口给的数据就有问题?
    df = ak.futures_spot_price('2022-02-09')
    for index, row in df.iterrows():
        log.debug(row)
5. 接口报错的截图或代码
接口疑似错误数据截图如下:
![image](https://user-images.githubusercontent.com/6269655/153356675-89364a1e-9b1a-4e96-a445-76a4255cda2d.png)

生意社数据如下:
![image](https://user-images.githubusercontent.com/6269655/153356711-968a18db-3805-4cfb-b011-57565a841722.png)

6. 期望获得的正确结果
spot_price  期望14735.0 , 实际13.77
dom_basis  期望-965 , 实际14721.23

**Comment by danielbill** [comment]
sorry ,我仔细检查了一下, 发现生意社的生猪现货价格,大概指的是 1KG的价格, 而它的基差值是用 现货价*100 - 主合约价格得出的.
所以这里的问题如果不是他们给错了数据,那么就是没有对现货价格*100导致的.

**Comment by jindaxiang** [comment]
> sorry ,我仔细检查了一下, 发现生意社的生猪现货价格,大概指的是 1KG的价格, 而它的基差值是用 现货价_100 - 主合约价格得出的. 所以这里的问题如果不是他们给错了数据,那么就是没有对现货价格_100导致的.

OK，里面 `ak.futures_spot_price('2022-02-09')` 该为 `ak.futures_spot_price('20220209')`
