### ISSUE TITLE
import AKShare 接口问题报告

### ISSUE THREAD

**Issue by michaeljerry456** [akfamily/akshare#2207]
AttributeError: 'NoneType' object has no attribute 'mr_free_context'

请问在导入时import akshare as ak 就遇到上述问题。
1.4.17
python 3.7
windows 19042.1526

**Comment by jindaxiang** [comment]
> 

AKShare 能正常运行，请检查您本地的环境配置是否合理。详情参考文档：https://www.akshare.xyz/installation.html

**Comment by michaeljerry456** [comment]
我是python（32位），请问是不是这个原因导致的？

**Comment by jindaxiang** [comment]
> 我是python（32位），请问是不是这个原因导致的？

必须 64 位才可以使用

**Comment by JackyUcode** [comment]
在导入时import akshare as ak 就遇到上述问题。
akshare:1.6.46
python: 3.10
MacOS:12.3---M1pro芯片
自己在按照官方提示：
大家下载使用：libmini_racer.dylib文件放到任意位置就可以使用，但是我无论是放到python的虚拟解释器环境中，还是放到py文件所在目录**都不成功。**
求解答，谢谢~

**Comment by karlzheng** [comment]
> 
把
https://jfds-1252952517.cos.ap-chengdu.myqcloud.com/akshare/software/pyminiracer/libmini_racer.dylib
放到提示的：`RuntimeError: Native library not available at /opt/homebrew/lib/python3.10/site-packages/py_mini_racer/libmini_racer.dylib`
的目录，就行
