### ISSUE TITLE
stock_em_jgdy_tj 接口的结果错误

### ISSUE THREAD

**Issue by andy001sun** [akfamily/akshare#2215]
**描述遇到的问题**
1. 操作系统版本：win10
2. Python 版本：3.10
3. AKShare 版本：1.3.99
4. 接口的名称和代码：stock_em_jgdy_tj
5. 接口报错的截图或代码
<img width="626" alt="image" src="https://user-images.githubusercontent.com/35391879/153861444-6e4db276-6b53-4c20-ae5a-3d341295b979.png">

6. 期望获得的正确结果：“最新价”和“涨跌幅”结果位置调换

**Comment by jindaxiang** [comment]
> **描述遇到的问题**
> 
> 1. 操作系统版本：win10
> 2. Python 版本：3.10
> 3. AKShare 版本：1.3.99
> 4. 接口的名称和代码：stock_em_jgdy_tj
> 5. 接口报错的截图或代码
> 
> <img alt="image" width="626" src="https://user-images.githubusercontent.com/35391879/153861444-6e4db276-6b53-4c20-ae5a-3d341295b979.png">
> 
> 6. 期望获得的正确结果：“最新价”和“涨跌幅”结果位置调换

感谢反馈问题，已修复该问题。该接口重命名为：stock_jgdy_tj_em，详情查看文档

**Comment by jindaxiang** [comment]
> **描述遇到的问题**
> 
> 1. 操作系统版本：win10
> 2. Python 版本：3.10
> 3. AKShare 版本：1.3.99
> 4. 接口的名称和代码：stock_em_jgdy_tj
> 5. 接口报错的截图或代码
> 
> <img alt="image" width="626" src="https://user-images.githubusercontent.com/35391879/153861444-6e4db276-6b53-4c20-ae5a-3d341295b979.png">
> 
> 6. 期望获得的正确结果：“最新价”和“涨跌幅”结果位置调换

升级到 AKShare 1.4.24 版本
