### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by chutiange** [akfamily/akshare#2222]
stock_info_sz_name_code接口参数错误

  params = {
      "SHOWTYPE": "xlsx",
      "CATALOGID": "1110",
      "TABKEY": indicator_map[indicator],
      "random": "0.6935816432433362",
  }

SHOWTYPE 应该是JSON

**Comment by jindaxiang** [comment]
> 

该接口可以正常运行，且 传入  JSON 会报错
