### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by hai-luo** [akfamily/akshare#2231]
stock_em_yysj 接口无法获取数据

**描述遇到的问题**
1. 操作系统版本  WIN10
2. Python 版本  3.7.0
3. AKShare 版本 1.4.33
4. 接口的名称和代码 stock_em_yysj 

ak.stock_em_yysj()

5. 接口报错的截图或代码
![image](https://user-images.githubusercontent.com/86064834/154808393-3c4416dd-14bb-4085-aaa8-e38beed95b0e.png)

6. 期望获得的正确结果
应该有返回数据

**Comment by jindaxiang** [comment]
> 

感谢反馈问题，已修复该问题同时修改该接口为：stock_yysj_em，详情请查看文档，升级到 AKShare 1.4.36 版本使用
