### ISSUE TITLE
stock_hsgt_individual_detail_em 接口问题报告

### ISSUE THREAD

**Issue by autoreleasepools** [akfamily/akshare#2233]
**描述遇到的问题**
1. 操作系统 WIN10
2. Python 3.8
3. AKShare 1.4.34
4. 接口的名称和代码
- 沪深港通持股-个股详情
- ak.stock_hsgt_individual_detail_em
5. 接口报错的截图或代码
![image](https://user-images.githubusercontent.com/47054100/154833229-3bd0edc8-6eae-4687-8653-576ea52559c5.png)
![屏幕截图 2022-02-20 154105](https://user-images.githubusercontent.com/47054100/154833286-420d1dbb-01e4-4ae5-b399-90cdedbef671.png)

6. 期望获得的正确结果
- 返回相关数据

**Comment by jindaxiang** [comment]
> * stock_hsgt_individual_detail_em

按文档说明提取，只能获取近期的数据，接口可以正常运行
