### ISSUE TITLE
给定股票能否获取该股对应的概念板块或行业板块？

### ISSUE THREAD

**Issue by Waterkin** [akfamily/akshare#2245]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jindaxiang** [comment]
> **Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> 
> **Describe the solution you'd like** A clear and concise description of what you want to happen.
> 
> **Describe alternatives you've considered** A clear and concise description of any alternative solutions or features you've considered.
> 
> **Additional context** Add any other context or screenshots about the feature request here.

还没有直接获取的接口，您可以参看文档，把多个接口组合使用

**Comment by Waterkin** [comment]
> > **Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> > **Describe the solution you'd like** A clear and concise description of what you want to happen.
> > **Describe alternatives you've considered** A clear and concise description of any alternative solutions or features you've considered.
> > **Additional context** Add any other context or screenshots about the feature request here.
> 
> 还没有直接获取的接口，您可以参看文档，把多个接口组合使用

谢谢！
