### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by andy001sun** [akfamily/akshare#2248]
**描述遇到的问题**
1. 操作系统版本: win10 
2. Python 版本: 3.10.1
3. AKShare 版本: 1.4.24
4. 接口的名称和代码: stock_em_dxsyl()
5. 接口报错的截图或代码:
<img width="619" alt="image" src="https://user-images.githubusercontent.com/35391879/155479547-1c70ee13-4e0b-4bd7-8cbb-21795e6ab716.png">

6. 期望获得的正确结果
目前“上海主板”、“创业板”可以获得数据，“深圳主板”无法获得数据；请修复下，谢谢

**Comment by jindaxiang** [comment]
> **描述遇到的问题**
> 
> 1. 操作系统版本: win10
> 2. Python 版本: 3.10.1
> 3. AKShare 版本: 1.4.24
> 4. 接口的名称和代码: stock_em_dxsyl()
> 5. 接口报错的截图或代码:
> 
> <img alt="image" width="619" src="https://user-images.githubusercontent.com/35391879/155479547-1c70ee13-4e0b-4bd7-8cbb-21795e6ab716.png">
> 
> 6. 期望获得的正确结果
>    目前“上海主板”、“创业板”可以获得数据，“深圳主板”无法获得数据；请修复下，谢谢

感谢反馈问题，已修复该问题，请升级到 AKShare 1.4.44 版本使用，同时修改该接口为：stock_dxsyl_em，详情请查询文档使用
