### ISSUE TITLE
希望提供接口变化列表

### ISSUE THREAD

**Issue by cxfans** [akfamily/akshare#2251]
更新之后，发现很多接口都没了，`stock_em_zt_pool`， `stock_em_zt_pool_zbgc`等，一时间也不知道现在变成了什么，能否提供列表？

**Comment by jindaxiang** [comment]
stock_em_zt_pool -> stock_zt_pool_em
stock_em_zt_pool_zbgc -> stock_zt_pool_zbgc_em

后续会统一所有接口，数据源标识会放在接口最后；
会在文档提供接口修改详情！

**Comment by jindaxiang** [comment]
> 更新之后，发现很多接口都没了，`stock_em_zt_pool`， `stock_em_zt_pool_zbgc`等，一时间也不知道现在变成了什么，能否提供列表？

后续接口修改信息，请参见：https://www.akshare.xyz/changelog.html
