### ISSUE TITLE
Import Error 

### ISSUE THREAD

**Issue by ZL221B** [akfamily/akshare#2260]
**Describe the bug**
It's print error when import the akshare

 - OS: Andriod
 - Version: 9
 - Termux + Ubuntu + Python3.9.7

**Additional context**

root@localhost:~# python3
Python 3.9.7 (default, Sep 10 2021, 14:59:43)
[GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import akshare
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/dist-packages/akshare/__init__.py", line 2188, in <module>
    from akshare.stock_feature.stock_ttm_lyr import stock_a_ttm_lyr
  File "/usr/local/lib/python3.9/dist-packages/akshare/stock_feature/stock_ttm_lyr.py", line 317, in <module>
    js_functions = py_mini_racer.MiniRacer()
  File "/usr/local/lib/python3.9/dist-packages/py_mini_racer/py_mini_racer.py", line 178, in __init__
    self.__class__.ext = _build_ext_handle()
  File "/usr/local/lib/python3.9/dist-packages/py_mini_racer/py_mini_racer.py", line 125, in _build_ext_handle
    raise RuntimeError("Native library not available at {}".format(EXTENSION_PATH))
RuntimeError: Native library not available at /usr/local/lib/python3.9/dist-packages/py_mini_racer/libmini_racer.glibc.so
>>>
>>> Ctrl + D
Exception ignored in: <function MiniRacer.__del__ at 0x7d77e29e50>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/py_mini_racer/py_mini_racer.py", line 315, in __del__
    self.ext.mr_free_context(getattr(self, "ctx", None))
AttributeError: 'NoneType' object has no attribute 'mr_free_context'
root@localhost:~#

**Comment by jindaxiang** [comment]
> **Describe the bug** A clear and concise description of what the bug is. It's print error when import the akshare
> 
> * OS: Andriod
> * Version: 9
> * Termux + Ubuntu + Python3.9.7
> 
> **Additional context** Add any other context about the problem here.
> 
> root@localhost:~# python3 Python 3.9.7 (default, Sep 10 2021, 14:59:43) [GCC 11.2.0] on linux Type "help", "copyright", "credits" or "license" for more information.
> 
> > > > import akshare
> > > > Traceback (most recent call last):
> > > > File "", line 1, in 
> > > > File "/usr/local/lib/python3.9/dist-packages/akshare/**init**.py", line 2188, in 
> > > > from akshare.stock_feature.stock_ttm_lyr import stock_a_ttm_lyr
> > > > File "/usr/local/lib/python3.9/dist-packages/akshare/stock_feature/stock_ttm_lyr.py", line 317, in 
> > > > js_functions = py_mini_racer.MiniRacer()
> > > > File "/usr/local/lib/python3.9/dist-packages/py_mini_racer/py_mini_racer.py", line 178, in **init**
> > > > self.**class**.ext = _build_ext_handle()
> > > > File "/usr/local/lib/python3.9/dist-packages/py_mini_racer/py_mini_racer.py", line 125, in _build_ext_handle
> > > > raise RuntimeError("Native library not available at {}".format(EXTENSION_PATH))
> > > > RuntimeError: Native library not available at /usr/local/lib/python3.9/dist-packages/py_mini_racer/libmini_racer.glibc.so
> > > > Ctrl + D
> > > > Exception ignored in: <function MiniRacer.**del** at 0x7d77e29e50>
> > > > Traceback (most recent call last):
> > > > File "/usr/local/lib/python3.9/dist-packages/py_mini_racer/py_mini_racer.py", line 315, in **del**
> > > > self.ext.mr_free_context(getattr(self, "ctx", None))
> > > > AttributeError: 'NoneType' object has no attribute 'mr_free_context'
> > > > root@localhost:~#

请严格安装文档要求进行安装，目前可以正常使用
