### ISSUE TITLE
AKShare 接口问题报告 请尽量保持接口名称稳定哈

### ISSUE THREAD

**Issue by danielbill** [akfamily/akshare#2269]
东财报表和东财快报的命名咋就变了呢.
今天刚刚更新了,结果就发现接口名变了. 
晕倒.
不算bug,不过请尽量保持函数名不变吧.
多谢了.

**Comment by jindaxiang** [comment]
> 东财报表和东财快报的命名咋就变了呢. 今天刚刚更新了,结果就发现接口名变了. 晕倒. 不算bug,不过请尽量保持函数名不变吧. 多谢了.

感谢反馈意见，一般不会修改接口，主要是规范接口的命名，如果对接口有修改，可以查看 https://www.akshare.xyz/changelog.html
