### ISSUE TITLE
所有股票的历史1分钟价格，成交量，成交额数据

### ISSUE THREAD

**Issue by liningbo** [akfamily/akshare#2270]
**Is your feature request related to a problem? Please describe.**
新浪分时接口，只能取最近20000条1分钟价格数据，东财分时接口，只返回最近5个交易日的1分钟数据。

**Describe the solution you'd like**
希望能支持查询某个交易日或者某一段时间的交易日的1分钟价格和成交量数据，能支持复权更好。

**Describe alternatives you've considered**

**Additional context**

**Comment by jindaxiang** [comment]
> **Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is. Ex. I'm always frustrated when [...] 新浪分时接口，只能取最近20000条1分钟价格数据，东财分时接口，只返回最近5个交易日的1分钟数据。
> 
> **Describe the solution you'd like** A clear and concise description of what you want to happen. 希望能支持查询某个交易日或者某一段时间的交易日的1分钟价格和成交量数据，能支持复权更好。
> 
> **Describe alternatives you've considered** A clear and concise description of any alternative solutions or features you've considered.
> 
> **Additional context** Add any other context or screenshots about the feature request here.

暂时没有相应的接口
