### ISSUE TITLE
希望index_detail_hist_cni 接口支持输入日期来获取历史成分股

### ISSUE THREAD

**Issue by liningbo** [akfamily/akshare#2276]
**Is your feature request related to a problem? Please describe.**

index_detail_hist_cni 目前只有指数代码这一个参数，会取各个月份的成分股信息，返回数据量太大。建议增加日期或者月份数据，只返回特定日期或者月份的成分股信息。我看国证官网是支持选择年月的。 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by liningbo** [comment]
我看了下，请求url是：http://www.cnindex.com.cn/sample-detail/detail?indexcode=399001&dateStr=2021-07&pageNum=1&rows=20
有 dateStr 参数，可以输入时间。分页参数不传的话，估计就是当前月份的全部成分股信息

**Comment by jindaxiang** [comment]
> **Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> 
> index_detail_hist_cni 目前只有指数代码这一个参数，会取各个月份的成分股信息，返回数据量太大。建议增加日期或者月份数据，只返回特定日期或者月份的成分股信息。我看国证官网是支持选择年月的。
> 
> **Describe the solution you'd like** A clear and concise description of what you want to happen.
> 
> **Describe alternatives you've considered** A clear and concise description of any alternative solutions or features you've considered.
> 
> **Additional context** Add any other context or screenshots about the feature request here.

感谢反馈问题，已修复该问题，新增 date 参数，升级到 AKShare 1.4.56 版本使用
