### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by ciwind** [akfamily/akshare#2284]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
macbook；python版本：3.7；akshare版本：1.4.60
stock_us_zh_spot接口调用失败，报错信息： list index out of range

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> **描述遇到的问题** macbook；python版本：3.7；akshare版本：1.4.60 stock_us_zh_spot接口调用失败，报错信息： list index out of range

请核对下数据源，应该是数据源目标网站没数据
