### ISSUE TITLE
东财和新浪股票的后复权数据不一致

### ISSUE THREAD

**Issue by liningbo** [akfamily/akshare#2287]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本
windows 10
2. Python 版本
3.8
3. AKShare 版本
1.4.59
4. 接口的名称和代码
stock_zh_a_hist
5. 接口报错的截图或代码
取600370的后复权数据，东财和新浪差别较大，新浪和其他家(掘金，聚宽)比较接近
东财的：
   日期     开盘     收盘     最高     最低     成交量          成交额     振幅   涨跌幅   涨跌额   
换手率
0     2015-12-07  30.97  32.64  32.79  30.50  137563  231829947.0   7.20  2.64  0.84  4.31
1     2015-12-08  32.93  32.46  32.95  30.95  148162  252130502.0   6.13 -0.55 -0.18  4.65
2     2015-12-09  31.99  34.24  35.45  31.53  196394  351068784.0  12.08  5.48  1.78  6.16
3     2015-12-10  33.85  30.97  34.33  30.97  233540  399713664.0   9.81 -9.55 -3.27  7.32
4     2015-12-11  30.25  28.74  30.43  28.03  231300  355677248.0   7.75 -7.20 -2.23  7.25
...          ...    ...    ...    ...    ...     ...          ...    ...   ...   ...   ...
1219  2020-12-25  15.68  15.68  15.77  15.41   26664    8101743.0   2.30  0.00  0.00  0.33
1220  2020-12-28  15.64  15.64  15.73  15.50   20708    6295283.0   1.47 -0.26 -0.04  0.26
1221  2020-12-29  15.68  15.41  15.68  15.32   36546   11012106.0   2.30 -1.47 -0.23  0.46
1222  2020-12-30  15.46  15.19  15.46  15.05   36593   10820928.0   2.66 -1.43 -0.22  0.46
1223  2020-12-31  15.23  15.68  15.68  15.19   36550   10990566.0   3.23  3.23  0.49  0.46

新浪的：
 date   open   high    low  close      volume  outstanding_share  turnover
0    2015-12-07  41.59  44.15  40.93  43.95  13756325.0        318897692.0  0.043137
1    2015-12-08  44.35  44.38  41.56  43.69  14816214.0        318897692.0  0.046461
2    2015-12-09  43.03  47.90  42.37  46.20  19639394.0        318897692.0  0.061585
3    2015-12-10  45.64  46.33  41.59  41.59  23354012.0        318897692.0  0.073234
4    2015-12-11  40.57  40.83  37.45  38.44  23130040.0        318897692.0  0.072531
...         ...    ...    ...    ...    ...         ...                ...       ...
1219 2020-12-25  20.02  20.15  19.62  20.02   2666415.0        797244230.0  0.003345
1220 2020-12-28  19.95  20.08  19.75  19.95   2070752.0        797244230.0  0.002597
1221 2020-12-29  20.02  20.02  19.49  19.62   3654602.0        797244230.0  0.004584
1222 2020-12-30  19.69  19.69  19.10  19.30   3659250.0        797244230.0  0.004590
1223 2020-12-31  19.36  20.02  19.30  20.02   3654953.0        797244230.0  0.004584
10. 期望获得的正确结果

我估计东财后复权不是从上市那天开始计算的，或者东财的接口有指定后复权日期的参数，不过我还没发现是否有参数可以指定复权日期

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本
>    windows 10
> 2. Python 版本
>    3.8
> 3. AKShare 版本
>    1.4.59
> 4. 接口的名称和代码
>    stock_zh_a_hist
> 5. 接口报错的截图或代码
>    取600370的后复权数据，东财和新浪差别较大，新浪和其他家(掘金，聚宽)比较接近
>    东财的：
>    日期     开盘     收盘     最高     最低     成交量          成交额     振幅   涨跌幅   涨跌额
>    换手率
>    0     2015-12-07  30.97  32.64  32.79  30.50  137563  231829947.0   7.20  2.64  0.84  4.31
>    1     2015-12-08  32.93  32.46  32.95  30.95  148162  252130502.0   6.13 -0.55 -0.18  4.65
>    2     2015-12-09  31.99  34.24  35.45  31.53  196394  351068784.0  12.08  5.48  1.78  6.16
>    3     2015-12-10  33.85  30.97  34.33  30.97  233540  399713664.0   9.81 -9.55 -3.27  7.32
>    4     2015-12-11  30.25  28.74  30.43  28.03  231300  355677248.0   7.75 -7.20 -2.23  7.25
>    ...          ...    ...    ...    ...    ...     ...          ...    ...   ...   ...   ...
>    1219  2020-12-25  15.68  15.68  15.77  15.41   26664    8101743.0   2.30  0.00  0.00  0.33
>    1220  2020-12-28  15.64  15.64  15.73  15.50   20708    6295283.0   1.47 -0.26 -0.04  0.26
>    1221  2020-12-29  15.68  15.41  15.68  15.32   36546   11012106.0   2.30 -1.47 -0.23  0.46
>    1222  2020-12-30  15.46  15.19  15.46  15.05   36593   10820928.0   2.66 -1.43 -0.22  0.46
>    1223  2020-12-31  15.23  15.68  15.68  15.19   36550   10990566.0   3.23  3.23  0.49  0.46
> 
> 新浪的： date open high low close volume outstanding_share turnover 0 2015-12-07 41.59 44.15 40.93 43.95 13756325.0 318897692.0 0.043137 1 2015-12-08 44.35 44.38 41.56 43.69 14816214.0 318897692.0 0.046461 2 2015-12-09 43.03 47.90 42.37 46.20 19639394.0 318897692.0 0.061585 3 2015-12-10 45.64 46.33 41.59 41.59 23354012.0 318897692.0 0.073234 4 2015-12-11 40.57 40.83 37.45 38.44 23130040.0 318897692.0 0.072531 ... ... ... ... ... ... ... ... ... 1219 2020-12-25 20.02 20.15 19.62 20.02 2666415.0 797244230.0 0.003345 1220 2020-12-28 19.95 20.08 19.75 19.95 2070752.0 797244230.0 0.002597 1221 2020-12-29 20.02 20.02 19.49 19.62 3654602.0 797244230.0 0.004584 1222 2020-12-30 19.69 19.69 19.10 19.30 3659250.0 797244230.0 0.004590 1223 2020-12-31 19.36 20.02 19.30 20.02 3654953.0 797244230.0 0.004584 10. 期望获得的正确结果
> 
> 我估计东财后复权不是从上市那天开始计算的，或者东财的接口有指定后复权日期的参数，不过我还没发现是否有参数可以指定复权日期

每家机构的计算方式不同，不建议混用数据
