### ISSUE TITLE
macro_china_swap_rate, bond_china_close_return接口问题报告

### ISSUE THREAD

**Issue by PuzzlingMojito** [akfamily/akshare#2296]
macro_china_swap_rate
bond_china_close_return
这几个我跑的都是document里面的样例，报document is empty或者长度mismatch，应该是爬取数据有问题。
看源代码这两个都是从中国货币网上爬的数据，应该是中国货币网有变动，麻烦您更新下

**Comment by jindaxiang** [comment]
> macro_china_swap_rate bond_china_close_return 这几个我跑的都是document里面的样例，报document is empty或者长度mismatch，应该是爬取数据有问题。 看源代码这两个都是从中国货币网上爬的数据，应该是中国货币网有变动，麻烦您更新下

感谢反馈问题，请升级到 AKShare 1.4.64 版本使用
