### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by forecasted** [akfamily/akshare#2304]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本
debian 11.0

2. Python 版本
python 3.9.7

3. AKShare 版本
akshare-1.4.66

4. 接口的名称和代码
>>> import akshare as ak
>>> names = ak.crypto_name_map()

5. 接口报错的截图或代码
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fw/miniconda3/envs/akshare/lib/python3.9/site-packages/akshare/crypto/crypto_hist_investing.py", line 32, in crypto_name_map
    soup = BeautifulSoup(r.json()["html"], "lxml")
  File "/home/fw/miniconda3/envs/akshare/lib/python3.9/site-packages/requests/models.py", line 899, in json
    return complexjson.loads(
  File "/home/fw/miniconda3/envs/akshare/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/home/fw/miniconda3/envs/akshare/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/fw/miniconda3/envs/akshare/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)

6. 期望获得的正确结果

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本
>    debian 11.0
> 2. Python 版本
>    python 3.9.7
> 3. AKShare 版本
>    akshare-1.4.66
> 4. 接口的名称和代码
> 
> > > > import akshare as ak
> > > > names = ak.crypto_name_map()
> 
> 5. 接口报错的截图或代码
>    Traceback (most recent call last):
>    File "", line 1, in 
>    File "/home/fw/miniconda3/envs/akshare/lib/python3.9/site-packages/akshare/crypto/crypto_hist_investing.py", line 32, in crypto_name_map
>    soup = BeautifulSoup(r.json()["html"], "lxml")
>    File "/home/fw/miniconda3/envs/akshare/lib/python3.9/site-packages/requests/models.py", line 899, in json
>    return complexjson.loads(
>    File "/home/fw/miniconda3/envs/akshare/lib/python3.9/json/**init**.py", line 346, in loads
>    return _default_decoder.decode(s)
>    File "/home/fw/miniconda3/envs/akshare/lib/python3.9/json/decoder.py", line 337, in decode
>    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>    File "/home/fw/miniconda3/envs/akshare/lib/python3.9/json/decoder.py", line 355, in raw_decode
>    raise JSONDecodeError("Expecting value", s, err.value) from None
>    json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
> 6. 期望获得的正确结果

感谢反馈问题，修复该问题，请升级到 AKShare 1.4.68 使用，注意该接口需要配合代理使用
