### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by michaeljerry456** [akfamily/akshare#2321]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
是
pip install akshare --upgrade  # Python 版本需要大于 3.7
3.9

**描述遇到的问题**
1. 操作系统版本 win10
2. Python 版本 3.9
3. AKShare 版本 1.4.23
4. 接口的名称和代码 全球指数
5. 接口报错的截图或代码 没有设置代理的原因报错
6. 期望获得的正确结果
 世界主要国家的各种指数, 该接口需要通过代理访问
 请问，能提供一个网上指导设置代理的链接吗？第三方收费的都行，谢谢！

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的** 是 pip install akshare --upgrade # Python 版本需要大于 3.7 3.9
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本 win10
> 2. Python 版本 3.9
> 3. AKShare 版本 1.4.23
> 4. 接口的名称和代码 全球指数
> 5. 接口报错的截图或代码 没有设置代理的原因报错
> 6. 期望获得的正确结果
>    世界主要国家的各种指数, 该接口需要通过代理访问
>    请问，能提供一个网上指导设置代理的链接吗？第三方收费的都行，谢谢！

您可以在网络上百度一下或者加群咨询下有没有相关小伙伴可以提供资料的

**Comment by michaeljerry456** [comment]
请给个群号，谢谢

**Comment by jindaxiang** [comment]
> 请给个群号，谢谢

可以联系小助手QQ加群:1254836886
