### ISSUE TITLE
关于性能方面的优化

### ISSUE THREAD

**Issue by ytian** [akfamily/akshare#2322]
**Is your feature request related to a problem? Please describe.**
有一些api的性能很差，例如：index_investing_global，我看了一下实现，里面有多次请求并不是针对数据，而是针对获取其他辅助的参数。当然，其他的api也存在类似的情况（例如，日行情的接口）。

**Describe the solution you'd like**
对这些性能差的接口增加缓存机制，例如：辅助参数数据可以通过另外的接口获取，并作为参数传入接口，以避免每次重复请求调用。这样可以大大提升性能。

**Describe alternatives you've considered**

**Additional context**

**Comment by jindaxiang** [comment]
> **Is your feature request related to a problem? Please describe.** 有一些api的性能很差，例如：index_investing_global，我看了一下实现，里面有多次请求并不是针对数据，而是针对获取其他辅助的参数。当然，其他的api也存在类似的情况（例如，日行情的接口）。
> 
> **Describe the solution you'd like** 对这些性能差的接口增加缓存机制，例如：辅助参数数据可以通过另外的接口获取，并作为参数传入接口，以避免每次重复请求调用。这样可以大大提升性能。
> 
> **Describe alternatives you've considered** A clear and concise description of any alternative solutions or features you've considered.
> 
> **Additional context** Add any other context or screenshots about the feature request here.

是的，会对部分接口增加缓存机制

**Comment by jindaxiang** [comment]
> **Is your feature request related to a problem? Please describe.** 有一些api的性能很差，例如：index_investing_global，我看了一下实现，里面有多次请求并不是针对数据，而是针对获取其他辅助的参数。当然，其他的api也存在类似的情况（例如，日行情的接口）。
> 
> **Describe the solution you'd like** 对这些性能差的接口增加缓存机制，例如：辅助参数数据可以通过另外的接口获取，并作为参数传入接口，以避免每次重复请求调用。这样可以大大提升性能。
> 
> **Describe alternatives you've considered** A clear and concise description of any alternative solutions or features you've considered.
> 
> **Additional context** Add any other context or screenshots about the feature request here.

已经在 index_investing_global 接口增加缓存，升级到 AKShare 1.4.78 版本使用，后续会对有需要的接口增加缓存
