### ISSUE TITLE
申请增加公募基金持仓重大变动

### ISSUE THREAD

**Issue by wujiajie1110** [akfamily/akshare#2324]
**Is your feature request related to a problem? Please describe.**
公募基金半年报或者年报公布的累计买入、卖出金额超出期初基金资产净值 2% 或前 20 名的股票明细。

**Describe the solution you'd like**
东财已经有该界面：
[http://fundf10.eastmoney.com/ccbd_003567.html](http://fundf10.eastmoney.com/ccbd_003567.html)

建议除了像东财这样从基金查询股票，可以增加从某个股票反查所有买卖该股票的基金的接口。
内部实现是同一套数据库上，写另一个SQL即可反查，不然用户需要先下载所有基金的重大变动，才能自行反查。

**Comment by jindaxiang** [comment]
> **Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is. Ex. I'm always frustrated when [...] 公募基金半年报或者年报公布的累计买入、卖出金额超出期初基金资产净值 2% 或前 20 名的股票明细。
> 
> **Describe the solution you'd like** A clear and concise description of what you want to happen. 东财已经有该界面： http://fundf10.eastmoney.com/ccbd_003567.html
> 
> 建议除了像东财这样从基金查询股票，可以增加从某个股票反查所有买卖该股票的基金的接口。 内部实现是同一套数据库上，写另一个SQL即可反查，不然用户需要先下载所有基金的重大变动，才能自行反查。

感谢反馈问题，升级到 AKShare 1.4.81 版本使用，新增：fund_portfolio_change_em
反查暂时不可行
