### ISSUE TITLE
stock_zh_a_hist_min_em 接口失效

### ISSUE THREAD

**Issue by zc1028** [akfamily/akshare#2335]
import akshare as ak

stock_zh_a_hist_min_em_df = ak.stock_zh_a_hist_min_em(symbol="000001", start_date="2021-09-01 09:32:00", end_date="2021-09-06 09:32:00", period='5', adjust='hfq')
print(stock_zh_a_hist_min_em_df)

返回
Empty DataFrame
Columns: [时间, 开盘, 收盘, 最高, 最低, 涨跌幅, 涨跌额, 成交量, 成交额, 振幅, 换手率]
Index: []

**Comment by jindaxiang** [comment]
> stock_zh_a_hist_min_em

该接口可以正常获取数据，请注意查看文档，只能获取近期的数据
