### ISSUE TITLE
cannot import name 'CachedSession' from 'requests_cache' 

### ISSUE THREAD

**Issue by shigubuhua** [akfamily/akshare#2339]
Python 3.10.2 (main, Jan 15 2022, 19:56:27) [GCC 11.1.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.1.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import akshare
No module named 'cattr'
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Input In [1], in <cell line: 1>()
----> 1 import akshare

File /usr/lib/python3.10/site-packages/akshare/__init__.py:2491, in <module>
   2486 from akshare.index.drewry_index import drewry_wci_index
   2488 """
   2489 柯桥指数
   2490 """
-> 2491 from akshare.index.index_kq_fz import index_kq_fz
   2492 from akshare.index.index_kq_ss import index_kq_fashion
   2494 """
   2495 问财-热门股票
   2496 """

File /usr/lib/python3.10/site-packages/akshare/index/index_kq_fz.py:11, in <module>
      8 import pandas as pd
      9 from tqdm import tqdm
---> 11 from akshare.utils.ak_session import session
     14 def index_kq_fz(symbol: str = "价格指数") -> pd.DataFrame:
     15     """
     16     中国柯桥纺织指数
     17     http://www.kqindex.cn/flzs/jiage
   (...)
     21     :rtype: pandas.DataFrame
     22     """

File /usr/lib/python3.10/site-packages/akshare/utils/ak_session.py:8, in <module>
      3 """
      4 Date: 2022/3/18 19:45
      5 Desc: 缓存工具
      6 """
      7 from datetime import timedelta
----> 8 from requests_cache import CachedSession
     10 session = CachedSession(
     11     'ak_cache',
     12     use_temp=True,
   (...)
     20     stale_if_error=False,               # In case of request errors, use stale cache data if possible
     21 )

ImportError: cannot import name 'CachedSession' from 'requests_cache' (/usr/lib/python3.10/site-packages/requests_cache/__init__.py)

**Comment by shigubuhua** [comment]
sorry. v1.4.84 is errror, but v1.4.86 is OK.

**Comment by jindaxiang** [comment]
> sorry. v1.4.84 is errror, but v1.4.86 is OK.

Ok, you should try `pip install `
That's fine
