### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by pfcstyle** [akfamily/akshare#2343]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本 win10
2. Python 版本 3.8.10
3. AKShare 版本 1.4.88
4. 接口的名称和代码 
```
ak.stock_us_hist(symbol='105.msft', period='daily', start_date='19000101', end_date=datetime.datetime.now().strftime('%Y%m%d'), adjust='')
```
5. 接口报错的截图或代码
测试了微软和苹果的接口，发现中间数据缺失。去了东方财富看了下，数据都是有的。
![image](https://user-images.githubusercontent.com/8980215/159730280-ee42363a-a504-4563-bd48-4b25fe6f68cd.png)

8. 期望获得的正确结果
2004到2007之间的完整数据

**Comment by jindaxiang** [comment]
> 105.msft

东财该数据是缺少的，请核对下
