### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by gigibang** [akfamily/akshare#2348]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本
2. Python 版本
3. AKShare 版本
4. 接口的名称和代码
5. 接口报错的截图或代码
6. 期望获得的正确结果

![image](https://user-images.githubusercontent.com/13517101/160027449-c2a5408e-764f-4e1b-a07b-58515f53d08f.png)
Having the Length mismatch: Expected axis has 3 elements, new values have 2 elements when getting stock detail by using ak.stock_individual_info_em(symbol="601816"). Any help is appreciated.

**Comment by jindaxiang** [comment]
> 601816

该接口可以正常运行，建议升级到最新版进行测试
