### ISSUE TITLE
希望接口增加startDate，endDate选项

### ISSUE THREAD

**Issue by haydengao** [akfamily/akshare#2361]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
东方财富的kline关键字接口，基本都是可以指定开始结束日期的，这样方便按需更新历史数据，例如bond_zh_hs_cov_min()中的：
url = 'https://push2his.eastmoney.com/api/qt/stock/kline/get'
        params = {
            'fields1': 'f1,f2,f3,f4,f5,f6',
            'fields2': 'f51,f52,f53,f54,f55,f56,f57,f58,f59,f60,f61',
            'ut': '7eea3edcaed734bea9cbfc24409ed989',
            'klt': period,
            'fqt': adjust_map[adjust],
            'secid': f"{market_type[symbol[:2]]}.{symbol[2:]}",
            'beg': '0',
            'end': '20500000',
            '_': '1630930917857',
        }
其中的beg=20200101，end=20220401，代表获取2020-1-1到2022-4-1的数据，类似的参数在其他的一些函数，例如stock_board_industry_hist_em()都可以如此修改，另外，这个分钟获取函数，还可以继续扩展到日线级别，只要设置klt参数的period变量为101

**Comment by jindaxiang** [comment]
> bond_zh_hs_cov_min

感谢反馈问题，后续会对相关接口增加开始和结束日期；日线级别以上的有另外的接口使用
