### ISSUE TITLE
stock_zh_a_spot & stock_zh_a_spot_em

### ISSUE THREAD

**Issue by xyLpf** [akfamily/akshare#2376]
The amount of data obtained by these two interfaces（stock_zh_a_spot & stock_zh_a_spot_em） is inconsistent.  

What is the difference ？

**Comment by jindaxiang** [comment]
> The amount of data obtained by these two interfaces（stock_zh_a_spot & stock_zh_a_spot_em） is inconsistent.
> 
> What is the difference ？

Yes, recommand you use stock_zh_a_spot_em interface

**Comment by xyLpf** [comment]
> > The amount of data obtained by these two interfaces（stock_zh_a_spot & stock_zh_a_spot_em） is inconsistent.
> > What is the difference ？
> 
> Yes, recommand you use stock_zh_a_spot_em interface

**Comment by xyLpf** [comment]
> > The amount of data obtained by these two interfaces（stock_zh_a_spot & stock_zh_a_spot_em） is inconsistent.
> > What is the difference ？
> 
> Yes, recommand you use stock_zh_a_spot_em interface

 I want to use "stock_zh_a_Hist_163", But the stock symbol prompts me to get it using 'ak.stock_zh_a_spot()' ,what to do next? thx!
