### ISSUE TITLE
air_quality_hist方法调用出错：akshare.utils.demjson.JSONDecodeError: No value to decode

### ISSUE THREAD

**Issue by zhoulexuan** [akfamily/akshare#2380]
air_quality_hist_df = air_quality_hist(
        city="杭州",
        period="day",
        start_date="20220101",
        end_date="20220305",
    )
    print(air_quality_hist_df)

错误信息：
akshare.utils.demjson.JSONDecodeError: No value to decode

**Comment by jindaxiang** [comment]
> air_quality_hist_df = air_quality_hist( city="杭州", period="day", start_date="20220101", end_date="20220305", ) print(air_quality_hist_df)
> 
> 错误信息： akshare.utils.demjson.JSONDecodeError: No value to decode

感谢反馈问题，已修复该问题，升级到 AKShare 1.5.9 版本使用
