### ISSUE TITLE
AKShare 可转债接口问题 没有返回所有数据

### ISSUE THREAD

**Issue by wangyu204** [akfamily/akshare#2381]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本  mac
2. Python 版本  3.8
3. AKShare 版本  1.5.8
4. 接口的名称和代码  bond_zh_hs_cov_spot
5. 接口报错的截图或代码
# 1.实时行情数据
df = ak.bond_zh_hs_cov_spot()
name = './csv/bond_zh_hs_cov_spot.csv'
df.to_csv(name, encoding="gbk", index=False)
print(df)
<img width="1108" alt="image" src="https://user-images.githubusercontent.com/8010411/162545611-f1d8cb05-6dd9-4994-a62a-55aad08a4d61.png">

7. 期望获得的正确结果  返回所有数据含有128145代码

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本  mac
> 2. Python 版本  3.8
> 3. AKShare 版本  1.5.8
> 4. 接口的名称和代码  bond_zh_hs_cov_spot
> 5. 接口报错的截图或代码
> 
> # 1.实时行情数据
> df = ak.bond_zh_hs_cov_spot() name = './csv/bond_zh_hs_cov_spot.csv' df.to_csv(name, encoding="gbk", index=False) print(df) <img alt="image" width="1108" src="https://user-images.githubusercontent.com/8010411/162545611-f1d8cb05-6dd9-4994-a62a-55aad08a4d61.png">
> 
> 7. 期望获得的正确结果  返回所有数据含有128145代码

目标网站：https://vip.stock.finance.sina.com.cn/mkt/#hskzz_z
没有日丰转债
接口暂时没发现问题

**Comment by wangyu204** [comment]
> > **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> > ```
> > pip install akshare --upgrade  # Python 版本需要大于 3.7
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **描述遇到的问题**
> > 
> > 1. 操作系统版本  mac
> > 2. Python 版本  3.8
> > 3. AKShare 版本  1.5.8
> > 4. 接口的名称和代码  bond_zh_hs_cov_spot
> > 5. 接口报错的截图或代码
> > 
> > # 1.实时行情数据
> > df = ak.bond_zh_hs_cov_spot() name = './csv/bond_zh_hs_cov_spot.csv' df.to_csv(name, encoding="gbk", index=False) print(df) <img alt="image" width="1108" src="https://user-images.githubusercontent.com/8010411/162545611-f1d8cb05-6dd9-4994-a62a-55aad08a4d61.png">
> > 
> > 7. 期望获得的正确结果  返回所有数据含有128145代码
> 
> 目标网站：https://vip.stock.finance.sina.com.cn/mkt/#hskzz_z 没有日丰转债 接口暂时没发现问题



> > **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> > ```
> > pip install akshare --upgrade  # Python 版本需要大于 3.7
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **描述遇到的问题**
> > 
> > 1. 操作系统版本  mac
> > 2. Python 版本  3.8
> > 3. AKShare 版本  1.5.8
> > 4. 接口的名称和代码  bond_zh_hs_cov_spot
> > 5. 接口报错的截图或代码
> > 
> > # 1.实时行情数据
> > df = ak.bond_zh_hs_cov_spot() name = './csv/bond_zh_hs_cov_spot.csv' df.to_csv(name, encoding="gbk", index=False) print(df) <img alt="image" width="1108" src="https://user-images.githubusercontent.com/8010411/162545611-f1d8cb05-6dd9-4994-a62a-55aad08a4d61.png">
> > 
> > 7. 期望获得的正确结果  返回所有数据含有128145代码
> 
> 目标网站：https://vip.stock.finance.sina.com.cn/mkt/#hskzz_z 没有日丰转债 接口暂时没发现问题

你试试目标地址按 代码排序，最大的那个就是日丰转债
