### ISSUE TITLE
请问可转债分钟级数据都是从2022年2月22日开始的吗?拿不到更早数据

### ISSUE THREAD

**Issue by OatLatte** [akfamily/akshare#2382]
已经安装akshare新版

问题已截图:
![issue](https://user-images.githubusercontent.com/103306071/162562922-f4696c32-f9cd-49de-83a6-c8296137958f.png)

**Comment by jindaxiang** [comment]
> 已经安装akshare新版
> 
> 问题已截图: ![issue](https://user-images.githubusercontent.com/103306071/162562922-f4696c32-f9cd-49de-83a6-c8296137958f.png)

是的，分时数据只能获取到近期的
