### ISSUE TITLE
stock_em_gpzy_pledge_ratio接口无返回数据

### ISSUE THREAD

**Issue by wjce** [akfamily/akshare#2385]
昨晚运行时有阵子是可以拉取2022.3.14以后的数据的，后来就不行了，接口返回是成功的，但是没有任何数据，换ip也一样
![image](https://user-images.githubusercontent.com/33532510/162595760-64c1ebcf-9735-476e-9ceb-b40ad4f0fa6f.png)

**Comment by jindaxiang** [comment]
> 昨晚运行时有阵子是可以拉取2022.3.14以后的数据的，后来就不行了，接口返回是成功的，但是没有任何数据，换ip也一样 ![image](https://user-images.githubusercontent.com/33532510/162595760-64c1ebcf-9735-476e-9ceb-b40ad4f0fa6f.png)

感谢反馈问题，已修复该问题，并且对接口重名，请参考 https://www.akshare.xyz/changelog.html 使用，其中数据的获取日期请按文档操作，升级到 AKShare 1.5.11 版本使用

**Comment by wjce** [comment]
> > 昨晚运行时有阵子是可以拉取2022.3.14以后的数据的，后来就不行了，接口返回是成功的，但是没有任何数据，换ip也一样 ![image](https://user-images.githubusercontent.com/33532510/162595760-64c1ebcf-9735-476e-9ceb-b40ad4f0fa6f.png)
> 
> 感谢反馈问题，已修复该问题，并且对接口重名，请参考 https://www.akshare.xyz/changelog.html 使用，其中数据的获取日期请按文档操作，升级到 AKShare 1.5.11 版本使用

现在升级到1.5.12了，还是不行，debug显示返回空数据
