### ISSUE TITLE
api-上市公司质押比例 报错，debug查看是404

### ISSUE THREAD

**Issue by wjce** [akfamily/akshare#2387]
`import os
import sys
curpath = os.path.abspath(os.path.dirname(__file__))
rootpath = os.path.split(curpath)[0]
print(rootpath)
sys.path.append(rootpath)

import time
import akshare as ak
import pandas as pd
import io
from database_util.db_env import save_to_default_postgre_replace

output = io.StringIO()
from sqlalchemy import types

# 上市公司质押比例（行业）
def save_update_data():
    save_db(stock_industry_data=requestData())
    return "sucess"

def save_db(stock_industry_data):
    table_name = 'stock_gpzy_industry_data'
    table_define = {
        'statistics_date': types.VARCHAR(20),
        'industry': types.DECIMAL(22, 10),
        'avg_pledge_rate': types.DECIMAL(22, 10),
        'company_num': types.DECIMAL(22, 10),
        'pledge_sum_num': types.DECIMAL(22, 10),
        'pledge_total': types.DECIMAL(22, 10),
        'pledge_new_pice': types.DECIMAL(22, 10),
    }

    try:
        save_to_default_postgre_replace(stock_industry_data, table_name, table_define)
        print('上市公司质押比例（行业）更新完毕')
    except Exception as e:
        print("error", e)
    finally:
        time.sleep(1)

def requestData():
    stock_industry_data = pd.DataFrame()
    stock_em_gpzy_industry_data_df = ak.stock_em_gpzy_industry_data()
    print(stock_em_gpzy_industry_data_df)

    stock_industry_data['statistics_date'] = stock_em_gpzy_industry_data_df['统计时间']
    stock_industry_data['industry'] = stock_em_gpzy_industry_data_df['行业']
    stock_industry_data['avg_pledge_rate'] = stock_em_gpzy_industry_data_df['平均质押比例(%)']
    stock_industry_data['company_num'] = stock_em_gpzy_industry_data_df['公司家数']
    stock_industry_data['pledge_sum_num'] = stock_em_gpzy_industry_data_df['质押总笔数']
    stock_industry_data['pledge_total'] = stock_em_gpzy_industry_data_df['质押总股本']
    stock_industry_data['pledge_new_pice'] = stock_em_gpzy_industry_data_df['最新质押市值']
    return stock_industry_data

if __name__ == '__main__':
    save_update_data()
    print('操作完成')`

**Comment by jindaxiang** [comment]
> stock_em_gpzy_industry_data
