### ISSUE TITLE
stock_gpzy_pledge_ratio_em返回空数据

### ISSUE THREAD

**Issue by wjce** [akfamily/akshare#2401]
![image](https://user-images.githubusercontent.com/33532510/163173943-f53ad0ee-bca7-4886-8578-200246fd24e0.png)

**Comment by jindaxiang** [comment]
> ![image](https://user-images.githubusercontent.com/33532510/163173943-f53ad0ee-bca7-4886-8578-200246fd24e0.png)

可以正常访问
