### ISSUE TITLE
AKShare-问题报告

### ISSUE THREAD

**Issue by Aoseala** [akfamily/akshare#2409]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. windows & ubuntu
2. python 3.8 & 3.10
3. AKShare 版本  akshare-1.5.22
4. 接口的名称和代码  stock_board_concept_name_em    &   stock_board_industry_hist_em

Traceback (most recent call last):
  File "pandas\_libs\lib.pyx", line 2315, in pandas._libs.lib.maybe_convert_numeric
ValueError: Unable to parse string "-"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\pyproject\download_em_concept.py", line 23, in <module>
    stock_board_concept_name_em_df = ak.stock_board_concept_name_em()
    temp_df["最新价"] = pd.to_numeric(temp_df["最新价"])
  File "D:\Program Files\Python310\lib\site-packages\pandas\core\tools\numeric.py", line 184, in to_numeric
    values, _ = lib.maybe_convert_numeric(
  File "pandas\_libs\lib.pyx", line 2357, in pandas._libs.lib.maybe_convert_numeric
ValueError: Unable to parse string "-" at position 0

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> **描述遇到的问题**
> 
> 1. windows & ubuntu
> 2. python 3.8 & 3.10
> 3. AKShare 版本  akshare-1.5.22
> 4. 接口的名称和代码  stock_board_concept_name_em    &   stock_board_industry_hist_em
> 
> Traceback (most recent call last): File "pandas_libs\lib.pyx", line 2315, in pandas._libs.lib.maybe_convert_numeric ValueError: Unable to parse string "-"
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "d:\pyproject\download_em_concept.py", line 23, in stock_board_concept_name_em_df = ak.stock_board_concept_name_em() temp_df["最新价"] = pd.to_numeric(temp_df["最新价"]) File "D:\Program Files\Python310\lib\site-packages\pandas\core\tools\numeric.py", line 184, in to_numeric values, _ = lib.maybe_convert_numeric( File "pandas_libs\lib.pyx", line 2357, in pandas._libs.lib.maybe_convert_numeric ValueError: Unable to parse string "-" at position 0

感谢反馈问题，这两个接口运行正常，可以正常使用
