### ISSUE TITLE
stock_comment_em 接口仍有问题

### ISSUE THREAD

**Issue by quanplex** [akfamily/akshare#2417]
在akshare最新版 1.5.26 中 调用 stock_comment_em 可顺利读取千股千评数据。但最新版的千股千评数据和之前版本下载的不一样，和东方财富的源数据也不一样，新下载数据少了三的变量列：分别是 涨跌幅，换手率，市盈率 ，同时还少了时间戳这一列。谢谢！

**Comment by jindaxiang** [comment]
> stock_comment_em

感谢反馈问题，已修复该问题，升级到 AKShare 1.5.27 版本使用
