### ISSUE TITLE
bond_zh_cov response 500

### ISSUE THREAD

**Issue by scanfyu** [akfamily/akshare#2418]
**Describe the bug**

**To Reproduce**
直接调用接口 ak.bond_zh_cov  报错 response 500

**Expected behavior**
正常调用接口并返回目标页 http://data.eastmoney.com/kzz/default.html 的数据

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows10]
 - Version [1.5.23]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jindaxiang** [comment]
> bond_zh_cov

感谢反馈问题，已修复该问题。升级到 AKShare 1.5.28 版本使用。
