### ISSUE TITLE
index_zh_a_hist_min_em 指数历史分时接口出错

### ISSUE THREAD

**Issue by kzerozero0** [akfamily/akshare#2419]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. windows
2. Python 3.9
3. AKShare 1.4.53
4. 分时行情数据，index_zh_a_hist_min_em
5.
第一个问题，该接口无法获取创业板，深证中指等指数的数据。 
```
index_zh_a_hist_min_em(symbol='399006', period="5", start_date="2022-04-15 09:32:00", end_date="2022-04-15 15:00:00")  

H:\workspace\jupyter\emotional\mytest.py in index_zh_a_hist_min_em(symbol, period, start_date, end_date)
    264         url = "http://push2his.eastmoney.com/api/qt/stock/kline/get"
    265         params = {
--> 266             #"secid": f"{code_id_dict[symbol]}.{symbol}",
    267             "secid": f"1.{symbol}",
    268             "ut": "7eea3edcaed734bea9cbfc24409ed989",
KeyError: '399006'
```
获取创业板指数出错。

在index_zh_a_hist_min_em接口所在文件中，添加两行代码绕过了这个问题，

```
85   code_id_dict['399006'] = 0
86  code_id_dict['399001'] = 0
```

第二个问题。该接口获取历史1分钟数据出错，每根1分钟数据的“开盘” 都是0.0. 同样的问题也出现在股票历史分时接口 stock_zh_a_hist_min_em上。

···
In [28]: index_zh_a_hist_df = ak.index_zh_a_hist_min_em(symbol="000016", period="1", start_date="1979-09-01 09:32:00", end_date="2222 
    ...: -01-01 09:32:00")

In [29]: index_zh_a_hist_df.head(5)
Out[29]: 
                    时间   开盘      收盘      最高      最低     成交量           成交额  \
0  2022-04-11 09:30:00 0.00 2908.54 2925.49 2908.54  308687  589996064.00
1  2022-04-11 09:31:00 0.00 2896.57 2908.54 2895.64  773538 1472991168.00
···

**Comment by jindaxiang** [comment]
> 399006

感谢反馈问题，已修复问题1；问题2是由于数据源导致的，建议获取最近交易日的数据；
升级到AKShare 1.5.29 版本使用
