### ISSUE TITLE
增添实时指标或每日指标接口

### ISSUE THREAD

**Issue by kzerozero0** [akfamily/akshare#2420]
增加一个接口获取所有股票某日的pe, pb, ps, 总市值，流通市值。就像tushare 中的 ```daily_basic```,  [https://tushare.pro/document/2?doc_id=32](url)

**Comment by jindaxiang** [comment]
> 增加一个接口获取所有股票某日的pe, pb, ps, 总市值，流通市值。就像tushare 中的 `daily_basic`, [https://tushare.pro/document/2?doc_id=32](url)

感谢反馈问题，有合适的数据源会新增
