### ISSUE TITLE
AKShare 接口问题报告ak.bond_zh_cov()

### ISSUE THREAD

**Issue by xnw176** [akfamily/akshare#2422]
**描述遇到的问题**
1. 操作系统版本   MAC OS 12.3
2. Python 版本 3.8
3. AKShare 版本. 1.5.26
4. 接口的名称和代码 ak.bond_zh_cov()
5. 接口报错的截图或代码
<img width="1007" alt="image" src="https://user-images.githubusercontent.com/82297022/163676466-2e30555d-9798-42e8-872e-89a6a47615ce.png">

**Comment by jindaxiang** [comment]
> 4\. bond_zh_cov

已修复该问题，升级到 AKShare 1.5.29 版本使用
