### ISSUE TITLE
日线接口获取的数据对不上

### ISSUE THREAD

**Issue by zevichen** [akfamily/akshare#2425]
1. 操作系统版本
<img width="670" alt="image" src="https://user-images.githubusercontent.com/9278899/163678406-17944311-87e7-4ec7-ba7a-23a7cbd3e6a5.png">

2. Python 版本
3. AKShare 版本
<img width="289" alt="image" src="https://user-images.githubusercontent.com/9278899/163678389-b31709a9-211d-4da9-94ce-a735a9f64d03.png">

4. 接口的名称和代码
```python
# 日线行情K线数据
futures_daily = ak.get_futures_daily(start_date="20220401", end_date="20220415", market="SHFE", index_bar=True)
futures_daily[futures_daily['symbol']=='FU2209']
```
5. 接口报错的截图或代码

- 接口获取数据：

<img width="937" alt="image" src="https://user-images.githubusercontent.com/9278899/163678503-571909f4-1e1d-4361-abf5-2f3008e8faa7.png">

- [上期交易所数据](http://www.shfe.com.cn/statements/dataview.html?paramid=delaymarket_fu)：

<img width="720" alt="image" src="https://user-images.githubusercontent.com/9278899/163678673-3de9dbda-8f23-404a-9a8c-982547338470.png">

6. 期望获得的正确结果

如果获取的是上期官网数据，这个结果是对不上的，我也对比了文华里面的数据，跟上期发布的交易数据是吻合的，所以只能是接口数据有问题。

**Comment by jindaxiang** [comment]
> ```python
> 20220415
> ```

数据是一致的：http://www.shfe.com.cn/statements/dataview.html?paramid=kx

**Comment by zevichen** [comment]
所以上期自己发布的数据，文华里面的数据等等都会存在有错误的地方吗
