### ISSUE TITLE
数据对不上，感觉浮点有问题

### ISSUE THREAD

**Issue by zevichen** [akfamily/akshare#2428]
1. 操作系统版本
2. Python 版本
3. AKShare 版本
4. 接口的名称和代码
5. 接口报错的截图或代码
```python
futures_1m=ak.futures_zh_minute_sina(symbol='FU2209',period='5')
```
<img width="540" alt="image" src="https://user-images.githubusercontent.com/9278899/163679861-7c44077e-6bf2-4cb5-9a9f-2ef11d707fc5.png">

<img width="678" alt="image" src="https://user-images.githubusercontent.com/9278899/163679876-978385fd-6d88-48df-9d2e-02966f2d252b.png">

这是1m里面存在的错误
<img width="827" alt="image" src="https://user-images.githubusercontent.com/9278899/163680003-870a6817-9656-4d8c-9589-14485051b9bf.png">

使用1m，5m都能看到有些错误的数据存在，有些数据是对的

**Comment by zevichen** [comment]
5m中的4231在文华里是4230...

**Comment by jindaxiang** [comment]
> 1. 操作系统版本
> 2. Python 版本
> 3. AKShare 版本
> 4. 接口的名称和代码
> 5. 接口报错的截图或代码
> 
> ```python
> futures_1m=ak.futures_zh_minute_sina(symbol='FU2209',period='5')
> ```
> 
> <img alt="image" width="540" src="https://user-images.githubusercontent.com/9278899/163679861-7c44077e-6bf2-4cb5-9a9f-2ef11d707fc5.png">
> 
> <img alt="image" width="678" src="https://user-images.githubusercontent.com/9278899/163679876-978385fd-6d88-48df-9d2e-02966f2d252b.png">
> 
> 这是1m里面存在的错误 <img alt="image" width="827" src="https://user-images.githubusercontent.com/9278899/163680003-870a6817-9656-4d8c-9589-14485051b9bf.png">
> 
> 使用1m，5m都能看到有些错误的数据存在，有些数据是对的

每个数据供应商计算方式不同，建议使用同一数据源的数据

**Comment by zevichen** [comment]
好的，谢谢
