### ISSUE TITLE
AKShare 接口问题报告 stock_a_pe_df = ak.stock_a_pe(symbol="sh")

### ISSUE THREAD

**Issue by OatLatte** [akfamily/akshare#2429]
![issue](https://user-images.githubusercontent.com/103306071/163682806-6736f83b-7920-45fd-9ea8-64c215dd25b9.png)
A股pe接口,sh,sz,zx,cy这几个不能调取数据

**Comment by jindaxiang** [comment]
> ![issue](https://user-images.githubusercontent.com/103306071/163682806-6736f83b-7920-45fd-9ea8-64c215dd25b9.png) A股pe接口,sh,sz,zx,cy这几个不能调取数据

可以正常运行
![Uploading image.png…]()

**Comment by jindaxiang** [comment]
> ![issue](https://user-images.githubusercontent.com/103306071/163682806-6736f83b-7920-45fd-9ea8-64c215dd25b9.png) A股pe接口,sh,sz,zx,cy这几个不能调取数据

可以正常运行：
![image](https://user-images.githubusercontent.com/18234520/163704614-95fad2be-62b4-4f03-845a-f19229bb7f8c.png)
