### ISSUE TITLE
树莓派4B import akshare时报错

### ISSUE THREAD

**Issue by 102757017** [akfamily/akshare#2437]
设备型号 树莓派4b
系统：Debian11 (bullseys)  
系统架构：aarch64 64bit
内核版本：5.15.32-v8+
python版本：3.9.2 64bit

>>> import akshare
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/.local/lib/python3.9/site-packages/akshare/__init__.py", line 2302, in <module>
    from akshare.stock_feature.stock_ttm_lyr import stock_a_ttm_lyr
  File "/home/pi/.local/lib/python3.9/site-packages/akshare/stock_feature/stock_ttm_lyr.py", line 317, in <module>
    js_functions = py_mini_racer.MiniRacer()
  File "/home/pi/.local/lib/python3.9/site-packages/py_mini_racer/py_mini_racer.py", line 178, in __init__
    self.__class__.ext = _build_ext_handle()
  File "/home/pi/.local/lib/python3.9/site-packages/py_mini_racer/py_mini_racer.py", line 125, in _build_ext_handle
    raise RuntimeError("Native library not available at {}".format(EXTENSION_PATH))
RuntimeError: Native library not available at /home/pi/.local/lib/python3.9/site-packages/py_mini_racer/libmini_racer.glibc.so

提示py_mini_racer这个包找不到libmini_racer.glibc.so这个文件，直接导入py_mini_racer这个包也报同样的错误。
查看安装的py_mini_racer这个包版本是0.6.0。
在/home/pi/.local/lib/python3.9/site-packages/py_mini_racer/目录下只有libmini_racer.muslc.so这个文件，没有libmini_racer.glibc.so

**Comment by jindaxiang** [comment]
> 设备型号 树莓派4b 系统：Debian11 (bullseys) 系统架构：aarch64 64bit 内核版本：5.15.32-v8+ python版本：3.9.2 64bit
> 
> > > > import akshare
> > > > Traceback (most recent call last):
> > > > File "", line 1, in 
> > > > File "/home/pi/.local/lib/python3.9/site-packages/akshare/**init**.py", line 2302, in 
> > > > from akshare.stock_feature.stock_ttm_lyr import stock_a_ttm_lyr
> > > > File "/home/pi/.local/lib/python3.9/site-packages/akshare/stock_feature/stock_ttm_lyr.py", line 317, in 
> > > > js_functions = py_mini_racer.MiniRacer()
> > > > File "/home/pi/.local/lib/python3.9/site-packages/py_mini_racer/py_mini_racer.py", line 178, in **init**
> > > > self.**class**.ext = _build_ext_handle()
> > > > File "/home/pi/.local/lib/python3.9/site-packages/py_mini_racer/py_mini_racer.py", line 125, in _build_ext_handle
> > > > raise RuntimeError("Native library not available at {}".format(EXTENSION_PATH))
> > > > RuntimeError: Native library not available at /home/pi/.local/lib/python3.9/site-packages/py_mini_racer/libmini_racer.glibc.so
> 
> 提示py_mini_racer这个包找不到libmini_racer.glibc.so这个文件，直接导入py_mini_racer这个包也报同样的错误。 查看安装的py_mini_racer这个包版本是0.6.0。 在/home/pi/.local/lib/python3.9/site-packages/py_mini_racer/目录下只有libmini_racer.muslc.so这个文件，没有libmini_racer.glibc.so

由于 py_mini_racer 库，没有相应的 ARM 编译版本导致的问题，有兴趣的可以看下这个库的 ARM 编译版本
