### ISSUE TITLE
数据问题，公募基金的分红配送数据不完全正确。

### ISSUE THREAD

**Issue by TonyTangTwj** [akfamily/akshare#2438]
通过函数fund_fh_em，fund_cf_em，获取的分红配送数据有重复。总的数据量是和网站上的一样的，但是由于其中有些是重复的数据，所以总的来说是缺少的。比如公募基金‘000001’缺少了2016.12.26的分红信息。

**Comment by jindaxiang** [comment]
> 000001

暂时没有发现所说的问题，方便的话可以提供代码和截图嘛？
