### ISSUE TITLE
api-上市公司质押比例 报错，debug查看是404

### ISSUE THREAD

**Issue by wjce** [akfamily/akshare#2440]
_get_page_num_gpzy_industry_data()
这个获取总页数的方法返回404

**Comment by jindaxiang** [comment]
> _get_page_num_gpzy_industry_data() 这个获取总页数的方法返回404

感谢反馈问题，已修复该问题；目前接口 stock_em_gpzy_industry_data 修改为 stock_gpzy_industry_data_em；不在需要 _get_page_num_gpzy_industry_data
升级到 AKShare 1.5.34 版本使用
