### ISSUE TITLE
stock_zh_a_hist_163股票名称中文乱码

### ISSUE THREAD

**Issue by handsomeceleste** [akfamily/akshare#2444]
1. 操作系统版本：MacOS 12.1
2. Python 版本：3.8.12
3. AKShare 版本：1.5.34
4. 接口的名称和代码：stock_hist_163.py里stock_zh_a_hist_163的测试代码
5. 接口报错的截图或代码：'sh600587'的股票名称显示为乱码'陔貌瓟谿'
6. 期望获得的正确结果：'新华医疗'

**Comment by jindaxiang** [comment]
> 5\. sh600587

接口测试正常；
![Uploading image.png…]()
建议升级 Pandas 到最新版

**Comment by handsomeceleste** [comment]
Pandas是最新版啊，1.4.1，和操作系统的默认语言是英文有关系吗？

**Comment by handsomeceleste** [comment]
我试了一下，在`r = requests.get(url, params=params, headers=headers)`之后加上`r.encoding = 'gbk'`即可，希望能够更新一下，谢谢~
