### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by OatLatte** [akfamily/akshare#2448]
![未命名1650559918](https://user-images.githubusercontent.com/103306071/164511347-d368b211-51e4-40b1-8d6b-7e7b2d62cc9a.png)

这个等权平均和中位数对应错了

**Comment by jindaxiang** [comment]
> ![未命名1650559918](https://user-images.githubusercontent.com/103306071/164511347-d368b211-51e4-40b1-8d6b-7e7b2d62cc9a.png)
> 
> 这个等权平均和中位数对应错了

感谢反馈问题，已修复
