### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by mtn888** [akfamily/akshare#2464]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本 Windows10
2. Python 版本 3.8
3. AKShare 版本 1.5.46
4. 接口的名称和代码 ak.futures_zh_daily_sina
5. 接口报错的截图或代码 
<img width="512" alt="1651066568(1)" src="https://user-images.githubusercontent.com/104508987/165531141-a0319d80-c067-42ca-8141-de596f6c6884.png">

6. 期望获得的正确结果
settle列都是0，没有获取到正确的值，请帮忙处理，谢谢！

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本 Windows10
> 2. Python 版本 3.8
> 3. AKShare 版本 1.5.46
> 4. 接口的名称和代码 ak.futures_zh_daily_sina
> 5. 接口报错的截图或代码
> 
> <img alt="1651066568(1)" width="512" src="https://user-images.githubusercontent.com/104508987/165531141-a0319d80-c067-42ca-8141-de596f6c6884.png">
> 
> 6. 期望获得的正确结果
>    settle列都是0，没有获取到正确的值，请帮忙处理，谢谢！

经核对是数据源没有该数据
