### ISSUE TITLE
Golang连接数据接口

### ISSUE THREAD

**Issue by Jsoooooooo** [akfamily/akshare#2472]
你好，请问golang如何连接ak数据，aktools没有详细解释呢

**Comment by jindaxiang** [comment]
> 你好，请问golang如何连接ak数据，aktools没有详细解释呢

HTTP 是通用的，使用 Go 进行 HTTP 请求即可

**Comment by Jsoooooooo** [comment]
收到，谢谢

**Comment by Jsoooooooo** [comment]
你好，请问aktools接口能否高频访问？我怕给服务器带来压力。另外，用socket连是否可以呢？
