### ISSUE TITLE
空气质量数据无法获取

### ISSUE THREAD

**Issue by edwardsun** [akfamily/akshare#2492]
**Describe the bug**
空气质量数据无法获取

**To Reproduce**
使用例子给出的代码:
import akshare as ak

air_quality_hist_df = ak.air_quality_hist(city="北京", period="day", start_date="20200320", end_date="20200427")
print(air_quality_hist_df)

**Expected behavior**
应该return一个dataframe

**Screenshots**
![image](https://user-images.githubusercontent.com/359830/166913268-9c49f269-1677-41fc-b1d9-e95e14dbbffd.png)

**Desktop (please complete the following information):**
Ubuntu 20.04
python 3.8.10
AKSHARE 1.5.58

**Smartphone (please complete the following information):**

**Additional context**

**Comment by edwardsun** [comment]
> 换近期的时间试试
近期数据也不管用。
但很有意思的是，昨天好像是可以获得数据的，因为我这里最新数据日期是2022-05-03

![image](https://user-images.githubusercontent.com/359830/166958666-f3b25cce-2fc9-48a1-9d36-8dc4dc11a4e6.png)

**Comment by jindaxiang** [comment]
> 20200427

可以正常获取到数据
