### ISSUE TITLE
申万二级实时指数返回行数不正确

### ISSUE THREAD

**Issue by Cuiqs76** [akfamily/akshare#2493]
**描述遇到的问题**
1. 操作系统版本: windows 10
2. Python 版本：3.9.7
3. AKShare 版本：1.5.59
4. 接口的名称和代码:
  申万二级行业实时行情 sw_index_second_spot.
```
import akshare as ak
sw_index_second_spot_df = ak.sw_index_second_spot()
print(sw_index_second_spot_df)
```

6. 接口报错的截图或代码
![image](https://user-images.githubusercontent.com/13130628/167081493-0b72eb90-3560-4dcc-ac62-a172bff06957.png)
返回的行业只有64个。

8. 期望获得的正确结果
返回应该是124行（SW二级行业124个）

**Comment by jindaxiang** [comment]
> **描述遇到的问题**
> 
> 1. 操作系统版本: windows 10
> 2. Python 版本：3.9.7
> 3. AKShare 版本：1.5.59
> 4. 接口的名称和代码:
>    申万二级行业实时行情 sw_index_second_spot.
> 
> ```
> import akshare as ak
> sw_index_second_spot_df = ak.sw_index_second_spot()
> print(sw_index_second_spot_df)
> ```
> 
> 6. 接口报错的截图或代码
>    ![image](https://user-images.githubusercontent.com/13130628/167081493-0b72eb90-3560-4dcc-ac62-a172bff06957.png)
>    返回的行业只有64个。
> 7. 期望获得的正确结果
>    返回应该是124行（SW二级行业124个）

感谢反馈问题，已修复该问题，升级到 AKShare 1.5.60 版本使用
