### ISSUE TITLE
AKShare 接口问题: 'stock_zh_a_hist_min_em' returns empty dataframe.

### ISSUE THREAD

**Issue by dubhex** [akfamily/akshare#2498]
**描述遇到的问题**
1. 操作系统版本: mac ox bigSur 11.2.2
2. Python 版本: 3.7.0
3. AKShare 版本: 1.5.61
4. 接口的名称和代码: stock_zh_a_hist_min_em
5. 接口报错的截图或代码: 

输入: 
ak.stock_zh_a_hist_min_em(symbol="000001", start_date="2021-09-01 09:32:00", end_date="2021-09-06 09:32:00", period='1', adjust='')
返回：
Empty DataFrame
Columns: [时间, 开盘, 收盘, 最高, 最低, 成交量, 成交额, 最新价]
Index: []

输入: 
ak.stock_zh_a_hist_min_em(symbol="000001", start_date="2021-09-01 09:32:00", end_date="2021-09-06 09:32:00", period='5', adjust='hfq')
返回：
Empty DataFrame
Columns: [时间, 开盘, 收盘, 最高, 最低, 涨跌幅, 涨跌额, 成交量, 成交额, 振幅, 换手率]
Index: []

6. 期望获得的正确结果: 正确的分时数据。

**Comment by jindaxiang** [comment]
> stock_zh_a_hist_min_em(symbol="000001", start_date="2021-09-01 09:32:00", end_date="2021-09-06 09:32:00", period='1', adjust='')

该接口只能获取近期的数据；请查看文档说明
