### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by Franklyn1987** [akfamily/akshare#2506]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本win11
2. Python 版本3.10
3. AKShare 版本 new
4. 接口的名称和代码
5. 接口报错的截图或代码
6. 期望获得的正确结果
C:\Python310\lib\site-packages\akshare\stock\stock_zh_a_sina.py:58: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  big_df = big_df.append(pd.DataFrame(data_json), ignore_index=True)

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本win11
> 2. Python 版本3.10
> 3. AKShare 版本 new
> 4. 接口的名称和代码
> 5. 接口报错的截图或代码
> 6. 期望获得的正确结果
>    C:\Python310\lib\site-packages\akshare\stock\stock_zh_a_sina.py:58: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
>    big_df = big_df.append(pd.DataFrame(data_json), ignore_index=True)

感谢反馈问题，已经修复该问题，升级到 AKShare 1.5.70 使用
