### ISSUE TITLE
沪深 A 股公告 - 根据日期返回该日期全部公告以及公告的链接地址

### ISSUE THREAD

**Issue by Cuiqs76** [akfamily/akshare#2515]
沪深 A 股公告
接口: stock_notice_report
描述: 东方财富网-数据中心-公告大全-沪深 A 股公告
限量: 单次获取指定页数的数据
问题：目前是根据页数返回数据，页数会有很多日期的，到某日不知一次要返回多少页。
**Describe the solution you'd like**
希望能够根据日期返回该日期所有公告以及公告的链接地址。

**Describe alternatives you've considered**
1.可以根据日期返回某日所有公告或某类型公告
2.可以输入日期返回返回所有公告

**Comment by jindaxiang** [comment]
> 沪深 A 股公告 接口: stock_notice_report 描述: 东方财富网-数据中心-公告大全-沪深 A 股公告 限量: 单次获取指定页数的数据 问题：目前是根据页数返回数据，页数会有很多日期的，到某日不知一次要返回多少页。 **Describe the solution you'd like** 希望能够根据日期返回该日期所有公告以及公告的链接地址。
> 
> **Describe alternatives you've considered** 1.可以根据日期返回某日所有公告或某类型公告 2.可以输入日期返回返回所有公告

感谢反馈问题，已修复该问题，升级到 AKShare 1.5.73 版本使用，注意参考文档参数
