### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by purplezzh** [akfamily/akshare#2519]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本
macOS Monterey 12.3.1, Windows 11 Pro 21H2
2. Python 版本
3.8.5, 3.9.11
3. AKShare 版本
`>=1.5.52
4. 接口的名称和代码
df = ak.stock_financial_analysis_indicator(symbol='000001')
5. 接口报错的截图或代码
在1.5.52及更高版本中，该函数返回结构的"日期"列仅显示序数，而非日期。
6. 期望获得的正确结果
在1.5.51及更早版本中，该函数返回的"日期"列可正常显示日期，以区分年报指标与季报指标。

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本
>    macOS Monterey 12.3.1, Windows 11 Pro 21H2
> 2. Python 版本
>    3.8.5, 3.9.11
> 3. AKShare 版本
>    `>=1.5.52
> 4. 接口的名称和代码
>    df = ak.stock_financial_analysis_indicator(symbol='000001')
> 5. 接口报错的截图或代码
>    在1.5.52及更高版本中，该函数返回结构的"日期"列仅显示序数，而非日期。
> 6. 期望获得的正确结果
>    在1.5.51及更早版本中，该函数返回的"日期"列可正常显示日期，以区分年报指标与季报指标。

感谢反馈问题，已修复该问题，请升级到 AKShare 1.5.75 使用
