### ISSUE TITLE
vix指数数据丢失了

### ISSUE THREAD

**Issue by subaochen** [akfamily/akshare#2528]
如下面的代码所示，无法获取vix指数数据：

`
import akshare as ak
index_vix_df = ak.index_vix(start_date="2020-03-20", end_date="2020-03-27")
print(index_vix_df)
`

会报告如下错误：

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Input In [5], in <cell line: 13>()
      4 #qqq = pro.us_daily(ts_code='QQQ', start_date='20220501', end_date='20220516')
      5 #vix = pro.us_daily(ts_code='^VIX', start_date='20220501', end_date='20220516')
      6 #print(qqq)
   (...)
      9 #print(df)
     10 #df.to_csv('us4.csv')
     12 import akshare as ak
---> 13 index_vix_df = ak.index_vix(start_date="2022-05-2", end_date="2022-05-17")
     14 print(index_vix_df)

File ~/anaconda3/envs/quant/lib/python3.8/site-packages/akshare/economic/macro_other.py:133, in index_vix(start_date, end_date)
    117 headers = {
    118     "accept": "*/*",
    119     "accept-encoding": "gzip, deflate, br",
   (...)
    130     "x-version": "1.0.0",
    131 }
    132 res = requests.get(url, params=params, headers=headers)
--> 133 temp_df = pd.DataFrame(res.json()["data"]["values"], index=["开盘价", "当前价", "涨跌", "涨跌幅"]).T
    134 temp_df = temp_df.astype(float)
    135 return temp_df

KeyError: 'data'

**Comment by jindaxiang** [comment]
> index_vix

请按文档说明撰写函数参数，近期该数据源暂未更新数据
