### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by xjjsg** [akfamily/akshare#2542]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本 macos 12.31
2. Python 版本 3.97
3. AKShare 版本 1.5.83
4. 接口的名称和代码 stock_zh_a_minute
5. 接口报错的截图或代码.  
<img width="730" alt="截屏2022-05-21 01 07 08" src="https://user-images.githubusercontent.com/55541830/169578178-0f8a2c77-7d89-495e-9809-61877bd6f19b.png">

6. 期望获得的正确结果
请问是只能获取20000行数据吗

**Comment by Haonan-Zhang** [comment]
1. 操作系统版本 macos 10.13.6
2. Python 版本 3.7.1
3. AKShare 版本 1.5.83
4. 接口的名称和代码 stock_three_report_em.py的全部函数，例如stock_profit_sheet_by_report_em
5. 接口报错的截图或代码
![屏幕快照 2022-05-21 上午9 57 27](https://user-images.githubusercontent.com/48652748/169630197-908d18a7-ee18-429c-99eb-5dc152933bbf.jpg)
6. 期望获得的正确结果
日期应没有跳跃（比如2020-12-31没有）。
`sep_list = [",".join(need_date[i: i + 5]) for i in range(0, len(need_date), 6)]`
需要改成
`sep_list = [",".join(need_date[i: i + 5]) for i in range(0, len(need_date), 5)]`

**Comment by jindaxiang** [comment]
> 4\. stock_zh_a_minute

是的

**Comment by jindaxiang** [comment]
> 1. 操作系统版本 macos 10.13.6
> 2. Python 版本 3.7.1
> 3. AKShare 版本 1.5.83
> 4. 接口的名称和代码 stock_three_report_em.py的全部函数，例如stock_profit_sheet_by_report_em
> 5. 接口报错的截图或代码
>    ![屏幕快照 2022-05-21 上午9 57 27](https://user-images.githubusercontent.com/48652748/169630197-908d18a7-ee18-429c-99eb-5dc152933bbf.jpg)
> 6. 期望获得的正确结果
>    日期应没有跳跃（比如2020-12-31没有）。
>    `sep_list = [",".join(need_date[i: i + 5]) for i in range(0, len(need_date), 6)]`
>    需要改成
>    `sep_list = [",".join(need_date[i: i + 5]) for i in range(0, len(need_date), 5)]`

已经合并 PR，请升级到最新版使用

**Comment by xjjsg** [comment]
不是一个接口啊，我想问是否一次仅能获取20000行
