### ISSUE TITLE
AKShare 接口问题报告-两市停复牌返回数据差2行

### ISSUE THREAD

**Issue by Cuiqs76** [akfamily/akshare#2545]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本
2. Python 版本 ：3.9
3. AKShare 版本:1.5.84
4. 接口的名称和代码：两市停复牌 stock_tfp_em
5. 接口报错的截图或代码
1. 返回数据比东财少2行 2. 顺序跟东财也不一致
![image](https://user-images.githubusercontent.com/13130628/169662237-11cf7ff4-b9ce-405c-99ef-17318e80c2b6.png)

7. 期望获得的正确结果
跟东财一致
![image](https://user-images.githubusercontent.com/13130628/169662288-0428a8e6-ae17-4a06-965f-726f3730adc3.png)

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本
> 2. Python 版本 ：3.9
> 3. AKShare 版本:1.5.84
> 4. 接口的名称和代码：两市停复牌 stock_tfp_em
> 5. 接口报错的截图或代码
> 6. 返回数据比东财少2行 2. 顺序跟东财也不一致
>    ![image](https://user-images.githubusercontent.com/13130628/169662237-11cf7ff4-b9ce-405c-99ef-17318e80c2b6.png)
> 7. 期望获得的正确结果
>    跟东财一致
>    ![image](https://user-images.githubusercontent.com/13130628/169662288-0428a8e6-ae17-4a06-965f-726f3730adc3.png)

感谢反馈问题，已修改该问题，升级到 AKShare 1.5.87 版本使用
