### ISSUE TITLE
AKShare 接口问题报告stock_us_fundamental获取数据过于缓慢

### ISSUE THREAD

**Issue by xnw176** [akfamily/akshare#2548]
**描述遇到的问题**

1. 操作系统版本:              
MAC  OS. 12.4
2. Python 版本
3.8
3. AKShare 版本:           
1.5.84
4. 接口的名称和代码:     
stock_us_fundamental
5. 接口报错的截图或代码:   
打开网页端速度并不慢，但用接口获取数据耗时需要大几分钟，实际数据为单页，数据量并不大，是否可以改善？感谢。

**Comment by jindaxiang** [comment]
> 4\. stock_us_fundamental

速度是由对方服务器决定的

**Comment by xnw176** [comment]
> > 4. stock_us_fundamental
> 
> 速度是由对方服务器决定的


目前个人用变通的方法解决，先用ak接口的symbol="info"读取保存一个本地表，通过这个表里面的字段生成一个URL地址，然后用pd.read_html直接读，这样差不多两秒内就可以获取到表格数据，而直接用接口读取耗时都在2分钟以上。

个人技术小白，并不懂底层，只是提议看看大佬有什么可以从接口底层来解决的办法。
