### ISSUE TITLE
IP被封应该是误报

### ISSUE THREAD

**Issue by csfreebird** [akfamily/akshare#2559]
**Describe the bug**
刚升级的最新版本akshare, 在文件
akshare/interest_rate/interbank_rate_em.py的73行, 对于异常情况统一报错为IP被封，实际上我的浏览器能正常访问东财数据网站

    except AttributeError as e:
        raise IPError("IP 被封了, 建议 20 分钟后再尝试或者切换 WIFI 为手机热点")
    return int(page_num)

**To Reproduce**
1. [网站url](https://datacenter-web.eastmoney.com/api/data/v1/get?callback=datatable1785869&reportName=RPT_IMP_INTRESTRATEN&columns=REPORT_DATE%2CREPORT_PERIOD%2CIR_RATE%2CCHANGE_RATE%2CINDICATOR_ID%2CLATEST_RECORD%2CMARKET%2CMARKET_CODE%2CCURRENCY%2CCURRENCY_CODE&quoteColumns=&filter=(MARKET_CODE%3D%22001%22)(CURRENCY_CODE%3D%22CNY%22)(INDICATOR_ID%3D%22001%22)&pageNumber=1&pageSize=20&sortTypes=-1&sortColumns=REPORT_DATE&source=WEB&client=WEB&_=1653366584710)
2. [网页url](https://data.eastmoney.com/shibor/shibor/001,CNY,001.html)

**Expected behavior**
希望检查异常原因，而不是简单抛出一个异常说是被封。

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: brave, 基于chrom内核

**Comment by jindaxiang** [comment]
> **Describe the bug** 刚升级的最新版本akshare, 在文件 akshare/interest_rate/interbank_rate_em.py的73行, 对于异常情况统一报错为IP被封，实际上我的浏览器能正常访问东财数据网站
> 
> ```
> except AttributeError as e:
>     raise IPError("IP 被封了, 建议 20 分钟后再尝试或者切换 WIFI 为手机热点")
> return int(page_num)
> ```
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. [网站url](https://datacenter-web.eastmoney.com/api/data/v1/get?callback=datatable1785869&reportName=RPT_IMP_INTRESTRATEN&columns=REPORT_DATE%2CREPORT_PERIOD%2CIR_RATE%2CCHANGE_RATE%2CINDICATOR_ID%2CLATEST_RECORD%2CMARKET%2CMARKET_CODE%2CCURRENCY%2CCURRENCY_CODE&quoteColumns=&filter=(MARKET_CODE%3D%22001%22)(CURRENCY_CODE%3D%22CNY%22)(INDICATOR_ID%3D%22001%22)&pageNumber=1&pageSize=20&sortTypes=-1&sortColumns=REPORT_DATE&source=WEB&client=WEB&_=1653366584710)
> 2. [网页url](https://data.eastmoney.com/shibor/shibor/001,CNY,001.html)
> 
> **Expected behavior** 希望检查异常原因，而不是简单抛出一个异常说是被封。
> 
> **Desktop (please complete the following information):**
> 
> * OS: Ubuntu 20.04
> * Browser: brave, 基于chrom内核

感谢反馈问题，已修复该问题，升级到 AKShare 1.5.92 版本使用
