### ISSUE TITLE
stock_zh_a_hist 接口数据范围问题 

### ISSUE THREAD

**Issue by ZL221B** [akfamily/akshare#2562]
stock_zh_a_hist 这个接口必须指定起止时间了吗？还是我没有搞对？
怎么像以前一样可以从上市那一天开始获取数据呢？

**Comment by jindaxiang** [comment]
> stock_zh_a_hist 这个接口必须指定起止时间了吗？还是我没有搞对？ 怎么像以前一样可以从上市那一天开始获取数据呢？

按文档说明操作

**Comment by ZL221B** [comment]
我一直用着的 今天突然不行了 就想问下怎么从上市第一天开始获取数据 说明文档没有这方面解释
