### ISSUE TITLE
开发者您好，stock_zh_a_hist该接口获取日K线数据，遇到停牌的股票会直接报错，使用版本1.5.91

### ISSUE THREAD

**Issue by tzmdaming** [akfamily/akshare#2563]
比如
吉林化纤  000420
这个股票
使用stock_zh_a_hist接口，参数设置为period="daily"的时候，遇到这个停牌的股票，直接报错，无法继续执行下去，其他股票能正常拉取数据，今天更新到1.5.91版本后，出现这个问题，上周五5月20日使用1.5.82版本的时候，正常
还请开发者能帮忙看看修复下，谢谢~

**Comment by ZL221B** [comment]
不会 我刚刚试了 到20220429就没有数据了

**Comment by tzmdaming** [comment]
> 不会 我刚刚试了 到20220429就没有数据了

是的，目前正是因为停牌的股票没数据，导致接口拉取该停牌股票行情数据的时候直接报错并导致程序终止运行了。而在之前的版本中，并不会报错，也不会终止代码运行的

**Comment by jindaxiang** [comment]
> 接口拉取该停牌股票行情数据的时候直接报错

提供下报错的代码及错误

**Comment by ZL221B** [comment]
我意思是没有报错 只是数据到20220429

**Comment by ZL221B** [comment]
我用的 1.5.92
             时间    开盘    收盘    最高  ...     振幅    涨跌幅   涨跌额    换手率
0    1996-08-02  2.60  2.29  2.60  ...  18.72  22.46  0.42  46.94
1    1996-08-05  2.30  2.35  2.35  ...   4.37   2.62  0.06  15.12
2    1996-08-06  2.36  2.49  2.50  ...   5.96   5.96  0.14  31.11
3    1996-08-07  2.49  2.54  2.56  ...   5.22   2.01  0.05  25.53
4    1996-08-08  2.54  2.65  2.71  ...   7.48   4.33  0.11  30.25
...         ...   ...   ...   ...  ...    ...    ...   ...    ...
6124 2022-04-25  3.68  3.35  3.68  ...   8.87  -9.95 -0.37   1.93
6125 2022-04-26  3.34  3.12  3.35  ...   7.46  -6.87 -0.23   2.00
6126 2022-04-27  2.93  3.39  3.43  ...  16.03   8.65  0.27   2.34
6127 2022-04-28  3.42  3.38  3.47  ...   4.72  -0.29 -0.01   1.58
6128 2022-04-29  3.43  3.39  3.45  ...   3.25   0.30  0.01   1.98

[6129 rows x 11 columns]

**Comment by tzmdaming** [comment]
我调用的代码是：
stock_zh_a_hist_df = ak.stock_zh_a_hist(symbol=str(res[0]), period="daily", start_date=ks_date, end_date=js_date, adjust="hfq")
其中res[0]，是具体某个股票的代码，比如000420这种
ks_date = "20220523"
js_date = "20220524"

这段调用代码，用了将近8个月了，在上周五使用的1.5.82版本及之前的版本，一直是正常运行的，即使是遇到停牌的股票，也不报错

**Comment by tzmdaming** [comment]
好的，非常感谢开发者，辛苦您了~

**Comment by tzmdaming** [comment]
> > 我调用的代码是： stock_zh_a_hist_df = ak.stock_zh_a_hist(symbol=str(res[0]), period="daily", start_date=ks_date, end_date=js_date, adjust="hfq") 其中res[0]，是具体某个股票的代码，比如000420这种 ks_date = "20220523" js_date = "20220524"
> > 这段调用代码，用了将近8个月了，在上周五使用的1.5.82版本及之前的版本，一直是正常运行的，即使是遇到停牌的股票，也不报错
> 
> 已修复该问题，升级到 AKShare 1.5.93 版本； 目前的拉取逻辑发生改变，只从服务器提取指定日期之间的数据，能够提高获取数据的速度，目前已经对非交易日和停牌等特殊日期进行处理，返回空 pandas.DataFrame，跟之前的版本对应

尊敬的开发者您好，今天我尝试使用stock_zh_a_hist接口，参数设置为 period="weekly"和period="monthly"，拉取周K线和月K线的时候，遇到了类似的问题。还请帮忙看看，谢谢了~


period="monthly"
股票代码 ：001267 
拉取时间周期：
start = "20060101"
end ="20211031"
报错如下：
Traceback (most recent call last):

  File "D:\upupup\获取股票月K线数据.py", line 62, in <module>
    stock_zh_a_hist_df = ak.stock_zh_a_hist(symbol=str(res[0]), period="monthly", start_date=start, end_date=end, adjust="hfq")

  File "D:\anaconda\lib\site-packages\akshare\stock_feature\stock_hist_em.py", line 323, in stock_zh_a_hist
    if not data_json["data"]["klines"]:

TypeError: 'NoneType' object is not subscriptable



period="weekly"
股票代码：301183
拉取周期：
start = "20060101"
end ="20220522"
报错如下：
Traceback (most recent call last):

  File "D:\upupup\获取股票周K线数据.py", line 50, in <module>
    stock_zh_a_hist_df = ak.stock_zh_a_hist(symbol=str(res[0]), period="weekly", start_date=start, end_date=end, adjust="hfq")

  File "D:\anaconda\lib\site-packages\akshare\stock_feature\stock_hist_em.py", line 323, in stock_zh_a_hist
    if not data_json["data"]["klines"]:

TypeError: 'NoneType' object is not subscriptable
