### ISSUE TITLE
尊敬的开发者您好，stock_zh_a_hist获取月线和周线数据，如果个股在非有效时间参数内，程序会报错并终止运行

### ISSUE THREAD

**Issue by tzmdaming** [akfamily/akshare#2568]
> > 我调用的代码是： stock_zh_a_hist_df = ak.stock_zh_a_hist(symbol=str(res[0]), period="daily", start_date=ks_date, end_date=js_date, adjust="hfq") 其中res[0]，是具体某个股票的代码，比如000420这种 ks_date = "20220523" js_date = "20220524"

> 
> 已修复该问题，升级到 AKShare 1.5.93 版本； 目前的拉取逻辑发生改变，只从服务器提取指定日期之间的数据，能够提高获取数据的速度，目前已经对非交易日和停牌等特殊日期进行处理，返回空 pandas.DataFrame，跟之前的版本对应

关联问题：

尊敬的开发者您好，period="daily"的时候，不管股票是否停牌或者是否时间参数是否是股票的有效时间，都能正常运行不再报错了
今天我尝试使用stock_zh_a_hist接口，参数设置为 period="weekly"和period="monthly"，拉取周K线和月K线的时候，遇到了类似的问题。还请帮忙看看，谢谢了~
我说一下我这边的使用情况，是这样的，日线数据是每天会进行更新，股票数据列表也是每天更新到数据库，而周K线和月K线数据，是隔一段时间统一更新一次（因为对周线和月线不太使用，主要用日线和分钟线），于是就遇到问题，比如我更新某一周的周K线(比如到5月8日这一周结束），而当前时间是今天5月26日去操作拉取周K线数据，我是先从数据库读取所有股票代码，然后依次调用接口去拉取该股票的周K线数据，那么从5月9日到今天发行的新股，通过同样的代码调用，去拉取周K线，于是就报错，程序终止运行了，不知道这个是否有办法解决，比如对于这批新股没数据的，可以返回默认的空，这样子，用户从使用的角度来说，就可以不用去判断在这个时间段内股票是否发行了以及一些其他各种各样特殊的情况，尤其是对于一些代码开发能力不强的非科班出生的用户来说，会好很多，非常感谢~~

具体报错场景：
参数设置： period="monthly"
股票代码 ：001267 
拉取时间周期：
start = "20060101"
end ="20211031"
报错如下：
Traceback (most recent call last):

  File "D:\获取股票月K线数据.py", line 62, in <module>
    stock_zh_a_hist_df = ak.stock_zh_a_hist(symbol=str(res[0]), period="monthly", start_date=start, end_date=end, adjust="hfq")

  File "D:\anaconda\lib\site-packages\akshare\stock_feature\stock_hist_em.py", line 323, in stock_zh_a_hist
    if not data_json["data"]["klines"]:

TypeError: 'NoneType' object is not subscriptable

参数设置：period="weekly"
股票代码：301183
拉取周期：
start = "20060101"
end ="20220522"
报错如下：
Traceback (most recent call last):

  File "D:\获取股票周K线数据.py", line 50, in <module>
    stock_zh_a_hist_df = ak.stock_zh_a_hist(symbol=str(res[0]), period="weekly", start_date=start, end_date=end, adjust="hfq")

  File "D:\anaconda\lib\site-packages\akshare\stock_feature\stock_hist_em.py", line 323, in stock_zh_a_hist
    if not data_json["data"]["klines"]:

TypeError: 'NoneType' object is not subscriptable

_Originally posted by @tzmdaming in https://github.com/akfamily/akshare/issues/2563#issuecomment-1136986904_

**Comment by tzmdaming** [comment]
尊敬的开发者您好，我目前测试下来，发现并不是所有非有效期都会报错，而似乎是这种情况下才会报错，比如301183的weekly之下，只有该股发行的上一周被纳入时间参数，才会报错，如果是上上周纳入时间参数，则不会报错，返回正常我们所期待的空值

print(ak.stock_zh_a_hist(symbol='301183', period='weekly', adjust='hfq', start_date='20060101', end_date='20220515'))
Empty DataFrame
Columns: []
Index: []


print(ak.stock_zh_a_hist(symbol='301183', period='weekly', adjust='hfq', start_date='20220516', end_date='20220522'))
Traceback (most recent call last):

  File "<ipython-input-62-c2802ba9d7f1>", line 1, in <module>
    print(ak.stock_zh_a_hist(symbol='301183', period='weekly', adjust='hfq', start_date='20220516', end_date='20220522'))

  File "D:\anaconda\lib\site-packages\akshare\stock_feature\stock_hist_em.py", line 323, in stock_zh_a_hist
    if not data_json["data"]["klines"]:

TypeError: 'NoneType' object is not subscriptable



又比如001267的monthly调用，如果是获取该新股发行以来的上一个月的月K线数据，则会报错，但是如果是获取上上一个月的月K线数据，则不会报错，返回正常我们所期待的空值

print(ak.stock_zh_a_hist(symbol='001267', period='monthly', adjust='hfq', start_date='20060101', end_date='20210930'))
Empty DataFrame
Columns: []
Index: []

print(ak.stock_zh_a_hist(symbol='001267', period='monthly', adjust='hfq', start_date='20060101', end_date='20211031'))
Traceback (most recent call last):

  File "<ipython-input-66-4f644f0b56bc>", line 1, in <module>
    print(ak.stock_zh_a_hist(symbol='001267', period='monthly', adjust='hfq', start_date='20060101', end_date='20211031'))

  File "D:\anaconda\lib\site-packages\akshare\stock_feature\stock_hist_em.py", line 323, in stock_zh_a_hist
    if not data_json["data"]["klines"]:

TypeError: 'NoneType' object is not subscriptable

**Comment by jindaxiang** [comment]
> 301183

已修复该问题，升级到 AKShare 1.5.97 使用

**Comment by tzmdaming** [comment]
好的，非常感谢~
