### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by bluesmilery** [akfamily/akshare#2576]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
stock_info_sh_delist接口报错

1. 操作系统版本：MacOS 12.4
2. Python 版本：3.7.9
3. AKShare 版本：1.6.2
4. 接口的名称和代码：终止上市-上证  stock_info_sh_delist
5. 接口报错的截图或代码：ValueError: Length mismatch: Expected axis has 13 elements, new values have 11 elements。stock_info.py 325行，dataframe有13列，但是给columns赋值只有11列
6. 期望获得的正确结果：修复错误

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> **描述遇到的问题** stock_info_sh_delist接口报错
> 
> 1. 操作系统版本：MacOS 12.4
> 2. Python 版本：3.7.9
> 3. AKShare 版本：1.6.2
> 4. 接口的名称和代码：终止上市-上证  stock_info_sh_delist
> 5. 接口报错的截图或代码：ValueError: Length mismatch: Expected axis has 13 elements, new values have 11 elements。stock_info.py 325行，dataframe有13列，但是给columns赋值只有11列
> 6. 期望获得的正确结果：修复错误

感谢反馈问题，已修复该问题，请升级到 AKShare 1.6.4 使用
