### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by bluesmilery** [akfamily/akshare#2577]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
stock_info_a_code_name接口报错
1. 操作系统版本：MacOS 12.4
2. Python 版本：3.7.9
3. AKShare 版本：1.6.2
4. 接口的名称和代码：股票列表-A股  stock_info_a_code_name
5. 接口报错的截图或代码：KeyError: "None of [Index(['公司代码', '公司简称'], dtype='object')] are in the [columns]"。stock_info.py 427行，列名应该为“证券代码”和“证券简称”
6. 期望获得的正确结果：修复错误

从刚才这两个问题来看，发版前似乎缺少接口回归？因为我是直接执行stock_info.py发现的

**Comment by jindaxiang** [comment]
已修复该问题，升级到 AKShare 1.6.4 版本使用；会陆续增加 测试代码
