### ISSUE TITLE
增加同花顺行业一览表

### ISSUE THREAD

**Issue by Cuiqs76** [akfamily/akshare#2581]
增加同花顺行业一览表接口
网址：http://q.10jqka.com.cn/thshy/
![image](https://user-images.githubusercontent.com/13130628/170865923-7cac5739-5d1e-4790-8ca0-896c69fd7c41.png)

**Comment by jindaxiang** [comment]
> 增加同花顺行业一览表接口 网址：http://q.10jqka.com.cn/thshy/ ![image](https://user-images.githubusercontent.com/13130628/170865923-7cac5739-5d1e-4790-8ca0-896c69fd7c41.png)

已经有了
