### ISSUE TITLE
同花顺概念接口使用反馈

### ISSUE THREAD

**Issue by xmsley614** [akfamily/akshare#2582]
stock_board_cons_ths 这个接口，同时可以根据传入代码返回行业成分股和概念成分股
使用过程中，概念代码为8开头的六位数，如阿里巴巴概念，885611
但是目前同花顺自己网站的概念板块成分股接口不是用的这个。经验证，阿里巴巴概念成分股可以同时通过如下两个url获取：
A http://q.10jqka.com.cn/gn/detail/field/199112/order/desc/page/1/ajax/1/code/301558
B http://q.10jqka.com.cn/thshy/detail/field/199112/order/desc/page/1/ajax/1/code/885611
A是同花顺网页版的做法，B是目前stock_board_cons_ths 的做法。同花顺网页版传的301558代码可以通过stock_board_concept_name_ths获得，但是885611这个代码没法通过现有接口获得。
是否可以考虑概念板块成分股改用A链接？或者概念时间表接口stock_board_concept_name_ths返回值增加885611这样子的编号，方便调用这个接口后进一步调用获取成分股接口。

相关截图：
同花顺行业板块链接地址和代码是一致的，但是同花顺概念板块链接的地址和代码是不一致的。
![image](https://user-images.githubusercontent.com/73490142/170882824-1cba10ea-fde8-4080-8603-f470c26a983f.png)
![image](https://user-images.githubusercontent.com/73490142/170882847-effc5f26-ba8c-4367-8f78-b29d7dd5beae.png)

**Comment by jindaxiang** [comment]
> stock_board_cons_ths 这个接口，同时可以根据传入代码返回行业成分股和概念成分股 使用过程中，概念代码为8开头的六位数，如阿里巴巴概念，885611 但是目前同花顺自己网站的概念板块成分股接口不是用的这个。经验证，阿里巴巴概念成分股可以同时通过如下两个url获取： A http://q.10jqka.com.cn/gn/detail/field/199112/order/desc/page/1/ajax/1/code/301558 B http://q.10jqka.com.cn/thshy/detail/field/199112/order/desc/page/1/ajax/1/code/885611 A是同花顺网页版的做法，B是目前stock_board_cons_ths 的做法。同花顺网页版传的301558代码可以通过stock_board_concept_name_ths获得，但是885611这个代码没法通过现有接口获得。 是否可以考虑概念板块成分股改用A链接？或者概念时间表接口stock_board_concept_name_ths返回值增加885611这样子的编号，方便调用这个接口后进一步调用获取成分股接口。
> 
> 相关截图： 同花顺行业板块链接地址和代码是一致的，但是同花顺概念板块链接的地址和代码是不一致的。 ![image](https://user-images.githubusercontent.com/73490142/170882824-1cba10ea-fde8-4080-8603-f470c26a983f.png) ![image](https://user-images.githubusercontent.com/73490142/170882847-effc5f26-ba8c-4367-8f78-b29d7dd5beae.png)

感谢反馈问题，已经修复该问题，升级到 AKShare 1.6.5 版本使用
