### ISSUE TITLE
AKShare 接口问题报告: fund_etf_category_sina

### ISSUE THREAD

**Issue by freelancerhc** [akfamily/akshare#2585]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本：docker in Win11
2. Python 版本：3.10.2
3. AKShare 版本：1.6.5
4. 接口的名称和代码：fund_etf_category_sina
5. 接口报错的截图或代码
![image](https://user-images.githubusercontent.com/13825798/171089606-1d9a481f-5f2b-4c32-acab-be3f37cfc244.png)
6. 期望获得的正确结果
返回正确的结果

**Comment by jindaxiang** [comment]
> 4\. fund_etf_category_sina

接口可以正常使用，请检查 docker 环境

**Comment by freelancerhc** [comment]
它好像自己恢复了，可能就那个时间点前后有问题，感谢快速回复
