### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'mr_free_context'

### ISSUE THREAD

**Issue by myapp-pan** [akfamily/akshare#2590]

**Comment by jindaxiang** [comment]
> _No description provided._

请详细描述问题

**Comment by myapp-pan** [comment]
使用akshare获取数据时报错 AttributeError: 'NoneType' object has no attribute 'mr_free_context' ，不太明白是什么错




秀儿浮笙
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "akfamily/akshare"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月1日(星期三) 下午3:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [akfamily/akshare] AttributeError: 'NoneType' object has no attribute 'mr_free_context' (Issue #2590)





 
Closed #2590 as completed.

**Comment by jindaxiang** [comment]
> 使用akshare获取数据时报错 AttributeError: 'NoneType' object has no attribute 'mr_free_context' ，不太明白是什么错 秀儿浮笙 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "akfamily/akshare" ***@***.***&gt;; 发送时间:&nbsp;2022年6月1日(星期三) 下午3:11 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [akfamily/akshare] AttributeError: 'NoneType' object has no attribute 'mr_free_context' (Issue #2590) Closed #2590 as completed. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

建议按文档配置环境，参见：[akshare.xyz](https://www.akshare.xyz/installation.html)

**Comment by myapp-pan** [comment]
这个问题确实很奇怪，之前程序是可以跑的，今天换了电脑后，就不能跑了，这个我看也没有什么特殊的环境要求




秀儿浮笙
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "akfamily/akshare"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月1日(星期三) 下午3:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [akfamily/akshare] AttributeError: 'NoneType' object has no attribute 'mr_free_context' (Issue #2590)





  
使用akshare获取数据时报错 AttributeError: 'NoneType' object has no attribute 'mr_free_context' ，不太明白是什么错 秀儿浮笙 @.*** &nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "akfamily/akshare" @.&gt;; 发送时间:&nbsp;2022年6月1日(星期三) 下午3:11 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [akfamily/akshare] AttributeError: 'NoneType' object has no attribute 'mr_free_context' (Issue #2590) Closed #2590 as completed. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
建议按文档配置环境，参见：akshare.xyz

**Comment by zycool** [comment]
已经解决，把整个 libmini_racer 文件夹拷贝进去，然后在差什么就考什么
