### ISSUE TITLE
增加一个接口，获取股票市场上历史出现过的所有股票代码和名称

### ISSUE THREAD

**Issue by RJ-ekoo** [akfamily/akshare#2610]
**Is your feature request related to a problem? Please describe.**
当我要获取股票市场上出现过的所有股票代码时感到非常麻烦，
有的是带sh,sz的股票代码，有的不带sh,sz，有的并不全

**Describe the solution you'd like**
希望可以增加一个接口：
可以获取所有股票的代码及名称（包括退市，停牌的即：股票市场上出现过的所有股票）
类似下图形式的数据

**Describe alternatives you've considered**

**Additional context**
![uTools_1654562163726](https://user-images.githubusercontent.com/83520333/172273178-87c277a2-026e-4b9f-81c6-fcaf5ffaac7a.png)

**Comment by jindaxiang** [comment]
> **Is your feature request related to a problem? Please describe.** 当我要获取股票市场上出现过的所有股票代码时感到非常麻烦， 有的是带sh,sz的股票代码，有的不带sh,sz，有的并不全
> 
> **Describe the solution you'd like** 希望可以增加一个接口： 可以获取所有股票的代码及名称（包括退市，停牌的即：股票市场上出现过的所有股票） 类似下图形式的数据
> 
> **Describe alternatives you've considered** A clear and concise description of any alternative solutions or features you've considered.
> 
> **Additional context** ![uTools_1654562163726](https://user-images.githubusercontent.com/83520333/172273178-87c277a2-026e-4b9f-81c6-fcaf5ffaac7a.png)

没有合适的数据源
