### ISSUE TITLE
增加一个接口：获取历史上出现过的所有股票

### ISSUE THREAD

**Issue by RJ-ekoo** [akfamily/akshare#2612]
**Is your feature request related to a problem? Please describe.**
当我要获取股票市场上出现过的所有股票代码时感到非常麻烦，
有的是带sh,sz的股票代码，有的不带sh,sz，有的并不全

**Describe the solution you'd like**
希望可以增加一个接口：
可以获取所有股票的代码及名称（包括退市，停牌的即：股票市场上出现过的所有股票）
类似图2：形式的数据

**Describe alternatives you've considered**

1.在DataFrame数据表格第一列加入从000000~999999的字符串（后面用df简称：数据表格）
2.根据各个交易所的股票代码特性在股票代码前加上sh,sz,bj,hk，（比如：000001变成sz000001），并加入df第二列
3.把df第二列循环带入接口: stock_zh_a_hist_163：历史行情数据-网易
4.用try:和except ValueError as e:接收步骤3的报错信息
5.如果报错提取步骤4中报错信息中的这个数：如图1，加入到df第三列，不报错的取nan值
6.把步骤5中报错的数不为1的对应代码都选出来，再次循环加入到步骤3,4,5中，直到步骤5中的报错的提取数值都为1为止
7.提取df第三列中所有空值对应的代码，再次通过接口: stock_zh_a_hist_163：历史行情数据-网易，获取股票对应的名字加入df第四列，其余的留nan值
8.选出df第四列中所有非空的值对应的股票行，重置索引，选出第一二四列，组成新的数据表df1
9.将df1保存到服务器上
10.增加一个接口每次调用这个接口就返回服务器上的df1

df1数据的更新：
1.通过接口: stock_info_a_code_name：股票列表-A股，获取最新的A股列表
2.检测步骤1中的列表是否有股票代码不在df1的数据中，把他选出来
3.之后根据各个交易所的股票代码特性在股票代码前加上sh,sz,bj,hk
4.带入接口: stock_zh_a_hist_163：历史行情数据-网易,获取股票对应的名字
5.把得到的这一行信息加入到df1数据中
（可以通过检测时间，在每天的9:31自动更新df1数据）

**Additional context**
图1：
![Cvrg3szW5J](https://user-images.githubusercontent.com/83520333/172508033-0be5359d-5e74-4db3-a4e4-371e257df424.png)
图2：
![uTools_1654562163726](https://user-images.githubusercontent.com/83520333/172508628-1c6c7136-c09f-4a1c-a12b-6807ed5b8af0.png)

**Comment by jindaxiang** [comment]
> **Is your feature request related to a problem? Please describe.** 当我要获取股票市场上出现过的所有股票代码时感到非常麻烦， 有的是带sh,sz的股票代码，有的不带sh,sz，有的并不全
> 
> **Describe the solution you'd like** 希望可以增加一个接口： 可以获取所有股票的代码及名称（包括退市，停牌的即：股票市场上出现过的所有股票） 类似图2：形式的数据
> 
> **Describe alternatives you've considered**
> 
> 1.在DataFrame数据表格第一列加入从000000~999999的字符串（后面用df简称：数据表格） 2.根据各个交易所的股票代码特性在股票代码前加上sh,sz,bj,hk，（比如：000001变成sz000001），并加入df第二列 3.把df第二列循环带入接口: stock_zh_a_hist_163：历史行情数据-网易 4.用try:和except ValueError as e:接收步骤3的报错信息 5.如果报错提取步骤4中报错信息中的这个数：如图1，加入到df第三列，不报错的取nan值 6.把步骤5中报错的数不为1的对应代码都选出来，再次循环加入到步骤3,4,5中，直到步骤5中的报错的提取数值都为1为止 7.提取df第三列中所有空值对应的代码，再次通过接口: stock_zh_a_hist_163：历史行情数据-网易，获取股票对应的名字加入df第四列，其余的留nan值 8.选出df第四列中所有非空的值对应的股票行，重置索引，选出第一二四列，组成新的数据表df1 9.将df1保存到服务器上 10.增加一个接口每次调用这个接口就返回服务器上的df1
> 
> df1数据的更新： 1.通过接口: stock_info_a_code_name：股票列表-A股，获取最新的A股列表 2.检测步骤1中的列表是否有股票代码不在df1的数据中，把他选出来 3.之后根据各个交易所的股票代码特性在股票代码前加上sh,sz,bj,hk 4.带入接口: stock_zh_a_hist_163：历史行情数据-网易,获取股票对应的名字 5.把得到的这一行信息加入到df1数据中 （可以通过检测时间，在每天的9:31自动更新df1数据）
> 
> **Additional context** 图1： ![Cvrg3szW5J](https://user-images.githubusercontent.com/83520333/172508033-0be5359d-5e74-4db3-a4e4-371e257df424.png) 图2： ![uTools_1654562163726](https://user-images.githubusercontent.com/83520333/172508628-1c6c7136-c09f-4a1c-a12b-6807ed5b8af0.png)

欢迎 PR 相关代码
