### ISSUE TITLE
北向资金增持行业板块排行接口问题

### ISSUE THREAD

**Issue by quanplex** [akfamily/akshare#2616]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
操作系统版本 Mac OS Monterey 12.0.1 
Python 版本 3.9.7 
AKShare 版本 1.6.13 
接口的名称和代码 ak$stock_hsgt_board_rank_em(symbol="北向资金增持行业板块排行", indicator="今日") %>% py_to_r
接口报错的截图或代码

<img width="365" alt="屏幕快照 2022-06-09 下午8 45 59" src="https://user-images.githubusercontent.com/8213679/172850497-055c8152-2052-4455-97d2-57ab6969367a.png">

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> **描述遇到的问题** 操作系统版本 Mac OS Monterey 12.0.1 Python 版本 3.9.7 AKShare 版本 1.6.13 接口的名称和代码 ak$stock_hsgt_board_rank_em(symbol="北向资金增持行业板块排行", indicator="今日") %>% py_to_r 接口报错的截图或代码
> 
> <img alt="屏幕快照 2022-06-09 下午8 45 59" width="365" src="https://user-images.githubusercontent.com/8213679/172850497-055c8152-2052-4455-97d2-57ab6969367a.png">

感谢反馈问题，已修复该问题，升级到 AKShare 1.6.14 使用
