### ISSUE TITLE
AKShare 接口问题报告 get bond_zh_cov_info fail

### ISSUE THREAD

**Issue by ruifeng96150** [akfamily/akshare#2620]
version: akshare-1.6.14

```
import akshare as ak
bond_zh_cov_info_df = ak.bond_zh_cov_info(symbol="123121")
print(bond_zh_cov_info_df)
```
result:

```
File ~/.local/lib/python3.8/site-packages/akshare/bond/bond_zh_cov_sina.py:512, in bond_zh_cov_info(symbol)
    510 soup = BeautifulSoup(r.text, "lxml")
    511 data_text = soup.find("script").string.strip()
--> 512 data_json = json.loads(re.findall("var info= (.*)", data_text)[0][:-1])
    513 temp_df = pd.json_normalize(data_json)
    514 return temp_df

IndexError: list index out of range

```

**Comment by jindaxiang** [comment]
> version: akshare-1.6.14
> 
> ```
> import akshare as ak
> bond_zh_cov_info_df = ak.bond_zh_cov_info(symbol="123121")
> print(bond_zh_cov_info_df)
> ```
> 
> result:
> 
> ```
> File ~/.local/lib/python3.8/site-packages/akshare/bond/bond_zh_cov_sina.py:512, in bond_zh_cov_info(symbol)
>     510 soup = BeautifulSoup(r.text, "lxml")
>     511 data_text = soup.find("script").string.strip()
> --> 512 data_json = json.loads(re.findall("var info= (.*)", data_text)[0][:-1])
>     513 temp_df = pd.json_normalize(data_json)
>     514 return temp_df
> 
> IndexError: list index out of range
> ```

感谢反馈问题，已修复该问题，升级到 AKShare 1.6.15 版本使用，同时注意文档已更新该接口使用方式：https://www.akshare.xyz/data/bond/bond.html?highlight=bond_zh_cov_info#id23
