### ISSUE TITLE
请问B股的最新历史行情每天什么时候更新

### ISSUE THREAD

**Issue by nbnc003** [akfamily/akshare#2625]
调用B股历史行情，发现下午4点时还没更新当天收盘的，调实时又没必要。
想问下更新时间，方便定时任务设置
另外B股历史行情和实时行情的股票代码不一致，一个带字母一个不带。
感谢。

**Comment by jindaxiang** [comment]
> B股历史行情

具体更新时间可以自行在本地测试下；
B 股 由于数据源来与通过，需要的参数也不同，建议用同一个来源的数据
