### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by shuaixiaoji** [akfamily/akshare#2626]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本
    Linux version 3.10.0-1160.el7.x86_64
3. Python 版本
    Python 3.8.5
4. AKShare 版本
   1.6.15
5. 接口的名称和代码
   stock_new_a_spot_em 返回的上市日期都是“1970-01-01T00:00:00.000Z”
6. 接口报错的截图或代码
   
![image](https://user-images.githubusercontent.com/39050392/173541210-93480e7c-eedd-4cc1-96f2-1478240c603f.png)

7. 期望获得的正确结果
 返回正确的上市日期

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本
>    Linux version 3.10.0-1160.el7.x86_64
> 2. Python 版本
>    Python 3.8.5
> 3. AKShare 版本
>    1.6.15
> 4. 接口的名称和代码
>    stock_new_a_spot_em 返回的上市日期都是“1970-01-01T00:00:00.000Z”
> 5. 接口报错的截图或代码
> 
> ![image](https://user-images.githubusercontent.com/39050392/173541210-93480e7c-eedd-4cc1-96f2-1478240c603f.png)
> 
> 7. 期望获得的正确结果
>    返回正确的上市日期

感谢反馈问题，已修复该问题，升级到 AKShare 1.6.17 版本使用
