### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by yulu0131** [akfamily/akshare#2630]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本:  Ubuntu 22.04 LTS
2. Python 版本: Python 3.9.12
3. AKShare 版本: 1.6.17
4. 接口的名称和代码 </br>
 index_zh_a_hist_min_em(symbol="000300", period="60", start_date="2022-05-08 09:30:00", end_date="2022-06-08 15:00:00")

6. 接口报错的截图或代码
7. 期望获得的正确结果

使用沪深300指数无法获得分时数据，上证50指数（symbol = "000016"）可以正常使用该接口
![image](https://user-images.githubusercontent.com/89432224/173975056-24a9ca8a-5920-4d94-9987-cb1ef4744aba.png)

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本:  Ubuntu 22.04 LTS
> 2. Python 版本: Python 3.9.12
> 3. AKShare 版本: 1.6.17
> 4. 接口的名称和代码 
>    index_zh_a_hist_min_em(symbol="000300", period="60", start_date="2022-05-08 09:30:00", end_date="2022-06-08 15:00:00")
> 5. 接口报错的截图或代码
> 6. 期望获得的正确结果
> 
> 使用沪深300指数无法获得分时数据，上证50指数（symbol = "000016"）可以正常使用该接口 ![image](https://user-images.githubusercontent.com/89432224/173975056-24a9ca8a-5920-4d94-9987-cb1ef4744aba.png)

该接口可以正常运行，主要只能获取近期的数据
