### ISSUE TITLE
2个接口问题及修复建议

### ISSUE THREAD

**Issue by gchuyun** [akfamily/akshare#2636]
1. 文件：/opt/conda/lib/python3.10/site-packages/akshare/stock/stock_board_industry_em.py
    接口：stock_board_industry_name_em

    temp_df["总市值"] = pd.to_numeric(temp_df["总市值"])
    接口获取到的数据会出现‘-’，此处几行转为数值会报错，可以先替换处理。

2. 文件：/opt/conda/lib/python3.10/site-packages/akshare/stock_feature/stock_hist_em.py
    接口：code_id_map_em

    url = "http://80.push2.eastmoney.com/api/qt/clist/get"
    params = {
        "pn": "1",
        "pz": "5000",
        "po": "1",
        "np": "1",
        "ut": "bd1d9ddb04089700cf9c27f6f7426281",
        "fltt": "2",
        "invt": "2",
        "fid": "f3",
        "fs": "m:1 t:2,m:1 t:23",
        "fields": "f12",
        "_": "1623833739532",
    }
    r = requests.get(url, params=params)

    只能获取到的5000条数据，实际有2w多条，造成某些调用它的接口报错，比如：stock_zh_a_hist 002607
    把5000替换为50000即可。

**Comment by jindaxiang** [comment]
> 2\. code_id_map_em

感想反馈问题，已修复该问题，升级到 AKShare 1.6.20 使用
