### ISSUE TITLE
AKShare 指数数据 分时行情数据示例中方法名使用错误

### ISSUE THREAD

**Issue by silenceTiano** [akfamily/akshare#2638]
AKShare 指数数据 分时行情数据示例中方法名使用错误

文档中说明使用的是 `index_zh_a_hist_min_em`

但是在示例中使用的是 `index_zh_a_hist`

导致直接复制会报错且无法使用。

![image](https://user-images.githubusercontent.com/24770698/174233561-c6807832-0f0b-4ef4-bfee-02390ec06626.png)

**Comment by jindaxiang** [comment]
> AKShare 指数数据 分时行情数据示例中方法名使用错误
> 
> 文档中说明使用的是 `index_zh_a_hist_min_em`
> 
> 但是在示例中使用的是 `index_zh_a_hist`
> 
> 导致直接复制会报错且无法使用。
> 
> ![image](https://user-images.githubusercontent.com/24770698/174233561-c6807832-0f0b-4ef4-bfee-02390ec06626.png)

感谢反馈问题，已修复该问题，升级到 AKShare 1.6.20 版本使用
