### ISSUE TITLE
集思录可转债等权指数接口报错（已更新）

### ISSUE THREAD

**Issue by hujian** [akfamily/akshare#2642]
akshare/bond_convert.py的bond_cb_index_jsl接口调用直接报错，错误如下：

  File "bond_convert.py", line 340, in <module>
    bond_cb_index_jsl_df = bond_cb_index_jsl()
  File "bond_convert.py", line 31, in bond_cb_index_jsl
    .strip(";\n\nvar")
  File "<string>", line 0

应该是解析哪里有点问题。

**Comment by hujian** [comment]
操作系统：
```
❯ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H1922
```

python版本：
```
❯ python --version
Python 3.7.3
```

AKShare 版本:
```
❯ pip list | grep akshare
akshare                           1.6.21
```

接口的名称和代码：
```
import akshare as ak
bond_cb_index_jsl_df = ak.bond_cb_index_jsl()
print(bond_cb_index_jsl_df)
```

接口报错的截图或代码:
```
>>> bond_cb_index_jsl_df = ak.bond_cb_index_jsl()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/hujian/anaconda3/envs/py37/lib/python3.7/site-packages/akshare/bond/bond_convert.py", line 31, in bond_cb_index_jsl
    .strip(";\n\nvar")
  File "<string>", line 0

    ^
SyntaxError: unexpected EOF while parsing
```

**Comment by jindaxiang** [comment]
> bond_cb_index_jsl

目前该接口可以正常运行，看看您本地环境配置是否正常：
![image](https://user-images.githubusercontent.com/18234520/174552630-25d1e0ad-d388-4674-8e67-5081defa3684.png)

**Comment by jindaxiang** [comment]
> 操作系统：
> 
> ```
> ❯ sw_vers
> ProductName:	Mac OS X
> ProductVersion:	10.15.7
> BuildVersion:	19H1922
> ```
> 
> python版本：
> 
> ```
> ❯ python --version
> Python 3.7.3
> ```
> 
> AKShare 版本:
> 
> ```
> ❯ pip list | grep akshare
> akshare                           1.6.21
> ```
> 
> 接口的名称和代码：
> 
> ```
> import akshare as ak
> bond_cb_index_jsl_df = ak.bond_cb_index_jsl()
> print(bond_cb_index_jsl_df)
> ```
> 
> 接口报错的截图或代码:
> 
> ```
> >>> bond_cb_index_jsl_df = ak.bond_cb_index_jsl()
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/Users/hujian/anaconda3/envs/py37/lib/python3.7/site-packages/akshare/bond/bond_convert.py", line 31, in bond_cb_index_jsl
>     .strip(";\n\nvar")
>   File "<string>", line 0
> 
>     ^
> SyntaxError: unexpected EOF while parsing
> ```

由于手头没有 Mac 系统，应该是换行符的问题，升级到 AKShare 1.6.24 版本，看看有没有问题？

**Comment by jindaxiang** [comment]
> akshare/bond_convert.py的bond_cb_index_jsl接口调用直接报错，错误如下：
> 
> File "bond_convert.py", line 340, in bond_cb_index_jsl_df = bond_cb_index_jsl() File "bond_convert.py", line 31, in bond_cb_index_jsl .strip(";\n\nvar") File "", line 0
> 
> 应该是解析哪里有点问题。

已修复该问题，升级到 AKShare 1.6.26 版本使用

**Comment by hujian** [comment]
升级到1.6.26就ok了，感谢。

**Comment by jindaxiang** [comment]
> 升级到1.6.26就ok了，感谢。

ok
