### ISSUE TITLE
接口返回数据与输入代码不符

### ISSUE THREAD

**Issue by iYerw** [akfamily/akshare#2646]
**软件版本如下图**
![image](https://user-images.githubusercontent.com/95393100/174554694-1b4cffec-8910-4a80-a432-5226b590e4d5.png)

**遇到的问题**
stock_individual_info_em
stock_zh_a_hist
这两个接口输入代码"000001"返回的都是上证指数，并不是平安银行，如何通过这两个接口获取到平安银行的数据呢？
<img width="802" alt="image" src="https://user-images.githubusercontent.com/95393100/174554883-e3385467-67b4-49e4-a2ea-098316d02913.png">
<img width="983" alt="image" src="https://user-images.githubusercontent.com/95393100/174555940-dfe81196-c310-41c0-be7c-96ead5428e10.png">

**Comment by jindaxiang** [comment]
> stock_individual_info_em

目前测试没有发现相关问题，建议查看下本地的环境配置：
![image](https://user-images.githubusercontent.com/18234520/174578317-11e0cffa-0df1-464d-85ee-27de2f031ce7.png)

**Comment by hundan2020** [comment]
现在我获取到的都是平安银行了 获取不到上证。。
