### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by kingtsi** [akfamily/akshare#2655]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本
2. Python 版本
3. AKShare 版本
4. 接口的名称和代码
5. 接口报错的截图或代码
6. 期望获得的正确结果

windows11
python 3.9 
akshare最新版

import akshare as ak
stock_board_industry_name_em_df = ak.stock_board_industry_name_em()
print(stock_board_industry_name_em_df)

每天9点半前，如果数据没有更新，显示 “-” 则调用会报错，是否可以兼容下，感谢，其他很多类似的接口有同样的问题，可以基于po的这个接口去debug一下。感谢。

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本
> 2. Python 版本
> 3. AKShare 版本
> 4. 接口的名称和代码
> 5. 接口报错的截图或代码
> 6. 期望获得的正确结果
> 
> windows11 python 3.9 akshare最新版
> 
> import akshare as ak stock_board_industry_name_em_df = ak.stock_board_industry_name_em() print(stock_board_industry_name_em_df)
> 
> 每天9点半前，如果数据没有更新，显示 “-” 则调用会报错，是否可以兼容下，感谢，其他很多类似的接口有同样的问题，可以基于po的这个接口去debug一下。感谢。

感谢反馈问题，已修复该问题，升级到 AKShare 1.6.29 使用

**Comment by kingtsi** [comment]
高效，感谢
