### ISSUE TITLE
股东持股明细-十大流通股东 出错了

### ISSUE THREAD

**Issue by toolgood** [akfamily/akshare#2660]
akshare 是最新的

``` python
stock_gdfx_free_holding_detail_em_df = ak.stock_gdfx_free_holding_detail_em(date="20210930")
```
发生异常: ValueError
Length mismatch: Expected axis has 37 elements, new values have 36 elements

**Comment by jindaxiang** [comment]
> ```python
> stock_gdfx_free_holding_detail_em
> ```

感谢反馈问题，已修复该问题，升级到 AKShare 1.6.31 版本使用
