### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by NetCloud2017** [akfamily/akshare#2665]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
windows系统下 ， 我安装 Python 版本 3.10，AKShare 版本也是最新的，遇到期货获取实时行情接口报错。具体如下： 
index.py 
![image](https://user-images.githubusercontent.com/32604559/175607951-cf3a5533-2acf-46ac-879b-0da4b5304a5d.png)

 
![image](https://user-images.githubusercontent.com/32604559/175608649-0d652555-40ed-4e23-9cff-de08f3a3bb1e.png)

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> **描述遇到的问题** windows系统下 ， 我安装 Python 版本 3.10，AKShare 版本也是最新的，遇到期货获取实时行情接口报错。具体如下： index.py ![image](https://user-images.githubusercontent.com/32604559/175607951-cf3a5533-2acf-46ac-879b-0da4b5304a5d.png)
> 
> ![image](https://user-images.githubusercontent.com/32604559/175608649-0d652555-40ed-4e23-9cff-de08f3a3bb1e.png)

接口可以正常运行，请在本地按文档调试编程环境
