### ISSUE TITLE
本地开启网络代理后 接口失效

### ISSUE THREAD

**Issue by nanshens** [akfamily/akshare#2668]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本 windows
3. Python 版本 3.8 
4. AKShare 版本 最新
5. 接口的名称和代码 ak.futures_zh_daily_sina(symbol=code)
6. 接口报错的截图或代码
7. 
![image](https://user-images.githubusercontent.com/29112598/175779171-1d8a82fe-e621-4d7a-92a4-7c64dc5497f1.png)

8. 期望获得的正确结果

**Comment by nanshens** [comment]
是否有考虑抽离代理配置?

**Comment by jindaxiang** [comment]
> 4\. futures_zh_daily_sina

可以尝试降低 urllib3 的版本，暂不考虑代理问题
