### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by NorseLZJ** [akfamily/akshare#2673]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本:win10
2. Python 版本:3.10
3. AKShare 版本:1.6.32
4. 接口的名称和代码:stock_report_fund_hold_detail
5. 接口报错的截图或代码:
![image](https://user-images.githubusercontent.com/52354783/175875564-baa53f3b-087e-4243-8349-268501b2b638.png)

6. 期望获得的正确结果:期望解析正确

**Comment by jindaxiang** [comment]
> 4\. stock_report_fund_hold_detail

感谢反馈问题，已修复该问题，升级到 AKShare 1.6.33 使用
