### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by YLiu4129** [akfamily/akshare#2678]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本: Windows 11
2. Python 版本: 3.7.9
3. AKShare 版本: 1.6.34
4. 接口的名称和代码: currency_time_series  `currency_time_series_df = ak.currency_time_series(base="USD", start_date="2020-02-03", end_date="2020-03-04", api_key="Please put your api key here")`
5. 接口报错的截图或代码: 
![issue](https://user-images.githubusercontent.com/51956278/176618461-2f5379cb-162d-4eda-9e8b-394ab467da80.png)

應該是使用的https://api.currencyscoop.com/v1/timeseries api失效了

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本: Windows 11
> 2. Python 版本: 3.7.9
> 3. AKShare 版本: 1.6.34
> 4. 接口的名称和代码: currency_time_series  `currency_time_series_df = ak.currency_time_series(base="USD", start_date="2020-02-03", end_date="2020-03-04", api_key="Please put your api key here")`
> 5. 接口报错的截图或代码:
>    ![issue](https://user-images.githubusercontent.com/51956278/176618461-2f5379cb-162d-4eda-9e8b-394ab467da80.png)
> 
> 應該是使用的https://api.currencyscoop.com/v1/timeseries api失效了

是的，该网站有问题
