### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by KureiSersen** [akfamily/akshare#2682]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本:mac m1 monterey
2. Python 版本:python3 3.9.13
3. AKShare 版本:1.6.35
4. 接口的名称和代码:
option_finance_board_df = ak.option_finance_board(symbol="华泰柏瑞沪深300ETF期权", end_month="2003")
print(option_finance_board_df)
6. 接口报错的截图或代码:
<img width="909" alt="image" src="https://user-images.githubusercontent.com/48450278/176727528-7c5e7a60-e3b9-42b7-bbf0-c2a0a0ad899b.png">

数据源有问题
<img width="587" alt="image" src="https://user-images.githubusercontent.com/48450278/176736014-0e8e34a5-c686-4c42-99fd-759e5711a50a.png">

8. 期望获得的正确结果:
别报错

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本:mac m1 monterey
> 2. Python 版本:python3 3.9.13
> 3. AKShare 版本:1.6.35
> 4. 接口的名称和代码:
>    option_finance_board_df = ak.option_finance_board(symbol="华泰柏瑞沪深300ETF期权", end_month="2003")
>    print(option_finance_board_df)
> 5. 接口报错的截图或代码:
> 
> <img alt="image" width="909" src="https://user-images.githubusercontent.com/48450278/176727528-7c5e7a60-e3b9-42b7-bbf0-c2a0a0ad899b.png">
> 
> 数据源有问题 <img alt="image" width="587" src="https://user-images.githubusercontent.com/48450278/176736014-0e8e34a5-c686-4c42-99fd-759e5711a50a.png">
> 
> 8. 期望获得的正确结果:
>    别报错

该接口只能后去近期的数据
