### ISSUE TITLE
20150918以前郑商所的仓单日报无法获取

### ISSUE THREAD

**Issue by lijiangxu** [akfamily/akshare#2687]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本
CentOS Linux release 7.8.2003 (Core)

2. Python 版本
Python 3.8.3

4. AKShare 版本
1.6.35

6. 接口的名称和代码
ak.futures_czce_warehouse_receipt(trade_date="20150917")

8. 接口报错的截图或代码
![image](https://user-images.githubusercontent.com/9277020/176879532-d968fff9-8992-4d6a-a363-810a9d031f9d.png)

10. 期望获得的正确结果
![image](https://user-images.githubusercontent.com/9277020/176879776-f9399901-d788-4d56-a6a7-c47b742e914e.png)

**Comment by jindaxiang** [comment]
> 4\. 20150917

数据源无 excel 格式数据
