### ISSUE TITLE
futures_inventory_99 接口出错，无法接通

### ISSUE THREAD

**Issue by danielbill** [akfamily/akshare#2688]
**描述遇到的问题**
1. 操作系统版本 win10
2. Python 版本 3.7
3. AKShare 版本 1.6.36
4. 接口的名称和代码
df = ak.futures_inventory_99(exchange=market, symbol=symbol)

6. 接口报错的截图或代码
![image](https://user-images.githubusercontent.com/6269655/176980838-c06b0c16-1241-475b-8a8e-3ad6fb901428.png)
--
请问，99期货网站的接口是不是关闭了？

**Comment by jindaxiang** [comment]
> 4\. futures_inventory_99

已经在最新版移除该接口，请用 futures_inventory_em 替换
