### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by 1228leo** [akfamily/akshare#2689]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本:   CentOS Linux release 7.8.2003 (Core)
2. Python 版本:   3.8.1
3. AKShare 版本   :   1.6.36
4. 接口的名称和代码   ： stock_hot_rank_wc_df = ak.stock_hot_rank_wc(date="20220701")
5. 接口报错的截图或代码
![image](https://user-images.githubusercontent.com/40904167/176990929-25f616de-0368-4282-8ee7-4266902d1531.png)

7. 期望获得的正确结果
![image](https://user-images.githubusercontent.com/40904167/176990966-064f4303-4a3d-4990-9081-cb2bef81afb8.png)

**Comment by jindaxiang** [comment]
> 4\. stock_hot_rank_wc

接口可以正常访问，请注意访问的频率
