### ISSUE TITLE
futures_symbol_mark 接口 有问题AKShare 接口问题报告

### ISSUE THREAD

**Issue by Tttst00001** [akfamily/akshare#2696]
1. 操作系统版本 => windows server 2012 R2 datacenter
2. Python 版本 => Python 3.10.0
3. AKShare 版本 => akshare 1.6.37
4. 接口的名称 => futures_symbol_mark
5. 问题 => 返回数据乱码

**Comment by jindaxiang** [comment]
> 1. 操作系统版本 => windows server 2012 R2 datacenter
> 2. Python 版本 => Python 3.10.0
> 3. AKShare 版本 => akshare 1.6.37
> 4. 接口的名称 => futures_symbol_mark
> 5. 问题 => 返回数据乱码

感谢反馈问题，经测试在正常系统没有问题，目前已经在代码中增加编码；
建议在本地升级到 Pandas 和 requests 到最新版；同时升级到 AKShare 到 1.6.39 版本

**Comment by Tttst00001** [comment]
牛逼啊!
