### ISSUE TITLE
AKShare 接口问题报告：访问失败

### ISSUE THREAD

**Issue by colin-woodson** [akfamily/akshare#2699]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```
$ sudo pip install akshare --upgrade -i https://pypi.org/simple
[sudo] password for colin: 
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip install --user` instead.
Requirement already up-to-date: akshare in /usr/local/lib/python3.7/site-packages (1.6.40)
Requirement already satisfied, skipping upgrade: html5lib>=1.0.1 in /usr/local/lib/python3.7/site-packages (from akshare) (1.1)
Requirement already satisfied, skipping upgrade: py-mini-racer>=0.6.0 in /usr/local/lib/python3.7/site-packages (from akshare) (0.6.0)
Requirement already satisfied, skipping upgrade: beautifulsoup4>=4.9.1 in /usr/local/lib/python3.7/site-packages (from akshare) (4.9.3)
Requirement already satisfied, skipping upgrade: requests>=2.22.0 in /usr/local/lib/python3.7/site-packages (from akshare) (2.23.0)
Requirement already satisfied, skipping upgrade: openpyxl>=3.0.3 in /usr/local/lib/python3.7/site-packages (from akshare) (3.0.7)
Requirement already satisfied, skipping upgrade: requests-cache>=0.9.3 in /usr/local/lib/python3.7/site-packages (from akshare) (0.9.3)
Requirement already satisfied, skipping upgrade: xlrd>=1.2.0 in /usr/local/lib/python3.7/site-packages (from akshare) (2.0.1)
Requirement already satisfied, skipping upgrade: tqdm>=4.43.0 in /usr/local/lib/python3.7/site-packages (from akshare) (4.62.0)
Requirement already satisfied, skipping upgrade: tabulate>=0.8.6 in /usr/local/lib/python3.7/site-packages (from akshare) (0.8.9)
Requirement already satisfied, skipping upgrade: pypinyin>=0.35.0 in /usr/local/lib/python3.7/site-packages (from akshare) (0.42.0)
Requirement already satisfied, skipping upgrade: pandas>=0.25 in /usr/local/lib64/python3.7/site-packages (from akshare) (1.3.1)
Requirement already satisfied, skipping upgrade: urllib3>=1.25.8 in /usr/local/lib/python3.7/site-packages (from akshare) (1.25.8)
Requirement already satisfied, skipping upgrade: jsonpath>=0.82 in /usr/local/lib/python3.7/site-packages (from akshare) (0.82)
Requirement already satisfied, skipping upgrade: decorator>=4.4.2 in /usr/local/lib/python3.7/site-packages (from akshare) (5.0.9)
Requirement already satisfied, skipping upgrade: lxml>=4.2.1 in /usr/local/lib64/python3.7/site-packages (from akshare) (4.6.3)
Requirement already satisfied, skipping upgrade: websocket-client>=0.56.0 in /usr/local/lib/python3.7/site-packages (from akshare) (1.1.1)
Requirement already satisfied, skipping upgrade: six>=1.9 in /usr/lib/python3.7/site-packages (from html5lib>=1.0.1->akshare) (1.12.0)
Requirement already satisfied, skipping upgrade: webencodings in /usr/local/lib/python3.7/site-packages (from html5lib>=1.0.1->akshare) (0.5.1)
Requirement already satisfied, skipping upgrade: soupsieve>1.2; python_version >= "3.0" in /usr/local/lib/python3.7/site-packages (from beautifulsoup4>=4.9.1->akshare) (2.2.1)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /usr/local/lib/python3.7/site-packages (from requests>=2.22.0->akshare) (2020.4.5.1)
Requirement already satisfied, skipping upgrade: idna<3,>=2.5 in /usr/local/lib/python3.7/site-packages (from requests>=2.22.0->akshare) (2.9)
Requirement already satisfied, skipping upgrade: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/site-packages (from requests>=2.22.0->akshare) (3.0.4)
Requirement already satisfied, skipping upgrade: et-xmlfile in /usr/local/lib/python3.7/site-packages (from openpyxl>=3.0.3->akshare) (1.1.0)
Requirement already satisfied, skipping upgrade: cattrs<2.0,>=1.8 in /usr/local/lib/python3.7/site-packages (from requests-cache>=0.9.3->akshare) (1.10.0)
Requirement already satisfied, skipping upgrade: url-normalize<2.0,>=1.4 in /usr/local/lib/python3.7/site-packages (from requests-cache>=0.9.3->akshare) (1.4.3)
Requirement already satisfied, skipping upgrade: attrs<22.0,>=21.2 in /usr/local/lib/python3.7/site-packages (from requests-cache>=0.9.3->akshare) (21.4.0)
Requirement already satisfied, skipping upgrade: appdirs<2.0.0,>=1.4.4 in /usr/local/lib/python3.7/site-packages (from requests-cache>=0.9.3->akshare) (1.4.4)
Requirement already satisfied, skipping upgrade: numpy>=1.17.3 in /usr/local/lib64/python3.7/site-packages (from pandas>=0.25->akshare) (1.21.1)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/site-packages (from pandas>=0.25->akshare) (2.8.2)
Requirement already satisfied, skipping upgrade: pytz>=2017.3 in /usr/local/lib/python3.7/site-packages (from pandas>=0.25->akshare) (2021.1)
Requirement already satisfied, skipping upgrade: typing_extensions; python_version >= "3.7" and python_version < "3.8" in /usr/local/lib/python3.7/site-packages (from cattrs<2.0,>=1.8->requests-cache>=0.9.3->akshare) (3.10.0.2)

**描述遇到的问题**
1. 操作系统版本：openEuler
2. Python 版本：3.7
3. AKShare 版本：3.10.0.2
4. 接口的名称和代码：stock_hold_num_cninfo
5. 接口报错的截图或代码：
>>> import akshare as ak
>>> stock_hold_num_cninfo_df = ak.stock_hold_num_cninfo(date="20210630")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'akshare' has no attribute 'stock_hold_num_cninfo'
6. 期望获得的正确结果

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> $ sudo pip install akshare --upgrade -i https://pypi.org/simple [sudo] password for colin: WARNING: Running pip install with root privileges is generally not a good idea. Try `pip install --user` instead. Requirement already up-to-date: akshare in /usr/local/lib/python3.7/site-packages (1.6.40) Requirement already satisfied, skipping upgrade: html5lib>=1.0.1 in /usr/local/lib/python3.7/site-packages (from akshare) (1.1) Requirement already satisfied, skipping upgrade: py-mini-racer>=0.6.0 in /usr/local/lib/python3.7/site-packages (from akshare) (0.6.0) Requirement already satisfied, skipping upgrade: beautifulsoup4>=4.9.1 in /usr/local/lib/python3.7/site-packages (from akshare) (4.9.3) Requirement already satisfied, skipping upgrade: requests>=2.22.0 in /usr/local/lib/python3.7/site-packages (from akshare) (2.23.0) Requirement already satisfied, skipping upgrade: openpyxl>=3.0.3 in /usr/local/lib/python3.7/site-packages (from akshare) (3.0.7) Requirement already satisfied, skipping upgrade: requests-cache>=0.9.3 in /usr/local/lib/python3.7/site-packages (from akshare) (0.9.3) Requirement already satisfied, skipping upgrade: xlrd>=1.2.0 in /usr/local/lib/python3.7/site-packages (from akshare) (2.0.1) Requirement already satisfied, skipping upgrade: tqdm>=4.43.0 in /usr/local/lib/python3.7/site-packages (from akshare) (4.62.0) Requirement already satisfied, skipping upgrade: tabulate>=0.8.6 in /usr/local/lib/python3.7/site-packages (from akshare) (0.8.9) Requirement already satisfied, skipping upgrade: pypinyin>=0.35.0 in /usr/local/lib/python3.7/site-packages (from akshare) (0.42.0) Requirement already satisfied, skipping upgrade: pandas>=0.25 in /usr/local/lib64/python3.7/site-packages (from akshare) (1.3.1) Requirement already satisfied, skipping upgrade: urllib3>=1.25.8 in /usr/local/lib/python3.7/site-packages (from akshare) (1.25.8) Requirement already satisfied, skipping upgrade: jsonpath>=0.82 in /usr/local/lib/python3.7/site-packages (from akshare) (0.82) Requirement already satisfied, skipping upgrade: decorator>=4.4.2 in /usr/local/lib/python3.7/site-packages (from akshare) (5.0.9) Requirement already satisfied, skipping upgrade: lxml>=4.2.1 in /usr/local/lib64/python3.7/site-packages (from akshare) (4.6.3) Requirement already satisfied, skipping upgrade: websocket-client>=0.56.0 in /usr/local/lib/python3.7/site-packages (from akshare) (1.1.1) Requirement already satisfied, skipping upgrade: six>=1.9 in /usr/lib/python3.7/site-packages (from html5lib>=1.0.1->akshare) (1.12.0) Requirement already satisfied, skipping upgrade: webencodings in /usr/local/lib/python3.7/site-packages (from html5lib>=1.0.1->akshare) (0.5.1) Requirement already satisfied, skipping upgrade: soupsieve>1.2; python_version >= "3.0" in /usr/local/lib/python3.7/site-packages (from beautifulsoup4>=4.9.1->akshare) (2.2.1) Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /usr/local/lib/python3.7/site-packages (from requests>=2.22.0->akshare) (2020.4.5.1) Requirement already satisfied, skipping upgrade: idna<3,>=2.5 in /usr/local/lib/python3.7/site-packages (from requests>=2.22.0->akshare) (2.9) Requirement already satisfied, skipping upgrade: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/site-packages (from requests>=2.22.0->akshare) (3.0.4) Requirement already satisfied, skipping upgrade: et-xmlfile in /usr/local/lib/python3.7/site-packages (from openpyxl>=3.0.3->akshare) (1.1.0) Requirement already satisfied, skipping upgrade: cattrs<2.0,>=1.8 in /usr/local/lib/python3.7/site-packages (from requests-cache>=0.9.3->akshare) (1.10.0) Requirement already satisfied, skipping upgrade: url-normalize<2.0,>=1.4 in /usr/local/lib/python3.7/site-packages (from requests-cache>=0.9.3->akshare) (1.4.3) Requirement already satisfied, skipping upgrade: attrs<22.0,>=21.2 in /usr/local/lib/python3.7/site-packages (from requests-cache>=0.9.3->akshare) (21.4.0) Requirement already satisfied, skipping upgrade: appdirs<2.0.0,>=1.4.4 in /usr/local/lib/python3.7/site-packages (from requests-cache>=0.9.3->akshare) (1.4.4) Requirement already satisfied, skipping upgrade: numpy>=1.17.3 in /usr/local/lib64/python3.7/site-packages (from pandas>=0.25->akshare) (1.21.1) Requirement already satisfied, skipping upgrade: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/site-packages (from pandas>=0.25->akshare) (2.8.2) Requirement already satisfied, skipping upgrade: pytz>=2017.3 in /usr/local/lib/python3.7/site-packages (from pandas>=0.25->akshare) (2021.1) Requirement already satisfied, skipping upgrade: typing_extensions; python_version >= "3.7" and python_version < "3.8" in /usr/local/lib/python3.7/site-packages (from cattrs<2.0,>=1.8->requests-cache>=0.9.3->akshare) (3.10.0.2)
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本：openEuler
> 2. Python 版本：3.7
> 3. AKShare 版本：3.10.0.2
> 4. 接口的名称和代码：stock_hold_num_cninfo
> 5. 接口报错的截图或代码：
> 
> > > > import akshare as ak
> > > > stock_hold_num_cninfo_df = ak.stock_hold_num_cninfo(date="20210630")
> > > > Traceback (most recent call last):
> > > > File "", line 1, in 
> > > > AttributeError: module 'akshare' has no attribute 'stock_hold_num_cninfo'
> 
> 6. 期望获得的正确结果

请按文档配置系统环境
