### ISSUE TITLE
AKShare 接口问题报告-stock_balance_sheet_by_yearly_em

### ISSUE THREAD

**Issue by YP-Ye** [akfamily/akshare#2700]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本 win10
2. Python 版本  3.8.8
3. AKShare 版本 1.6.40
4. 接口的名称和代码
```
import akshare as ak

stock_balance_sheet_by_yearly_em_df = ak.stock_balance_sheet_by_yearly_em(symbol="SZ000001")
print(stock_balance_sheet_by_yearly_em_df)
```

5. 接口报错的截图或代码
```
Traceback (most recent call last):

  File "<ipython-input-1-153d90327da9>", line 3, in <module>
    stock_balance_sheet_by_yearly_em_df = ak.stock_balance_sheet_by_yearly_em(symbol="SZ000001")

  File "C:\Anaconda3\lib\site-packages\akshare\stock_feature\stock_three_report_em.py", line 68, in stock_balance_sheet_by_yearly_em
    temp_df = pd.DataFrame(data_json["data"])

KeyError: 'data'
```
6. 期望获得的正确结果
尝试了几个银行股和保险股，输出资产负债表时都有这类问题，盼解决。

**Comment by YP-Ye** [comment]
后续发现ak.stock_cash_flow_sheet_by_report_em接口导出现金流量表也有该问题，利润表无问题

**Comment by jindaxiang** [comment]
> stock_balance_sheet_by_yearly_em

感谢反馈问题，已修复该问题，升级到 AKShare 1.6.42 使用

**Comment by AlexLid** [comment]
最新的版本中也是有这个问题，通过源码排查，当公司类型（company_type）为1的时候，会出现此类问题，查询对应的上市公司信息，是退市的状态，返回的结果为：{
   "$types": {
      "System.Object, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089": "1"
   },
   "$type": "1"
}，因此取不到data。

**Comment by AlexLid** [comment]
还有就是利润表、现金流量表和资产负债表中字段代表的含义，在官网没有说明，因为字段很多，只能通过chatgpt来翻译，同时像上面提到的company_type的码值说明也没有。
