### ISSUE TITLE
AKShare 接口问题报告: stock_zh_index_hist_csindex

### ISSUE THREAD

**Issue by xnw176** [akfamily/akshare#2709]
**描述遇到的问题**
1. 操作系统版本.     MAC. OS 12.4
2. Python 版本.      3.8
3. AKShare 版本.    1.6.44
4. 接口的名称和代码.   stock_zh_index_hist_csindex
5. 接口报错的截图或代码 
<img width="720" alt="image" src="https://user-images.githubusercontent.com/82297022/178091004-17c06498-17be-4f68-8252-43496984ceb2.png">

7. 期望获得的正确结果

**Comment by xnw176** [comment]
刚发现问题的原因是中证修改了可查询时间段，以前可以下载5年的数据，现在只能查询60天的数据了。
中证指数的数据东方财富上也有，只是网页链接地址和东方财富其它可查询指数不同，是否可以开发？我可以先整理一下地址规则。

**Comment by jindaxiang** [comment]
> **描述遇到的问题**
> 
> 1. 操作系统版本.     MAC. OS 12.4
> 2. Python 版本.      3.8
> 3. AKShare 版本.    1.6.44
> 4. 接口的名称和代码.   stock_zh_index_hist_csindex
> 5. 接口报错的截图或代码
> 
> <img alt="image" width="720" src="https://user-images.githubusercontent.com/82297022/178091004-17c06498-17be-4f68-8252-43496984ceb2.png">
> 
> 7. 期望获得的正确结果

感谢反馈问题，已经增加文档说明；另外可以用 index_zh_a_hist 来获取相关数据

**Comment by xnw176** [comment]
中证9和字母开头的指数是无法用 index_zh_a_hist 获取的。
我发现这部分的数据东财的网页链接如下。
比如中华半导体芯片990001
http://quote.eastmoney.com/zz/2.990001.html
比如软件指数​H30202
http://quote.eastmoney.com/zz/2.H30202.html
而目前 index_zh_a_hist 获取的地址比如沪深300（000300）是以下地址。
http://quote.eastmoney.com/zs000300.html

可否对接口进行修改或新增一个接口，来获取/zz/2.里面的指数数据，这部分的指数数据很丰富，大部分ETF追踪的是这部分以9和字母开头的中证指数，很有参考意义。

万分感谢。
