### ISSUE TITLE
请求开发从东财获取中证指数的接口

### ISSUE THREAD

**Issue by xnw176** [akfamily/akshare#2712]
**Is your feature request related to a problem? Please describe.**
中证官网对数据获取进行限制，AK接口stock_zh_index_hist_csindex从以前最长可能获取5年数据变成3个月，这样对指数级别的数据已经意义不大了。

**Describe the solution you'd like**
通过东财网站对此部分数据进行获取（注：AK已有接口index_zh_a_hist只能获取部分0和3开头指数的数据，但这部分对整个中证指数来说，只是极少部分，大部分国内ETF实际上是追踪以9和字母开开头的指数）。
东财存放中证http://quote.eastmoney.com/zz/2.990001.html(990001半导体指数)和目前ak获取数据如上证50(http://quote.eastmoney.com/zs000016.html)的网页结构完全相同，仅网页链接不同。

两者数据文件请求也仅仅有secid的区别，一个是secid=2.指数代码，一个是secid=1.指数代码

http://62.push2his.eastmoney.com/api/qt/stock/kline/get?cb=jQuery351045220371430932205_1657500963496&secid=2.990001&ut=fa5fd1943c7b386f172d6893dbfba10b&fields1=f1%2Cf2%2Cf3%2Cf4%2Cf5%2Cf6&fields2=f51%2Cf52%2Cf53%2Cf54%2Cf55%2Cf56%2Cf57%2Cf58%2Cf59%2Cf60%2Cf61&klt=101&fqt=1&beg=0&end=20500101&smplmt=460&lmt=1000000&_=1657500963497

http://47.push2his.eastmoney.com/api/qt/stock/kline/get?cb=jQuery3510302534704641956_1657501723401&secid=1.000016&ut=fa5fd1943c7b386f172d6893dbfba10b&fields1=f1%2Cf2%2Cf3%2Cf4%2Cf5%2Cf6&fields2=f51%2Cf52%2Cf53%2Cf54%2Cf55%2Cf56%2Cf57%2Cf58%2Cf59%2Cf60%2Cf61&klt=101&fqt=1&beg=0&end=20500101&smplmt=460&lmt=1000000&_=1657501723483

万分感谢🙏

**Comment by jindaxiang** [comment]
> **Is your feature request related to a problem? Please describe.** 中证官网对数据获取进行限制，AK接口stock_zh_index_hist_csindex从以前最长可能获取5年数据变成3个月，这样对指数级别的数据已经意义不大了。
> 
> **Describe the solution you'd like** 通过东财网站对此部分数据进行获取（注：AK已有接口index_zh_a_hist只能获取部分0和3开头指数的数据，但这部分对整个中证指数来说，只是极少部分，大部分国内ETF实际上是追踪以9和字母开开头的指数）。 东财存放中证[http://quote.eastmoney.com/zz/2.990001.html(990001半导体指数)和目前ak获取数据如上证50(http://quote.eastmoney.com/zs000016.html)的网页结构完全相同，仅网页链接不同。](http://quote.eastmoney.com/zz/2.990001.html(990001%E5%8D%8A%E5%AF%BC%E4%BD%93%E6%8C%87%E6%95%B0)%E5%92%8C%E7%9B%AE%E5%89%8Dak%E8%8E%B7%E5%8F%96%E6%95%B0%E6%8D%AE%E5%A6%82%E4%B8%8A%E8%AF%8150(http://quote.eastmoney.com/zs000016.html)%E7%9A%84%E7%BD%91%E9%A1%B5%E7%BB%93%E6%9E%84%E5%AE%8C%E5%85%A8%E7%9B%B8%E5%90%8C%EF%BC%8C%E4%BB%85%E7%BD%91%E9%A1%B5%E9%93%BE%E6%8E%A5%E4%B8%8D%E5%90%8C%E3%80%82)
> 
> 两者数据文件请求也仅仅有secid的区别，一个是secid=2.指数代码，一个是secid=1.指数代码
> 
> http://62.push2his.eastmoney.com/api/qt/stock/kline/get?cb=jQuery351045220371430932205_1657500963496&secid=2.990001&ut=fa5fd1943c7b386f172d6893dbfba10b&fields1=f1%2Cf2%2Cf3%2Cf4%2Cf5%2Cf6&fields2=f51%2Cf52%2Cf53%2Cf54%2Cf55%2Cf56%2Cf57%2Cf58%2Cf59%2Cf60%2Cf61&klt=101&fqt=1&beg=0&end=20500101&smplmt=460&lmt=1000000&_=1657500963497
> 
> http://47.push2his.eastmoney.com/api/qt/stock/kline/get?cb=jQuery3510302534704641956_1657501723401&secid=1.000016&ut=fa5fd1943c7b386f172d6893dbfba10b&fields1=f1%2Cf2%2Cf3%2Cf4%2Cf5%2Cf6&fields2=f51%2Cf52%2Cf53%2Cf54%2Cf55%2Cf56%2Cf57%2Cf58%2Cf59%2Cf60%2Cf61&klt=101&fqt=1&beg=0&end=20500101&smplmt=460&lmt=1000000&_=1657501723483
> 
> 万分感谢🙏

感谢反馈问题，升级到 AKShare 1.6.52 后 index_zh_a_hist 支持 990001 symbol 访问
