### ISSUE TITLE
中证整数历史行情获取报错

### ISSUE THREAD

**Issue by Silver-L** [akfamily/akshare#2713]
stock_zh_index_hist_csindex_df = ak.stock_zh_index_hist_csindex(symbol="H30374", start_date="20100101", end_date="20211015")

<img width="988" alt="企业微信20220711-212901@2x" src="https://user-images.githubusercontent.com/38281885/178275360-0ad19330-34a8-467f-977c-3b578e34b97b.png">

**Comment by jindaxiang** [comment]
> stock_zh_index_hist_csindex

该接口由于数据源的限制，目前只能返回最近 60 交易日的数据，请参考文档说明
