### ISSUE TITLE
非常感谢，已可以获取数据。

### ISSUE THREAD

**Issue by xnw176** [akfamily/akshare#2727]
非常感谢，已可以获取数据。

目前只发现有2个0开头的指数000859(中证国企一路一带)，000861(中证央企创新)，实际地址指向zz/2(secid=2)，可以的话有劳做个特例规则。

Thanks a lot.

_Originally posted by @xnw176 in https://github.com/akfamily/akshare/issues/2712#issuecomment-1183834433_

**Comment by jindaxiang** [comment]
> 非常感谢，已可以获取数据。
> 
> 目前只发现有2个0开头的指数000859(中证国企一路一带)，000861(中证央企创新)，实际地址指向zz/2(secid=2)，可以的话有劳做个特例规则。
> 
> Thanks a lot.
> 
> _Originally posted by @xnw176 in [#2712 (comment)](https://github.com/akfamily/akshare/issues/2712#issuecomment-1183834433)_

已修复该问题，升级到 AKShare 1.6.56 版本使用
