### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by cewccc** [akfamily/akshare#2735]
操作系统版本 win10
Python 版本 Python 3.8.8
AKShare 版本 1.6.52
Pandas 版本 1.2.4
接口的名称和代码
ak.futures_dce_position_rank('20220715')
接口报错的截图或代码
BadZipFile                                Traceback (most recent call last)
<ipython-input-68-db497ad2cbba> in <module>
----> 1 ak.futures_dce_position_rank('20220715')

~\anaconda3\lib\site-packages\akshare\futures\cot.py in futures_dce_position_rank(date)
    643     r = requests.post(url, payload, headers=headers)
    644     big_dict = dict()
--> 645     with zipfile.ZipFile(BytesIO(r.content), "r") as z:
    646         for i in z.namelist():
    647             file_name = i.encode('cp437').decode('GBK')

~\anaconda3\lib\zipfile.py in __init__(self, file, mode, compression, allowZip64, compresslevel, strict_timestamps)
   1267         try:
   1268             if mode == 'r':
-> 1269                 self._RealGetContents()
   1270             elif mode in ('w', 'x'):
   1271                 # set the modified flag so central directory gets written

~\anaconda3\lib\zipfile.py in _RealGetContents(self)
   1334             raise BadZipFile("File is not a zip file")
   1335         if not endrec:
-> 1336             raise BadZipFile("File is not a zip file")
   1337         if self.debug > 1:
   1338             print(endrec)

BadZipFile: File is not a zip file

**Comment by jindaxiang** [comment]
> 

大商所的所有接口由于大商所增加了加密方式，暂时无法使用
