### ISSUE TITLE
大连商品交易所的所有接口暂时无法使用，修复后会在此处通知

### ISSUE THREAD

**Issue by jindaxiang** [akfamily/akshare#2737]
接口中包含 dce 的暂时都无法使用

**Comment by yinlinzhan** [comment]
是因为前几天大商所官网打不开造成的吗？大商所的官网现在可以打开了

**Comment by yinlinzhan** [comment]
是因为前几天大商所官网打不开造成的吗？现在大商所的官网可以进去了

**Comment by lijiangxu** [comment]
请问大佬，这个问题是大商所页面是通过cookie做了反爬虫了吧？我看了半天不懂前端的技术有点懵。请问有思路解决嘛，预计要花多久呀~

**Comment by mhr1031** [comment]
大佬 有办法获取外盘分时行情么

**Comment by CharmaineLin** [comment]
大连交易所接口恢复了
