### ISSUE TITLE
stock_zh_a_minute  symbo='sh60004' throw exception

### ISSUE THREAD

**Issue by ghmole** [akfamily/akshare#2766]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本
win10
3. Python 版本 
4.9
5. AKShare 版本
1.6.5.7
7. 接口的名称和代码
code='sh60004'
stock_zh_a_hist_df = ak.stock_zh_a_minute(symbol=code, period='1', adjust='qfq')

9. 接口报错的截图或代码
index not in list exception
11. 期望获得的正确结果

**Comment by jindaxiang** [comment]
> 

目前该接口因为数据源的问题，暂时异常，建议用东财接口替代
