### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by ganxy1028** [akfamily/akshare#2771]
从上交所拿数据的接口，http://query.sse.com.cn/sseQuery/commonQuery.do，实测应该最大只支持返回2000行。
目前 akshare 的处理方法应是 pageHelp.pageSize 设置到10000行，暂时我使用还没遇到问题，但是这个处理是有风险的。

**Comment by jindaxiang** [comment]
> 从上交所拿数据的接口，[http://query.sse.com.cn/sseQuery/commonQuery.do，实测应该最大只支持返回2000行。](http://query.sse.com.cn/sseQuery/commonQuery.do%EF%BC%8C%E5%AE%9E%E6%B5%8B%E5%BA%94%E8%AF%A5%E6%9C%80%E5%A4%A7%E5%8F%AA%E6%94%AF%E6%8C%81%E8%BF%94%E5%9B%9E2000%E8%A1%8C%E3%80%82) 目前 akshare 的处理方法应是 pageHelp.pageSize 设置到10000行，暂时我使用还没遇到问题，但是这个处理是有风险的。

get it
