### ISSUE TITLE
多个函数存在frame.append语法即将失效，需改成pandas.concat的警告。

### ISSUE THREAD

**Issue by Elliont** [akfamily/akshare#2776]
例如：
/akshare/fund/fund_portfolio_em.py
/akshare/futures/futures_roll_yield.py
等等

**Comment by jindaxiang** [comment]
> 例如： /akshare/fund/fund_portfolio_em.py /akshare/futures/futures_roll_yield.py 等等

感谢反馈问题，已修改 fund_portfolio_em.py 和 futures_roll_yield.py 中的问题，其余接口也在陆续修改中
