### ISSUE TITLE
英维财经国际指数接口失效

### ISSUE THREAD

**Issue by windblood** [akfamily/akshare#2777]
如题
另外，网页下拉式国家和地区，第一个参数名称country，输入香港有点怪，还是改一下吧，免得被冲了

**Comment by jindaxiang** [comment]
> 如题 另外，网页下拉式国家和地区，第一个参数名称country，输入香港有点怪，还是改一下吧，免得被冲了

感想反馈问题，已修改相关参数及表述。
该接口需要通过代理才可以访问，可以正常获取数据
