### ISSUE TITLE
可转债实时数据参数需求

### ISSUE THREAD

**Issue by balan123332** [akfamily/akshare#2778]
**我想根据我的需求提两个建议：**
一、我认为在可转债实时数据的获取中，获取该支转债的昨日收盘价是有必要的，可以用于量化参考；
二、增加以1分钟为尺度的成交量的数据会更加方便，现有的volume显示的是当天过去时间段所有的成交量，如果有每分钟的成交量，则可以更灵活的适应更多的需求。
以上两点建议望采纳，谢谢

**Comment by jindaxiang** [comment]
> **我想根据我的需求提两个建议：** 一、我认为在可转债实时数据的获取中，获取该支转债的昨日收盘价是有必要的，可以用于量化参考； 二、增加以1分钟为尺度的成交量的数据会更加方便，现有的volume显示的是当天过去时间段所有的成交量，如果有每分钟的成交量，则可以更灵活的适应更多的需求。 以上两点建议望采纳，谢谢

具体是哪里接口？

**Comment by CNUlichao** [comment]
可转债实时数据有误：
1）bond_zh_hs_cov_spot 函数(新浪财经数据) 返回仅有 377 个可转债，而 bond_cb_jsl 函数(集思录数据) 有 437 个可转债；
2）bond_zh_hs_cov_min 函数，指定 period = '5' 时，深可转债换手率正常，但沪可转债的换手率均是 0

**Comment by jindaxiang** [comment]
> 可转债实时数据有误： 1）bond_zh_hs_cov_spot 函数(新浪财经数据) 返回仅有 377 个可转债，而 bond_cb_jsl 函数(集思录数据) 有 437 个可转债； 2）bond_zh_hs_cov_min 函数，指定 period = '5' 时，深可转债换手率正常，但沪可转债的换手率均是 0

1. 建议用 bond_cb_jsl  接口，相对使用人数更多；
2. bond_zh_hs_cov_min 接口，跟数据源提供的数据是一致的；

**Comment by balan123332** [comment]
> > **我想根据我的需求提两个建议：** 一、我认为在可转债实时数据的获取中，获取该支转债的昨日收盘价是有必要的，可以用于量化参考； 二、增加以1分钟为尺度的成交量的数据会更加方便，现有的volume显示的是当天过去时间段所有的成交量，如果有每分钟的成交量，则可以更灵活的适应更多的需求。 以上两点建议望采纳，谢谢
> 
> 具体是哪里接口？

ak.bond_zh_hs_cov_spot()

**Comment by CNUlichao** [comment]
> 



> > 可转债实时数据有误： 1）bond_zh_hs_cov_spot 函数(新浪财经数据) 返回仅有 377 个可转债，而 bond_cb_jsl 函数(集思录数据) 有 437 个可转债； 2）bond_zh_hs_cov_min 函数，指定 period = '5' 时，深可转债换手率正常，但沪可转债的换手率均是 0
> 
> 1. 建议用 bond_cb_jsl  接口，相对使用人数更多；
> 2. bond_zh_hs_cov_min 接口，跟数据源提供的数据是一致的；

好的，谢谢，建议集思录的 bond_cb_jsl 接口，可以增加使用 selenium 模拟登录的功能，自动获取 cookie，而不需要手动填写
