### ISSUE TITLE
bugs in interface `stock_balance_sheet_by_report_em`

### ISSUE THREAD

**Issue by ppoak** [akfamily/akshare#2782]
When I call the function with the parameter 'sh601878' `ak.stock_balance_sheet_by_report_em('sh601878')`, the bug is reported.

Chip: Mac M1
Python Version: 3.9.13

Produce the bug:

1. Open python console
2. import akshare as ak 
3. ak.stock_balance_sheet_by_report_em('sh601878')

**Expected behavior**

The balance sheet of company sh601878

**Desktop (please complete the following information):**

 - OS: MacOS Monterey 12.4
 - Browser Safari
 - Version 1.6.64

**Additional context**

When I inspect the source code in the function `stock_balance_sheet_by_report_em`, I found that in the first phrase, there is a `company_type` parameter, if the symbol is not started with 'SZ', the `company_type` will be set to 3, which failed and the bug came out. However, when I try to modify the code, set `company_type` to 1 forcibly, it worked out fine. So may be fix the problem with `company_type` will be fine.

**Comment by ppoak** [comment]
Now I find actually most company in financial industry, like security, bank, has the `company_type` 1 or some company on market Shenzhen has the `company_type` 3 (the same as companies on Shanghai market)

**Comment by ppoak** [comment]
OK, actually, after my trials, comes to a conclusion:

1. Bank companies has the parameter `comp_type = 3`
2. Insurance has the parameter `comp_type = 2`
3. Security has the parameter `comp_type = 1`

**Comment by jindaxiang** [comment]
> When I call the function with the parameter 'sh601878' `ak.stock_balance_sheet_by_report_em('sh601878')`, the bug is reported.
> 
> Chip: Mac M1 Python Version: 3.9.13
> 
> Produce the bug:
> 
> 1. Open python console
> 2. import akshare as ak
> 3. ak.stock_balance_sheet_by_report_em('sh601878')
> 
> **Expected behavior**
> 
> The balance sheet of company sh601878
> 
> **Desktop (please complete the following information):**
> 
> * OS: MacOS Monterey 12.4
> * Browser Safari
> * Version 1.6.64
> 
> **Additional context**
> 
> When I inspect the source code in the function `stock_balance_sheet_by_report_em`, I found that in the first phrase, there is a `company_type` parameter, if the symbol is not started with 'SZ', the `company_type` will be set to 3, which failed and the bug came out. However, when I try to modify the code, set `company_type` to 1 forcibly, it worked out fine. So may be fix the problem with `company_type` will be fine.

Thanks for your kind report, we have fixed the bug, please upgrade to AKShare 1.6.66.
