### ISSUE TITLE
建议增加指数基金（不仅仅是指数型-股票）列表

### ISSUE THREAD

**Issue by CaoKang-David** [akfamily/akshare#2791]
首先，非常感谢团队提供这么棒的免费财经工具！
希望团队可以提供更详细的分类指数基金数据。
目前可以从ak.fund_name_em()中获取指数型-股票的基金信息，但该基金类别不包含像商品指数、债券指数等的指数基金。希望团队能提供类似被动指数、增强指数等包括全部指数类型的指数基金信息。
指数基金分类参考页面：http://fund.eastmoney.com/trade/zs.html#zwf_,fr1_051
截图中可以看到指数基金分成了很多类别
![image](https://user-images.githubusercontent.com/19624728/181001671-b31222ff-de82-42e0-af82-f42c443f0430.png)
非常感谢！

**Comment by jindaxiang** [comment]
> 首先，非常感谢团队提供这么棒的免费财经工具！ 希望团队可以提供更详细的分类指数基金数据。 目前可以从ak.fund_name_em()中获取指数型-股票的基金信息，但该基金类别不包含像商品指数、债券指数等的指数基金。希望团队能提供类似被动指数、增强指数等包括全部指数类型的指数基金信息。 指数基金分类参考页面：http://fund.eastmoney.com/trade/zs.html#zwf_,fr1_051 截图中可以看到指数基金分成了很多类别 ![image](https://user-images.githubusercontent.com/19624728/181001671-b31222ff-de82-42e0-af82-f42c443f0430.png) 非常感谢！

感谢反馈问题，目前已新增 fund_info_index_em 接口，详情见文档，升级到 AKShare 1.6.69 版本使用
