### ISSUE TITLE
akshare在armbian上运行失败

### ISSUE THREAD

**Issue by highjim** [akfamily/akshare#2792]
armbian是跑在arm系统上的linux，似乎遇到了与苹果M1一样的问题

>苹果 M1 处理器支持
>AKShare 由于使用 [PyMiniRacer](https://blog.sqreen.com/embedding-javascript-into-python/) 项目来支持在 Python 中运行 JavaScript >代码，所以要完整的使用 AKShare 的全部功能需要安装该库。
>但是由于苹果的 M1 芯片采用 ARM 架构，而 [PyMiniRacer](https://blog.sqreen.com/embedding-javascript-into-python/) 并没有编译相>对应的 版本，所以造成在 M1 芯片的计算机上使用 AKShare 会出问题。

**Comment by jindaxiang** [comment]
> armbian是跑在arm系统上的linux，似乎遇到了与苹果M1一样的问题
> 
> > 苹果 M1 处理器支持
> > AKShare 由于使用 [PyMiniRacer](https://blog.sqreen.com/embedding-javascript-into-python/) 项目来支持在 Python 中运行 JavaScript >代码，所以要完整的使用 AKShare 的全部功能需要安装该库。
> > 但是由于苹果的 M1 芯片采用 ARM 架构，而 [PyMiniRacer](https://blog.sqreen.com/embedding-javascript-into-python/) 并没有编译相>对应的 版本，所以造成在 M1 芯片的计算机上使用 AKShare 会出问题。

暂不支持 M1 以外的 ARM 架构
