### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by bugstest** [akfamily/akshare#2793]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

接口 stock_zh_a_minute 获取 **部分股票**1分钟历史数据时失败，提示 ：
~\anaconda3\lib\site-packages\akshare\stock\stock_zh_a_sina.py in stock_zh_a_minute(symbol, period, adjust)
    356     r = requests.get(url, params=params)
    357     data_text = r.text
--> 358     data_json = json.loads(data_text.split("=(")[1].split(");")[0])
    359     temp_df = pd.DataFrame(data_json).iloc[:, :6]
    360     if temp_df.empty:

IndexError: list index out of range

已测试失败的股票代码为 sz000001，成功的股票代码为sz301306，sh600519，bj871970

1. 操作系统版本:windows 10 
2. Python 版本: 3.8.8
3. AKShare 版本: 1.6.67
4. 接口的名称和代码: stock_zh_a_minute
5. 接口报错的截图或代码: IndexError: list index out of range
6. 期望获得的正确结果: 正常获取数据

**Comment by jindaxiang** [comment]
> sz000001

感谢反馈问题，已修复该问题，升级到 AKShare 1.6.68 使用
