### ISSUE TITLE
建议futures_foreign_commodity_realtime函数取消code到symbol的转换

### ISSUE THREAD

**Issue by WeiZhou2372** [akfamily/akshare#2803]
涉及\futures\futures_hq_sina.py 文件中的151-153行。目前的函数只支持外盘的连续合约，比如说大豆的code是S，返回的是连续合约。但是使用S2211的话，能拉取到数据，但函数在处理的时候会报错。

目前我自己是用如下代码替换，因为我不需要合约的名字，ticker我都认识，所以我是直接删掉了从code到symbol的映射，如果你们有更优雅的方式的话那就更好了：

```   
    # temp_symbol_code_df = futures_hq_subscribe_exchange_symbol()
    # temp_symbol_code_dict = dict(zip(temp_symbol_code_df['code'], temp_symbol_code_df['symbol']))
    data_df["symbol"] = subscribe_list
```

**Comment by jindaxiang** [comment]
> 涉及\futures\futures_hq_sina.py 文件中的151-153行。目前的函数只支持外盘的连续合约，比如说大豆的code是S，返回的是连续合约。但是使用S2211的话，能拉取到数据，但函数在处理的时候会报错。
> 
> 目前我自己是用如下代码替换，因为我不需要合约的名字，ticker我都认识，所以我是直接删掉了从code到symbol的映射，如果你们有更优雅的方式的话那就更好了：
> 
> ```
>     # temp_symbol_code_df = futures_hq_subscribe_exchange_symbol()
>     # temp_symbol_code_dict = dict(zip(temp_symbol_code_df['code'], temp_symbol_code_df['symbol']))
>     data_df["symbol"] = subscribe_list
> ```

感谢反馈问题，该接口目前用于期货外盘数据的获取；获取其他数据请使用相应的接口
