### ISSUE TITLE
涨停分析能否取THS的涨停数据(含'涨停原因')

### ISSUE THREAD

**Issue by ifcheung2012** [akfamily/akshare#2812]
涨停分析能否取THS的涨停数据(含'涨停原因'),目前取的东财的，东财没有‘涨停原因’。

**Comment by jindaxiang** [comment]
> 涨停分析能否取THS的涨停数据(含'涨停原因'),目前取的东财的，东财没有‘涨停原因’。

具体是哪个页面？

**Comment by ifcheung2012** [comment]
> > 涨停分析能否取THS的涨停数据(含'涨停原因'),目前取的东财的，东财没有‘涨停原因’。
> 
> 具体是哪个页面？

http://www.iwencai.com/unifiedwap/result?w=今日涨停；非st&querytype=stock

**Comment by jindaxiang** [comment]
> > > 涨停分析能否取THS的涨停数据(含'涨停原因'),目前取的东财的，东财没有‘涨停原因’。
> > 
> > 
> > 具体是哪个页面？
> 
> [http://www.iwencai.com/unifiedwap/result?w=今日涨停；非st&querytype=stock](http://www.iwencai.com/unifiedwap/result?w=%E4%BB%8A%E6%97%A5%E6%B6%A8%E5%81%9C%EF%BC%9B%E9%9D%9Est&querytype=stock)

该接口属于问财系列，可以利用现有的接口 技术选股 完成相应的操作；暂不考虑新增接口
