### ISSUE TITLE
接口获取的lme铝收盘价数据和实际收盘价数据有所偏差

### ISSUE THREAD

**Issue by txzrfy** [akfamily/akshare#2814]
用接口获取的外盘期货数据的lme铝收盘价数据和实际收盘价数据有所偏差，查证了新浪历史价格我页面和文华财经页面，每天基本收盘价相差2美元左右。

**Comment by jindaxiang** [comment]
> 用接口获取的外盘期货数据的lme铝收盘价数据和实际收盘价数据有所偏差，查证了新浪历史价格我页面和文华财经页面，每天基本收盘价相差2美元左右。

感谢反馈问题；
目前接口设计的原则是跟数据源网站的数据保持一致，关于数据不一致的问题，建议在使用中通过多个数据源对比，也建议用同一个数据源；有条件的建议使用商业数据源以确保数据质量问题
