### ISSUE TITLE
获取成分股时抛出异常

### ISSUE THREAD

**Issue by ifcheung2012** [akfamily/akshare#2815]
本来想先获取ths所有概念，然后获取每个概念下的成分股的，但遍历的时候遇到特定的概念就卡壳儿了，比如下面的这种概念'DRG/DIP'

> import akshare as ak
> 
> ak.stock_board_concept_cons_ths(symbol='DRG/DIP')

---------------------报错如下----------------------------
IndexError                                Traceback (most recent call last)
/var/folders/z8/d___9t814s9g92ttzr6fyhjh0000gn/T/ipykernel_12987/85403759.py in <module>
----> 1 a = ak.stock_board_concept_cons_ths(symbol='DRG/DIP')
      2 a

~/opt/anaconda3/lib/python3.9/site-packages/akshare/stock_feature/stock_board_concept_ths.py in stock_board_concept_cons_ths(symbol)
    143     stock_board_ths_map_df = stock_board_concept_name_ths()
    144     symbol = (
--> 145         stock_board_ths_map_df[stock_board_ths_map_df["概念名称"] == symbol]["网址"]
    146         .values[0]
    147         .split("/")[-2]

IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by ifcheung2012** [comment]
1、知道什么问题了：数据问题 ！
2、我的概念不是取的‘概念时间表’数据 而是取的概念资金流数据 概念资金流数据中概念名称不标准且又没有概念编码，导致获取成分股时 处理的变量stock_board_ths_map_df为空dataframe
    资金流-概念名称：DRG/DIP
    时间表-概念丞丞：DRG/DIP概念
3、这还可以优化下？😂

import akshare as ak
df2 = ak.stock_fund_flow_concept("即时")
df2[50:60]

**Comment by jindaxiang** [comment]
> 

感谢反馈问题，暂不考虑修改接口；
建议在本地通过 概念资金流数据 获取的概念，通过匹配方式，再调用原接口获取数据
