### ISSUE TITLE
fund_rating_all接口数据错误

### ISSUE THREAD

**Issue by h2y** [akfamily/akshare#2821]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本 Darwin 21.5.0 Darwin Kernel Version 21.5.0
2. Python 版本 Python 3.9.13
3. AKShare 版本 8-6 16:06最新版
4. 接口的名称和代码 f = ak.fund_rating_all()
5. 接口报错的截图或代码

```
>>> f[f['代码']=='470018']
        代码        简称 基金经理 基金公司 5星评级家数 上海证券 招商证券 济安金信    手续费       类型
40  470018  汇添富双利债券A  吴江宏  汇添富      1         3    5  0.08%  债券型-混合债
>>> f[f['代码']=='481017']
        代码         简称 基金经理 基金公司 5星评级家数 上海证券 招商证券 济安金信    手续费      类型
29  481017  工银量化策略混合A  张乐涛   工银      1    4    4    5  0.15%  混合型-偏股
```

7. 期望获得的正确结果
<http://fund.eastmoney.com/data/fundrating.html>
![image](https://user-images.githubusercontent.com/12909077/183240534-155ce346-5ab8-44c5-89dc-5546285ec585.png)

1. 481017三个证券评级所在列未对应
2. 470018带有⬇️符号的栏目，没有爬出结果

**Comment by jindaxiang** [comment]
> 470018

感谢反馈问题；已修复该问题，升级到 AKShare 1.6.79 版本使用
