### ISSUE TITLE
currency_hist报错

### ISSUE THREAD

**Issue by csfreebird** [akfamily/akshare#2822]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本: ubuntu 20.04
3. Python 版本: 3.8.10
4. AKShare 版本: 最新版本，测试前刚刚升级过akshare
5. 接口的名称和代码: currency_hist
7. 接口报错的截图或代码
```
>>> import akshare as ak
>>> currency_hist_df = ak.currency_hist(symbol="usd-jpy", start_date="20050101", end_date="20200117")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dean/work/pyenv/quantopianPython/lib/python3.8/site-packages/akshare/fx/currency_investing.py", line 57, in currency_hist
    title = soup.find("h2", attrs={"class": "float_lang_base_1"}).get_text()
AttributeError: 'NoneType' object has no attribute 'get_text'
```

8. 期望获得的正确结果
之前工作正常，最近两天突然报错。

**Comment by newtomblue** [comment]
對~我也有相同問題  AttributeError: 'NoneType' object has no attribute 'get_text'

**Comment by jindaxiang** [comment]
> 對~我也有相同問題 AttributeError: 'NoneType' object has no attribute 'get_text'

目标网页接口调整了

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本: ubuntu 20.04
> 2. Python 版本: 3.8.10
> 3. AKShare 版本: 最新版本，测试前刚刚升级过akshare
> 4. 接口的名称和代码: currency_hist
> 5. 接口报错的截图或代码
> 
> ```
> >>> import akshare as ak
> >>> currency_hist_df = ak.currency_hist(symbol="usd-jpy", start_date="20050101", end_date="20200117")
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/dean/work/pyenv/quantopianPython/lib/python3.8/site-packages/akshare/fx/currency_investing.py", line 57, in currency_hist
>     title = soup.find("h2", attrs={"class": "float_lang_base_1"}).get_text()
> AttributeError: 'NoneType' object has no attribute 'get_text'
> ```
> 
> 8. 期望获得的正确结果
>    之前工作正常，最近两天突然报错。

感谢反馈问题；已修复该问题，升级到 AKShare 1.6.81 版本使用

**Comment by jindaxiang** [comment]
> 那該怎麼修改呢 我一直找方法

感谢反馈问题；已修复该问题，升级到 AKShare 1.6.81 版本使用

**Comment by jindaxiang** [comment]
感谢反馈问题；已修复该问题，升级到 AKShare 1.6.81 版本使用

**Comment by newtomblue** [comment]
可是 ~~~~升级到 AKShare 1.6.81 版本使用後~~~~

index_investing_global_df = ak.index_investing_global(country="美国", index_name="VIX恐慌指数", period="每月", start_date="2005-01-01", end_date="2020-06-05")


TypeError: index_investing_global() got an unexpected keyword argument 'country'

**Comment by newtomblue** [comment]
> > 對~我也有相同問題 AttributeError: 'NoneType' object has no attribute 'get_text'
> 
> 目标网页接口调整了

非常感謝 小伙伴的幫忙~~~
