### ISSUE TITLE
申万历史行情接口问题

### ISSUE THREAD

**Issue by rayzzy** [akfamily/akshare#2823]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本 win10 
2. Python 版本  3.7.6
3. AKShare 版本 '1.6.78'

4. 接口的名称和代码
申万行业历史行情
![image](https://user-images.githubusercontent.com/30099596/183278604-42e5ba48-6408-4b97-9670-b025884c66f8.png)
![image](https://user-images.githubusercontent.com/30099596/183278609-4f960918-1a7b-4d85-815c-eb1b4320726b.png)
![image](https://user-images.githubusercontent.com/30099596/183278640-527670ce-8e8f-4e5b-afa2-f2c5f4aac3e7.png)

5. 接口报错的截图或代码
6. 期望获得的正确结果

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本 win10
> 2. Python 版本  3.7.6
> 3. AKShare 版本 '1.6.78'
> 4. 接口的名称和代码
>    申万行业历史行情
>    ![image](https://user-images.githubusercontent.com/30099596/183278604-42e5ba48-6408-4b97-9670-b025884c66f8.png)
>    ![image](https://user-images.githubusercontent.com/30099596/183278609-4f960918-1a7b-4d85-815c-eb1b4320726b.png)
>    ![image](https://user-images.githubusercontent.com/30099596/183278640-527670ce-8e8f-4e5b-afa2-f2c5f4aac3e7.png)
> 5. 接口报错的截图或代码
> 6. 期望获得的正确结果

参见文档说明

**Comment by xnw176** [comment]
申万网站不提供下载的确是个大问题。
