### ISSUE TITLE
请求在基金数据中提供一个参数，以查询指定基金的数据

### ISSUE THREAD

**Issue by CaoKang-David** [akfamily/akshare#2825]
如题，请求在基金数据中提供一个参数，如基金代码，这样可以指定查询某一支基金的数据，而不是每次都把所有基金的数据都下载下来。
例如，通过这个 fund_open_fund_daily_em_df = ak.fund_open_fund_daily_em() 查询基金的每日净值，返回的结果是所有基金的每日净值，我们希望能够给一个参数，返回指定基金的数据。如， ak.fund_open_fund_daily_em([funds]) funds是指定基金代码列表，能返回funds列表中的基金所对应的数据。

**Comment by jindaxiang** [comment]
> fund_open_fund_daily_em

感谢反馈问题；fund_open_fund_daily_em 函数的请求发送后，目标网站默认返回所有数据，所以通过设置参数并不能提高访问的效率；建议获取数据到本地后进行处理

**Comment by CaoKang-David** [comment]
谢谢您的解答
