### ISSUE TITLE
stock_zt_pool_em(date=‘20170719’) 无返回数据

### ISSUE THREAD

**Issue by Martech123** [akfamily/akshare#2837]
1. inux yangyang-ThinkPad-X1-Carbon-3rd 5.15.0-43-generic #46~20.04.1-Ubuntu SMP Thu Jul 14 15:20:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
2. python 3.8.10
3. akshare 1.6.83
4. stock_zt_pool_em()
6. 接口无返回数据

**Comment by jindaxiang** [comment]
> 

该接口只能返回近期的数据
