### ISSUE TITLE
option_finance_board接口问题

### ISSUE THREAD

**Issue by UserLeeZJ** [akfamily/akshare#2841]
中证1000已经上了,为什么只增加了新浪的数据源
option_finance_board 这个接口还是查不到中证1000期权的合约

**Comment by jindaxiang** [comment]
> 中证1000已经上了,为什么只增加了新浪的数据源 option_finance_board 这个接口还是查不到中证1000期权的合约

感谢反馈问题；升级到 AKShare 1.6.85 版本使用，已新增对中证1000股指期权的支持
