### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by dalongchen** [akfamily/akshare#2847]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```
import akshare as ak
 stock_zh_a_hist_df = ak.stock_zh_a_hist(symbol="000001", period="daily", start_date="20170301", end_date='20210907', adjust="")
AttributeError: module 'akshare' has no attribute 'stock_zh_a_hist'
老师好，为何报错找不到这个属性stock_zh_a_hist。版本为0.6.10

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> import akshare as ak stock_zh_a_hist_df = ak.stock_zh_a_hist(symbol="000001", period="daily", start_date="20170301", end_date='20210907', adjust="") AttributeError: module 'akshare' has no attribute 'stock_zh_a_hist' 老师好，为何报错找不到这个属性stock_zh_a_hist。版本为0.6.10

升级到最新版使用；升级方式参见文档
