### ISSUE TITLE
同花顺概念板块获取数据错误

### ISSUE THREAD

**Issue by flnlucifer** [akfamily/akshare#2852]
版本全部最新

stock_board_concept_name_ths_df = ak.stock_board_concept_name_ths()使用这条代码获取概念板块列表
问题1：这个列表最后一行的代码是什么意义？同花顺软件中的代码是8开头的。
问题2：
把得到的dataframe拉到最下面 会多出几个板块，并且没有日期和成分股数量
![微信图片_20220813192432](https://user-images.githubusercontent.com/8034877/184489193-b7927590-34df-466b-8ca3-c552acfe183d.png)

**Comment by jindaxiang** [comment]
> 版本全部最新
> 
> stock_board_concept_name_ths_df = ak.stock_board_concept_name_ths()使用这条代码获取概念板块列表 问题1：这个列表最后一行的代码是什么意义？同花顺软件中的代码是8开头的。 问题2： 把得到的dataframe拉到最下面 会多出几个板块，并且没有日期和成分股数量 ![微信图片_20220813192432](https://user-images.githubusercontent.com/8034877/184489193-b7927590-34df-466b-8ca3-c552acfe183d.png)

感谢反馈问题，已经在文档接口新增说明
