### ISSUE TITLE
currency_hist升级akshare后再次报错

### ISSUE THREAD

**Issue by csfreebird** [akfamily/akshare#2854]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本: ubuntu 20.04
2. Python 版本: 3.8.10
3. AKShare 版本:  akshare-1.6.89
4. 接口的名称和代码
参数symbol的值为: usd-cny, 使用代理访问
```
def download_huilv_data(start, end, symbol):
    df = ak.currency_hist(symbol=symbol,
                          period="每日",
                          start_date=start.replace('-', ''),
                          end_date=end.replace('-', ''))
    df['代码'] = symbol
    df = df.rename_axis('日期').reset_index(drop=False)
    df['日期'] = df['日期'].map(lambda e: str(e.date()))
    return df
```
5. 接口报错的截图或代码
```
    df = ak.currency_hist(symbol=symbol,
  File "/home/dean/work/pyenv/quantopianPython/lib/python3.8/site-packages/akshare/fx/currency_investing.py", line 85, in currency_hist
    code = currency_hist_area_index_name_code(symbol)
  File "/home/dean/work/pyenv/quantopianPython/lib/python3.8/site-packages/akshare/fx/currency_investing.py", line 57, in currency_hist_area_index_name_code
    data_json = json.loads(data_text)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
6. 期望获得的正确结果

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本: ubuntu 20.04
> 2. Python 版本: 3.8.10
> 3. AKShare 版本:  akshare-1.6.89
> 4. 接口的名称和代码
>    参数symbol的值为: usd-cny, 使用代理访问
> 
> ```
> def download_huilv_data(start, end, symbol):
>     df = ak.currency_hist(symbol=symbol,
>                           period="每日",
>                           start_date=start.replace('-', ''),
>                           end_date=end.replace('-', ''))
>     df['代码'] = symbol
>     df = df.rename_axis('日期').reset_index(drop=False)
>     df['日期'] = df['日期'].map(lambda e: str(e.date()))
>     return df
> ```
> 
> 5. 接口报错的截图或代码
> 
> ```
>     df = ak.currency_hist(symbol=symbol,
>   File "/home/dean/work/pyenv/quantopianPython/lib/python3.8/site-packages/akshare/fx/currency_investing.py", line 85, in currency_hist
>     code = currency_hist_area_index_name_code(symbol)
>   File "/home/dean/work/pyenv/quantopianPython/lib/python3.8/site-packages/akshare/fx/currency_investing.py", line 57, in currency_hist_area_index_name_code
>     data_json = json.loads(data_text)
>   File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
>     return _default_decoder.decode(s)
>   File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> ```
> 
> 6. 期望获得的正确结果

可以正常获取，注意代理的配置且可以加上 try 多试几次

**Comment by csfreebird** [comment]
运行了很多次，不行。我的代理没问题，浏览器可以通过代理访问源网站。
为什么不改用东财的数据源: http://quote.eastmoney.com/forex/USDCNH.html
这并不需要代理啊？
