### ISSUE TITLE
希望添加接口自定义输出参数的功能

### ISSUE THREAD

**Issue by HKevin1993** [akfamily/akshare#2858]
目前akshare获取实时数据、k线数据API的输出参数是固定的，我们能不能在请求时自定义输出参数？因为有些数据并不是我们需要的，获取这些数据浪费资源；而有些我们需要的数据却无法获取，比如一只股票的封单金额

**Comment by jindaxiang** [comment]
> 目前akshare获取实时数据、k线数据API的输出参数是固定的，我们能不能在请求时自定义输出参数？因为有些数据并不是我们需要的，获取这些数据浪费资源；而有些我们需要的数据却无法获取，比如一只股票的封单金额

感谢反馈问题；目前接口都是根据目标网站返回的数据相统一；本身并不生产数据，所以有部分功能暂时不能实现
