### ISSUE TITLE
stock_board_concept_name_ths  接口问题

### ISSUE THREAD

**Issue by ssz25** [akfamily/akshare#2872]
stock_board_concept_name_ths  接口

部分概念数据缺失  大概有10来个

501        None             流感  None  http://q.10jqka.com.cn/gn/detail/code/300038/  300038      
525        None           苹果概念  None  http://q.10jqka.com.cn/gn/detail/code/300309/  300309    
526        None          PM2.5  None  http://q.10jqka.com.cn/gn/detail/code/300134/  300134        
555        None            石墨烯  None  http://q.10jqka.com.cn/gn/detail/code/300337/  300337     
622        None          新能源汽车  None

**Comment by jindaxiang** [comment]
> 

已经在接口中
