### ISSUE TITLE
AKShare 接口问题报告 -

### ISSUE THREAD

**Issue by Astraeux** [akfamily/akshare#2888]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本：Ubuntu 16.04.4 LTS
2. Python 版本：3.7.4
3. AKShare 版本：1.5.4~1.7.4
4. 接口的名称和代码：stock_hk_hist接口，requests.get没设置timeout
5. 接口报错的截图或代码：直接卡死，无报错无返回值
6. 期望获得的正确结果：返回或者报错
7. 建议：增加抓取爬虫的全局超时设置，或者针对单个接口允许自定义超时。

**Comment by cl1515652** [comment]
**基金分红记录错误**

aktools 版本：0.0.69
接口的名称和代码：fund_fh_em 接口
接口报错的截图或代码：返回结果数据中 基金代码 = 008434 分红记录返回24条，实际分红记录 26条
期望获得的正确结果：返回实际分红记录条数
建议：建议新增根据基金编号 查询分红，拆分记录，保证与天天基金页面数据一致
参考页面地址: http://fundf10.eastmoney.com/fhsp_519029.html

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本：Ubuntu 16.04.4 LTS
> 2. Python 版本：3.7.4
> 3. AKShare 版本：1.5.4~1.7.4
> 4. 接口的名称和代码：stock_hk_hist接口，requests.get没设置timeout
> 5. 接口报错的截图或代码：直接卡死，无报错无返回值
> 6. 期望获得的正确结果：返回或者报错
> 7. 建议：增加抓取爬虫的全局超时设置，或者针对单个接口允许自定义超时。

基于目前的开发模式，建议在本地处理

**Comment by jindaxiang** [comment]
> **基金分红记录错误**
> 
> aktools 版本：0.0.69 接口的名称和代码：fund_fh_em 接口 接口报错的截图或代码：返回结果数据中 基金代码 = 008434 分红记录返回24条，实际分红记录 26条 期望获得的正确结果：返回实际分红记录条数 建议：建议新增根据基金编号 查询分红，拆分记录，保证与天天基金页面数据一致 参考页面地址: http://fundf10.eastmoney.com/fhsp_519029.html

感谢反馈问题；已修复改问题，升级到 AKShare 1.7.5 使用

**Comment by Astraeux** [comment]
> > **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> > ```
> > pip install akshare --upgrade  # Python 版本需要大于 3.7
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **描述遇到的问题**
> > 
> > 1. 操作系统版本：Ubuntu 16.04.4 LTS
> > 2. Python 版本：3.7.4
> > 3. AKShare 版本：1.5.4~1.7.4
> > 4. 接口的名称和代码：stock_hk_hist接口，requests.get没设置timeout
> > 5. 接口报错的截图或代码：直接卡死，无报错无返回值
> > 6. 期望获得的正确结果：返回或者报错
> > 7. 建议：增加抓取爬虫的全局超时设置，或者针对单个接口允许自定义超时。
> 
> 基于目前的开发模式，建议在本地处理

请问目前的开发模式是什么意思？
