### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by chenluyj** [akfamily/akshare#2892]
接口: covid_19_risk_area

卫健委疫情数据接口发生了变更
http://103.66.32.242:8005/zwfwMovePortal/interface/interfaceJson
变化为了
http://bmfw.www.gov.cn/bjww/interface/interfaceJson

akshare/event/covid.py 需要更新下

[covid_19_risk_area.txt](https://github.com/akfamily/akshare/files/9412072/covid_19_risk_area.txt)

**Comment by jindaxiang** [comment]
> 接口: covid_19_risk_area
> 
> 卫健委疫情数据接口发生了变更 http://103.66.32.242:8005/zwfwMovePortal/interface/interfaceJson 变化为了 http://bmfw.www.gov.cn/bjww/interface/interfaceJson
> 
> akshare/event/covid.py 需要更新下
> 
> [covid_19_risk_area.txt](https://github.com/akfamily/akshare/files/9412072/covid_19_risk_area.txt)

感谢反馈问题；升级到 AKShare 1.7.6 使用
