### ISSUE TITLE
AKShare 接口数据问题报告

### ISSUE THREAD

**Issue by cl1515652** [akfamily/akshare#2893]
基金分红记录错误

aktools 版本：0.0.69
接口的名称和代码：fund_fh_em 接口
接口报错的截图或代码：返回结果数据中 基金代码 = 008434 分红记录返回24条，实际分红记录 26条
期望获得的正确结果：返回实际分红记录条数
建议：建议新增根据基金编号 查询分红，拆分记录，保证与天天基金页面数据一致
参考页面地址: http://fundf10.eastmoney.com/fhsp_519029.html

**Comment by jindaxiang** [comment]
> 基金分红记录错误
> 
> aktools 版本：0.0.69 接口的名称和代码：fund_fh_em 接口 接口报错的截图或代码：返回结果数据中 基金代码 = 008434 分红记录返回24条，实际分红记录 26条 期望获得的正确结果：返回实际分红记录条数 建议：建议新增根据基金编号 查询分红，拆分记录，保证与天天基金页面数据一致 参考页面地址: http://fundf10.eastmoney.com/fhsp_519029.html

已修复该问题
