### ISSUE TITLE
这个库有什么办法可以异步调用吗

### ISSUE THREAD

**Issue by hejianhui** [akfamily/akshare#2897]
因为这个代码是同步的，没办法加到python的asyncio里面，目前想到的几个方式：
多进程？
多线程？
异步调用aktools接口？

**Comment by hejianhui** [comment]
sorry，我还想问一下，aktools最高支持多少并发

**Comment by jindaxiang** [comment]
> 因为这个代码是同步的，没办法加到python的asyncio里面，目前想到的几个方式： 多进程？ 多线程？ 异步调用aktools接口？

AKShare 本身不支持异步调用，建议通过修改源码完成；AKTools 可以支持，但需要考虑目标服务器的承受能力
