### ISSUE TITLE
申万市场表征/一级行业/风格指数历史数据获取。

### ISSUE THREAD

**Issue by xnw176** [akfamily/akshare#2900]
前段时间申万网站获取历史数据的接口失效（原因可能是网站漏洞，实际上可获取收费的两级行业数据，所以堵上了）。

但免费部分的数据，申万还是给予了下载地址，只是不能用以前选取时间段区的方式下载而已。
现在的下载页地址为
http://www.swsindex.com/idx0110.aspx
<img width="914" alt="image" src="https://user-images.githubusercontent.com/82297022/186795792-b0f37511-ac99-43ea-aa56-fc230e0ad759.png">
一级行业农林牧渔的下载地址为
http://www.swsindex.com/downloadfiles.aspx?swindexcode=801010&type=510&columnid=8890
<img width="914" alt="image" src="https://user-images.githubusercontent.com/82297022/186796006-2cfc2249-e550-471f-9f78-ea9804ee0361.png">

免费部分有申万市场表征/一级行业/风格指数
收费部分需要密码才能进入下载页面

虽然可以手动下载后再用进行数据处理分析，但还是希望能修改已有的申万接口可以把这些免费指数直接读入dataframe.

非常感谢～

**Comment by jindaxiang** [comment]
> 前段时间申万网站获取历史数据的接口失效（原因可能是网站漏洞，实际上可获取收费的两级行业数据，所以堵上了）。
> 
> 但免费部分的数据，申万还是给予了下载地址，只是不能用以前选取时间段区的方式下载而已。 现在的下载页地址为 http://www.swsindex.com/idx0110.aspx <img alt="image" width="914" src="https://user-images.githubusercontent.com/82297022/186795792-b0f37511-ac99-43ea-aa56-fc230e0ad759.png"> 一级行业农林牧渔的下载地址为 http://www.swsindex.com/downloadfiles.aspx?swindexcode=801010&type=510&columnid=8890 <img alt="image" width="914" src="https://user-images.githubusercontent.com/82297022/186796006-2cfc2249-e550-471f-9f78-ea9804ee0361.png">
> 
> 免费部分有申万市场表征/一级行业/风格指数 收费部分需要密码才能进入下载页面
> 
> 虽然可以手动下载后再用进行数据处理分析，但还是希望能修改已有的申万接口可以把这些免费指数直接读入dataframe.
> 
> 非常感谢～

感谢反馈问题；已新增相关接口，升级到 AKShare 1.7.9 使用
