### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by momobabaxx** [akfamily/akshare#2906]
港股个股指标接口失效
接口: stock_hk_eniu_indicator
目标地址: https://eniu.com/gu/hk01093/roe

亿牛网似乎已不再提供数据更新，最新的数据只拿到7月份的。

**Comment by jindaxiang** [comment]
> 港股个股指标接口失效 接口: stock_hk_eniu_indicator 目标地址: https://eniu.com/gu/hk01093/roe
> 
> 亿牛网似乎已不再提供数据更新，最新的数据只拿到7月份的。

感谢反馈问题；已在接口增加说明，后续如果数据源未更新数据，则会移除该接口
