### ISSUE TITLE
AKShare 获取上市公司财报问题报告

### ISSUE THREAD

**Issue by insight-01** [akfamily/akshare#2912]
### 资产负债表-按年度 stock_balance_sheet_by_yearly_em 的问题

**目前问题，貌似只有"银行类"的资产负债表会出现这个问题，我只试了”招商银行，农业银行，建设银行“都有问题，其他上市公司的还没遇到过,求解答，谢谢!**

1. OS : win10
2. Python 版本 : Python 3.10.0
3. AKShare 版本 : akshare  1.7.12
4. 接口的名称和代码 : 资产负债表-按年度 stock_balance_sheet_by_yearly_em
5. 接口报错的截图或代码:
这个是提示的错误：![Snipaste_2022-08-29_17-12-27](https://user-images.githubusercontent.com/79095234/187167178-e7fa6767-d05c-4cd1-8a56-8de7e3953e43.png)
我到里面去打印了下：
![Snipaste_2022-08-29_17-19-06](https://user-images.githubusercontent.com/79095234/187168642-de27d1be-6312-4c19-ac41-bfa1f46f22e7.png)
其他上市公司的正常显示:
![Snipaste_2022-08-29_17-19-21](https://user-images.githubusercontent.com/79095234/187169179-0c3a42e4-5f94-462c-b712-f9ea8ae88e5b.png)

**Comment by jindaxiang** [comment]
> ### 资产负债表-按年度 stock_balance_sheet_by_yearly_em 的问题
> **目前问题，貌似只有"银行类"的资产负债表会出现这个问题，我只试了”招商银行，农业银行，建设银行“都有问题，其他上市公司的还没遇到过,求解答，谢谢!**
> 
> 1. OS : win10
> 2. Python 版本 : Python 3.10.0
> 3. AKShare 版本 : akshare  1.7.12
> 4. 接口的名称和代码 : 资产负债表-按年度 stock_balance_sheet_by_yearly_em
> 5. 接口报错的截图或代码:
>    这个是提示的错误：![Snipaste_2022-08-29_17-12-27](https://user-images.githubusercontent.com/79095234/187167178-e7fa6767-d05c-4cd1-8a56-8de7e3953e43.png)
>    我到里面去打印了下：
>    ![Snipaste_2022-08-29_17-19-06](https://user-images.githubusercontent.com/79095234/187168642-de27d1be-6312-4c19-ac41-bfa1f46f22e7.png)
>    其他上市公司的正常显示:
>    ![Snipaste_2022-08-29_17-19-21](https://user-images.githubusercontent.com/79095234/187169179-0c3a42e4-5f94-462c-b712-f9ea8ae88e5b.png)

感谢反馈问题；已修复该问题，升级到 AKShare 1.7.13 版本使用
