### ISSUE TITLE
crypto_js_spot()报错

### ISSUE THREAD

**Issue by hejianhui** [akfamily/akshare#2915]
crypto_js_spot()报错，以下为代码：
```python
import akshare as ak

crypto_js_spot_df = ak.crypto_js_spot()
print(crypto_js_spot_df)
```
以下为返回结果：
```
Traceback (most recent call last):
  File "/home/kiss/.local/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/kiss/.local/lib/python3.10/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/home/kiss/.local/lib/python3.10/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/home/kiss/.local/lib/python3.10/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kiss/akshare_data/crypto.py", line 3, in <module>
    crypto_js_spot_df = ak.crypto_js_spot()
  File "/home/kiss/.local/lib/python3.10/site-packages/akshare/economic/macro_other.py", line 26, in crypto_js_spot
    data_json = r.json()
  File "/home/kiss/.local/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```
1. Ubuntu 22.04.1 LTS (WSL2)
2. Python3.10.4
3. akshare 1.7.13
4. 加密货币，实时数据； crypto_js_spot()
5. 如上
6. 期望获得datafame

**Comment by jindaxiang** [comment]
> crypto_js_spot()报错，以下为代码：
> 
> ```python
> import akshare as ak
> 
> crypto_js_spot_df = ak.crypto_js_spot()
> print(crypto_js_spot_df)
> ```
> 
> 以下为返回结果：
> 
> ```
> Traceback (most recent call last):
>   File "/home/kiss/.local/lib/python3.10/site-packages/requests/models.py", line 971, in json
>     return complexjson.loads(self.text, **kwargs)
>   File "/home/kiss/.local/lib/python3.10/site-packages/simplejson/__init__.py", line 525, in loads
>     return _default_decoder.decode(s)
>   File "/home/kiss/.local/lib/python3.10/site-packages/simplejson/decoder.py", line 370, in decode
>     obj, end = self.raw_decode(s)
>   File "/home/kiss/.local/lib/python3.10/site-packages/simplejson/decoder.py", line 400, in raw_decode
>     return self.scan_once(s, idx=_w(s, idx).end())
> simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/kiss/akshare_data/crypto.py", line 3, in <module>
>     crypto_js_spot_df = ak.crypto_js_spot()
>   File "/home/kiss/.local/lib/python3.10/site-packages/akshare/economic/macro_other.py", line 26, in crypto_js_spot
>     data_json = r.json()
>   File "/home/kiss/.local/lib/python3.10/site-packages/requests/models.py", line 975, in json
>     raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
> requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> ```
> 
> 1. Ubuntu 22.04.1 LTS (WSL2)
> 2. Python3.10.4
> 3. akshare 1.7.13
> 4. 加密货币，实时数据； crypto_js_spot()
> 5. 如上
> 6. 期望获得datafame

可以正常运行：
![image](https://user-images.githubusercontent.com/18234520/187603110-031adcd3-164c-4b20-b992-48972802c983.png)
