### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by Demme-H** [akfamily/akshare#2920]
同花顺股票热度接口现在只能返回前100个数据。
import akshare as ak

stock_hot_rank_wc_df = ak.stock_hot_rank_wc(date="20210928")
print(stock_hot_rank_wc_df)

能像以前一样返回所有的股票热度吗？

**Comment by jindaxiang** [comment]
> 同花顺股票热度接口现在只能返回前100个数据。 import akshare as ak
> 
> stock_hot_rank_wc_df = ak.stock_hot_rank_wc(date="20210928") print(stock_hot_rank_wc_df)
> 
> 能像以前一样返回所有的股票热度吗？

数据源限制，目前只能返回前 100 个股票
