### ISSUE TITLE
news_economic_baidu数据获取不全

### ISSUE THREAD

**Issue by kingls** [akfamily/akshare#2921]
1. 操作系统版本 Win11
2. Python 版本 3.9.12
3. AKShare 版本 1.7.14
4. 接口的名称和代码 全球宏观-全球宏观事件 news_economic_baidu
5. 问题：这个接口只能截取当日前100条数据（就是原网页中 **查看更多** 之前的数据），例如2022-08-31日只能获取到加拿大第二季度GDP，后面的EIA原油库存数据是拿不到的。
6. 希望获取当日全部数据

**Comment by jindaxiang** [comment]
> 

感谢反馈问题；已修复该问题，升级到 AKShare 1.7.15 版本使用
