### ISSUE TITLE
stock_hot_rank_wc 只能展示100个股票

### ISSUE THREAD

**Issue by dylandadada** [akfamily/akshare#2922]
1. 操作系统版本 Win10 64，macOS Monterey
2. Python 版本 3.9
3. AKShare 版本 1.7.14
4. 接口的名称和代码 股票热度-问财  stock_hot_rank_wc(‘20220901’)
5. 接口报错的截图或代码——
非报错，但是以前可以显示4千只股票，现在只能100.
<img width="743" alt="截屏2022-09-05 00 04 40" src="https://user-images.githubusercontent.com/29272508/188322717-8eab52e7-327a-4a7c-994c-e10df2f20445.png">

6. 期望获得的正确结果 希望可以获取全量而不是只有100只。

**Comment by jindaxiang** [comment]
> 1. 操作系统版本 Win10 64，macOS Monterey
> 2. Python 版本 3.9
> 3. AKShare 版本 1.7.14
> 4. 接口的名称和代码 股票热度-问财  stock_hot_rank_wc(‘20220901’)
> 5. 接口报错的截图或代码——
>    非报错，但是以前可以显示4千只股票，现在只能100.
> 
> <img alt="截屏2022-09-05 00 04 40" width="743" src="https://user-images.githubusercontent.com/29272508/188322717-8eab52e7-327a-4a7c-994c-e10df2f20445.png">
> 
> 6. 期望获得的正确结果 希望可以获取全量而不是只有100只。

由于数据源的限制，目前只能获取前 100 条

**Comment by ItachiHiSky** [comment]
http://ai.iwencai.com/urp/v7/landing/getDataList
这个可以用
