### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by zhangyuanwai** [akfamily/akshare#2927]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

akshare已更新到最新，遇到了集思录可转债查询异常的问题。

**描述遇到的问题**
1. 操作系统版本
windows10
2. Python 版本
3.9.7
3. AKShare 版本
1.7.16
4. 接口的名称和代码
bond_cb_jsl
5. 接口报错的截图或代码
![image](https://user-images.githubusercontent.com/31298446/188582931-d47a19c9-4b61-425f-b556-727e82214639.png)
6. 期望获得的正确结果
望修复，谢谢。

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> akshare已更新到最新，遇到了集思录可转债查询异常的问题。
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本
>    windows10
> 2. Python 版本
>    3.9.7
> 3. AKShare 版本
>    1.7.16
> 4. 接口的名称和代码
>    bond_cb_jsl
> 5. 接口报错的截图或代码
>    ![image](https://user-images.githubusercontent.com/31298446/188582931-d47a19c9-4b61-425f-b556-727e82214639.png)
> 6. 期望获得的正确结果
>    望修复，谢谢。

感谢反馈问题；已修复该问题，升级到 AKShare 1.7.17 版本使用
