### ISSUE TITLE
AKShare stock_lhb_jgmmtj_em 接口问题

### ISSUE THREAD

**Issue by quanplex** [akfamily/akshare#2930]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题** 
1. 操作系统版本 Mac OS 12.0.1
2. Python 版本 python 3.7
3. AKShare 版本 1.7.17
4. 接口的名称和代码 stock_lhb_jgmmtj_em
5. 接口报错的截图或代码

<img width="788" alt="image" src="https://user-images.githubusercontent.com/8213679/188679157-cc19eaee-4473-45f8-8375-2ccbff2b885b.png">

**Comment by quanplex** [comment]
接口信息如下：
ak$stock_lhb_jgmmtj_em(start_date='20220906',end_date='20220906') 报错

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本 Mac OS 12.0.1
> 2. Python 版本 python 3.7
> 3. AKShare 版本 1.7.17
> 4. 接口的名称和代码 stock_lhb_jgmmtj_em
> 5. 接口报错的截图或代码
> 
> <img alt="image" width="788" src="https://user-images.githubusercontent.com/8213679/188679157-cc19eaee-4473-45f8-8375-2ccbff2b885b.png">

感谢反馈问题；已修复该问题，升级到 AKShare 1.7.18 版本使用
