### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by Daydreamer-w** [akfamily/akshare#2941]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本
2. Python 版本 3.8.8
3. AKShare 版本 1.6.8
4. 接口的名称和代码 
接口名称：stock_zh_a_spot_em
代码：
# encoding: utf-8
import akshare as ak

import datetime
import time

from db import writeDB

#  获取上午的日内数据（9：30-11：30）
def getNow():
    # 查询所有股票代码
    while 1 == 1:
        # 获取当前时间戳
        timestamp = datetime.datetime.now()
        print(timestamp)
        if int(timestamp.strftime('%H')) >= 11 and int(timestamp.strftime('%M')) >= 30:
            break
        # 获取当前股票信息
        stock_zh_a_spot_em_df = ak.stock_zh_a_spot_em()
        print(stock_zh_a_spot_em_df)
        stock_code = stock_zh_a_spot_em_df['代码'].tolist()
        stock_name = stock_zh_a_spot_em_df['名称'].tolist()
        price = stock_zh_a_spot_em_df['最新价'].tolist()
        ranges = stock_zh_a_spot_em_df['涨跌幅'].tolist()
        amount = stock_zh_a_spot_em_df['涨跌额'].tolist()
        turnover = stock_zh_a_spot_em_df['成交量'].tolist()
        volume = stock_zh_a_spot_em_df['成交额'].tolist()
        amplitude =stock_zh_a_spot_em_df['振幅'].tolist()
        high = stock_zh_a_spot_em_df['最高'].tolist()
        low = stock_zh_a_spot_em_df['最低'].tolist()
        open = stock_zh_a_spot_em_df['今开'].tolist()
        close = stock_zh_a_spot_em_df['昨收'].tolist()
        turnover_ratio = stock_zh_a_spot_em_df['换手率'].tolist()
        trade = stock_zh_a_spot_em_df['市盈率-动态'].tolist()
        total_market = stock_zh_a_spot_em_df['总市值'].tolist()
        current_market = stock_zh_a_spot_em_df['流通市值'].tolist()
        speed = stock_zh_a_spot_em_df['涨速'].tolist()
        five_range = stock_zh_a_spot_em_df['5分钟涨跌'].tolist()
        sixty_range = stock_zh_a_spot_em_df['60日涨跌幅'].tolist()
        ytd = stock_zh_a_spot_em_df['年初至今涨跌幅'].tolist()
        writeDB(stock_code,stock_name,timestamp,price,ranges,amount,turnover,volume,amplitude,high,low,open,close,turnover_ratio,trade,total_market,current_market,speed,five_range,sixty_range,ytd)
        time.sleep(3) #等待三秒

getNow()
6. 接口报错的截图或代码
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/python3/lib/python3.8/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/local/python3/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/local/python3/lib/python3.8/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.8/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/local/python3/lib/python3.8/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/python3/lib/python3.8/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/python3/lib/python3.8/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/local/python3/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/local/python3/lib/python3.8/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/www/wwwroot/mquant-intraday/main.py", line 45, in <module>
    getNow()
  File "/www/wwwroot/mquant-intraday/main.py", line 20, in getNow
    stock_zh_a_spot_em_df = ak.stock_zh_a_spot_em()
  File "/usr/local/python3/lib/python3.8/site-packages/akshare/stock_feature/stock_hist_em.py", line 32, in stock_zh_a_spot_em
    r = requests.get(url, params=params)
  File "/usr/local/python3/lib/python3.8/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/requests/adapters.py", line 547, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
7. 期望获得的正确结果
您好，我在获取实时数据的时候有时中途会报错，导致获取终止，这是什么原因

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本
> 2. Python 版本 3.8.8
> 3. AKShare 版本 1.6.8
> 4. 接口的名称和代码
>    接口名称：stock_zh_a_spot_em
>    代码：
> 
> # encoding: utf-8
> import akshare as ak
> 
> import datetime import time
> 
> from db import writeDB
> 
> # 获取上午的日内数据（9：30-11：30）
> def getNow(): # 查询所有股票代码 while 1 == 1: # 获取当前时间戳 timestamp = datetime.datetime.now() print(timestamp) if int(timestamp.strftime('%H')) >= 11 and int(timestamp.strftime('%M')) >= 30: break # 获取当前股票信息 stock_zh_a_spot_em_df = ak.stock_zh_a_spot_em() print(stock_zh_a_spot_em_df) stock_code = stock_zh_a_spot_em_df['代码'].tolist() stock_name = stock_zh_a_spot_em_df['名称'].tolist() price = stock_zh_a_spot_em_df['最新价'].tolist() ranges = stock_zh_a_spot_em_df['涨跌幅'].tolist() amount = stock_zh_a_spot_em_df['涨跌额'].tolist() turnover = stock_zh_a_spot_em_df['成交量'].tolist() volume = stock_zh_a_spot_em_df['成交额'].tolist() amplitude =stock_zh_a_spot_em_df['振幅'].tolist() high = stock_zh_a_spot_em_df['最高'].tolist() low = stock_zh_a_spot_em_df['最低'].tolist() open = stock_zh_a_spot_em_df['今开'].tolist() close = stock_zh_a_spot_em_df['昨收'].tolist() turnover_ratio = stock_zh_a_spot_em_df['换手率'].tolist() trade = stock_zh_a_spot_em_df['市盈率-动态'].tolist() total_market = stock_zh_a_spot_em_df['总市值'].tolist() current_market = stock_zh_a_spot_em_df['流通市值'].tolist() speed = stock_zh_a_spot_em_df['涨速'].tolist() five_range = stock_zh_a_spot_em_df['5分钟涨跌'].tolist() sixty_range = stock_zh_a_spot_em_df['60日涨跌幅'].tolist() ytd = stock_zh_a_spot_em_df['年初至今涨跌幅'].tolist() writeDB(stock_code,stock_name,timestamp,price,ranges,amount,turnover,volume,amplitude,high,low,open,close,turnover_ratio,trade,total_market,current_market,speed,five_range,sixty_range,ytd) time.sleep(3) #等待三秒
> 
> getNow() 6. 接口报错的截图或代码 Traceback (most recent call last): File "/usr/local/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen httplib_response = self._make_request( File "/usr/local/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 449, in _make_request six.raise_from(e, None) File "", line 3, in raise_from File "/usr/local/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 444, in _make_request httplib_response = conn.getresponse() File "/usr/local/python3/lib/python3.8/http/client.py", line 1347, in getresponse response.begin() File "/usr/local/python3/lib/python3.8/http/client.py", line 307, in begin version, status, reason = self._read_status() File "/usr/local/python3/lib/python3.8/http/client.py", line 276, in _read_status raise RemoteDisconnected("Remote end closed connection without" http.client.RemoteDisconnected: Remote end closed connection without response
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/usr/local/python3/lib/python3.8/site-packages/requests/adapters.py", line 489, in send resp = conn.urlopen( File "/usr/local/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 787, in urlopen retries = retries.increment( File "/usr/local/python3/lib/python3.8/site-packages/urllib3/util/retry.py", line 550, in increment raise six.reraise(type(error), error, _stacktrace) File "/usr/local/python3/lib/python3.8/site-packages/urllib3/packages/six.py", line 769, in reraise raise value.with_traceback(tb) File "/usr/local/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen httplib_response = self._make_request( File "/usr/local/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 449, in _make_request six.raise_from(e, None) File "", line 3, in raise_from File "/usr/local/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 444, in _make_request httplib_response = conn.getresponse() File "/usr/local/python3/lib/python3.8/http/client.py", line 1347, in getresponse response.begin() File "/usr/local/python3/lib/python3.8/http/client.py", line 307, in begin version, status, reason = self._read_status() File "/usr/local/python3/lib/python3.8/http/client.py", line 276, in _read_status raise RemoteDisconnected("Remote end closed connection without" urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/www/wwwroot/mquant-intraday/main.py", line 45, in getNow() File "/www/wwwroot/mquant-intraday/main.py", line 20, in getNow stock_zh_a_spot_em_df = ak.stock_zh_a_spot_em() File "/usr/local/python3/lib/python3.8/site-packages/akshare/stock_feature/stock_hist_em.py", line 32, in stock_zh_a_spot_em r = requests.get(url, params=params) File "/usr/local/python3/lib/python3.8/site-packages/requests/api.py", line 73, in get return request("get", url, params=params, **kwargs) File "/usr/local/python3/lib/python3.8/site-packages/requests/api.py", line 59, in request return session.request(method=method, url=url, **kwargs) File "/usr/local/python3/lib/python3.8/site-packages/requests/sessions.py", line 587, in request resp = self.send(prep, **send_kwargs) File "/usr/local/python3/lib/python3.8/site-packages/requests/sessions.py", line 701, in send r = adapter.send(request, **kwargs) File "/usr/local/python3/lib/python3.8/site-packages/requests/adapters.py", line 547, in send raise ConnectionError(err, request=request) requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')) 7. 期望获得的正确结果 您好，我在获取实时数据的时候有时中途会报错，导致获取终止，这是什么原因

增加获取数据的时间间隔

**Comment by Daydreamer-w** [comment]
感谢您的回复，由于想要获取实时的数据，我设置的是3秒一次的间隔，如果设置成5秒一次情况能有所改善吗，或者说能不能从代码等其他方面进行改进

**Comment by Daydreamer-w** [comment]
> > **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> > ```
> > pip install akshare --upgrade  # Python 版本需要大于 3.7
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **描述遇到的问题**
> > 
> > 1. 操作系统版本
> > 2. Python 版本 3.8.8
> > 3. AKShare 版本 1.6.8
> > 4. 接口的名称和代码
> >    接口名称：stock_zh_a_spot_em
> >    代码：
> > 
> > # encoding: utf-8
> > import akshare as ak
> > import datetime import time
> > from db import writeDB
> > # 获取上午的日内数据（9：30-11：30）
> > def getNow(): # 查询所有股票代码 while 1 == 1: # 获取当前时间戳 timestamp = datetime.datetime.now() print(timestamp) if int(timestamp.strftime('%H')) >= 11 and int(timestamp.strftime('%M')) >= 30: break # 获取当前股票信息 stock_zh_a_spot_em_df = ak.stock_zh_a_spot_em() print(stock_zh_a_spot_em_df) stock_code = stock_zh_a_spot_em_df['代码'].tolist() stock_name = stock_zh_a_spot_em_df['名称'].tolist() price = stock_zh_a_spot_em_df['最新价'].tolist() ranges = stock_zh_a_spot_em_df['涨跌幅'].tolist() amount = stock_zh_a_spot_em_df['涨跌额'].tolist() turnover = stock_zh_a_spot_em_df['成交量'].tolist() volume = stock_zh_a_spot_em_df['成交额'].tolist() amplitude =stock_zh_a_spot_em_df['振幅'].tolist() high = stock_zh_a_spot_em_df['最高'].tolist() low = stock_zh_a_spot_em_df['最低'].tolist() open = stock_zh_a_spot_em_df['今开'].tolist() close = stock_zh_a_spot_em_df['昨收'].tolist() turnover_ratio = stock_zh_a_spot_em_df['换手率'].tolist() trade = stock_zh_a_spot_em_df['市盈率-动态'].tolist() total_market = stock_zh_a_spot_em_df['总市值'].tolist() current_market = stock_zh_a_spot_em_df['流通市值'].tolist() speed = stock_zh_a_spot_em_df['涨速'].tolist() five_range = stock_zh_a_spot_em_df['5分钟涨跌'].tolist() sixty_range = stock_zh_a_spot_em_df['60日涨跌幅'].tolist() ytd = stock_zh_a_spot_em_df['年初至今涨跌幅'].tolist() writeDB(stock_code,stock_name,timestamp,price,ranges,amount,turnover,volume,amplitude,high,low,open,close,turnover_ratio,trade,total_market,current_market,speed,five_range,sixty_range,ytd) time.sleep(3) #等待三秒
> > getNow() 6. 接口报错的截图或代码 Traceback (most recent call last): File "/usr/local/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen httplib_response = self._make_request( File "/usr/local/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 449, in _make_request six.raise_from(e, None) File "", line 3, in raise_from File "/usr/local/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 444, in _make_request httplib_response = conn.getresponse() File "/usr/local/python3/lib/python3.8/http/client.py", line 1347, in getresponse response.begin() File "/usr/local/python3/lib/python3.8/http/client.py", line 307, in begin version, status, reason = self._read_status() File "/usr/local/python3/lib/python3.8/http/client.py", line 276, in _read_status raise RemoteDisconnected("Remote end closed connection without" http.client.RemoteDisconnected: Remote end closed connection without response
> > During handling of the above exception, another exception occurred:
> > Traceback (most recent call last): File "/usr/local/python3/lib/python3.8/site-packages/requests/adapters.py", line 489, in send resp = conn.urlopen( File "/usr/local/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 787, in urlopen retries = retries.increment( File "/usr/local/python3/lib/python3.8/site-packages/urllib3/util/retry.py", line 550, in increment raise six.reraise(type(error), error, _stacktrace) File "/usr/local/python3/lib/python3.8/site-packages/urllib3/packages/six.py", line 769, in reraise raise value.with_traceback(tb) File "/usr/local/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen httplib_response = self._make_request( File "/usr/local/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 449, in _make_request six.raise_from(e, None) File "", line 3, in raise_from File "/usr/local/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 444, in _make_request httplib_response = conn.getresponse() File "/usr/local/python3/lib/python3.8/http/client.py", line 1347, in getresponse response.begin() File "/usr/local/python3/lib/python3.8/http/client.py", line 307, in begin version, status, reason = self._read_status() File "/usr/local/python3/lib/python3.8/http/client.py", line 276, in _read_status raise RemoteDisconnected("Remote end closed connection without" urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
> > During handling of the above exception, another exception occurred:
> > Traceback (most recent call last): File "/www/wwwroot/mquant-intraday/main.py", line 45, in getNow() File "/www/wwwroot/mquant-intraday/main.py", line 20, in getNow stock_zh_a_spot_em_df = ak.stock_zh_a_spot_em() File "/usr/local/python3/lib/python3.8/site-packages/akshare/stock_feature/stock_hist_em.py", line 32, in stock_zh_a_spot_em r = requests.get(url, params=params) File "/usr/local/python3/lib/python3.8/site-packages/requests/api.py", line 73, in get return request("get", url, params=params, **kwargs) File "/usr/local/python3/lib/python3.8/site-packages/requests/api.py", line 59, in request return session.request(method=method, url=url, **kwargs) File "/usr/local/python3/lib/python3.8/site-packages/requests/sessions.py", line 587, in request resp = self.send(prep, **send_kwargs) File "/usr/local/python3/lib/python3.8/site-packages/requests/sessions.py", line 701, in send r = adapter.send(request, **kwargs) File "/usr/local/python3/lib/python3.8/site-packages/requests/adapters.py", line 547, in send raise ConnectionError(err, request=request) requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')) 7. 期望获得的正确结果 您好，我在获取实时数据的时候有时中途会报错，导致获取终止，这是什么原因
> 
> 增加获取数据的时间间隔

>感谢您的回复，由于想要获取实时的数据，我设置的是3秒一次的间隔，如果设置成5秒一次情况能有所改善吗，或者说能不能从代码等其他方面进行改进

**Comment by Daydreamer-w** [comment]
@jindaxiang 可以通过随机切换User-Agent等方式来处理吗
