### ISSUE TITLE
全球指数数据-英为财情Investing.com 相关的数据请求问题

### ISSUE THREAD

**Issue by c7h12** [akfamily/akshare#2943]
**Describe the bug**

- `index_investing_global_area_index_name_code` 文档中还存在，但是这个接口已经被删除了
<img width="900" alt="image" src="https://user-images.githubusercontent.com/705184/189942496-0b60d06a-ae7f-4a24-9cb1-73ad6bb17e10.png">

- `ak.index_investing_global(symbol="中国", index_name="富时中国A50指数", period="每日", start_date="20100101", end_date="20220808")`  文档中示例参数名不一致，同时访问不了
<img width="1265" alt="image" src="https://user-images.githubusercontent.com/705184/189944443-9674e3e3-005b-4689-bad5-36c75fa7f8f6.png">

- ak.index_investing_global_from_url
 dom中改成`h1`了
<img width="1316" alt="image" src="https://user-images.githubusercontent.com/705184/189942008-dfdd8d04-6318-4d3d-bb91-42e7dc848d04.png">

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jindaxiang** [comment]
> **Describe the bug** A clear and concise description of what the bug is.
> 
> * `index_investing_global_area_index_name_code` 文档中还存在，但是这个接口已经被删除了
> 
> <img alt="image" width="900" src="https://user-images.githubusercontent.com/705184/189942496-0b60d06a-ae7f-4a24-9cb1-73ad6bb17e10.png">
> 
> * `ak.index_investing_global(symbol="中国", index_name="富时中国A50指数", period="每日", start_date="20100101", end_date="20220808")`  文档中示例参数名不一致，同时访问不了
> 
> <img alt="image" width="1265" src="https://user-images.githubusercontent.com/705184/189944443-9674e3e3-005b-4689-bad5-36c75fa7f8f6.png">
> 
> * ak.index_investing_global_from_url
>   dom中改成`h1`了
> 
> <img alt="image" width="1316" src="https://user-images.githubusercontent.com/705184/189942008-dfdd8d04-6318-4d3d-bb91-42e7dc848d04.png">
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
> * OS: [e.g. iOS]
> * Browser [e.g. chrome, safari]
> * Version [e.g. 22]
> 
> **Smartphone (please complete the following information):**
> 
> * Device: [e.g. iPhone6]
> * OS: [e.g. iOS8.1]
> * Browser [e.g. stock browser, safari]
> * Version [e.g. 22]
> 
> **Additional context** Add any other context about the problem here.

请先确认使用的 AKShare 的版本
