### ISSUE TITLE
私募基金数据里可不可以增加管理人诚信信息

### ISSUE THREAD

**Issue by Edison918** [akfamily/akshare#2950]
各位大佬好，最近需要调取私募基金管理人信息公示页面里的‘机构诚信信息’和‘机构提示信息’这两个诚信提示，发现接口没有提供，想问一下可不可以更新一下？还有管理规模区间、注册资本、实缴资本
辛苦大佬

**Comment by jindaxiang** [comment]
> 各位大佬好，最近需要调取私募基金管理人信息公示页面里的‘机构诚信信息’和‘机构提示信息’这两个诚信提示，发现接口没有提供，想问一下可不可以更新一下？还有管理规模区间、注册资本、实缴资本 辛苦大佬

感谢反馈问题；已在接口新增相关字段，升级到 AKShare 1.7.24 版本使用
