### ISSUE TITLE
有基金的详细费率接口吗？

### ISSUE THREAD

**Issue by RunSimple42** [akfamily/akshare#2955]
**Is your feature request related to a problem? Please describe.**
基金基本信息里的手续费没什么指导作用，缺少管理费、托管费这些数据

**Comment by jindaxiang** [comment]
> **Is your feature request related to a problem? Please describe.** 基金基本信息里的手续费没什么指导作用，缺少管理费、托管费这些数据

还没有，后续有相关接口会更新
