### ISSUE TITLE
1.全球指数数据获取的建议2.中债指数获取需求。

### ISSUE THREAD

**Issue by xnw176** [akfamily/akshare#2958]
1.全球指数数据获取的建议
目前AK的的全球指数据来自英维，一是需要代理二是对方服务器也有限制。建议改用东财网站的数据。
东财网页地址如下，比如英国富时100FTSE，规则就是/gb/zs加指数代码，页面也同国内指数类似。
http://quote.eastmoney.com/gb/zsFTSE.html

2.中债指数获取需求
国内债基指数基本是以中债指数为基准，网页如下，请求AK进行新接口开发。非常感谢。
https://yield.chinabond.com.cn/cbweb-mn/indices/single_index_query

**Comment by jindaxiang** [comment]
> 1.全球指数数据获取的建议 目前AK的的全球指数据来自英维，一是需要代理二是对方服务器也有限制。建议改用东财网站的数据。 东财网页地址如下，比如英国富时100FTSE，规则就是/gb/zs加指数代码，页面也同国内指数类似。 http://quote.eastmoney.com/gb/zsFTSE.html
> 
> 2.中债指数获取需求 国内债基指数基本是以中债指数为基准，网页如下，请求AK进行新接口开发。非常感谢。 https://yield.chinabond.com.cn/cbweb-mn/indices/single_index_query

感想反馈问题；
1. 东财的接口数据较少且非正常数据格式
2. 已新增部分接口，目前正在更新中，升级到 AKShare 1.7.26 版本查看
