### ISSUE TITLE
辛苦大佬在amac_manager_classify_info接口再添加如下信息

### ISSUE THREAD

**Issue by Edison918** [akfamily/akshare#2959]
辛苦大佬在amac_manager_classify_info接口再添加如下信息：
‘办公地址’
‘注册资本’
‘实缴资本’
‘全职员工人数’
‘取得基金从业人数’
‘机构网址’
‘是否为符合提供投资交易条件的第三方机构’
‘管理规模区间’
‘机构信息最后更新时间’

感谢各位大佬

**Comment by Edison918** [comment]
另外，现在有‘在管基金数量’，能不能再加一个‘已清算基金数量’

**Comment by jindaxiang** [comment]
> 辛苦大佬在amac_manager_classify_info接口再添加如下信息： ‘办公地址’ ‘注册资本’ ‘实缴资本’ ‘全职员工人数’ ‘取得基金从业人数’ ‘机构网址’ ‘是否为符合提供投资交易条件的第三方机构’ ‘管理规模区间’ ‘机构信息最后更新时间’
> 
> 感谢各位大佬

没有相关的数据
