### ISSUE TITLE
AKShare 接口问题报告 stock_em_qsjy

### ISSUE THREAD

**Issue by zc1028** [akfamily/akshare#2964]
请求 stock_em_qsjy 
返回 远程主机强迫关闭了一个现有的连接

**Comment by jindaxiang** [comment]
> 请求 stock_em_qsjy 返回 远程主机强迫关闭了一个现有的连接

感谢反馈问题；已修改该问题，且修改该接口命名为：stock_qsjy_em；升级到 AKShare 1.7.27 版本使用
