### ISSUE TITLE
接口疑问：关于 fund_etf_hist_sina 返回的复权数据问题

### ISSUE THREAD

**Issue by jenerse** [akfamily/akshare#2968]
fund_etf_hist_sina 接口返回的是不复权的数据，有没有办法获取得到前复权或者后复权的数据？
谢谢

**Comment by jindaxiang** [comment]
> fund_etf_hist_sina 接口返回的是不复权的数据，有没有办法获取得到前复权或者后复权的数据？ 谢谢

数据源没有复权后的数据，暂时没有办法
