### ISSUE TITLE
加密货币历史数据接口失效

### ISSUE THREAD

**Issue by wabbaf** [akfamily/akshare#2978]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```
已开启网络代理，Google以及数据来源目标网站正常访问。同一个设备之前可以正常返回收据，任何代码未改动的情况下某天开始报错，故猜测无关本地网络代理问题。

**描述遇到的问题**
1. 操作系统版本
MacOs 12.6
3. Python 版本
4.10
5. AKShare 版本
1.7.30
6. 接口的名称和代码
ak.crypto_hist
8. 接口报错的截图或代码
![Xnip2022-09-26_01-47-27](https://user-images.githubusercontent.com/30892328/192157609-c49a4a36-f467-4d68-aa8e-c03d0cdc9280.png)

10. 期望获得的正确结果

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> 已开启网络代理，Google以及数据来源目标网站正常访问。同一个设备之前可以正常返回收据，任何代码未改动的情况下某天开始报错，故猜测无关本地网络代理问题。
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本
>    MacOs 12.6
> 2. Python 版本
>    4.10
> 3. AKShare 版本
>    1.7.30
> 4. 接口的名称和代码
>    ak.crypto_hist
> 5. 接口报错的截图或代码
>    ![Xnip2022-09-26_01-47-27](https://user-images.githubusercontent.com/30892328/192157609-c49a4a36-f467-4d68-aa8e-c03d0cdc9280.png)
> 6. 期望获得的正确结果

英为财情的接口暂时不能使用
