### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by lan-slot** [akfamily/akshare#2980]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本 :win10
3. Python 版本 3.8
4. AKShare 版本 最新
5. 接口的名称和代码：A 股个股指标，乐咕乐股-A 股个股指标: 市盈率, 市净率, 股息率
6. 接口报错的截图或代码

官方这个示例，报错：
import akshare as ak

stock_a_lg_indicator_df = ak.stock_a_lg_indicator(symbol="000001")
print(stock_a_lg_indicator_df)

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [15], in <cell line: 3>()
      1 import akshare as ak
----> 3 stock_a_lg_indicator_df = ak.stock_a_lg_indicator(symbol="000001")
      4 print(stock_a_lg_indicator_df)

TypeError: 'DataFrame' object is not callable

8. 期望获得的正确结果

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本 :win10
> 2. Python 版本 3.8
> 3. AKShare 版本 最新
> 4. 接口的名称和代码：A 股个股指标，乐咕乐股-A 股个股指标: 市盈率, 市净率, 股息率
> 5. 接口报错的截图或代码
> 
> 官方这个示例，报错： import akshare as ak
> 
> stock_a_lg_indicator_df = ak.stock_a_lg_indicator(symbol="000001") print(stock_a_lg_indicator_df)
> 
> TypeError Traceback (most recent call last) Input In [15], in <cell line: 3>() 1 import akshare as ak ----> 3 stock_a_lg_indicator_df = ak.stock_a_lg_indicator(symbol="000001") 4 print(stock_a_lg_indicator_df)
> 
> TypeError: 'DataFrame' object is not callable
> 
> 8. 期望获得的正确结果

接口可以正常使用；建议升级到 AKShare 1.7.31 使用

**Comment by ISayTT** [comment]
你好，大佬，请问如何更新到1.7.31呢？

**Comment by jindaxiang** [comment]
> 你好，大佬，请问如何更新到1.7.31呢？

参见文档的安装部分
