### ISSUE TITLE
ak.stock_zh_ah_daily接口A股问题

### ISSUE THREAD

**Issue by Cyiming** [akfamily/akshare#2984]
港股可以直接获取  沪深无法获取 如600993 换成sh600993 SH600993 还是sh:600993都不行

**Comment by jindaxiang** [comment]
> 港股可以直接获取 沪深无法获取 如600993 换成sh600993 SH600993 还是sh:600993都不行

该接口只能通过港股代码获取，参见文档对该接口的说明，同时升级到最新版，已经对接口进行改动

**Comment by Cyiming** [comment]
> 

了解了 但我是刚安装的 看的也是最新文档  另外请教现在有接口能获取A+H历史行情么 

![image](https://user-images.githubusercontent.com/45073586/193000413-9d705ef2-1ed1-43b2-b236-f63326573bf2.png)
