### ISSUE TITLE
ak.bond_investing_global 全球债券行情数据 - 英为财情Investing.com 接口问题

### ISSUE THREAD

**Issue by qmaxzh** [akfamily/akshare#2990]
ak.bond_investing_global(
        country="中国", index_name="中国1年期国债", period="每周",
        start_date="20000101", end_date="20200606"
    )

获取以上债券数据报错： ValueError: No tables found。 测试源代码 bond_investing.py，第104行session res status_code 是403.

操作系统版本
Ubuntu Server v20.04

Python 版本
Python 3.7

AKShare 版本
akshare version: 1.7.32

**Comment by jindaxiang** [comment]
> bond_investing_global

该接口暂时不能获取数据
