### ISSUE TITLE
建议增加港股通汇率数据

### ISSUE THREAD

**Issue by Cyiming** [akfamily/akshare#2998]
数据有每日参考汇率 每日结算汇率

数据源：
深港通：https://www.szse.cn/szhk/hkbussiness/exchangerate/index.html
沪港通：http://www.sse.com.cn/services/hkexsc/disclo/ratios/

**Comment by jindaxiang** [comment]
> 数据有每日参考汇率 每日结算汇率
> 
> 数据源： 深港通：https://www.szse.cn/szhk/hkbussiness/exchangerate/index.html 沪港通：http://www.sse.com.cn/services/hkexsc/disclo/ratios/

感谢提供数据源；升级到 AKShare 1.7.39 版本使用，文档见：https://www.akshare.xyz/data/stock/stock.html?highlight=stock_sgt_settlement_exchange_rate_szse#id106
