### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by Master-Chi** [akfamily/akshare#3004]
**描述遇到的问题**
1. 操作系统版本
    win11，pycharm
2. Python 版本
    3.9.5
3. AKShare 版本
    1.7.40
4. 接口的名称和代码
    ak.stock_financial_hk_report_em(stock="00700", symbol="资产负债表", indicator="年度")
    ak.stock_financial_hk_analysis_indicator_em(symbol="00700", indicator="年度")
5. 接口报错的截图或代码
    **错误信息：**
    Traceback (most recent call last):
  File "D:\量化分析\main.py", line 131, in <module>
    stock_financial_hk_report_em(stock="00700", symbol="资产负债表", indicator="年度")
  File "D:\量化分析\main.py", line 76, in stock_financial_hk_report_em
    stock_financial_hk_report_em_df = ak.stock_financial_hk_report_em(stock=stock, symbol=symbol, indicator=indicator)
  File "D:\量化分析\venv\lib\site-packages\akshare\stock_fundamental\stock_finance_hk.py", line 40, in stock_financial_hk_report_em
    temp_df = pd.DataFrame(eval(r.text)["data"])
  File "<string>", line 1
    <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
    ^
SyntaxError: invalid syntax
6. 期望获得的正确结果

**Comment by jindaxiang** [comment]
> **描述遇到的问题**
> 
> 1. 操作系统版本
>    win11，pycharm
> 2. Python 版本
>    3.9.5
> 3. AKShare 版本
>    1.7.40
> 4. 接口的名称和代码
>    ak.stock_financial_hk_report_em(stock="00700", symbol="资产负债表", indicator="年度")
>    ak.stock_financial_hk_analysis_indicator_em(symbol="00700", indicator="年度")
> 5. 接口报错的截图或代码
>    **错误信息：**
>    Traceback (most recent call last):
>    File "D:\量化分析\main.py", line 131, in 
>    stock_financial_hk_report_em(stock="00700", symbol="资产负债表", indicator="年度")
>    File "D:\量化分析\main.py", line 76, in stock_financial_hk_report_em
>    stock_financial_hk_report_em_df = ak.stock_financial_hk_report_em(stock=stock, symbol=symbol, indicator=indicator)
>    File "D:\量化分析\venv\lib\site-packages\akshare\stock_fundamental\stock_finance_hk.py", line 40, in stock_financial_hk_report_em
>    temp_df = pd.DataFrame(eval(r.text)["data"])
>    File "", line 1
>     
>    ^
>    SyntaxError: invalid syntax
> 6. 期望获得的正确结果

数据源暂未更新，等数据源恢复后再测试能否获取数据；数据源参见文档
