### ISSUE TITLE
关于港股个股指标接口

### ISSUE THREAD

**Issue by inspirits** [akfamily/akshare#3009]
你好，
之前获取港股个股指标使用的接口是 stock_hk_eniu_indicator ，但已经失效，现在发现百度股市通里面有相关数据，不知道是否可以作为数据源使用呢？
感谢。

以腾讯为例
[腾讯](https://gushitong.baidu.com/stock/hk-00700)
![image](https://user-images.githubusercontent.com/114276252/193507651-b2726b13-a02c-4dfd-a184-7ad026471703.png)

**Comment by jindaxiang** [comment]
> 你好， 之前获取港股个股指标使用的接口是 stock_hk_eniu_indicator ，但已经失效，现在发现百度股市通里面有相关数据，不知道是否可以作为数据源使用呢？ 感谢。
> 
> 以腾讯为例 [腾讯](https://gushitong.baidu.com/stock/hk-00700) ![image](https://user-images.githubusercontent.com/114276252/193507651-b2726b13-a02c-4dfd-a184-7ad026471703.png)

感谢反馈问题；已新增 stock_hk_valuation_baidu 接口，升级到 AKShare 1.7.45 版本使用

**Comment by inspirits** [comment]
感谢大大，但现在接口没有包括symbol 参数，请问是不是bug？
