### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by freelancerhc** [akfamily/akshare#3014]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本
    MacOS Monterey 12.6 on Macbook Pro M1
2. Python 版本
    3.10.5
3. AKShare 版本
    1.7.42
4. 接口的名称和代码
    index_investing_global
    index_investing_global_from_url
5. 接口报错的截图或代码
```
index_investing_global_df = ak.index_investing_global(area="中国", symbol="富时中国A50指数", period="每日", start_date="20100101", end_date="20220808")
index_investing_global_df = ak.index_investing_global_from_url(url="https://www.investing.com/indices/us-spx-500", period="每日", start_date="19900101", end_date="20210909")
```
<img width="1560" alt="image" src="https://user-images.githubusercontent.com/13825798/194090291-6fadbf39-0a0a-4de1-b25d-af354cfcc33a.png">

6. 期望获得的正确结果
    正常返回结果

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本
>    MacOS Monterey 12.6 on Macbook Pro M1
> 2. Python 版本
>    3.10.5
> 3. AKShare 版本
>    1.7.42
> 4. 接口的名称和代码
>    index_investing_global
>    index_investing_global_from_url
> 5. 接口报错的截图或代码
> 
> ```
> index_investing_global_df = ak.index_investing_global(area="中国", symbol="富时中国A50指数", period="每日", start_date="20100101", end_date="20220808")
> index_investing_global_df = ak.index_investing_global_from_url(url="https://www.investing.com/indices/us-spx-500", period="每日", start_date="19900101", end_date="20210909")
> ```
> 
> <img alt="image" width="1560" src="https://user-images.githubusercontent.com/13825798/194090291-6fadbf39-0a0a-4de1-b25d-af354cfcc33a.png">
> 
> 6. 期望获得的正确结果
>    正常返回结果

英为财情的接口暂时不能使用
