### ISSUE TITLE
FAILED: 信创 - 'NoneType' object has no attribute 'find' 

### ISSUE THREAD

**Issue by clm971910** [akfamily/akshare#3018]
1. 操作系统版本  ： macOS 12.5.1
3. Python 版本 :  Python 3.8.13
4. AKShare 版本 :  akshare-1.7.43 
5. 接口的名称和代码 :   ak.stock_board_concept_hist_ths
6. 接口报错的截图或代码

错误代码：
akshare/stock_feature/stock_board_concept_ths.py  第 251 行

错误信息：
FAILED: 信创 - 'NoneType' object has no attribute 'find'                                                                           
FAILED: 空气能热泵 - 'NoneType' object has no attribute 'find'
 FAILED: 先进封装（Chiplet） - 'NoneType' object has no attribute 'find'
 FAILED: 减速器 - 'NoneType' object has no attribute 'find'
FAILED: TOPCON电池 - 'NoneType' object has no attribute 'find'
FAILED: 钙钛矿电池 - 'NoneType' object has no attribute 'find'
FAILED: 生物质能发电 - 'NoneType' object has no attribute 'find'
FAILED: 一体化压铸 - 'NoneType' object has no attribute 'find'
FAILED: 高压快充 - 'NoneType' object has no attribute 'find'
FAILED: 虚拟电厂 - 'NoneType' object has no attribute 'find'
FAILED: 钒电池 - 'NoneType' object has no attribute 'find'
FAILED: 宠物经济 - 'NoneType' object has no attribute 'find'
FAILED: 首发新股 - 'NoneType' object has no attribute 'find'
FAILED: 机器视觉 - 'NoneType' object has no attribute 'find'
FAILED: 光热发电 - 'NoneType' object has no attribute 'find'

8. 期望获得的正确结果
    不要报错

**Comment by jindaxiang** [comment]
> 4\. stock_board_concept_hist_ths

建议在本地用 try ... except 处理

**Comment by clm971910** [comment]
好的 我自己这边处理一下
