### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by wudaweixxx** [akfamily/akshare#3037]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本：win10
2. Python 版本:3.9.7
3. AKShare 版本:1.7.50
4. 接口的名称和代码: stock_a_lg_indicator
5. 接口报错的截图或代码
![image](https://user-images.githubusercontent.com/67285482/195972503-8b8fd26b-5011-46f2-801b-d0f83e09417a.png)
![image](https://user-images.githubusercontent.com/67285482/195972531-004c3c2a-4af1-4e3b-9dc6-5020b9ed84ff.png)

7. 期望获得的正确结果
    该接口已经失效，烦请修复。

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本：win10
> 2. Python 版本:3.9.7
> 3. AKShare 版本:1.7.50
> 4. 接口的名称和代码: stock_a_lg_indicator
> 5. 接口报错的截图或代码
>    ![image](https://user-images.githubusercontent.com/67285482/195972503-8b8fd26b-5011-46f2-801b-d0f83e09417a.png)
>    ![image](https://user-images.githubusercontent.com/67285482/195972531-004c3c2a-4af1-4e3b-9dc6-5020b9ed84ff.png)
> 6. 期望获得的正确结果
>    该接口已经失效，烦请修复。

感谢反馈问题；已修改该问题，升级到 AKShare 1.7.51 版本使用
