### ISSUE TITLE
升级1.7.53, [接口报错]stock_a_lg_indicator

### ISSUE THREAD

**Issue by OatLatte** [akfamily/akshare#3046]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**

1. 操作系统版本 

win 11

4. Python 版本 

3.9.7

6. AKShare 版本 

1.7.53

7. 接口的名称和代码 

stock_a_lg_indicator

8. 接口报错的截图或代码

![image](https://user-images.githubusercontent.com/103306071/196047185-4760076f-a58f-42eb-b8c2-06a3867976c6.png)

9. 期望获得的正确结果

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本
> 
> win 11
> 
> 4. Python 版本
> 
> 3.9.7
> 
> 6. AKShare 版本
> 
> 1.7.53
> 
> 7. 接口的名称和代码
> 
> stock_a_lg_indicator
> 
> 8. 接口报错的截图或代码
> 
> ![image](https://user-images.githubusercontent.com/103306071/196047185-4760076f-a58f-42eb-b8c2-06a3867976c6.png)
> 
> 9. 期望获得的正确结果

感谢反馈问题；已修复该问题，升级到 AKShare 1.7.54 版本使用
