### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by AntonioSu** [akfamily/akshare#3047]
这个代码下：akshare/stock_feature/stock_a_indicator.py，通过如下url无法获取到信息https://www.legulegu.com/s/base-info/{symbol}
code:
`stock_a_indicator_df = ak.stock_a_lg_indicator(symbol='000001')
print(stock_a_indicator_df)`
![image](https://user-images.githubusercontent.com/18456646/196109767-327c6332-89f0-4a54-ac7d-069374deb80c.png)

**Comment by jindaxiang** [comment]
> 这个代码下：akshare/stock_feature/stock_a_indicator.py，通过如下url无法获取到信息[https://www.legulegu.com/s/base-info/{symbol}](https://www.legulegu.com/s/base-info/%7Bsymbol%7D) code: `stock_a_indicator_df = ak.stock_a_lg_indicator(symbol='000001') print(stock_a_indicator_df)` ![image](https://user-images.githubusercontent.com/18456646/196109767-327c6332-89f0-4a54-ac7d-069374deb80c.png)

感谢反馈问题；已修复该问题，升级到 AKShare 1.7.54 版本使用
