### ISSUE TITLE
AttributeError: type object 'Placeholder' has no attribute 'loads'

### ISSUE THREAD

**Issue by RogueJin** [akfamily/akshare#3048]
**描述遇到的问题**
1. 操作系统版本
Monterey ver 12.6 Apple M2

2. 日志
% pip install akshare --upgrade
Requirement already satisfied: akshare in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (1.7.53)
Requirement already satisfied: html5lib>=1.0.1 in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from akshare) (1.1)
Requirement already satisfied: requests-cache>=0.9.3 in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from akshare) (0.9.6)
Requirement already satisfied: decorator>=4.4.2 in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from akshare) (5.1.1)
Requirement already satisfied: pypinyin>=0.35.0 in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from akshare) (0.47.1)
Requirement already satisfied: beautifulsoup4>=4.9.1 in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from akshare) (4.11.1)
Requirement already satisfied: lxml>=4.2.1 in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from akshare) (4.9.1)
Requirement already satisfied: xlrd>=1.2.0 in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from akshare) (2.0.1)
Requirement already satisfied: urllib3>=1.25.8 in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from akshare) (1.26.11)
Requirement already satisfied: openpyxl>=3.0.3 in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from akshare) (3.0.10)
Requirement already satisfied: requests>=2.22.0 in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from akshare) (2.28.1)
Requirement already satisfied: jsonpath>=0.82 in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from akshare) (0.82)
Requirement already satisfied: pandas>=0.25 in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from akshare) (1.4.3)
Requirement already satisfied: websocket-client>=0.56.0 in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from akshare) (0.57.0)
Requirement already satisfied: cfscrape>=2.1.1 in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from akshare) (2.1.1)
Requirement already satisfied: tabulate>=0.8.6 in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from akshare) (0.8.10)
Requirement already satisfied: tqdm>=4.43.0 in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from akshare) (4.64.0)
Requirement already satisfied: py-mini-racer>=0.6.0 in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from akshare) (0.6.0)
Requirement already satisfied: soupsieve>1.2 in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from beautifulsoup4>=4.9.1->akshare) (2.3.2.post1)
Requirement already satisfied: webencodings in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from html5lib>=1.0.1->akshare) (0.5.1)
Requirement already satisfied: six>=1.9 in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from html5lib>=1.0.1->akshare) (1.16.0)
Requirement already satisfied: et-xmlfile in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from openpyxl>=3.0.3->akshare) (1.1.0)
Requirement already satisfied: pytz>=2020.1 in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from pandas>=0.25->akshare) (2022.1)
Requirement already satisfied: python-dateutil>=2.8.1 in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from pandas>=0.25->akshare) (2.8.2)
Requirement already satisfied: numpy>=1.20.0 in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from pandas>=0.25->akshare) (1.23.1)
Requirement already satisfied: charset-normalizer<3,>=2 in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from requests>=2.22.0->akshare) (2.1.0)
Requirement already satisfied: certifi>=2017.4.17 in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from requests>=2.22.0->akshare) (2022.6.15)
Requirement already satisfied: idna<4,>=2.5 in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from requests>=2.22.0->akshare) (3.3)
Requirement already satisfied: url-normalize>=1.4 in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from requests-cache>=0.9.3->akshare) (1.4.3)
Requirement already satisfied: cattrs>=1.8 in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from requests-cache>=0.9.3->akshare) (22.2.0)
Requirement already satisfied: appdirs>=1.4.4 in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from requests-cache>=0.9.3->akshare) (1.4.4)
Requirement already satisfied: attrs>=21.2 in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from requests-cache>=0.9.3->akshare) (22.1.0)
Requirement already satisfied: exceptiongroup in ./.pyenv/versions/3.9.1/lib/python3.9/site-packages (from cattrs>=1.8->requests-cache>=0.9.3->akshare) (1.0.0rc9)
% python                       
Python 3.9.1 (default, Aug  6 2022, 18:47:07) 
[Clang 13.1.6 (clang-1316.0.21.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import akshare as ak
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/x/.pyenv/versions/3.9.1/lib/python3.9/site-packages/akshare/__init__.py", line 2945, in <module>
    from akshare.index.index_kq_fz import index_kq_fz
  File "/Users/x/.pyenv/versions/3.9.1/lib/python3.9/site-packages/akshare/index/index_kq_fz.py", line 11, in <module>
    from akshare.utils.ak_session import session
  File "/Users/x/.pyenv/versions/3.9.1/lib/python3.9/site-packages/akshare/utils/ak_session.py", line 8, in <module>
    from requests_cache import CachedSession
  File "/Users/x/.pyenv/versions/3.9.1/lib/python3.9/site-packages/requests_cache/__init__.py", line 7, in <module>
    from .backends import *
  File "/Users/x/.pyenv/versions/3.9.1/lib/python3.9/site-packages/requests_cache/backends/__init__.py", line 7, in <module>
    from .base import BaseCache, BaseStorage, DictStorage
  File "/Users/x/.pyenv/versions/3.9.1/lib/python3.9/site-packages/requests_cache/backends/base.py", line 18, in <module>
    from ..serializers import init_serializer
  File "/Users/x/.pyenv/versions/3.9.1/lib/python3.9/site-packages/requests_cache/serializers/__init__.py", line 6, in <module>
    from .preconf import (
  File "/Users/x/.pyenv/versions/3.9.1/lib/python3.9/site-packages/requests_cache/serializers/preconf.py", line 103, in <module>
    bson_serializer = SerializerPipeline(
  File "/Users/x/.pyenv/versions/3.9.1/lib/python3.9/site-packages/requests_cache/serializers/pipeline.py", line 44, in __init__
    self.load_stages = [stage.loads for stage in reversed(stages)]
  File "/Users/x/.pyenv/versions/3.9.1/lib/python3.9/site-packages/requests_cache/serializers/pipeline.py", line 44, in <listcomp>
    self.load_stages = [stage.loads for stage in reversed(stages)]
AttributeError: type object 'Placeholder' has no attribute 'loads'
>>>

**Comment by RogueJin** [comment]
resolved by installing anaconda

**Comment by jindaxiang** [comment]
> resolved by installing anaconda

fine
