### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by leonbaichi** [akfamily/akshare#3056]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本 win10 64
2. Python 版本 3.7.7
3. AKShare 版本 1.7.55
4. 接口的名称和代码  bond_zh_hs_cov_min

代码如下：
import akshare as ak
bond_zh_hs_cov_min_df = ak.bond_zh_hs_cov_min(symbol="sz127004", period='5', adjust='hfq', start_date="2021-09-01 09:32:00", end_date="2022-09-06 09:32:00")
print(bond_zh_hs_cov_min_df.head())

6. 接口报错的截图或代码
    时间       开盘       收盘       最高       最低   涨跌幅    涨跌额    成交量         成交额    振幅    换手率
0  2022-08-26 09:35:00  187.500  187.562  191.697  187.500  0.10  0.182  13664  25912733.0  2.24  10.42
1  2022-08-26 09:40:00  187.728  186.459  188.208  186.279 -0.59 -1.103   5493  10294365.0  1.03   4.19
2  2022-08-26 09:45:00  186.453  185.680  186.453  184.012 -0.42 -0.779   4943   9150169.0  1.31   3.77
3  2022-08-26 09:50:00  185.571  186.212  186.462  185.020  0.29  0.532   4043   7504482.0  0.78   3.08
4  2022-08-26 09:55:00  186.139  187.286  187.305  185.690  0.58  1.074   3827   7140384.0  0.87   2.92
8. 期望获得的正确结果

不管是用5分钟还是30分钟，或者缺省start_date,end_date，都只从8-26开始，不知道怎么回事，麻烦作者大大帮忙看看

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本 win10 64
> 2. Python 版本 3.7.7
> 3. AKShare 版本 1.7.55
> 4. 接口的名称和代码  bond_zh_hs_cov_min
> 
> 代码如下： import akshare as ak bond_zh_hs_cov_min_df = ak.bond_zh_hs_cov_min(symbol="sz127004", period='5', adjust='hfq', start_date="2021-09-01 09:32:00", end_date="2022-09-06 09:32:00") print(bond_zh_hs_cov_min_df.head())
> 
> 6. 接口报错的截图或代码
>    时间       开盘       收盘       最高       最低   涨跌幅    涨跌额    成交量         成交额    振幅    换手率
>    0  2022-08-26 09:35:00  187.500  187.562  191.697  187.500  0.10  0.182  13664  25912733.0  2.24  10.42
>    1  2022-08-26 09:40:00  187.728  186.459  188.208  186.279 -0.59 -1.103   5493  10294365.0  1.03   4.19
>    2  2022-08-26 09:45:00  186.453  185.680  186.453  184.012 -0.42 -0.779   4943   9150169.0  1.31   3.77
>    3  2022-08-26 09:50:00  185.571  186.212  186.462  185.020  0.29  0.532   4043   7504482.0  0.78   3.08
>    4  2022-08-26 09:55:00  186.139  187.286  187.305  185.690  0.58  1.074   3827   7140384.0  0.87   2.92
> 7. 期望获得的正确结果
> 
> 不管是用5分钟还是30分钟，或者缺省start_date,end_date，都只从8-26开始，不知道怎么回事，麻烦作者大大帮忙看看

已在文档增加说明；该接口只能获取近期的数据
