### ISSUE TITLE
stock_hold_control_cninfo 数据太老或者错误

### ISSUE THREAD

**Issue by xswby** [akfamily/akshare#3058]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
遇到任何问题，请先确认您的 AKShare 版本是最新的

pip install akshare --upgrade  # Python 版本需要大于 3.7
描述遇到的问题

1、操作系统版本 macos
2、Python 版本 3.9
3、AKShare 版本 最新版
接口的名称： stock_hold_control_cninfo
代码如下：
kg_df = ak.stock_hold_control_cninfo(symbol="全部")

获取的数据应该比较老，我选了几个数据，例如英 力 特000635的直接控制人名称是错误的

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> **描述遇到的问题** 遇到任何问题，请先确认您的 AKShare 版本是最新的
> 
> pip install akshare --upgrade # Python 版本需要大于 3.7 描述遇到的问题
> 
> 1、操作系统版本 macos 2、Python 版本 3.9 3、AKShare 版本 最新版 接口的名称： stock_hold_control_cninfo 代码如下： kg_df = ak.stock_hold_control_cninfo(symbol="全部")
> 
> 获取的数据应该比较老，我选了几个数据，例如英 力 特000635的直接控制人名称是错误的

数据跟目标网站一直，可以查看最新的更新的数据
