### ISSUE TITLE
AKShare 接口问题报告  ak.stock_a_high_low_statistics

### ISSUE THREAD

**Issue by lightcax** [akfamily/akshare#3064]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本 win10
2. Python 版本 3.7
3. AKShare 版本 1.7.43
4. 接口的名称和代码 ak.stock_a_high_low_statistics(symbol="all")
5. 接口报错的截图或代码
2895                 return self._engine.get_loc(casted_key)
   2896             except KeyError as err:
-> 2897                 raise KeyError(key) from err
   2898
   2899         if tolerance is not None:

KeyError: 'id'
7. 期望获得的正确结果

最近这个接口 异常出错

**Comment by jindaxiang** [comment]
> 4\. stock_a_high_low_statistics

感谢反馈问题，升级到AKShare 1.7.58 版本使用
