### ISSUE TITLE
AKShare 接口问题报告 bond_cb_redeem_jsl 

### ISSUE THREAD

**Issue by zhangyuanwai** [akfamily/akshare#3065]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本 windows11 
2. Python 版本 3.9.7
3. AKShare 版本 1.7.56
4. 接口的名称和代码 bond_cb_redeem_jsl 
5. 接口报错的截图或代码 

![image](https://user-images.githubusercontent.com/31298446/197125825-29cc7591-49a7-4e21-be21-e689d725ce05.png)

6. 期望获得的正确结果
谢谢

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本 windows11
> 2. Python 版本 3.9.7
> 3. AKShare 版本 1.7.56
> 4. 接口的名称和代码 bond_cb_redeem_jsl
> 5. 接口报错的截图或代码
> 
> ![image](https://user-images.githubusercontent.com/31298446/197125825-29cc7591-49a7-4e21-be21-e689d725ce05.png)
> 
> 6. 期望获得的正确结果
>    谢谢

感谢反馈问题；已修复该问题，升级到 AKShare 1.7.58 版本使用
