### ISSUE TITLE
中国指数和期货恐慌指数VIX接口开发

### ISSUE THREAD

**Issue by xnw176** [akfamily/akshare#3070]
地址：https://1.optbbs.com/s/vix.shtml（期权论坛）

截图：
![image](https://user-images.githubusercontent.com/82297022/197372872-991bc4c7-866a-484a-b3ca-6f92876d2a51.png)

图上红框部分数据是免费的，但我还未研究网站数据结构，请看一下是否可以获取。

VIX数据对量化分析的重要因子，这个网站是近期才发现的，上面不少数据相当有用，可以具体深入研究一下。

非常感谢🙏

**Comment by jindaxiang** [comment]
> 地址：[https://1.optbbs.com/s/vix.shtml（期权论坛）](https://1.optbbs.com/s/vix.shtml%EF%BC%88%E6%9C%9F%E6%9D%83%E8%AE%BA%E5%9D%9B%EF%BC%89)
> 
> 截图： ![image](https://user-images.githubusercontent.com/82297022/197372872-991bc4c7-866a-484a-b3ca-6f92876d2a51.png)
> 
> 图上红框部分数据是免费的，但我还未研究网站数据结构，请看一下是否可以获取。
> 
> VIX数据对量化分析的重要因子，这个网站是近期才发现的，上面不少数据相当有用，可以具体深入研究一下。
> 
> 非常感谢🙏

已更新相关日频率数据；升级到 AKShare 1.7.61 版本使用
