### ISSUE TITLE
申万宏源网站改版，域名变更，旧有相关接口全部失效。

### ISSUE THREAD

**Issue by xnw176** [akfamily/akshare#3075]
最新网址
https://www.swhyresearch.com/institute_sw/allIndex/releasedIndex
<img width="1256" alt="image" src="https://user-images.githubusercontent.com/82297022/197709617-c9719a54-528b-43c5-8254-409b57fee4cc.png">
单个指数页面地址
https://www.swhyresearch.com/institute_sw/allIndex/releasedIndex/releasedetail?code=801250&name=申万制造
截图
<img width="1256" alt="image" src="https://user-images.githubusercontent.com/82297022/197710130-640db5b9-68c6-4eef-96c3-072d51766a4d.png">

感觉数据还是可以获取的，就是应该是全新架构，工作量可能比较大。

**Comment by jindaxiang** [comment]
> 最新网址 https://www.swhyresearch.com/institute_sw/allIndex/releasedIndex <img alt="image" width="1256" src="https://user-images.githubusercontent.com/82297022/197709617-c9719a54-528b-43c5-8254-409b57fee4cc.png"> 单个指数页面地址 [https://www.swhyresearch.com/institute_sw/allIndex/releasedIndex/releasedetail?code=801250&name=申万制造](https://www.swhyresearch.com/institute_sw/allIndex/releasedIndex/releasedetail?code=801250&name=%E7%94%B3%E4%B8%87%E5%88%B6%E9%80%A0) 截图 <img alt="image" width="1256" src="https://user-images.githubusercontent.com/82297022/197710130-640db5b9-68c6-4eef-96c3-072d51766a4d.png">
> 
> 感觉数据还是可以获取的，就是应该是全新架构，工作量可能比较大。

感谢反馈问题；已新增 index_realtime_sw, index_hist_sw 接口，升级到 AKShare 1.7.69 使用
