### ISSUE TITLE
【AKShare 接口问题报告】美股基本面stock_us_fundamental接口无法连接

### ISSUE THREAD

**Issue by zhengbcao** [akfamily/akshare#3077]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

基本面接口：https://akshare.akfamily.xyz/data/stock/stock.html#id58

**描述遇到的问题**
1. 操作系统版本：Win
2. Python 版本: 3.7
3. AKShare 版本: 1.7.60
4. 接口的名称和代码: stock_us_fundamental
5. 接口报错的截图或代码: ak.stock_us_fundamental(stock="GOOGL", symbol="info")
![image](https://user-images.githubusercontent.com/115263158/197782296-fa98c38e-bcba-4dc7-ba69-f6e75aed2290.png)

6. 期望获得的正确结果

**Comment by jindaxiang** [comment]
> 4\. stock_us_fundamental

可以正常获取数据；注意数据获取的频率。
<img width="700" alt="image" src="https://user-images.githubusercontent.com/18234520/197825597-01d6ae25-e797-4831-b53d-7554d073c6d3.png">
