### ISSUE TITLE
AttributeError: module 'akshare' has no attribute 'stock_profile_cninfo'

### ISSUE THREAD

**Issue by matthewxuda** [akfamily/akshare#3091]
>>> import akshare as ak
>>> 
>>> stock_profile_cninfo_df = ak.stock_profile_cninfo(symbol="600030")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'akshare' has no attribute 'stock_profile_cninfo'
>>> print(stock_profile_cninfo_df)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'stock_profile_cninfo_df' is not defined

![image](https://user-images.githubusercontent.com/5927005/198828884-33289b37-aef5-4fa8-81ef-b5f9ff591700.png)

**Comment by jindaxiang** [comment]
> stock_profile_cninfo_df

接口可以正常使用，建议升级到最新版使用
