### ISSUE TITLE
胡润百富榜2018数据接口失败问题

### ISSUE THREAD

**Issue by chenhongqi0716** [akfamily/akshare#3097]
胡润百富榜2018年数据无法导入：ak.hurun_rank(indicator="胡润百富榜", year=“2018”) 。其他年份均正常。

![image](https://user-images.githubusercontent.com/14307522/198859290-a6273aa5-06cb-40e5-9778-8fd31e8c8c5e.png)

**Comment by jindaxiang** [comment]
> hurun_rank

感谢反馈问题；已修复该问题；升级到 AKShare 1.7.68
