### ISSUE TITLE
新财富富豪榜接口数据错误

### ISSUE THREAD

**Issue by chenhongqi0716** [akfamily/akshare#3098]
新财富富豪榜数据全部出错： ak.xincaifu_rank(year=“2022”)
返回
![image](https://user-images.githubusercontent.com/14307522/198859579-78dc98bc-11dc-4176-a3e7-e1830d16fbcb.png)

但实际数据是

![image](https://user-images.githubusercontent.com/14307522/198859591-01bbccbc-31cd-48fd-a3ef-ceeec3334242.png)

**Comment by jindaxiang** [comment]
> xincaifu_rank

感谢反馈问题；已修复该问题，升级到 AKShare 1.7.67 版本使用
