### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by xiaopge** [akfamily/akshare#3099]
请教一下ak.stock_zh_a_spot_em()这个接口的历史数据有存档吗，怎么获取？！

**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本
2. Python 版本
3. AKShare 版本
4. 接口的名称和代码
5. 接口报错的截图或代码
6. 期望获得的正确结果

**Comment by jindaxiang** [comment]
> 请教一下ak.stock_zh_a_spot_em()这个接口的历史数据有存档吗，怎么获取？！
> 
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本
> 2. Python 版本
> 3. AKShare 版本
> 4. 接口的名称和代码
> 5. 接口报错的截图或代码
> 6. 期望获得的正确结果

可以在本地自行存储数据
