### ISSUE TITLE
index_hist_sw

### ISSUE THREAD

**Issue by callcter** [akfamily/akshare#3108]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本 macOS 10.15
2. Python 版本 3.7.5
3. AKShare 版本 1.7.70
4. 接口的名称和代码
index_hist_sw
```python
index_hist_sw_df = ak.index_hist_sw(symbol="801193", period="day")
index_hist_sw_df
```
5. 接口报错的截图或代码
801193 少了 2022-08-04 往后至 2022-10-31 中间的数据
8. 期望获得的正确结果
完整数据

**Comment by jindaxiang** [comment]
> ```python
> 801193
> ```

接口可以正常使用；跟数据源一致
