### ISSUE TITLE
貌似没有查询场内基金的后复权价格的接口

### ISSUE THREAD

**Issue by seawayfisher** [akfamily/akshare#3115]
大神您好~
       打扰了，请问一下，貌似没有找到查询A股的场内基金的后复权价格的接口，
stock_zh_index_daily
stock_zh_index_daily_tx
stock_zh_index_daily_em
这三个接口我在测试的时候发现都不是后复权价格。不知道大神什么时候有空加上呢？如果没空的话，能否指点一下，这个接口我该如何改造呢？

**Comment by jindaxiang** [comment]
> 大神您好~ 打扰了，请问一下，貌似没有找到查询A股的场内基金的后复权价格的接口， stock_zh_index_daily stock_zh_index_daily_tx stock_zh_index_daily_em 这三个接口我在测试的时候发现都不是后复权价格。不知道大神什么时候有空加上呢？如果没空的话，能否指点一下，这个接口我该如何改造呢？

没有相应的数据源
