### ISSUE TITLE
index_value_hist_funddb接口问题报告

### ISSUE THREAD

**Issue by inspirits** [akfamily/akshare#3123]
接口：index_value_hist_funddb
所在文件：zh_stock_index_csindex.py
前几天都使用正常，昨天开始提示错误，添加打印信息后，提示{'code': -1, 'message': '服务器异常'}，但对应的url能够正常访问。

**Comment by zavatar** [comment]
我也发现了，好像是API从post改成get了，换成‘requests.get(url)’就可以运行了。

**Comment by inspirits** [comment]
我试了改成get后，index_value_name_funddb()这个接口能正常使用，但是index_value_hist_funddb(symbol,indicator)这个接口还是有问题，取回来的数据无视参数，全是一样的。

**Comment by jindaxiang** [comment]
> 接口：index_value_hist_funddb 所在文件：zh_stock_index_csindex.py 前几天都使用正常，昨天开始提示错误，添加打印信息后，提示{'code': -1, 'message': '服务器异常'}，但对应的url能够正常访问。

感谢反馈问题；已修复该问题，升级到 AKShare 1.7.77 版本使用

**Comment by jindaxiang** [comment]
> 我也发现了，好像是API从post改成get了，换成‘requests.get(url)’就可以运行了。

感谢反馈问题；已修复该问题，升级到 AKShare 1.7.77 版本使用
