### ISSUE TITLE
macro_euro_gdp_yoy接口缺少近期数据

### ISSUE THREAD

**Issue by chengqinglian** [akfamily/akshare#3125]
akshare-1.7.75
ak.macro_euro_gdp_yoy()接口返回数据只到2021.3
目标数据源https://datacenter.jin10.com/reportType/dc_eurozone_gdp_yoy 上缺包含了2022数据

**Comment by jindaxiang** [comment]
> macro_euro_gdp_yoy

感谢反馈问题；已修复该问题，升级到 AKShare 1.7.76 版本使用

**Comment by chengqinglian** [comment]
感谢！
