### ISSUE TITLE
申万新网站指数分析页面数据接口开发

### ISSUE THREAD

**Issue by xnw176** [akfamily/akshare#3129]
网页地址：https://www.swhyresearch.com/institute_sw/allIndex/analysisIndex
截图：
<img width="1211" alt="image" src="https://user-images.githubusercontent.com/82297022/199913045-3dab2399-4443-4768-9d4b-d7b7d4395060.png">
和旧网站一样，有市净率，市盈率等估值数据。表征，一级和风格指数是可以免费获取的。

感谢开发。

**Comment by jindaxiang** [comment]
> 网页地址：https://www.swhyresearch.com/institute_sw/allIndex/analysisIndex 截图： <img alt="image" width="1211" src="https://user-images.githubusercontent.com/82297022/199913045-3dab2399-4443-4768-9d4b-d7b7d4395060.png"> 和旧网站一样，有市净率，市盈率等估值数据。表征，一级和风格指数是可以免费获取的。
> 
> 感谢开发。

感谢反馈问题；已新增 index_analysis_sw 接口，升级到 AKShare 1.7.78 版本使用
