### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by 1999yzm** [akfamily/akshare#3135]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本 -- APPLE M1 macos12.6
2. Python 版本 -- 3.9
3. AKShare 版本 -- 1.7.48
4. 接口的名称和代码 -- index_investing_global
5. 接口报错的截图或代码 -- index_investing_global_df = ak.index_investing_global(area="中国", symbol="富时中国A50指数", period="每日", start_date="20100101", end_date="20220808")。 报错:'NoneType' object has no attribute 'find_all'
print(index_investing_global_df)
6. 期望获得的正确结果 -- 代码直接报错,无返回结果

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本 -- APPLE M1 macos12.6
> 2. Python 版本 -- 3.9
> 3. AKShare 版本 -- 1.7.48
> 4. 接口的名称和代码 -- index_investing_global
> 5. 接口报错的截图或代码 -- index_investing_global_df = ak.index_investing_global(area="中国", symbol="富时中国A50指数", period="每日", start_date="20100101", end_date="20220808")。 报错:'NoneType' object has no attribute 'find_all'
>    print(index_investing_global_df)
> 6. 期望获得的正确结果 -- 代码直接报错,无返回结果

该接口暂时不能使用
