### ISSUE TITLE
[bug] akshare中ak.sw_index_third_cons调用问题

### ISSUE THREAD

**Issue by pipinstall-patrick** [akfamily/akshare#3138]
**ak.sw_index_third_cons**
在最新版本的akshare中调用sw_index_thied_cons出现报错

**硬件版本**
操作系统版本: Ubuntu 18.04
Python 版本 :3.8.11
AKShare 版本 :1.7.79
接口的名称和代码: ak.sw_index_third_cons
接口报错的截图或代码: ![image](https://user-images.githubusercontent.com/67516497/200229000-7f96c342-4e53-4c04-a2fa-1c54167da79e.png)
期望获得的正确结果: 顺利运行

**Screenshots**
![image](https://user-images.githubusercontent.com/67516497/200229000-7f96c342-4e53-4c04-a2fa-1c54167da79e.png)

**Comment by jindaxiang** [comment]
> sw_index_third_cons

目标网站调整，该接口暂时不能使用
