### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by Anlandme** [akfamily/akshare#3141]
这个接口：macro_china_gksccz，貌似是原接口返回了404

在我的机器上报这个错：
.......
File "D:\work\code\dddd\src\economic\service\macro_china.py", line 14, in gksccz
    macro_china_gksccz_df = ak.macro_china_gksccz()
  File "D:\work\code\tt\venv\lib\site-packages\akshare\economic\macro_china.py", line 3124, in macro_china_gksccz
    data_json = r.json()
  File "D:\work\code\tt\venv\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by jindaxiang** [comment]
> 这个接口：macro_china_gksccz，貌似是原接口返回了404
> 
> 在我的机器上报这个错： ....... File "D:\work\code\dddd\src\economic\service\macro_china.py", line 14, in gksccz macro_china_gksccz_df = ak.macro_china_gksccz() File "D:\work\code\tt\venv\lib\site-packages\akshare\economic\macro_china.py", line 3124, in macro_china_gksccz data_json = r.json() File "D:\work\code\tt\venv\lib\site-packages\requests\models.py", line 975, in json raise RequestsJSONDecodeError(e.msg, e.doc, e.pos) requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

接口将在后续移除

**Comment by Anlandme** [comment]
okk
