### ISSUE TITLE
申万指数分析周线和月线数据错误

### ISSUE THREAD

**Issue by hkhj326** [akfamily/akshare#3145]
https://www.swhyresearch.com/institute_sw/allIndex/analysisIndex

`index_analysis_sw` 接口里，源数据的 `周报表` 和  `月报表` 只能通过 `bargaindate` 取一个日期的截面数据，指定`start_date`和`end_date`  返回的都是日级别数据。

**Comment by jindaxiang** [comment]
> https://www.swhyresearch.com/institute_sw/allIndex/analysisIndex
> 
> `index_analysis_sw` 接口里，源数据的 `周报表` 和 `月报表` 只能通过 `bargaindate` 取一个日期的截面数据，指定`start_date`和`end_date` 返回的都是日级别数据。

感谢反馈问题；新增     index_analysis_daily_sw, index_analysis_weekly_sw, index_analysis_monthly_sw, index_analysis_week_month_sw 接口，升级到 AKShare 1.7.82 使用
