### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by xueminglv** [akfamily/akshare#3158]
1. import akshare as ak

stock_a_pe_and_pb_df = ak.stock_a_pe_and_pb(symbol="000300.SH")
print(stock_a_pe_and_pb_df)

只能返回 2017-11-13 之后的数据

2.            date  addTtmPe  middleAddTtmPe  ...  averagePb  middleAveragePb    close
0     2017-11-13     14.12           29.04  ...       3.54             2.59  4128.07
1     2017-11-14     14.04           28.89  ...       3.50             2.58  4099.35
2     2017-11-15     13.94           28.62  ...       3.46             2.56  4073.67
3     2017-11-16     13.97           28.56  ...       3.47             2.54  4105.01
4     2017-11-17     14.09           28.36  ...       3.42             2.49  4120.85
...          ...       ...             ...  ...        ...              ...      ...
1210  2022-11-07      9.62           20.03  ...       3.41             2.28  3775.30
1211  2022-11-08      9.57           19.85  ...       3.38             2.28  3749.33
1212  2022-11-09      9.50           19.76  ...       3.35             2.25  3714.27
1213  2022-11-10      9.46           19.91  ...       3.33             2.23  3685.69
1214  2022-11-11      9.72           20.51  ...       3.40             2.27  3788.44

[1215 rows x 11 columns]

3. 我的 python & akshare 版本
C:\Windows\System32>pip list | findstr akshare
akshare                       1.7.85

C:\Windows\System32>python --version
Python 3.9.13

C:\Windows\System32>ver

Microsoft Windows [版本 10.0.22621.819]

**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本
2. Python 版本
3. AKShare 版本
5. 接口的名称和代码
6. 接口报错的截图或代码
7. 期望获得的正确结果

**Comment by jindaxiang** [comment]
> stock_a_pe_and_pb

是的

**Comment by xueminglv** [comment]
C:\Windows\System32>python --version
Python 3.9.15

C:\Windows\System32>pip install akshare -U
Requirement already satisfied: akshare in c:\anaconda3\lib\site-packages (1.8.25)

C:\Anaconda3\python.exe C:\Anaconda3\Lib\site-packages\akshare\stock_feature\stock_a_pe_and_pb.py 
            date  addTtmPe  middleAddTtmPe  ...  averagePb  middleAveragePb    close
0     2017-12-06     14.66           36.46  ...       4.35             2.84  3293.96
1     2017-12-07     14.55           36.27  ...       3.94             2.83  3272.05
2     2017-12-08     14.62           36.78  ...       3.98             2.87  3289.99
3     2017-12-11     14.76           37.26  ...       4.02             2.89  3322.20
4     2017-12-12     14.57           36.62  ...       3.97             2.86  3280.81
...          ...       ...             ...  ...        ...              ...      ...
1209  2022-11-29     10.87           31.93  ...       3.45             2.40  3149.75
1210  2022-11-30     10.88           31.80  ...       3.43             2.40  3151.34
1211  2022-12-01     10.93           32.17  ...       3.42             2.40  3165.47
1212  2022-12-02     10.90           32.32  ...       3.44             2.43  3156.14
1213  2022-12-05     11.11           32.56  ...       3.45             2.45  3211.81

[1214 rows x 11 columns]
            date  addTtmPe  middleAddTtmPe  ...  averagePb  middleAveragePb    close
0     2017-12-06     13.83           27.20  ...       3.31             2.41  4015.82
1     2017-12-07     13.69           27.00  ...       3.29             2.41  3971.06
2     2017-12-08     13.74           26.97  ...       3.33             2.43  4003.38
3     2017-12-11     14.01           27.03  ...       3.63             2.55  4069.50
4     2017-12-12     13.83           26.52  ...       3.60             2.53  4016.02
...          ...       ...             ...  ...        ...              ...      ...
1209  2022-11-29     10.54           20.73  ...       3.95             2.64  3848.42
1210  2022-11-30     10.57           20.65  ...       3.95             2.61  3853.04
1211  2022-12-01     10.64           20.71  ...       4.02             2.64  3894.77
1212  2022-12-02     10.57           20.80  ...       4.00             2.63  3870.95
1213  2022-12-05     10.81           21.27  ...       4.04             2.69  3946.88

[1214 rows x 11 columns]

进程已结束,退出代码0

数句还是不全，不知道为什么

**Comment by OatLatte** [comment]
请问这个有解决办法吗? 目前我用这个只能返回 2018 年以后的了.

**Comment by OatLatte** [comment]
> 请问这个有解决办法吗? 目前我用这个只能返回 2018 年以后的了.

**Comment by OatLatte** [comment]
请问这个有解决办法吗? 目前我用这个只能返回 2018 年以后的了.
