### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by jqAtNJ** [akfamily/akshare#3165]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本  Windows 11 22H2
2. Python 版本 Python 3.11.0
3. AKShare 版本 1.7.90
4. 接口的名称和代码 fund_portfolio_hold_em ak.fund_portfolio_hold_em(symbol=code, date="2022")
5. 接口报错的截图或代码 
![image](https://user-images.githubusercontent.com/118098796/201510960-8d6d59c2-56dd-44b3-b983-9daa76756dff.png)
看起来页面解析的结果key是“占净值 比例”，“持股数 （万股）”， “ 持仓市值 （万元）”，--key中包含空格。
而代码是按照“占净值比例”，“持股数（万股）”， “ 持仓市值（万元）”处理的。
6. 期望获得的正确结果

**Comment by poorren** [comment]
I got same problem on this

**Comment by jindaxiang** [comment]
> 4\. 2022

接口目前使用正常；请提供详细的调用代码

**Comment by jindaxiang** [comment]
> 4\. fund_portfolio_hold_em

请提供下调用的代码

**Comment by jqAtNJ** [comment]
import akshare as ak
def show_bug():
    hold_df = ak.fund_portfolio_hold_em(symbol="513100", date="2022")
    print(hold_df)

if __name__ == '__main__':
    show_bug()

**Comment by jindaxiang** [comment]
> import akshare as ak def show_bug(): hold_df = ak.fund_portfolio_hold_em(symbol="513100", date="2022") print(hold_df)
> 
> if **name** == '**main**': show_bug()

接口可以正常使用，建议升级到 最新版
<img width="826" alt="image" src="https://user-images.githubusercontent.com/18234520/201590740-3db0168e-1de3-4274-8651-3ddf2387e266.png">

**Comment by jqAtNJ** [comment]
我这依旧不能正常处理，html里的内容是“持仓市值<br />（万元人民币）”,

@poorren 

如果和我类似，可以在“fund_portfolio_em.py“内key中 自己手动加入空格，
temp_df.rename(
            columns={"持股数 （万股）": "持股数", "持仓市值 （万元）": "持仓市值"}, inplace=True
        )
        temp_df.rename(
            columns={"持股数 （万股）": "持股数", "持仓市值 （万元人民币）": "持仓市值"}, inplace=True
        )

**Comment by jindaxiang** [comment]
> 我这依旧不能正常处理，html里的内容是“持仓市值（万元人民币）”,
> 
> @poorren
> 
> 如果和我类似，可以在“fund_portfolio_em.py“内key中 自己手动加入空格， temp_df.rename( columns={"持股数 （万股）": "持股数", "持仓市值 （万元）": "持仓市值"}, inplace=True ) temp_df.rename( columns={"持股数 （万股）": "持股数", "持仓市值 （万元人民币）": "持仓市值"}, inplace=True )

感谢反馈问题；已修复该问题，升级到 AKShare 1.7.92 版本使用
