### ISSUE TITLE
 加密货币历史数据接口失效

### ISSUE THREAD

**Issue by zechzhao** [akfamily/akshare#3166]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本： win
2. Python 版本
3.8
3. AKShare 版本
akshare==1.7.91
4. 接口的名称和代码
 ak.crypto_hist(symbol="BTC", period="每日", start_date="20151020", end_date="20201023")
5. 接口报错的截图或代码
    crypto_hist_df = ak.crypto_hist(symbol="BTC", period="每日", start_date="20151020", end_date="20201023")
  File "C:\Users\HP\miniconda3\lib\site-packages\akshare\crypto\crypto_hist_investing.py", line 177, in crypto_hist
    temp_df = pd.read_html(r.text)[0]
  File "C:\Users\HP\miniconda3\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\HP\miniconda3\lib\site-packages\pandas\io\html.py", line 1098, in read_html
    return _parse(
  File "C:\Users\HP\miniconda3\lib\site-packages\pandas\io\html.py", line 926, in _parse
    raise retained
  File "C:\Users\HP\miniconda3\lib\site-packages\pandas\io\html.py", line 906, in _parse
    tables = p.parse_tables()
  File "C:\Users\HP\miniconda3\lib\site-packages\pandas\io\html.py", line 222, in parse_tables
    tables = self._parse_tables(self._build_doc(), self.match, self.attrs)
  File "C:\Users\HP\miniconda3\lib\site-packages\pandas\io\html.py", line 552, in _parse_tables
    raise ValueError("No tables found")
ValueError: No tables found
6. 期望获得的正确结果
同文档。

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本： win
> 2. Python 版本
>    3.8
> 3. AKShare 版本
>    akshare==1.7.91
> 4. 接口的名称和代码
>    ak.crypto_hist(symbol="BTC", period="每日", start_date="20151020", end_date="20201023")
> 5. 接口报错的截图或代码
>    crypto_hist_df = ak.crypto_hist(symbol="BTC", period="每日", start_date="20151020", end_date="20201023")
>    File "C:\Users\HP\miniconda3\lib\site-packages\akshare\crypto\crypto_hist_investing.py", line 177, in crypto_hist
>    temp_df = pd.read_html(r.text)[0]
>    File "C:\Users\HP\miniconda3\lib\site-packages\pandas\util_decorators.py", line 311, in wrapper
>    return func(*args, **kwargs)
>    File "C:\Users\HP\miniconda3\lib\site-packages\pandas\io\html.py", line 1098, in read_html
>    return _parse(
>    File "C:\Users\HP\miniconda3\lib\site-packages\pandas\io\html.py", line 926, in _parse
>    raise retained
>    File "C:\Users\HP\miniconda3\lib\site-packages\pandas\io\html.py", line 906, in _parse
>    tables = p.parse_tables()
>    File "C:\Users\HP\miniconda3\lib\site-packages\pandas\io\html.py", line 222, in parse_tables
>    tables = self._parse_tables(self._build_doc(), self.match, self.attrs)
>    File "C:\Users\HP\miniconda3\lib\site-packages\pandas\io\html.py", line 552, in _parse_tables
>    raise ValueError("No tables found")
>    ValueError: No tables found
> 6. 期望获得的正确结果
>    同文档。

英为财情的接口暂时不能使用
