### ISSUE TITLE
ak.stock_sse_deal_daily 问题报告

### ISSUE THREAD

**Issue by shij10** [akfamily/akshare#3173]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本    Ubuntu 20.4
3. Python 版本     Python 3.8.10
4. AKShare 版本     1.7.91
5. 接口的名称和代码     ak.stock_sse_deal_daily
6. 接口报错的截图或代码

![image](https://user-images.githubusercontent.com/16433697/201678873-0cae267e-c9fd-4092-9aa3-832e9bc49659.png)

8. 期望获得的正确结果

能得到正确结果

**Comment by shij10** [comment]
问题出现在 Linux， windows 是正常

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本    Ubuntu 20.4
> 2. Python 版本     Python 3.8.10
> 3. AKShare 版本     1.7.91
> 4. 接口的名称和代码     ak.stock_sse_deal_daily
> 5. 接口报错的截图或代码
> 
> ![image](https://user-images.githubusercontent.com/16433697/201678873-0cae267e-c9fd-4092-9aa3-832e9bc49659.png)
> 
> 8. 期望获得的正确结果
> 
> 能得到正确结果

目前在 ubuntu 18.04 测试是正常的；建议建立虚拟环境，安装最新的依赖库
