### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by nankaimy** [akfamily/akshare#3179]
import akshare as ak

sw_index_third_cons_df = ak.sw_index_third_cons(symbol="851921.SI")

ValueError: Length mismatch: Expected axis has 17 elements, new values have 13 elements

ak.__version__
Out[4]: '1.7.92'

**Comment by jindaxiang** [comment]
> import akshare as ak
> 
> sw_index_third_cons_df = ak.sw_index_third_cons(symbol="851921.SI")
> 
> ValueError: Length mismatch: Expected axis has 17 elements, new values have 13 elements
> 
> ak.**version** Out[4]: '1.7.92'

感谢反馈问题；已修复该问题，升级到 AKShare 1.7.93 使用
