### ISSUE TITLE
AKShare 接口问题报告 spot_golden_benchmark_sge

### ISSUE THREAD

**Issue by h2y** [akfamily/akshare#3182]
**描述遇到的问题**
1. 操作系统版本
ubuntu server
3. Python 版本
3
5. AKShare 版本
最新版
7. 接口的名称和代码
spot_golden_benchmark_sge
8. 接口报错的截图或代码
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/code/main.py", line 20, in <module>
    data = DataFetcher(target, config['rule']).Get()
  File "/code/get_data.py", line 19, in Get
    data = self.spot_golden_benchmark_sge()
  File "/code/get_data.py", line 74, in spot_golden_benchmark_sge
    data = ak.spot_golden_benchmark_sge()
  File "/usr/local/lib/python3.10/site-packages/akshare/spot/spot_sge.py", line 74, in spot_golden_benchmark_sge
    data_json = r.json()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value]
```
9. 期望获得的正确结果
-

**Comment by jindaxiang** [comment]
> **描述遇到的问题**
> 
> 1. 操作系统版本
>    ubuntu server
> 2. Python 版本
>    3
> 3. AKShare 版本
>    最新版
> 4. 接口的名称和代码
>    spot_golden_benchmark_sge
> 5. 接口报错的截图或代码
> 
> ```
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 910, in json
>     return complexjson.loads(self.text, **kwargs)
>   File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
>     return _default_decoder.decode(s)
>   File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/code/main.py", line 20, in <module>
>     data = DataFetcher(target, config['rule']).Get()
>   File "/code/get_data.py", line 19, in Get
>     data = self.spot_golden_benchmark_sge()
>   File "/code/get_data.py", line 74, in spot_golden_benchmark_sge
>     data = ak.spot_golden_benchmark_sge()
>   File "/usr/local/lib/python3.10/site-packages/akshare/spot/spot_sge.py", line 74, in spot_golden_benchmark_sge
>     data_json = r.json()
>   File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 917, in json
>     raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
> requests.exceptions.JSONDecodeError: [Errno Expecting value]
> ```
> 
> 9. 期望获得的正确结果

感谢反馈问题；已修复该问题；升级到 AKShare 1.7.95 版本使用
