### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by jqAtNJ** [akfamily/akshare#3183]
描述遇到的问题
KeyError: '占净值比例'

操作系统版本 Windows 11 22H2
Python 版本 Python 3.8.13
AKShare 版本 1.7.93
接口的名称和代码 fund_portfolio_hold_em（symbol="159909", date="2022"）
接口报错的截图或代码
![image](https://user-images.githubusercontent.com/118098796/202169872-17a47386-518c-4ea7-885f-86ada7312291.png)

看起来key“占净值 比例 ”解析中间也有空格。

**Comment by jindaxiang** [comment]
> 描述遇到的问题 KeyError: '占净值比例'
> 
> 操作系统版本 Windows 11 22H2 Python 版本 Python 3.8.13 AKShare 版本 1.7.93 接口的名称和代码 fund_portfolio_hold_em（symbol="159909", date="2022"） 接口报错的截图或代码 ![image](https://user-images.githubusercontent.com/118098796/202169872-17a47386-518c-4ea7-885f-86ada7312291.png)
> 
> 看起来key“占净值 比例 ”解析中间也有空格。

感谢反馈问题；已修复该问题，升级到 AKShare 1.7.94 版本使用

**Comment by superzw** [comment]
ak version : 1.7.99，还是有这个问题
