### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by nikewater** [akfamily/akshare#3193]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本 
Windows 10 企业版22H2, 9045.2251
3. Python 版本
3.10.6
5. AKShare 版本
1.7.94
7. 接口的名称和代码
df_raise= ak.stock_sina_lhb_detail_daily(trade_date="20221117", symbol="跌幅偏离值达7%的证券")
9. 接口报错的截图或代码
![image](https://user-images.githubusercontent.com/12806079/202661846-39d3eaf0-a19a-42cd-88c9-a0e53b14494e.png)

11. 期望获得的正确结果
![image](https://user-images.githubusercontent.com/12806079/202662128-dd5d4363-fe09-4267-bb01-b37544e6ef70.png)
增加flavor='bs4‘问题解决，html5lib未测试。默认为lxml
**另外，建议：**
position_num = table_name_list.index(symbol)
if len(table_name_list) == position_num + 1:
  temp_df_1 = pd.read_html(r.text, flavor='bs4', header=1)[position_num].iloc[0:, :]
  temp_df_2 = pd.read_html(r.text, flavor='bs4',header=1)[position_num + 1].iloc[0:, :]
  temp_df_3 = pd.read_html(r.text, flavor='bs4',header=1)[position_num + 2].iloc[0:, :]
  temp_df = temp_df_1.append(temp_df_2).append(temp_df_3)
else:
  temp_df = pd.read_html(r.text, flavor='bs4',header=1)[position_num].iloc[0:, :]
**修改为：**append 从1.4.0 depricated
position_num = table_name_list.index(symbol)
list_df = pd.read_html(r.text, flavor='bs4', header=1)
if len(table_name_list) == position_num + 1:
    temp_df = pd.concat(list_df[position_num:])
else:
    temp_df = list_df[position_num]

**Comment by jindaxiang** [comment]
> 6\. flavor='bs4'

感谢反馈问题及解决方案；已修复该问题；升级到 AKShare 1.7.99 使用，部分接口已修改名称，参考：https://www.akshare.xyz/changelog.html
