### ISSUE TITLE
fund_portfolio_hold_em接口 KeyError

### ISSUE THREAD

**Issue by gkdgkdgkdgkd** [akfamily/akshare#3202]
1. 操作系统版本
Manjaro

2. Python 版本
Python 3.10.8

3. AKShare 版本
1.7.99

4. 接口的名称和代码
fund_portfolio_hold_em

5. 接口报错的截图或代码
![2022-11-20_15-15](https://user-images.githubusercontent.com/50223031/202890507-88e080e6-5c7e-42aa-aa76-9cd0202a2a91.png)

![image](https://user-images.githubusercontent.com/50223031/202890517-6fb1e12c-68c1-415b-b0a0-32c5539a1e4a.png)

6. 期望获得的正确结果
这不官方文档的api吗，咋报错KeyError了。。。

**Comment by jindaxiang** [comment]
> 4\. fund_portfolio_hold_em

感谢反馈问题；已修复该问题，升级到 AKShare 1.8.2 版本使用
