### ISSUE TITLE
akshare.macro_china_hgjck() 东财进口数据，报错JSONDecodeError

### ISSUE THREAD

**Issue by park** [akfamily/akshare#3205]
Python 3.8/3.9环境，akshare 1.7.99，运行以下
```
import akshare as ak
ak.macro_china_hgjck()
```
……报错 JSONDecodeError
```
---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
Input In [1], in <cell line: 2>()
      1 import akshare as ak
----> 2 ak.macro_china_hgjck()

File ~/anaconda3/lib/python3.9/site-packages/akshare/economic/macro_china.py:2893, in macro_china_hgjck()
   2891 r = requests.get(url, params=params)
   2892 data_text = r.text
-> 2893 data_json = demjson.decode(data_text[data_text.find("{") : -1])
   2894 temp_df = pd.DataFrame([item.split(",") for item in data_json["data"]])
   2895 temp_df.columns = [
   2896     "月份",
   2897     "当月出口额-金额",
   (...)
   2906     "累计进口额-同比增长",
   2907 ]

File ~/anaconda3/lib/python3.9/site-packages/akshare/utils/demjson.py:5740, in decode(txt, encoding, **kwargs)
   5737 j = JSON(**kwargs)
   5739 # Now do the actual JSON decoding
-> 5740 result = j.decode(txt,
   5741                   encoding=encoding,
   5742                   return_errors=(return_errors or write_errors),
   5743                   return_stats=(return_stats or write_stats))
   5745 if write_errors:
   5746     import sys

File ~/anaconda3/lib/python3.9/site-packages/akshare/utils/demjson.py:4957, in JSON.decode(self, txt, encoding, return_errors, return_stats)
   4955 errors = [err for err in state.errors if err.severity in ('fatal', 'error')]
   4956 if errors:
-> 4957     raise errors[0]
   4958 if return_stats:
   4959     return result_type(state.obj, None, state.stats)

JSONDecodeError: Missing value for object property, expected ":"
```

**Comment by jindaxiang** [comment]
> Python 3.8/3.9环境，akshare 1.7.99，运行以下
> 
> ```
> import akshare as ak
> ak.macro_china_hgjck()
> ```
> 
> ……报错 JSONDecodeError
> 
> ```
> ---------------------------------------------------------------------------
> JSONDecodeError                           Traceback (most recent call last)
> Input In [1], in <cell line: 2>()
>       1 import akshare as ak
> ----> 2 ak.macro_china_hgjck()
> 
> File ~/anaconda3/lib/python3.9/site-packages/akshare/economic/macro_china.py:2893, in macro_china_hgjck()
>    2891 r = requests.get(url, params=params)
>    2892 data_text = r.text
> -> 2893 data_json = demjson.decode(data_text[data_text.find("{") : -1])
>    2894 temp_df = pd.DataFrame([item.split(",") for item in data_json["data"]])
>    2895 temp_df.columns = [
>    2896     "月份",
>    2897     "当月出口额-金额",
>    (...)
>    2906     "累计进口额-同比增长",
>    2907 ]
> 
> File ~/anaconda3/lib/python3.9/site-packages/akshare/utils/demjson.py:5740, in decode(txt, encoding, **kwargs)
>    5737 j = JSON(**kwargs)
>    5739 # Now do the actual JSON decoding
> -> 5740 result = j.decode(txt,
>    5741                   encoding=encoding,
>    5742                   return_errors=(return_errors or write_errors),
>    5743                   return_stats=(return_stats or write_stats))
>    5745 if write_errors:
>    5746     import sys
> 
> File ~/anaconda3/lib/python3.9/site-packages/akshare/utils/demjson.py:4957, in JSON.decode(self, txt, encoding, return_errors, return_stats)
>    4955 errors = [err for err in state.errors if err.severity in ('fatal', 'error')]
>    4956 if errors:
> -> 4957     raise errors[0]
>    4958 if return_stats:
>    4959     return result_type(state.obj, None, state.stats)
> 
> JSONDecodeError: Missing value for object property, expected ":"
> ```

感谢反馈问题；已修复该问题，升级到 AKShare 1.8.4 使用
