### ISSUE TITLE
stock_a_lg_indicator 接口报错

### ISSUE THREAD

**Issue by wabbaf** [akfamily/akshare#3206]
akshare 版本已更新到最新，接口依然报错

以下为vscode运行报错代码：HTTPSConnectionPool(host='www.legulegu.com', port=443): Max retries exceeded with url: /api/s/base-info/300869?token=f81d352f849694626bdeafa85744295b (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)')))
```

**描述遇到的问题**
1. 操作系统版本 macOS 13.0.1 
2. Python 版本 3.10.5
3. AKShare 版本 1.7.99
4. 接口的名称和代码 stock_a_lg_indicator
5. 接口报错的截图或代码
![Xnip2022-11-21_14-08-33](https://user-images.githubusercontent.com/30892328/202979353-44f9694f-2c36-4f85-9500-f0d443da21f5.png)

7. 期望获得的正确结果

**Comment by hy2014** [comment]
r = requests.get(url, params=params, verify=False) verify=False可解决问题

**Comment by wabbaf** [comment]
> r = requests.get (url, params=params, verify=False) verify=False 可解决问题

你好，请问一下 verify=False 这个参数应该怎么与接口结合呢？似乎是无法直接在akshare的接口传入设置信息的（如下代码会报错：stock_a_lg_indicator_df = ak.stock_a_lg_indicator(symbol="000001",verify=False)

**Comment by jindaxiang** [comment]
> akshare 版本已更新到最新，接口依然报错
> 
> 以下为vscode运行报错代码：HTTPSConnectionPool(host='www.legulegu.com', port=443): Max retries exceeded with url: /api/s/base-info/300869?token=f81d352f849694626bdeafa85744295b (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)')))
> 
> ```
> 
> **描述遇到的问题**
> 1. 操作系统版本 macOS 13.0.1 
> 2. Python 版本 3.10.5
> 3. AKShare 版本 1.7.99
> 4. 接口的名称和代码 stock_a_lg_indicator
> 5. 接口报错的截图或代码
> ![Xnip2022-11-21_14-08-33](https://user-images.githubusercontent.com/30892328/202979353-44f9694f-2c36-4f85-9500-f0d443da21f5.png)
> 
> 7. 期望获得的正确结果
> ```

感谢反馈问题；已修复该问题，升级到 AKShare 1.8.4 版本使用
