### ISSUE TITLE
`stock_market_activity_legu`接口SSL报错

### ISSUE THREAD

**Issue by JiangJamm** [akfamily/akshare#3214]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本 MacOS 13.0.1
2. Python 版本 3.8.7
3. AKShare 版本 1.8.5
4. 接口的名称和代码 `stock_market_activity_legu`
5. 接口报错的截图或代码
```
requests.exceptions.SSLError: HTTPSConnectionPool(host='www.legulegu.com', port=443): Max retries exceeded with url: /stockdata/market-activity (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1125)')))
```

![image](https://user-images.githubusercontent.com/39955422/203131960-6bd6249b-d6c4-40bd-992d-43acaab930f2.png)

6. 期望获得的正确结果

**Comment by jindaxiang** [comment]
> 4\. stock_market_activity_legu

感谢反馈问题；已修复该问题，升级到 AKShare 1.8.7 版本使用
