### ISSUE TITLE
ak.macro_china_gdp() 接口参数报错

### ISSUE THREAD

**Issue by happyhzq** [akfamily/akshare#3215]
akshare v= 1.8.5
python =3.8
system=ubuntu
error=JSONDecodeError: Missing value for object property, expected ":"
---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
Cell In [1], line 3
      1 import akshare as ak
----> 3 macro_china_gdp_df = ak.macro_china_gdp()
      4 print(macro_china_gdp_df)

File /usr/local/lib/python3.8/site-packages/akshare/economic/macro_china.py:2723, in macro_china_gdp()
   2721 r = requests.get(url, params=params)
   2722 data_text = r.text
-> 2723 data_json = demjson.decode(data_text[data_text.find("{") : -1])
   2724 temp_df = pd.DataFrame([item.split(",") for item in data_json["data"]])
   2725 temp_df.columns = [
   2726     "季度",
   2727     "国内生产总值-绝对值",
   (...)
   2734     "第三产业-同比增长",
   2735 ]

File /usr/local/lib/python3.8/site-packages/akshare/utils/demjson.py:5740, in decode(txt, encoding, **kwargs)
   5737 j = JSON(**kwargs)
   5739 # Now do the actual JSON decoding
-> 5740 result = j.decode(txt,
   5741                   encoding=encoding,
   5742                   return_errors=(return_errors or write_errors),
   5743                   return_stats=(return_stats or write_stats))
   5745 if write_errors:
   5746     import sys

File /usr/local/lib/python3.8/site-packages/akshare/utils/demjson.py:4957, in JSON.decode(self, txt, encoding, return_errors, return_stats)
   4955 errors = [err for err in state.errors if err.severity in ('fatal', 'error')]
   4956 if errors:
-> 4957     raise errors[0]
   4958 if return_stats:
   4959     return result_type(state.obj, None, state.stats)

JSONDecodeError: Missing value for object property, expected ":"

**Comment by jindaxiang** [comment]
> macro_china_gdp

感谢反馈问题；已修复该问题，升级到 AKShare 1.8.8 版本使用
