### ISSUE TITLE
ak.stock_a_ttm_lyr() 接口问题报告

### ISSUE THREAD

**Issue by wabbaf** [akfamily/akshare#3216]
在vscode上运行的报错信息为：
发生异常: SSLError
HTTPSConnectionPool(host='www.legulegu.com', port=443): Max retries exceeded with url: /api/stock-data/market-ttm-lyr?marketId=5&token=a9fbe601e15d659fb284c53033ce1a3f (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)')))

**描述遇到的问题**
1. 操作系统版本： macOS 13
2. Python 版本： 3.10.5
3. AKShare 版本： 1.8.5 已更新为最新
4. 接口的名称和代码： ak.stock_a_ttm_lyr()
5. 接口报错的截图或代码
![Xnip2022-11-22_10-02-39](https://user-images.githubusercontent.com/30892328/203199818-5ae1a1e7-cea7-4a37-abc2-1724e54f80d4.png)

7. 期望获得的正确结果

**Comment by jindaxiang** [comment]
> 在vscode上运行的报错信息为： 发生异常: SSLError HTTPSConnectionPool(host='www.legulegu.com', port=443): Max retries exceeded with url: /api/stock-data/market-ttm-lyr?marketId=5&token=a9fbe601e15d659fb284c53033ce1a3f (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)')))
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本： macOS 13
> 2. Python 版本： 3.10.5
> 3. AKShare 版本： 1.8.5 已更新为最新
> 4. 接口的名称和代码： ak.stock_a_ttm_lyr()
> 5. 接口报错的截图或代码
>    ![Xnip2022-11-22_10-02-39](https://user-images.githubusercontent.com/30892328/203199818-5ae1a1e7-cea7-4a37-abc2-1724e54f80d4.png)
> 6. 期望获得的正确结果

感谢反馈问题，已修复该问题，升级到 AKShare 1.8.9 版本使用
