### ISSUE TITLE
ak.stock_a_all_pb() 接口报错

### ISSUE THREAD

**Issue by wabbaf** [akfamily/akshare#3221]
估计是所有关于www.legulegu.com的接口都有SSL错误的问题

在 vscode 上运行的报错信息为： 
发生异常: SSLError
HTTPSConnectionPool(host='www.legulegu.com', port=443): Max retries exceeded with url: /api/stock-data/market-index-pb?marketId=ALL&token=a9fbe601e15d659fb284c53033ce1a3f (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)')))

描述遇到的问题
**描述遇到的问题**
操作系统版本： macOS 13
Python 版本： 3.10.5
AKShare 版本： 1.8.9 已更新为最新
接口的名称和代码： ak.stock_a_all_pb() 
接口报错的截图或代码

**Comment by jindaxiang** [comment]
> 估计是所有关于www.legulegu.com的接口都有SSL错误的问题
> 
> 在 vscode 上运行的报错信息为： 发生异常: SSLError HTTPSConnectionPool(host='www.legulegu.com', port=443): Max retries exceeded with url: /api/stock-data/market-index-pb?marketId=ALL&token=a9fbe601e15d659fb284c53033ce1a3f (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)')))
> 
> 描述遇到的问题 **描述遇到的问题** 操作系统版本： macOS 13 Python 版本： 3.10.5 AKShare 版本： 1.8.9 已更新为最新 接口的名称和代码： ak.stock_a_all_pb() 接口报错的截图或代码

感谢反馈问题；已修复该问题，升级到 AKShare 1.8.10 版本使用
