### ISSUE TITLE
hope akshare will add data for commodity option expiry dates

### ISSUE THREAD

**Issue by Kayce001** [akfamily/akshare#3223]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
hope akshare will add data for commodity option expiry dates

**Comment by jindaxiang** [comment]
> **Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> 
> **Describe the solution you'd like** A clear and concise description of what you want to happen.
> 
> **Describe alternatives you've considered** A clear and concise description of any alternative solutions or features you've considered.
> 
> **Additional context** hope akshare will add data for commodity option expiry dates

有合适的数据源会增加
