### ISSUE TITLE
All http://datainterface.eastmoney.com/EM_DataCenter/JS.aspx URL does not work. Need replace with new URL

### ISSUE THREAD

**Issue by ForrestFeng** [akfamily/akshare#3226]
Python: 3.8
OS: Linux 
akshare:1.8.10

**Error of the current URL:**
![image](https://user-images.githubusercontent.com/5875631/203457295-786b1af8-d09f-458e-92d3-85420fa6bbbe.png)

**This bad URL often result error like this:**
![image](https://user-images.githubusercontent.com/5875631/203457852-f0d1bb9c-69e1-434b-9c48-6c6f0747e77a.png)

**To fix such issues all the bad URL should be replace with new URL in code base**
**Please check one of the file macro_china.py**
![image](https://user-images.githubusercontent.com/5875631/203457426-7c2f03e0-5f70-46b2-a878-0c6ddf30df32.png)

**Comment by vivienicepig** [comment]
Do you have the newest URL? I have encouter this issue too.
Appears many eastmoney api cannot run correctly.

**Comment by ForrestFeng** [comment]
I do not know, but @jindaxiang has fixed a similar issue with a new URL of  "https://datacenter-web.eastmoney.com/api/data/v1/get". You may check if this url can be used to fix this issue.


![image](https://user-images.githubusercontent.com/5875631/204122371-abb1cbc6-2195-453d-ae1a-5bc80ad7df42.png)

**Comment by jindaxiang** [comment]
> Python: 3.8 OS: Linux akshare:1.8.10
> 
> **Error of the current URL:** ![image](https://user-images.githubusercontent.com/5875631/203457295-786b1af8-d09f-458e-92d3-85420fa6bbbe.png)
> 
> **This bad URL often result error like this:** ![image](https://user-images.githubusercontent.com/5875631/203457852-f0d1bb9c-69e1-434b-9c48-6c6f0747e77a.png)
> 
> **To fix such issues all the bad URL should be replace with new URL in code base** **Please check one of the file macro_china.py** ![image](https://user-images.githubusercontent.com/5875631/203457426-7c2f03e0-5f70-46b2-a878-0c6ddf30df32.png)

感谢反馈问题；已修复该问题，升级到 AKShare 1.8.17 版本使用
