### ISSUE TITLE
同花顺行业板块能否增加更详细的数据，目前只能获取到行业代码

### ISSUE THREAD

**Issue by xsstomy** [akfamily/akshare#3229]
如下图

<img width="1217" alt="image" src="https://user-images.githubusercontent.com/8943787/203471002-c3382f8c-3ba7-421a-a1cf-a08624eb24a3.png">

stock_board_industry_name_ths  这个只能获取行业的名字

<img width="731" alt="image" src="https://user-images.githubusercontent.com/8943787/203471586-4164e429-ac78-4593-8891-87c7ee1d94dd.png">

我看东方财富行业板块提供了更详细的数据。

<img width="736" alt="image" src="https://user-images.githubusercontent.com/8943787/203471084-d5e9aaa6-625c-4821-b47c-f7de71424d6d.png">

**Comment by jindaxiang** [comment]
> 如下图
> 
> <img alt="image" width="1217" src="https://user-images.githubusercontent.com/8943787/203471002-c3382f8c-3ba7-421a-a1cf-a08624eb24a3.png">
> 
> stock_board_industry_name_ths 这个只能获取行业的名字
> 
> <img alt="image" width="731" src="https://user-images.githubusercontent.com/8943787/203471586-4164e429-ac78-4593-8891-87c7ee1d94dd.png">
> 
> 我看东方财富行业板块提供了更详细的数据。
> 
> <img alt="image" width="736" src="https://user-images.githubusercontent.com/8943787/203471084-d5e9aaa6-625c-4821-b47c-f7de71424d6d.png">

已新增 stock_board_industry_summary_ths 接口，升级到 AKShare 1.8.14 版本使用
