### ISSUE TITLE
sw_index_daily_indicator接口返回异常

### ISSUE THREAD

**Issue by yaotao3000** [akfamily/akshare#3231]
版本1.8.11，1.8.10皆有以下问题，anaconda3环境，python3.8

调用
import akshare as ak
sw_index_daily_indicator_df = ak.sw_index_daily_indicator(symbol="801010", start_date="20191201", end_date="20191207", data_type="Day")

结果返回报

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~/opt/anaconda3/lib/python3.8/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   2894             try:
-> 2895                 return self._engine.get_loc(casted_key)
   2896             except KeyError as err:

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'date'

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
<ipython-input-7-8cedb5086b31> in <module>
      1 import akshare as ak
      2 
----> 3 sw_index_daily_indicator_df = ak.sw_index_daily_indicator(symbol="801010", start_date="20191201", end_date="20191207", data_type="Day")
      4 sw_index_daily_indicator_df

~/opt/anaconda3/lib/python3.8/site-packages/akshare/index/index_sw.py in sw_index_daily_indicator(symbol, start_date, end_date, data_type)
    323             )
    324     temp_df = pd.DataFrame(data)
--> 325     temp_df["date"] = pd.to_datetime(temp_df["date"]).dt.date
    326     temp_df["close"] = pd.to_numeric(temp_df["close"])
    327     temp_df["volume"] = temp_df["volume"].apply(lambda x: x.replace(",", ""))

~/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py in __getitem__(self, key)
   2904             if self.columns.nlevels > 1:
   2905                 return self._getitem_multilevel(key)
-> 2906             indexer = self.columns.get_loc(key)
   2907             if is_integer(indexer):
   2908                 indexer = [indexer]

~/opt/anaconda3/lib/python3.8/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   2895                 return self._engine.get_loc(casted_key)
   2896             except KeyError as err:
-> 2897                 raise KeyError(key) from err
   2898 
   2899         if tolerance is not None:

KeyError: 'date'

**Comment by jindaxiang** [comment]
> sw_index_daily_indicator

接口暂时不能使用；参见文档
