### ISSUE TITLE
韭菜说接口已经更新，无法获得指数的历史PE/PB数据

### ISSUE THREAD

**Issue by J-Z-Z** [akfamily/akshare#3233]
**Describe the bug**
韭菜说接口已经更新，无法获得指数的历史PE/PB数据

**To Reproduce**
akshare/index/zh_stock_index_csindex.py

def index_value_name_funddb() -> pd.DataFrame:
这个函数中，从韭菜圈api接口获得数据，
url = "https://api.jiucaishuo.com/v2/guzhi/newtubiaolinedata"
    payload = {
        "gu_code": name_code_map[symbol],
        "pe_category": indicator_map[indicator],
    }
    r = requests.post(url, json=payload, headers=headers)

这段代码 无法获得数据， 应该是这个api 增加了反爬虫策略。

**Screenshots**

**Desktop (please complete the following information):**
 - OS:  pc
直接使用python调用这个接口

**Comment by jindaxiang** [comment]
> **Describe the bug** 韭菜说接口已经更新，无法获得指数的历史PE/PB数据
> 
> **To Reproduce** akshare/index/zh_stock_index_csindex.py
> 
> def index_value_name_funddb() -> pd.DataFrame: 这个函数中，从韭菜圈api接口获得数据， url = "https://api.jiucaishuo.com/v2/guzhi/newtubiaolinedata" payload = { "gu_code": name_code_map[symbol], "pe_category": indicator_map[indicator], } r = requests.post(url, json=payload, headers=headers)
> 
> 这段代码 无法获得数据， 应该是这个api 增加了反爬虫策略。
> 
> **Screenshots**
> 
> **Desktop (please complete the following information):**
> 
> * OS:  pc
>   直接使用python调用这个接口

可以正常获取
