### ISSUE TITLE
AKShare stock_price_js 接口报错‘JSONDecodeError ’

### ISSUE THREAD

**Issue by happyhzq** [akfamily/akshare#3234]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```

**描述遇到的问题**
1. 操作系统版本-Docker20.10.21
2. Python 版本-3.8
3. AKShare 版本-最新
4. 接口的名称和代码‘stock_price_js_df = ak.stock_price_js(symbol="us")’
5. 接口报错的截图或代码
---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
File /usr/local/lib/python3.8/site-packages/requests/models.py:971, in Response.json(self, **kwargs)
    970 try:
--> 971     return complexjson.loads(self.text, **kwargs)
    972 except JSONDecodeError as e:
    973     # Catch JSON-related errors and raise as requests.JSONDecodeError
    974     # This aliases json.JSONDecodeError and simplejson.JSONDecodeError

File /usr/local/lib/python3.8/json/__init__.py:357, in loads(s, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    354 if (cls is None and object_hook is None and
    355         parse_int is None and parse_float is None and
    356         parse_constant is None and object_pairs_hook is None and not kw):
--> 357     return _default_decoder.decode(s)
    358 if cls is None:

File /usr/local/lib/python3.8/json/decoder.py:337, in JSONDecoder.decode(self, s, _w)
    333 """Return the Python representation of ``s`` (a ``str`` instance
    334 containing a JSON document).
    335 
    336 """
--> 337 obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    338 end = _w(s, end).end()

File /usr/local/lib/python3.8/json/decoder.py:355, in JSONDecoder.raw_decode(self, s, idx)
    354 except StopIteration as err:
--> 355     raise JSONDecodeError("Expecting value", s, err.value) from None
    356 return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

JSONDecodeError                           Traceback (most recent call last)
Cell In [1], line 3
      1 import akshare as ak
----> 3 stock_price_js_df = ak.stock_price_js(symbol="us")
      4 print(stock_price_js_df)

File /usr/local/lib/python3.8/site-packages/akshare/stock/stock_us_js.py:43, in stock_price_js(symbol)
     26 headers = {
     27     "accept": "application/json, text/plain, */*",
     28     "accept-encoding": "gzip, deflate, br",
   (...)
     40     "x-version": "1.0.0"
     41 }
     42 r = requests.get(url, params=params, headers=headers)
---> 43 json_data = r.json()
     44 temp_df = pd.DataFrame(json_data["data"]["list"])
     45 temp_df.columns = [
     46     "_",
     47     "_",
   (...)
     57     "_",
     58 ]

File /usr/local/lib/python3.8/site-packages/requests/models.py:975, in Response.json(self, **kwargs)
    971     return complexjson.loads(self.text, **kwargs)
    972 except JSONDecodeError as e:
    973     # Catch JSON-related errors and raise as requests.JSONDecodeError
    974     # This aliases json.JSONDecodeError and simplejson.JSONDecodeError
--> 975     raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)

JSONDecodeError: Expecting value: line 1 column 1 (char 0)


7. 期望获得的正确结果-正常数据

**Comment by happyhzq** [comment]
Docker image: registry.cn-shanghai.aliyuncs.com/akfamily/aktools:jupyter

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> 
> **描述遇到的问题**
> 1. 操作系统版本-Docker20.10.21
> 2. Python 版本-3.8
> 3. AKShare 版本-最新
> 4. 接口的名称和代码‘stock_price_js_df = ak.stock_price_js(symbol="us")’
> 5. 接口报错的截图或代码
> ---------------------------------------------------------------------------
> JSONDecodeError                           Traceback (most recent call last)
> File /usr/local/lib/python3.8/site-packages/requests/models.py:971, in Response.json(self, **kwargs)
>     970 try:
> --> 971     return complexjson.loads(self.text, **kwargs)
>     972 except JSONDecodeError as e:
>     973     # Catch JSON-related errors and raise as requests.JSONDecodeError
>     974     # This aliases json.JSONDecodeError and simplejson.JSONDecodeError
> 
> File /usr/local/lib/python3.8/json/__init__.py:357, in loads(s, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
>     354 if (cls is None and object_hook is None and
>     355         parse_int is None and parse_float is None and
>     356         parse_constant is None and object_pairs_hook is None and not kw):
> --> 357     return _default_decoder.decode(s)
>     358 if cls is None:
> 
> File /usr/local/lib/python3.8/json/decoder.py:337, in JSONDecoder.decode(self, s, _w)
>     333 """Return the Python representation of ``s`` (a ``str`` instance
>     334 containing a JSON document).
>     335 
>     336 """
> --> 337 obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>     338 end = _w(s, end).end()
> 
> File /usr/local/lib/python3.8/json/decoder.py:355, in JSONDecoder.raw_decode(self, s, idx)
>     354 except StopIteration as err:
> --> 355     raise JSONDecodeError("Expecting value", s, err.value) from None
>     356 return obj, end
> 
> JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 
> During handling of the above exception, another exception occurred:
> 
> JSONDecodeError                           Traceback (most recent call last)
> Cell In [1], line 3
>       1 import akshare as ak
> ----> 3 stock_price_js_df = ak.stock_price_js(symbol="us")
>       4 print(stock_price_js_df)
> 
> File /usr/local/lib/python3.8/site-packages/akshare/stock/stock_us_js.py:43, in stock_price_js(symbol)
>      26 headers = {
>      27     "accept": "application/json, text/plain, */*",
>      28     "accept-encoding": "gzip, deflate, br",
>    (...)
>      40     "x-version": "1.0.0"
>      41 }
>      42 r = requests.get(url, params=params, headers=headers)
> ---> 43 json_data = r.json()
>      44 temp_df = pd.DataFrame(json_data["data"]["list"])
>      45 temp_df.columns = [
>      46     "_",
>      47     "_",
>    (...)
>      57     "_",
>      58 ]
> 
> File /usr/local/lib/python3.8/site-packages/requests/models.py:975, in Response.json(self, **kwargs)
>     971     return complexjson.loads(self.text, **kwargs)
>     972 except JSONDecodeError as e:
>     973     # Catch JSON-related errors and raise as requests.JSONDecodeError
>     974     # This aliases json.JSONDecodeError and simplejson.JSONDecodeError
> --> 975     raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
> 
> JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 
> 
> 7. 期望获得的正确结果-正常数据
> ```

该接口暂时不能使用；已新增说明

**Comment by happyhzq** [comment]
谢谢
