### ISSUE TITLE
linux后导入报错的问题

### ISSUE THREAD

**Issue by bobyang-code** [akfamily/akshare#3241]
RuntimeError: Native library not available at /home/pi/.local/lib/python3.9/site-packages/py_mini_racer/libmini_racer.glibc.so
Exception ignored in: <function MiniRacer.__del__ at 0x7f9e549dc0>
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.9/site-packages/py_mini_racer/py_mini_racer.py", line 315, in __del__
    self.ext.mr_free_context(getattr(self, "ctx", None))
AttributeError: 'NoneType' object has no attribute 'mr_free_context'
请问改类型问题怎么解决

**Comment by jindaxiang** [comment]
> RuntimeError: Native library not available at /home/pi/.local/lib/python3.9/site-packages/py_mini_racer/libmini_racer.glibc.so Exception ignored in: <function MiniRacer.**del** at 0x7f9e549dc0> Traceback (most recent call last): File "/home/pi/.local/lib/python3.9/site-packages/py_mini_racer/py_mini_racer.py", line 315, in **del** self.ext.mr_free_context(getattr(self, "ctx", None)) AttributeError: 'NoneType' object has no attribute 'mr_free_context' 请问改类型问题怎么解决

树莓派暂不支持
