### ISSUE TITLE
AKShare 接口 stock_board_concept_hist_em 问题报告

### ISSUE THREAD

**Issue by simon-yanghl** [akfamily/akshare#3247]
**描述遇到的问题**
4. 接口的名称和代码
stock_board_concept_hist_em

6. 期望获得的正确结果
希望添加周线数据和起止时间参数

**Comment by jindaxiang** [comment]
> **描述遇到的问题** 4. 接口的名称和代码 stock_board_concept_hist_em
> 
> 6. 期望获得的正确结果
>    希望添加周线数据和起止时间参数

感谢反馈问题；升级到 AKShare 1.8.20 版本使用
