### ISSUE TITLE
fund_etf_category_sina接口是否有复权数据

### ISSUE THREAD

**Issue by zsrl** [akfamily/akshare#3258]
```python
df = ak.fund_etf_hist_sina(symbol="sh512010")
```

想获取某基金的历史行情，返回的数据是不复权的。请问作者大佬是否可以返回复权数据。

**Comment by jindaxiang** [comment]
> ```python
> df = ak.fund_etf_hist_sina(symbol="sh512010")
> ```
> 
> 想获取某基金的历史行情，返回的数据是不复权的。请问作者大佬是否可以返回复权数据。

数据源暂未提供

**Comment by zsrl** [comment]
@jindaxiang 

大佬，关于基金复权数据这个问题。我又研究了一下。 `ak.fund_etf_hist_sina`获取的源站新浪，的确没有复权数据。

但我翻看了一下`ak.stock_zh_a_hist`的源码，是从东财的一个页面上获取的。

我尝试把页面参数换成基金代码，也可以访问，例如：https://quote.eastmoney.com/concept/sh512010.html?from=classic

大概看了一下浏览器network里的数据，是有复权数据的，请求接口应该与股票相同。

不过使用一下代码直接调用，是会报错的。

```python
df = ak.stock_zh_a_hist(symbol="512010", adjust="qfq")
```
![image](https://user-images.githubusercontent.com/4284926/205328347-b878e437-3f88-482c-9cda-912582461cc7.png)

请问是否可以兼容一下基金代码，或者开辟个新api，从东财获取基金历史数据。
