### ISSUE TITLE
全球指数接口问题

### ISSUE THREAD

**Issue by rayzzy** [akfamily/akshare#3263]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本
2. Python 版本
3. AKShare 版本
4. 接口的名称和代码
全球指数接口，测试案例代码
index_investing_global_df = ak.index_investing_global(area="中国", symbol="富时中国A50指数", period="每日", start_date="20100101", end_date="20220808")
print(index_investing_global_df)
6. 接口报错的截图或代码
![image](https://user-images.githubusercontent.com/30099596/205428720-8504d808-cf57-4856-a466-2f2f50ad27d0.png)
![image](https://user-images.githubusercontent.com/30099596/205428732-778039e8-5811-4fae-aab5-8b3c0793d92d.png)

7. 期望获得的正确结果

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本
> 2. Python 版本
> 3. AKShare 版本
> 4. 接口的名称和代码
>    全球指数接口，测试案例代码
>    index_investing_global_df = ak.index_investing_global(area="中国", symbol="富时中国A50指数", period="每日", start_date="20100101", end_date="20220808")
>    print(index_investing_global_df)
> 5. 接口报错的截图或代码
>    ![image](https://user-images.githubusercontent.com/30099596/205428720-8504d808-cf57-4856-a466-2f2f50ad27d0.png)
>    ![image](https://user-images.githubusercontent.com/30099596/205428732-778039e8-5811-4fae-aab5-8b3c0793d92d.png)
> 6. 期望获得的正确结果

该接口在暂时不能使用
