### ISSUE TITLE
AKShare 安装失败

### ISSUE THREAD

**Issue by simon-yanghl** [akfamily/akshare#3265]
**描述遇到的问题**
1. 操作系统版本
WIN SERVER 2019
2. Python 版本
  3.10

错误提示：

PS P:\Python> pip install akshare -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host=mirrors.aliyun.com  --upgrade
Looking in indexes: http://mirrors.aliyun.com/pypi/simple/
Collecting akshare
  Downloading http://mirrors.aliyun.com/pypi/packages/f5/d0/e73c15079a515567597c7d2479a3ec59412d2acdf47cf8536e831e045ba2/akshare-1.8.24-py3-none-any.whl (965 kB)
     ---------------------------------------- 965.9/965.9 kB 325.4 kB/s eta 0:00:00
Collecting beautifulsoup4>=4.9.1
  Downloading http://mirrors.aliyun.com/pypi/packages/9c/d8/909c4089dbe4ade9f9705f143c9f13f065049a9d5e7d34c828aefdd0a97c/beautifulsoup4-4.11.1-py3-none-any.whl (128 kB)
     ---------------------------------------- 128.2/128.2 kB 343.8 kB/s eta 0:00:00
Collecting lxml>=4.2.1
  Downloading http://mirrors.aliyun.com/pypi/packages/70/bb/7a2c7b4f8f434aa1ee801704bf08f1e53d7b5feba3d5313ab17003477808/lxml-4.9.1.tar.gz (3.4 MB)
     ---------------------------------------- 3.4/3.4 MB 350.4 kB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pandas>=0.25 in c:\program files\python\lib\site-packages (from akshare) (1.5.2)
Requirement already satisfied: requests>=2.22.0 in c:\program files\python\lib\site-packages (from akshare) (2.28.1)
Requirement already satisfied: pypinyin>=0.35.0 in c:\program files\python\lib\site-packages (from akshare) (0.47.1)
Requirement already satisfied: websocket-client>=0.56.0 in c:\program files\python\lib\site-packages (from akshare) (1.4.2)
Collecting html5lib>=1.0.1
  Downloading http://mirrors.aliyun.com/pypi/packages/6c/dd/a834df6482147d48e225a49515aabc28974ad5a4ca3215c18a882565b028/html5lib-1.1-py2.py3-none-any.whl (112 kB)
     ---------------------------------------- 112.2/112.2 kB 271.8 kB/s eta 0:00:00
Requirement already satisfied: xlrd>=1.2.0 in c:\program files\python\lib\site-packages (from akshare) (2.0.1)
Requirement already satisfied: urllib3>=1.25.8 in c:\program files\python\lib\site-packages (from akshare) (1.26.13)
Collecting tqdm>=4.43.0
  Downloading http://mirrors.aliyun.com/pypi/packages/47/bb/849011636c4da2e44f1253cd927cfb20ada4374d8b3a4e425416e84900cc/tqdm-4.64.1-py2.py3-none-any.whl (78 kB)
     ---------------------------------------- 78.5/78.5 kB 313.0 kB/s eta 0:00:00
Requirement already satisfied: openpyxl>=3.0.3 in c:\program files\python\lib\site-packages (from akshare) (3.0.10)
Requirement already satisfied: jsonpath>=0.82 in c:\program files\python\lib\site-packages (from akshare) (0.82)
Requirement already satisfied: tabulate>=0.8.6 in c:\program files\python\lib\site-packages (from akshare) (0.9.0)
Collecting decorator>=4.4.2
  Downloading http://mirrors.aliyun.com/pypi/packages/d5/50/83c593b07763e1161326b3b8c6686f0f4b0f24d5526546bee538c89837d6/decorator-5.1.1-py3-none-any.whl (9.1 kB)
Requirement already satisfied: py-mini-racer>=0.6.0 in c:\program files\python\lib\site-packages (from akshare) (0.6.0)
Collecting requests-cache>=0.9.3
  Downloading http://mirrors.aliyun.com/pypi/packages/65/a8/404ed794200edecf53f952066a8d33887924c6956ef0db71fccb90f1f68f/requests_cache-0.9.7-py3-none-any.whl (48 kB)
     ---------------------------------------- 48.5/48.5 kB 348.0 kB/s eta 0:00:00
Collecting cfscrape>=2.1.1
  Downloading http://mirrors.aliyun.com/pypi/packages/74/6b/410751a88b7c868f147c721446b83148329d2936707df2433a4fed1d78da/cfscrape-2.1.1-py3-none-any.whl (12 kB)
Requirement already satisfied: soupsieve>1.2 in c:\program files\python\lib\site-packages (from beautifulsoup4>=4.9.1->akshare) (2.3.2.post1)
Requirement already satisfied: six>=1.9 in c:\program files\python\lib\site-packages (from html5lib>=1.0.1->akshare) (1.16.0)
Requirement already satisfied: webencodings in c:\program files\python\lib\site-packages (from html5lib>=1.0.1->akshare) (0.5.1)
Requirement already satisfied: et-xmlfile in c:\program files\python\lib\site-packages (from openpyxl>=3.0.3->akshare) (1.1.0)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\program files\python\lib\site-packages (from pandas>=0.25->akshare) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\program files\python\lib\site-packages (from pandas>=0.25->akshare) (2022.6)
Requirement already satisfied: numpy>=1.21.0 in c:\program files\python\lib\site-packages (from pandas>=0.25->akshare) (1.23.5)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\program files\python\lib\site-packages (from requests>=2.22.0->akshare) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in c:\program files\python\lib\site-packages (from requests>=2.22.0->akshare) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\program files\python\lib\site-packages (from requests>=2.22.0->akshare) (2022.9.24)
Requirement already satisfied: appdirs>=1.4.4 in c:\program files\python\lib\site-packages (from requests-cache>=0.9.3->akshare) (1.4.4)
Collecting attrs>=21.2
  Downloading http://mirrors.aliyun.com/pypi/packages/f2/bc/d817287d1aa01878af07c19505fafd1165cd6a119e9d0821ca1d1c20312d/attrs-22.1.0-py2.py3-none-any.whl (58 kB)
     ---------------------------------------- 58.8/58.8 kB 344.4 kB/s eta 0:00:00
Collecting cattrs>=22.2
  Downloading http://mirrors.aliyun.com/pypi/packages/43/3b/1d34fc4449174dfd2bc5ad7047a23edb6558b2e4b5a41b25a8ad6655c6c7/cattrs-22.2.0-py3-none-any.whl (35 kB)
Requirement already satisfied: url-normalize>=1.4 in c:\program files\python\lib\site-packages (from requests-cache>=0.9.3->akshare) (1.4.3)
Collecting colorama
  Downloading http://mirrors.aliyun.com/pypi/packages/d1/d6/3965ed04c63042e047cb6a3e6ed1a63a35087b6a609aa3a15ed8ac56c221/colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Installing collected packages: lxml, html5lib, decorator, colorama, beautifulsoup4, attrs, tqdm, cfscrape, cattrs, requests-cache, akshare
  DEPRECATION: lxml is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible
replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for lxml ... error
  error: subprocess-exited-with-error

  × Running setup.py install for lxml did not run successfully.
  │ exit code: 1
  ╰─> [76 lines of output]
      Building lxml version 4.9.1.
      Building without Cython.
      Building against pre-built libxml2 andl libxslt libraries
      running install
      C:\Program Files\Python\Lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-311
      creating build\lib.win-amd64-cpython-311\lxml
      copying src\lxml\builder.py -> build\lib.win-amd64-cpython-311\lxml
      copying src\lxml\cssselect.py -> build\lib.win-amd64-cpython-311\lxml
      copying src\lxml\doctestcompare.py -> build\lib.win-amd64-cpython-311\lxml
      copying src\lxml\ElementInclude.py -> build\lib.win-amd64-cpython-311\lxml
      copying src\lxml\pyclasslookup.py -> build\lib.win-amd64-cpython-311\lxml
      copying src\lxml\sax.py -> build\lib.win-amd64-cpython-311\lxml
      copying src\lxml\usedoctest.py -> build\lib.win-amd64-cpython-311\lxml
      copying src\lxml\_elementpath.py -> build\lib.win-amd64-cpython-311\lxml
      copying src\lxml\__init__.py -> build\lib.win-amd64-cpython-311\lxml
      creating build\lib.win-amd64-cpython-311\lxml\includes
      copying src\lxml\includes\__init__.py -> build\lib.win-amd64-cpython-311\lxml\includes
      creating build\lib.win-amd64-cpython-311\lxml\html
      copying src\lxml\html\builder.py -> build\lib.win-amd64-cpython-311\lxml\html
      copying src\lxml\html\clean.py -> build\lib.win-amd64-cpython-311\lxml\html
      copying src\lxml\html\defs.py -> build\lib.win-amd64-cpython-311\lxml\html
      copying src\lxml\html\diff.py -> build\lib.win-amd64-cpython-311\lxml\html
      copying src\lxml\html\ElementSoup.py -> build\lib.win-amd64-cpython-311\lxml\html
      copying src\lxml\html\formfill.py -> build\lib.win-amd64-cpython-311\lxml\html
      copying src\lxml\html\html5parser.py -> build\lib.win-amd64-cpython-311\lxml\html
      copying src\lxml\html\soupparser.py -> build\lib.win-amd64-cpython-311\lxml\html
      copying src\lxml\html\usedoctest.py -> build\lib.win-amd64-cpython-311\lxml\html
      copying src\lxml\html\_diffcommand.py -> build\lib.win-amd64-cpython-311\lxml\html
      copying src\lxml\html\_html5builder.py -> build\lib.win-amd64-cpython-311\lxml\html
      copying src\lxml\html\_setmixin.py -> build\lib.win-amd64-cpython-311\lxml\html
      copying src\lxml\html\__init__.py -> build\lib.win-amd64-cpython-311\lxml\html
      creating build\lib.win-amd64-cpython-311\lxml\isoschematron
      copying src\lxml\isoschematron\__init__.py -> build\lib.win-amd64-cpython-311\lxml\isoschematron
      copying src\lxml\etree.h -> build\lib.win-amd64-cpython-311\lxml
      copying src\lxml\etree_api.h -> build\lib.win-amd64-cpython-311\lxml
      copying src\lxml\lxml.etree.h -> build\lib.win-amd64-cpython-311\lxml
      copying src\lxml\lxml.etree_api.h -> build\lib.win-amd64-cpython-311\lxml
      copying src\lxml\includes\c14n.pxd -> build\lib.win-amd64-cpython-311\lxml\includes
      copying src\lxml\includes\config.pxd -> build\lib.win-amd64-cpython-311\lxml\includes
      copying src\lxml\includes\dtdvalid.pxd -> build\lib.win-amd64-cpython-311\lxml\includes
      copying src\lxml\includes\etreepublic.pxd -> build\lib.win-amd64-cpython-311\lxml\includes
      copying src\lxml\includes\htmlparser.pxd -> build\lib.win-amd64-cpython-311\lxml\includes
      copying src\lxml\includes\relaxng.pxd -> build\lib.win-amd64-cpython-311\lxml\includes
      copying src\lxml\includes\schematron.pxd -> build\lib.win-amd64-cpython-311\lxml\includes
      copying src\lxml\includes\tree.pxd -> build\lib.win-amd64-cpython-311\lxml\includes
      copying src\lxml\includes\uri.pxd -> build\lib.win-amd64-cpython-311\lxml\includes
      copying src\lxml\includes\xinclude.pxd -> build\lib.win-amd64-cpython-311\lxml\includes
      copying src\lxml\includes\xmlerror.pxd -> build\lib.win-amd64-cpython-311\lxml\includes
      copying src\lxml\includes\xmlparser.pxd -> build\lib.win-amd64-cpython-311\lxml\includes
      copying src\lxml\includes\xmlschema.pxd -> build\lib.win-amd64-cpython-311\lxml\includes
      copying src\lxml\includes\xpath.pxd -> build\lib.win-amd64-cpython-311\lxml\includes
      copying src\lxml\includes\xslt.pxd -> build\lib.win-amd64-cpython-311\lxml\includes
      copying src\lxml\includes\__init__.pxd -> build\lib.win-amd64-cpython-311\lxml\includes
      copying src\lxml\includes\etree_defs.h -> build\lib.win-amd64-cpython-311\lxml\includes
      copying src\lxml\includes\lxml-version.h -> build\lib.win-amd64-cpython-311\lxml\includes
      creating build\lib.win-amd64-cpython-311\lxml\isoschematron\resources
      creating build\lib.win-amd64-cpython-311\lxml\isoschematron\resources\rng
      copying src\lxml\isoschematron\resources\rng\iso-schematron.rng -> build\lib.win-amd64-cpython-311\lxml\isoschematron\resources\rng
      creating build\lib.win-amd64-cpython-311\lxml\isoschematron\resources\xsl
      copying src\lxml\isoschematron\resources\xsl\RNG2Schtrn.xsl -> build\lib.win-amd64-cpython-311\lxml\isoschematron\resources\xsl
      copying src\lxml\isoschematron\resources\xsl\XSD2Schtrn.xsl -> build\lib.win-amd64-cpython-311\lxml\isoschematron\resources\xsl
      creating build\lib.win-amd64-cpython-311\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
      copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_abstract_expand.xsl -> build\lib.win-amd64-cpython-311\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
      copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_dsdl_include.xsl -> build\lib.win-amd64-cpython-311\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
      copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_schematron_message.xsl -> build\lib.win-amd64-cpython-311\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
      copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_schematron_skeleton_for_xslt1.xsl -> build\lib.win-amd64-cpython-311\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
      copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_svrl_for_xslt1.xsl -> build\lib.win-amd64-cpython-311\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
      copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\readme.txt -> build\lib.win-amd64-cpython-311\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
      running build_ext
      building 'lxml.etree' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> lxml

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by jindaxiang** [comment]
按错误提示操作：error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
