### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by xiaofeng0223** [akfamily/akshare#3272]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本   => win10
2. Python 版本   => python3.7.4
3. AKShare 版本  =>1.8.26
4. 接口的名称和代码
5. 
![image](https://user-images.githubusercontent.com/59379341/206338012-6c8d92f5-b5b0-4e14-933b-d71977ff21bf.png)

6. 接口报错的截图或代码
外汇接口无法获取数据
8. 期望获得的正确结果
无法按照文档的demo拿到预期的结果

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本   => win10
> 2. Python 版本   => python3.7.4
> 3. AKShare 版本  =>1.8.26
> 4. 接口的名称和代码
> 
> ![image](https://user-images.githubusercontent.com/59379341/206338012-6c8d92f5-b5b0-4e14-933b-d71977ff21bf.png)
> 
> 6. 接口报错的截图或代码
>    外汇接口无法获取数据
> 7. 期望获得的正确结果
>    无法按照文档的demo拿到预期的结果

该接口暂时不能使用，已在文档增加说明
