### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by qmaxzh** [akfamily/akshare#3278]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本 - ubuntu 20.04
2. Python 版本 - 3.7
3. AKShare 版本 -  akshare-1.8.26
4. 接口的名称和代码: 

ak.macro_china_cpi()
ak.macro_china_new_financial_credit()

两个借口报错一样：
JSONDecodeError: Missing value for object property, expected ":"

**Comment by jindaxiang** [comment]
> macro_china_new_financial_credit

接口使用正常；请升级依赖到最新版
