### ISSUE TITLE
AKShare 接口问题报告——使用基金分红接口: fund_fh_em，报unexpected EOF while parsing

### ISSUE THREAD

**Issue by lwx0218** [akfamily/akshare#3280]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

Python 版本 - 3.7.12
AKShare 版本 - akshare-1.8.26
接口的名称和代码:

ak.fund_fh_em()

![image](https://user-images.githubusercontent.com/28493513/206998037-2cbbae8e-9966-4a7a-949a-3e1f9eb7f8dd.png)

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> Python 版本 - 3.7.12 AKShare 版本 - akshare-1.8.26 接口的名称和代码:
> 
> ak.fund_fh_em()
> 
> ![image](https://user-images.githubusercontent.com/28493513/206998037-2cbbae8e-9966-4a7a-949a-3e1f9eb7f8dd.png)

感谢反馈问题；已修复该问题，升级到 AKShare 1.8.27 版本使用
