### ISSUE TITLE
新人求教，SSLError报错

### ISSUE THREAD

**Issue by a52682312** [akfamily/akshare#3287]
多个接口报错SSLError: HTTPSConnectionPool(host='datacenter-web.eastmoney.com', port=443)
![image](https://user-images.githubusercontent.com/64454325/208055143-0c429f2e-74ac-413c-bf8b-1bd8e14f30b4.png)
尝试搜索答案，没搜索到，请问如何解决？

**Comment by jindaxiang** [comment]
> 多个接口报错SSLError: HTTPSConnectionPool(host='datacenter-web.eastmoney.com', port=443) ![image](https://user-images.githubusercontent.com/64454325/208055143-0c429f2e-74ac-413c-bf8b-1bd8e14f30b4.png) 尝试搜索答案，没搜索到，请问如何解决？

建议检查下本地网络问题；或者在访问接口的时候控制下频率
