### ISSUE TITLE
AKShare 接口问题报告 index_value_name_funddb_df

### ISSUE THREAD

**Issue by haox1982** [akfamily/akshare#3288]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本:   Mac 12.6.2
2. Python 版本: 3.9
3. AKShare 版本: 1.8.26
4. 接口的名称和代码:   index_value_name_funddb_df
      import akshare as ak
      index_value_name_funddb_df = ak.index_value_name_funddb()
      print(index_value_name_funddb_df)

5. 接口报错的截图或代码:  
      ValueError: Length mismatch: Expected axis has 30 elements, new values have 32 elements
6. 期望获得的正确结果
       df

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本:   Mac 12.6.2
> 2. Python 版本: 3.9
> 3. AKShare 版本: 1.8.26
> 4. 接口的名称和代码:   index_value_name_funddb_df
>    import akshare as ak
>    index_value_name_funddb_df = ak.index_value_name_funddb()
>    print(index_value_name_funddb_df)
> 5. 接口报错的截图或代码:
>    ValueError: Length mismatch: Expected axis has 30 elements, new values have 32 elements
> 6. 期望获得的正确结果
>    df

感谢反馈问题；已修复该问题，升级到 AKShare 1.8.30 版本使用
