### ISSUE TITLE
AKShare 接口问题报告：ak.index_value_hist_funddb

### ISSUE THREAD

**Issue by xnw176** [akfamily/akshare#3293]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本 mac os
2. Python 版本 3.8
3. AKShare 版本 最新
4. 接口的名称和代码ak.index_value_hist_funddb
5. 接口报错的截图或代码
<img width="1062" alt="image" src="https://user-images.githubusercontent.com/82297022/208226668-fb7d3186-793f-4669-8d26-597b8be7f96b.png">

7. 期望获得的正确结果

**Comment by jindaxiang** [comment]
> 4\. index_value_hist_funddb

接口正常；

**Comment by xnw176** [comment]
能否再看一下，我这边还是不行。
另一个韭圈的接口的接口能够正常使用。
