### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by Juncheng-Li** [akfamily/akshare#3296]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本:  Mac Catalina 10.15.7
3. Python 版本: 3.8.6
4. AKShare 版本: 1.8.31
5. 接口的名称和代码:  ak.js_news(timestamp="2022-12-16 17:57:18")
6. 接口报错的截图或代码: news_df = ak.js_news(timestamp="2022-12-16 17:57:18")
<img width="1239" alt="image" src="https://user-images.githubusercontent.com/36284027/208241774-c88e226f-1db9-4981-8296-1a963d46c7d2.png">
8. 期望获得的正确结果: ak.js_news(timestamp="2022-12-16 17:57:18") 不报错执行，返回dataframe

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本:  Mac Catalina 10.15.7
> 2. Python 版本: 3.8.6
> 3. AKShare 版本: 1.8.31
> 4. 接口的名称和代码:  ak.js_news(timestamp="2022-12-16 17:57:18")
> 5. 接口报错的截图或代码: news_df = ak.js_news(timestamp="2022-12-16 17:57:18")
> 
> <img alt="image" width="1239" src="https://user-images.githubusercontent.com/36284027/208241774-c88e226f-1db9-4981-8296-1a963d46c7d2.png">
> 
> 8. 期望获得的正确结果: ak.js_news(timestamp="2022-12-16 17:57:18") 不报错执行，返回dataframe

该接口暂时不能使用
