### ISSUE TITLE
AKShare 接口问题报告 -- index_value_hist_funddb_df

### ISSUE THREAD

**Issue by haox1982** [akfamily/akshare#3299]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本: Mac 12.6.2
2. Python 版本  3.9
3. AKShare 版本: 1.8.31
4. 接口的名称和代码: 
   -  index_value_hist_funddb_df = ak.index_value_hist_funddb(symbol="大盘成长", indicator="市盈率")
 
6. 接口报错的截图或代码
    
<img width="444" alt="image" src="https://user-images.githubusercontent.com/30982263/208270775-53d5e6b7-8bf4-46cc-b062-b588b5eb362f.png">

8. 期望获得的正确结果
  包括 ’指数代码‘ ， ’指数名称‘  信息

**Comment by jindaxiang** [comment]
> * index_value_hist_funddb

接口可以正常使用；请在本地配合其他接口完成该需求
