### ISSUE TITLE
#covid_19_baidu   AKShare 接口问题报告 covid_19_baidu

### ISSUE THREAD

**Issue by xinxiaobao** [akfamily/akshare#3301]
Linux, akshare已更新，接口报错，covid_19_city_df = ak.covid_19_baidu(indicator="中国分城市详情")
错误代码：JSONDecodeError: No value to decode

**Comment by jindaxiang** [comment]
> ak.covid_19_baidu(indicator="中国分城市详情")

疫情接口即将移除
