### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by OatLatte** [akfamily/akshare#3307]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本
WIN10/MAC M2 Ventura 都试过

2. Python 版本
3.9.7

3. AKShare 版本
最新

4. 接口的名称和代码
ak.stock_a_lg_indicator

5. 接口报错的截图或代码
所有8开头的股票代码, 获取的数据日期大量重复(如图所示)
![akshare](https://user-images.githubusercontent.com/103306071/209112880-1448e298-4e10-4c4f-89ea-96b0f0b14169.png)

6. 期望获得的正确结果
日期不重复的争取结果
谢谢!

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本
>    WIN10/MAC M2 Ventura 都试过
> 2. Python 版本
>    3.9.7
> 3. AKShare 版本
>    最新
> 4. 接口的名称和代码
>    ak.stock_a_lg_indicator
> 5. 接口报错的截图或代码
>    所有8开头的股票代码, 获取的数据日期大量重复(如图所示)
>    ![akshare](https://user-images.githubusercontent.com/103306071/209112880-1448e298-4e10-4c4f-89ea-96b0f0b14169.png)
> 6. 期望获得的正确结果
>    日期不重复的争取结果
>    谢谢!

该接口返回的数据与数据源一致；估计是数据源计算有问题；
