### ISSUE TITLE
【AKShare 接口问题报告】接口 macro_cons_gold_volume \ macro_cons_silver_volume 报错

### ISSUE THREAD

**Issue by congcong009** [akfamily/akshare#3314]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本
2. Python 版本 3.9
3. AKShare 版本 1.8.35
4. 接口的名称和代码 macro_cons_gold_volume
5. 接口报错的截图或代码
`Traceback (most recent call last):
  File "C:\Users\congcong009\anaconda3\envs\dev\lib\site-packages\IPython\core\interactiveshell.py", line 3398, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-52b7ec8d97cc>", line 1, in <cell line: 1>
    r.json()
  File "C:\Users\congcong009\anaconda3\envs\dev\lib\site-packages\requests\models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\congcong009\anaconda3\envs\dev\lib\site-packages\simplejson\__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "C:\Users\congcong009\anaconda3\envs\dev\lib\site-packages\simplejson\decoder.py", line 373, in decode
    raise JSONDecodeError("Extra data", s, end, len(s))
simplejson.errors.JSONDecodeError: Extra data: line 1 column 2 - line 3 column 153 (char 1 - 450)`

源代码 macro_constitute.py 70行 `temp_se = pd.DataFrame(r.json()["data"]["values"]).iloc[:, :2]` 返回值报错，其中 r 的查询数据返回为乱码

7. 期望获得的正确结果
同样出错

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本
> 2. Python 版本 3.9
> 3. AKShare 版本 1.8.35
> 4. 接口的名称和代码 macro_cons_gold_volume
> 5. 接口报错的截图或代码
>    `Traceback (most recent call last):   File "C:\Users\congcong009\anaconda3\envs\dev\lib\site-packages\IPython\core\interactiveshell.py", line 3398, in run_code exec(code_obj, self.user_global_ns, self.user_ns)   File "<ipython-input-1-52b7ec8d97cc>", line 1, in <cell line: 1> r.json()   File "C:\Users\congcong009\anaconda3\envs\dev\lib\site-packages\requests\models.py", line 900, in json return complexjson.loads(self.text, **kwargs)   File "C:\Users\congcong009\anaconda3\envs\dev\lib\site-packages\simplejson\__init__.py", line 525, in loads return _default_decoder.decode(s)   File "C:\Users\congcong009\anaconda3\envs\dev\lib\site-packages\simplejson\decoder.py", line 373, in decode raise JSONDecodeError("Extra data", s, end, len(s)) simplejson.errors.JSONDecodeError: Extra data: line 1 column 2 - line 3 column 153 (char 1 - 450)`
> 
> 源代码 macro_constitute.py 70行 `temp_se = pd.DataFrame(r.json()["data"]["values"]).iloc[:, :2]` 返回值报错，其中 r 的查询数据返回为乱码
> 
> 7. 期望获得的正确结果
>    同样出错

感谢反馈问题；已修复该问题，升级到 AKShare 1.8.38 使用；相关接口已经修改，参见相关文档
