### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by ygcool** [akfamily/akshare#3326]
阿里云香港的云服务器ESC
docker部署的aktools。

接口：(尝试过其他国家和指数数据，全是提示:内部服务错误)
`http://127.0.0.1:8001/api/public/index_investing_global?area=土耳其&symbol=土耳其ISE National-100&period=每日&start_date=20221220&end_date=20221228`
和
`http://127.0.0.1:8001/api/public/index_investing_global?area=中国&symbol=上证指数&period=每日&start_date=20221220&end_date=20221229`

响应：
`Internal Server Error`

数据源链接：
`https://cn.investing.com/indices/ise-100`

docker日志：
```
[root@tzjdpool ~]# docker run -p 8001:8001 ak_tools:1.8.42 python -m aktools --host 0.0.0.0 --port 8001
请访问：http://0.0.0.0:8001/version 来获取最新的库版本信息，确保使用最新版本的 AKShare 和 AKTools
当前的 AKTools 版本为：0.0.81，AKShare 版本为：1.8.42
点击打开 HTTP API 主页：http://0.0.0.0:8001/
点击打开接口导览：http://0.0.0.0:8001/docs
INFO:     Started server process [9]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8001 (Press CTRL+C to quit)
INFO:     103.177.248.233:49674 - "GET /api/public/index_investing_global?area=%E4%B8%AD%E5%9B%BD&symbol=%E4%B8%8A%E8%AF%81%E6%8C%87%E6%95%B0&period=%E6%AF%8F%E6%97%A5&start_date=20221220&end_date=20221229 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 235, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aktools/core/api.py", line 140, in root
    received_df = eval("ak." + item_id + f"({eval_str})")
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/akshare/index/index_investing.py", line 162, in index_investing_global
    name_code_dict = index_investing_global_area_index_name_code(area)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/akshare/index/index_investing.py", line 89, in index_investing_global_area_index_name_code
    name_url_dict = _get_global_country_name_url()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/akshare/index/index_investing.py", line 68, in _get_global_country_name_url
    ).find_all("option")[
      ^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'find_all'
```

期待回复，谢谢

**Comment by jindaxiang** [comment]
> 阿里云香港的云服务器ESC docker部署的aktools。
> 
> 接口：(尝试过其他国家和指数数据，全是提示:内部服务错误) `http://127.0.0.1:8001/api/public/index_investing_global?area=土耳其&symbol=土耳其ISE National-100&period=每日&start_date=20221220&end_date=20221228` 和 `http://127.0.0.1:8001/api/public/index_investing_global?area=中国&symbol=上证指数&period=每日&start_date=20221220&end_date=20221229`
> 
> 响应： `Internal Server Error`
> 
> 数据源链接： `https://cn.investing.com/indices/ise-100`
> 
> docker日志：
> 
> ```
> [root@tzjdpool ~]# docker run -p 8001:8001 ak_tools:1.8.42 python -m aktools --host 0.0.0.0 --port 8001
> 请访问：http://0.0.0.0:8001/version 来获取最新的库版本信息，确保使用最新版本的 AKShare 和 AKTools
> 当前的 AKTools 版本为：0.0.81，AKShare 版本为：1.8.42
> 点击打开 HTTP API 主页：http://0.0.0.0:8001/
> 点击打开接口导览：http://0.0.0.0:8001/docs
> INFO:     Started server process [9]
> INFO:     Waiting for application startup.
> INFO:     Application startup complete.
> INFO:     Uvicorn running on http://0.0.0.0:8001 (Press CTRL+C to quit)
> INFO:     103.177.248.233:49674 - "GET /api/public/index_investing_global?area=%E4%B8%AD%E5%9B%BD&symbol=%E4%B8%8A%E8%AF%81%E6%8C%87%E6%95%B0&period=%E6%AF%8F%E6%97%A5&start_date=20221220&end_date=20221229 HTTP/1.1" 500 Internal Server Error
> ERROR:    Exception in ASGI application
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
>     result = await app(  # type: ignore[func-returns-value]
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
>     return await self.app(scope, receive, send)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 270, in __call__
>     await super().__call__(scope, receive, send)
>   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 124, in __call__
>     await self.middleware_stack(scope, receive, send)
>   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
>     raise exc
>   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
>     await self.app(scope, receive, _send)
>   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 84, in __call__
>     await self.app(scope, receive, send)
>   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
>     raise exc
>   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
>     await self.app(scope, receive, sender)
>   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
>     raise e
>   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
>     await self.app(scope, receive, send)
>   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 706, in __call__
>     await route.handle(scope, receive, send)
>   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
>     await self.app(scope, receive, send)
>   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
>     response = await func(request)
>                ^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 235, in app
>     raw_response = await run_endpoint_function(
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
>     return await run_in_threadpool(dependant.call, **values)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
>     return await anyio.to_thread.run_sync(func, *args)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/anyio/to_thread.py", line 31, in run_sync
>     return await get_asynclib().run_sync_in_worker_thread(
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
>     return await future
>            ^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 867, in run
>     result = context.run(func, *args)
>              ^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/aktools/core/api.py", line 140, in root
>     received_df = eval("ak." + item_id + f"({eval_str})")
>                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "<string>", line 1, in <module>
>   File "/usr/local/lib/python3.11/site-packages/akshare/index/index_investing.py", line 162, in index_investing_global
>     name_code_dict = index_investing_global_area_index_name_code(area)
>                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/akshare/index/index_investing.py", line 89, in index_investing_global_area_index_name_code
>     name_url_dict = _get_global_country_name_url()
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/akshare/index/index_investing.py", line 68, in _get_global_country_name_url
>     ).find_all("option")[
>       ^^^^^^^^
> AttributeError: 'NoneType' object has no attribute 'find_all'
> ```
> 
> 期待回复，谢谢

英为财情的接口暂时不能使用
