### ISSUE TITLE
不知道是什么问题

### ISSUE THREAD

**Issue by ZL221B** [akfamily/akshare#3329]
root@localhost:~# python3 ./ak_Run.py
Traceback (most recent call last):
  File "/root/./ak_Run.py", line 11, in <module>
    import akshare as ak
  File "/usr/local/lib/python3.10/dist-packages/akshare/__init__.py", line 2852, in <module>
    from akshare.stock_feature.stock_ttm_lyr import stock_a_ttm_lyr
  File "/usr/local/lib/python3.10/dist-packages/akshare/stock_feature/stock_ttm_lyr.py", line 317, in <module>
    js_functions = py_mini_racer.MiniRacer()
  File "/usr/local/lib/python3.10/dist-packages/py_mini_racer/py_mini_racer.py", line 178, in __init__
    self.__class__.ext = _build_ext_handle()
  File "/usr/local/lib/python3.10/dist-packages/py_mini_racer/py_mini_racer.py", line 125, in _build_ext_handle
    raise RuntimeError("Native library not available at {}".format(EXTENSION_PATH))
RuntimeError: Native library not available at /usr/local/lib/python3.10/dist-packages/py_mini_racer/libmini_racer.glibc.so
Exception ignored in: <function MiniRacer.__del__ at 0x7d05710940>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/py_mini_racer/py_mini_racer.py", line 315, in __del__
    self.ext.mr_free_context(getattr(self, "ctx", None))
AttributeError: 'NoneType' object has no attribute 'mr_free_context'

**Comment by jindaxiang** [comment]
> root@localhost:~# python3 ./ak_Run.py Traceback (most recent call last): File "/root/./ak_Run.py", line 11, in import akshare as ak File "/usr/local/lib/python3.10/dist-packages/akshare/**init**.py", line 2852, in from akshare.stock_feature.stock_ttm_lyr import stock_a_ttm_lyr File "/usr/local/lib/python3.10/dist-packages/akshare/stock_feature/stock_ttm_lyr.py", line 317, in js_functions = py_mini_racer.MiniRacer() File "/usr/local/lib/python3.10/dist-packages/py_mini_racer/py_mini_racer.py", line 178, in **init** self.**class**.ext = _build_ext_handle() File "/usr/local/lib/python3.10/dist-packages/py_mini_racer/py_mini_racer.py", line 125, in _build_ext_handle raise RuntimeError("Native library not available at {}".format(EXTENSION_PATH)) RuntimeError: Native library not available at /usr/local/lib/python3.10/dist-packages/py_mini_racer/libmini_racer.glibc.so Exception ignored in: <function MiniRacer.**del** at 0x7d05710940> Traceback (most recent call last): File "/usr/local/lib/python3.10/dist-packages/py_mini_racer/py_mini_racer.py", line 315, in **del** self.ext.mr_free_context(getattr(self, "ctx", None)) AttributeError: 'NoneType' object has no attribute 'mr_free_context'

目前测试正常；请检查环境配置

**Comment by wushiwe-beep** [comment]
AKShare 目前已经默认适合苹果 M 系列芯片，先uninstall，再直接通过 pip install akshare --upgrade 即可使用。我就是这么解决的
