### ISSUE TITLE
获取北京证券交易所股票列表数据出错

### ISSUE THREAD

**Issue by haijiangxu** [akfamily/akshare#3330]
**Describe the bug**
调用stock_info_bj_name_code()函数获取北交所股票列表数据出错

**To Reproduce**
实际只有8个page,函数调用时有388个页面，返回的数据大多重复且无效

**Comment by jindaxiang** [comment]
> **Describe the bug** 调用stock_info_bj_name_code()函数获取北交所股票列表数据出错
> 
> **To Reproduce** 实际只有8个page,函数调用时有388个页面，返回的数据大多重复且无效

感谢反馈问题；已修复该问题，升级到 AKShare 1.8.44 版本使用
