### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by ChunxiaoYang** [akfamily/akshare#3346]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本：win11，2022-适用于 Windows 11 的 12 累积更新，适合基于 x64 的系统 (KB5021234)
2. Python 版本：3.8.5
3. AKShare 版本：1.7.79
4. 接口的名称和代码：主要都是英为财情的接口出错。第一个是获取美国所有指数名称的列表ak.index_investing_global_area_index_name_code('美国') 。第二个是获取美国的指数ak.index_investing_global(area='美国', symbol='VIX恐慌指数', period='每月', start_date='20050101', end_date='20200605')。第三个是用url获取美国标普500指数出错ak.index_investing_global_from_url(url="https://www.investing.com/indices/us-spx-500", period="每日", start_date="2004-12-31", end_date="2022-12-31")。
5. 接口报错的截图或代码
![image](https://user-images.githubusercontent.com/121948670/210561482-8d4b2623-aba4-4124-ad01-55ab3303a637.png)
![image](https://user-images.githubusercontent.com/121948670/210561698-9f5db3ce-e0d3-4aec-a2c5-a1e06345ddcd.png)

![image](https://user-images.githubusercontent.com/121948670/210561618-beed1b75-2f2d-4acc-9dc5-46e6aa4c1657.png)

6. 期望获得的正确结果：希望能够正常下载到美国的指数数据，比如标普500指数。谢谢！感谢akshare对我学习的帮助！！！

**Comment by ChunxiaoYang** [comment]
您好！我刚刚升级了akshare到1.8.48版本，仍然存在这个情况。谢谢！辛苦了！

**Comment by jindaxiang** [comment]
> 您好！我刚刚升级了akshare到1.8.48版本，仍然存在这个情况。谢谢！辛苦了！

英为财情的数据暂时不能获取，已经在接口文档增加说明
