### ISSUE TITLE
AKShare 接口问题报告 stock_individual_info_em只能获取上交所上市的股票代码信息

### ISSUE THREAD

**Issue by Palpitate-xus** [akfamily/akshare#3349]
![image](https://user-images.githubusercontent.com/54174343/210810227-eb6a1e45-85a4-4ba3-b605-927c73d0a108.png)
stock_individual_info_em接口只能获取上交所的信息，stock_individual_info_em_df = ak.stock_individual_info_em(symbol="399552")会报错。
可能的原因是目标地址: http://quote.eastmoney.com/concept/sh603777.html?from=classic里面的股票代码有sh标识

**Comment by Palpitate-xus** [comment]
![image](https://user-images.githubusercontent.com/54174343/210811633-d91d3283-9d6c-4cf0-b59b-7321c96b7dec.png)

**Comment by jindaxiang** [comment]
> ![image](https://user-images.githubusercontent.com/54174343/210810227-eb6a1e45-85a4-4ba3-b605-927c73d0a108.png) stock_individual_info_em接口只能获取上交所的信息，stock_individual_info_em_df = ak.stock_individual_info_em(symbol="399552")会报错。 可能的原因是目标地址: [http://quote.eastmoney.com/concept/sh603777.html?from=classic里面的股票代码有sh标识](http://quote.eastmoney.com/concept/sh603777.html?from=classic%E9%87%8C%E9%9D%A2%E7%9A%84%E8%82%A1%E7%A5%A8%E4%BB%A3%E7%A0%81%E6%9C%89sh%E6%A0%87%E8%AF%86)

目前只能获取个股的信息
