### ISSUE TITLE
stock_zh_a_hist_min_em 东财1min数据开盘价的值一直是0

### ISSUE THREAD

**Issue by QingPing1** [akfamily/akshare#3350]
stock_zh_a_hist_min_em_df = ak.stock_zh_a_hist_min_em(symbol="000001", start_date="2022-12-30 09:32:00", end_date="2022-01-06 15:30:00", period='1', adjust='hfq')  
东财  该语句1min历史数据中的开盘价 一直为 0，是什么原因，能修复吗？
展示的数据示例也都是为0的。
                                           时间       开盘     收盘  ...    成交量         成交额       最新价
0     2021-08-31 09:30:00   **0.00**  17.72  ...   5905  10463660.0  17.720
1     2021-08-31 09:31:00   **0.00**  17.65  ...  18454  32576004.0  17.669
2     2021-08-31 09:32:00   **0.00**  17.70  ...  14085  24864945.0  17.663
3     2021-08-31 09:33:00   **0.00**  17.68  ...  11138  19719604.0  17.673
4     2021-08-31 09:34:00   **0.00**  17.77  ...  14392  25513573.0  17.685

_Originally posted by @QingPing1 in https://github.com/akfamily/akshare/issues/2335#issuecomment-1373052931_

**Comment by jindaxiang** [comment]
> ```
>     stock_zh_a_hist_min_em_df = ak.stock_zh_a_hist_min_em(symbol="000001", start_date="2022-12-30 09:32:00", end_date="2022-01-06 15:30:00", period='1', adjust='hfq')  
> ```
> 
> 东财 该语句1min历史数据中的开盘价 一直为 0，是什么原因，能修复吗？ 展示的数据示例也都是为0的。 时间 开盘 收盘 ... 成交量 成交额 最新价 0 2021-08-31 09:30:00 **0.00** 17.72 ... 5905 10463660.0 17.720 1 2021-08-31 09:31:00 **0.00** 17.65 ... 18454 32576004.0 17.669 2 2021-08-31 09:32:00 **0.00** 17.70 ... 14085 24864945.0 17.663 3 2021-08-31 09:33:00 **0.00** 17.68 ... 11138 19719604.0 17.673 4 2021-08-31 09:34:00 **0.00** 17.77 ... 14392 25513573.0 17.685
> 
> _Originally posted by @QingPing1 in [#2335 (comment)](https://github.com/akfamily/akshare/issues/2335#issuecomment-1373052931)_

主要问题是数据源提供的数据为 0，已经在文档增加说明
