### ISSUE TITLE
fortune_rank() function does't work,please update.

### ISSUE THREAD

**Issue by tianhaisuifeng** [akfamily/akshare#3353]
**Describe the bug**
1、Missing data for 2021 and 2022
2、Can't work for 2010 and 2011

The version of akshare is 1.8.45

**Comment by jindaxiang** [comment]
> **Describe the bug** 1、Missing data for 2021 and 2022 2、Can't work for 2010 and 2011
> 
> The version of akshare is 1.8.45

Thanks for your issue, we have fixed the bug, you can update AKShare to 1.8.51
