### ISSUE TITLE
The stock_hot_rank_wc() only get first 100 data,please update.

### ISSUE THREAD

**Issue by tianhaisuifeng** [akfamily/akshare#3357]
**Describe the bug**
The stock_hot_rank_wc() only gets first 100 data,the reture data is restricted by the website. 

We can use a for loop to get all data,but there is also a restriction,about 260 times,it also fails.
After that,we can't get anything from the website,for the IP address is banned.

Suggestions:
1.Can your team provide an interface to get any data from wencai website,but not only '热门5000股票',because the parameter "question" can be anything.
2.The interface just returns the dataframe according to the "question",the user decides how to use it.
3.The parameter 'date' is not necessary because it can be included in parameter "question",for example,the "question" can be '20210430热门5000股票'.
4.So there is only one parameter in this interface,the "question".
5.The final result is,you ask a question,we provide all the data,you decide how to use it.

**Comment by jindaxiang** [comment]
> **Describe the bug** The stock_hot_rank_wc() only gets first 100 data,the reture data is restricted by the website.
> 
> We can use a for loop to get all data,but there is also a restriction,about 260 times,it also fails. After that,we can't get anything from the website,for the IP address is banned.
> 
> Suggestions: 1.Can your team provide an interface to get any data from wencai website,but not only '热门5000股票',because the parameter "question" can be anything. 2.The interface just returns the dataframe according to the "question",the user decides how to use it. 3.The parameter 'date' is not necessary because it can be included in parameter "question",for example,the "question" can be '20210430热门5000股票'. 4.So there is only one parameter in this interface,the "question". 5.The final result is,you ask a question,we provide all the data,you decide how to use it.

Thanks for your issue!
1. we have fixed the interface to return first 1000 stock, please update AKShare to 1.8.53!
2. we will plan to make a new interface to fit the wencai, please pay attention to the upgrade of AKShare!
