### ISSUE TITLE
index_value_hist_funddb可以增加indicator:风险溢价

### ISSUE THREAD

**Issue by laye0619** [akfamily/akshare#3359]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
指数估值-历史行情-韭圈儿的接口 index_value_hist_funddb可以增加indicator:风险溢价

**Describe alternatives you've considered**
韭圈儿接口已经支持，只需要在index_value_hist_funddb方法中->   indicator_map-> 加入 "风险溢价": 'fed', 即可

**Additional context**

**Comment by jindaxiang** [comment]
> **Is your feature request related to a problem? Please describe.** No
> 
> **Describe the solution you'd like** 指数估值-历史行情-韭圈儿的接口 index_value_hist_funddb可以增加indicator:风险溢价
> 
> **Describe alternatives you've considered** 韭圈儿接口已经支持，只需要在index_value_hist_funddb方法中-> indicator_map-> 加入 "风险溢价": 'fed', 即可
> 
> **Additional context** Add any other context or screenshots about the feature request here.

感谢反馈问题；已增加该参数，升级到 AKShare 1.8.52 版本使用
