### ISSUE TITLE
get_roll_yield_bar 的参数var="IM"时无输出

### ISSUE THREAD

**Issue by JaveCai** [akfamily/akshare#3364]
**描述遇到的问题**
1. 操作系统版本 WIN10
3. Python 版本 3.8.5
4. AKShare 版本 1.8.53
5. 接口的名称和代码 get_roll_yield_bar
6. 接口报错的截图或代码
* source
import akshare as ak
get_roll_yield_bar_df = ak.get_roll_yield_bar(type_method="date", var="IM", start_day="20221210", end_day="20230111")
print(get_roll_yield_bar_df)
* output
Empty DataFrame
Columns: []
Index: []

8. 期望获得的正确结果
同样的接口，把var赋值为"IC"，可以正常输出。期望var=“IM”也可以.
IM是22年新增的期指品种，是否接口还没提供支持？

**Comment by jindaxiang** [comment]
> **描述遇到的问题**
> 
> 1. 操作系统版本 WIN10
> 2. Python 版本 3.8.5
> 3. AKShare 版本 1.8.53
> 4. 接口的名称和代码 get_roll_yield_bar
> 5. 接口报错的截图或代码
> 
> * source
>   import akshare as ak
>   get_roll_yield_bar_df = ak.get_roll_yield_bar(type_method="date", var="IM", start_day="20221210", end_day="20230111")
>   print(get_roll_yield_bar_df)
> * output
>   Empty DataFrame
>   Columns: []
>   Index: []
> 
> 8. 期望获得的正确结果
>    同样的接口，把var赋值为"IC"，可以正常输出。期望var=“IM”也可以.
>    IM是22年新增的期指品种，是否接口还没提供支持？

感谢反馈问题；已修复该问题，升级 AKShare 到 1.8.54 版本使用
