### ISSUE TITLE
美国制造业pmi数据

### ISSUE THREAD

**Issue by MichoChan** [akfamily/akshare#3365]
好像没有美国制造业market pmi数据，这个可以从英为财情上爬取吗

**Comment by jindaxiang** [comment]
> 好像没有美国制造业market pmi数据，这个可以从英为财情上爬取吗

有 macro_usa_pmi 接口，升级到 AKShare 1.8.55 版本使用

**Comment by MichoChan** [comment]
> > 好像没有美国制造业market pmi数据，这个可以从英为财情上爬取吗
> 
> 有 macro_usa_pmi 接口，升级到 AKShare 1.8.55 版本使用

谢谢~
