### ISSUE TITLE
get_roll_yield_bar 结果有点奇怪，参数有优化空间

### ISSUE THREAD

**Issue by JaveCai** [akfamily/akshare#3369]
**描述遇到的问题**
1. 操作系统版本 WIN10
2. Python 版本 3.8.5
3. AKShare 版本 1.5.55
4. 接口的名称和代码 
    df = ak.get_roll_yield_bar(type_method="date",var="IM",start_day="20221201",end_day="20230112")
6. 接口报错的截图或代码
    * 问题点：结果中的标的存在突变，主力次主力的突变是否因为交易量的变化，如否，这是软件bug；如是，那么默认用主力和次主力并不合理，建议由用户指定。
   * 下面是输出结果：
![image](https://user-images.githubusercontent.com/16680048/212088838-467c7898-77f9-4e37-ab5c-6b96391892b3.png)
![image](https://user-images.githubusercontent.com/16680048/212090939-dd97bd37-14d6-4f50-8caf-0a9658259149.png)
（目前IM2301还是主力合约）

8. 期望获得的正确结果
   算是一个小建议：希望能指定全部的四个连续合约（当然能指定两个或者三个也很不错），比如指定IMM0,IMM1,IMS1,IMS2，则结果为3组展期收益，分别对应IMM1-IMM0,IMS1-IMM0,IMS2-IMM0.

**Comment by jindaxiang** [comment]
> **描述遇到的问题**
> 
> 1. 操作系统版本 WIN10
> 2. Python 版本 3.8.5
> 3. AKShare 版本 1.5.55
> 4. 接口的名称和代码
>    df = ak.get_roll_yield_bar(type_method="date",var="IM",start_day="20221201",end_day="20230112")
> 5. 接口报错的截图或代码
>    
>    * 问题点：结果中的标的存在突变，主力次主力的突变是否因为交易量的变化，如否，这是软件bug；如是，那么默认用主力和次主力并不合理，建议由用户指定。
>    * 下面是输出结果：
>      ![image](https://user-images.githubusercontent.com/16680048/212088838-467c7898-77f9-4e37-ab5c-6b96391892b3.png)
>      ![image](https://user-images.githubusercontent.com/16680048/212090939-dd97bd37-14d6-4f50-8caf-0a9658259149.png)
>      （目前IM2301还是主力合约）
> 6. 期望获得的正确结果
>    算是一个小建议：希望能指定全部的四个连续合约（当然能指定两个或者三个也很不错），比如指定IMM0,IMM1,IMS1,IMS2，则结果为3组展期收益，分别对应IMM1-IMM0,IMS1-IMM0,IMS2-IMM0.

这部分建议还是通过接口获取数据后在本地进行处理
