### ISSUE TITLE
stock_hk_valuation_baidu接口返回数据有误

### ISSUE THREAD

**Issue by inspirits** [akfamily/akshare#3371]
df = ak.stock_hk_valuation_baidu(symbol="00700", indicator="总市值")
以2023-01-13执行为例，返回数据缺失2023-01-04到2023-01-11这段时间的数据，但在网站上能查看到对应时间的数据。

**Comment by jindaxiang** [comment]
> 00700

感谢反馈问题；已修复该问题，在接口中新增 period 参数，通过 近一年 能获取到这段时间的数据；应该是数据源的问题；升级到 AKShare 1.8.56 版本使用
