### ISSUE TITLE
 AKShare 接口问题报告

### ISSUE THREAD

**Issue by 811458691** [akfamily/akshare#3372]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本  windows11
2. Python 版本    3.9
3. AKShare 版本  1.8.38
4. 接口的名称和代码   stock_zh_a_hist_163
<img width="611" alt="image" src="https://user-images.githubusercontent.com/122612813/212322302-01e67f19-fdf5-455b-9b01-888e38befc85.png">

5. 接口报错的截图或代码
<img width="486" alt="image" src="https://user-images.githubusercontent.com/122612813/212322349-bc5935bf-5c31-45a2-b908-55e350943bbb.png">

6. 期望获得的正确结果  接口之前一直使用正常，但今天早上突然开始报错，试了一下说明文档中的示例代码还是一样的情况，恳请早日修复

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本  windows11
> 2. Python 版本    3.9
> 3. AKShare 版本  1.8.38
> 4. 接口的名称和代码   stock_zh_a_hist_163
> 
> <img alt="image" width="611" src="https://user-images.githubusercontent.com/122612813/212322302-01e67f19-fdf5-455b-9b01-888e38befc85.png">
> 
> 5. 接口报错的截图或代码
> 
> <img alt="image" width="486" src="https://user-images.githubusercontent.com/122612813/212322349-bc5935bf-5c31-45a2-b908-55e350943bbb.png">
> 
> 6. 期望获得的正确结果  接口之前一直使用正常，但今天早上突然开始报错，试了一下说明文档中的示例代码还是一样的情况，恳请早日修复

数据源未提供数据，该接口即将移除

**Comment by lan-slot** [comment]
请问stock_zh_a_hist_163已经移除了吗？

**Comment by lan-slot** [comment]
@jindaxiang 请问stock_zh_a_hist_163接口已经移除了吗？

**Comment by log4jc** [comment]
@albertandking 请问stock_zh_a_hist_163接口已经被移除了么？我在版本更新里面没有看到相关描述，但是在Python中引用不到此接口
