### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by Douglasxin** [akfamily/akshare#3374]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本：win11
2. Python 版本：3.09
3. AKShare 版本：最新
4. 接口的名称和代码：ak.stock_szse_summary
5. 接口报错的截图或代码：
requests.exceptions.ConnectionError: HTTPConnectionPool(host='www.szse.cn', port=80): Max retries exceeded with url: /api/report/ShowReport?SHOWTYPE=xlsx&CATALOGID=1803_sczm&TABKEY=tab1&txtQueryDate=2023-01-13&random=0.39339437497296137 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002203B0135E0>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed'))

6. 期望获得的正确结果：返回数据

**Comment by jindaxiang** [comment]
> 4\. stock_szse_summary

接口可以正常使用；建议升级到最新版后重试
