### ISSUE TITLE
接口频繁访问的时间间隔

### ISSUE THREAD

**Issue by 811458691** [akfamily/akshare#3378]
看到新浪股票实时数据描述中写明重复运行函数会被新浪暂时封IP，而东财股票实时行情描述中没有，是否意味东财没有时间间隔？如果有，是否有具体的数值？

**Comment by jindaxiang** [comment]
> 看到新浪股票实时数据描述中写明重复运行函数会被新浪暂时封IP，而东财股票实时行情描述中没有，是否意味东财没有时间间隔？如果有，是否有具体的数值？

对，东财目前暂时还没有访问限制，建议适度访问
