### ISSUE TITLE
The hurun_rank() interface doesn't work for year 2018,please update.

### ISSUE THREAD

**Issue by tianhaisuifeng** [akfamily/akshare#3386]
**Describe the bug**
The hurun_rank() interface doesn't work for **year 2018**.

Here is the issue:
in <module>
    hurun_rank_df = hurun_rank(indicator="胡润百富榜", year="2018")
except requests.exceptions.JSONDecodeError as e:
AttributeError: module 'requests.exceptions' has no attribute 'JSONDecodeError'

Please run the file **fortune_hurun.py** to test the whole interface:
if __name__ == "__main__":
    hurun_rank_df = hurun_rank(indicator="胡润百富榜", year="2018")
    print(hurun_rank_df)

    hurun_rank_df = hurun_rank(indicator="胡润全球富豪榜", year="2022")
    print(hurun_rank_df)

    hurun_rank_df = hurun_rank(indicator="胡润印度榜", year="2021")
    print(hurun_rank_df)

    hurun_rank_df = hurun_rank(indicator="胡润全球独角兽榜", year="2021")
    print(hurun_rank_df)

    hurun_rank_df = hurun_rank(indicator="中国瞪羚企业榜", year="2021")
    print(hurun_rank_df)

    hurun_rank_df = hurun_rank(indicator="全球瞪羚企业榜", year="2021")
    print(hurun_rank_df)

    hurun_rank_df = hurun_rank(indicator="胡润Under30s创业领袖榜", year="2021")
    print(hurun_rank_df)

    hurun_rank_df = hurun_rank(indicator="胡润中国500强民营企业", year="2021")
    print(hurun_rank_df)

    hurun_rank_df = hurun_rank(indicator="胡润世界500强", year="2021")
    print(hurun_rank_df)

    hurun_rank_df = hurun_rank(indicator="胡润艺术榜", year="2021")
    print(hurun_rank_df)

**Comment by jindaxiang** [comment]
> **Describe the bug** The hurun_rank() interface doesn't work for **year 2018**.
> 
> Here is the issue: in hurun_rank_df = hurun_rank(indicator="胡润百富榜", year="2018") except requests.exceptions.JSONDecodeError as e: AttributeError: module 'requests.exceptions' has no attribute 'JSONDecodeError'
> 
> Please run the file **fortune_hurun.py** to test the whole interface: if **name** == "**main**": hurun_rank_df = hurun_rank(indicator="胡润百富榜", year="2018") print(hurun_rank_df)
> 
> ```
> hurun_rank_df = hurun_rank(indicator="胡润全球富豪榜", year="2022")
> print(hurun_rank_df)
> 
> hurun_rank_df = hurun_rank(indicator="胡润印度榜", year="2021")
> print(hurun_rank_df)
> 
> hurun_rank_df = hurun_rank(indicator="胡润全球独角兽榜", year="2021")
> print(hurun_rank_df)
> 
> hurun_rank_df = hurun_rank(indicator="中国瞪羚企业榜", year="2021")
> print(hurun_rank_df)
> 
> hurun_rank_df = hurun_rank(indicator="全球瞪羚企业榜", year="2021")
> print(hurun_rank_df)
> 
> hurun_rank_df = hurun_rank(indicator="胡润Under30s创业领袖榜", year="2021")
> print(hurun_rank_df)
> 
> hurun_rank_df = hurun_rank(indicator="胡润中国500强民营企业", year="2021")
> print(hurun_rank_df)
> 
> hurun_rank_df = hurun_rank(indicator="胡润世界500强", year="2021")
> print(hurun_rank_df)
> 
> hurun_rank_df = hurun_rank(indicator="胡润艺术榜", year="2021")
> print(hurun_rank_df)
> ```

可以正常获取；
![image](https://user-images.githubusercontent.com/18234520/212842919-46973ced-5e2a-4c79-9727-4b4ee2666f76.png)
