### ISSUE TITLE
stock_zh_a_tick_163 接口返回错误

### ISSUE THREAD

**Issue by sjtuxiaoming** [akfamily/akshare#3389]
**Describe the bug**

MacOS  运行：
import akshare as ak
stock_zh_a_tick_163_df = ak.stock_zh_a_tick_163(symbol="sh600848", trade_date="20230116")

报错如下：
ValueError: Excel file format cannot be determined, you must specify an engine manually.

**Screenshots**
![image](https://user-images.githubusercontent.com/17291290/212879151-fe124778-b070-44e4-8a09-58be82ea59d5.png)

上周运行还是OK的，本周开始出现问题~~

**Comment by sjtuxiaoming** [comment]
更新到最新的akshare后，报错有变化：xlrd.biffh.XLRDError: Unsupported format, or corrupt file: Expected BOF record; found b'<!DOCTYP'
![image](https://user-images.githubusercontent.com/17291290/212886167-a9174c8b-c37a-40cd-8e7f-d2a307dec082.png)

**Comment by jindaxiang** [comment]
> **Describe the bug**
> 
> MacOS 运行： import akshare as ak stock_zh_a_tick_163_df = ak.stock_zh_a_tick_163(symbol="sh600848", trade_date="20230116")
> 
> 报错如下： ValueError: Excel file format cannot be determined, you must specify an engine manually.
> 
> **Screenshots** ![image](https://user-images.githubusercontent.com/17291290/212879151-fe124778-b070-44e4-8a09-58be82ea59d5.png)
> 
> 上周运行还是OK的，本周开始出现问题~~

感谢反馈问题；该接口由于数据源未提供数据，接口即将移除，已经在文档增加说明
