### ISSUE TITLE
A 股股票代码和简称接口与 深证+上证 + 北证 总和不一致

### ISSUE THREAD

**Issue by eromoe** [akfamily/akshare#3392]
Hi,

我希望实现
1. 获取所有A股在交易的股票
2. 然后获取所有日级别的数据

目前在步骤1上出现问题， 下列接口获取的到内容是没有前缀 sh,sz的
>  "stock_info_a_code_name"  # A 股股票代码和简称

导致无法使用 `ak.stock_zh_a_daily` 下载日级别数据

所以我使用下面3个接口，获取symbol 后，手动添加前缀

>  "stock_info_sz_name_code"  # 深证证券交易所股票代码和简称
>  "stock_info_sh_name_code"  # 上海证券交易所股票代码和简称
>  "stock_info_bj_name_code"  # 北京证券交易所股票代码和简称

结果发现总数只有 4570，`stock_info_a_code_name` 总数不一致

所以想请教正确的实现步骤是什么

**Comment by crazydragon8888** [comment]
我就不信你能做所有股票？

**Comment by jindaxiang** [comment]
> `stock_info_a_code_name`

stock_info_sh_name_code 还需要增加科创板的数据
