### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by zsrl** [akfamily/akshare#3399]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本 win11
3. Python 版本 3.8
4. AKShare 版本 1.8.62(lastest)
5. 接口的名称和代码
```python
import akshare as ak

a = ak.stock_cash_flow_sheet_by_report_em(symbol='SH601398')
```
7. 接口报错的截图或代码
![image](https://user-images.githubusercontent.com/4284926/214809618-e4445595-f95d-4887-9662-3afbf9806a4a.png)

9. 期望获得的正确结果 查询SH601398不报错，正确返回

**初步排查原因**

601398 与 官方文档示例600519 在东财那边发送的参数不一样。

![image](https://user-images.githubusercontent.com/4284926/214810324-dfaae043-89a0-426b-89ff-a79f3d11363b.png)
![image](https://user-images.githubusercontent.com/4284926/214810470-6a05abd2-e435-4fe0-9eed-bf2611286750.png)

akshare源码里写死的是4

![image](https://user-images.githubusercontent.com/4284926/214810697-ff28a7db-c1e7-4a6d-b78c-b05cd3db90d8.png)

companyType具体如何区分，我目前还不太清楚

**Comment by zsrl** [comment]
猜测companyType表示公司类型，601398是工商银行，银行的财务报表字段与普通股票不同。

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本 win11
> 2. Python 版本 3.8
> 3. AKShare 版本 1.8.62(lastest)
> 4. 接口的名称和代码
> 
> ```python
> import akshare as ak
> 
> a = ak.stock_cash_flow_sheet_by_report_em(symbol='SH601398')
> ```
> 
> 7. 接口报错的截图或代码
>    ![image](https://user-images.githubusercontent.com/4284926/214809618-e4445595-f95d-4887-9662-3afbf9806a4a.png)
> 8. 期望获得的正确结果 查询SH601398不报错，正确返回
> 
> **初步排查原因**
> 
> 601398 与 官方文档示例600519 在东财那边发送的参数不一样。
> 
> ![image](https://user-images.githubusercontent.com/4284926/214810324-dfaae043-89a0-426b-89ff-a79f3d11363b.png) ![image](https://user-images.githubusercontent.com/4284926/214810470-6a05abd2-e435-4fe0-9eed-bf2611286750.png)
> 
> akshare源码里写死的是4
> 
> ![image](https://user-images.githubusercontent.com/4284926/214810697-ff28a7db-c1e7-4a6d-b78c-b05cd3db90d8.png)
> 
> companyType具体如何区分，我目前还不太清楚

是公司类型判断的问题，感谢反馈问题；已修复该问题，升级到 AKShare 1.8.63 版本使用；
