### ISSUE TITLE
get_roll_yield_bar接口问题报告

### ISSUE THREAD

**Issue by yinlinzhan** [akfamily/akshare#3403]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本：windows
2. Python 版本：3.9
3. AKShare 版本：1.8.62
4. 接口的名称和代码:get_roll_yield_bar
5. 接口报错的截图或代码:
在如下参数下ak.get_roll_yield_bar(type_method="var", date=date)现在会获取‘MO’和'HO‘两个期权的展期收益率，需要将futures_roll_yield.py文件中的get_roll_yield_bar函数下面这两行代码
if "IO" in var_list:
        var_list.remove("IO")  # IO 为期权
修改为：
for i_remove in ['IO', 'MO', 'HO']:
            if i_remove in var_list:
                var_list.remove(i_remove)  # IO 为期权
如果从长远考虑，希望能加入自动删除期权种类的代码，而不是每次上海金融期货交易所上市新期权都需要手动加入要删除的新品种。
7. 期望获得的正确结果
get_roll_yield_bar接口是获取期货展期收益率的，需要将期权剔除掉。

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本：windows
> 2. Python 版本：3.9
> 3. AKShare 版本：1.8.62
> 4. 接口的名称和代码:get_roll_yield_bar
> 5. 接口报错的截图或代码:
>    在如下参数下ak.get_roll_yield_bar(type_method="var", date=date)现在会获取‘MO’和'HO‘两个期权的展期收益率，需要将futures_roll_yield.py文件中的get_roll_yield_bar函数下面这两行代码
>    if "IO" in var_list:
>    var_list.remove("IO")  # IO 为期权
>    修改为：
>    for i_remove in ['IO', 'MO', 'HO']:
>    if i_remove in var_list:
>    var_list.remove(i_remove)  # IO 为期权
>    如果从长远考虑，希望能加入自动删除期权种类的代码，而不是每次上海金融期货交易所上市新期权都需要手动加入要删除的新品种。
> 6. 期望获得的正确结果
>    get_roll_yield_bar接口是获取期货展期收益率的，需要将期权剔除掉。

感谢反馈问题及修复方案，已修复该问题，升级到 AKShare 1.8.65 版本使用；目前来看上市品种较少，以手动更新为主，近期会重构这部分接口

**Comment by yinlinzhan** [comment]
好滴，辛苦前辈啦
