### ISSUE TITLE
建议stock_zh_a_hist接口返回的数据带交易所代码

### ISSUE THREAD

**Issue by alaxcc** [akfamily/akshare#3406]
现在返回的只是股票代码，建议stock_zh_a_hist接口返回的数据带交易所代码，比如SZ，SH等，还有属于主板还是创业版等。这个数据从你的文档里没找到哪个api可以查到。

感谢！

**Comment by jindaxiang** [comment]
> 现在返回的只是股票代码，建议stock_zh_a_hist接口返回的数据带交易所代码，比如SZ，SH等，还有属于主板还是创业版等。这个数据从你的文档里没找到哪个api可以查到。
> 
> 感谢！

目前接口设计原则是跟数据源统一；关于您说的问题，可以配置 AKShare 中相关接口 stock_info_sz_name_code 等完成
