### ISSUE TITLE
外汇数据相关的2个接口报错

### ISSUE THREAD

**Issue by Silver-L** [akfamily/akshare#3407]
以下2个外汇相关的接口报错：
1. ak.currency_hist
2. ak.currency_pair_map

<img width="1217" alt="image" src="https://user-images.githubusercontent.com/38281885/215256163-2b9b108c-3cc6-479d-a557-2d0b013ac41a.png">

**Comment by jindaxiang** [comment]
> 2\. currency_pair_map

英为财情的接口暂不能获取数据；已在文档增加说明
