### ISSUE TITLE
AKShare 接口问题报告（stock_profit_sheet_by_report_em）

### ISSUE THREAD

**Issue by zsrl** [akfamily/akshare#3408]
接续问题#3399，之前的问题的确得到了解决，目前 `stock_cash_flow_sheet_by_report_em(symbol='601398')` 和 `stock_balance_sheet_by_report_em(symbol='601398')`可正常返回，但获取利润表数据报错：

```python
import akshare as ak

ak.stock_profit_sheet_by_report_em(symbol='601398')
```
报错

![image](https://user-images.githubusercontent.com/4284926/215269569-ac47c8f1-20ca-43b5-be94-4aeb18ff3674.png)

还劳烦再帮忙排查，感谢

**Comment by jindaxiang** [comment]
> 601398

接口正常，请按文档使用
