### ISSUE TITLE
AKShare 接口问题报告 stock_zygc_ym，针对极个别标的（1个）输入，返回空表，原因是源网页数据源表格不存在。

### ISSUE THREAD

**Issue by tyePhDCandy** [akfamily/akshare#3413]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本 : windows 10
2. Python 版本 :  3.9.7
3. AKShare 版本: 1.8.65
4. 接口的名称和代码:
stock_zygc_ym
```python
import akshare as ak

stock_zygc_ym_df = ak.stock_zygc_ym(symbol="688041")
print(stock_zygc_ym_df)
```

5. 接口报错的截图或代码
AKShare 接口问题报告 stock_zygc_ym，针对个别标的输入，返回空表，原因是[源网页](http://f10.emoney.cn/f10/zbyz/688041)数据源表格不存在。目前，只发现688041 这一个标的，存在这种情况。代码如下。
```python
from IPython.display import display
import akshare as ak
stock_zygc_ym_df = ak.stock_zygc_ym(symbol="688041")
display(stock_zygc_ym_df.head(5))
```
截图如下

![image](https://user-images.githubusercontent.com/22343659/215305696-1e3fc7eb-cd77-45a8-9ad3-e98e0ca908af.png)

**建议：** 更换源网页为东方财富，可解决个别标的对应的现有网页源数据为空表的问题，而且数据源更加稳定可靠。

6. 期望获得的正确结果
更换源网页为东方财富，可解决个别标的对应的现有网页源数据为空表的问题，而且数据源更加稳定可靠。唯一麻烦的地方是，需要判断标的属于上海或者深圳交易所。
东方财富数据源网页链接：
http://emweb.securities.eastmoney.com/PC_HSF10/BusinessAnalysis/Index?type=web&code=sh688041#zygcfx-0

我查看了一下html element，其表格结构并不复杂，修改工作量应不大。谢谢。

**Comment by jindaxiang** [comment]
> 5\. stock_zygc_ym

感谢反馈问题；已新增 stock_zygc_em 接口，升级到 AKShare 1.8.71 版本使用
