### ISSUE TITLE
股票数据中“破净股统计“接口无法使用

### ISSUE THREAD

**Issue by RongchengZhang** [akfamily/akshare#3416]
您好，我在使用过程中，遇到“破净股统计”接口的示例无法使用。
接口名称：stock_a_below_net_asset_statistics
代码：
import akshare as ak
stock_a_below_net_asset_statistics_df = ak.stock_a_below_net_asset_statistics(symbol="全部A股")
print(stock_a_below_net_asset_statistics_df)

报错信息：
![image](https://user-images.githubusercontent.com/123867600/215319897-40190e2f-b179-41f5-813b-7c782723d33c.png)

可能的原因：
我想可能是数据源格式发生了改变。

**Comment by jindaxiang** [comment]
> 您好，我在使用过程中，遇到“破净股统计”接口的示例无法使用。 接口名称：stock_a_below_net_asset_statistics 代码： import akshare as ak stock_a_below_net_asset_statistics_df = ak.stock_a_below_net_asset_statistics(symbol="全部A股") print(stock_a_below_net_asset_statistics_df)
> 
> 报错信息： ![image](https://user-images.githubusercontent.com/123867600/215319897-40190e2f-b179-41f5-813b-7c782723d33c.png)
> 
> 可能的原因： 我想可能是数据源格式发生了改变。

接口可以正常使用；建议升级到最新版
