### ISSUE TITLE
stock_ebs_lg报错，无此接口

### ISSUE THREAD

**Issue by OatLatte** [akfamily/akshare#3417]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本 2. Python 版本 3. AKShare 版本
最新

4. 接口的名称和代码
 **stock_ebs_lg** 
AttributeError: module 'akshare' has no attribute 'stock_ebs_lg'

**Comment by jindaxiang** [comment]
> 2\. stock_ebs_lg

接口正常，升级到最新版使用
