### ISSUE TITLE
stock_a_pe 和 stock_a_pe_and_pb 接口问题

### ISSUE THREAD

**Issue by OatLatte** [akfamily/akshare#3418]
**描述遇到的问题**
python和 akshare 均为最新版,操作系统苹果 windows 都试过

1.
ak.stock_a_pe_and_pb所有指数目前只能返回 2018 年以后数据, 但是查看数据源 legulegu.com 是有更早数据的.
例如ak.stock_a_pe_and_pb(symbol='000300.SH'),只能返回沪深 300 指数2018 年 1 月30 日以后的数据, 但是查看数据源https://legulegu.com/stockdata/hs300-ttm-lyr, 数据应该从 2005 年 4 月 8 日开始

2.
ak.stock_a_pe 返回的指数缺少一条最新日期. 例如最近的交易如距离今天是 2023 年 1 月 20 日, 但数据只能返回至 2023 年 1 月 19 日. 同样, 查看数据源 legulegu.com是有 1 月 20 日数据的, 但接口没有返回该数据.

3.另外发现一个 akshare 文档的 typo
文档内容
ak.stock_a_lg_indicator(stock="all") 获取股票代码
实际应该是 symbol="all" 用 stock 会报错

期望结果:
ak.stock_a_pe_and_pb 接口可以返回 2018 年以前数据

谢谢!

**Comment by jindaxiang** [comment]
> **描述遇到的问题** python和 akshare 均为最新版,操作系统苹果 windows 都试过
> 
> 
> ak.stock_a_pe_and_pb所有指数目前只能返回 2018 年以后数据, 但是查看数据源 legulegu.com 是有更早数据的. 例如ak.stock_a_pe_and_pb(symbol='000300.SH'),只能返回沪深 300 指数2018 年 1 月30 日以后的数据, 但是查看数据源https://legulegu.com/stockdata/hs300-ttm-lyr, 数据应该从 2005 年 4 月 8 日开始
> 
> 
> ak.stock_a_pe 返回的指数缺少一条最新日期. 例如最近的交易如距离今天是 2023 年 1 月 20 日, 但数据只能返回至 2023 年 1 月 19 日. 同样, 查看数据源 legulegu.com是有 1 月 20 日数据的, 但接口没有返回该数据.
> 
> 3.另外发现一个 akshare 文档的 typo 文档内容 ak.stock_a_lg_indicator(stock="all") 获取股票代码 实际应该是 symbol="all" 用 stock 会报错
> 
> 期望结果: ak.stock_a_pe_and_pb 接口可以返回 2018 年以前数据
> 
> 谢谢!

感谢反馈问题；
问题1和2，已新增 stock_market_pe_lg 等函数，详情查看文档，升级到 AKShare 1.8.71 版本使用；
问题3已经在文档修复
