### ISSUE TITLE
stock_lhb_ggtj_sina 函数的问题以及改进建议

### ISSUE THREAD

**Issue by skyformat99** [akfamily/akshare#3421]
最近，通过这个函数stock_lhb_ggtj_sina获取龙虎榜5天的龙虎榜数据，是空白的；
原因是sina的这个是空白的；

另外一个获取函数是：
stock_lhb_stock_statistic_em
这个函数是通过东财获取的，比较稳定；https://data.eastmoney.com/stock/tradedetail.html
函数stock_lhb_stock_statistic_em获取的是网页上的，那么
能不能进一步，通过stock_lhb_stock_statistic_em函数获取的数据，合并同一个股票的数据，形成类似 前面sina的那个统计数据
比如3天，或者5天之内的  净额相加的数据

**Comment by jindaxiang** [comment]
> 最近，通过这个函数stock_lhb_ggtj_sina获取龙虎榜5天的龙虎榜数据，是空白的； 原因是sina的这个是空白的；
> 
> 另外一个获取函数是： stock_lhb_stock_statistic_em 这个函数是通过东财获取的，比较稳定；https://data.eastmoney.com/stock/tradedetail.html 函数stock_lhb_stock_statistic_em获取的是网页上的，那么 能不能进一步，通过stock_lhb_stock_statistic_em函数获取的数据，合并同一个股票的数据，形成类似 前面sina的那个统计数据 比如3天，或者5天之内的 净额相加的数据

目前接口设计的原则是保持跟数据源的统一；您说的需求建议在获取到数据后在本地合并操作
