### ISSUE TITLE
求：同花顺主营介绍 http://basic.10jqka.com.cn/new/002847/operate.html -> 爬虫

### ISSUE THREAD

**Issue by tyePhDCandy** [akfamily/akshare#3427]
# 同花顺主营介绍 http://basic.10jqka.com.cn/new/002847/operate.html -> 爬虫
建议名称：主营介绍-同花顺
网页链接：  http://basic.10jqka.com.cn/new/002847/operate.html
网页中目标信息截图。
![image](https://user-images.githubusercontent.com/22343659/215679726-6a147ced-bddd-4f29-86fc-c184045f42bc.png)

# 建议：以后如果有需要爬取的信息，可优先考虑同花顺网页
http://basic.10jqka.com.cn/new/002847/operate.html

**Comment by jindaxiang** [comment]
> # 同花顺主营介绍 http://basic.10jqka.com.cn/new/002847/operate.html -> 爬虫
> 建议名称：主营介绍-同花顺 网页链接： http://basic.10jqka.com.cn/new/002847/operate.html 网页中目标信息截图。 ![image](https://user-images.githubusercontent.com/22343659/215679726-6a147ced-bddd-4f29-86fc-c184045f42bc.png)
> 
> # 建议：以后如果有需要爬取的信息，可优先考虑同花顺网页
> http://basic.10jqka.com.cn/new/002847/operate.html

感谢提供建议；已新增 stock_zyjs_ths 接口，升级到 AKShare 1.8.73 版本使用
