### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by maggie-chen** [akfamily/akshare#3429]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本
   MacBook Pro (15-inch, 2019)
2. Python 版本
    Python 3.10.8
3. AKShare 版本 
    1.8.72
4. 接口的名称和代码
```
import akshare as ak

stock_hk_spot_em = ak.stock_hk_spot_em()

codes = []
for i in range(len(stock_hk_spot_em)):
    if stock_hk_spot_em["最新价"][i] > 0.2 and stock_hk_spot_em["成交量"][i] > 100 * 10000 and stock_hk_spot_em["涨跌幅"][i] > 0.02:
        codes.append(stock_hk_spot_em["代码"][i])
print('共有' + str(len(codes)) + '个股票符合')
print(codes)

result = []
for code in codes:
    print(code)
    stock_hk_hist_df = ak.stock_hk_hist(symbol=code, period="daily", start_date="20230131", end_date="20230201",
                                        adjust="")
    yesterday = stock_hk_hist_df["成交量"][0]
    today = stock_hk_hist_df["成交量"][1]
    if yesterday > 10 * 10000 and today/yesterday > 3:
        result.append(code)
print('共有' + str(len(result)) + '个股票符合')
print(result)
```
5. 接口报错的截图或代码
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 2699 (char 2698)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Maggie/Desktop/项目/stock/python/h.py", line 19, in <module>
    stock_hk_hist_df = ak.stock_hk_hist(symbol=code, period="daily", start_date="20230131", end_date="20230201",
  File "/usr/local/lib/python3.10/site-packages/akshare/stock_feature/stock_hist_em.py", line 1269, in stock_hk_hist
    data_json = r.json()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
```
6. 期望获得的正确结果
 期望能返回所有符合的代码

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本
>    MacBook Pro (15-inch, 2019)
> 2. Python 版本
>    Python 3.10.8
> 3. AKShare 版本
>    1.8.72
> 4. 接口的名称和代码
> 
> ```
> import akshare as ak
> 
> stock_hk_spot_em = ak.stock_hk_spot_em()
> 
> codes = []
> for i in range(len(stock_hk_spot_em)):
>     if stock_hk_spot_em["最新价"][i] > 0.2 and stock_hk_spot_em["成交量"][i] > 100 * 10000 and stock_hk_spot_em["涨跌幅"][i] > 0.02:
>         codes.append(stock_hk_spot_em["代码"][i])
> print('共有' + str(len(codes)) + '个股票符合')
> print(codes)
> 
> result = []
> for code in codes:
>     print(code)
>     stock_hk_hist_df = ak.stock_hk_hist(symbol=code, period="daily", start_date="20230131", end_date="20230201",
>                                         adjust="")
>     yesterday = stock_hk_hist_df["成交量"][0]
>     today = stock_hk_hist_df["成交量"][1]
>     if yesterday > 10 * 10000 and today/yesterday > 3:
>         result.append(code)
> print('共有' + str(len(result)) + '个股票符合')
> print(result)
> ```
> 
> 5. 接口报错的截图或代码
> 
> ```
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 971, in json
>     return complexjson.loads(self.text, **kwargs)
>   File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 346, in loads
>     return _default_decoder.decode(s)
>   File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 353, in raw_decode
>     obj, end = self.scan_once(s, idx)
> json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 2699 (char 2698)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/Maggie/Desktop/项目/stock/python/h.py", line 19, in <module>
>     stock_hk_hist_df = ak.stock_hk_hist(symbol=code, period="daily", start_date="20230131", end_date="20230201",
>   File "/usr/local/lib/python3.10/site-packages/akshare/stock_feature/stock_hist_em.py", line 1269, in stock_hk_hist
>     data_json = r.json()
>   File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 975, in json
>     raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
> ```
> 
> 6. 期望获得的正确结果
>    期望能返回所有符合的代码

接口可以正常使用；请在本地调试代码
