### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by yonghengzhilei** [akfamily/akshare#3439]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本：win10
2. Python 版本 : 3.8.6
3. AKShare 版本 : 1.8.75
4. 接口的名称和代码 : 分析师详情
  stock_analyst_detail_em_df = ak.stock_analyst_detail_em(analyst_id="11000257131", indicator="最新跟踪成分股")
6. 接口问题描述
  东方财富网-数据中心-研究报告-东方财富分析师指数-分析师详情（接口已经跟新）
  之前接口获取的不是最新数据。

**Comment by jindaxiang** [comment]
> 4\. 11000257131

感谢反馈问题；已修复该问题，升级到 AKShare 1.8.77 版本使用
