### ISSUE TITLE
sina_ws 接口问题报告

### ISSUE THREAD

**Issue by manyhelp** [akfamily/akshare#3440]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本  win10
2. Python 版本   3.8
3. AKShare 版本  master 
4. 接口的名称和代码  sina_ws.py
5. 接口报错的截图或代码
    Handshake status 403 Forbidden
7. 期望获得的正确结果
    需要过验证

**Comment by jindaxiang** [comment]
> 

已经移除相关 ws 接口
