### ISSUE TITLE
无法获取港股相关指数的历史数据！

### ISSUE THREAD

**Issue by J-Z-Z** [akfamily/akshare#3441]
在获取股港股相关指数数据的时候， 程序报错。 

例如获取恒生指数，恒生科技指数， 使用stock_zh_index_hist_csindex接口获取时出现异常。

看了一下代码，应该是这个接口没有提供港股相关的内容。

**Comment by jindaxiang** [comment]
> stock_zh_index_hist_csindex

是的

**Comment by J-Z-Z** [comment]
能否定制一下？
