### ISSUE TITLE
提个不成熟的建议stock_a_pe_and_pb是否可以支持指数代号传入呢

### ISSUE THREAD

**Issue by seawayfisher** [akfamily/akshare#3445]
不得不说akshare真的很好用。十分感谢作者大佬。
在使用的过程中，发现stock_a_pe_and_pb并不支持传入指数代码进行调用。

起因：我想查询更多指数
现状：发现stock_index_pe_lg支持的参数列表是写死的
    symbol_map = {
        "上证50": "000016.SH",
        "沪深300": "000300.SH",
        "上证380": "000009.SH",
        "创业板50": "399673.SZ",
        "中证500": "000905.SH",
        "上证180": "000010.SH",
        "深证红利": "399324.SZ",
        "深证100": "399330.SZ",
        "中证1000": "000852.SH",
        "上证红利": "000015.SH",
        "中证100": "000903.SH",
        "中证800": "000906.SH",
    }

我的不成熟意见是：是否可以支持直接通过传入代码进行查询呢？ 比如像这样的参数："000016.SH"。
当然不接受我的意见也没问题，我本地学习akshare的时候，也可以手动改掉这些接口以达到我想查询任意指数的目的

**Comment by jindaxiang** [comment]
> 000016.SH

感谢支持和 idea，目前数据源只提供固定种类的指数数据，保证接口稳定性，暂不考虑任意输入获取
