### ISSUE TITLE
The interface stock_profit_forecast() doesn't work,please update.

### ISSUE THREAD

**Issue by tianhaisuifeng** [akfamily/akshare#3447]
**Describe the bug**
The interface stock_profit_forecast() doesn't work.
Here is the bug:
big_df[f"{year2}预测每股收益"] = pd.to_numeric(big_df[f"{year2}预测每股收益"])
in to_numeric
    raise TypeError("arg must be a list, tuple, 1-d array, or Series")
TypeError: arg must be a list, tuple, 1-d array, or Series

another issue:
ak.stock_profit_forecast() returns many duplicated data,there are about 2731 records,and 782 are duplicated records,you can test it by print **stock_profit_forecast()["名称"].to_list()**

This issue can be fixed by removing these two parameters:
params = {
        'reportName': 'RPT_WEB_RESPREDICT',
        'columns': 'WEB_RESPREDICT',
        'pageNumber': '1',
        'pageSize': '500',
        **# 'sortTypes': '-1',
        # 'sortColumns': 'RATING_ORG_NUM',**
        'p': '1',
        'pageNo': '1',
        'pageNum': '1',
        'filter': '',
        '_': '1640241417037',
    }

**Comment by jindaxiang** [comment]
> **Describe the bug** The interface stock_profit_forecast() doesn't work. Here is the bug: big_df[f"{year2}预测每股收益"] = pd.to_numeric(big_df[f"{year2}预测每股收益"]) in to_numeric raise TypeError("arg must be a list, tuple, 1-d array, or Series") TypeError: arg must be a list, tuple, 1-d array, or Series
> 
> another issue: ak.stock_profit_forecast() returns many duplicated data,there are about 2731 records,and 782 are duplicated records,you can test it by print **stock_profit_forecast()["名称"].to_list()**
> 
> This issue can be fixed by removing these two parameters: params = { 'reportName': 'RPT_WEB_RESPREDICT', 'columns': 'WEB_RESPREDICT', 'pageNumber': '1', 'pageSize': '500', **# 'sortTypes': '-1', # 'sortColumns': 'RATING_ORG_NUM',** 'p': '1', 'pageNo': '1', 'pageNum': '1', 'filter': '', '_': '1640241417037', }

感谢反馈问题；已修复该问题，升级到 AKShare 1.8.78 版本使用
