### ISSUE TITLE
The interface stock_profit_forecast() still doesn't work,please update. 

### ISSUE THREAD

**Issue by tianhaisuifeng** [akfamily/akshare#3449]
**Describe the bug**
As I reported in [,this](https://github.com/akfamily/akshare/issues/3447) bug still exists in version AKShare 1.8.78.
When sortTypes and sortColumns are set,the return data is duplicated,the result is _so many companies are missing_.

another issue:
ak.stock_profit_forecast() returns many duplicated data,there are about 2731 records,and 782 are duplicated records,you can test it by print stock_profit_forecast()["名称"].to_list()

This issue can be fixed by **removing these two parameters**:
params = {
'reportName': 'RPT_WEB_RESPREDICT',
'columns': 'WEB_RESPREDICT',
'pageNumber': '1',
'pageSize': '500',
# 'sortTypes': '-1',
# 'sortColumns': 'RATING_ORG_NUM',
'p': '1',
'pageNo': '1',
'pageNum': '1',
'filter': '',
'_': '1640241417037',
}

**Comment by jindaxiang** [comment]
> stock_profit_forecast

接口设计原则是与数据源网站统一；建议在获取数据到本地后进行去重处理

**Comment by tianhaisuifeng** [comment]
This is a bug and has nothing to do with design  principles. @jindaxiang 
**From the website,we can see 2731 different companies**,ak.stock_profit_forecast() returns 2731 companies,but about 782 are duplicated records,that's to say about 782 company data are missing.**We can get only 1949 company data with stock_profit_forecast()**.
For example,the company '天海防务' are in website:
![image](https://user-images.githubusercontent.com/48590872/218048854-e60ac3b7-4bf8-4af3-8e82-b44e4e3dbc0e.png)
But we can't get the data from stock_profit_forecast(),it is missing.
Am I clear?

**Comment by jindaxiang** [comment]
> This is a bug and has nothing to do with design principles. @jindaxiang **From the website,we can see 2731 different companies**,ak.stock_profit_forecast() returns 2731 companies,but about 782 are duplicated records,that's to say about 782 company data are missing.**We can get only 1949 company data with stock_profit_forecast()**. For example,the company '天海防务' are in website: ![image](https://user-images.githubusercontent.com/48590872/218048854-e60ac3b7-4bf8-4af3-8e82-b44e4e3dbc0e.png) But we can't get the data from stock_profit_forecast(),it is missing. Am I clear?

已修复该问题；具体问题为东财网页端的数据返回就有重复值，目前已经按你描述的方法剔除相关请求参数，并新增 symbol 接口参数，升级到 AKShare 1.8.80 版本使用

**Comment by tianhaisuifeng** [comment]
Thank you for your hard work! @jindaxiang
