### ISSUE TITLE
AKShare bond_zh_hs_cov_spot接口返回decode错误信息

### ISSUE THREAD

**Issue by Doebe** [akfamily/akshare#3457]
**描述遇到的问题**
1. 操作系统版本：Linux version 3.10.0-1160.71.1.el7.x86_64
2. Python 版本：3.8
3. AKShare 版本：akshare-1.8.78
4. 接口的名称和代码：bond_zh_hs_cov_spot
5. 接口报错的截图或代码：Can not decode value starting with character '<'
6. 期望获得的正确结果：正常返回df

bond_zh_hs_cov_spot接口时而出现错误信息：Can not decode value starting with character '<'

**Comment by jindaxiang** [comment]
> 4\. bond_zh_hs_cov_spot

接口可以正常使用，注意控制使用频率

**Comment by Doebe** [comment]
这个接口问题不是必现，一些情况下能正常获取数据，一些情况下返回报错信息：Can not decode value starting with character '<'。
猜测可能跟数据源网站更新时，一些数值带有上下箭头有关？交易时间内调用应该能复现问题。

**Comment by Doebe** [comment]
> > 4. bond_zh_hs_cov_spot
> 
> 接口可以正常使用，注意控制使用频率

这个接口问题不是必现，一些情况下能正常获取数据，一些情况下返回报错信息：Can not decode value starting with character '<'。
猜测可能跟数据源网站更新时，一些数值带有上下箭头有关？交易时间内调用应该能复现问题。

**Comment by jindaxiang** [comment]
> > > 4. bond_zh_hs_cov_spot
> > 
> > 
> > 接口可以正常使用，注意控制使用频率
> 
> 这个接口问题不是必现，一些情况下能正常获取数据，一些情况下返回报错信息：Can not decode value starting with character '<'。 猜测可能跟数据源网站更新时，一些数值带有上下箭头有关？如下 ![image](https://user-images.githubusercontent.com/7132796/218648729-0689adc1-e03d-4a21-909f-9ff8add1689d.png)
> 
> 交易时间内调用应该能复现问题。

是访问太频繁被封禁 IP，一段时间后恢复
