### ISSUE TITLE
ak.stock_info_a_code_name() 报错 ValueError: Length mismatch: Expected axis has 14 elements, new values have 13 elements

### ISSUE THREAD

**Issue by zgpnuaa** [akfamily/akshare#3471]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本 :    Win11
3. Python 版本:     3.11.2
4. AKShare 版本:   1.8.84
5. 接口的名称和代码:    stock_info_a_code_name() 
6. 接口报错的截图或代码
```
dat= ak.stock_info_a_code_name()
print(dat)
```

```
ValueError                                Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_8664/153525904.py in <module>
      1 # df1 = ak.index_stock_cons_weight_csindex(symbol="000905")
      2 # stocks = list(df1[['成分券代码'][0]])
----> 3 dat= ak.stock_info_a_code_name()
      4 dat

D:\VScodeProjects\QMTmini\venv\lib\site-packages\akshare\stock\stock_info.py in stock_info_a_code_name()
    427     """
    428     big_df = pd.DataFrame()
--> 429     stock_sh = stock_info_sh_name_code(indicator="主板A股")
    430     stock_sh = stock_sh[["证券代码", "证券简称"]]
    431 

D:\VScodeProjects\QMTmini\venv\lib\site-packages\akshare\stock\stock_info.py in stock_info_sh_name_code(indicator)
    165         "-",
    166         "证券代码",
--> 167         "-",
    168     ]
    169     temp_df = temp_df[

D:\VScodeProjects\QMTmini\venv\lib\site-packages\pandas\core\generic.py in __setattr__(self, name, value)
   5489         try:
   5490             object.__getattribute__(self, name)
-> 5491             return object.__setattr__(self, name, value)
   5492         except AttributeError:
   5493             pass

D:\VScodeProjects\QMTmini\venv\lib\site-packages\pandas\_libs\properties.pyx in pandas._libs.properties.AxisProperty.__set__()

D:\VScodeProjects\QMTmini\venv\lib\site-packages\pandas\core\generic.py in _set_axis(self, axis, labels)
    761     def _set_axis(self, axis: int, labels: Index) -> None:
    762         labels = ensure_index(labels)
--> 763         self._mgr.set_axis(axis, labels)
    764         self._clear_item_cache()
    765 

D:\VScodeProjects\QMTmini\venv\lib\site-packages\pandas\core\internals\managers.py in set_axis(self, axis, new_labels)
    214     def set_axis(self, axis: int, new_labels: Index) -> None:
    215         # Caller is responsible for ensuring we have an Index object.
--> 216         self._validate_set_axis(axis, new_labels)
    217         self.axes[axis] = new_labels
    218 

D:\VScodeProjects\QMTmini\venv\lib\site-packages\pandas\core\internals\base.py in _validate_set_axis(self, axis, new_labels)
     56         elif new_len != old_len:
     57             raise ValueError(
---> 58                 f"Length mismatch: Expected axis has {old_len} elements, new "
     59                 f"values have {new_len} elements"
     60             )

ValueError: Length mismatch: Expected axis has 14 elements, new values have 13 elements
```

8. 期望获得的正确结果

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本 :    Win11
> 2. Python 版本:     3.11.2
> 3. AKShare 版本:   1.8.84
> 4. 接口的名称和代码:    stock_info_a_code_name()
> 5. 接口报错的截图或代码
> 
> ```
> dat= ak.stock_info_a_code_name()
> print(dat)
> ```
> 
> ```
> ValueError                                Traceback (most recent call last)
> ~\AppData\Local\Temp/ipykernel_8664/153525904.py in <module>
>       1 # df1 = ak.index_stock_cons_weight_csindex(symbol="000905")
>       2 # stocks = list(df1[['成分券代码'][0]])
> ----> 3 dat= ak.stock_info_a_code_name()
>       4 dat
> 
> D:\VScodeProjects\QMTmini\venv\lib\site-packages\akshare\stock\stock_info.py in stock_info_a_code_name()
>     427     """
>     428     big_df = pd.DataFrame()
> --> 429     stock_sh = stock_info_sh_name_code(indicator="主板A股")
>     430     stock_sh = stock_sh[["证券代码", "证券简称"]]
>     431 
> 
> D:\VScodeProjects\QMTmini\venv\lib\site-packages\akshare\stock\stock_info.py in stock_info_sh_name_code(indicator)
>     165         "-",
>     166         "证券代码",
> --> 167         "-",
>     168     ]
>     169     temp_df = temp_df[
> 
> D:\VScodeProjects\QMTmini\venv\lib\site-packages\pandas\core\generic.py in __setattr__(self, name, value)
>    5489         try:
>    5490             object.__getattribute__(self, name)
> -> 5491             return object.__setattr__(self, name, value)
>    5492         except AttributeError:
>    5493             pass
> 
> D:\VScodeProjects\QMTmini\venv\lib\site-packages\pandas\_libs\properties.pyx in pandas._libs.properties.AxisProperty.__set__()
> 
> D:\VScodeProjects\QMTmini\venv\lib\site-packages\pandas\core\generic.py in _set_axis(self, axis, labels)
>     761     def _set_axis(self, axis: int, labels: Index) -> None:
>     762         labels = ensure_index(labels)
> --> 763         self._mgr.set_axis(axis, labels)
>     764         self._clear_item_cache()
>     765 
> 
> D:\VScodeProjects\QMTmini\venv\lib\site-packages\pandas\core\internals\managers.py in set_axis(self, axis, new_labels)
>     214     def set_axis(self, axis: int, new_labels: Index) -> None:
>     215         # Caller is responsible for ensuring we have an Index object.
> --> 216         self._validate_set_axis(axis, new_labels)
>     217         self.axes[axis] = new_labels
>     218 
> 
> D:\VScodeProjects\QMTmini\venv\lib\site-packages\pandas\core\internals\base.py in _validate_set_axis(self, axis, new_labels)
>      56         elif new_len != old_len:
>      57             raise ValueError(
> ---> 58                 f"Length mismatch: Expected axis has {old_len} elements, new "
>      59                 f"values have {new_len} elements"
>      60             )
> 
> ValueError: Length mismatch: Expected axis has 14 elements, new values have 13 elements
> ```
> 
> 8. 期望获得的正确结果

感谢反馈问题，已修复该问题，升级到 AKShare 1.8.85 使用
