### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by zwj-lambda** [akfamily/akshare#3484]
输入：
import akshare as ak
bond_info_detail_cm_df = ak.bond_info_detail_cm(symbol="19万林投资CP001")
输出报错
raise JSONDecodeError(errmsg, string, idx)
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by jindaxiang** [comment]
> 输入： import akshare as ak bond_info_detail_cm_df = ak.bond_info_detail_cm(symbol="19万林投资CP001") 输出报错 raise JSONDecodeError(errmsg, string, idx) simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

感谢反馈问题，已修复该问题，升级到 AKShare 1.8.90 版本使用
