### ISSUE TITLE
AKShare 接口问题报告 futures_egg_price()

### ISSUE THREAD

**Issue by chenjc2011** [akfamily/akshare#3502]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
 akshare  1.8.94
python    3.85
**描述遇到的问题**
  import akshare as ak
>>> df_price = ak.futures_egg_price()
Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    df_price = ak.futures_egg_price()
  File "H:\python3-85\lib\site-packages\akshare\futures_derivative\futures_egg.py", line 79, in futures_egg_price
    value_2015_list = eval(re.findall(r"data: (\[.*?])", js_text_processed[3])[0])
IndexError: list index out of range

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
>  akshare  1.8.94
> python    3.85
> **描述遇到的问题**
>   import akshare as ak
> >>> df_price = ak.futures_egg_price()
> Traceback (most recent call last):
>   File "<pyshell#1>", line 1, in <module>
>     df_price = ak.futures_egg_price()
>   File "H:\python3-85\lib\site-packages\akshare\futures_derivative\futures_egg.py", line 79, in futures_egg_price
>     value_2015_list = eval(re.findall(r"data: (\[.*?])", js_text_processed[3])[0])
> IndexError: list index out of range
> ```

感谢反馈问题，已修复该问题，升级到 AKShare 1.8.98 使用
