### ISSUE TITLE
AKShare 接口问题报告 AttributeError: module 'akshare' has no attribute 'fund_etf_hist_em'

### ISSUE THREAD

**Issue by calorand** [akfamily/akshare#3505]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本 : windows
2. Python 版本: 3.10
3. AKShare 版本 : 最新
4. 接口的名称和代码 ：fund_etf_hist_em
5. 接口报错的截图或代码 : AttributeError: module 'akshare' has no attribute 'fund_etf_hist_em'
6. 期望获得的正确结果: 该接口正常使用

AttributeError: module 'akshare' has no attribute 'fund_etf_hist_em'

提示无此用法？

**Comment by jindaxiang** [comment]
> fund_etf_hist_em

接口正常可以用，建议升级到最新版
