### ISSUE TITLE
stock_us_code_table_fu api 报错

### ISSUE THREAD

**Issue by sunaigo** [akfamily/akshare#3511]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本 ubuntu 22.04 x86
3. Python 版本 3.9.16
4. AKShare 版本 1.8.99
5. 接口的名称和代码 stock_us_code_table_fu
6. 接口报错的截图或代码
   
<img width="1275" alt="CleanShot 2023-03-01 at 14 37 38@2x" src="https://user-images.githubusercontent.com/19339064/222063247-9311eb0a-714a-4433-b7fe-dddd259c3e3c.png">

8. 期望获得的正确结果
正确返回

**Comment by jindaxiang** [comment]
> 4\. stock_us_code_table_fu

接口正常
