### ISSUE TITLE
AKShare 接口问题报告ak.stock_xgsglb_em出错

### ISSUE THREAD

**Issue by xnw176** [akfamily/akshare#3516]
**描述遇到的问题**
1. 操作系统版本 MAC OS 13
2. Python 版本 3.8
3. AKShare 版本 最新
4. 接口的名称和代。ak.stock_xgsglb_em
5. 接口报错的截图或代码
<img width="667" alt="image" src="https://user-images.githubusercontent.com/82297022/222604818-037cd7b3-1824-4fa0-93e7-6debc85f2e95.png">

**Comment by jindaxiang** [comment]
> **描述遇到的问题**
> 
> 1. 操作系统版本 MAC OS 13
> 2. Python 版本 3.8
> 3. AKShare 版本 最新
> 4. 接口的名称和代。ak.stock_xgsglb_em
> 5. 接口报错的截图或代码
> 
> <img alt="image" width="667" src="https://user-images.githubusercontent.com/82297022/222604818-037cd7b3-1824-4fa0-93e7-6debc85f2e95.png">

感谢反馈问题，已修复该问题，升级到 AKShare 1.9.2 版本使用
