### ISSUE TITLE
中国股票指数数据 除权问题

### ISSUE THREAD

**Issue by U-369956** [akfamily/akshare#3521]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本
win10
2. Python 版本
3.7
3. AKShare 版本
1.9.2
4. 接口的名称和代码
ak.stock_zh_index_daily_em(symbol= 'sz159845')
5. 接口报错的截图或代码
接口无报错，但股指接口无除权参数
6. 期望获得的正确结果
希望大佬能够加入股指除权功能

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本
>    win10
> 2. Python 版本
>    3.7
> 3. AKShare 版本
>    1.9.2
> 4. 接口的名称和代码
>    ak.stock_zh_index_daily_em(symbol= 'sz159845')
> 5. 接口报错的截图或代码
>    接口无报错，但股指接口无除权参数
> 6. 期望获得的正确结果
>    希望大佬能够加入股指除权功能

接口请求正常
