### ISSUE TITLE
futures_hog_info 接口返回数据仅到202207

### ISSUE THREAD

**Issue by Sjymmd** [akfamily/akshare#3532]
这个接口中调用URL = "https://zhujia.zhuwang.cc" 返回数据只到202207，修改 URL = "https://zhujia.zhuwang.com.cn" 后和网站显示一致，望修复

**Comment by jindaxiang** [comment]
> 这个接口中调用URL = "https://zhujia.zhuwang.cc" 返回数据只到202207，修改 URL = "https://zhujia.zhuwang.com.cn" 后和网站显示一致，望修复

感谢反馈问题及解决方案，已修复该问题，升级到 AKShare 1.9.6 使用
