### ISSUE TITLE
AKShare 接口问题报告 - bond_investing_global

### ISSUE THREAD

**Issue by congcong009** [akfamily/akshare#3536]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本：Win10
2. Python 版本：3.8
3. AKShare 版本：1.9.6
4. 接口的名称和代码：bond_investing_global
5. 接口报错的截图或代码：AttributeError: 'NoneType' object has no attribute 'find_all'

通过海外ip访问，在 _get_global_country_name_url() 第28行获得的soup 反馈，<h1 data-translate="block_headline">Sorry, you have been blocked</h1>，切换多个地区均无法通过，但网页访问目标网页是可行的。

7. 期望获得的正确结果

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本：Win10
> 2. Python 版本：3.8
> 3. AKShare 版本：1.9.6
> 4. 接口的名称和代码：bond_investing_global
> 5. 接口报错的截图或代码：AttributeError: 'NoneType' object has no attribute 'find_all'
> 
> 通过海外ip访问，在 _get_global_country_name_url() 第28行获得的soup 反馈，
> 
> # Sorry, you have been blocked
> ，切换多个地区均无法通过，但网页访问目标网页是可行的。
> 7. 期望获得的正确结果

该接口暂不能使用，已在文档添加说明
