### ISSUE TITLE
求：同花顺盈利预测 http://basic.10jqka.com.cn/new/600536/worth.html -> 爬虫

### ISSUE THREAD

**Issue by tyePhDCandy** [akfamily/akshare#3541]
# 同花顺盈利预测 http://basic.10jqka.com.cn/new/600536/worth.html -> 爬虫
建议名称：盈利预测-同花顺
网页链接： http://basic.10jqka.com.cn/new/600536/worth.html

# 网页中目标信息截图。可以只实现“业绩预测”爬虫。如果不麻烦的话，可以额外实现“业绩预测详表”的爬虫。谢谢。
![image](https://user-images.githubusercontent.com/22343659/223726888-fa8fc588-8992-4f6f-bae4-78e42d174a00.png)

**Comment by jindaxiang** [comment]
> # 同花顺盈利预测 http://basic.10jqka.com.cn/new/600536/worth.html -> 爬虫
> 建议名称：盈利预测-同花顺 网页链接： http://basic.10jqka.com.cn/new/600536/worth.html
> 
> # 网页中目标信息截图。可以只实现“业绩预测”爬虫。如果不麻烦的话，可以额外实现“业绩预测详表”的爬虫。谢谢。
> ![image](https://user-images.githubusercontent.com/22343659/223726888-fa8fc588-8992-4f6f-bae4-78e42d174a00.png)

感谢反馈接口，已新增 stock_profit_forecast_ths 接口，升级到 AKShare 1.9.7 使用
