### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by bonarealm** [akfamily/akshare#3550]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. Ubuntu20.04
2. Python 3.8.10
3. AKShare 1.8.99
4.stock_info_bj_name_code  发生异常: JSONDecodeError
Expecting value: line 1 column 1 (char 0)
5. 
![image](https://user-images.githubusercontent.com/55485921/224694911-a8819291-16b5-43d8-9ba4-1357054a62e8.png)

6. 期望获得的正确结果

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> **描述遇到的问题**
> 
> 1. Ubuntu20.04
> 2. Python 3.8.10
> 3. AKShare 1.8.99
>    4.stock_info_bj_name_code  发生异常: JSONDecodeError
>    Expecting value: line 1 column 1 (char 0)
> 
> ![image](https://user-images.githubusercontent.com/55485921/224694911-a8819291-16b5-43d8-9ba4-1357054a62e8.png)
> 
> 6. 期望获得的正确结果

升级到最新版使用
