### ISSUE TITLE
futures_global_commodity_hist接口失效

### ISSUE THREAD

**Issue by Yitong-Guo** [akfamily/akshare#3551]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1.操作系统版本 WIN10

2.Python 版本 3.8.5

3.AKShare 版本 1.9.10

4.接口：futures_global_commodity_hist
问题代码：futures_global_commodity_name_url_map_dict = ak.futures_global_commodity_name_url_map(sector="能源")
print(futures_global_commodity_name_url_map_dict)

5.报错截图：
<img width="681" alt="屏幕截图 2023-03-13 203355" src="https://user-images.githubusercontent.com/93232845/224703344-2758bdab-d4b8-472c-97f3-bac68201d37b.png">

6.这是akshare这个接口的源码运行，表现为已经抓取不到该网页的源代码了
<img width="577" alt="屏幕截图 2023-03-13 203730" src="https://user-images.githubusercontent.com/93232845/224704228-5bf9ffee-0f7c-4163-8d55-f4573913f694.png">

**Comment by jindaxiang** [comment]
> futures_global_commodity_name_url_map

该接口暂时不能获取数据，已增加文档说明
