### ISSUE TITLE
强烈建议科创板数据从东方财富网获取

### ISSUE THREAD

**Issue by dominicx** [akfamily/akshare#3552]
http://quote.eastmoney.com/center/gridlist.html#kcb_board

用实时行情数据-东财 沪深京 A 股 接口 stock_zh_a_spot_em 改吧改吧应该可以实现。

现在科创板数据从 http://vip.stock.finance.sina.com.cn/mkt/#kcb获取的。

**Comment by jindaxiang** [comment]
> 科创板

参考stock_kc_a_spot_em

**Comment by dominicx** [comment]
> stock_kc_a_spot_em

非常好！，文档里面科创板 节点使用新浪数据。A股 实时行情数据 科创板 链接用的是http://quote.eastmoney.com/center/gridlist.html#hs_a_board 所以没有搜索到。

再次感谢！
