### ISSUE TITLE
stock_hot_rank_wc()只能返回前300条数据，请修复更新，谢谢！

### ISSUE THREAD

**Issue by tianhaisuifeng** [akfamily/akshare#3560]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
akshare-1.9.11版本
stock_hot_rank_wc()只能返回前300条数据，远小于预期的1000条数据

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> **描述遇到的问题** akshare-1.9.11版本 stock_hot_rank_wc()只能返回前300条数据，远小于预期的1000条数据

由于数据源限制，目前只能返回前 300 个股票的数据，已经修改文档表述

**Comment by tianhaisuifeng** [comment]
@jindaxiang 这个接口现在获取的不是300个数据，是只能获取前30个数据。代码中循环10次获取数据，只是把前30个数据重复获取了10次，也就是pageid没有生效。

**Comment by jindaxiang** [comment]
> @jindaxiang 这个接口现在获取的不是300个数据，是只能获取前30个数据。代码中循环10次获取数据，只是把前30个数据重复获取了10次，也就是pageid没有生效。

感谢反馈问题；已修复该问题，且可以获取近5000条数据，升级到AKShare 1.9.12 版本使用

**Comment by tianhaisuifeng** [comment]
@jindaxiang 非常感谢！你们团队的实力太强悍了，为你们点赞！！！
