### ISSUE TITLE
news_economic_baidu函数失效

### ISSUE THREAD

**Issue by kingls** [akfamily/akshare#3562]
Python 版本 3.9.12
AKShare 版本 1.9.11
接口的名称和代码 news_economic_baidu

函数返回空白DataFrame

**Comment by jindaxiang** [comment]
> Python 版本 3.9.12 AKShare 版本 1.9.11 接口的名称和代码 news_economic_baidu
> 
> 函数返回空白DataFrame

目前该接口访问正常；如有问题，请提供更多参考代码
