### ISSUE TITLE
ak.stock_zh_valuation_baidu()接口返回数据不全

### ISSUE THREAD

**Issue by ChunxiaoYang** [akfamily/akshare#3564]
python 3.8.5
ak.__version__ '1.8.48'
![image](https://user-images.githubusercontent.com/121948670/226117324-80a9d567-9104-4e13-ba6f-ac3f2dce6898.png)
可以运行出结果，但是可以看到3月份的数据有缺失。

**Comment by ChunxiaoYang** [comment]
而且可以看到3月18日是星期六不是交易日。

**Comment by jindaxiang** [comment]
> python 3.8.5 ak.**version** '1.8.48' ![image](https://user-images.githubusercontent.com/121948670/226117324-80a9d567-9104-4e13-ba6f-ac3f2dce6898.png) 可以运行出结果，但是可以看到3月份的数据有缺失。

感谢反馈问题；已修复该问题，升级到 AKShare 1.9.13 版本使用
