### ISSUE TITLE
AKShare 接口stock_a_lg_indicator问题报告

### ISSUE THREAD

**Issue by Baike2023** [akfamily/akshare#3574]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本 win11
2. Python 版本 3.8.14
3. AKShare 版本 1.9.15
4. 接口的名称和代码 
import akshare as ak
SH600030_gxl = ak.stock_a_lg_indicator(symbol="600030")

5. 接口报错的截图或代码
JSONDecodeError                           Traceback (most recent call last)
File /usr/local/lib/python3.8/site-packages/requests/models.py:971, in Response.json(self, **kwargs)
    970 try:
--> 971     return complexjson.loads(self.text, **kwargs)
    972 except JSONDecodeError as e:
    973     # Catch JSON-related errors and raise as requests.JSONDecodeError
    974     # This aliases json.JSONDecodeError and simplejson.JSONDecodeError

File /usr/local/lib/python3.8/json/__init__.py:357, in loads(s, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    354 if (cls is None and object_hook is None and
    355         parse_int is None and parse_float is None and
    356         parse_constant is None and object_pairs_hook is None and not kw):
--> 357     return _default_decoder.decode(s)
    358 if cls is None:

7. 期望获得的正确结果

**Comment by jindaxiang** [comment]
> 4\. stock_a_lg_indicator

可以正常获取；注意获取的频率

**Comment by Baike2023** [comment]
1. 使用"all"可以正常返回
all_gxl = ak.stock_a_lg_indicator(symbol="all")
2. 使用个股依旧返回错误，估值是url拼接的不对，请帮忙查看
SH600030_gxl = ak.stock_a_lg_indicator(symbol="600030")
---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
File /usr/local/lib/python3.8/site-packages/requests/models.py:971, in Response.json(self, **kwargs)
    970 try:
--> 971     return complexjson.loads(self.text, **kwargs)
    972 except JSONDecodeError as e:
    973     # Catch JSON-related errors and raise as requests.JSONDecodeError
    974     # This aliases json.JSONDecodeError and simplejson.JSONDecodeError

File /usr/local/lib/python3.8/json/__init__.py:357, in loads(s, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    354 if (cls is None and object_hook is None and
    355         parse_int is None and parse_float is None and
    356         parse_constant is None and object_pairs_hook is None and not kw):
--> 357     return _default_decoder.decode(s)
    358 if cls is None:

File /usr/local/lib/python3.8/json/decoder.py:337, in JSONDecoder.decode(self, s, _w)
    333 """Return the Python representation of ``s`` (a ``str`` instance
    334 containing a JSON document).
    335 
    336 """
--> 337 obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    338 end = _w(s, end).end()

File /usr/local/lib/python3.8/json/decoder.py:355, in JSONDecoder.raw_decode(self, s, idx)
    354 except StopIteration as err:
--> 355     raise JSONDecodeError("Expecting value", s, err.value) from None
    356 return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

JSONDecodeError                           Traceback (most recent call last)
Cell In [55], line 1
----> 1 SH600030_gxl_df = ak.stock_a_lg_indicator(symbol="600030")

File /usr/local/lib/python3.8/site-packages/akshare/stock_feature/stock_a_indicator.py:41, in stock_a_lg_indicator(symbol)
     **39 url = f"[https://www.legulegu.com/s/base-info/{symbol](https://www.legulegu.com/s/base-info/%7Bsymbol)}"**
     40 r = requests.get(url)
---> 41 temp_json = r.json()
     42 temp_df = pd.DataFrame(
     43     temp_json["data"]["items"], columns=temp_json["data"]["fields"]
     44 )
     45 temp_df["trade_date"] = pd.to_datetime(temp_df["trade_date"]).dt.date

File /usr/local/lib/python3.8/site-packages/requests/models.py:975, in Response.json(self, **kwargs)
    971     return complexjson.loads(self.text, **kwargs)
    972 except JSONDecodeError as e:
    973     # Catch JSON-related errors and raise as requests.JSONDecodeError
    974     # This aliases json.JSONDecodeError and simplejson.JSONDecodeError
--> 975     raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)

JSONDecodeError: Expecting value: line 1 column 1 (char 0)
