### ISSUE TITLE
fund_em.py的fund_info_index_em 133行条件写错了吧

### ISSUE THREAD

**Issue by zkna** [akfamily/akshare#3585]
fund_em.py 这里应该是` symbol in {"股票指数", "债券指数"} `
而不是` symbol in {"股票指数", "股票指数"} `这个吧
![如图](https://user-images.githubusercontent.com/19741934/227116644-dbc9458a-1153-4eaf-8cc4-d3913b7cf4ed.png)

**Comment by jindaxiang** [comment]
> fund_em.py 这里应该是`symbol in {"股票指数", "债券指数"}` 而不是`symbol in {"股票指数", "股票指数"}`这个吧 ![如图](https://user-images.githubusercontent.com/19741934/227116644-dbc9458a-1153-4eaf-8cc4-d3913b7cf4ed.png)

感谢反馈问题；已修复该问题，升级到 AKShare 1.9.22 版本使用
