### ISSUE TITLE
ak.stock_zh_a_minute    分钟历史数据  接口错误 raise SSLError(e, request=request)  SSLError: HTTPSConnectionPool(host='quotes.sina.cn', port=443): Max retries exceeded with url: 

### ISSUE THREAD

**Issue by yutyflynew1** [akfamily/akshare#3586]
Python 3.9.13 (main, Aug 25 2022, 23:51:50) [MSC v.1916 64 bit (AMD64)]

stock_zh_a_minute_df = ak.stock_zh_a_minute(symbol='sh600751', period='1', adjust="qfq")

raise SSLError(e, request=request)

SSLError: HTTPSConnectionPool(host='quotes.sina.cn', port=443): Max retries exceeded with url: /cn/api/jsonp_v2.php/=/CN_MarketDataService.getKLineData?symbol=sh600751&scale=1&ma=no&datalen=36580 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))

**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本
2. Python 版本
3. AKShare 版本
4. 接口的名称和代码
5. 接口报错的截图或代码
6. 期望获得的正确结果

**Comment by jindaxiang** [comment]
> qfq

可以正常使用
