### ISSUE TITLE
bond_cb_redeem_jsl() error

### ISSUE THREAD

**Issue by Alexrus2023** [akfamily/akshare#3589]
When i input bond_cb_redeem_jsl() , i got:
ValueError: Length mismatch: Expected axis has 33 elements, new values have 29 elements

**Comment by jindaxiang** [comment]
> When i input bond_cb_redeem_jsl() , i got: ValueError: Length mismatch: Expected axis has 33 elements, new values have 29 elements

感谢反馈问题；已修复该问题，升级到 AKShare 1.9.23 版本使用
