### ISSUE TITLE
AKShare 接口问题报告 -> stock_board_industry_summary_ths

### ISSUE THREAD

**Issue by tianyongliu** [akfamily/akshare#3596]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本
2. Python 版本
3. AKShare 版本
4. 接口的名称和代码
5. 接口报错的截图或代码

stock_board_industry_summary_ths

7. 期望获得的正确结果

这个接口能加上个时间吗，比如我今天上午调用该接口，那么接口返回的数据是昨天的还是今天的？感觉不直观啊，一点小意见，如果不对，请忽略！

**Comment by tianyongliu** [comment]
还是这个接口，期望这个接口再增加如下字段：
资金净流入，成交量。

不知道还有没有根据行业名称或者板块代码查询成分股的结构，如果有就更好了，谢谢！

**Comment by jindaxiang** [comment]
> stock_board_industry_summary_ths

目前接口的设计原则是跟目标网站一致；如果需要相关数据，可以调用 AKShare 中其他相关的接口使用
