### ISSUE TITLE
获取基金历史数据时报KeyError

### ISSUE THREAD

**Issue by coneagoe** [akfamily/akshare#3603]
**Describe the bug**

获取基金‘162411’历史数据时报KeyError

```python
    df = ak.fund_etf_hist_em(symbol=stock_id, period="daily",
  File "C:\Users\conea\anaconda3\envs\frog\lib\site-packages\akshare\fund\fund_etf_em.py", line 154, in fund_etf_hist_em    "secid": f"{code_id_dict[symbol]}.{symbol}",
KeyError: '162411'
```

OS: WIN10
Python version: 3.9.16
AKShare version: 1.8.87

**To Reproduce**
见描述

**Desktop (please complete the following information):**
 - OS: Win10
 - Python: 3.9.16
 - AKShare: 1.8.87

**Comment by jindaxiang** [comment]
> 162411

该接口是为 etf 准备的；请使用 fund_money_fund_info_em 接口
