### ISSUE TITLE
获取上交所股票列表时偶尔出现股票简称出错的问题

### ISSUE THREAD

**Issue by haijiangxu** [akfamily/akshare#3608]
df = ak.stock_info_sh_name_code(symbol="科创板")
df = df.set_index('证券代码')
df.loc['688531']
显示如下：
证券简称               -
公司全称    无锡日联科技股份有限公司
上市日期      2023-03-31

而上交所网站上显示  N日联

**Comment by jindaxiang** [comment]
> stock_info_sh_name_code

接口正常，升级到最新版使用
