### ISSUE TITLE
stock_a_lg_indicator()接口问题报告

### ISSUE THREAD

**Issue by tianhaisuifeng** [akfamily/akshare#3609]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
stock_a_lg_indicator()接口获取单个公司数据时报错

建议修改方法：
增加**tuShareHttpContent**
temp_df = pd.DataFrame(
            temp_json["**tuShareHttpContent**"]["data"]["items"], columns=temp_json["**tuShareHttpContent**"]["data"]["fields"]
        )

**Comment by jindaxiang** [comment]
> tuShareHttpContent

感谢反馈问题及提供解决方案，已修复该问题，升级到 AKShare 1.9.29 使用
