### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by zacharyzzc** [akfamily/akshare#3612]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本    Mac
2. Python 版本    3.8
3. AKShare 版本  1.9.29
4. 接口的名称和代码   1.9.29
5. 接口报错的截图或代码   stock_a_lg_indicator?symbol=600839 
6. 期望获得的正确结果    异常了

**Comment by edward852** [comment]
legu又改了。。。
我自己试了一下，需要使用同一个session(requests库的Session)分2个步骤获取
1
访问首页，提取其中的_csrf元素的内容
2
`headers = {'X-CSRF-Token': csrf, 'Accept': "application/json", "Content-Type": "application/json"}`
加入headers(主要是X-CSRF-Token)用post方法访问原接口
![image](https://user-images.githubusercontent.com/1405557/229406576-75551f05-e96f-4471-b1ef-1fef52efb986.png)

**Comment by namoshizun** [comment]
好像还要提供session id才行，已开了一个[PR](https://github.com/akfamily/akshare/pull/3614)

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本    Mac
> 2. Python 版本    3.8
> 3. AKShare 版本  1.9.29
> 4. 接口的名称和代码   1.9.29
> 5. 接口报错的截图或代码   stock_a_lg_indicator?symbol=600839
> 6. 期望获得的正确结果    异常了

感谢反馈问题，已修复该问题，升级到 AKShare 1.9.30 版本使用
