### ISSUE TITLE
stock_a_lg_indicator()接口获取单个公司报错

### ISSUE THREAD

**Issue by tianhaisuifeng** [akfamily/akshare#3625]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
stock_a_lg_indicator()接口获取单个公司报错，r.json()报错：line 37, in _scan_once
    nextchar = string[idx] IndexError: string index out of range

akshare版本：1.9.34

**Comment by xnw176** [comment]
乐估的接口大批失效。

**Comment by tianhaisuifeng** [comment]
建议修改方案：
1、在Cookie中增加rdtkolg
2、解析数据时，修改成如下：
temp_df = pd.DataFrame(
            temp_json["data"]["items"],
            columns = temp_json["data"]["fields"],
        )

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> **描述遇到的问题** stock_a_lg_indicator()接口获取单个公司报错，r.json()报错：line 37, in _scan_once nextchar = string[idx] IndexError: string index out of range
> 
> akshare版本：1.9.34

感谢反馈问题；已修复该问题，升级到 AKShare 1.9.35 使用
