### ISSUE TITLE
stock_a_pb 获取数据有误

### ISSUE THREAD

**Issue by stockquant** [akfamily/akshare#3627]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本: WINDOWS
3. Python 版本: 3.8
4. AKShare 版本: 1.9.35
5. 接口的名称和代码：
import akshare as ak
stock_a_pb_df = ak.stock_a_pb(symbol="000902.XSHG")
print(stock_a_pb_df)
7. 接口报错的截图或代码
JSONDecodeError                           Traceback (most recent call last)
File C:\anaconda3\lib\site-packages\requests\models.py:910, in Response.json(self, **kwargs)
    909 try:
--> 910     return complexjson.loads(self.text, **kwargs)
    911 except JSONDecodeError as e:
    912     # Catch JSON-related errors and raise as requests.JSONDecodeError
    913     # This aliases json.JSONDecodeError and simplejson.JSONDecodeError

File C:\anaconda3\lib\json\__init__.py:346, in loads(s, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    343 if (cls is None and object_hook is None and
    344         parse_int is None and parse_float is None and
    345         parse_constant is None and object_pairs_hook is None and not kw):
--> 346     return _default_decoder.decode(s)
    347 if cls is None:

File C:\anaconda3\lib\json\decoder.py:337, in JSONDecoder.decode(self, s, _w)
    333 """Return the Python representation of ``s`` (a ``str`` instance
    334 containing a JSON document).
    335 
    336 """
--> 337 obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    338 end = _w(s, end).end()

File C:\anaconda3\lib\json\decoder.py:355, in JSONDecoder.raw_decode(self, s, idx)
    354 except StopIteration as err:
--> 355     raise JSONDecodeError("Expecting value", s, err.value) from None
    356 return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

JSONDecodeError                           Traceback (most recent call last)
Input In [4], in <cell line: 3>()
      1 import akshare as ak
----> 3 stock_a_pb_df = ak.stock_a_pb(symbol="000902.XSHG")
      4 print(stock_a_pb_df)

File C:\anaconda3\lib\site-packages\akshare\stock_feature\stock_a_pb.py:345, in stock_a_pb(symbol)
    343 params = {"token": token, "marketId": symbol}
    344 r = requests.get(url, params=params)
--> 345 data_json = r.json()
    346 temp_df = pd.DataFrame(data_json)
    347 temp_df.index = (
    348     pd.to_datetime(temp_df["date"], unit="ms", utc=True)
    349     .dt.tz_convert("Asia/Shanghai")
    350     .dt.date
    351 )

File C:\anaconda3\lib\site-packages\requests\models.py:917, in Response.json(self, **kwargs)
    915     raise RequestsJSONDecodeError(e.message)
    916 else:
--> 917     raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)

JSONDecodeError: [Errno Expecting value] : 0
9. 期望获得的正确结果

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本: WINDOWS
> 2. Python 版本: 3.8
> 3. AKShare 版本: 1.9.35
> 4. 接口的名称和代码：
>    import akshare as ak
>    stock_a_pb_df = ak.stock_a_pb(symbol="000902.XSHG")
>    print(stock_a_pb_df)
> 5. 接口报错的截图或代码
>    JSONDecodeError                           Traceback (most recent call last)
>    File C:\anaconda3\lib\site-packages\requests\models.py:910, in Response.json(self, **kwargs)
>    909 try:
>    --> 910     return complexjson.loads(self.text, **kwargs)
>    911 except JSONDecodeError as e:
>    912     # Catch JSON-related errors and raise as requests.JSONDecodeError
>    913     # This aliases json.JSONDecodeError and simplejson.JSONDecodeError
> 
> File C:\anaconda3\lib\json__init__.py:346, in loads(s, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw) 343 if (cls is None and object_hook is None and 344 parse_int is None and parse_float is None and 345 parse_constant is None and object_pairs_hook is None and not kw): --> 346 return _default_decoder.decode(s) 347 if cls is None:
> 
> File C:\anaconda3\lib\json\decoder.py:337, in JSONDecoder.decode(self, s, _w) 333 """Return the Python representation of `s` (a `str` instance 334 containing a JSON document). 335 336 """ --> 337 obj, end = self.raw_decode(s, idx=_w(s, 0).end()) 338 end = _w(s, end).end()
> 
> File C:\anaconda3\lib\json\decoder.py:355, in JSONDecoder.raw_decode(self, s, idx) 354 except StopIteration as err: --> 355 raise JSONDecodeError("Expecting value", s, err.value) from None 356 return obj, end
> 
> JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 
> During handling of the above exception, another exception occurred:
> 
> JSONDecodeError Traceback (most recent call last) Input In [4], in <cell line: 3>() 1 import akshare as ak ----> 3 stock_a_pb_df = ak.stock_a_pb(symbol="000902.XSHG") 4 print(stock_a_pb_df)
> 
> File C:\anaconda3\lib\site-packages\akshare\stock_feature\stock_a_pb.py:345, in stock_a_pb(symbol) 343 params = {"token": token, "marketId": symbol} 344 r = requests.get(url, params=params) --> 345 data_json = r.json() 346 temp_df = pd.DataFrame(data_json) 347 temp_df.index = ( 348 pd.to_datetime(temp_df["date"], unit="ms", utc=True) 349 .dt.tz_convert("Asia/Shanghai") 350 .dt.date 351 )
> 
> File C:\anaconda3\lib\site-packages\requests\models.py:917, in Response.json(self, **kwargs) 915 raise RequestsJSONDecodeError(e.message) 916 else: --> 917 raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
> 
> JSONDecodeError: [Errno Expecting value] : 0 9. 期望获得的正确结果

该接口已经移除；升级到 AKShare 1.9.37 使用 stock_market_pe_lg 等接口替代

**Comment by stockquant** [comment]
stock_market_pe_lg 也是同样的问题
