### ISSUE TITLE
run  ak.stock_a_lg_indicator(symbol="000001") ,show error 

### ISSUE THREAD

**Issue by matthewxuda** [akfamily/akshare#3629]
>> import akshare as ak
>>> 
>>> stock_a_lg_indicator_df = ak.stock_a_lg_indicator(symbol="000001")
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/akshare/stock_feature/stock_a_indicator.py", line 57, in stock_a_lg_indicator
    temp_json = r.json()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] <!doctype html><html lang="en"><head><title>HTTP Status 405 – Method Not Allowed</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 405 – Method Not Allowed</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Message</b> Request method &#39;GET&#39; not supported</p><p><b>Description</b> The method received in the request-line is known by the origin server but not supported by the target resource.</p><hr class="line" /><h3>Apache Tomcat/8.5.57</h3></body></html>: 0
>>> stock_a_lg_indicator_df = ak.stock_a_lg_indicator(symbol="600031")
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/akshare/stock_feature/stock_a_indicator.py", line 57, in stock_a_lg_indicator
    temp_json = r.json()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] <!doctype html><html lang="en"><head><title>HTTP Status 405 – Method Not Allowed</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 405 – Method Not Allowed</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Message</b> Request method &#39;GET&#39; not supported</p><p><b>Description</b> The method received in the request-line is known by the origin server but not supported by the target resource.</p><hr class="line" /><h3>Apache Tomcat/8.5.57</h3></body></html>: 0
>>>

**Comment by jindaxiang** [comment]
> > > import akshare as ak
> > > > stock_a_lg_indicator_df = ak.stock_a_lg_indicator(symbol="000001")
> > > > Traceback (most recent call last):
> > > > File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/models.py", line 910, in json
> > > > return complexjson.loads(self.text, **kwargs)
> > > > File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/simplejson/**init**.py", line 525, in loads
> > > > return _default_decoder.decode(s)
> > > > File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
> > > > obj, end = self.raw_decode(s)
> > > > File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
> > > > return self.scan_once(s, idx=_w(s, idx).end())
> > > > simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "", line 1, in File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/akshare/stock_feature/stock_a_indicator.py", line 57, in stock_a_lg_indicator temp_json = r.json() File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/models.py", line 917, in json raise RequestsJSONDecodeError(e.msg, e.doc, e.pos) requests.exceptions.JSONDecodeError: [Errno Expecting value] <!doctype html><title>HTTP Status 405 – Method Not Allowed</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style>
> 
> # HTTP Status 405 – Method Not Allowed
> Type Status Report
> 
> Message Request method 'GET' not supported
> 
> Description The method received in the request-line is known by the origin server but not supported by the target resource.
> 
> ### Apache Tomcat/8.5.57
> : 0
> > > > stock_a_lg_indicator_df = ak.stock_a_lg_indicator(symbol="600031")
> > > > Traceback (most recent call last):
> > > > File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/models.py", line 910, in json
> > > > return complexjson.loads(self.text, **kwargs)
> > > > File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/simplejson/**init**.py", line 525, in loads
> > > > return _default_decoder.decode(s)
> > > > File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
> > > > obj, end = self.raw_decode(s)
> > > > File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
> > > > return self.scan_once(s, idx=_w(s, idx).end())
> > > > simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "", line 1, in File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/akshare/stock_feature/stock_a_indicator.py", line 57, in stock_a_lg_indicator temp_json = r.json() File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/models.py", line 917, in json raise RequestsJSONDecodeError(e.msg, e.doc, e.pos) requests.exceptions.JSONDecodeError: [Errno Expecting value] <!doctype html><title>HTTP Status 405 – Method Not Allowed</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style>
> 
> # HTTP Status 405 – Method Not Allowed
> Type Status Report
> 
> Message Request method 'GET' not supported
> 
> Description The method received in the request-line is known by the origin server but not supported by the target resource.
> 
> ### Apache Tomcat/8.5.57
> : 0
> > > >

感谢反馈问题，已修复该问题，升级到 AKShare 1.9.38 使用
