### ISSUE TITLE
upgrade to akshare-1.9.36, run stock_a_lg_indicator, show KeyError: "name='rdtkolg', domain=None, path=None"

### ISSUE THREAD

**Issue by matthewxuda** [akfamily/akshare#3630]
Installing collected packages: akshare
Successfully installed akshare-1.9.36
P_DWXU-MB0:555 xianxian$ python3
Python 3.8.0 (v3.8.0:fa919fdf25, Oct 14 2019, 10:23:27) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import akshare as ak
>>> stock_a_lg_indicator_df = ak.stock_a_lg_indicator(symbol="000001")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/akshare/stock_feature/stock_a_indicator.py", line 62, in stock_a_lg_indicator
    rdtkolg = r.cookies["rdtkolg"]
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='rdtkolg', domain=None, path=None"
>>>

**Comment by namoshizun** [comment]
legu又换cookies了，这次所需的cookie是2F8EA1。个人猜测这个可能是会自动更替的，建议干脆把cookies里的所有key value都提供给到`https://legulegu.com/api/s/base-info/` API headers中。。

e.g., 

```
In [6]: res = requests.get('https://legulegu.com/s/000333')

In [7]: res.cookies
Out[7]: <RequestsCookieJar[Cookie(version=0, name='2F8EA1', value='4dfac0cf-1086-47ad-94ab-408ce00fa70e', port=None, port_specified=False, domain='legulegu.com', domain_specified=False, domain_initial_dot=False, path='/', path_specified=True, secure=False, expires=None, discard=True, comment=None, comment_url=None, rest={}, rfc2109=False), Cookie(version=0, name='JSESSIONID', value='DCD7D1499E2F52731E82F7118444F0B3', port=None, port_specified=False, domain='legulegu.com', domain_specified=False, domain_initial_dot=False, path='/', path_specified=True, secure=False, expires=None, discard=True, comment=None, comment_url=None, rest={'HttpOnly': None}, rfc2109=False)]>

In [8]: res.cookies.keys()
Out[8]: ['2F8EA1', 'JSESSIONID']
```

**Comment by matthewxuda** [comment]
是不是要 pip install akshare upgrade 能够解决这个问题呀

**Comment by jindaxiang** [comment]
> Installing collected packages: akshare Successfully installed akshare-1.9.36 P_DWXU-MB0:555 xianxian$ python3 Python 3.8.0 (v3.8.0:fa919fdf25, Oct 14 2019, 10:23:27) [Clang 6.0 (clang-600.0.57)] on darwin Type "help", "copyright", "credits" or "license" for more information.
> 
> > > > import akshare as ak
> > > > stock_a_lg_indicator_df = ak.stock_a_lg_indicator(symbol="000001")
> > > > Traceback (most recent call last):
> > > > File "", line 1, in 
> > > > File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/akshare/stock_feature/stock_a_indicator.py", line 62, in stock_a_lg_indicator
> > > > rdtkolg = r.cookies["rdtkolg"]
> > > > File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/cookies.py", line 328, in **getitem**
> > > > return self._find_no_duplicates(name)
> > > > File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/cookies.py", line 399, in _find_no_duplicates
> > > > raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
> > > > KeyError: "name='rdtkolg', domain=None, path=None"

感谢反馈问题，已修复该问题，升级到 AKShare 1.9.38 使用
