### ISSUE TITLE
AKShare 接口问题报告：乐估网若干接口失效

### ISSUE THREAD

**Issue by xnw176** [akfamily/akshare#3631]
**描述遇到的问题**
1. 操作系统版本：MAC OS
3. Python 版本：3.8
4. AKShare 版本 1.9.36
5. 接口的名称和代码
ak.fund_stock_position_lg()
ak.fund_balance_position_lg()
ak.fund_linghuo_position_lg()
ak.stock_ebs_lg()
ak.stock_buffett_index_lg()
7. 接口报错的截图或代码
最终的报错都是JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by stockquant** [comment]
这个问题我也碰到了。

**Comment by jindaxiang** [comment]
> **描述遇到的问题**
> 
> 1. 操作系统版本：MAC OS
> 2. Python 版本：3.8
> 3. AKShare 版本 1.9.36
> 4. 接口的名称和代码
>    ak.fund_stock_position_lg()
>    ak.fund_balance_position_lg()
>    ak.fund_linghuo_position_lg()
>    ak.stock_ebs_lg()
>    ak.stock_buffett_index_lg()
> 5. 接口报错的截图或代码
>    最终的报错都是JSONDecodeError: Expecting value: line 1 column 1 (char 0)

感谢反馈问题；升级到 AKShare 1.9.39 使用
