### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by newboy518** [akfamily/akshare#3632]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本
3. Python 版本
4. AKShare 版本
5. 接口的名称和代码
stock_info_a_code_name_df = ak.stock_info_a_code_name()
7. 接口报错的截图或代码
ValueError: Length mismatch: Expected axis has 14 elements, new values have 13 elements
9. 期望获得的正确结果
<img width="688" alt="Snipaste_2023-04-05_14-00-55" src="https://user-images.githubusercontent.com/18328447/229994304-2d3b3b5c-0ca2-4e80-9f11-4c3e63d0f20a.png">

**Comment by jindaxiang** [comment]
> 4\. stock_info_a_code_name

升级到最新版使用
