### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by SYGOwner** [akfamily/akshare#3641]
我在使用 index_stock_cons(symbol="399006")这个接口时遇到了问题，具体的问题是当我在我的macbook上（最新的akshare，python版本为3.7）运行该接口调取成分股数据时，可以顺利运行。但是同样的代码在我的windows电脑上运行时（python版本为3.11），有一些指数（当前已知的有000016, 000688，399006）是无法获取数据并报错了。具体报错的信息在下方截图。
![WechatIMG221](https://user-images.githubusercontent.com/91171150/230244759-40b12d8c-d3b1-43b2-bf35-79cbb9a8ae6a.jpeg)

**Comment by jindaxiang** [comment]
> 我在使用 index_stock_cons(symbol="399006")这个接口时遇到了问题，具体的问题是当我在我的macbook上（最新的akshare，python版本为3.7）运行该接口调取成分股数据时，可以顺利运行。但是同样的代码在我的windows电脑上运行时（python版本为3.11），有一些指数（当前已知的有000016, 000688，399006）是无法获取数据并报错了。具体报错的信息在下方截图。 ![WechatIMG221](https://user-images.githubusercontent.com/91171150/230244759-40b12d8c-d3b1-43b2-bf35-79cbb9a8ae6a.jpeg)

都升级 Pandas 到最新版试试

**Comment by SYGOwner** [comment]
不是python版本的问题，我windows已经是3.11的python。
