### ISSUE TITLE
AKShare 接口问题报告：另外2个乐估网接口失效

### ISSUE THREAD

**Issue by xnw176** [akfamily/akshare#3642]
**描述遇到的问题**
1. 操作系统版本：MAC OS
2. Python 版本：3.8
3. AKShare 版本：最新
4. 接口的名称和代码
ak.stock_index_pb_lg()
ak.stock_index_pe_lg()
6. 接口报错的截图或代码
<img width="988" alt="image" src="https://user-images.githubusercontent.com/82297022/230252847-95ff37c1-dc3a-46d7-bf39-e8c97f5cecb9.png">

**Comment by jindaxiang** [comment]
> **描述遇到的问题**
> 
> 1. 操作系统版本：MAC OS
> 2. Python 版本：3.8
> 3. AKShare 版本：最新
> 4. 接口的名称和代码
>    ak.stock_index_pb_lg()
>    ak.stock_index_pe_lg()
> 5. 接口报错的截图或代码
> 
> <img alt="image" width="988" src="https://user-images.githubusercontent.com/82297022/230252847-95ff37c1-dc3a-46d7-bf39-e8c97f5cecb9.png">

感谢反馈问题；已修复该问题，升级到 AKShare 1.9.40 版本使用
