### ISSUE TITLE
AKShare stock_profit_forecast_em 接口问题报告

### ISSUE THREAD

**Issue by eshion** [akfamily/akshare#3644]
stock_profit_forecast_em接口返回的数据和官网数据对不上：
官网数据：
<img width="915" alt="image" src="https://user-images.githubusercontent.com/1287467/230265432-9d524436-d1dc-46db-adbe-fcf72511a1fa.png">
jie k接口返回的数据：
<img width="1331" alt="image" src="https://user-images.githubusercontent.com/1287467/230265515-3b1078f2-5e73-454f-9ebf-3ccc44affedf.png">
年份错了。

**Comment by jindaxiang** [comment]
> stock_profit_forecast_em接口返回的数据和官网数据对不上： 官网数据： <img alt="image" width="915" src="https://user-images.githubusercontent.com/1287467/230265432-9d524436-d1dc-46db-adbe-fcf72511a1fa.png"> jie k接口返回的数据： <img alt="image" width="1331" src="https://user-images.githubusercontent.com/1287467/230265515-3b1078f2-5e73-454f-9ebf-3ccc44affedf.png"> 年份错了。

感谢反馈问题；已修复该问题，升级到 AKShare 1.9.40 版本使用

**Comment by eshion** [comment]
安装了1.9.41的版本，年份还是不对。 @jindaxiang

**Comment by jindaxiang** [comment]
> 同花顺网站跟东方财富网站显示的年份一样，会不会是东方财富数据接口返回的年份有问题。 <img alt="image" width="454" src="https://user-images.githubusercontent.com/1287467/230400686-8963ebb1-2cf6-4301-9806-64f737f3dbb3.png">

网站上下滚动会变化年份，估计是前端的问题
