### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by frankyang2022** [akfamily/akshare#3648]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本
2. Python 版本
3. AKShare 版本
4. 接口的名称和代码
5. 接口报错的截图或代码
6. 期望获得的正确结果

以下接口仍旧有问题：
df =  ak.stock_a_congestion_lg()

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本
> 2. Python 版本
> 3. AKShare 版本
> 4. 接口的名称和代码
> 5. 接口报错的截图或代码
> 6. 期望获得的正确结果
> 
> 以下接口仍旧有问题： df = ak.stock_a_congestion_lg()

感谢反馈问题；已修复该接口，升级到 AKShare 1.9.43 版本使用
