### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by ximing-kooboo** [akfamily/akshare#3650]
使用1.9.42 版本
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[2], line 1
----> 1 stock_fhps_em_df = ak.stock_fhps_em(date='20230407')
      2 print(stock_fhps_em_df)

File c:\Python311\Lib\site-packages\akshare\stock_feature\stock_fhps_em.py:39, in stock_fhps_em(date)
     37 r = requests.get(url, params=params)
     38 data_json = r.json()
---> 39 total_pages = int(data_json['result']['pages'])
     40 big_df = pd.DataFrame()
     41 for page in tqdm(range(1, total_pages + 1), leave=False):

TypeError: 'NoneType' object is not subscriptable

**Comment by jindaxiang** [comment]
> 20230407

接口正常，请按文档说明操作

**Comment by AKAKayLiu** [comment]
是按文档里的操作来的，也遇到了同样的报错
stock_fhps_em
    total_pages = int(data_json["result"]["pages"])
TypeError: 'NoneType' object is not subscriptable
