### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by SYGOwner** [akfamily/akshare#3653]
我在使用 index_stock_cons(symbol="399006")这个接口时遇到了问题，具体的问题是在尝试获取某些指数（当前已知的有000016, 000688，399006）的成分股列表时报错了。具体报错的信息在下方截图。

![1](https://user-images.githubusercontent.com/91171150/230608606-3963aa6e-8f84-455f-9ba3-a47ab2e12dd8.jpeg)

**Comment by jindaxiang** [comment]
> 000688

感谢反馈问题；已修复该问题，升级到 AKShare 1.9.48 使用
