### ISSUE TITLE
东方财富分红配送数据有大量错误的数据

### ISSUE THREAD

**Issue by eshion** [akfamily/akshare#3656]
ak.stock_fhps_em接口获取的东方财富分红数据存在大量错误数据：
比如：
东方财富：
https://data.eastmoney.com/yjfp/detail/603444.html
<img width="890" alt="image" src="https://user-images.githubusercontent.com/1287467/230725244-bf847a37-08ba-4ed7-87b2-093d42abd2a1.png">
同花顺：
http://basic.10jqka.com.cn/new/603444/bonus.html
<img width="921" alt="image" src="https://user-images.githubusercontent.com/1287467/230725277-a065d812-ae1c-4259-8028-6fa026baebe1.png">
同花顺的数据是正确的，而东方财富缺少三季报的分红数据。希望作者大佬能加上同花顺的分红数据接口。谢谢

**Comment by jindaxiang** [comment]
> ak.stock_fhps_em接口获取的东方财富分红数据存在大量错误数据： 比如： 东方财富： https://data.eastmoney.com/yjfp/detail/603444.html <img alt="image" width="890" src="https://user-images.githubusercontent.com/1287467/230725244-bf847a37-08ba-4ed7-87b2-093d42abd2a1.png"> 同花顺： http://basic.10jqka.com.cn/new/603444/bonus.html <img alt="image" width="921" src="https://user-images.githubusercontent.com/1287467/230725277-a065d812-ae1c-4259-8028-6fa026baebe1.png"> 同花顺的数据是正确的，而东方财富缺少三季报的分红数据。希望作者大佬能加上同花顺的分红数据接口。谢谢

感谢反馈问题；已新增 stock_fhps_detail_ths 接口，升级到 AKShare 1.9.45 版本使用
