### ISSUE TITLE
接口失效

### ISSUE THREAD

**Issue by wabbaf** [akfamily/akshare#3665]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
ak.stock_a_ttm_lyr()
ak.stock_a_all_pb()
以上两个接口失效

1. 操作系统版本 macOS 13.2.1
2. Python 版本 3.11
3. AKShare 版本 1.9.48
4. 接口的名称和代码  
ak.stock_a_ttm_lyr()
ak.stock_a_all_pb()
6. 接口报错的截图或代码
![Xnip2023-04-11_00-13-15](https://user-images.githubusercontent.com/30892328/230944435-9386e209-138e-423e-8700-844ce29be23a.png)
![Xnip2023-04-11_00-19-21](https://user-images.githubusercontent.com/30892328/230944548-ecc5ece1-9a49-4b63-8a9b-e4197ba4264e.png)

8. 期望获得的正确结果

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> **描述遇到的问题** ak.stock_a_ttm_lyr() ak.stock_a_all_pb() 以上两个接口失效
> 
> 1. 操作系统版本 macOS 13.2.1
> 2. Python 版本 3.11
> 3. AKShare 版本 1.9.48
> 4. 接口的名称和代码
>    ak.stock_a_ttm_lyr()
>    ak.stock_a_all_pb()
> 5. 接口报错的截图或代码
>    ![Xnip2023-04-11_00-13-15](https://user-images.githubusercontent.com/30892328/230944435-9386e209-138e-423e-8700-844ce29be23a.png)
>    ![Xnip2023-04-11_00-19-21](https://user-images.githubusercontent.com/30892328/230944548-ecc5ece1-9a49-4b63-8a9b-e4197ba4264e.png)
> 6. 期望获得的正确结果

感谢反馈问题；已修复该问题，升级到 AKShare 1.9.50 使用
