### ISSUE TITLE
兼容pandas 2.0更新：DataFrame/Series append方法移除

### ISSUE THREAD

**Issue by TrayWang** [akfamily/akshare#3679]
pandas2.0以后，移除了DataFrame/Series append方法
Removed deprecated Series.append(), DataFrame.append(), use concat() instead  [GH35407]
http://pandas.pydata.org/docs/whatsnew/v2.0.0.html#backwards-incompatible-api-changes

导致调用函数ak.get_cffex_rank_table报错，具体如下：

![1681563731933](https://user-images.githubusercontent.com/25060116/232225477-509f0f8b-43ac-4fa8-9788-19a1fd5ba779.png)

**Comment by jindaxiang** [comment]
> pandas2.0以后，移除了DataFrame/Series append方法 Removed deprecated Series.append(), DataFrame.append(), use concat() instead [GH35407] http://pandas.pydata.org/docs/whatsnew/v2.0.0.html#backwards-incompatible-api-changes
> 
> 导致调用函数ak.get_cffex_rank_table报错，具体如下：
> 
> ![1681563731933](https://user-images.githubusercontent.com/25060116/232225477-509f0f8b-43ac-4fa8-9788-19a1fd5ba779.png)

感谢反馈问题；已修复该问题，升级到 AKShare 1.9.54 使用
