### ISSUE TITLE
AKShare 接口问题报告(stock_board_concept_cons_ths)

### ISSUE THREAD

**Issue by ycdm** [akfamily/akshare#3680]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本:win10 
2. Python 版本:Python 3.11.2
3. AKShare 版本:当前的 AKTools 版本为：0.0.83，AKShare 版本为：1.9.53
4. 接口的名称和代码:http://localhost:8080/api/public/stock_board_concept_cons_ths?symbol=小米概念
6. 接口报错的截图或代码
![image](https://user-images.githubusercontent.com/8018446/232290785-df441b99-1a97-4fc5-a53c-04215a2bf08a.png)

8. 期望获得的正确结果
最后一组json是有问题的，应该去掉：
 {
    "序号": "暂无成份股数据",
    "代码": "暂无成份股数据",
    "名称": "暂无成份股数据",
    "现价": "暂无成份股数据",
    "涨跌幅": "暂无成份股数据",
    "涨跌": "暂无成份股数据",
    "涨速": "暂无成份股数据",
    "换手": "暂无成份股数据",
    "量比": "暂无成份股数据",
    "振幅": "暂无成份股数据",
    "成交额": "暂无成份股数据",
    "流通股": "暂无成份股数据",
    "流通市值": "暂无成份股数据",
    "市盈率": "暂无成份股数据"
  }

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本:win10
> 2. Python 版本:Python 3.11.2
> 3. AKShare 版本:当前的 AKTools 版本为：0.0.83，AKShare 版本为：1.9.53
> 4. 接口的名称和代码:[http://localhost:8080/api/public/stock_board_concept_cons_ths?symbol=小米概念](http://localhost:8080/api/public/stock_board_concept_cons_ths?symbol=%E5%B0%8F%E7%B1%B3%E6%A6%82%E5%BF%B5)
> 5. 接口报错的截图或代码
>    ![image](https://user-images.githubusercontent.com/8018446/232290785-df441b99-1a97-4fc5-a53c-04215a2bf08a.png)
> 6. 期望获得的正确结果
>    最后一组json是有问题的，应该去掉：
>    {
>    "序号": "暂无成份股数据",
>    "代码": "暂无成份股数据",
>    "名称": "暂无成份股数据",
>    "现价": "暂无成份股数据",
>    "涨跌幅": "暂无成份股数据",
>    "涨跌": "暂无成份股数据",
>    "涨速": "暂无成份股数据",
>    "换手": "暂无成份股数据",
>    "量比": "暂无成份股数据",
>    "振幅": "暂无成份股数据",
>    "成交额": "暂无成份股数据",
>    "流通股": "暂无成份股数据",
>    "流通市值": "暂无成份股数据",
>    "市盈率": "暂无成份股数据"
>    }

感谢反馈问题；已修复该问题，升级到 AKShare 1.9.54 使用
