### ISSUE TITLE
是否考虑将输出的参数名称转化为英文？

### ISSUE THREAD

**Issue by phil9000** [akfamily/akshare#3682]
最近在使用数据接口的时候，发现股票行情输出后列标题都是中文，无法通过mplfinance中的函数进行计算构图，请问是否有考虑将输出的行情数据标题以英文为表头，中文为解释说明？

**Comment by jindaxiang** [comment]
> 最近在使用数据接口的时候，发现股票行情输出后列标题都是中文，无法通过mplfinance中的函数进行计算构图，请问是否有考虑将输出的行情数据标题以英文为表头，中文为解释说明？

有考虑过，但是考虑到实际情况，很多字难以找到合适的翻译，还有就是难以和数据源对应；
mplfinance 绘图可以在本地设置中文字体后使用即可！
