### ISSUE TITLE
AKShare 接口问题报告：stock_lhb_detail_em接口返回数据不全

### ISSUE THREAD

**Issue by xnw176** [akfamily/akshare#3685]
**描述遇到的问题**
1. 操作系统版本： MAC OS
2. Python 版本： 3.8
3. AKShare 版本： 最新
4. 接口的名称和代码： stock_lhb_detail_em
5. 接口报错的截图或代码
指定时间段返回多日数据时字段缺失。
网页字段截图
<img width="1212" alt="image" src="https://user-images.githubusercontent.com/82297022/232454039-93ac63d7-afcb-4b13-bc01-4c7dce76fb93.png">
接口返回字段截图
<img width="1089" alt="image" src="https://user-images.githubusercontent.com/82297022/232454296-5dc323b3-b006-4bd5-b3af-25616d8bfecd.png">
缺少上榜日以及上榜后涨跌等数据

请求添加～

**Comment by jindaxiang** [comment]
> **描述遇到的问题**
> 
> 1. 操作系统版本： MAC OS
> 2. Python 版本： 3.8
> 3. AKShare 版本： 最新
> 4. 接口的名称和代码： stock_lhb_detail_em
> 5. 接口报错的截图或代码
>    指定时间段返回多日数据时字段缺失。
>    网页字段截图
> 
> <img alt="image" width="1212" src="https://user-images.githubusercontent.com/82297022/232454039-93ac63d7-afcb-4b13-bc01-4c7dce76fb93.png">
> 
> 接口返回字段截图
> <img alt="image" width="1089" src="https://user-images.githubusercontent.com/82297022/232454296-5dc323b3-b006-4bd5-b3af-25616d8bfecd.png">
> 
> 缺少上榜日以及上榜后涨跌等数据
> 请求添加～

感谢反馈问题，已修复该问题，升级到 AKShare 1.9.57 使用
