### ISSUE TITLE
get_receipt获取上期所和能源所仓单数据失败

### ISSUE THREAD

**Issue by choir2001** [akfamily/akshare#3686]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本 win10
2. Python 版本 3.9.7
3. AKShare 版本 1.9.55
4. 接口的名称和代码
get_receipt
ak_data=akshare.get_receipt(start_day='20230411', end_day='20230411', vars_list=['LU'])
上期所和能源所的品种，全部链接失败。其他交易所都正常。

6. 接口报错的截图或代码
2023-04-11
第1次链接失败, 最多尝试 20 次
第2次链接失败, 最多尝试 20 次
.......
ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

8. 这个接口上周还可以用，今天不行了。get_receipt链接的上期所原始URL，用EDGE浏览器可以访问，但爬虫就失败。

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本 win10
> 2. Python 版本 3.9.7
> 3. AKShare 版本 1.9.55
> 4. 接口的名称和代码
>    get_receipt
>    ak_data=akshare.get_receipt(start_day='20230411', end_day='20230411', vars_list=['LU'])
>    上期所和能源所的品种，全部链接失败。其他交易所都正常。
> 5. 接口报错的截图或代码
>    2023-04-11
>    第1次链接失败, 最多尝试 20 次
>    第2次链接失败, 最多尝试 20 次
>    .......
>    ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
> 6. 这个接口上周还可以用，今天不行了。get_receipt链接的上期所原始URL，用EDGE浏览器可以访问，但爬虫就失败。

感谢反馈问题，已修复该问题，升级到 AKShare 1.9.57 使用
