### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by The-timing** [akfamily/akshare#3689]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本 
2. Python 版本``` python3```
3. AKShare 版本```aktools:1.8.95```
4. 接口的名称和代码
```
curl http://127.0.0.1:8111/api/public/stock_individual_info_em?symbol=000001
```
5. 接口报错的截图或代码
```
Internal Server Error
```
6. 期望获得的正确结果

**Comment by jindaxiang** [comment]
> stock_individual_info_em

接口可以正常使用，建议查看下本地的运行环境
