### ISSUE TITLE
stock_zt_pool_dtgc_em 接口返回为空

### ISSUE THREAD

**Issue by Loovelj** [akfamily/akshare#3691]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本 liunx 
2. Python 版本 3.8
3. AKShare 版本 akshare==1.9.57
4. 接口的名称和代码
```python
>>> data = ak.stock_zt_pool_dtgc_em(date='20230418')
>>> data
Empty DataFrame
Columns: []
Index: []
```
6. 接口报错的截图或代码
7. 期望获得的正确结果

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本 liunx
> 2. Python 版本 3.8
> 3. AKShare 版本 akshare==1.9.57
> 4. 接口的名称和代码
> 
> ```python
> >>> data = ak.stock_zt_pool_dtgc_em(date='20230418')
> >>> data
> Empty DataFrame
> Columns: []
> Index: []
> ```
> 
> 6. 接口报错的截图或代码
> 7. 期望获得的正确结果

接口正常；应该是数据源的问题
