### ISSUE TITLE
ak.index_stock_cons(symbol=‘000849’) 接口报错

### ISSUE THREAD

**Issue by SYGOwner** [akfamily/akshare#3698]
在调用 ak.index_stock_cons(symbol=‘000849’)这个接口时发生了错误。
有些品种代码通过这个接口可以获得成分股数据，但是有一些例如000849不行。我的python跟akshare都update到最新版本了。

![image](https://user-images.githubusercontent.com/91171150/233647972-60eb67ac-377f-421f-9909-f9d3cf7a09ee.png)

**Comment by jindaxiang** [comment]
> index_stock_cons

数据源没有该指数的数据
