### ISSUE TITLE
请问大佬是否可增加同花顺的查公司资料接口，谢谢

### ISSUE THREAD

**Issue by eshion** [akfamily/akshare#3699]
http://basic.10jqka.com.cn/176/HK0700/company.html

<img width="919" alt="image" src="https://user-images.githubusercontent.com/1287467/233754952-d37e2194-ee74-4f65-b0ef-21bc4e6749ce.png">

**Comment by jindaxiang** [comment]
> http://basic.10jqka.com.cn/176/HK0700/company.html
> 
> <img alt="image" width="919" src="https://user-images.githubusercontent.com/1287467/233754952-d37e2194-ee74-4f65-b0ef-21bc4e6749ce.png">

已有相关其他数据源的接口
