### ISSUE TITLE
希望大佬增加同花顺港股的分红接口

### ISSUE THREAD

**Issue by eshion** [akfamily/akshare#3700]
http://stockpage.10jqka.com.cn/HK0700/bonus/#bonus

谢谢大佬

**Comment by jindaxiang** [comment]
> http://stockpage.10jqka.com.cn/HK0700/bonus/#bonus
> 
> 谢谢大佬

新增 stock_hk_fhpx_detail_ths 接口，升级到 AKShare 1.9.60 使用
