### ISSUE TITLE
stock_a_indicator_lg()接口获取单个公司失败

### ISSUE THREAD

**Issue by tianhaisuifeng** [akfamily/akshare#3711]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
stock_a_indicator_lg()接口获取单个公司失败
修改建议：
把**get_cookie_csrf(url=f"https://legulegu.com/s/{symbol}")修改为：
**get_cookie_csrf(url = f"https://legulegu.com"),

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> **描述遇到的问题** stock_a_indicator_lg()接口获取单个公司失败 修改建议： 把**get_cookie_csrf(url=f"[https://legulegu.com/s/{symbol}")修改为：](https://legulegu.com/s/%7Bsymbol%7D%22)%E4%BF%AE%E6%94%B9%E4%B8%BA%EF%BC%9A) **get_cookie_csrf(url = f"https://legulegu.com"),

感谢反馈问题；已修复改问题，升级到 AKShare 1.9.64 使用
