### ISSUE TITLE
可转债周频、月频接口

### ISSUE THREAD

**Issue by shoarh** [akfamily/akshare#3716]
大佬，能否增加可转债周频、月频的接口。

还有就是同花顺的行业版块数据（每个版块的月频、周频、日频、分钟级别的）

**Comment by jindaxiang** [comment]
> 大佬，能否增加可转债周频、月频的接口。
> 
> 还有就是同花顺的行业版块数据（每个版块的月频、周频、日频、分钟级别的）

在获取日频率数据后在本地处理即可
