### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by xiaodongwei** [akfamily/akshare#3727]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```
1、windows10
2、python3.8
3、akshare1.9.65
4、ak.stock_szse_sector_summary
import akshare as ak

stock_szse_sector_summary_df = ak.stock_szse_sector_summary()
print(stock_szse_sector_summary_df)
 5、
  File D:\ProgramData\Anaconda3\lib\site-packages\akshare\stock\stock_summary.py:98 in stock_szse_sector_summary
    tags_list = soup.find_all("div", attrs={"class": "g-container"})[4].find_all(

IndexError: list index out of range   
**描述遇到的问题**
1. 操作系统版本
2. Python 版本
3. AKShare 版本
4. 接口的名称和代码
5. 接口报错的截图或代码
6. 期望获得的正确结果

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> 1、windows10 2、python3.8 3、akshare1.9.65 4、ak.stock_szse_sector_summary import akshare as ak
> 
> stock_szse_sector_summary_df = ak.stock_szse_sector_summary() print(stock_szse_sector_summary_df) 5、 File D:\ProgramData\Anaconda3\lib\site-packages\akshare\stock\stock_summary.py:98 in stock_szse_sector_summary tags_list = soup.find_all("div", attrs={"class": "g-container"})[4].find_all(
> 
> IndexError: list index out of range **描述遇到的问题**
> 
> 1. 操作系统版本
> 2. Python 版本
> 3. AKShare 版本
> 4. 接口的名称和代码
> 5. 接口报错的截图或代码
> 6. 期望获得的正确结果

感谢反馈问题，已修复该问题，升级到 AKShare 1.9.70 实用
