### ISSUE TITLE
希望作者大佬能增加同花顺的财务分析数据

### ISSUE THREAD

**Issue by eshion** [akfamily/akshare#3731]
如题，虽然有同类的接口，但这些接口返回的数据并没有“扣非净利润同比增长率”这些比较关键的内容，经过搜寻发现，同花顺提供了比较全的财务分析数据，链接如下：

https://basic.10jqka.com.cn/new/000063/finance.html

<img width="570" alt="image" src="https://user-images.githubusercontent.com/1287467/235922283-1c6671db-062b-4ee2-b4d3-36e7a7867d9d.png">

盼望作者大佬可以增加上。谢谢🙏

**Comment by jindaxiang** [comment]
> 如题，虽然有同类的接口，但这些接口返回的数据并没有“扣非净利润同比增长率”这些比较关键的内容，经过搜寻发现，同花顺提供了比较全的财务分析数据，链接如下：
> 
> https://basic.10jqka.com.cn/new/000063/finance.html
> 
> <img alt="image" width="570" src="https://user-images.githubusercontent.com/1287467/235922283-1c6671db-062b-4ee2-b4d3-36e7a7867d9d.png">
> 
> 盼望作者大佬可以增加上。谢谢🙏

已新增 stock_financial_abstract_ths 接口，升级到 AKShare 1.9.91 版本使用
