### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by dengsong666** [akfamily/akshare#3735]
stock_zh_index_spot 指数实时的这个获取的数据有些中证指数没有，看了一下只包括001或者399开头的？能添加支持其他的吗？

**Comment by jindaxiang** [comment]
> stock_zh_index_spot

目前该接口仅支持新浪财经提供的数据

**Comment by dengsong666** [comment]
那能加个指数实时数据的接口吗？可以用东方财富这个 http://push2.eastmoney.com/api/qt/stock/get?invt=2&fltt=1&cb=jQuery35109106980659231783_1683277552610&fields=f58%2Cf107%2Cf57%2Cf43%2Cf59%2Cf169%2Cf170%2Cf152%2Cf46%2Cf60%2Cf44%2Cf45%2Cf47%2Cf48%2Cf19%2Cf532%2Cf39%2Cf161%2Cf49%2Cf171%2Cf50%2Cf86%2Cf600%2Cf601%2Cf154%2Cf84%2Cf85%2Cf168%2Cf108%2Cf116%2Cf167%2Cf164%2Cf92%2Cf71%2Cf117%2Cf292%2Cf113%2Cf114%2Cf115%2Cf119%2Cf120%2Cf121%2Cf122%2Cf296&secid=2.930875&ut=fa5fd1943c7b386f172d6893dbfba10b&wbp2u=%7C0%7C0%7C0%7Cweb&_=1683277552611
