### ISSUE TITLE
"stock_individual_fund_flow_rank" cann't work

### ISSUE THREAD

**Issue by Frankpython** [akfamily/akshare#3742]
the following code cann't work:
import akshare as ak
ddf = ak.stock_individual_fund_flow_rank()

the error message is:
"JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 1263019 (char 1263018)"

this error occured from 5 May.

Thanks!

**Comment by jindaxiang** [comment]
> the following code cann't work: import akshare as ak ddf = ak.stock_individual_fund_flow_rank()
> 
> the error message is: "JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 1263019 (char 1263018)"
> 
> this error occured from 5 May.
> 
> Thanks!

目前接口正常
