### ISSUE TITLE
希望大佬增加恒生指数和恒生科技指数的接口。

### ISSUE THREAD

**Issue by zwing1201** [akfamily/akshare#3752]
akshare库的版本1.9.76
A股指数有stock_zh_index_spot, stock_zh_index_daily 接口，但是没有找到获取港股市场指数的 类似stock_hk_index_spot, stock_hk_index_daily 的接口。希望作者大佬有空支持下。

**Comment by jindaxiang** [comment]
> akshare库的版本1.9.76 A股指数有stock_zh_index_spot, stock_zh_index_daily 接口，但是没有找到获取港股市场指数的 类似stock_hk_index_spot, stock_hk_index_daily 的接口。希望作者大佬有空支持下。

感谢反馈问题；已新增 stock_hk_index_spot_sina, stock_hk_index_daily_em, stock_hk_index_spot_em, stock_hk_index_daily_sina 等接口，升级到 AKShare 1.9.81 使用
