### ISSUE TITLE
fund_etf_hist_min_em 接口失效

### ISSUE THREAD

**Issue by QingPing1** [akfamily/akshare#3753]
fund_etf_hist_min_em_df = ak.fund_etf_hist_min_em(symbol="513500", period="1", adjust="", start_date="2023-01-01 09:32:00", end_date="2023-01-04 14:40:00",)
print(fund_etf_hist_min_em_df)
fund_etf_hist_min_em运行此语句时报错，“AttributeError: module 'akshare' has no attribute 'fund_etf_hist_min_em'”提示akshare中没有fund_etf_hist_min_em_df 属性。能帮忙解决吗？
主要是想下载场内ETF分钟数据。

**Comment by jindaxiang** [comment]
> fund_etf_hist_min_em

接口正常，按文档操作即可
