### ISSUE TITLE
stock_hot_rank_wc()接口失效

### ISSUE THREAD

**Issue by tianhaisuifeng** [akfamily/akshare#3754]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
stock_hot_rank_wc()接口失效，request返回结果：组件不存在：
{'status_code': '-8302', 'status_msg': '组件不存在', 'trace_id': '63bb86216ccc1e9503c6ddacb4cfcdc6', 'uniqid': '63bb86216ccc1e9503c6ddacb4cfcdc6'}

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> **描述遇到的问题** stock_hot_rank_wc()接口失效，request返回结果：组件不存在： {'status_code': '-8302', 'status_msg': '组件不存在', 'trace_id': '63bb86216ccc1e9503c6ddacb4cfcdc6', 'uniqid': '63bb86216ccc1e9503c6ddacb4cfcdc6'}

已修复，升级到 AKShare 1.9.79 使用

**Comment by tianhaisuifeng** [comment]
@jindaxiang 非常感谢！
想问一下，url = "https://www.iwencai.com/gateway/urp/v7/landing/getDataList"这个链接是从哪获取的呢？
还有comp_id和uuid这两个参数
