### ISSUE TITLE
希望作者丰富个股资金流接口stock_individual_fund_flow的调用

### ISSUE THREAD

**Issue by jaryvan** [akfamily/akshare#3758]
1.本接口单次只能返回近一百条数据，若想使用过去几年的数据将没办法实现，希望可以新增时间参数start_date和end_date，以实现在此时间范围内的资金流向数据。
2.希望可以新增trade_date参数获取该交易日所有stock的资金流向数据，其中trader_date和stock二选一，望采纳

**Comment by jindaxiang** [comment]
> 1.本接口单次只能返回近一百条数据，若想使用过去几年的数据将没办法实现，希望可以新增时间参数start_date和end_date，以实现在此时间范围内的资金流向数据。 2.希望可以新增trade_date参数获取该交易日所有stock的资金流向数据，其中trader_date和stock二选一，望采纳

good idea！
