### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by ahren001** [akfamily/akshare#3763]
ak.futures_zh_spot(symbol='RB2310', market="CF", adjust='0')，
报错，IndexError    Traceback (most recent call last)
Input In [31], in <cell line: 3>()
      1 import akshare as ak
----> 3 futures_zh_spot_df = ak.futures_zh_spot(symbol='rb2310', market="CF", adjust='0')
      4 print(futures_zh_spot_df)

File C:\vnstation\lib\site-packages\akshare\futures\futures_zh_sina.py:238, in futures_zh_spot(symbol, market, adjust)
    225 headers = {
    226     "Accept": "*/*",
    227     "Accept-Encoding": "gzip, deflate",
   (...)
    234     "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36",
    235 }
    236 r = requests.get(url, headers=headers)
    237 data_df = pd.DataFrame(
--> 238     [
    239         item.strip().split("=")[1].split(",")
    240         for item in r.text.split(";")
    241         if item.strip() != ""
    242     ]
    243 )
    244 data_df.iloc[:, 0] = data_df.iloc[:, 0].str.replace('"', "")
    245 data_df.iloc[:, -1] = data_df.iloc[:, -1].str.replace('"', "")

File C:\vnstation\lib\site-packages\akshare\futures\futures_zh_sina.py:239, in <listcomp>(.0)
    225 headers = {
    226     "Accept": "*/*",
    227     "Accept-Encoding": "gzip, deflate",
   (...)
    234     "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36",
    235 }
    236 r = requests.get(url, headers=headers)
    237 data_df = pd.DataFrame(
    238     [
--> 239         item.strip().split("=")[1].split(",")
    240         for item in r.text.split(";")
    241         if item.strip() != ""
    242     ]
    243 )
    244 data_df.iloc[:, 0] = data_df.iloc[:, 0].str.replace('"', "")
    245 data_df.iloc[:, -1] = data_df.iloc[:, -1].str.replace('"', "")

IndexError: list index out of range

**Comment by jindaxiang** [comment]
> ak.futures_zh_spot(symbol='RB2310', market="CF", adjust='0')，

接口正常

**Comment by ahren001** [comment]
这问题出在那儿啊，索引超出范围；卸载重装akshare也没用
