### ISSUE TITLE
咨询下，东方财富的千股千评是否有完整的历史数据

### ISSUE THREAD

**Issue by KittenCN** [akfamily/akshare#3765]
我正在做一个基于神经网络的预测算法，想多加入一些评判的因子，所以咨询下，东方财富的千股千评是否有完整的历史数据？目前接口返回的大概是最近三四十个交易日的数据

**Comment by jindaxiang** [comment]
> 我正在做一个基于神经网络的预测算法，想多加入一些评判的因子，所以咨询下，东方财富的千股千评是否有完整的历史数据？目前接口返回的大概是最近三四十个交易日的数据

没有的
