### ISSUE TITLE
ak.stock_hk_fhpx_detail_ths 接口问题报告

### ISSUE THREAD

**Issue by eshion** [akfamily/akshare#3773]
正常数据：
http://stockpage.10jqka.com.cn/HK0968/bonus/
<img width="901" alt="image" src="https://github.com/akfamily/akshare/assets/1287467/4c0c567a-305e-4a6c-a60c-73d6856c3d29">

接口返回数据：
ak.stock_hk_fhpx_detail_ths(symbol='0968')
<img width="1195" alt="image" src="https://github.com/akfamily/akshare/assets/1287467/e19bff51-4d1c-4232-937c-9f63d8203fbf">

**Comment by jindaxiang** [comment]
> 正常数据： http://stockpage.10jqka.com.cn/HK0968/bonus/ <img alt="image" width="901" src="https://user-images.githubusercontent.com/1287467/238612078-4c0c567a-305e-4a6c-a60c-73d6856c3d29.png">
> 
> 接口返回数据： ak.stock_hk_fhpx_detail_ths(symbol='0968') <img alt="image" width="1195" src="https://user-images.githubusercontent.com/1287467/238612461-e19bff51-4d1c-4232-937c-9f63d8203fbf.png">

感谢反馈问题；已修复该问题，升级到 AKShare 1.9.84 版本使用
