### ISSUE TITLE
import failed in multiple user server

### ISSUE THREAD

**Issue by Naich** [akfamily/akshare#3776]
only first user could use akshare because of  /tmp/ak_cache.sqlite permission.

https://github.com/akfamily/akshare/blob/224d71ca63a208752ade487aabeb27c670d71e10/akshare/utils/ak_session.py#LL13C1-L13C84

maybe should set use_cache_dir=True?

**Comment by jindaxiang** [comment]
> only first user could use akshare because of /tmp/ak_cache.sqlite permission.
> 
> https://github.com/akfamily/akshare/blob/224d71ca63a208752ade487aabeb27c670d71e10/akshare/utils/ak_session.py#LL13C1-L13C84
> 
> maybe should set use_cache_dir=True?

Thanks for your issue, we have fixed it, please update AKShare to 1.9.86 version
