### ISSUE TITLE
函数sw_index_daily_indicator 请求受限

### ISSUE THREAD

**Issue by waaaaaaz** [akfamily/akshare#3779]
函数sw_index_daily_indicator 请求受限

返回 ：
<html><head><title>访问禁止</title><style type="text/css">p{color:#666;FONT-SIZE:12pt}A{TEXT-DECORATION:none}</style></head><body topmargin="50"><table align="center" border="0" cellspacing="0" cepadding="0" width="600"><tbody><tr><td><p><b>访问禁止</b></p><hr noshade="" size="0"/><p style="height:9px">☉ 确保浏览器的地址栏中的地址拼写和格式正确无误；</p><p style="height:9px;">☉ 单击<a href="javascript:history.back(1)">后退</a>返回上一页；</p><p style="height:9px;margin:0 0 30px 0">☉ 如有任何疑问，请与管理员联系。</p><hr noshade="" size="0"/><p style="height:9px;"><a href="#" onclick="javascript:var od=document.getElementById('d');od.style.display=='none'?od.style.display='': od.style.display='none';">☉ 详细&gt;&gt;</a></p><p id="d" style="display:none">检测到可疑访问，事件编号：202305181400786500   </p></td></tr></tbody></table></body></html>

**Comment by jindaxiang** [comment]
> sw_index_daily_indicator

看文档说明
