### ISSUE TITLE
The symbol error when using 'ak.stock_zh_a_daily' function

### ISSUE THREAD

**Issue by FtoPayRespec** [akfamily/akshare#3783]
**Describe the bug**
When using ak.stock_zh_a_daily() function to get the history data of a stock, occur error **KeyError: 'sz002008'**.
The error shows like:
```python
Traceback (most recent call last):
  File "C:\Users\liu11\PycharmProjects\stockTrading\reptile\reptile.py", line 134, in <module>
    stock_zh_a_daily_qfq_df = ak.stock_zh_a_hist(symbol="sz002008", start_date="20120101", end_date="20230510")
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\liu11\PycharmProjects\stockTrading\venv\Lib\site-packages\akshare\stock_feature\stock_hist_em.py", line 1022, in stock_zh_a_hist
    "secid": f"{code_id_dict[symbol]}.{symbol}",
                ~~~~~~~~~~~~^^^^^^^^
KeyError: 'sz002008'
```

**To Reproduce**
1. Use `ak.stock_zh_a_spot()` to get stock id. In this case, it returns **sz002008** for me.
![3](https://github.com/akfamily/akshare/assets/116171159/4bfb12f2-df41-4b12-8c88-9d1f2013549d)

![1](https://github.com/akfamily/akshare/assets/116171159/44dfe3ec-5e63-40fb-9468-74425e8f5fe1)
2. Use a statement `stock_zh_a_daily_qfq_df = ak.stock_zh_a_hist(symbol="sz002008", start_date="20120101", end_date="20230510")` to get historical data.
![4](https://github.com/akfamily/akshare/assets/116171159/848cbb8c-0680-4cf1-bf42-aab06911f93c)
3. See error.

**Expected behavior**
It should return the correct historical data for me.

**Screenshots**
I trace the error that comes from file `stock_hist_em.py`, line 1016. The problem occurred by the wrong param of **symbol** inside the statement.
![2](https://github.com/akfamily/akshare/assets/116171159/34982fae-7004-46e8-9118-4d96590fcc4a)

Then I noticed that the symbol it needs is only the pure stock code like **002008** rather than **sz002008** which comes from `ak.stock_zh_a_spot()`.
After changing the symbol as `ak.stock_zh_a_hist(symbol="002008", start_date="20120101", end_date="20230510")`, the code is running functionality.
Because of these reasons, I recommend author of guide book fix the content in section **历史行情数据-新浪**.

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - Browser: Chrome
 - Version 113.0.5672.126

**Comment by jindaxiang** [comment]
> stock_zh_a_hist

Thanks for your issue, please pay attention to "stock_zh_a_hist" and "stock_zh_a_daily"
