### ISSUE TITLE
AKShare 接口问题报告-新浪财经财务报表关键指标存在数据缺失

### ISSUE THREAD

**Issue by eshion** [akfamily/akshare#3785]
ak. stock_financial_abstract接口获取的新浪财经-财务报表-关键指标的数据
比如：
新浪财经:
https://vip.stock.finance.sina.com.cn/corp/go.php/vFD_FinanceSummary/stockid/600015.phtml
<img width="850" alt="image" src="https://github.com/akfamily/akshare/assets/1287467/96edec3e-3227-4c4d-8202-909eef7af005">

同花顺：
https://basic.10jqka.com.cn/new/600015/finance.html
<img width="983" alt="image" src="https://github.com/akfamily/akshare/assets/1287467/eab606e6-6200-47e1-aff7-b0e7ce965114">

同花顺的数据是正确的，而新浪财经某些数据缺失。希望作者大佬能加上同花顺的财务指标接口。谢谢

**Comment by jindaxiang** [comment]
> ak. stock_financial_abstract接口获取的新浪财经-财务报表-关键指标的数据 比如： 新浪财经: https://vip.stock.finance.sina.com.cn/corp/go.php/vFD_FinanceSummary/stockid/600015.phtml <img alt="image" width="850" src="https://user-images.githubusercontent.com/1287467/239455167-96edec3e-3227-4c4d-8202-909eef7af005.png">
> 
> 同花顺： https://basic.10jqka.com.cn/new/600015/finance.html <img alt="image" width="983" src="https://user-images.githubusercontent.com/1287467/239455255-eab606e6-6200-47e1-aff7-b0e7ce965114.png">
> 
> 同花顺的数据是正确的，而新浪财经某些数据缺失。希望作者大佬能加上同花顺的财务指标接口。谢谢

已新增 stock_financial_abstract_ths 接口，升级到 AKShare 1.9.91 版本使用
