### ISSUE TITLE
大佬好，还麻烦新增对于苹果M2 Max的支持，感谢

### ISSUE THREAD

**Issue by KissAngeles** [akfamily/akshare#3789]
1、简述：
苹果M2 Max下执行ak.stock_zh_a_hist报错且按照https://akshare.akfamily.xyz/installation.html的libmini_racer.dylib解决方案未生效

2、前置：
平台：苹果M2 Max
环境：Docker Desktop 4.19.0 (106363) 
镜像：jupyter/scipy-notebook:2023-02-28
akshare版本：akshare-1.9.81

3、步骤：
首先在苹果M2 Max平台上安装docker
然后拉取jupyter镜像并pip安装akshare
接下来执行ak.stock_zh_a_hist报错RuntimeError: Native library not available at /opt/conda/lib/python3.10/site-packages/py_mini_racer/libmini_racer.glibc.so**如图1所示**
最后按照https://akshare.akfamily.xyz/installation.html提示将libmini_racer.dylib下载置于/opt/conda/lib/python3.10/site-packages/py_mini_racer/目录下，问题未解决
有尝试各种google之类的，但没有get到可靠的解决方案

4、问题：
还麻烦帮忙看下是否M2 Max同M1之间解决方案不一致，感谢

**图1**
<img width="693" alt="image" src="https://github.com/akfamily/akshare/assets/27079259/e1dd1246-03f9-4e17-9006-1f2a1a439aee">

**Comment by jindaxiang** [comment]
> 1、简述： 苹果M2 Max下执行ak.stock_zh_a_hist报错且按照[https://akshare.akfamily.xyz/installation.html的libmini_racer.dylib解决方案未生效](https://akshare.akfamily.xyz/installation.html%E7%9A%84libmini_racer.dylib%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88%E6%9C%AA%E7%94%9F%E6%95%88)
> 
> 2、前置： 平台：苹果M2 Max 环境：Docker Desktop 4.19.0 (106363) 镜像：jupyter/scipy-notebook:2023-02-28 akshare版本：akshare-1.9.81
> 
> 3、步骤： 首先在苹果M2 Max平台上安装docker 然后拉取jupyter镜像并pip安装akshare 接下来执行ak.stock_zh_a_hist报错RuntimeError: Native library not available at /opt/conda/lib/python3.10/site-packages/py_mini_racer/libmini_racer.glibc.so**如图1所示** 最后按照[https://akshare.akfamily.xyz/installation.html提示将libmini_racer.dylib下载置于/opt/conda/lib/python3.10/site-packages/py_mini_racer/目录下，问题未解决](https://akshare.akfamily.xyz/installation.html%E6%8F%90%E7%A4%BA%E5%B0%86libmini_racer.dylib%E4%B8%8B%E8%BD%BD%E7%BD%AE%E4%BA%8E/opt/conda/lib/python3.10/site-packages/py_mini_racer/%E7%9B%AE%E5%BD%95%E4%B8%8B%EF%BC%8C%E9%97%AE%E9%A2%98%E6%9C%AA%E8%A7%A3%E5%86%B3) 有尝试各种google之类的，但没有get到可靠的解决方案
> 
> 4、问题： 还麻烦帮忙看下是否M2 Max同M1之间解决方案不一致，感谢
> 
> **图1** <img alt="image" width="693" src="https://user-images.githubusercontent.com/27079259/239547936-e1dd1246-03f9-4e17-9006-1f2a1a439aee.png">

需要在本地镜像中进行相关设置，目前设置后是可以正常使用的

**Comment by KissAngeles** [comment]
问题确认已解决，之前一直在和libmini_racer.glibc.so较劲，始终没搞定，后面直接拉取了akshare的docker镜像，该镜像自带了jupyter的环境，很方便大家使用，多谢大佬

docker指令：docker run -it registry.cn-shanghai.aliyuncs.com/akfamily/aktools:jupyter
文档链接：https://akshare.xyz/akdocker/akdocker.html
