### ISSUE TITLE
社会融资规模网站没有更新到最新，建议同步其他经济数据

### ISSUE THREAD

**Issue by snowywhiten** [akfamily/akshare#3791]
1、社会融资规模选择的商务部网站停更了，建议换成国家统计局数据：https://data.stats.gov.cn/easyquery.htm?cn=A01&zb=A0203&sj=202304
2、统计局其他详细经济数据建议也收纳，比如失业率等指标，可参考wind、choice的edb数据库列举的指标：国家统计局数据 https://data.stats.gov.cn/easyquery.htm?cn=A01&zb=A0203&sj=202304

**Comment by albertandking** [comment]
> 1、社会融资规模选择的商务部网站停更了，建议换成国家统计局数据：https://data.stats.gov.cn/easyquery.htm?cn=A01&zb=A0203&sj=202304 2、统计局其他详细经济数据建议也收纳，比如失业率等指标，可参考wind、choice的edb数据库列举的指标：国家统计局数据 https://data.stats.gov.cn/easyquery.htm?cn=A01&zb=A0203&sj=202304

感谢反馈问题；1. 数据是正在更新的 2. 升级到 AKS hare1.10.75 版本，新增 macro_china_urban_unemployment 接口获取
