### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by xiaodongwei** [akfamily/akshare#3797]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```import akshare as ak
#巨潮资讯-个股-公司概况
stock_profile_cninfo_df = ak.stock_profile_cninfo(symbol="600030")
print(stock_profile_cninfo_df)


**描述遇到的问题**
  File D:\QuantStudy\StockQuant\Selected_Stock_datasets\tmptst.py:9
    stock_profile_cninfo_df = ak.stock_profile_cninfo(symbol="600030")

  File D:\Program Files\anaconda\envs\env_streamlit\lib\site-packages\akshare\stock\stock_profile_cninfo.py:107 in stock_profile_cninfo
    count = data_json["count"]

KeyError: 'count'
1. 操作系统版本
windows 10
3. Python 版本
3.8
5. AKShare 版本
1.9.81
7. 接口的名称和代码
import akshare as ak
#巨潮资讯-个股-公司概况
stock_profile_cninfo_df = ak.stock_profile_cninfo(symbol="600030")
print(stock_profile_cninfo_df)

9. 接口报错的截图或代码
10. 期望获得的正确结果

**Comment by jindaxiang** [comment]
> stock_profile_cninfo

该接口暂时不能获取数据

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```import akshare as ak
> #巨潮资讯-个股-公司概况
> stock_profile_cninfo_df = ak.stock_profile_cninfo(symbol="600030")
> print(stock_profile_cninfo_df)
> 
> 
> **描述遇到的问题**
>   File D:\QuantStudy\StockQuant\Selected_Stock_datasets\tmptst.py:9
>     stock_profile_cninfo_df = ak.stock_profile_cninfo(symbol="600030")
> 
>   File D:\Program Files\anaconda\envs\env_streamlit\lib\site-packages\akshare\stock\stock_profile_cninfo.py:107 in stock_profile_cninfo
>     count = data_json["count"]
> 
> KeyError: 'count'
> 1. 操作系统版本
> windows 10
> 3. Python 版本
> 3.8
> 5. AKShare 版本
> 1.9.81
> 7. 接口的名称和代码
> import akshare as ak
> #巨潮资讯-个股-公司概况
> stock_profile_cninfo_df = ak.stock_profile_cninfo(symbol="600030")
> print(stock_profile_cninfo_df)
> 
> 9. 接口报错的截图或代码
> 10. 期望获得的正确结果
> ```

已修复该问题，升级都 AKShare 1.9.97 使用
