### ISSUE TITLE
ak.stock_a_indicator_lg参数异常时不报错，而是返回了数据。

### ISSUE THREAD

**Issue by iamjackie** [akfamily/akshare#3798]
**Describe the bug**
当使用ak.stock_a_indicator_lg(symbol="513100")查询一个不存在的股票代码时（这里查询的是指数基金的代码），不会报错，而是返回一个不知道是谁的数据。任何错误的代码都将获得相同的结果。

**To Reproduce**
当使用ak.stock_a_indicator_lg(symbol="513100")查询一个不存在的股票代码时（这里查询的是指数基金的代码），不会报错，而是返回一个不知道是谁的数据。任何错误的代码都将获得相同的结果。

**Expected behavior**
应该直接报错股票不存在。

**Screenshots**
填入任何不存在的股票代码，无论如何替换代码，获得结果都是相同的。
<img width="747" alt="image" src="https://github.com/akfamily/akshare/assets/21194282/ba002968-3a3a-4109-a0e8-4b9426b9d4ac">
<img width="751" alt="image" src="https://github.com/akfamily/akshare/assets/21194282/19c9503b-fe80-4f78-b755-ae0ab2b31efa">
<img width="782" alt="image" src="https://github.com/akfamily/akshare/assets/21194282/6e893ad4-e308-425a-98f7-066be782e4cf">

**Comment by jindaxiang** [comment]
> **Describe the bug** 当使用ak.stock_a_indicator_lg(symbol="513100")查询一个不存在的股票代码时（这里查询的是指数基金的代码），不会报错，而是返回一个不知道是谁的数据。任何错误的代码都将获得相同的结果。
> 
> **To Reproduce** Steps to reproduce the behavior: 当使用ak.stock_a_indicator_lg(symbol="513100")查询一个不存在的股票代码时（这里查询的是指数基金的代码），不会报错，而是返回一个不知道是谁的数据。任何错误的代码都将获得相同的结果。
> 
> **Expected behavior** 应该直接报错股票不存在。
> 
> **Screenshots** 填入任何不存在的股票代码，无论如何替换代码，获得结果都是相同的。 <img alt="image" width="747" src="https://user-images.githubusercontent.com/21194282/240276098-ba002968-3a3a-4109-a0e8-4b9426b9d4ac.png"> <img alt="image" width="751" src="https://user-images.githubusercontent.com/21194282/240276311-19c9503b-fe80-4f78-b755-ae0ab2b31efa.png"> <img alt="image" width="782" src="https://user-images.githubusercontent.com/21194282/240276450-6e893ad4-e308-425a-98f7-066be782e4cf.png">

感谢反馈问题；已修复该问题，升级到 AKShare 1.9.94 使用
