### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by wg142857** [akfamily/akshare#3809]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本
2. Python 版本
3. AKShare 版本
4. 接口的名称和代码
5. 接口报错的截图或代码
6. 期望获得的正确结果
7. 
stock_hold_control_cninfo接口报错, 请问是后台更新代码了还是?

**Comment by jindaxiang** [comment]
> stock_hold_control_cninfo

升级到最新版使用

**Comment by wg142857** [comment]
已经升级到最新版了, 还是报错啊
akshare                   1.9.81
---------------------------------------
import akshare as ak
stock_hold_control_cninfo_df = ak.stock_hold_control_cninfo(symbol="全部")
print(stock_hold_control_cninfo_df)
-----------------------------------------------------------------
Traceback (most recent call last):
  File "D:\app\spiders\测试.py", line 3, in <module>
    stock_hold_control_cninfo_df = ak.stock_hold_control_cninfo(symbol="全部")
  File "F:\AnacondaEXE\envs\py_STOCK\lib\site-packages\akshare\stock\stock_hold_control_cninfo.py", line 90, in stock_hold_control_cninfo
    temp_df = pd.DataFrame(data_json["records"])
KeyError: 'records'

**Comment by wg142857** [comment]
> > stock_hold_control_cninfo
> 
> 升级到最新版本使用

已经升级到最新版了，还是报错啊
akshare 1.9.81
将 akshare 导入为 ak
stock_hold_control_cninfo_df = ak.stock_hold_control_cninfo(symbol="全部")
print(stock_hold_control_cninfo_df)
回溯（最近调用最后）：
文件“D:\app\spiders\测试.py”，第 3 行，在
stock_hold_control_cninfo_df = ak.stock_hold_control_cninfo(symbol="全部")
文件“F:\AnacondaEXE\envs\py_STOCK\lib \site-packages\akshare\stock\stock_hold_control_cninfo.py", 第 90 行，在 stock_hold_control_cninfo
temp_df = pd.DataFrame(data_json["records"])
KeyError: 'records'

**Comment by wg142857** [comment]
> > stock_hold_control_cninfo
> 
> 升级到最新版本使用

已经升级到最新版了啊, 还是报错啊
版本:
akshare                   1.9.81
-----------------------------------------------------------------
官网代码:
import akshare as ak
stock_hold_control_cninfo_df = ak.stock_hold_control_cninfo(symbol="全部")
print(stock_hold_control_cninfo_df)
-----------------------------------------------------------------
报错信息:
Traceback (most recent call last):
  File "D:\app\spiders\测试.py", line 3, in <module>
    stock_hold_control_cninfo_df = ak.stock_hold_control_cninfo(symbol="全部")
  File "F:\AnacondaEXE\envs\py_STOCK\lib\site-packages\akshare\stock\stock_hold_control_cninfo.py", line 90, in stock_hold_control_cninfo
    temp_df = pd.DataFrame(data_json["records"])
KeyError: 'records'
---------------------------------------------------------------------
