### ISSUE TITLE
申请增加中国出口集装箱运价指数接口

### ISSUE THREAD

**Issue by alvinyangzz** [akfamily/akshare#3814]
中国出口集装箱运价指数（CCFI）https://www.sse.net.cn/index/singleIndex?indexType=ccfi
上海出口集装箱运价指数（SCFI）https://www.sse.net.cn/index/singleIndex?indexType=scfi

**Comment by jindaxiang** [comment]
> 中国出口集装箱运价指数（CCFI）https://www.sse.net.cn/index/singleIndex?indexType=ccfi 上海出口集装箱运价指数（SCFI）https://www.sse.net.cn/index/singleIndex?indexType=scfi

暂无法获取
