### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by leon507** [akfamily/akshare#3821]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1、接口名称：futures_return_index_nh，南华商品指数
代码：
import akshare as ak
futures_return_index_nh_df = ak.futures_return_index_nh(symbol="NHCI")
print(futures_return_index_nh_df)
问题描述：
数据抓取结果，日期与对应的value值不上对应关系，如：5月29日的实际的value值，抓取的结果记录在了5月28日；且抓取的数据与http://www.nanhua.net/nhzc/varietytrend.html，网站上显示的数据会有0.几的偏差

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> **描述遇到的问题** 1、接口名称：futures_return_index_nh，南华商品指数 代码： import akshare as ak futures_return_index_nh_df = ak.futures_return_index_nh(symbol="NHCI") print(futures_return_index_nh_df) 问题描述： 数据抓取结果，日期与对应的value值不上对应关系，如：5月29日的实际的value值，抓取的结果记录在了5月28日；且抓取的数据与[http://www.nanhua.net/nhzc/varietytrend.html，网站上显示的数据会有0.几的偏差](http://www.nanhua.net/nhzc/varietytrend.html%EF%BC%8C%E7%BD%91%E7%AB%99%E4%B8%8A%E6%98%BE%E7%A4%BA%E7%9A%84%E6%95%B0%E6%8D%AE%E4%BC%9A%E6%9C%890.%E5%87%A0%E7%9A%84%E5%81%8F%E5%B7%AE)

感谢反馈问题，已修复该问题，升级到 1.10.4 使用；关于数据差距问题，请留下下是否四舍五入
