### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by mutex86** [akfamily/akshare#3828]
**描述遇到的问题**
1. 操作系统版本：window11
2. Python 版本:3.10.11
3. AKShare 版本:1.10.5
4. 接口的名称和代码:分红送配-东财，ak.stock_fhps_em(date="20230602")
5. 接口报错的截图或代码:报错：‘NoneType’  object is not subsciptable
6. 期望获得的正确结果:当天应该有83个股票发生了分红送配

**Comment by jindaxiang** [comment]
> **描述遇到的问题**
> 
> 1. 操作系统版本：window11
> 2. Python 版本:3.10.11
> 3. AKShare 版本:1.10.5
> 4. 接口的名称和代码:分红送配-东财，ak.stock_fhps_em(date="20230602")
> 5. 接口报错的截图或代码:报错：‘NoneType’  object is not subsciptable
> 6. 期望获得的正确结果:当天应该有83个股票发生了分红送配

请参考文档关于该接口 date 的描述
