### ISSUE TITLE
stock_hk_valuation_baidu 接口报错

### ISSUE THREAD

**Issue by inspirits** [akfamily/akshare#3841]
使用 stock_hk_valuation_baidu 接口，如df = ak.stock_hk_valuation_baidu(symbol='00700', indicator='市盈率(TTM)', period='全部')
返回结果 TypeError: list indices must be integers or slices, not str
打印 getresponse() 的响应为 {'QueryID': '0', 'ResultCode': '403', 'Result': []}

烦请查看，谢谢

**Comment by albertandking** [comment]
> 市盈率(TTM)

可以正常运行；建议升级到最新版使用

**Comment by inspirits** [comment]
你好，我又自己测试了下，python版本全程保持不变，
先把akshare版本升级至最新1.10.9，依然报同样的错
再单独把stock_hk_valuation_baidu文件内容回滚到20230210版本（最新为20230309），还是报同样的错
基于1.10.9版本的akshare包和20230210版本的stock_hk_valuation_baidu文件，在stock_hk_valuation_baidu文件headers中添加User-Agent内容后，运行成功
请问是不是最新版本(20230309)不够完善？

**Comment by albertandking** [comment]
> stock_hk_valuation_baidu

可能是你访问过于频繁，这边测试最新版可以正常运行

**Comment by inspirits** [comment]
hello，我又自查了一番，问题应该是
stock_zh_valuation_baidu.py这个用于A股的文件内容更新了，更新时间是20230417，已改为从gushitong.baidu.com获取数据
但是
stock_hk_valuation_baidu.py这个用于港股的文件内容却没有更新，还是20230309的，依然是从finance.pae.baidu.com获取数据，所以无法获得正确的数据
烦请确认，谢谢

**Comment by albertandking** [comment]
> 市盈率(TTM)

目前可以获取到数据，应该不是你反馈的问题：
![image](https://github.com/akfamily/akshare/assets/18234520/7a84bb58-0924-4aa2-b523-aa281cf13a33)

**Comment by inspirits** [comment]
我现在是把stock_zh_valuation_baidu中的内容copy到stock_hk_valuation_baidu中，把market改成了hk就能正常使用了
既然你那边确认了没问题，那就ok，感谢耐心回复！

**Comment by albertandking** [comment]
> 

之前有一段时间是 hk 的写法，应该百度切换了 api，但是还保留之前的接口；如果数据由不一致欢迎及时反馈
