### ISSUE TITLE
ak.bond_zh_hs_cov_min 接口问题报告

### ISSUE THREAD

**Issue by icecoldsnow1** [akfamily/akshare#3857]
ak.bond_zh_hs_cov_min 接口
可转债分时行情

问题描述：
     5,15,30,60分钟的分时行情时间字段显示只有年月日，显示不出分钟信息
![image](https://github.com/akfamily/akshare/assets/105289905/7f31c895-005f-4916-8db7-d726b7e320ec)

**Comment by albertandking** [comment]
> ak.bond_zh_hs_cov_min 接口 可转债分时行情
> 
> 问题描述： 5,15,30,60分钟的分时行情时间字段显示只有年月日，显示不出分钟信息 ![image](https://user-images.githubusercontent.com/105289905/244620199-7f31c895-005f-4916-8db7-d726b7e320ec.png)

已修复该问题，升级到 AKShare 1.10.16 使用
