### ISSUE TITLE
建议增加个股的实时行情数据

### ISSUE THREAD

**Issue by fr4nkhe** [akfamily/akshare#3868]
建议增加个股的实时行情数据，在东方财富个股详情页可以获取数据
目标url:http://quote.eastmoney.com/sz301320.html
个股参数在path里

**Comment by albertandking** [comment]
> 建议增加个股的实时行情数据，在东方财富个股详情页可以获取数据 目标url:http://quote.eastmoney.com/sz301320.html 个股参数在path里

已有相关接口；详情访问文档
