### ISSUE TITLE
AKShare 接口问题报告 加密货币接口不稳定

### ISSUE THREAD

**Issue by fungaren** [akfamily/akshare#3869]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本 Debian 12
2. Python 版本 3.11.2
3. AKShare 版本 1.10.17
4. 接口的名称和代码

```python
import akshare as ak
df = ak.crypto_name_url_table()
```

6. 接口报错的截图或代码

```
Traceback (most recent call last):
  File "/home/fang/venv/lib/python3.11/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fang/venv/lib/python3.11/site-packages/akshare/crypto/crypto_hist_investing.py", line 105, in crypto_name_url_table
    data_json = r.json()
                ^^^^^^^^
  File "/home/fang/venv/lib/python3.11/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

8. 期望获得的正确结果

https://www.akshare.xyz/data/dc/dc.html

而且这个接口太慢咯

**Comment by fungaren** [comment]
另一个接口也用不了：


```python
df = ak.crypto_hist(symbol="BTC", period="每日",start_date='20230601',end_date='20230611')
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fang/venv/lib/python3.11/site-packages/akshare/crypto/crypto_hist_investing.py", line 177, in crypto_hist
    temp_df = pd.read_html(r.text)[0]
              ^^^^^^^^^^^^^^^^^^^^
  File "/home/fang/venv/lib/python3.11/site-packages/pandas/io/html.py", line 1212, in read_html
    return _parse(
           ^^^^^^^
  File "/home/fang/venv/lib/python3.11/site-packages/pandas/io/html.py", line 1001, in _parse
    raise retained
  File "/home/fang/venv/lib/python3.11/site-packages/pandas/io/html.py", line 981, in _parse
    tables = p.parse_tables()
             ^^^^^^^^^^^^^^^^
  File "/home/fang/venv/lib/python3.11/site-packages/pandas/io/html.py", line 257, in parse_tables
    tables = self._parse_tables(self._build_doc(), self.match, self.attrs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fang/venv/lib/python3.11/site-packages/pandas/io/html.py", line 613, in _parse_tables
    raise ValueError("No tables found")
ValueError: No tables found
```

**Comment by albertandking** [comment]
> 另一个接口也用不了：
> 
> ```python
> df = ak.crypto_hist(symbol="BTC", period="每日",start_date='20230601',end_date='20230611')
> ```
> 
> ```
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/fang/venv/lib/python3.11/site-packages/akshare/crypto/crypto_hist_investing.py", line 177, in crypto_hist
>     temp_df = pd.read_html(r.text)[0]
>               ^^^^^^^^^^^^^^^^^^^^
>   File "/home/fang/venv/lib/python3.11/site-packages/pandas/io/html.py", line 1212, in read_html
>     return _parse(
>            ^^^^^^^
>   File "/home/fang/venv/lib/python3.11/site-packages/pandas/io/html.py", line 1001, in _parse
>     raise retained
>   File "/home/fang/venv/lib/python3.11/site-packages/pandas/io/html.py", line 981, in _parse
>     tables = p.parse_tables()
>              ^^^^^^^^^^^^^^^^
>   File "/home/fang/venv/lib/python3.11/site-packages/pandas/io/html.py", line 257, in parse_tables
>     tables = self._parse_tables(self._build_doc(), self.match, self.attrs)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/fang/venv/lib/python3.11/site-packages/pandas/io/html.py", line 613, in _parse_tables
>     raise ValueError("No tables found")
> ValueError: No tables found
> ```

该接口暂不能使用；已添加文档说明；

**Comment by otfung** [comment]
Windows 11 Enterprise 10.0.22621 Build 22621
conda 23.5.0
Python 3.10.11
akshare-1.10.40

接口用不了. 
期望获得的正确结果: https://www.akshare.xyz/data/dc/dc.html (接口示例)

`---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[3], line 1
----> 1 a_hist_df = akshare.crypto_hist()


File [~\AppData\Roaming\Python\Python310\site-packages\akshare\crypto\crypto_hist_investing.py:177], in crypto_hist(symbol, period, start_date, end_date)
    164 payload = {
    165     "curr_id": curr_id,
    166     "smlID": sml_id,
   (...)
    173     "action": "historical_data",
    174 }
    175 r = requests.post(url, data=payload, headers=headers)
--> 177 temp_df = pd.read_html(r.text)[0]
    178 df_data = temp_df.copy()
    179 if period == "每月":

File [~\AppData\Roaming\Python\Python310\site-packages\pandas\io\html.py:1212], in read_html(io, match, flavor, header, index_col, skiprows, attrs, parse_dates, thousands, encoding, decimal, converters, na_values, keep_default_na, displayed_only, extract_links, dtype_backend)
   1208 check_dtype_backend(dtype_backend)
   1210 io = stringify_path(io)
-> 1212 return _parse(
   1213     flavor=flavor,
   1214     io=io,
   1215     match=match,
...
--> 613     raise ValueError("No tables found")
    615 result = []
    616 unique_tables = set()

ValueError: No tables found`
