### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by wallace46886799** [akfamily/akshare#3871]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. Mac OS  Ventura 13.2.1
2. 3.9
3. 1.10.17 
4. bond_cov_issue_cninfo
5. '未经授权的访问,code:003 token null '
6. 正确返回可转债发行信息
 
File "akshare_test.py", line 3, in <module>
    bond_cov_issue_cninfo_df = ak.bond_cov_issue_cninfo(start_date="20210913", end_date="20211112")
  File "akshare-1.10.17-py3.9.egg/akshare/bond/bond_issue_cninfo.py", line 364, in bond_cov_issue_cninfo
    temp_df = pd.DataFrame(data_json["records"])
KeyError: 'records'

**Comment by albertandking** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> **描述遇到的问题**
> 
> 1. Mac OS  Ventura 13.2.1
> 2. 3.9
> 3. 1.10.17
> 4. bond_cov_issue_cninfo
> 5. '未经授权的访问,code:003 token null '
> 6. 正确返回可转债发行信息
> 
> File "akshare_test.py", line 3, in bond_cov_issue_cninfo_df = ak.bond_cov_issue_cninfo(start_date="20210913", end_date="20211112") File "akshare-1.10.17-py3.9.egg/akshare/bond/bond_issue_cninfo.py", line 364, in bond_cov_issue_cninfo temp_df = pd.DataFrame(data_json["records"]) KeyError: 'records'

感谢反馈问题；已修复该问题，升级到 AKShare 1.10.19 使用

**Comment by wallace46886799** [comment]
stock_new_ipo_cninfo 似乎也有类似问题，谢谢
