### ISSUE TITLE
Native library not available at /usr/local/lib/python3.10/site-packages/py_mini_racer/libmini_racer.glibc.so

### ISSUE THREAD

**Issue by nyndyhx** [akfamily/akshare#3876]
akshare: 1.10.19
py_mini-racer: 0.6

python: 3.10.10
OS: centos7-aarch64

RuntimeError: Native library not available at /usr/local/lib/python3.10/site-packages/py_mini_racer/libmini_racer.glibc.so
Exception ignored in: <function MiniRacer.del at 0x743dd9da20>
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/py_mini_racer/py_mini_racer.py", line 315, in del
self.ext.mr_free_context(getattr(self, "ctx", None))
AttributeError: 'NoneType' object has no attribute 'mr_free_context'
![image](https://github.com/akfamily/akshare/assets/29719049/eea11bc3-acd5-485e-a020-ae254f7ddcd5)

无法运行求帮忙😢

**Comment by nyndyhx** [comment]
目前PyMiniRacer不支持aarch64架构

**Comment by albertandking** [comment]
> 目前PyMiniRacer不支持aarch64架构

按文档对 m 处理器的说明操作
