### ISSUE TITLE
futures_zh_minute_sina接口调取期货历史分钟K，日期不全，只有最后接近交割月的一个月数据。但是一个合约应当持续很多个月。

### ISSUE THREAD

**Issue by ChunxiaoYang** [akfamily/akshare#3883]
![image](https://github.com/akfamily/akshare/assets/121948670/ae663a63-c058-4787-9daa-a88cd6875727)

首先通过基差的接口，调用了2023年6月1日的甲醇MA的主力合约代码是MA2309。
然后利用futures_zh_minute_sina调取MA2309的时候，他只有最近几天的数据。我的代码运行日期是北京时间20230615凌晨1点左右。
有两个期待：
1、能把这个分钟K的接口修复，能完整拉取合约所有天的分钟K
2、如果能直接拉各个品种主力合约的历史若干年的分钟K就最好啦！
非常感谢！！！

**Comment by ChunxiaoYang** [comment]
而且好像拉取过去的合约，分钟K也只能获取1023行，请问是有数量限制吗

**Comment by albertandking** [comment]
> 而且好像拉取过去的合约，分钟K也只能获取1023行，请问是有数量限制吗

对，该目标网站只提供近期的数据
