### ISSUE TITLE
tock_info_sh_name_code(symbol: str = "主板A股")，参数名为symbol，以前名字为indicator

### ISSUE THREAD

**Issue by quant2008** [akfamily/akshare#3892]
1.10.20版akshare中的函数def stock_info_sh_name_code(symbol: str = "主板A股")，参数名为symbol，以前名字为indicator，请改回去。

获取深圳数据的函数参数名字是对的，如下。
def stock_info_sz_name_code(indicator: str = "A股列表")

**Comment by albertandking** [comment]
> 1.10.20版akshare中的函数def stock_info_sh_name_code(symbol: str = "主板A股")，参数名为symbol，以前名字为indicator，请改回去。
> 
> 获取深圳数据的函数参数名字是对的，如下。 def stock_info_sz_name_code(indicator: str = "A股列表")

感谢反馈问题；已修复stock_info_sz_name_code，升级到 AKShare 1.10.30 使用
