### ISSUE TITLE
AKShare 接口问题报告：get_cffex_daily不支持IO产品

### ISSUE THREAD

**Issue by Hoyuri** [akfamily/akshare#3893]
**描述遇到的问题**
接口名称：get_cffex_daily
代码：
```python
    data_df = data_df[data_df["合约代码"] != "小计"]
    data_df = data_df[data_df["合约代码"] != "合计"]
    data_df = data_df[~data_df["合约代码"].str.contains("IO")]
    data_df.reset_index(inplace=True, drop=True)
    data_df["合约代码"] = data_df["合约代码"].str.strip()
    symbol_list = data_df["合约代码"].to_list()
```
其中这里`data_df = data_df[~data_df["合约代码"].str.contains("IO")]`使得查询结果不支持IO（沪深300期权）产品，可以考虑注释掉

**Comment by albertandking** [comment]
> ```python
> data_df[~data_df["合约代码"].str.contains("IO")]
> ```

该接口设计是获取期货数据

**Comment by Hoyuri** [comment]
如果只返回期货数据，那还要加一下`data_df[~data_df["合约代码"].str.contains("MO")]`和`data_df[~data_df["合约代码"].str.contains("HO")]`，因为CFFEX那边会把期货和期权数据都返回回来（参考主界面http://www.cffex.com.cn）。然后如果这个接口访问频繁（比如长session连接），会返回“10054, 远程主机强迫关闭了一个现有的连接。”，可以在文档里提示一下，避免用户被ban掉ip，麻烦了。

**Comment by albertandking** [comment]
> data_df[~data_df["合约代码"].str.contains("HO")]

感谢反馈，已进行相关的修改，升级到 AKShare 1.10.32 版本使用
