### ISSUE TITLE
AKShare 接口问题报告：stock_zh_index_daily_em不支持中信指数

### ISSUE THREAD

**Issue by Hoyuri** [akfamily/akshare#3894]
接口的名称：`stock_zh_index_daily_em`
接口源码：
```python
def stock_zh_index_daily_em(symbol: str = "sh000913") -> pd.DataFrame:
    """
    东方财富网-股票指数数据
    https://quote.eastmoney.com/center/hszs.html
    :param symbol: 带市场标识的指数代码
    :type symbol: str
    :return: 指数数据
    :rtype: pandas.DataFrame
    """
    market_map = {"sz": "0", "sh": "1","cs":"2","bj":"3"}
    url = "http://push2his.eastmoney.com/api/qt/stock/kline/get"
    params = {
        "cb": "jQuery1124033485574041163946_1596700547000",
        "secid": f"{market_map[symbol[:2]]}.{symbol[2:]}",
        "ut": "fa5fd1943c7b386f172d6893dbfba10b",
        "fields1": "f1,f2,f3,f4,f5",
        "fields2": "f51,f52,f53,f54,f55,f56,f57,f58",
        "klt": "101",  # 日频率
        "fqt": "0",
        "beg": "19900101",
        "end": "20320101",
        "_": "1596700547039",
    }
    r = requests.get(url, params=params)
    data_text = r.text
    data_json = demjson.decode(data_text[data_text.find("{") : -2])
    temp_df = pd.DataFrame([item.split(",") for item in data_json["data"]["klines"]])
    temp_df.columns = ["date", "open", "close", "high", "low", "volume", "amount", "_"]
    temp_df = temp_df[["date", "open", "close", "high", "low", "volume", "amount"]]

    temp_df["open"] = pd.to_numeric(temp_df["open"])
    temp_df["close"] = pd.to_numeric(temp_df["close"])
    temp_df["high"] = pd.to_numeric(temp_df["high"])
    temp_df["low"] = pd.to_numeric(temp_df["low"])
    temp_df["volume"] = pd.to_numeric(temp_df["volume"])
    temp_df["amount"] = pd.to_numeric(temp_df["amount"])
    return temp_df
```
问题描述：现在股票指数数据已支持csi中信指数，market_map可修改为`market_map = {"sz": "0", "sh": "1","csi":"2"}`
修改后代码为：
```python
def stock_zh_index_daily_em(
        symbol: str = "sh000913",
        startdate: str = "19900101",
        enddate: str = "20320101"
    ) -> pd.DataFrame:
    """
    东方财富网-股票指数数据
    https://quote.eastmoney.com/center/hszs.html
    @param: 
        @symbol:
            :meaning: 带市场标识的指数代码
            :type: str
            :supported format: sz 深交所, sh 上交所, csi中信指数 + id(000905)
        @startdate:
            :meaning: 取数据的起始日
            :type: str
            :supported format: yyyymmdd
        @enddate:
            :meaning: 取数据的终止日
            :type: str
            :supported format: yyyymmdd
    @return: 
        @temp_df:
            :meaning: 指数数据
            :rtype: pandas.DataFrame
    """
    market_map = {"sz": "0", "sh": "1","csi":"2"}
    url = "http://push2his.eastmoney.com/api/qt/stock/kline/get"
    if symbol.find("sz") != -1: secid = "{}.{}".format(market_map["sz"],symbol.replace("sz",""))
    elif symbol.find("sh") != -1: secid = "{}.{}".format(market_map["sh"],symbol.replace("sh",""))
    elif symbol.find("csi") != -1: secid = "{}.{}".format(market_map["csi"],symbol.replace("csi",""))
    else: return None

    params = {
        "cb": "jQuery1124033485574041163946_1596700547000",
        "secid": secid,
        "ut": "fa5fd1943c7b386f172d6893dbfba10b",
        "fields1": "f1,f2,f3,f4,f5",
        "fields2": "f51,f52,f53,f54,f55,f56,f57,f58",
        "klt": "101",  # 日频率
        "fqt": "0",
        "beg": startdate,
        "end": enddate,
        "_": "1596700547039",
    }
    r = requests.get(url, params=params)
    data_text = r.text
    data_json = demjson.decode(data_text[data_text.find("{") : -2])
    temp_df = pd.DataFrame([item.split(",") for item in data_json["data"]["klines"]])
    temp_df.columns = ["date", "open", "close", "high", "low", "volume", "amount", "_"]
    temp_df = temp_df[["date", "open", "close", "high", "low", "volume", "amount"]]

    temp_df["open"] = pd.to_numeric(temp_df["open"])
    temp_df["close"] = pd.to_numeric(temp_df["close"])
    temp_df["high"] = pd.to_numeric(temp_df["high"])
    temp_df["low"] = pd.to_numeric(temp_df["low"])
    temp_df["volume"] = pd.to_numeric(temp_df["volume"])
    temp_df["amount"] = pd.to_numeric(temp_df["amount"])
    return temp_df
```
使用示例：
```python
stock_zh_index_daily_em("csi931151","20200101","20230617") #光伏产业指数
```
返回示例：
```
	date	open	close	high	low	volume	amount
0	2020-12-21	3301.40	3373.85	3385.05	3290.24	26011305	4.360813e+10
1	2020-12-22	3357.60	3297.08	3411.81	3291.19	25724652	4.356199e+10
2	2020-12-23	3344.30	3487.90	3534.47	3344.30	33935345	5.280226e+10
3	2020-12-24	3482.44	3463.18	3522.39	3434.69	28687815	3.995600e+10
4	2020-12-25	3458.35	3619.27	3623.71	3456.91	37604473	4.889399e+10
...	...	...	...	...	...	...	...
599	2023-06-12	3477.56	3527.22	3547.22	3446.72	12784286	2.788541e+10
600	2023-06-13	3509.65	3512.48	3546.63	3490.14	9215303	1.976396e+10
601	2023-06-14	3520.30	3469.50	3523.84	3469.50	8476996	1.944076e+10
602	2023-06-15	3470.18	3659.38	3667.53	3455.72	16072231	4.407773e+10
603	2023-06-16	3673.33	3723.87	3727.72	3657.09	14520977	3.933791e+10
```

**Comment by albertandking** [comment]
> 接口的名称：`stock_zh_index_daily_em` 接口源码：
> 
> ```python
> def stock_zh_index_daily_em(symbol: str = "sh000913") -> pd.DataFrame:
>     """
>     东方财富网-股票指数数据
>     https://quote.eastmoney.com/center/hszs.html
>     :param symbol: 带市场标识的指数代码
>     :type symbol: str
>     :return: 指数数据
>     :rtype: pandas.DataFrame
>     """
>     market_map = {"sz": "0", "sh": "1","cs":"2","bj":"3"}
>     url = "http://push2his.eastmoney.com/api/qt/stock/kline/get"
>     params = {
>         "cb": "jQuery1124033485574041163946_1596700547000",
>         "secid": f"{market_map[symbol[:2]]}.{symbol[2:]}",
>         "ut": "fa5fd1943c7b386f172d6893dbfba10b",
>         "fields1": "f1,f2,f3,f4,f5",
>         "fields2": "f51,f52,f53,f54,f55,f56,f57,f58",
>         "klt": "101",  # 日频率
>         "fqt": "0",
>         "beg": "19900101",
>         "end": "20320101",
>         "_": "1596700547039",
>     }
>     r = requests.get(url, params=params)
>     data_text = r.text
>     data_json = demjson.decode(data_text[data_text.find("{") : -2])
>     temp_df = pd.DataFrame([item.split(",") for item in data_json["data"]["klines"]])
>     temp_df.columns = ["date", "open", "close", "high", "low", "volume", "amount", "_"]
>     temp_df = temp_df[["date", "open", "close", "high", "low", "volume", "amount"]]
> 
>     temp_df["open"] = pd.to_numeric(temp_df["open"])
>     temp_df["close"] = pd.to_numeric(temp_df["close"])
>     temp_df["high"] = pd.to_numeric(temp_df["high"])
>     temp_df["low"] = pd.to_numeric(temp_df["low"])
>     temp_df["volume"] = pd.to_numeric(temp_df["volume"])
>     temp_df["amount"] = pd.to_numeric(temp_df["amount"])
>     return temp_df
> ```
> 
> 问题描述：现在股票指数数据已支持csi中信指数，market_map可修改为`market_map = {"sz": "0", "sh": "1","csi":"2"}` 修改后代码为：
> 
> ```python
> def stock_zh_index_daily_em(
>         symbol: str = "sh000913",
>         startdate: str = "19900101",
>         enddate: str = "20320101"
>     ) -> pd.DataFrame:
>     """
>     东方财富网-股票指数数据
>     https://quote.eastmoney.com/center/hszs.html
>     @param: 
>         @symbol:
>             :meaning: 带市场标识的指数代码
>             :type: str
>             :supported format: sz 深交所, sh 上交所, csi中信指数 + id(000905)
>         @startdate:
>             :meaning: 取数据的起始日
>             :type: str
>             :supported format: yyyymmdd
>         @enddate:
>             :meaning: 取数据的终止日
>             :type: str
>             :supported format: yyyymmdd
>     @return: 
>         @temp_df:
>             :meaning: 指数数据
>             :rtype: pandas.DataFrame
>     """
>     market_map = {"sz": "0", "sh": "1","csi":"2"}
>     url = "http://push2his.eastmoney.com/api/qt/stock/kline/get"
>     if symbol.find("sz") != -1: secid = "{}.{}".format(market_map["sz"],symbol.replace("sz",""))
>     elif symbol.find("sh") != -1: secid = "{}.{}".format(market_map["sh"],symbol.replace("sh",""))
>     elif symbol.find("csi") != -1: secid = "{}.{}".format(market_map["csi"],symbol.replace("csi",""))
>     else: return None
> 
>     params = {
>         "cb": "jQuery1124033485574041163946_1596700547000",
>         "secid": secid,
>         "ut": "fa5fd1943c7b386f172d6893dbfba10b",
>         "fields1": "f1,f2,f3,f4,f5",
>         "fields2": "f51,f52,f53,f54,f55,f56,f57,f58",
>         "klt": "101",  # 日频率
>         "fqt": "0",
>         "beg": startdate,
>         "end": enddate,
>         "_": "1596700547039",
>     }
>     r = requests.get(url, params=params)
>     data_text = r.text
>     data_json = demjson.decode(data_text[data_text.find("{") : -2])
>     temp_df = pd.DataFrame([item.split(",") for item in data_json["data"]["klines"]])
>     temp_df.columns = ["date", "open", "close", "high", "low", "volume", "amount", "_"]
>     temp_df = temp_df[["date", "open", "close", "high", "low", "volume", "amount"]]
> 
>     temp_df["open"] = pd.to_numeric(temp_df["open"])
>     temp_df["close"] = pd.to_numeric(temp_df["close"])
>     temp_df["high"] = pd.to_numeric(temp_df["high"])
>     temp_df["low"] = pd.to_numeric(temp_df["low"])
>     temp_df["volume"] = pd.to_numeric(temp_df["volume"])
>     temp_df["amount"] = pd.to_numeric(temp_df["amount"])
>     return temp_df
> ```
> 
> 使用示例：
> 
> ```python
> stock_zh_index_daily_em("csi931151","20200101","20230617") #光伏产业指数
> ```
> 
> 返回示例：
> 
> ```
> 	date	open	close	high	low	volume	amount
> 0	2020-12-21	3301.40	3373.85	3385.05	3290.24	26011305	4.360813e+10
> 1	2020-12-22	3357.60	3297.08	3411.81	3291.19	25724652	4.356199e+10
> 2	2020-12-23	3344.30	3487.90	3534.47	3344.30	33935345	5.280226e+10
> 3	2020-12-24	3482.44	3463.18	3522.39	3434.69	28687815	3.995600e+10
> 4	2020-12-25	3458.35	3619.27	3623.71	3456.91	37604473	4.889399e+10
> ...	...	...	...	...	...	...	...
> 599	2023-06-12	3477.56	3527.22	3547.22	3446.72	12784286	2.788541e+10
> 600	2023-06-13	3509.65	3512.48	3546.63	3490.14	9215303	1.976396e+10
> 601	2023-06-14	3520.30	3469.50	3523.84	3469.50	8476996	1.944076e+10
> 602	2023-06-15	3470.18	3659.38	3667.53	3455.72	16072231	4.407773e+10
> 603	2023-06-16	3673.33	3723.87	3727.72	3657.09	14520977	3.933791e+10
> ```

感谢反馈问题及代码；已修复该问题，升级到 AKShare 1.10.29 使用
