### ISSUE TITLE
三大财务报表（利润表、现金流量表和资产负债表）的字段中文说明在官方文档中没有说明

### ISSUE THREAD

**Issue by AlexLid** [akfamily/akshare#3899]
你好，你们目前提供的三大财务报表很好用，也很难得做的这么好，因为报表的会计项很多，接口返回的数据字段都是英文，很难与中文含义对照，我自己也翻译了，但是不确定是否准确，你们后续可以增加字段的中文说明吗？

**Comment by albertandking** [comment]
> 你好，你们目前提供的三大财务报表很好用，也很难得做的这么好，因为报表的会计项很多，接口返回的数据字段都是英文，很难与中文含义对照，我自己也翻译了，但是不确定是否准确，你们后续可以增加字段的中文说明吗？

感谢使用；本项目是开源项目，如果方便的话，欢迎提交已翻译的项目，可以一起构建一个完善的字段翻译文档

**Comment by AlexLid** [comment]
可以啊，通过上传文档帮助你们完善翻译，晚点我整理一下！
