### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by caosiqiao4000** [akfamily/akshare#3902]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本             Window 11 专业版
2. Python 版本               3.10.10
3. AKShare 版本            1.10.32
4. 接口的名称和代码
`"""
    期货连续合约
    接口: futures_main_sina
    目标地址: http://vip.stock.finance.sina.com.cn/quotes_service/view/qihuohangqing.html#titlePos_0
    描述: 新浪财经-期货-主力连续合约历史数据
    限量: 单次返回单个期货品种的主力连续合约的日频历史数据
    """`

` futures_display_main_sina_df = ak.futures_display_main_sina()`
6. 接口报错的截图或代码
`Traceback (most recent call last):
  File "D:\pythonWorkSpace\caosiqiao4000\python-stock\akshareT\a_market\run_get_history_bars.py", line 20, in <module>
    start_fetch_a_future()  # 内盘
  File "D:\pythonWorkSpace\caosiqiao4000\python-stock\akshareT\a_market\handlerHistoryFutureToAndroidAssetCsv.py", line 64, in start_fetch_a_future
    futures_display_main_sina_df = ak.futures_display_main_sina()
  File "D:\ProgramData\anaconda3\envs\ak_test\lib\site-packages\akshare\futures_derivative\sina_futures_index.py", line 96, in futures_display_main_sina
    temp_df = pd.concat([temp_df, match_main_contract(symbol=item)])
  File "D:\ProgramData\anaconda3\envs\ak_test\lib\site-packages\akshare\futures_derivative\sina_futures_index.py", line 61, in match_main_contract
    zh_subscribe_exchange_symbol(symbol).iloc[:, 1].tolist()
  File "D:\ProgramData\anaconda3\envs\ak_test\lib\site-packages\akshare\futures_derivative\sina_futures_index.py", line 30, in zh_subscribe_exchange_symbol
    data_json = demjson.decode(

  File "D:\ProgramData\anaconda3\envs\ak_test\lib\site-packages\akshare\utils\demjson.py", line 5740, in decode
    result = j.decode(txt,
  File "D:\ProgramData\anaconda3\envs\ak_test\lib\site-packages\akshare\utils\demjson.py", line 4957, in decode
    raise errors[0]
akshare.utils.demjson.JSONDecodeError: No value to decode`

期望获得的正确结果

**Comment by albertandking** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本             Window 11 专业版
> 2. Python 版本               3.10.10
> 3. AKShare 版本            1.10.32
> 4. 接口的名称和代码
>    `""" 期货连续合约 接口: futures_main_sina 目标地址: http://vip.stock.finance.sina.com.cn/quotes_service/view/qihuohangqing.html#titlePos_0 描述: 新浪财经-期货-主力连续合约历史数据 限量: 单次返回单个期货品种的主力连续合约的日频历史数据 """`
> 
> ` futures_display_main_sina_df = ak.futures_display_main_sina()` 6. 接口报错的截图或代码 `Traceback (most recent call last): File "D:\pythonWorkSpace\caosiqiao4000\python-stock\akshareT\a_market\run_get_history_bars.py", line 20, in start_fetch_a_future() # 内盘 File "D:\pythonWorkSpace\caosiqiao4000\python-stock\akshareT\a_market\handlerHistoryFutureToAndroidAssetCsv.py", line 64, in start_fetch_a_future futures_display_main_sina_df = ak.futures_display_main_sina() File "D:\ProgramData\anaconda3\envs\ak_test\lib\site-packages\akshare\futures_derivative\sina_futures_index.py", line 96, in futures_display_main_sina temp_df = pd.concat([temp_df, match_main_contract(symbol=item)]) File "D:\ProgramData\anaconda3\envs\ak_test\lib\site-packages\akshare\futures_derivative\sina_futures_index.py", line 61, in match_main_contract zh_subscribe_exchange_symbol(symbol).iloc[:, 1].tolist() File "D:\ProgramData\anaconda3\envs\ak_test\lib\site-packages\akshare\futures_derivative\sina_futures_index.py", line 30, in zh_subscribe_exchange_symbol data_json = demjson.decode(
> 
> File "D:\ProgramData\anaconda3\envs\ak_test\lib\site-packages\akshare\utils\demjson.py", line 5740, in decode result = j.decode(txt, File "D:\ProgramData\anaconda3\envs\ak_test\lib\site-packages\akshare\utils\demjson.py", line 4957, in decode raise errors[0] akshare.utils.demjson.JSONDecodeError: No value to decode`
> 
> 期望获得的正确结果

感谢反馈问题；已修复该问题，升级到 AKShare 1.10.34 使用
