### ISSUE TITLE
申请get_receipt接口增加获取广期所工业硅仓单的功能

### ISSUE THREAD

**Issue by yinlinzhan** [akfamily/akshare#3907]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by albertandking** [comment]
> **Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> 
> **Describe the solution you'd like** A clear and concise description of what you want to happen.
> 
> **Describe alternatives you've considered** A clear and concise description of any alternative solutions or features you've considered.
> 
> **Additional context** Add any other context or screenshots about the feature request here.

感谢反馈问题；已新增相关功能，升级到 AKShare 1.10.35 使用

**Comment by yinlinzhan** [comment]
感谢
