### ISSUE TITLE
stock_zh_a_hist_min_em返回5分钟数据不正确

### ISSUE THREAD

**Issue by ztlsir** [akfamily/akshare#3912]
问题：
通过stock_zh_a_hist_min_em获取的5分钟前复权数据，在2023-06-21 14:55左右获取的数据都是11块左右，实际应该是12块左右
1. 操作系统版本
macOS 13.0.1
2. Python 版本
3.11
3. AKShare 版本
akshare 1.10.34
4. 接口的名称和代码
接口名称：stock_zh_a_hist_min_em
代码：
`stock_zh_a_hist_min_em_df = ak.stock_zh_a_hist_min_em(
        symbol="000001",
        start_date="2023-03-26 09:32:00",
        end_date="2023-06-25 09:00:00",
        period="5",
        adjust="qfq",
    ).values`
5. 接口报错的截图或代码
代码通过调试获取数据内容：
<img width="832" alt="image" src="https://github.com/akfamily/akshare/assets/9571578/7987b578-bb5e-4ead-93c4-38749a418088">
6. 期望获得的正确结果
postman获取数据内容（参数与代码一致，都是5分钟、前复权）：
<img width="807" alt="image" src="https://github.com/akfamily/akshare/assets/9571578/4dd1d303-f0c3-4e93-b7b1-4b2cc69eabdf">

**Comment by albertandking** [comment]
> 4\. period="5", adjust="qfq"

接口获取数据正常；建议检查 postman 获取的数据
