### ISSUE TITLE
stock_zh_a_hist获取数据有错误.

### ISSUE THREAD

**Issue by tmuer** [akfamily/akshare#3913]
**描述遇到的问题**
1. 系统:win11
2. Python 版本:3.11
3. AKShare 版本:最新
4. 接口的名称和代码:股票历史数据,stock_zh_a_hist
akshare似乎更推荐使用东财的接口而不是新浪的,今天发现东财的接口有很大问题.
例如华塑控股,后复权,在2020年5月底,股票每天的涨跌幅动辄二三十,甚至2020-05-21当天出现90%的涨幅.后复权数据出现巨大的错误.
经过对比,东财网站,通达信的数据都出现相同问题,同花顺的后复权则出现股价负数的离谱情况,2020-05-21当天股价为-28元.
几大平台中,东财旗下的choice数据是正确的,新浪和choice的数据很接近.
建议仔细核对stock_zh_a_hist接口的东财数据,谨慎使用东财接口.

**Comment by albertandking** [comment]
> 

该日期区间该股票有异常波动且是 *ST 的股票，免费行情数据源会有该情况出现；建议使用专业数据源，如万得，choice 等数据源；
