### ISSUE TITLE
AKShare 接口问题报告：同花顺-概念时间表

### ISSUE THREAD

**Issue by flizzywine** [akfamily/akshare#3918]
1. 操作系统版本  MacOS 12.0.1 
2. Python 版本  python3.9.12
3. AKShare 版本  akshare-1.10.37
4. 接口的名称和代码 
```
concept_list_df = ak.stock_board_concept_name_ths()
# 同花顺-概念时间表[](https://www.akshare.xyz/data/stock/stock.html#id311)
```
5. 接口报错的截图或代码
![image](https://github.com/akfamily/akshare/assets/27564130/3abf8cde-5d04-4451-8bb0-6a6a69c78fd1)

6. 期望获得的正确结果 返回同花顺的概念列表。

PS： 在晚上9点半的时候，使用这个接口，还没有问题。到晚上10点，再去调用，就会报错。

**Comment by flizzywine** [comment]
![image](https://github.com/akfamily/akshare/assets/27564130/ccbcbcc1-a66b-408b-b9c7-c7ad3b1ae9a9)

原因：同花顺接口网址直接拒绝服务。
URL：http://q.10jqka.com.cn/gn/detail/code/301558/

**Comment by albertandking** [comment]
> stock_board_concept_name_ths

注意访问频率
