### ISSUE TITLE
东方财富行业概念数据获取有误

### ISSUE THREAD

**Issue by tin555** [akfamily/akshare#3921]
> **描述遇到的问题**
> 
> 1. python 板块  Python 3.7.6
> 2. AKShare 版本 1.10.38
> 3. 接口的名称和代码
>    ak.stock_board_concept_hist_min_em
> 4. 接口报错的截图或代码
    在原来 issues上 https://github.com/akfamily/akshare/issues/3916 这边只修改了stock_board_industry_hist_min_em接口但是stock_board_concept_hist_min_em存在修改遗漏，麻烦更新一下，感恩~~！
_Originally posted by @albertandking in https://github.com/akfamily/akshare/issues/3916#issuecomment-1609034797_

**Comment by albertandking** [comment]
> > **描述遇到的问题**
> > 
> > 1. python 板块  Python 3.7.6
> > 2. AKShare 版本 1.10.38
> > 3. 接口的名称和代码
> >    ak.stock_board_concept_hist_min_em
> > 4. 接口报错的截图或代码
> >    在原来 issues上 [AKShare 东方财富行业概念板块数据获取不正确 #3916](https://github.com/akfamily/akshare/issues/3916) 这边只修改了stock_board_industry_hist_min_em接口但是stock_board_concept_hist_min_em存在修改遗漏，麻烦更新一下，感恩~~！
> >    _Originally posted by @albertandking in [AKShare 东方财富行业概念板块数据获取不正确 #3916 (comment)](https://github.com/akfamily/akshare/issues/3916#issuecomment-1609034797)_

感谢反馈问题；已修复该问题，升级到 AKShare 最新版使用
