### ISSUE TITLE
基金历史行情-东财fund_etf_hist_em接口建议。

### ISSUE THREAD

**Issue by xnw176** [akfamily/akshare#3925]
相同的网页地址结构还可以获取场内LOF的相关页面和数据，目前的接口有dict，如代码不在列表中会出错。

建议扩大code_id_dict范围使之包含LOF代码，或者干脆取消这个dict，让接口使用者自已对基金代码是否正确负责。

望采纳，万分感谢。

**Comment by albertandking** [comment]
> 相同的网页地址结构还可以获取场内LOF的相关页面和数据，目前的接口有dict，如代码不在列表中会出错。
> 
> 建议扩大code_id_dict范围使之包含LOF代码，或者干脆取消这个dict，让接口使用者自已对基金代码是否正确负责。
> 
> 望采纳，万分感谢。

感谢反馈问题；已新增 fund_lof_hist_em 接口，升级到 AKShare 1.10.41 使用
