### ISSUE TITLE
AKShare 接口 sw_index_spot  问题报告

### ISSUE THREAD

**Issue by new-agent-lk** [akfamily/akshare#3928]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本  ubuntu 22.04
2. Python 版本  3.8
3. AKShare 版本 1.9.97
4. 接口的名称和代码  
    sw_index_spot()
5. 接口报错的截图或代码
![image](https://github.com/akfamily/akshare/assets/66538692/e2ad4adf-ddd3-4cf5-aaf3-fb997a319206)

6. 期望获得的正确结果

**Comment by new-agent-lk** [comment]
![image](https://github.com/akfamily/akshare/assets/66538692/96d113dd-80d2-4ead-9316-1004ae44c8b4)

大概是接口过期了？或者被屏蔽了

**Comment by albertandking** [comment]
> 4\. sw_index_spot

看文档相关说明
