### ISSUE TITLE
调用stock_szse_sector_summary方法时会出现 SSL 错误，配置本地证书也无效，应该如何修改

### ISSUE THREAD

**Issue by lizhao903** [akfamily/akshare#3931]
stock_szse_sector_summary_df = ak.stock_szse_sector_summary(symbol="当年", date="202204")
print(stock_szse_sector_summary_df)

SSLError: HTTPSConnectionPool(host='www.szse.cn', port=443): Max retries exceeded with url: /market/periodical/month/index.html (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')))

---------------------------
配置本地通用证书仍然报错
import certifi
import os
os.environ['REQUESTS_CA_BUNDLE'] = certifi.where()

**Comment by lizhao903** [comment]
操作系统版本：mac OSX
Python 版本：3.10
AKshare 版本：1.10.23

**Comment by albertandking** [comment]
> stock_szse_sector_summary(symbol="当年", date="202204")

接口正常；请查看本地网络配置
