### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by XX-Trader** [akfamily/akshare#3935]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. windows
2. Python 3.10
3. AKShare 版本 1.10.44
4. 接口的名称和代码: 
akshare/stock/stock_zh_a_sina.stock_zh_a_minute
6. 接口报错的截图或代码: 
 url = "https://quotes.sina.cn/cn/api/jsonp_v2.php/=/CN_MarketDataService.getKLineData"
   该接口可能已经更换，
7. 期望获得的正确结果
     能够获取到与之前一样的K线数据

**Comment by hpeiyan** [comment]
same issue

**Comment by hpeiyan** [comment]
快更新，官方已经解决了

**Comment by albertandking** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> **描述遇到的问题**
> 
> 1. windows
> 2. Python 3.10
> 3. AKShare 版本 1.10.44
> 4. 接口的名称和代码:
>    akshare/stock/stock_zh_a_sina.stock_zh_a_minute
> 5. 接口报错的截图或代码:
>    url = "https://quotes.sina.cn/cn/api/jsonp_v2.php/=/CN_MarketDataService.getKLineData"
>    该接口可能已经更换，
> 6. 期望获得的正确结果
>    能够获取到与之前一样的K线数据

感谢反馈问题；已修复该问题，升级到 AKShare 1.10.46 使用
