### ISSUE TITLE
问题：中证指数历史成分数据获取

### ISSUE THREAD

**Issue by o0fatigue** [akfamily/akshare#3936]
请问中证指数历史成分数据目前是否有接口可以获取呢？

**Comment by jukxi** [comment]
+1

**Comment by albertandking** [comment]
> 中证指数

index_stock_cons_csindex；参见文档

**Comment by o0fatigue** [comment]
@albertandking  index_stock_cons_csindex这个接口貌似没办法查询历史成分的吧？只有最新的？
