### ISSUE TITLE
获取指数信息操作返回错误

### ISSUE THREAD

**Issue by eyingpi** [akfamily/akshare#3938]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本: Windows 10 Enterprise
2. Python 版本: Python 3.11.2
3. AKShare 版本: 1.10.44
4. 接口的名称和代码
以前该接口能正常使用, 从今天中午(2023-07-06)开始就报错了.
import akshare as ak

index_value_name_funddb_df = ak.index_value_name_funddb()
print(index_value_name_funddb_df)

6. 接口报错的截图或代码
---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
File [c:\Users\eyingpi\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py:971](file:///C:/Users/eyingpi/AppData/Local/Programs/Python/Python311/Lib/site-packages/requests/models.py:971), in Response.json(self, **kwargs)
    970 try:
--> 971     return complexjson.loads(self.text, **kwargs)
    972 except JSONDecodeError as e:
    973     # Catch JSON-related errors and raise as requests.JSONDecodeError
    974     # This aliases json.JSONDecodeError and simplejson.JSONDecodeError

File [c:\Users\eyingpi\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py:346](file:///C:/Users/eyingpi/AppData/Local/Programs/Python/Python311/Lib/json/__init__.py:346), in loads(s, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    343 if (cls is None and object_hook is None and
    344         parse_int is None and parse_float is None and
    345         parse_constant is None and object_pairs_hook is None and not kw):
--> 346     return _default_decoder.decode(s)
    347 if cls is None:

File [c:\Users\eyingpi\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py:337](file:///C:/Users/eyingpi/AppData/Local/Programs/Python/Python311/Lib/json/decoder.py:337), in JSONDecoder.decode(self, s, _w)
    333 """Return the Python representation of ``s`` (a ``str`` instance
    334 containing a JSON document).
    335 
    336 """
--> 337 obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    338 end = _w(s, end).end()

File [c:\Users\eyingpi\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py:355](file:///C:/Users/eyingpi/AppData/Local/Programs/Python/Python311/Lib/json/decoder.py:355), in JSONDecoder.raw_decode(self, s, idx)
    354 except StopIteration as err:
--> 355     raise JSONDecodeError("Expecting value", s, err.value) from None
    356 return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

JSONDecodeError                           Traceback (most recent call last)
Cell In[5], line 3
      1 import akshare as ak
----> 3 index_value_name_funddb_df = ak.index_value_name_funddb()
      4 print(index_value_name_funddb_df)

File [c:\Users\eyingpi\AppData\Local\Programs\Python\Python311\Lib\site-packages\akshare\index\stock_zh_index_csindex.py:114](file:///C:/Users/eyingpi/AppData/Local/Programs/Python/Python311/Lib/site-packages/akshare/index/stock_zh_index_csindex.py:114), in index_value_name_funddb()
    112 url = "https://api.jiucaishuo.com/v2/guzhi/showcategory"
    113 r = requests.get(url)
--> 114 data_json = r.json()
    115 temp_df = pd.DataFrame(data_json["data"]["right_list"])
    116 temp_df.columns = [
    117     "指数开始时间",
    118     "-",
   (...)
    146     "-",
    147 ]

File [c:\Users\eyingpi\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py:975](file:///C:/Users/eyingpi/AppData/Local/Programs/Python/Python311/Lib/site-packages/requests/models.py:975), in Response.json(self, **kwargs)
    971     return complexjson.loads(self.text, **kwargs)
    972 except JSONDecodeError as e:
    973     # Catch JSON-related errors and raise as requests.JSONDecodeError
    974     # This aliases json.JSONDecodeError and simplejson.JSONDecodeError
--> 975     raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

7. 期望获得的正确结果
能取到指数信息

**Comment by hpeiyan** [comment]
same issue

**Comment by albertandking** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本: Windows 10 Enterprise
> 2. Python 版本: Python 3.11.2
> 3. AKShare 版本: 1.10.44
> 4. 接口的名称和代码
>    以前该接口能正常使用, 从今天中午(2023-07-06)开始就报错了.
>    import akshare as ak
> 
> index_value_name_funddb_df = ak.index_value_name_funddb() print(index_value_name_funddb_df)
> 
> 6. 接口报错的截图或代码
> 
> JSONDecodeError Traceback (most recent call last) File c:\Users\eyingpi\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py:971, in Response.json(self, **kwargs) 970 try: --> 971 return complexjson.loads(self.text, **kwargs) 972 except JSONDecodeError as e: 973 # Catch JSON-related errors and raise as requests.JSONDecodeError 974 # This aliases json.JSONDecodeError and simplejson.JSONDecodeError
> 
> File c:\Users\eyingpi\AppData\Local\Programs\Python\Python311\Lib\json__init__.py:346, in loads(s, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw) 343 if (cls is None and object_hook is None and 344 parse_int is None and parse_float is None and 345 parse_constant is None and object_pairs_hook is None and not kw): --> 346 return _default_decoder.decode(s) 347 if cls is None:
> 
> File c:\Users\eyingpi\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py:337, in JSONDecoder.decode(self, s, _w) 333 """Return the Python representation of `s` (a `str` instance 334 containing a JSON document). 335 336 """ --> 337 obj, end = self.raw_decode(s, idx=_w(s, 0).end()) 338 end = _w(s, end).end()
> 
> File c:\Users\eyingpi\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py:355, in JSONDecoder.raw_decode(self, s, idx) 354 except StopIteration as err: --> 355 raise JSONDecodeError("Expecting value", s, err.value) from None 356 return obj, end
> 
> JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 
> During handling of the above exception, another exception occurred:
> 
> JSONDecodeError Traceback (most recent call last) Cell In[5], line 3 1 import akshare as ak ----> 3 index_value_name_funddb_df = ak.index_value_name_funddb() 4 print(index_value_name_funddb_df)
> 
> File c:\Users\eyingpi\AppData\Local\Programs\Python\Python311\Lib\site-packages\akshare\index\stock_zh_index_csindex.py:114, in index_value_name_funddb() 112 url = "https://api.jiucaishuo.com/v2/guzhi/showcategory" 113 r = requests.get(url) --> 114 data_json = r.json() 115 temp_df = pd.DataFrame(data_json["data"]["right_list"]) 116 temp_df.columns = [ 117 "指数开始时间", 118 "-", (...) 146 "-", 147 ]
> 
> File c:\Users\eyingpi\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py:975, in Response.json(self, **kwargs) 971 return complexjson.loads(self.text, **kwargs) 972 except JSONDecodeError as e: 973 # Catch JSON-related errors and raise as requests.JSONDecodeError 974 # This aliases json.JSONDecodeError and simplejson.JSONDecodeError --> 975 raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
> 
> JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 
> 7. 期望获得的正确结果
>    能取到指数信息

感谢反馈问题；已修复该问题，升级到 AKShare 1.10.46 使用

**Comment by Minaloushe** [comment]
操作系统版本: Windows 10
Python 版本: Python 3.10
AKShare 版本: 1.11.91
仍有上述报错，求助
