### ISSUE TITLE
index_value_name_funddb()、index_value_hist_funddb()接口报错

### ISSUE THREAD

**Issue by tianhaisuifeng** [akfamily/akshare#3939]
akshare最新版本

接口index_value_name_funddb()、index_value_hist_funddb()报错，昨天还能正常使用
line 37, in _scan_once
    nextchar = string[idx]
IndexError: string index out of range

**Comment by hpeiyan** [comment]
兄台有进到他们的群吗？联系及时一点

**Comment by hpeiyan** [comment]
接口都没法用了，损失。。。

**Comment by albertandking** [comment]
> akshare最新版本
> 
> 接口index_value_name_funddb()、index_value_hist_funddb()报错，昨天还能正常使用 line 37, in _scan_once nextchar = string[idx] IndexError: string index out of range

感谢反馈问题；已修复该问题，升级到 AKShare 1.10.46 使用
