### ISSUE TITLE
东财港股三大报表仅能下载最近 8 年的数据（ak.stock_financial_hk_report_em）

### ISSUE THREAD

**Issue by pengcui** [akfamily/akshare#3943]
**描述遇到的问题**
1. macOS Catalina
2. Python 3.8.15
3. AKShare 1.10.30
4. 接口和代码：ak.stock_financial_hk_report_em(stock="00853", symbol="资产负债表", indicator="年度")
5. 东财港股三大报表仅能下载最近 8 年的数据，但其实之前年份的数据也是有的，看网站上是有个小按钮（下图红色圈出）
<img width="731" alt="截屏2023-07-06 下午10 13 08" src="https://github.com/akfamily/akshare/assets/4489100/34fb64f3-1bf9-4d06-8686-d81cf4c338df">
<img width="1052" alt="截屏2023-07-06 下午10 13 47" src="https://github.com/akfamily/akshare/assets/4489100/e9822c88-6df6-4b69-adb6-7fe31d16b61b">
相同网站的情况， A 股三大报表数据就是完整的，如 ak.stock_balance_sheet_by_yearly_em(symbol="SH600276")，可以下载到所有年份的数据，或许可以看看两个接口代码的区别。

**Comment by albertandking** [comment]
> **描述遇到的问题**
> 
> 1. macOS Catalina
> 2. Python 3.8.15
> 3. AKShare 1.10.30
> 4. 接口和代码：ak.stock_financial_hk_report_em(stock="00853", symbol="资产负债表", indicator="年度")
> 5. 东财港股三大报表仅能下载最近 8 年的数据，但其实之前年份的数据也是有的，看网站上是有个小按钮（下图红色圈出）
> 
> <img alt="截屏2023-07-06 下午10 13 08" width="731" src="https://user-images.githubusercontent.com/4489100/251477495-34fb64f3-1bf9-4d06-8686-d81cf4c338df.png"> <img alt="截屏2023-07-06 下午10 13 47" width="1052" src="https://user-images.githubusercontent.com/4489100/251478316-e9822c88-6df6-4b69-adb6-7fe31d16b61b.png"> 相同网站的情况， A 股三大报表数据就是完整的，如 ak.stock_balance_sheet_by_yearly_em(symbol="SH600276")，可以下载到所有年份的数据，或许可以看看两个接口代码的区别。

感谢反馈问题；已修复该问题，升级到 AKShare 1.10.52 使用
