### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by baointoo2** [akfamily/akshare#3944]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本
    windows 10
2. Python 版本:
    python 3.9.13
3. AKShare 版本:
    akshare 1.10.44
4. 接口的名称和代码:
    接口名：stock_zh_a_minute

   调用代码：
   import akshare as ak

  def get_hist_data(self, startDate, ktype):
	df = ak.stock_zh_a_minute(self.stockCode, ktype)

	df = df[df['day'] > startDate]

	df.rename(columns={'day':'date'}, inplace=True)

	print(df)

	return df
   
    filetered_df = self.get_hist_data('2023-06-27 09:30:00', '1')

5. 接口报错的截图或代码
    
   
![image](https://github.com/akfamily/akshare/assets/13964607/f1e0fa6d-a3a7-439e-bbc4-d0ccb536dbda)

6. 期望获得的正确结果
    正常获取接口数据，之前一直是好的，从7月3，4号开始不行的，估计是新浪换接口了。

**Comment by albertandking** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本
>    windows 10
> 2. Python 版本:
>    python 3.9.13
> 3. AKShare 版本:
>    akshare 1.10.44
> 4. 接口的名称和代码:
>    接口名：stock_zh_a_minute
>    调用代码：
>    import akshare as ak
> 
> def get_hist_data(self, startDate, ktype): df = ak.stock_zh_a_minute(self.stockCode, ktype)
> 
> ```
> df = df[df['day'] > startDate]
> 
> df.rename(columns={'day':'date'}, inplace=True)
> 
> print(df)
> 
> return df
> 
> filetered_df = self.get_hist_data('2023-06-27 09:30:00', '1')
> ```
> 
> 5. 接口报错的截图或代码
> 
> ![image](https://user-images.githubusercontent.com/13964607/251487396-f1e0fa6d-a3a7-439e-bbc4-d0ccb536dbda.png)
> 
> 6. 期望获得的正确结果
>    正常获取接口数据，之前一直是好的，从7月3，4号开始不行的，估计是新浪换接口了。

已修复，升级到最新版使用
