### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by Perrygd** [akfamily/akshare#3945]
index_value_name_funddb()接口运行出错，无法获得返回结果

**Comment by albertandking** [comment]
> index_value_name_funddb

升级到最新版使用

**Comment by Perrygd** [comment]
谢谢！给力！发自我的 iPhone在 2023年7月7日，14:37，Albert King ***@***.***> 写道：﻿

index_value_name_funddb

升级到最新版使用
