### ISSUE TITLE
电竞-俱乐部排名已经无法访问

### ISSUE THREAD

**Issue by chenyuyou** [akfamily/akshare#3947]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本
2. Python 版本
3. AKShare 版本
4. 接口的名称和代码
5. 接口报错的截图或代码
6. 期望获得的正确结果

**Comment by albertandking** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本
> 2. Python 版本
> 3. AKShare 版本
> 4. 接口的名称和代码
> 5. 接口报错的截图或代码
> 6. 期望获得的正确结果

已移除相关接口；数据源未提供数据
