### ISSUE TITLE
获取中证指数成分历史

### ISSUE THREAD

**Issue by o0fatigue** [akfamily/akshare#3952]
#3936 中恢复说使用`index_stock_cons_csindex`查询中证指数成分历史，但是文档中貌似并没有相关指定日期的参数，请问这是预期内行为吗？

<html>
<body>
<p style="box-sizing: border-box; line-height: 24px; font-size: 16px; margin: 0px 0px 24px; color: rgb(64, 64, 64); font-family: Lato, proxima-nova, &quot;Helvetica Neue&quot;, Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(252, 252, 252); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">输入参数</p><div class="wy-table-responsive" style="box-sizing: border-box; margin-bottom: 24px; max-width: 100%; overflow: auto; color: rgb(64, 64, 64); font-family: Lato, proxima-nova, &quot;Helvetica Neue&quot;, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(252, 252, 252); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

名称 | 类型 | 描述
-- | -- | --
symbol | str | symbol="000300"; 指数代码

</div>
</body>
</html>

<html>
<body>
<p style="box-sizing: border-box; line-height: 24px; font-size: 16px; margin: 0px 0px 24px; color: rgb(64, 64, 64); font-family: Lato, proxima-nova, &quot;Helvetica Neue&quot;, Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(252, 252, 252); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">输出参数</p><div class="wy-table-responsive" style="box-sizing: border-box; margin-bottom: 24px; max-width: 100%; overflow: auto; color: rgb(64, 64, 64); font-family: Lato, proxima-nova, &quot;Helvetica Neue&quot;, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(252, 252, 252); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

名称 | 类型 | 描述
-- | -- | --
日期 | object | -
指数代码 | object | -
指数名称 | object | -
指数英文名称 | object | -
成分券代码 | object | -
成分券名称 | object | -
成分券英文名称 | object | -
交易所 | object | -
交易所英文名称 | object | -

</div>
</body>
</html>

示例代码
```python
import akshare as ak

index_stock_cons_csindex_df = ak.index_stock_cons_csindex(symbol="931463")
print(index_stock_cons_csindex_df)
```

**Comment by albertandking** [comment]
> #3936 中恢复说使用`index_stock_cons_csindex`查询中证指数成分历史，但是文档中貌似并没有相关指定日期的参数，请问这是预期内行为吗？
> 
> 输入参数
> 
> 名称	类型	描述
> symbol	str	symbol="000300"; 指数代码
> 输出参数
> 
> 名称	类型	描述
> 日期	object	-
> 指数代码	object	-
> 指数名称	object	-
> 指数英文名称	object	-
> 成分券代码	object	-
> 成分券名称	object	-
> 成分券英文名称	object	-
> 交易所	object	-
> 交易所英文名称	object	-
> 示例代码
> 
> ```python
> import akshare as ak
> 
> index_stock_cons_csindex_df = ak.index_stock_cons_csindex(symbol="931463")
> print(index_stock_cons_csindex_df)
> ```

默认获取所有数据
