### ISSUE TITLE
index_value_name_funddb接口问题报告

### ISSUE THREAD

**Issue by inspirits** [akfamily/akshare#3957]
akshare版本已更新至1.10.51，包含1.10.46版本的改动。
刚更新至1.10.46时index_value_name_funddb和index_value_hist_funddb已经可正常使用，但今天中午又报错无法使用。

**Comment by eyingpi** [comment]
The same issue:
源码:
import akshare as ak
index_value_name_funddb_df = ak.index_value_name_funddb()
print(index_value_name_funddb_df)

错误信息:
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[1], line 3
      1 import akshare as ak
----> 3 index_value_name_funddb_df = ak.index_value_name_funddb()
      4 print(index_value_name_funddb_df)

File [c:\Users\eyingpi\AppData\Local\Programs\Python\Python311\Lib\site-packages\akshare\index\stock_zh_index_csindex.py:340](file:///C:/Users/eyingpi/AppData/Local/Programs/Python/Python311/Lib/site-packages/akshare/index/stock_zh_index_csindex.py:340), in index_value_name_funddb()
    338 r = requests.post(url, json=payload)
    339 data_json = r.json()
--> 340 temp_df = pd.DataFrame(data_json["data"]["right_list"])
    341 temp_df.columns = [
    342     "指数开始时间",
    343     "-",
   (...)
    371     "-",
    372 ]
    373 temp_df = temp_df[
    374     [
    375         "指数名称",
   (...)
    385     ]
    386 ]

KeyError: 'data'

**Comment by eyingpi** [comment]
升级到akshare-1.10.52版本后, 没有这个问题了

**Comment by inspirits** [comment]
> 升级到akshare-1.10.52版本后, 没有这个问题了

1.10.52 fix: fix stock_financial_hk_report_em interface
我的依然有问题，而且1.10.52的改动和这个无关呀

**Comment by albertandking** [comment]
> akshare版本已更新至1.10.51，包含1.10.46版本的改动。 刚更新至1.10.46时index_value_name_funddb和index_value_hist_funddb已经可正常使用，但今天中午又报错无法使用。

升级到 AKShare 1.10.52 使用

**Comment by albertandking** [comment]
> > 升级到akshare-1.10.52版本后, 没有这个问题了
> 
> 1.10.52 fix: fix stock_financial_hk_report_em interface 我的依然有问题，而且1.10.52的改动和这个无关呀

要看 changelog.md 部分
