### ISSUE TITLE
index_stock_cons_csindex无法获取成分历史

### ISSUE THREAD

**Issue by o0fatigue** [akfamily/akshare#3958]
接 #3952 
 index_stock_cons_csindex与index_stock_cons_weight_csindex并不会返回全部数据，指定`symbol="000300"` 返回shape分别为`(300, 9)` 和 `(300, 10)`，不包含历史信息，与“默认获取所有数据”的预期不一致，是否数据源发生改变？

希望可以添加`start_date`, `end_date`参数获取指定范围的成分历史，如不指定则与当前行为一致。

**Comment by albertandking** [comment]
> index_stock_cons_weight_csindex

数据源未提供更多历史数据，目前只能获取最近一期的数据
