### ISSUE TITLE
美国CPI月率报告&美国核心CPI月率报告出错

### ISSUE THREAD

**Issue by yacper** [akfamily/akshare#3961]
**Describe the bug**
在获取这两个数据的时候报错，原因是代码使用的pandas版本过低，现在新一点的版本，pandas series没有append函数了，建议升级一下pandas的版本。

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[~\AppData\Local\Temp\ipykernel_58340\3487255860.py](https://file+.vscode-resource.vscode-cdn.net/c%3A/Git/Quant101/Python/13-%E9%87%91%E8%9E%8D%E6%95%B0%E6%8D%AE%E8%8E%B7%E5%8F%96/~/AppData/Local/Temp/ipykernel_58340/3487255860.py) in ?()
      1 import akshare as ak
      2 
----> 3 macro_usa_core_cpi_monthly_se = ak.macro_usa_core_cpi_monthly()
      4 print(macro_usa_core_cpi_monthly_se.name)
      5 print(macro_usa_core_cpi_monthly_se)

[c:\ProgramData\anaconda3\lib\site-packages\akshare\economic\macro_usa.py](file:///C:/ProgramData/anaconda3/lib/site-packages/akshare/economic/macro_usa.py) in ?()
    245     r = requests.get(url, params=params, headers=headers)
    246     temp_se = pd.DataFrame(r.json()["data"]["values"]).iloc[:, :2]
    247     temp_se.index = pd.to_datetime(temp_se.iloc[:, 0])
    248     temp_se = temp_se.iloc[:, 1]
--> 249     temp_df = temp_df.append(temp_se)
    250     temp_df.dropna(inplace=True)
    251     temp_df.sort_index(inplace=True)
    252     temp_df = temp_df.reset_index()

[c:\ProgramData\anaconda3\lib\site-packages\pandas\core\generic.py](file:///C:/ProgramData/anaconda3/lib/site-packages/pandas/core/generic.py) in ?(self, name)
   5985             and name not in self._accessors
   5986             and self._info_axis._can_hold_identifiers_and_holds_name(name)
   5987         ):
   5988             return self[name]
-> 5989         return object.__getattribute__(self, name)

AttributeError: 'Series' object has no attribute 'append'

**To Reproduce**
```python
import akshare as ak

macro_usa_core_cpi_monthly_se = ak.macro_usa_core_cpi_monthly()
print(macro_usa_core_cpi_monthly_se.name)
print(macro_usa_core_cpi_monthly_se)
```

**Comment by albertandking** [comment]
> **Describe the bug** 在获取这两个数据的时候报错，原因是代码使用的pandas版本过低，现在新一点的版本，pandas series没有append函数了，建议升级一下pandas的版本。
> 
> AttributeError Traceback (most recent call last) [~\AppData\Local\Temp\ipykernel_58340\3487255860.py](https://file+.vscode-resource.vscode-cdn.net/c%3A/Git/Quant101/Python/13-%E9%87%91%E8%9E%8D%E6%95%B0%E6%8D%AE%E8%8E%B7%E5%8F%96/~/AppData/Local/Temp/ipykernel_58340/3487255860.py) in ?() 1 import akshare as ak 2 ----> 3 macro_usa_core_cpi_monthly_se = ak.macro_usa_core_cpi_monthly() 4 print(macro_usa_core_cpi_monthly_se.name) 5 print(macro_usa_core_cpi_monthly_se)
> 
> c:\ProgramData\anaconda3\lib\site-packages\akshare\economic\macro_usa.py in ?() 245 r = requests.get(url, params=params, headers=headers) 246 temp_se = pd.DataFrame(r.json()["data"]["values"]).iloc[:, :2] 247 temp_se.index = pd.to_datetime(temp_se.iloc[:, 0]) 248 temp_se = temp_se.iloc[:, 1] --> 249 temp_df = temp_df.append(temp_se) 250 temp_df.dropna(inplace=True) 251 temp_df.sort_index(inplace=True) 252 temp_df = temp_df.reset_index()
> 
> c:\ProgramData\anaconda3\lib\site-packages\pandas\core\generic.py in ?(self, name) 5985 and name not in self._accessors 5986 and self._info_axis._can_hold_identifiers_and_holds_name(name) 5987 ): 5988 return self[name] -> 5989 return object.**getattribute**(self, name)
> 
> AttributeError: 'Series' object has no attribute 'append'
> 
> **To Reproduce**
> 
> ```python
> import akshare as ak
> 
> macro_usa_core_cpi_monthly_se = ak.macro_usa_core_cpi_monthly()
> print(macro_usa_core_cpi_monthly_se.name)
> print(macro_usa_core_cpi_monthly_se)
> ```

感谢反馈问题；后续接口要统一到 pandas.DataFrame 的格式，升级到 AKShare 1.10.55 使用
