### ISSUE TITLE
请求添加美国CPI年率

### ISSUE THREAD

**Issue by yacper** [akfamily/akshare#3969]
目前有jin10的cpi月率，但没有年率
年率数据可以参考：https://data.eastmoney.com/cjsj/foreign_0_12.html

**Comment by albertandking** [comment]
> 目前有jin10的cpi月率，但没有年率 年率数据可以参考：https://data.eastmoney.com/cjsj/foreign_0_12.html

感谢 PR，已新增相关接口，升级到 AKShare 最新版使用
