### ISSUE TITLE
pip install akshare --upgrade 为什么只能更新到1.10.42版本？

### ISSUE THREAD

**Issue by plok1221** [akfamily/akshare#3970]
pip install akshare --upgrade 为什么只能更新到1.10.42版本？很多接口问题是在更新的版本里解决的，但是pip不能安装新版本
![b803996c2ed7dafc2266381050e6af3](https://github.com/akfamily/akshare/assets/18573584/deb1f767-f48a-455b-a5ef-267f6c2efc9c)

**Comment by albertandking** [comment]
> pip install akshare --upgrade 为什么只能更新到1.10.42版本？很多接口问题是在更新的版本里解决的，但是pip不能安装新版本 ![b803996c2ed7dafc2266381050e6af3](https://user-images.githubusercontent.com/18573584/253133267-deb1f767-f48a-455b-a5ef-267f6c2efc9c.png)

不再支持 python 3.7，请升级 python 版本
