### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by laureatian** [akfamily/akshare#3973]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本"Ubuntu 18.04.6 LTS"
2. Python 版本 3.10.10
3. AKShare 版本 1.10.56
4. 接口的名称和代码 akshare/akshare/stock/stock_zh_a_tick_tx.py  def stock_zh_a_tick_tx
5. 接口报错的截图或代码: 获取688589历史交易记录 返回的是空dataframe ，没有报错
6. 期望获得的正确结果 ：返回某个股票历史（2023）某天的每笔成交记录

**Comment by albertandking** [comment]
> 4\. stock_zh_a_tick_tx

参见文档接口说明，该接口暂时不能获取数据
