### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by lan-slot** [akfamily/akshare#3975]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. macos Ventura 13.4
2. python 3.8
3. AKShare 版本 1.10.50
4. 接口的名称和代码: stock_zh_valuation_baidu
5. period="近十年"，或者"全部"，
![FireShot Capture 064 - Bank market power and green bond - paper - Jupyter Notebook - localhost](https://github.com/akfamily/akshare/assets/68606787/96c445eb-fa63-488e-b956-1e7c9e64fd5c)

![FireShot Capture 065 - Bank market power and green bond - paper - Jupyter Notebook - localhost](https://github.com/akfamily/akshare/assets/68606787/580e76b0-064f-42cc-9ef3-4c351c65f087)

6. 期望获得的正确结果: 想获取每个交易日的全部数据。

**Comment by albertandking** [comment]
> 

每个交易日数据只能获取近一年的；主要是数据源的限制

**Comment by lan-slot** [comment]
请问还有没有类似这种，能获取单个股票每个交易日总市值的接口？ ‘stock_a_indicator_lg’这个接口取多了会被封。。。谢谢！

**Comment by lan-slot** [comment]
> Collaborator
请问还有没有类似这种，能获取单个股票每个交易日总市值的接口？ ‘stock_a_indicator_lg’这个接口取多了会被封。。。谢谢！
