### ISSUE TITLE
 ak.get_futures_daily not working well with DCE

### ISSUE THREAD

**Issue by grryaaa** [akfamily/akshare#3976]
**Describe the bug**
When querying futures data using ak.get_futures_daily for DCE, it has such errors:
     ValueError: Excel file format cannot be determined, you must specify an engine manually.
this error started a few weeks ago. It looks like DCE has some thing against this function.

**To Reproduce**

you can simply query DCE with this get_futures_daily for a whole year data, you will see this error.

**Expected behavior**

expected the function call will return the whole year data like with SHFE etc.

**Screenshots**

![image](https://github.com/akfamily/akshare/assets/139524370/5b0ef5dd-5b29-4ba4-a18e-e3bd4fd54a82)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] windows 10
 - Browser [e.g. chrome, safari] chrome
 - Version [e.g. 22] python 3.10.11/akshare 1.10.49

**Comment by albertandking** [comment]
> get_futures_daily

you can fetch data from DCE interface, just like here:
![image](https://github.com/akfamily/akshare/assets/18234520/7c94d27b-268c-40df-9b8c-aa7c6ca79ee0)

**Comment by grryaaa** [comment]
My code is as below:
-------------------------------------------------
import akshare as ak

get_futures_daily_df = ak.get_futures_daily(start_date="20220713", end_date="20230713", market="DCE")
print(get_futures_daily_df)

--------------------------------------------------

it looks like if I query a long time history, it will generate the error like 

![image](https://github.com/akfamily/akshare/assets/139524370/beabc613-dd06-48c9-9349-ecfc9e426360)


I suspect it could be some anti-bot mechanism? 

Even if I query a history like one month, it sometime will have the same error.
