### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by wangjiale1998** [akfamily/akshare#3980]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本
2. Python 版本
Python 3.8.16 (default, Mar  2 2023, 03:18:16) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
3. AKShare 版本 1.9.89
4. 接口的名称和代码
公司概况-巨潮资讯 ak.stock_profile_cninfo()
5. 接口报错的截图或代码
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\Anaconda\envs\chatGLM\lib\site-packages\akshare\stock\stock_profile_cninfo.py", line 107, in stock_profile_cninfo
    count = data_json["count"]
KeyError: 'count'
查看data_json内容，{'resultmsg': '未经授权的访问,code:003 token null ', 'resultcode': 451}
6. 期望获得的正确结果
请维护对应的api接口。

**Comment by JiangJamm** [comment]
<img width="1124" alt="image" src="https://github.com/akfamily/akshare/assets/39955422/965cf42e-4994-4588-a24b-e4622c189856">
看起来接口好像是正常的@wangjiale1998

**Comment by wangjiale1998** [comment]
[](

> <img alt="image" width="1124" src="https://user-images.githubusercontent.com/39955422/253947932-965cf42e-4994-4588-a24b-e4622c189856.png"> 看起来接口好像是正常的@wangjiale1998
![QQ图片20230718163645](https://github.com/akfamily/akshare/assets/34213203/d9e50d2f-ec69-47a2-a254-38cda1fe9ead)
![QQ截图20230718163949](https://github.com/akfamily/akshare/assets/34213203/a030e7c8-d976-4d7e-920b-49e5002a8670)
很奇怪。

**Comment by wangjiale1998** [comment]
> <img alt="image" width="1124" src="https://user-images.githubusercontent.com/39955422/253947932-965cf42e-4994-4588-a24b-e4622c189856.png"> 看起来接口好像是正常的@wangjiale1998

![QQ截图20230718163949](https://github.com/akfamily/akshare/assets/34213203/091c676f-f568-468c-821b-68b2be41b6d8)
感谢回复，但很奇怪我这边还是如此。

**Comment by albertandking** [comment]
> 4\. stock_profile_cninfo

接口正常；升级到最新版使用
