### ISSUE TITLE
`fund_etf_hist_em` 接口无法获取511010基金历史数据

### ISSUE THREAD

**Issue by JiangJamm** [akfamily/akshare#3981]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本 Mac OS 13.2.1 (22D68)
2. Python 版本 Python3.8.7
3. AKShare 版本 1.10.57
4. 接口的名称和代码 `fund_etf_hist_em`
5. 接口报错的截图或代码
<img width="1071" alt="image" src="https://github.com/akfamily/akshare/assets/39955422/4e2f9420-723d-4af4-be14-f8202ce9d2aa">

7. 期望获得的正确结果
该基金链接：http://quote.eastmoney.com/sh511010.html
与该接口说明的链接相同，但无法被查出

**Comment by albertandking** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本 Mac OS 13.2.1 (22D68)
> 2. Python 版本 Python3.8.7
> 3. AKShare 版本 1.10.57
> 4. 接口的名称和代码 `fund_etf_hist_em`
> 5. 接口报错的截图或代码
> 
> <img alt="image" width="1071" src="https://user-images.githubusercontent.com/39955422/253946795-4e2f9420-723d-4af4-be14-f8202ce9d2aa.png">
> 7. 期望获得的正确结果
>    该基金链接：http://quote.eastmoney.com/sh511010.html
>    与该接口说明的链接相同，但无法被查出

感谢反馈问题；已修复，升级到 AKShare 1.10.62 使用
