### ISSUE TITLE
AKShare 接口问题报告申万宏源研究相关接口失效

### ISSUE THREAD

**Issue by xnw176** [akfamily/akshare#3983]
**描述遇到的问题**
1. 操作系统版本  MAC OS 13
2. Python 版本 3.8
3. AKShare 版本 最新
4. 接口的名称和代码。ak.index_analysis_daily_sw 和 ak.index_hist_sw
5. 接口报错的截图或代码
      URL送入request返回502，实际上用浏览器打开URL有相关数据，应该是网上新加了反爬机制。

<img width="898" alt="image" src="https://github.com/akfamily/akshare/assets/82297022/fffe5d7d-10a5-48ac-ac4e-77bec6254b4f">

7. 期望获得的正确结果

**Comment by albertandking** [comment]
> 4\. index_analysis_daily_sw

感谢反馈问题；已修复，升级到 AKShare 1.10.62 使用
