### ISSUE TITLE
是否可以加入雪球数据获取

### ISSUE THREAD

**Issue by inspirits** [akfamily/akshare#3985]
雪球除了A股港股美股股票外，在指数方面比新浪东财包含得更全面，请问能否添加获取相关日K线数据的接口？

数据源网站：https://xueqiu.com/
A股股票：https://xueqiu.com/S/SH600519
A股指数：https://xueqiu.com/S/CSI000300
港股股票：https://xueqiu.com/S/00700
港股指数：https://xueqiu.com/S/HKHSI
美股股票：https://xueqiu.com/S/AAPL
美股指数：https://xueqiu.com/S/.INX

**Comment by albertandking** [comment]
> 雪球除了A股港股美股股票外，在指数方面比新浪东财包含得更全面，请问能否添加获取相关日K线数据的接口？
> 
> 数据源网站：https://xueqiu.com/ A股股票：https://xueqiu.com/S/SH600519 A股指数：https://xueqiu.com/S/CSI000300 港股股票：https://xueqiu.com/S/00700 港股指数：https://xueqiu.com/S/HKHSI 美股股票：https://xueqiu.com/S/AAPL 美股指数：https://xueqiu.com/S/.INX

暂不考虑；
