### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by hpeiyan** [akfamily/akshare#3986]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```
**描述遇到的问题**
1. 操作系统版本
Mac OS 12.6.7
2. Python 版本
3.8
3. AKShare 版本
akshare    1.10.57
4. 接口的名称和代码
```python
接口名称：stock_zh_a_minute
源代码位置：https://github.com/akfamily/akshare/blob/main/akshare/stock/stock_zh_a_sina.py#L374
该接口方法内部还会调用一次 stock_zh_a_daily 的请求
```
5. 接口报错的截图或代码
<img width="1552" alt="image" src="https://github.com/akfamily/akshare/assets/12880598/5c46653d-9f45-4191-8a86-50982f22b424">

6. 期望获得的正确结果
是否不需要调用？

**Comment by albertandking** [comment]
> 

该调用是为了获取复权数据
