### ISSUE TITLE
接口macro_china_lpr返回数据不全

### ISSUE THREAD

**Issue by tj-jiang** [akfamily/akshare#3993]
通过接口macro_china_lpr返回的数据只获得了从 2017-10-27 开始的数据，而接口doc中说明是从1991年开始的数据，而东方财富网上也是有从1991年开始的数据

**Comment by albertandking** [comment]
> 通过接口macro_china_lpr返回的数据只获得了从 2017-10-27 开始的数据，而接口doc中说明是从1991年开始的数据，而东方财富网上也是有从1991年开始的数据

感谢反馈问题；已修复该问题，升级到 AKShare 1.10.66 使用
