### ISSUE TITLE
 同花顺概念指数获取的时候，能否增加时间范围选择？

### ISSUE THREAD

**Issue by 980693651** [akfamily/akshare#3997]
目前的时间范围只能选去从某一年开始，能否增加比如从几号到几号这样的时间范围选择，这样不仅可以选择更便捷，还可以节约查询数据的成本，谢谢

**Comment by albertandking** [comment]
> 目前的时间范围只能选去从某一年开始，能否增加比如从几号到几号这样的时间范围选择，这样不仅可以选择更便捷，还可以节约查询数据的成本，谢谢

暂不能
