### ISSUE TITLE
鸡蛋价格提取出错：ak.futures_egg_price()

### ISSUE THREAD

**Issue by chenjc2011** [akfamily/akshare#3998]
>>> import akshare as ak
>>> df = ak.futures_egg_price()
Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    df = ak.futures_egg_price()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\akshare\futures_derivative\futures_egg.py", line 56, in futures_egg_price
    js_text = soup.find_all("script")[9].string
IndexError: list index out of range

**Comment by albertandking** [comment]
> > > > import akshare as ak
> > > > df = ak.futures_egg_price()
> > > > Traceback (most recent call last):
> > > > File "<pyshell#1>", line 1, in 
> > > > df = ak.futures_egg_price()
> > > > File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\akshare\futures_derivative\futures_egg.py", line 56, in futures_egg_price
> > > > js_text = soup.find_all("script")[9].string
> > > > IndexError: list index out of range

数据源未提供数据；已移除相关接口
