### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by 190237192** [akfamily/akshare#4001]
通过东方财富获取的财务报表数据错误，接口为stock_balance_sheet_by_report_em_df = ak.stock_balance_sheet_by_report_em(symbol="sz002594"),目前我就测试了比亚迪的财务数据，得到的数据和真实财务数据不一样。

**Comment by albertandking** [comment]
> 通过东方财富获取的财务报表数据错误，接口为stock_balance_sheet_by_report_em_df = ak.stock_balance_sheet_by_report_em(symbol="sz002594"),目前我就测试了比亚迪的财务数据，得到的数据和真实财务数据不一样。

可以和目标地址的数据源核对下

**Comment by 190237192** [comment]
不好意思说错了，东方财富是对的，新浪是有问题的，接口为stock_financial_report_sina_df = ak.stock_financial_report_sina(stock="sz002594", symbol="资产负债表")
