### ISSUE TITLE
Ability to configure requests.get timeout in stock_zh_a_hist

### ISSUE THREAD

**Issue by hy-lei** [akfamily/akshare#4003]
用例：当使用stock_zh_a_hist请求一篮子股票历史数据时（e.g. 股票数量大于2000），requests.get的默认参数timeout=None可能使请求失去响应

解决方案：用户可以控制timeout参数跳过失去响应的请求

**Comment by albertandking** [comment]
> 用例：当使用stock_zh_a_hist请求一篮子股票历史数据时（e.g. 股票数量大于2000），requests.get的默认参数timeout=None可能使请求失去响应
> 
> 解决方案：用户可以控制timeout参数跳过失去响应的请求

感谢 PR，已合并
