### ISSUE TITLE
AKShare 接口问题报告 index_level_one_hist_sw

### ISSUE THREAD

**Issue by Opheliayang** [akfamily/akshare#4009]
**环境**
cloud ide
python 3.10.8
akshare 1.10.70

申万一级行业历史行情 index_level_one_hist_sw

![image](https://github.com/akfamily/akshare/assets/8156246/25dc026d-4f03-4623-991a-6d831e1b5df7)

**Comment by albertandking** [comment]
> **环境** cloud ide python 3.10.8 akshare 1.10.70
> 
> 申万一级行业历史行情 index_level_one_hist_sw
> 
> ![image](https://user-images.githubusercontent.com/8156246/255775627-25dc026d-4f03-4623-991a-6d831e1b5df7.png)

已移除该接口；在文档中搜索相关申万的其他接口使用
