### ISSUE TITLE
AKShare 接口问题报告-stock_us_hist_df 

### ISSUE THREAD

**Issue by lyj6668882002** [akfamily/akshare#4010]
东财的美股历史数据的案例报错

import akshare as ak

stock_us_hist_df = ak.stock_us_hist(symbol='105.MTP', period="daily", start_date="19700101", end_date="22220101",
                                    adjust="qfq")
print(stock_us_hist_df)

TypeError: 'NoneType' object is not subscriptable

**Comment by albertandking** [comment]
> 105.MTP

按文档要求输入symbol
