### ISSUE TITLE
在M1 docker linux环境提示缺少py_mini_racer.glibc.so的问题

### ISSUE THREAD

**Issue by kevin-jfzhu** [akfamily/akshare#4012]
Hello,

感谢提供mac arm芯片的dylib文件，目前在mac环境下可以成功使用。但如果需要在m1 docker的linux环境内进行部署（本地测试使用），则会提示找不到py_mini_racer.glibc.so的文件，请问能否也提供此文件呢？

**Comment by albertandking** [comment]
> py_mini_racer.glibc.so

可以在 https://github.com/sqreen/PyMiniRacer/issues 查找
