### ISSUE TITLE
申请获取股票历史流通市值与总市值

### ISSUE THREAD

**Issue by DU1234DUDU** [akfamily/akshare#4014]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本
2. Python 版本
3. AKShare 版本
4. 接口的名称和代码
5. 接口报错的截图或代码
6. 期望获得的正确结果

**Comment by albertandking** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本
> 2. Python 版本
> 3. AKShare 版本
> 4. 接口的名称和代码
> 5. 接口报错的截图或代码
> 6. 期望获得的正确结果

可以在文档中搜索相关内容
