### ISSUE TITLE
get_receipt获取大商所和上期所仓单数据失败

### ISSUE THREAD

**Issue by choir2001** [akfamily/akshare#4017]
已升级到AKShare最新版本

1，上期所和能源所品种
代码：
ak_data=akshare.get_receipt(start_day='20230719', end_day='20230719', vars_list=['CU'])
错误提示：
2023-07-19
第1次链接失败, 最多尝试 20 次
2，大商所品种
代码：
ak_data=akshare.get_receipt(start_day='20230719', end_day='20230719', vars_list=['A'])

会出现以下两种提示，随机出现：
ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

ParserError: Document is empty

**Comment by albertandking** [comment]
> 已升级到AKShare最新版本
> 
> 1，上期所和能源所品种 代码： ak_data=akshare.get_receipt(start_day='20230719', end_day='20230719', vars_list=['CU']) 错误提示： 2023-07-19 第1次链接失败, 最多尝试 20 次 2，大商所品种 代码： ak_data=akshare.get_receipt(start_day='20230719', end_day='20230719', vars_list=['A'])
> 
> 会出现以下两种提示，随机出现： ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
> 
> ParserError: Document is empty

最近几个交易所网站不稳定，需要重复运行几次
