### ISSUE TITLE
“stock_zh_valuation_baidu”接口市盈率数据有误

### ISSUE THREAD

**Issue by Andy-Dihong-Luo** [akfamily/akshare#4020]
如题，调用`stock_zh_valuation_baidu`接口调用的市净率数据与网页直接搜索的结果不一致。
复现代码：
```python
import akshare as ak

[In]: 
stock_zh_valuation_baidu_df = ak.stock_zh_valuation_baidu(symbol="002955", indicator="市净率", period="近一年")
print(stock_zh_valuation_baidu_df)

[Out]:
           date  value
0    2022-08-02   1.55
1    2022-08-03   1.56
2    2022-08-04   1.57
3    2022-08-05   1.57
4    2022-08-06   1.57
..          ...    ...
361  2023-07-29   1.34
362  2023-07-30   1.34
363  2023-07-31   1.34
364  2023-08-01   1.35
365  2023-08-02   1.34

[366 rows x 2 columns]
```
实际网页数据：
![image](https://github.com/akfamily/akshare/assets/128155646/005c1ccc-0a97-4c7e-9a4e-58670315ca3e)

Akshare版本： 1.10.72
Python版本：3.11.4

**Comment by albertandking** [comment]
> 如题，调用`stock_zh_valuation_baidu`接口调用的市净率数据与网页直接搜索的结果不一致。 复现代码：
> 
> ```python
> import akshare as ak
> 
> [In]: 
> stock_zh_valuation_baidu_df = ak.stock_zh_valuation_baidu(symbol="002955", indicator="市净率", period="近一年")
> print(stock_zh_valuation_baidu_df)
> 
> [Out]:
>            date  value
> 0    2022-08-02   1.55
> 1    2022-08-03   1.56
> 2    2022-08-04   1.57
> 3    2022-08-05   1.57
> 4    2022-08-06   1.57
> ..          ...    ...
> 361  2023-07-29   1.34
> 362  2023-07-30   1.34
> 363  2023-07-31   1.34
> 364  2023-08-01   1.35
> 365  2023-08-02   1.34
> 
> [366 rows x 2 columns]
> ```
> 
> 实际网页数据： ![image](https://user-images.githubusercontent.com/128155646/257829344-005c1ccc-0a97-4c7e-9a4e-58670315ca3e.png)
> 
> Akshare版本： 1.10.72 Python版本：3.11.4

哪里不一致？

**Comment by albertandking** [comment]
> 1.46

跟页面 
![image](https://github.com/akfamily/akshare/assets/18234520/e8959620-d86e-4107-a58e-57b2b2f029f7)
一致
