### ISSUE TITLE
能否提供沪深交易所的互动易平台的数据提取？

### ISSUE THREAD

**Issue by firezym** [akfamily/akshare#4021]
深市按照股票代码的互动易：
https://irm.cninfo.com.cn/ircs/company/companyDetail?stockcode=000725&orgId=gssz0000725
沪市按照股票代码的互动平台：
https://sns.sseinfo.com/company.do?uid=196

**Comment by albertandking** [comment]
> 深市按照股票代码的互动易： https://irm.cninfo.com.cn/ircs/company/companyDetail?stockcode=000725&orgId=gssz0000725 沪市按照股票代码的互动平台： https://sns.sseinfo.com/company.do?uid=196

感谢反馈问题；已新增 stock_irm_cninfo 等接口，升级到 AKShare 1.10.73 版本使用

**Comment by firezym** [comment]
@albertandking 非常感谢，我试用一下！
