### ISSUE TITLE
AKShare 接口问题报告申万行业历史行情报错

### ISSUE THREAD

**Issue by Ji1031** [akfamily/akshare#4026]
大佬您好，我是小白用户第一次使用贵平台，依据doc指引，其他数据接口数据导出正常，但是申万一级行业历史行情信息无法导出（直接粘贴了doc教程代码显示报错如下，请大佬指点
![image](https://github.com/akfamily/akshare/assets/141519057/b7c0bb0d-80cd-4354-8290-300c1c88a5d1)

**Comment by xnw176** [comment]
网站的问题，数据暂时无法获取，大概率是网站在更新反爬机制，更新好之前用临时手段关闭了相关接口。

**Comment by Ji1031** [comment]
好的收到！谢谢大佬！

--------------原始邮件--------------
发件人："xnw176 ***@***.***&gt;;
发送时间：2023年8月6日(星期天) 下午2:50
收件人："akfamily/akshare" ***@***.***&gt;;
抄送："Ji1031 ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [akfamily/akshare] AKShare 接口问题报告申万行业历史行情报错 (Issue #4026)
-----------------------------------

 

 
网站的问题，数据暂时无法获取，大概率是网站在更新反爬机制，更新好之前用临时手段关闭了相关接口。

**Comment by albertandking** [comment]
> 好的收到！谢谢大佬！
> […](#)
> --------------原始邮件-------------- 发件人："xnw176 ***@***.***&gt;; 发送时间：2023年8月6日(星期天) 下午2:50 收件人："akfamily/akshare" ***@***.***&gt;; 抄送："Ji1031 ***@***.***&gt;;"Author ***@***.***&gt;; 主题：Re: [akfamily/akshare] AKShare 接口问题报告申万行业历史行情报错 (Issue #4026) ----------------------------------- 网站的问题，数据暂时无法获取，大概率是网站在更新反爬机制，更新好之前用临时手段关闭了相关接口。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

对的
