### ISSUE TITLE
stock_irm_cninfo深交所互动平台，增加返回结果字段

### ISSUE THREAD

**Issue by firezym** [akfamily/akshare#4030]
@albertandking 观察了一下接口返回的数据，建议增加`attachedId`, `attachedContent`,`attachedAuthor`三个字段可以加入到返回的big_df结果中，如果该问题有被回答，回答内容是`attachedContent`,回答者是`attachedAuthor`（`attachedPubDate`似乎都是null暂时没有被用到），这样一个接口访问就能初步返回问和答的所有内容，可能无需再次针对每个问题id去访问`stock_irm_ans_cninfo`。请帮忙看一下，非常感谢~~

```python
def stock_irm_cninfo(symbol: str = "002594") -> pd.DataFrame:
    ...
    big_df.rename(
        columns={
            "indexId": "问题编号",
             ...
            "attachedId": "-",
            "attachedContent": "-",
            "attachedAuthor": "-",
            "attachedPubDate": "-",
             ... 
```

**Comment by albertandking** [comment]
> @albertandking 观察了一下接口返回的数据，建议增加`attachedId`, `attachedContent`,`attachedAuthor`三个字段可以加入到返回的big_df结果中，如果该问题有被回答，回答内容是`attachedContent`,回答者是`attachedAuthor`（`attachedPubDate`似乎都是null暂时没有被用到），这样一个接口访问就能初步返回问和答的所有内容，可能无需再次针对每个问题id去访问`stock_irm_ans_cninfo`。请帮忙看一下，非常感谢~~
> 
> ```python
> def stock_irm_cninfo(symbol: str = "002594") -> pd.DataFrame:
>     ...
>     big_df.rename(
>         columns={
>             "indexId": "问题编号",
>              ...
>             "attachedId": "-",
>             "attachedContent": "-",
>             "attachedAuthor": "-",
>             "attachedPubDate": "-",
>              ... 
> ```

感谢反馈问题；已新增相关字段，升级到 AKShare 1.10.76 使用
