### ISSUE TITLE
[feature]董监高及相关人员持股变动明细

### ISSUE THREAD

**Issue by edwardsun** [akfamily/akshare#4033]
申请增加-董监高及相关人员持股变动明细

http://data.eastmoney.com/executive/list.html

**Comment by albertandking** [comment]
> 申请增加-董监高及相关人员持股变动明细
> 
> http://data.eastmoney.com/executive/list.html

感谢反馈问题；已新增 stock_hold_management_detail_em 接口，升级到 AKShare 1.10.79 使用
