### ISSUE TITLE
[feature]股市日历公司动态

### ISSUE THREAD

**Issue by edwardsun** [akfamily/akshare#4034]
申请增加数据-股市日历-公司动态

http://data.eastmoney.com/gsrl/gsdt.html

感谢

**Comment by albertandking** [comment]
> 申请增加数据-股市日历-公司动态
> 
> http://data.eastmoney.com/gsrl/gsdt.html
> 
> 感谢

已新增 stock_gsrl_gsdt_em 接口，升级到 AKShare 1.10.79 使用
