### ISSUE TITLE
Configure requests.get timeout in stock_individual_info_em

### ISSUE THREAD

**Issue by hy-lei** [akfamily/akshare#4041]
Would like to handle http request hangs when fetching individual stock info for a basket of securities - i.e. stock_individual_info_em(symbol="000001") can hang forever.  Implemented a similar issue in #4003

**Comment by albertandking** [comment]
> Would like to handle http request hangs when fetching individual stock info for a basket of securities - i.e. stock_individual_info_em(symbol="000001") can hang forever. Implemented a similar issue in #4003

Thanks for your issue, have merged your PR, update AKShare to 1.10.81
