### ISSUE TITLE
stock_us_fundamental 接口 403

### ISSUE THREAD

**Issue by kevinningthu** [akfamily/akshare#4055]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本: ios
2. Python 版本: 3.11
3. AKShare 版本: 1.10.83
4. 接口的名称和代码:  stock_us_fundamental_df = ak.stock_us_fundamental(stock="GOOGL", symbol="PE") 
5. 接口报错的截图或代码:  403  
6. 期望获得的正确结果: 正确返回股票对应的PE数据。

**Comment by albertandking** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本: ios
> 2. Python 版本: 3.11
> 3. AKShare 版本: 1.10.83
> 4. 接口的名称和代码:  stock_us_fundamental_df = ak.stock_us_fundamental(stock="GOOGL", symbol="PE")
> 5. 接口报错的截图或代码:  403
> 6. 期望获得的正确结果: 正确返回股票对应的PE数据。

感谢反馈问题；已修复该问题，升级到 AKShare 1.10.84 使用

**Comment by kevinningthu** [comment]
谢谢，效率真高！
