### ISSUE TITLE
[feature]重大合同

### ISSUE THREAD

**Issue by edwardsun** [akfamily/akshare#4061]
您好，
请问近期是否有计划支持个股重大合同的数据?

http://data.eastmoney.com/zdht/mx.html

**Comment by albertandking** [comment]
> 您好， 请问近期是否有计划支持个股重大合同的数据?
> 
> http://data.eastmoney.com/zdht/mx.html

已新增接口 stock_zdhtmx_em，升级到 AKShare 1.10.87 使用
