### ISSUE TITLE
stock_rank_forecast_cninfo接口bug

### ISSUE THREAD

**Issue by xiaojie-user** [akfamily/akshare#4063]
akshare\stock\stock_rank_forecast.py中stock_rank_forecast_cninfo抛出异常：
{'resultcode': 451, 'resultmsg': '未经授权的访问,code:003 token null '}

**Comment by albertandking** [comment]
> akshare\stock\stock_rank_forecast.py中stock_rank_forecast_cninfo抛出异常： {'resultcode': 451, 'resultmsg': '未经授权的访问,code:003 token null '}

感谢反馈问题；已修复该问题，升级到 AKShare 1.80.86 使用
