### ISSUE TITLE
ak.fund_portfolio_bond_hold_em 基金债券持仓明细报错

### ISSUE THREAD

**Issue by Pscjiayou** [akfamily/akshare#4064]
**Describe the bug**
**fund_portfolio_bond_hold_em(symbol="320007", date="2016")**
当我想获取320007基金2016年每季度的债券持仓时，指令报错。报错显示，输出dataframe中“占净值比例”无法计算。

**Expected behavior**
如akshare网站上该条指令的template所示，显示基金对应年份每季度的债券持仓

**Screenshots**
截图链接：https://imgse.com/i/pP3VjzQ

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: edge -> anaconda -> jupyter notebook (python edittion)
 - Version: Python 3

**Comment by albertandking** [comment]
> 2016

接口正常；请核对数据源
