### ISSUE TITLE
美股指数的市净率/市盈率/分红率等

### ISSUE THREAD

**Issue by kevinningthu** [akfamily/akshare#4068]
请问下有办法获取 美股指数（标普500/纳指100等）的市净率/市盈率/分红率等数据吗

类似于 index_value_hist_funddb 或者 stock_index_pe_lg/stock_market_pb_lg接口

**Comment by albertandking** [comment]
> 请问下有办法获取 美股指数（标普500/纳指100等）的市净率/市盈率/分红率等数据吗
> 
> 类似于 index_value_hist_funddb 或者 stock_index_pe_lg/stock_market_pb_lg接口

木有
