### ISSUE TITLE
AKShare 财报接口问题

### ISSUE THREAD

**Issue by lucther** [akfamily/akshare#4072]
使用接口stock_profit_sheet_by_report_em、stock_financial_report_sina获取现金流量表都没有固定资产折旧、无形资产摊销等的数据。好像是补充资产下面的数据都没有。

**Comment by albertandking** [comment]
> 使用接口stock_profit_sheet_by_report_em、stock_financial_report_sina获取现金流量表都没有固定资产折旧、无形资产摊销等的数据。好像是补充资产下面的数据都没有。

在相应的接口里面可以获取到

**Comment by lucther** [comment]
> > 使用接口stock_profit_sheet_by_report_em、stock_financial_report_sina获取现金流量表都没有固定资产折旧、无形资产摊销等的数据。好像是补充资产下面的数据都没有。
> 
> 在相应的接口里面可以获取到

确实找不到相应的数据。
