### ISSUE TITLE
[bug]stock_share_hold_change_szse

### ISSUE THREAD

**Issue by edwardsun** [akfamily/akshare#4079]
您好，
我发现stock_share_hold_change_szse这个函数好像有问题。
ak.stock_share_hold_change_szse(symbol='全部')虽然好像遍历了所有页面，但只有前面的20个数据行是unique的。(after dataframe.drop_duplicates() )
麻烦您看看。谢谢

**Comment by albertandking** [comment]
> 您好， 我发现stock_share_hold_change_szse这个函数好像有问题。 ak.stock_share_hold_change_szse(symbol='全部')虽然好像遍历了所有页面，但只有前面的20个数据行是unique的。(after dataframe.drop_duplicates() ) 麻烦您看看。谢谢

感谢反馈问题；已修复该问题，升级到 AKShare 1.10.91 版本
