### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by scrod7** [akfamily/akshare#4093]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本 macOS 13.4 (22F66)
2. Python 版本 3.11.2
3. AKShare 版本 1.10.94
4. 接口的名称和代码
index_investing_global
index_investing_global_df = ak.index_investing_global(area="中国", symbol="上证指数", period="每日",
                                                          start_date="20100101", end_date="20220808")
    print(index_investing_global_df)

6. 接口报错的截图或代码
<img width="1149" alt="image" src="https://github.com/akfamily/akshare/assets/16398331/2cb6fc69-465c-4232-84ca-60a197323f84">

抓包看接口403, 但是直接访问网站无问题
<img width="1090" alt="image" src="https://github.com/akfamily/akshare/assets/16398331/c2ecf861-f3fc-468a-9fe3-a609aaf4245b">

8. 期望获得的正确结果
<img width="759" alt="image" src="https://github.com/akfamily/akshare/assets/16398331/0ea1c511-11bc-4bf9-bc47-8410e682bf86">

**Comment by albertandking** [comment]
> 4\. index_investing_global

注意查看文档接口说明
