### ISSUE TITLE
ak.macro_china_ctci 读取超时

### ISSUE THREAD

**Issue by congcong009** [akfamily/akshare#4103]
**Describe the bug**
调用 ak.macro_china_ctci 时，出现如下报错

> Traceback (most recent call last):
  File ",\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "...env\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "...env\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "...env\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "...env\lib\site-packages\urllib3\connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "...env\lib\site-packages\urllib3\connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "...env\lib\http\client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "...env\lib\http\client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "...env\lib\http\client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "...env\lib\http\client.py", line 1011, in _send_output
    self.send(msg)
  File "...env\lib\http\client.py", line 951, in send
    self.connect()
  File "...env\lib\site-packages\urllib3\connection.py", line 205, in connect
    conn = self._new_conn()
  File "...env\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0000023B99658130>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "...env\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "...env\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "...env\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='59.252.41.60', port=80): Max retries exceeded with url: /portal//out/dm?t=1578298533594 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023B99658130>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "..env/api_commond.py", line 15, in <module>
    df = pd.DataFrame(ak.macro_china_ctci()).reset_index()
  File "...env\lib\site-packages\akshare\economic\macro_china.py", line 1535, in macro_china_ctci
    r = requests.get(url)
  File "...env\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "...env\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "...env\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "...env\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "...env\lib\site-packages\requests\adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='59.252.41.60', port=80): Max retries exceeded with url: /portal//out/dm?t=1578298533594 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023B99658130>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

**Expected behavior**
应符合 [接口地址](https://akshare.xyz/data/macro/macro.html#id85)

**版本**
python 3.8
akshare 1.10.98

**Comment by albertandking** [comment]
> **Describe the bug** 调用 ak.macro_china_ctci 时，出现如下报错
> 
> > Traceback (most recent call last):
> > File ",\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
> > conn = connection.create_connection(
> > File "...env\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
> > raise err
> > File "...env\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
> > sock.connect(sa)
> > TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
> > During handling of the above exception, another exception occurred:
> > Traceback (most recent call last):
> > File "...env\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
> > httplib_response = self._make_request(
> > File "...env\lib\site-packages\urllib3\connectionpool.py", line 398, in _make_request
> > conn.request(method, url, **httplib_request_kw)
> > File "...env\lib\site-packages\urllib3\connection.py", line 239, in request
> > super(HTTPConnection, self).request(method, url, body=body, headers=headers)
> > File "...env\lib\http\client.py", line 1256, in request
> > self._send_request(method, url, body, headers, encode_chunked)
> > File "...env\lib\http\client.py", line 1302, in _send_request
> > self.endheaders(body, encode_chunked=encode_chunked)
> > File "...env\lib\http\client.py", line 1251, in endheaders
> > self._send_output(message_body, encode_chunked=encode_chunked)
> > File "...env\lib\http\client.py", line 1011, in _send_output
> > self.send(msg)
> > File "...env\lib\http\client.py", line 951, in send
> > self.connect()
> > File "...env\lib\site-packages\urllib3\connection.py", line 205, in connect
> > conn = self._new_conn()
> > File "...env\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
> > raise NewConnectionError(
> > urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0000023B99658130>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
> > During handling of the above exception, another exception occurred:
> > Traceback (most recent call last):
> > File "...env\lib\site-packages\requests\adapters.py", line 489, in send
> > resp = conn.urlopen(
> > File "...env\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
> > retries = retries.increment(
> > File "...env\lib\site-packages\urllib3\util\retry.py", line 592, in increment
> > raise MaxRetryError(_pool, url, error or ResponseError(cause))
> > urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='59.252.41.60', port=80): Max retries exceeded with url: /portal//out/dm?t=1578298533594 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023B99658130>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
> > During handling of the above exception, another exception occurred:
> > Traceback (most recent call last):
> > File "..env/api_commond.py", line 15, in 
> > df = pd.DataFrame(ak.macro_china_ctci()).reset_index()
> > File "...env\lib\site-packages\akshare\economic\macro_china.py", line 1535, in macro_china_ctci
> > r = requests.get(url)
> > File "...env\lib\site-packages\requests\api.py", line 73, in get
> > return request("get", url, params=params, **kwargs)
> > File "...env\lib\site-packages\requests\api.py", line 59, in request
> > return session.request(method=method, url=url, **kwargs)
> > File "...env\lib\site-packages\requests\sessions.py", line 587, in request
> > resp = self.send(prep, **send_kwargs)
> > File "...env\lib\site-packages\requests\sessions.py", line 701, in send
> > r = adapter.send(request, **kwargs)
> > File "...env\lib\site-packages\requests\adapters.py", line 565, in send
> > raise ConnectionError(e, request=request)
> > requests.exceptions.ConnectionError: HTTPConnectionPool(host='59.252.41.60', port=80): Max retries exceeded with url: /portal//out/dm?t=1578298533594 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023B99658130>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
> 
> **Expected behavior** 应符合 [接口地址](https://akshare.xyz/data/macro/macro.html#id85)
> 
> **版本** python 3.8 akshare 1.10.98

由于数据源没有数据，已计划移除相关接口
