### ISSUE TITLE
郑商所的会员持仓排行榜从23年开始一直返回的是空值

### ISSUE THREAD

**Issue by heartwxmddd** [akfamily/akshare#4105]
**描述遇到的问题**

4. 接口的名称和代码
5. 接口报错的截图或代码
![image](https://github.com/akfamily/akshare/assets/90307780/31ba6b2b-b1d6-4056-80de-fefbd4683550)

本人从230103一直试到了09，一直为空，18年-22年底没问题

**Comment by albertandking** [comment]
> **描述遇到的问题**
> 
> 4. 接口的名称和代码
> 5. 接口报错的截图或代码
>    ![image](https://user-images.githubusercontent.com/90307780/265641514-31ba6b2b-b1d6-4056-80de-fefbd4683550.png)
> 
> 本人从230103一直试到了09，一直为空，18年-22年底没问题

接口正常；升级到最新版使用
