### ISSUE TITLE
概念板块的同花顺指数当天数据异常

### ISSUE THREAD

**Issue by heiying777** [akfamily/akshare#4107]
概念板块的同花顺指数，昨晚获取的数据和同花顺客户端的对应不上，但今天早上再次获取又能对应上，是数据有延迟吗

**Comment by albertandking** [comment]
> 概念板块的同花顺指数，昨晚获取的数据和同花顺客户端的对应不上，但今天早上再次获取又能对应上，是数据有延迟吗

可以分时段调取在本地测试下
