### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by szgz** [akfamily/akshare#4113]
**描述遇到的问题**
1. 操作系统版本
2. Python 版本
3. AKShare 版本
akshare-1.11.1
5. 接口的名称和代码
stock_a_below_net_asset_statistics
7. 源程序
    :param symbol: choice of {"全部A股", "沪深300"}
    :type symbol: str
    :return: 创新高和新低的股票数量
    :rtype: pandas.DataFrame
    """
    symbol_map = {
        "全部A股": "1",
        "沪深300": "000300.XSHG"
    }
9. 可以增加两个参数，并修改return的注释：
    :param symbol: choice of {"全部A股", "沪深300", "上证50", "中证500"}
    :type symbol: str
    :return: 破净的股票数量
    :rtype: pandas.DataFrame
    """
    symbol_map = {
        "全部A股": "1",
        "沪深300": "000300.XSHG",
        "上证50": "000016.SH",
        "中证500": "000905.SH"
    }

**Comment by albertandking** [comment]
> **描述遇到的问题**
> 
> 1. 操作系统版本
> 2. Python 版本
> 3. AKShare 版本
>    akshare-1.11.1
> 4. 接口的名称和代码
>    stock_a_below_net_asset_statistics
> 5. 源程序
>    :param symbol: choice of {"全部A股", "沪深300"}
>    :type symbol: str
>    :return: 创新高和新低的股票数量
>    :rtype: pandas.DataFrame
>    """
>    symbol_map = {
>    "全部A股": "1",
>    "沪深300": "000300.XSHG"
>    }
> 6. 可以增加两个参数，并修改return的注释：
>    :param symbol: choice of {"全部A股", "沪深300", "上证50", "中证500"}
>    :type symbol: str
>    :return: 破净的股票数量
>    :rtype: pandas.DataFrame
>    """
>    symbol_map = {
>    "全部A股": "1",
>    "沪深300": "000300.XSHG",
>    "上证50": "000016.SH",
>    "中证500": "000905.SH"
>    }

感谢反馈问题，已修复该问题，升级到 AKShare 1.11.2 使用
