### ISSUE TITLE
fund_etf_hist_em()和fund_lof_hist_em()接口大概率连接失败

### ISSUE THREAD

**Issue by kiddliulr** [akfamily/akshare#4117]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本---MacOS 13.5 (22G74)
2. Python 版本---3.8
3. AKShare 版本---1.11.3
4. 接口的名称和代码---fund_etf_hist_em() + fund_lof_hist_em()
5. 接口报错的截图或代码
仅执行上述2个接口，大概率出现如下报错：
SSLError: HTTPSConnectionPool(host='push2his.eastmoney.com', port=443): Max retries exceeded with url: /api/qt/stock/kline/get?fields1=f1%2Cf2%2Cf3%2Cf4%2Cf5%2Cf6&fields2=f51%2Cf52%2Cf53%2Cf54%2Cf55%2Cf56%2Cf57%2Cf58%2Cf59%2Cf60%2Cf61%2Cf116&ut=7eea3edcaed734bea9cbfc24409ed989&klt=101&fqt=2&beg=19700101&end=20500101&_=1623766962675&secid=0.159901 (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:997)')))
7. 期望获得的正确结果---正常稳定连接目标地址

**Comment by albertandking** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本---MacOS 13.5 (22G74)
> 2. Python 版本---3.8
> 3. AKShare 版本---1.11.3
> 4. 接口的名称和代码---fund_etf_hist_em() + fund_lof_hist_em()
> 5. 接口报错的截图或代码
>    仅执行上述2个接口，大概率出现如下报错：
>    SSLError: HTTPSConnectionPool(host='push2his.eastmoney.com', port=443): Max retries exceeded with url: /api/qt/stock/kline/get?fields1=f1%2Cf2%2Cf3%2Cf4%2Cf5%2Cf6&fields2=f51%2Cf52%2Cf53%2Cf54%2Cf55%2Cf56%2Cf57%2Cf58%2Cf59%2Cf60%2Cf61%2Cf116&ut=7eea3edcaed734bea9cbfc24409ed989&klt=101&fqt=2&beg=19700101&end=20500101&_=1623766962675&secid=0.159901 (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:997)')))
> 6. 期望获得的正确结果---正常稳定连接目标地址

这两个接口都比较稳定；建议检查下本地的网络配置且设置访问的频率

**Comment by kiddliulr** [comment]
谢谢反馈，看起来很可能是访问频率太高触发了网站的反爬虫机制。我这边改进一下代码，减少不必要的访问次数。
