### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by caosiqiao4000** [akfamily/akshare#4120]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本  Windows11 专业版
2. Python 版本    3.10.10
3. AKShare 版本   1.11.5
4. 接口的名称和代码      
        futures_main_sina_hist = ak.futures_main_sina(symbol='V0', start_date='20170916',end_date='20230915')
6. 接口报错的截图或代码
        
![1694758923612](https://github.com/akfamily/akshare/assets/3088352/2b3c9f07-7e70-4047-96f6-9806ce95d393)

8. 期望获得的正确结果
    不报错就行了

**Comment by albertandking** [comment]
> 4\. 20230915

接口正常

**Comment by caosiqiao4000** [comment]
好是
