### ISSUE TITLE
news_economic_baidu 接口获取不到数据

### ISSUE THREAD

**Issue by fghhunter** [akfamily/akshare#4124]
**描述遇到的问题**
1. 操作系统版本 阿里云ECS云服务器win10
2. Python 版本 3.11.5
3. AKShare 版本 1.11.7
4. 接口的名称和代码 全球宏观-全球宏观事件 news_economic_baidu
5. 接口报错的截图或代码 python return: empty dataframe columns:[] index:[]
6. 期望获得的正确结果
PS：在个人电脑上可以正确返回数据，但云服务器上不行，接口未返回错误原因，无法调整。

**Comment by fghhunter** [comment]
其他接口可以正常返回数据，
这个接口ak.currency_boc_safe()是加了如下设置才在云服务器上获取成功的
import ssl
ssl._create_default_https_context = ssl._create_unverified_context

**Comment by albertandking** [comment]
> **描述遇到的问题**
> 
> 1. 操作系统版本 阿里云ECS云服务器win10
> 2. Python 版本 3.11.5
> 3. AKShare 版本 1.11.7
> 4. 接口的名称和代码 全球宏观-全球宏观事件 news_economic_baidu
> 5. 接口报错的截图或代码 python return: empty dataframe columns:[] index:[]
> 6. 期望获得的正确结果
>    PS：在个人电脑上可以正确返回数据，但云服务器上不行，接口未返回错误原因，无法调整。

接口正常
