### ISSUE TITLE
中债指数-新综合指数-净价数据获取不到

### ISSUE THREAD

**Issue by none2003** [akfamily/akshare#4127]
**描述遇到的问题**
1. 操作系统版本： Windows 11

2. Python 版本：3.9

3. AKShare 版本：1.11.9

4. 接口的名称和代码：bond_new_composite_index_cbond
`bond_new_composite_index_cbond_df = ak.bond_new_composite_index_cbond(indicator="净价", period="总值")`

5. 接口报错的截图或代码：
根据上面参数查询接口返回的结果都是NaN，且无法查询最新一天的结果，比如2023-09-17查询的时候，只返回最新14号的结果，而其实可以看到15号的结果的。下面是返回的dataframe最后几行：
5432,2023-09-14,NaN
5431,2023-09-13,NaN
5430,2023-09-12,NaN
5429,2023-09-11,NaN
5428,2023-09-10,NaN
5427,2023-09-07,NaN

6. 期望获得的正确结果
根据中国债券信息网https://yield.chinabond.com.cn/cbweb-mn/indices/single_index_query 的查询结果，
2023-09-14净价102.3466
2023-09-15净价102.3109

**Comment by albertandking** [comment]
> **描述遇到的问题**
> 
> 1. 操作系统版本： Windows 11
> 2. Python 版本：3.9
> 3. AKShare 版本：1.11.9
> 4. 接口的名称和代码：bond_new_composite_index_cbond
>    `bond_new_composite_index_cbond_df = ak.bond_new_composite_index_cbond(indicator="净价", period="总值")`
> 5. 接口报错的截图或代码：
>    根据上面参数查询接口返回的结果都是NaN，且无法查询最新一天的结果，比如2023-09-17查询的时候，只返回最新14号的结果，而其实可以看到15号的结果的。下面是返回的dataframe最后几行：
>    5432,2023-09-14,NaN
>    5431,2023-09-13,NaN
>    5430,2023-09-12,NaN
>    5429,2023-09-11,NaN
>    5428,2023-09-10,NaN
>    5427,2023-09-07,NaN
> 6. 期望获得的正确结果
>    根据中国债券信息网https://yield.chinabond.com.cn/cbweb-mn/indices/single_index_query 的查询结果，
>    2023-09-14净价102.3466
>    2023-09-15净价102.3109

感谢反馈问题，已修复，升级到 AKShare 1.11.11 使用

**Comment by none2003** [comment]
Hi @albertandking 

谢谢你的及时响应，关于获取数据为NaN的问题，证实在新的1.11.11上已经修复了。

但是，最新一天的数据获取不到的问题依旧存在，比如现在是2023年9月21日 23:34，中债网站上已经可以获取到21日这一天的数据了，但是akshare的接口还不行，还请再看看，我尝试用1.11.13，问题仍然存在。

谢谢。
