### ISSUE TITLE
同花顺行业一览表拿不到code

### ISSUE THREAD

**Issue by manyhelp** [akfamily/akshare#4128]
接口: stock_board_industry_summary_ths 拿不到code

要优化下代码。

**Comment by albertandking** [comment]
> 接口: stock_board_industry_summary_ths 拿不到code
> 
> 要优化下代码。

跟数据源保持一致

**Comment by manyhelp** [comment]
明明可以从href地址中拿到code的。 @albertandking

**Comment by albertandking** [comment]
> 明明可以从href地址中拿到code的。 @albertandking

建议从：stock_board_industry_name_ths 接口获取代码；stock_board_industry_summary_ths 返回数据与数据源保持一致
