### ISSUE TITLE
macro_china_nbs_nation运行出错

### ISSUE THREAD

**Issue by xldistance** [akfamily/akshare#4132]
Version v1.11.11
```
Traceback (most recent call last):
  File "H:\Desktop\macro_china_nbs.py", line 262, in <module>
    macro_china_nbs_nation_df = macro_china_nbs_nation(
                                ^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Desktop\macro_china_nbs.py", line 138, in macro_china_nbs_nation
    data_ndarray = np.reshape(temp_df["data"], (len(row_name), len(column_name)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<__array_function__ internals>", line 180, in reshape
  File "C:\Users\xldistance\AppData\Local\Programs\Python\Python311\Lib\site-packages\numpy\core\fromnumeric.py", line 298, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xldistance\AppData\Local\Programs\Python\Python311\Lib\site-packages\numpy\core\fromnumeric.py", line 54, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xldistance\AppData\Local\Programs\Python\Python311\Lib\site-packages\numpy\core\fromnumeric.py", line 47, in _wrapit
    result = wrap(result)
             ^^^^^^^^^^^^
  File "C:\Users\xldistance\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\generic.py", line 2107, in __array_wrap__
    return self._constructor(res, **d).__finalize__(self, method="__array_wrap__")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xldistance\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\series.py", line 461, in __init__
    com.require_length_match(data, index)
  File "C:\Users\xldistance\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\common.py", line 561, in require_length_match
    raise ValueError(
ValueError: Length of values (76) does not match length of index (988)
```

**Comment by albertandking** [comment]
> Version v1.11.11
> 
> ```
> Traceback (most recent call last):
>   File "H:\Desktop\macro_china_nbs.py", line 262, in <module>
>     macro_china_nbs_nation_df = macro_china_nbs_nation(
>                                 ^^^^^^^^^^^^^^^^^^^^^^^
>   File "H:\Desktop\macro_china_nbs.py", line 138, in macro_china_nbs_nation
>     data_ndarray = np.reshape(temp_df["data"], (len(row_name), len(column_name)))
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "<__array_function__ internals>", line 180, in reshape
>   File "C:\Users\xldistance\AppData\Local\Programs\Python\Python311\Lib\site-packages\numpy\core\fromnumeric.py", line 298, in reshape
>     return _wrapfunc(a, 'reshape', newshape, order=order)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\xldistance\AppData\Local\Programs\Python\Python311\Lib\site-packages\numpy\core\fromnumeric.py", line 54, in _wrapfunc
>     return _wrapit(obj, method, *args, **kwds)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\xldistance\AppData\Local\Programs\Python\Python311\Lib\site-packages\numpy\core\fromnumeric.py", line 47, in _wrapit
>     result = wrap(result)
>              ^^^^^^^^^^^^
>   File "C:\Users\xldistance\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\generic.py", line 2107, in __array_wrap__
>     return self._constructor(res, **d).__finalize__(self, method="__array_wrap__")
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\xldistance\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\series.py", line 461, in __init__
>     com.require_length_match(data, index)
>   File "C:\Users\xldistance\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\common.py", line 561, in require_length_match
>     raise ValueError(
> ValueError: Length of values (76) does not match length of index (988)
> ```

接口正常

**Comment by xldistance** [comment]
运行到data_ndarray = np.reshape(temp_df["data"], (len(row_name), len(column_name)))就会出错，打印出来的row_name,column_name,temp_df["data"]如下
```
0           企业单位数_本月末(个)
1            亏损企业_本月末(个)
2           亏损企业_上年同期(个)
3             亏损企业_增减(%)
4         流动资产合计_本月末(亿元)
             ...
71     应交增值税_上年同期累计值(亿元)
72         应交增值税_累计增长(%)
73        平均用工人数_累计值(万人)
74    平均用工人数_上年同期累计值(万人)
75        平均用工人数_累计增长(%)
Name: fname, Length: 76, dtype: object 0      2023年8月
1      2023年7月
2      2023年6月
3      2023年5月
4      2023年4月
5      2023年3月
6      2023年2月
7      2023年1月
8     2022年12月
9     2022年11月
10    2022年10月
11     2022年9月
12     2022年8月
Name: fname, dtype: object
0           NaN
1      477076.0
2      476369.0
3      475532.0
4      475226.0
         ...
983        -1.8
984        -1.7
985        -1.3
986        -1.1
987        -1.0
Name: data, Length: 988, dtype: float64
```

**Comment by albertandking** [comment]
> 运行到data_ndarray = np.reshape(temp_df["data"], (len(row_name), len(column_name)))就会出错，打印出来的row_name,column_name,temp_df["data"]如下
> 
> ```
> 0           企业单位数_本月末(个)
> 1            亏损企业_本月末(个)
> 2           亏损企业_上年同期(个)
> 3             亏损企业_增减(%)
> 4         流动资产合计_本月末(亿元)
>              ...
> 71     应交增值税_上年同期累计值(亿元)
> 72         应交增值税_累计增长(%)
> 73        平均用工人数_累计值(万人)
> 74    平均用工人数_上年同期累计值(万人)
> 75        平均用工人数_累计增长(%)
> Name: fname, Length: 76, dtype: object 0      2023年8月
> 1      2023年7月
> 2      2023年6月
> 3      2023年5月
> 4      2023年4月
> 5      2023年3月
> 6      2023年2月
> 7      2023年1月
> 8     2022年12月
> 9     2022年11月
> 10    2022年10月
> 11     2022年9月
> 12     2022年8月
> Name: fname, dtype: object
> 0           NaN
> 1      477076.0
> 2      476369.0
> 3      475532.0
> 4      475226.0
>          ...
> 983        -1.8
> 984        -1.7
> 985        -1.3
> 986        -1.1
> 987        -1.0
> Name: data, Length: 988, dtype: float64
> ```

方便的话提供下调用调用代码

**Comment by xldistance** [comment]
数据是有的，在赋值data_ndarray时出错
![QQ截图20230919145115](https://github.com/akfamily/akshare/assets/29418474/91754106-240f-4ce6-b173-a00b243b34e5)

**Comment by xldistance** [comment]
macro_china_nbs_region也是运行到data_ndarray = np.reshape(temp_df["data"], (len(row_name), len(column_name)))出错

**Comment by albertandking** [comment]
> 数据是有的，在赋值data_ndarray时出错 ![QQ截图20230919145115](https://user-images.githubusercontent.com/29418474/268865999-91754106-240f-4ce6-b173-a00b243b34e5.jpg)

升级 pandas 到最新版试试，目前接口正常
