### ISSUE TITLE
提个建议：写代码还是严谨点比较好

### ISSUE THREAD

**Issue by manyhelp** [akfamily/akshare#4133]
接口: stock_board_industry_summary_ths 拿不到code

返回数据里面明明有code，为了应付了事，不处理href里的code

提交的issues直接关闭了事，都没时间去看一下问题。哪怕看一眼，也不会着急关闭issues。

page明明从第一页开始获取了一次，for里面又继续获取一次。

包括下面源码里的多余代码，for里面获取到了这个数据，也不剔除该代码。

` # 处理遗漏的板块
    url = "http://q.10jqka.com.cn/gn/detail/code/301558/"
    r = requests.get(url, headers=headers)
    soup = BeautifulSoup(r.text, "lxml")`

**Comment by albertandking** [comment]
> 接口: stock_board_industry_summary_ths 拿不到code
> 
> 返回数据里面明明有code，为了应付了事，不处理href里的code
> 
> 提交的issues直接关闭了事，都没时间去看一下问题。哪怕看一眼，也不会着急关闭issues。
> 
> page明明从第一页开始获取了一次，for里面又继续获取一次。
> 
> 包括下面源码里的多余代码，for里面获取到了这个数据，也不剔除该代码。
> 
> ` # 处理遗漏的板块 url = "http://q.10jqka.com.cn/gn/detail/code/301558/" r = requests.get(url, headers=headers) soup = BeautifulSoup(r.text, "lxml")`

1. 已回复 issues；
2. `处理遗漏的板块` 是数据源有缺失需要补充的内容；
3. for 循环是为了保持代码一致性>性能
4. 会不断提高代码质量，也建议组合使用多个接口，欢迎贡献代码
