### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by wangze1219** [akfamily/akshare#4140]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本
win11
2. Python 版本
3.9
3. AKShare 版本
1.11.13
5. 接口的名称和代码
migration_scale_baidu
import akshare as ak
df = ak.migration_scale_baidu(area="浙江省", indicator="move_in", start_date="20190112", end_date="20200201")
print(df)
6. 接口报错的截图或代码
ValueError: Length mismatch: Expected axis has 0 elements, new values have 1 elements
7. 期望获得的正确结果

**Comment by albertandking** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本
>    win11
> 2. Python 版本
>    3.9
> 3. AKShare 版本
>    1.11.13
> 4. 接口的名称和代码
>    migration_scale_baidu
>    import akshare as ak
>    df = ak.migration_scale_baidu(area="浙江省", indicator="move_in", start_date="20190112", end_date="20200201")
>    print(df)
> 5. 接口报错的截图或代码
>    ValueError: Length mismatch: Expected axis has 0 elements, new values have 1 elements
> 6. 期望获得的正确结果

感谢反馈问题，已修复该问题，升级到 AKShare 1.11.14 使用
