### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by Jayson-Li** [akfamily/akshare#4141]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本
win11
3. Python 版本
3.9
5. AKShare 版本
1.2.80
7. 接口的名称和代码
hsi_index_daily_sina_df = ak.stock_hk_index_daily_sina(symbol="HSI")
9. 接口报错的截图或代码
AttributeError: module 'akshare' has no attribute 'stock_hk_index_daily_sina'

11. 期望获得的正确结果

**Comment by albertandking** [comment]
> 4\. stock_hk_index_daily_sina

接口正常
