### ISSUE TITLE
为“财务报表-东财”接口增加对已退市股票的财务报表获取支持

### ISSUE THREAD

**Issue by cty198** [akfamily/akshare#4143]
**发现问题：**
对于已退市股票，使用“财务报表-东财”获取三大报表，返回为空，以下讨论以“000013” 石化A为例。

**问题分析：**
通过观察akshare的源代码文档，该接口对应的目标页面为：
**link 1：**https://emweb.securities.eastmoney.com/PC_HSF10/NewFinanceAnalysis/Index?type=web&code=sz000013#lrb-0
若传入证券代码为“sz000013”，该页面可显示ST石化的相关信息，但三大报表均无数据。

进一步尝试在东财网页搜索000013对应的页面，发现在以下页面中，存在已退市的000013在退市前的三大报表：
**link 2：**https://emweb.securities.eastmoney.com/pc_hsf10/pages/index.html?type=web&code=SZ000013&color=b#/cwfx/zcfzb
可尝试已退市上证代码SH600003，同样可以在link 2中获取到历史财务数据

**需求探讨：**
是否可以针对上述第二条链接，增加对已退市股票财务报表的获取支持，或增加针对已退市代码专用的财务报表接口。

**更新：**

尝试根据上述link2写了个获取退市股票财报的接口，供参考
测试了一下，返回的列字段和现有akshare接口返回的字段是一致的

[Delisted_Stock_Report_Crawler_em.zip](https://github.com/akfamily/akshare/files/12717453/Delisted_Stock_Report_Crawler_em.zip)

**Comment by cty198** [comment]
> > 财务报表-东财
> 
> 感谢反馈及提供解决方案，已新增 stock_cash_flow_sheet_by_report_delisted_em 等接口，升级到 AKShare 1.11.45 使用

感谢更新，也可以正常回去退市公司财务报表。
经测试，发现退市公司财务报表的dataframe是按时间正序，而正常的东财财务报表接口dataframe是按时间倒序，希望两个接口的数据排序可以统一，感谢！

**Comment by albertandking** [comment]
> stock_cash_flow_sheet_by_report_delisted_em

已同一排序方式，升级到 AKShare 1.11.56 使用
