### ISSUE TITLE
AKShare 接口：stock_dividents_cninfo问题

### ISSUE THREAD

**Issue by insight-01** [akfamily/akshare#4144]
**描述遇到的问题**
1. 操作系统版本: **win10**
2. Python 版本: **3.10**
3. AKShare 版本: **1.11.14**
4. 接口的名称和代码: **stock_dividents_cninfo**
5. 接口报错的截图或代码
![Snipaste_2023-09-25_14-54-59](https://github.com/akfamily/akshare/assets/79095234/31981174-aec1-49cd-ae12-5e1f68a0cc94)
![Snipaste_2023-09-25_14-55-15](https://github.com/akfamily/akshare/assets/79095234/2fe7a1f1-39fe-4c07-9769-fdf6104955c8)
**这个是错误信息和返回的信息，这个接口是不是没用了,我使用的时候没有频繁请求，第一次请求就报这个错!请问是什么原因?谢谢!**

**Comment by albertandking** [comment]
> **描述遇到的问题**
> 
> 1. 操作系统版本: **win10**
> 2. Python 版本: **3.10**
> 3. AKShare 版本: **1.11.14**
> 4. 接口的名称和代码: **stock_dividents_cninfo**
> 5. 接口报错的截图或代码
>    ![Snipaste_2023-09-25_14-54-59](https://user-images.githubusercontent.com/79095234/270254989-31981174-aec1-49cd-ae12-5e1f68a0cc94.png)
>    ![Snipaste_2023-09-25_14-55-15](https://user-images.githubusercontent.com/79095234/270255061-2fe7a1f1-39fe-4c07-9769-fdf6104955c8.png)
>    **这个是错误信息和返回的信息，这个接口是不是没用了,我使用的时候没有频繁请求，第一次请求就报这个错!请问是什么原因?谢谢!**

感谢反馈问题；升级到 AKShare 1.11.15 使用
