### ISSUE TITLE
stock_zh_a_daily调用发生错误

### ISSUE THREAD

**Issue by geweixin** [akfamily/akshare#4145]
**描述遇到的问题**
1. 操作系统版本
windows10
2. Python 版本
3.11
3. AKShare 版本
1.11.14
4. 接口的名称和代码
stock_zh_a_daily
5. 接口报错的截图或代码
>>> import akshare as ak
>>> df=ak.stock_zh_a_daily(symbol="sz000002",start_date="20101103",end_date="20201116",adjust="qfq")
C:\Python311\Lib\site-packages\akshare\stock\stock_zh_a_sina.py:199: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  temp_df.fillna(method="ffill", inplace=True)
6. 期望获得的正确结果
似乎是新浪的接口发生改变了。

**Comment by albertandking** [comment]
> **描述遇到的问题**
> 
> 1. 操作系统版本
>    windows10
> 2. Python 版本
>    3.11
> 3. AKShare 版本
>    1.11.14
> 4. 接口的名称和代码
>    stock_zh_a_daily
> 5. 接口报错的截图或代码
> 
> > > > import akshare as ak
> > > > df=ak.stock_zh_a_daily(symbol="sz000002",start_date="20101103",end_date="20201116",adjust="qfq")
> > > > C:\Python311\Lib\site-packages\akshare\stock\stock_zh_a_sina.py:199: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
> > > > temp_df.fillna(method="ffill", inplace=True)
> 
> 6. 期望获得的正确结果
>    似乎是新浪的接口发生改变了。

感谢反馈问题；升级到 AKShare 1.11.15 使用
