### ISSUE TITLE
建议包含tqdm的接口增加“是否开启进度条”的参数

### ISSUE THREAD

**Issue by oreohao** [akfamily/akshare#4149]
建议包含tqdm的接口增加是否开启进度条的参数，例如：stock_board_industry_summary_ths、stock_board_concept_name_ths等

**Comment by oreohao** [comment]
一方面满足使用者自己控制进度的需求，另一方面在某些情况下tqdm会有样式上的错误
![image](https://github.com/akfamily/akshare/assets/135679218/4207021e-dfc2-4609-8458-5cd30b112cef)

**Comment by albertandking** [comment]
> 建议包含tqdm的接口增加是否开启进度条的参数，例如：stock_board_industry_summary_ths、stock_board_concept_name_ths等

暂不考虑，目前设计是在运行完毕后进度条会移除
