### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by pentium100** [akfamily/akshare#4159]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本 windows 11
2. Python 版本 3.8
3. AKShare 版本 1.11.18
4. 接口的名称和代码 option_dce_daily
6. 接口报错的截图或代码
![image](https://github.com/akfamily/akshare/assets/27917/db965bee-c850-4294-9178-6017b779fbeb)

大连所返回的期权行情excel， 第一行需要略过。他不是标题。
![image](https://github.com/akfamily/akshare/assets/27917/1e5f4e3c-0c98-4f87-88c9-75d1d0f5d0ee)

8. 期望获得的正确结果
要改成header=1
![image](https://github.com/akfamily/akshare/assets/27917/e164a2c5-cbaf-4408-8cd2-40e13e5bf78f)

**Comment by pentium100** [comment]
get_dce_daily也是一样的问题。

**Comment by albertandking** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本 windows 11
> 2. Python 版本 3.8
> 3. AKShare 版本 1.11.18
> 4. 接口的名称和代码 option_dce_daily
> 5. 接口报错的截图或代码
>    ![image](https://user-images.githubusercontent.com/27917/271475536-db965bee-c850-4294-9178-6017b779fbeb.png)
> 
> 大连所返回的期权行情excel， 第一行需要略过。他不是标题。 ![image](https://user-images.githubusercontent.com/27917/271475797-1e5f4e3c-0c98-4f87-88c9-75d1d0f5d0ee.png)
> 
> 8. 期望获得的正确结果
>    要改成header=1
>    ![image](https://user-images.githubusercontent.com/27917/271475993-e164a2c5-cbaf-4408-8cd2-40e13e5bf78f.png)

感谢反馈问题并提供解决方案，已修复该问题，升级到 AKShare 1.11.20 使用
