### ISSUE TITLE
WCI date format error 

### ISSUE THREAD

**Issue by ericwbzhang** [akfamily/akshare#4160]
ak.__version__
'1.11.14'

ak.drewry_wci_index("composite")

ValueError: time data '07-Sept-23' does not match format '%d-%b-%y' (match)

It seems the data vendor has changed the date format which leads to an error here.

**Comment by albertandking** [comment]
> ak.**version** '1.11.14'
> 
> ak.drewry_wci_index("composite")
> 
> ValueError: time data '07-Sept-23' does not match format '%d-%b-%y' (match)
> 
> It seems the data vendor has changed the date format which leads to an error here.

感谢反馈问题，已修复该问题，升级到 AKShare 1.11.19 使用
