### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by pentium100** [akfamily/akshare#4165]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本 windows 11
2. Python 版本  3.11.5
3. AKShare 版本  1.11.21
4. 接口的名称和代码
option/option_commodity.py
方法：option_dce_daily

6. 接口报错的截图或代码
![image](https://github.com/akfamily/akshare/assets/27917/45668340-c044-4cb3-8ed7-f0b217ed459b)
不需要对第一列名进行分割 ，原来的名字就是对的。 这句话可以注释掉。

8. 期望获得的正确结果
标题正确地命名。

**Comment by pentium100** [comment]
错误的数据如下：
![image](https://github.com/akfamily/akshare/assets/27917/91e1f73c-4828-4abe-96f7-b54d6a8725c1)

**Comment by albertandking** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本 windows 11
> 2. Python 版本  3.11.5
> 3. AKShare 版本  1.11.21
> 4. 接口的名称和代码
>    option/option_commodity.py
>    方法：option_dce_daily
> 5. 接口报错的截图或代码
>    ![image](https://user-images.githubusercontent.com/27917/271771549-45668340-c044-4cb3-8ed7-f0b217ed459b.png)
>    不需要对第一列名进行分割 ，原来的名字就是对的。 这句话可以注释掉。
> 6. 期望获得的正确结果
>    标题正确地命名。

感谢反馈问题，已修复该问题，升级到 AKShare 1.11.22 使用
