### ISSUE TITLE
Doc A股股票指数数据

### ISSUE THREAD

**Issue by martinwang2002** [akfamily/akshare#4166]
https://www.akshare.xyz/data/stock/stock.html#id41 页面为 **股票数据->股票指数**，其中仅包含接口`stock_zh_index_spot`, `stock_zh_index_daily`, `stock_zh_index_daily_tx`

https://www.akshare.xyz/data/index/index.html#a 页面为**指数数据->A股股票指数数据**， 此部分包含了**股票数据->股票指数**中的三个接口以及更多接口。

因此，在文档中**股票数据->股票指数**的部分是多余的。能否使用重定向或其他方式，更容易寻找这部分接口？

**Comment by albertandking** [comment]
> https://www.akshare.xyz/data/stock/stock.html#id41 页面为 **股票数据->股票指数**，其中仅包含接口`stock_zh_index_spot`, `stock_zh_index_daily`, `stock_zh_index_daily_tx`
> 
> https://www.akshare.xyz/data/index/index.html#a 页面为**指数数据->A股股票指数数据**， 此部分包含了**股票数据->股票指数**中的三个接口以及更多接口。
> 
> 因此，在文档中**股票数据->股票指数**的部分是多余的。能否使用重定向或其他方式，更容易寻找这部分接口？

感谢反馈问题，已删除 **股票数据->股票指数** 部分的内容
