### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by nfenzhongredu** [akfamily/akshare#4169]
已经排除其他问题，也用了代理
**描述遇到的问题**
ak.stock_hsgt_stock_statistics_em  该接口爆如下错误
{'version': None, 'result': None, 'success': False, 'message': '参数预处理错误:org.antlr.v4.runtime.InputMismatchException', 'code': 9501}

**Comment by albertandking** [comment]
> 已经排除其他问题，也用了代理 **描述遇到的问题** ak.stock_hsgt_stock_statistics_em 该接口爆如下错误 {'version': None, 'result': None, 'success': False, 'message': '参数预处理错误:org.antlr.v4.runtime.InputMismatchException', 'code': 9501}

接口测试正常；只能获取近期的数据
