### ISSUE TITLE
深证证券交易所-融资融券数据-融资融券交易明细 代码优化

### ISSUE THREAD

**Issue by Zhangch99** [akfamily/akshare#4173]
**Describe the bug**
Dataframe返回的数据类型为int类型，不支持使用str操作

**To Reproduce**
stock_margin_detail_sse_df = ak.stock_margin_detail_szse(date="20100402")

**Expected behavior**
返回对应日期的数据

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser chrome
 - Version 1.11.25

**Comment by Zhangch99** [comment]
Screenshots
期望的效果：
<img width="836" alt="image" src="https://github.com/akfamily/akshare/assets/68682057/38d5df95-e9dd-4cd8-be14-8f2da4fdc74c">

**Comment by albertandking** [comment]
> stock_margin_detail_szse

返回格式是 pandas 中的 object，目前是正常的

**Comment by Zhangch99** [comment]
代码：result_df = ak.stock_margin_detail_szse(date="20221230")
<img width="1387" alt="image" src="https://github.com/akfamily/akshare/assets/68682057/93c535ac-3420-4ed4-9c57-971ca61259c8">
代码：result_df = ak.stock_margin_detail_szse(date="20100402")
<img width="1374" alt="image" src="https://github.com/akfamily/akshare/assets/68682057/47c9798d-fbb8-48d1-a7c6-c0ce273dca50">
是的，日期比较近的数据，返回是正常的，只是在部分历史日期中出现这种情况，这和网站的返回数据有关。

**Comment by albertandking** [comment]
> 代码：result_df = ak.stock_margin_detail_szse(date="20221230") <img alt="image" width="1387" src="https://user-images.githubusercontent.com/68682057/273486380-93c535ac-3420-4ed4-9c57-971ca61259c8.png"> 代码：result_df = ak.stock_margin_detail_szse(date="20100402") <img alt="image" width="1374" src="https://user-images.githubusercontent.com/68682057/273486512-47c9798d-fbb8-48d1-a7c6-c0ce273dca50.png"> 是的，日期比较近的数据，返回是正常的，只是在部分历史日期中出现这种情况，这和网站的返回数据有关。

已修复，升级到 AKShare 1.11.28 使用
