### ISSUE TITLE
资产负债表利润表现金流量表公告日期有问题

### ISSUE THREAD

**Issue by Chilianxin** [akfamily/akshare#4177]
读取20220331出来的数据公告日期有一部分是23年8月

**Comment by albertandking** [comment]
> 读取20220331出来的数据公告日期有一部分是23年8月

应该跟财务报表修正有关系

**Comment by Chilianxin** [comment]
> > 读取20220331出来的数据公告日期有一部分是23年8月
> 
> 应该跟财务报表修正有关系

有准备修复吗
