### ISSUE TITLE
中债指数-新综合指数-净价数据对应日期错误

### ISSUE THREAD

**Issue by none2003** [akfamily/akshare#4179]
描述遇到的问题

操作系统版本： Windows 11

Python 版本：3.9

AKShare 版本：1.11.28

接口的名称和代码：bond_new_composite_index_cbond
bond_new_composite_index_cbond_df = ak.bond_new_composite_index_cbond(indicator="净价", period="总值")

接口报错的截图或代码：
根据上面参数查询接口返回的结果如下：
5444,2023-10-08,102.1267
5443,2023-10-07,102.1706
5442,2023-10-06,102.1570
5441,2023-09-27,102.1202
5440,2023-09-26,102.0672

期望获得的正确结果
根据中国债券信息网https://yield.chinabond.com.cn/cbweb-mn/indices/single_index_query 的查询结果，2023-10-09的数据应该是102.1267，akshare错把对应的时间弄成2023-10-08了，其余的数据对应的日期也都是差了一天。
![image](https://github.com/akfamily/akshare/assets/10540630/1fa8ea2c-701d-40c4-b816-4f4f43ce45c5)

**Comment by albertandking** [comment]
> 描述遇到的问题
> 
> 操作系统版本： Windows 11
> 
> Python 版本：3.9
> 
> AKShare 版本：1.11.28
> 
> 接口的名称和代码：bond_new_composite_index_cbond bond_new_composite_index_cbond_df = ak.bond_new_composite_index_cbond(indicator="净价", period="总值")
> 
> 接口报错的截图或代码： 根据上面参数查询接口返回的结果如下： 5444,2023-10-08,102.1267 5443,2023-10-07,102.1706 5442,2023-10-06,102.1570 5441,2023-09-27,102.1202 5440,2023-09-26,102.0672
> 
> 期望获得的正确结果 根据中国债券信息网https://yield.chinabond.com.cn/cbweb-mn/indices/single_index_query 的查询结果，2023-10-09的数据应该是102.1267，akshare错把对应的时间弄成2023-10-08了，其余的数据对应的日期也都是差了一天。 ![image](https://user-images.githubusercontent.com/10540630/273637949-1fa8ea2c-701d-40c4-b816-4f4f43ce45c5.png)

感谢反馈问题，已修复该问题，升级到 AKShare 1.11.29 使用
