### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by Neekky** [akfamily/akshare#4185]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本：Mac M2
2. Python 版本： python3.10
3. AKShare 版本： 1.11.31
4. 接口的名称和代码：stock_analyst_detail_em、stock_analyst_detail_em
5. 接口报错的截图或代码：
![image](https://github.com/akfamily/akshare/assets/42760076/78c2cc45-2624-475a-8c5a-068bbe01f032)
接口请求不到数据了
6. 期望获得的正确结果

**Comment by albertandking** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本：Mac M2
> 2. Python 版本： python3.10
> 3. AKShare 版本： 1.11.31
> 4. 接口的名称和代码：stock_analyst_detail_em、stock_analyst_detail_em
> 5. 接口报错的截图或代码：
>    ![image](https://user-images.githubusercontent.com/42760076/274495430-78c2cc45-2624-475a-8c5a-068bbe01f032.png)
>    接口请求不到数据了
> 6. 期望获得的正确结果

按文档苹果 M 系列处理器方式安装
