### ISSUE TITLE
同花顺概念板块更新，导致个别板块无法解释

### ISSUE THREAD

**Issue by tangchi-coder** [akfamily/akshare#4186]
发现问题：
i='新能源汽车'
ak.stock_board_concept_hist_ths(symbol=i, start_year='2023')，报错，诱因肯能是页面进行了更改，

问题分析：
(http://q.10jqka.com.cn/gn/detail/code/300008)
更改了，需要更细兼容改版后内容，

需求探讨：
1.是否能更新兼容解析比如“新能源汽车”
2.是否能解析出该概念下产业链一览的数据

**Comment by tangchi-coder** [comment]
再观察一下

**Comment by tangchi-coder** [comment]
关闭

**Comment by albertandking** [comment]
> stock_board_concept_hist_ths

1. 问题1测试是正常的
2. 问题2新增 stock_board_concept_graph_ths 接口，升级到 AKShare 1.11.34 使用
