### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by warmdog1234** [akfamily/akshare#4187]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本 win10
2. Python 版本 3.10
3. AKShare 版本 最新
4. 接口的名称和代码
ak.get_dce_rank_table(date='20230914')
5. 接口报错的截图或代码
找不到数据，只有大连的持仓排名有问题，其它交易所是正常的，看示例代码中，写着是大连的，但是用例却是郑州的，怀疑是否一直有问题。

**Comment by albertandking** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本 win10
> 2. Python 版本 3.10
> 3. AKShare 版本 最新
> 4. 接口的名称和代码
>    ak.get_dce_rank_table(date='20230914')
> 5. 接口报错的截图或代码
>    找不到数据，只有大连的持仓排名有问题，其它交易所是正常的，看示例代码中，写着是大连的，但是用例却是郑州的，怀疑是否一直有问题。

可以使用 futures_dce_position_rank 替代
