### ISSUE TITLE
关于盘前数据获取

### ISSUE THREAD

**Issue by FuctionLife** [akfamily/akshare#4190]
根据AKshare文档，我只能找到当天的盘前历史数据，并且该历史数据应该只有9点25分之后的交易数据，没有集合竞价的数据，
这里找到一个api: http://quote.eastmoney.com/f1.html?newcode=0.002175 可以获得当天的集合竞价数据（挂单和价格）

想问的问题是：能否找到历史的集合竞价数据吗？如果可以的话，发一个api，完善一波功能，非常感谢

**Comment by albertandking** [comment]
> 根据AKshare文档，我只能找到当天的盘前历史数据，并且该历史数据应该只有9点25分之后的交易数据，没有集合竞价的数据， 这里找到一个api: http://quote.eastmoney.com/f1.html?newcode=0.002175 可以获得当天的集合竞价数据（挂单和价格）
> 
> 想问的问题是：能否找到历史的集合竞价数据吗？如果可以的话，发一个api，完善一波功能，非常感谢

感谢反馈问题，已新增 stock_intraday_em 接口，获取 http://quote.eastmoney.com/f1.html?newcode=0.002175 的数据，升级到 AKShare 1.11.33 版本使用

**Comment by FuctionLife** [comment]
你好，针对 stock_intraday_em接口，其中如果涉及到新三板或者是京版（430开头或者8开头），可能会存在问题（可能是因为不支持？），报错会显示实际有0列，但是要求有5列
需要修改stock_intraday_em.py的第124行，从pd.DataFrame()变成pd.DataFrame(columns=range(5))，这样初始化可能就没有问题了
