### ISSUE TITLE
关于过去历史的盘前数据获取

### ISSUE THREAD

**Issue by FuctionLife** [akfamily/akshare#4196]
前面提到了一个，获取当天盘前交易数据的stock_intraday_em接口，能否找到一个获取过去历史的盘前数据(类似于stock_intraday_em)，十分感谢

**Comment by albertandking** [comment]
> 前面提到了一个，获取当天盘前交易数据的stock_intraday_em接口，能否找到一个获取过去历史的盘前数据(类似于stock_intraday_em)，十分感谢

暂无
