### ISSUE TITLE
大神，能帮忙开发这个界面的接口吗？https://funddb.cn/tool/fear

### ISSUE THREAD

**Issue by tianhaisuifeng** [akfamily/akshare#4198]
对于韭圈儿网站，已经提供的接口index_value_hist_funddb()非常好用，能帮忙提供https://funddb.cn/tool/fear
这界面的接口吗？
包括：恐惧贪婪指数表、恐惧贪婪指数: 近两年、叠加大盘等。
自己尝试了一下，爬取url = "https://api.jiucaishuo.com/v2/kjtl/getbasedata"，然后用__create_encode()生成了对应的payload，但无法返回对应的数据，返回的是一窜字符串。

**Comment by albertandking** [comment]
> 对于韭圈儿网站，已经提供的接口index_value_hist_funddb()非常好用，能帮忙提供https://funddb.cn/tool/fear 这界面的接口吗？ 包括：恐惧贪婪指数表、恐惧贪婪指数: 近两年、叠加大盘等。 自己尝试了一下，爬取url = "[https://api.jiucaishuo.com/v2/kjtl/getbasedata"，然后用__create_encode()生成了对应的payload，但无法返回对应的数据，返回的是一窜字符串。](https://api.jiucaishuo.com/v2/kjtl/getbasedata%22%EF%BC%8C%E7%84%B6%E5%90%8E%E7%94%A8__create_encode()%E7%94%9F%E6%88%90%E4%BA%86%E5%AF%B9%E5%BA%94%E7%9A%84payload%EF%BC%8C%E4%BD%86%E6%97%A0%E6%B3%95%E8%BF%94%E5%9B%9E%E5%AF%B9%E5%BA%94%E7%9A%84%E6%95%B0%E6%8D%AE%EF%BC%8C%E8%BF%94%E5%9B%9E%E7%9A%84%E6%98%AF%E4%B8%80%E7%AA%9C%E5%AD%97%E7%AC%A6%E4%B8%B2%E3%80%82)

已新增 stock_fear_greed_funddb 接口，升级到 AKShare 1.11.36 使用

**Comment by tianhaisuifeng** [comment]
@albertandking 大神太强了，佩服啊！
