### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by StephenLee2016** [akfamily/akshare#4202]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本
   mac m1
2. Python 版本
   python3.8
3. AKShare 版本
  1.11.12
4. 接口的名称和代码
  "stock_hk_hist_min_em"
  ak.stock_hk_hist_min_em(symbol='06660',
                                           period='1',
                                           adjust='',
                                           start_date='20231018',
                                           end_date='20231018')

5. 接口报错的截图或代码
                         时间    开盘    收盘    最高    最低    成交量       成交额     最新价
0    2023-10-18 09:30:00  0.00  9.39  9.39  9.39  27400  257286.0  9.3900
1    2023-10-18 09:31:00  0.00  9.36  9.39  9.36   6800   63834.0  9.3895
2    2023-10-18 09:32:00  0.00  9.27  9.33  9.27  16800  156334.0  9.3618
3    2023-10-18 09:33:00  0.00  9.20  9.22  9.20   5600   51566.0  9.3466
4    2023-10-18 09:34:00  0.00  9.22  9.22  9.15  63400  581672.0  9.2558
..                   ...   ...   ...   ...   ...    ...       ...     ...
379  2023-10-19 10:18:00  9.01  9.01  9.01  9.01   4200   37842.0  8.9150
380  2023-10-19 10:19:00  9.01  8.90  9.01  8.90  78800  707378.0  8.9177
381  2023-10-19 10:20:00  8.90  8.90  8.90  8.90   6000   53400.0  8.9177
382  2023-10-19 10:21:00  8.90  8.87  8.90  8.87   2000   17758.0  8.9176
383  2023-10-19 10:22:00  8.87  8.84  8.87  8.83   6000   53068.0  8.9174
6. 期望获得的正确结果
    查询两天的数据，发现最近的数据 open数据是正常的，但是前一天的open就都是0了

**Comment by albertandking** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本
>    mac m1
> 2. Python 版本
>    python3.8
> 3. AKShare 版本
>    1.11.12
> 4. 接口的名称和代码
>    "stock_hk_hist_min_em"
>    ak.stock_hk_hist_min_em(symbol='06660',
>    period='1',
>    adjust='',
>    start_date='20231018',
>    end_date='20231018')
> 5. 接口报错的截图或代码
>    时间    开盘    收盘    最高    最低    成交量       成交额     最新价
>    0    2023-10-18 09:30:00  0.00  9.39  9.39  9.39  27400  257286.0  9.3900
>    1    2023-10-18 09:31:00  0.00  9.36  9.39  9.36   6800   63834.0  9.3895
>    2    2023-10-18 09:32:00  0.00  9.27  9.33  9.27  16800  156334.0  9.3618
>    3    2023-10-18 09:33:00  0.00  9.20  9.22  9.20   5600   51566.0  9.3466
>    4    2023-10-18 09:34:00  0.00  9.22  9.22  9.15  63400  581672.0  9.2558
>    ..                   ...   ...   ...   ...   ...    ...       ...     ...
>    379  2023-10-19 10:18:00  9.01  9.01  9.01  9.01   4200   37842.0  8.9150
>    380  2023-10-19 10:19:00  9.01  8.90  9.01  8.90  78800  707378.0  8.9177
>    381  2023-10-19 10:20:00  8.90  8.90  8.90  8.90   6000   53400.0  8.9177
>    382  2023-10-19 10:21:00  8.90  8.87  8.90  8.87   2000   17758.0  8.9176
>    383  2023-10-19 10:22:00  8.87  8.84  8.87  8.83   6000   53068.0  8.9174
> 6. 期望获得的正确结果
>    查询两天的数据，发现最近的数据 open数据是正常的，但是前一天的open就都是0了

数据源提供的数据是这样的
