### ISSUE TITLE
AKShare 接口问题报告ak.stock_gpzy_pledge_ratio_em()

### ISSUE THREAD

**Issue by xnw176** [akfamily/akshare#4208]
**描述遇到的问题**
1. 操作系统版本 MAC OS 13.6
2. Python 版本 3.9
3. AKShare 版本 最新
4. 接口的名称和代码
ak.stock_gpzy_pledge_ratio_em()
6. 接口报错的截图或代码
<img width="496" alt="image" src="https://github.com/akfamily/akshare/assets/82297022/d23311f3-067e-4e4f-a45e-8b65b3d722a2">

8. 期望获得的正确结果

**Comment by albertandking** [comment]
> **描述遇到的问题**
> 
> 1. 操作系统版本 MAC OS 13.6
> 2. Python 版本 3.9
> 3. AKShare 版本 最新
> 4. 接口的名称和代码
>    ak.stock_gpzy_pledge_ratio_em()
> 5. 接口报错的截图或代码
> 
> <img alt="image" width="496" src="https://user-images.githubusercontent.com/82297022/277100417-d23311f3-067e-4e4f-a45e-8b65b3d722a2.png">
> 8. 期望获得的正确结果

感谢反馈问题，已修复该问题，升级到 AKShare 1.11.42 使用
