### ISSUE TITLE
获取每日的筹码分布

### ISSUE THREAD

**Issue by marshalyauly** [akfamily/akshare#4212]
### Discussed in https://github.com/orgs/akfamily/discussions/4211

<div type='discussions-op-text'>

<sup>Originally posted by **marshalyauly** October 23, 2023</sup>
可以增加每日的筹码分布数据吗？比如东方财富网股票详情里的以下信息：

获利比例
平均成本
90%成本
集中度
70%成本
集中度</div>

**Comment by albertandking** [comment]
> ### Discussed in https://github.com/orgs/akfamily/discussions/4211
> Originally posted by **marshalyauly** October 23, 2023 可以增加每日的筹码分布数据吗？比如东方财富网股票详情里的以下信息：
> 
> 获利比例 平均成本 90%成本 集中度 70%成本 集中度

该指标是计算出来的，可以在本地获取行情数据后自行计算

**Comment by albertandking** [comment]
> ### Discussed in https://github.com/orgs/akfamily/discussions/4211
> Originally posted by **marshalyauly** October 23, 2023 可以增加每日的筹码分布数据吗？比如东方财富网股票详情里的以下信息：
> 
> 获利比例 平均成本 90%成本 集中度 70%成本 集中度

新增 stock_cyq_em 接口，升级到 AKShare 1.11.44 使用

**Comment by marshalyauly** [comment]
感谢大佬的更新，亲测好用。

**Comment by marshalyauly** [comment]
> > ### Discussed in https://github.com/orgs/akfamily/discussions/4211
> > Originally posted by **marshalyauly** October 23, 2023 可以增加每日的筹码分布数据吗？比如东方财富网股票详情里的以下信息：
> > 获利比例 平均成本 90%成本 集中度 70%成本 集中度
> 
> 新增 stock_cyq_em 接口，升级到 AKShare 1.11.44 使用

感谢大佬的更新，亲测好用。
