### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by zhangbyes** [akfamily/akshare#4221]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**

1. 操作系统版本 : WIN10 LTSC 2021
3. Python 版本 : 3.11.3
4. AKShare 版本 : 1.10.56
5. 接口的名称和代码 : amac_fund_abs
6. 接口报错的截图或代码 : 
![图片](https://github.com/akfamily/akshare/assets/41775980/559d18a4-4a48-42ff-890b-37a94a77422a)

7. 期望获得的正确结果

**Comment by albertandking** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本 : WIN10 LTSC 2021
> 2. Python 版本 : 3.11.3
> 3. AKShare 版本 : 1.10.56
> 4. 接口的名称和代码 : amac_fund_abs
> 5. 接口报错的截图或代码 :
>    ![图片](https://user-images.githubusercontent.com/41775980/277849312-559d18a4-4a48-42ff-890b-37a94a77422a.png)
> 6. 期望获得的正确结果

感谢反馈问题；已修复该问题，升级到 AKShare 1.11.50 使用
