### ISSUE TITLE
不支持pandas2.0

### ISSUE THREAD

**Issue by fizechan** [akfamily/akshare#4225]
AKShare截止当前最新版1.11.50，不支持pandas2.0。比如调用fund_scale_change_em接口时，会提示以下异常信息：

'DataFrame' object has no attribute 'append'

这是因为pandas2.0版本已移除append方法，pandas官方推荐使用concat方法。

**Comment by albertandking** [comment]
> AKShare截止当前最新版1.11.50，不支持pandas2.0。比如调用fund_scale_change_em接口时，会提示以下异常信息：
> 
> 'DataFrame' object has no attribute 'append'
> 
> 这是因为pandas2.0版本已移除append方法，pandas官方推荐使用concat方法。

感谢反馈问题；已修复该问题，升级到 AKShare 1.11.52 版本使用
