### ISSUE TITLE
fund_portfolio_change_em()接口问题报告

### ISSUE THREAD

**Issue by tianhaisuifeng** [akfamily/akshare#4230]
fund_portfolio_change_em()接口出现告警：
FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  temp_df = pd.read_html(data_json["content"], converters={"股票代码": str})[
建议修改方案：
from io import StringIO
temp_df = pd.read_html(StringIO(str(data_json["content"])), converters={"股票代码": str})[
            item
        ]

**Comment by albertandking** [comment]
> fund_portfolio_change_em()接口出现告警： FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object. temp_df = pd.read_html(data_json["content"], converters={"股票代码": str})[ 建议修改方案： from io import StringIO temp_df = pd.read_html(StringIO(str(data_json["content"])), converters={"股票代码": str})[ item ]

感谢反馈问题，已修复该问题，升级到 AKShare 1.11.55 使用
