### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by spancer** [akfamily/akshare#4236]
版本：  1.11.56
接口：stock_zt_pool_em
问题：传入日期格式YMD的日期报错： ValueError: Length mismatch: Expected axis has 1 elements, new values have 17 elements
示例：stock_zt_pool_em_df = ak.stock_zt_pool_em(date='20230511')
说明：并不是传入所有的日期都报这个错，也有不报错的情形。

**Comment by albertandking** [comment]
> 版本： 1.11.56 接口：stock_zt_pool_em 问题：传入日期格式YMD的日期报错： ValueError: Length mismatch: Expected axis has 1 elements, new values have 17 elements 示例：stock_zt_pool_em_df = ak.stock_zt_pool_em(date='20230511') 说明：并不是传入所有的日期都报这个错，也有不报错的情形。

目前只能获取近期的数据，目前测试没有遇到问题，如有相关的报错案例，可以新开 issues

**Comment by lenhill** [comment]
Generally,Stock_zt_pool_em interface can only retrieve data within the past two weeks.
If the time span is exceeded 2 weeks, this error will be occured.
Reported ValueError: Length mismatch: Expected axis has 1 elements, new values have 17 elements.
Hope this can help you.
