### ISSUE TITLE
bond_china_close_return()出现403禁止访问

### ISSUE THREAD

**Issue by qiuning79** [akfamily/akshare#4239]
bond_china_close_return()出现403禁止访问

**描述遇到的问题**
1. 操作系统版本 win10
2. Python 版本 3.11.4
3. AKShare 版本 1.11.57
4. 接口的名称和代码 bond_china_close_return（）
5. 接口报错的截图或代码 
运行文档中的示例代码：
import akshare as ak
bond_china_close_return_df = ak.bond_china_close_return(symbol="政策性金融债(进出口行)", period="1", start_date="20220104", end_date="20220104")
print(bond_china_close_return_df)
运行后显示的错误为：
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Program Files\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\Python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python38\lib\site-packages\akshare\bond\bond_china_money.py", line 68, in bond_china_close_return
    name_code_df = bond_china_close_return_map()
  File "C:\Program Files\Python38\lib\site-packages\akshare\bond\bond_china_money.py", line 43, in bond_china_close_return_map
    data_json = r.json()
  File "C:\Program Files\Python38\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
单步进去发现requests请求返回的值是403。
测试中发现如果用本机的浏览器手工打开一下网站：
https://www.chinamoney.com.cn/chinese/bkcurvclosedyhis/?bondType=CYCC000&reference=1
网页可以正常显示
然后再在python中执行bond_china_close_return()，requests的返回值就是200正常了。不过这一现象只能持续1天，第二天没有提前手工在浏览器中先访问过上述网站的话，调用bond_china_close_return()，requests的返回值还是403，无法正常执行。
6. 期望获得的正确结果
可以不依赖人工访问网站就可以成功调用bond_china_close_return()函数

**Comment by qiuning79** [comment]
刚刚测试了一下bond_china_money.py中的另一个函数bond_china_close_return_map()也存在同样的问题。当天未手工在浏览器中访问过https://www.chinamoney.com.cn/chinese/bkcurvclosedyhis/?bondType=CYCC000&reference=1的电脑上直接调用函数，代码中requests的返回值是403

**Comment by albertandking** [comment]
> bond_china_close_return()出现403禁止访问
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本 win10
> 2. Python 版本 3.11.4
> 3. AKShare 版本 1.11.57
> 4. 接口的名称和代码 bond_china_close_return（）
> 5. 接口报错的截图或代码
>    运行文档中的示例代码：
>    import akshare as ak
>    bond_china_close_return_df = ak.bond_china_close_return(symbol="政策性金融债(进出口行)", period="1", start_date="20220104", end_date="20220104")
>    print(bond_china_close_return_df)
>    运行后显示的错误为：
>    Traceback (most recent call last):
>    File "C:\Program Files\Python38\lib\site-packages\requests\models.py", line 971, in json
>    return complexjson.loads(self.text, **kwargs)
>    File "C:\Program Files\Python38\lib\json__init__.py", line 357, in loads
>    return _default_decoder.decode(s)
>    File "C:\Program Files\Python38\lib\json\decoder.py", line 337, in decode
>    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>    File "C:\Program Files\Python38\lib\json\decoder.py", line 355, in raw_decode
>    raise JSONDecodeError("Expecting value", s, err.value) from None
>    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "", line 1, in File "C:\Program Files\Python38\lib\site-packages\akshare\bond\bond_china_money.py", line 68, in bond_china_close_return name_code_df = bond_china_close_return_map() File "C:\Program Files\Python38\lib\site-packages\akshare\bond\bond_china_money.py", line 43, in bond_china_close_return_map data_json = r.json() File "C:\Program Files\Python38\lib\site-packages\requests\models.py", line 975, in json raise RequestsJSONDecodeError(e.msg, e.doc, e.pos) requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0) 单步进去发现requests请求返回的值是403。 测试中发现如果用本机的浏览器手工打开一下网站： https://www.chinamoney.com.cn/chinese/bkcurvclosedyhis/?bondType=CYCC000&reference=1 网页可以正常显示 然后再在python中执行bond_china_close_return()，requests的返回值就是200正常了。不过这一现象只能持续1天，第二天没有提前手工在浏览器中先访问过上述网站的话，调用bond_china_close_return()，requests的返回值还是403，无法正常执行。 6. 期望获得的正确结果 可以不依赖人工访问网站就可以成功调用bond_china_close_return()函数

目前测试接口正常，只能获取近期的数据

**Comment by qiuning79** [comment]
@albertandking 
我这里调用新用例中的昨天数据：
ak.bond_china_close_return(symbol="国债", period="1", start_date="20231101", end_date="20231101")
还是requests返回403，用浏览器手工访问chinamoney网站后再调用以上函数就可以正常返回了。
换了台电脑，在网络环境也不一样的情况下，可以复现该问题。
