### ISSUE TITLE
bond_china_close_return接口出错规律研究

### ISSUE THREAD

**Issue by LittleWorm1** [akfamily/akshare#4247]
python：3.11.6
akshare：1.11.58

import akshare as ak
ak.bond_china_close_return(symbol="国债", period="1", start_date="20231101", end_date="20231101")
错误信息：requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

观察到的出错规律如下，供大家参考：
1）上周开始才有这个问题的，以前无此现象，访问很稳定；
2）实际错误的原因是requests返回了403，引起了json错误；
3）出现上述错误后，无论进行多少次尝试还是会报错，不要通过重试来规避该问题；
4）手工浏览器访问https://www.chinamoney.com.cn/主页，再调用bond_china_close_return即可正常使用；
5）手工浏览器访问后能正常调用函数的时间限制为24小时，24小时内每次都成功，24小时候再调用就每次都出错了，出错后还可以手工浏览器访问让有效期继续延长24小时；
希望上述现象对大家应急使用时有帮助，也期待大牛出手修订这一问题，谢谢！

**Comment by albertandking** [comment]
> python：3.11.6 akshare：1.11.58
> 
> import akshare as ak ak.bond_china_close_return(symbol="国债", period="1", start_date="20231101", end_date="20231101") 错误信息：requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 
> 观察到的出错规律如下，供大家参考： 1）上周开始才有这个问题的，以前无此现象，访问很稳定； 2）实际错误的原因是requests返回了403，引起了json错误； 3）出现上述错误后，无论进行多少次尝试还是会报错，不要通过重试来规避该问题； 4）手工浏览器访问[https://www.chinamoney.com.cn/主页，再调用bond_china_close_return即可正常使用；](https://www.chinamoney.com.cn/%E4%B8%BB%E9%A1%B5%EF%BC%8C%E5%86%8D%E8%B0%83%E7%94%A8bond_china_close_return%E5%8D%B3%E5%8F%AF%E6%AD%A3%E5%B8%B8%E4%BD%BF%E7%94%A8%EF%BC%9B) 5）手工浏览器访问后能正常调用函数的时间限制为24小时，24小时内每次都成功，24小时候再调用就每次都出错了，出错后还可以手工浏览器访问让有效期继续延长24小时； 希望上述现象对大家应急使用时有帮助，也期待大牛出手修订这一问题，谢谢！

已复现并修复该问题，升级到 AKShare 1.11.60 使用
