### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by 1lz2** [akfamily/akshare#4256]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```
无法使用stock_news_em
![image](https://github.com/akfamily/akshare/assets/95406124/b9ad599a-d417-49e1-940c-cdeb39bfa527)

**Comment by albertandking** [comment]
> stock_news_em

接口正常，按说明文档使用
