### ISSUE TITLE
实时接口没有内外盘数据以及日内分时数据无法区分买与卖

### ISSUE THREAD

**Issue by liyqxtu** [akfamily/akshare#4257]
1、实时接口 stock_sh_a_spot_em() 没有内外盘数据
2、实时接口 stock_intraday_em() 中的手无法区分买与卖

**Comment by albertandking** [comment]
> stock_intraday_em

在 stock_intraday_em 接口新增 买卖盘字段；stock_sh_a_spot_em 由于数据源没有相关字段的数据，暂不处理；升级到 AKShare 1.11.64 版本使用
