### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by LStarRain** [akfamily/akshare#4259]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本 Win10
2. Python 版本 3.9.12
3. AKShare 版本 1.11.61
4. 接口的名称和代码 stock_news_em_df = ak.stock_news_em(symbol = "600497")
5. 接口报错的截图或代码
![image](https://github.com/akfamily/akshare/assets/129396629/2bf45199-7325-4926-83a1-090cfc4d3739)

**Comment by albertandking** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本 Win10
> 2. Python 版本 3.9.12
> 3. AKShare 版本 1.11.61
> 4. 接口的名称和代码 stock_news_em_df = ak.stock_news_em(symbol = "600497")
> 5. 接口报错的截图或代码
>    ![image](https://user-images.githubusercontent.com/129396629/281389001-2bf45199-7325-4926-83a1-090cfc4d3739.png)

目前测试正常
