### ISSUE TITLE
一次请求获取历史A股中每只股票的总市值

### ISSUE THREAD

**Issue by zhiyyyu** [akfamily/akshare#4268]
**Is your feature request related to a problem? Please describe.**
需求：一次请求获取历史上某一天A股中每只股票的当天总市值。
是否已经存在现有的接口了？我在文档中搜索“总市值”没有找到合适的方法，能够一次请求获取每只股票的历史总市值。如果已经存在，请告知。
我目前的方法：
1. stock_zh_valuation_baidu可以获取某只股票历史总市值，但是需要对每只股票做一次请求，考虑到频率限制，会非常慢。
2. stock_zh_a_spot_em：可以获取所有股票当日的总市值，但是没有历史信息。

**Describe the solution you'd like**
类似于tushare中的[daily_basic](https://tushare.pro/document/2?doc_id=32)接口，df = pro.daily_basic(ts_code='', trade_date='20180726', fields='ts_code,trade_date,turnover_rate,volume_ratio,pe,pb')可以指定trade_date，获取当日内容。
可以在历史行情数据分类下，增加接口，指定trade_date返回历史某天每只股票的信息。

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by albertandking** [comment]
> **Is your feature request related to a problem? Please describe.** 需求：一次请求获取历史上某一天A股中每只股票的当天总市值。 是否已经存在现有的接口了？我在文档中搜索“总市值”没有找到合适的方法，能够一次请求获取每只股票的历史总市值。如果已经存在，请告知。 我目前的方法：
> 
> 1. stock_zh_valuation_baidu可以获取某只股票历史总市值，但是需要对每只股票做一次请求，考虑到频率限制，会非常慢。
> 2. stock_zh_a_spot_em：可以获取所有股票当日的总市值，但是没有历史信息。
> 
> **Describe the solution you'd like** 类似于tushare中的[daily_basic](https://tushare.pro/document/2?doc_id=32)接口，df = pro.daily_basic(ts_code='', trade_date='20180726', fields='ts_code,trade_date,turnover_rate,volume_ratio,pe,pb')可以指定trade_date，获取当日内容。 可以在历史行情数据分类下，增加接口，指定trade_date返回历史某天每只股票的信息。
> 
> **Describe alternatives you've considered** None.
> 
> **Additional context** None.

目前还没有相关接口
