### ISSUE TITLE
财务报表-东财的三个年度报告接口500了

### ISSUE THREAD

**Issue by xiatian12345** [akfamily/akshare#4272]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本:macos 13.2.1 (22D68)
3. Python 版本:Python 3.10.11
4. AKShare 版本:1.11.68
5. AKTool 版本:0.0.83
6. 接口的名称和代码
```javascript
const queryObj = {
	symbol: code,
};
const result1 = await getStock("stock_balance_sheet_by_yearly_em", queryObj); //资产负债表-按年度
const result2 = await getStock("stock_profit_sheet_by_yearly_em", queryObj); //利润表-按年度
const result3 = await getStock("stock_cash_flow_sheet_by_yearly_em", queryObj); //现金流量表-按年度
```
8. 接口报错的截图或代码
stock_balance_sheet_by_yearly_em:1     Failed to load resource: the server responded with a status of 500 (Internal Server Error)
10. 期望获得的正确结果
期望获取正确结果

**Comment by albertandking** [comment]
> ```js
> stock_balance_sheet_by_yearly_em
> ```

目前测试接口是正常的
