### ISSUE TITLE
AKShare 接口问题报告：ak.option_czce_daily

### ISSUE THREAD

**Issue by yeams** [akfamily/akshare#4282]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本：mac
3. Python 版本：python 3.9.5
4. AKShare 版本: 1.11.59
5. 接口的名称和代码：
郑州商品交易所-期权数据接口

import akshare as ak
a = ak.option_czce_daily(symbol="短纤期权", trade_date="20231116")
print(a)

7. 接口报错的截图或代码
<img width="569" alt="截屏2023-11-16 23 08 27" src="https://github.com/akfamily/akshare/assets/38125853/1bb94723-2028-4a66-a59a-f2ba54833054">
返回2023年11月16日的棉花期权数据

9. 期望获得的正确结果

返回2023年11月16日的短纤期权数据
PS：郑州商品交易所的纯碱期权、尿素期权 存在同样问题，即返 棉花期权数据

**Comment by albertandking** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本：mac
> 2. Python 版本：python 3.9.5
> 3. AKShare 版本: 1.11.59
> 4. 接口的名称和代码：
>    郑州商品交易所-期权数据接口
> 
> import akshare as ak a = ak.option_czce_daily(symbol="短纤期权", trade_date="20231116") print(a)
> 
> 7. 接口报错的截图或代码
> 
> <img alt="截屏2023-11-16 23 08 27" width="569" src="https://user-images.githubusercontent.com/38125853/283498531-1bb94723-2028-4a66-a59a-f2ba54833054.png"> 返回2023年11月16日的棉花期权数据
> 9. 期望获得的正确结果
> 
> 返回2023年11月16日的短纤期权数据 PS：郑州商品交易所的纯碱期权、尿素期权 存在同样问题，即返 棉花期权数据

感谢反馈问题，已新增相关品种，升级到 AKShare 1.11.76 使用
