### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by hesihan1994** [akfamily/akshare#4286]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本: win11
2. Python 版本: 3.11
3. AKShare 版本: akshare-1.11.76
4. 接口的名称和代码: ak.futures_zh_spot(symbol='BB0', market="CF", adjust='0').to_dict('records')[0]
5. 接口报错的截图或代码: ValueError: Length mismatch: Expected axis has 1 elements, new values have 44 elements
6. 期望获得的正确结果: {'symbol': '胶合板连续', 'time': '023000', 'open': 实时数值, 'high': 实时数值, 'low': 实时数值, 'current_price': 实时数值, 'bid_price': 实时数值, 'ask_price': 实时数值, 'buy_vol': 实时数值, 'sell_vol': 实时数值, 'hold': 实时数值, 'volume': 实时数值, 'avg_price': 实时数值, 'last_close': 实时数值, 'last_settle_price': 实时数值}

**Comment by hesihan1994** [comment]
这些symbol也有问题：
- WH0 强麦连续, Expected axis has 1 elements, new values have 44 elements
- JR0 粳稻连续, Expected axis has 1 elements, new values have 44 elements
- RI0 早籼稻连续, Expected axis has 1 elements, new values have 44 elements
- LR0 晚籼稻连续, Expected axis has 1 elements, new values have 44 elements
- IF0 沪深300指数期货连续, Expected axis has 50 elements, new values have 44 elements
- TF0 5年期国债期货连续, Expected axis has 50 elements, new values have 44 elements
- IH0 上证50指数期货连续, Expected axis has 50 elements, new values have 44 elements
- IC0 中证500指数期货连续, Expected axis has 50 elements, new values have 44 elements
- TS0 2年期国债期货连续, Expected axis has 50 elements, new values have 44 elements
- IM0 中证连续指数期货连续, Expected axis has 50 elements, new values have 44 elements

**Comment by albertandking** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本: win11
> 2. Python 版本: 3.11
> 3. AKShare 版本: akshare-1.11.76
> 4. 接口的名称和代码: ak.futures_zh_spot(symbol='BB0', market="CF", adjust='0').to_dict('records')[0]
> 5. 接口报错的截图或代码: ValueError: Length mismatch: Expected axis has 1 elements, new values have 44 elements
> 6. 期望获得的正确结果: {'symbol': '胶合板连续', 'time': '023000', 'open': 实时数值, 'high': 实时数值, 'low': 实时数值, 'current_price': 实时数值, 'bid_price': 实时数值, 'ask_price': 实时数值, 'buy_vol': 实时数值, 'sell_vol': 实时数值, 'hold': 实时数值, 'volume': 实时数值, 'avg_price': 实时数值, 'last_close': 实时数值, 'last_settle_price': 实时数值}

接口正常，应该是新浪没有数据

**Comment by stshuen** [comment]
最新的也有这个问题，新浪的接口返回没有这几支股的数据，现在直接排除就可以；

def futures_zh_spot(symbol: str = "V2309", market: str = "CF") -> pd.DataFrame:
    """
    期货的实时行情数据
    :param symbol: 合约名称的字符串组合
    :type symbol: str
    :param market: CF 为商品期货
    :type market: str
    :return: 期货的实时行情数据
    :rtype: pandas.DataFrame
    """
    # symbol = ",".join([value['code'] for key, value in futures.iterrows()])
    subscribe_list = ",".join(
        ["nf_" + item.strip() for item in symbol.split(",")]
    )
    print(subscribe_list)
    url = f"http://hq.sinajs.cn/list={subscribe_list}"
    headers = {
        "Accept": "*/*",
        "Accept-Encoding": "gzip, deflate",
        "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
        "Cache-Control": "no-cache",
        "Host": "hq.sinajs.cn",
        "Pragma": "no-cache",
        "Proxy-Connection": "keep-alive",
        "Referer": "http://vip.stock.finance.sina.com.cn/",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36",
    }
    r = requests.get(url, headers=headers)

    columns = ["symbol", "time", "open", "high", "low", "last_close", "bid_price", "ask_price", "current_price", "avg_price", "last_settle_price", "buy_vol", "sell_vol", "hold", "volume"]

    pattern = r'nf_(.*?)='
    df = []
    for row in r.text.split("\n")[:-1]:
        line = row.strip().split(",")
        match = re.search(pattern, line[0])
        if match:
            line[0] = match.group(1)

        if len(line) > 10:
            df.append([line[i] for i in [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]])
        else:
            df.append([line[0]])

    return pd.DataFrame(data=df, columns=columns)

futures_zh_spot(symbol='BB0, A0')
