### ISSUE TITLE
能否配置一份GitHubPages的文档

### ISSUE THREAD

**Issue by liuxinyumocn** [akfamily/akshare#4290]
https://akshare.akfamily.xyz/ 文档站点网络环境不够良好，时常子页访问缓慢，使用 GitHub 提供的 Pages 优化这一问题。

**Comment by albertandking** [comment]
> https://akshare.akfamily.xyz/ 文档站点网络环境不够良好，时常子页访问缓慢，使用 GitHub 提供的 Pages 优化这一问题。

目前基于 readthedocs 是通用的方式，暂不考虑 Github Pages 部署，建议可以项目本地查看部署和查看文档
