### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by chenzhiweiwk** [akfamily/akshare#4308]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本
2. Python 版本：3.8.14
3. AKShare 版本：1.11.75
4. 接口的名称和代码：stock_index_pe_lg、stock_index_pb_lg
5. 接口报错的截图或代码
![图片](https://github.com/akfamily/akshare/assets/50659359/7dc2aa8a-d370-4e88-99d0-ce4c7b9e98f0)
6. 期望获得的正确结果：返回正确的数据

**Comment by albertandking** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本
> 2. Python 版本：3.8.14
> 3. AKShare 版本：1.11.75
> 4. 接口的名称和代码：stock_index_pe_lg、stock_index_pb_lg
> 5. 接口报错的截图或代码
>    ![图片](https://private-user-images.githubusercontent.com/50659359/286844140-7dc2aa8a-d370-4e88-99d0-ce4c7b9e98f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzNDQ0MjAsIm5iZiI6MTcwMTM0NDEyMCwicGF0aCI6Ii81MDY1OTM1OS8yODY4NDQxNDAtN2RjMmFhOGEtZDM3MC00ZTg4LTk5ZDAtY2U0YzdiOWU5OGYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDExMzUyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5ZWFmMWE5MjMwNTM4MWI4NzFhNTM3Nzc5ODllMTc5YmIzMTNiOTA2Yzc3YWViNjhkNjg2MzMwZmRkOWEwZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9-gNk3WDE_HABfosCIkZb_VUOCRpOUzuc8PQfHx_img)
> 6. 期望获得的正确结果：返回正确的数据

接口测试正常
