### ISSUE TITLE
stock_xgsglb_em_df = ak.stock_xgsglb_em(symbol="京市A股")  执行出错

### ISSUE THREAD

**Issue by Perrygd** [akfamily/akshare#4310]
ValueError: Length mismatch: Expected axis has 38 elements, new values have 30 elements

**Comment by albertandking** [comment]
> ValueError: Length mismatch: Expected axis has 38 elements, new values have 30 elements

感谢反馈问题，已在 AKShare 1.11.86 更新，PR 由于代码修改，暂时关闭，感谢 PR
