### ISSUE TITLE
stock_zh_a_hist 获取不到历史数据

### ISSUE THREAD

**Issue by thedarkclouds** [akfamily/akshare#4314]
**描述遇到的问题**
1. mac os 14.1.1
3. Python 3.10
4.  akshare-1.11.84
5. 接口的名称和代码
stock_zh_a_hist  获取不到历史数据
![image](https://github.com/akfamily/akshare/assets/38521805/a6f04bb0-a06d-43c6-86a9-a943cf541227)

**Comment by albertandking** [comment]
> 4\. stock_zh_a_hist

接口测试正常
