### ISSUE TITLE
询问如何只要加红的电报

### ISSUE THREAD

**Issue by hanjz123** [akfamily/akshare#4315]
请问如何能对电报内容进行筛选？比如我现在通过接口获取的是财联社新闻的全部消息，我如何才能只获取加红（重点）消息呢

**Comment by albertandking** [comment]
> 请问如何能对电报内容进行筛选？比如我现在通过接口获取的是财联社新闻的全部消息，我如何才能只获取加红（重点）消息呢

建议可以研究下源码在本地测试下
