### ISSUE TITLE
stock_market_activity_legu接口使用pd.read_html()需要更新对新特性的支持

### ISSUE THREAD

**Issue by JiangJamm** [akfamily/akshare#4317]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本 MacOS 14.1.1 (23B81)
2. Python 版本 3.10
3. AKShare 版本 1.11.84
4. 接口的名称和代码
```python
import akshare as ak

df = ak.stock_market_activity_legu()

print(df)

```

5. 接口报错的截图或代码
<img width="2355" alt="image" src="https://github.com/akfamily/akshare/assets/39955422/aa86ec82-5504-4a58-80e3-d4d339bc631b">

6. 期望获得的正确结果
- 应使用StringIO包装r.text
- 活跃度包含换行符需要处理

**Comment by albertandking** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本 MacOS 14.1.1 (23B81)
> 2. Python 版本 3.10
> 3. AKShare 版本 1.11.84
> 4. 接口的名称和代码
> 
> ```python
> import akshare as ak
> 
> df = ak.stock_market_activity_legu()
> 
> print(df)
> ```
> 
> 5. 接口报错的截图或代码
> 
> <img alt="image" width="2000" src="https://private-user-images.githubusercontent.com/39955422/287332185-aa86ec82-5504-4a58-80e3-d4d339bc631b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1MTczMjEsIm5iZiI6MTcwMTUxNzAyMSwicGF0aCI6Ii8zOTk1NTQyMi8yODczMzIxODUtYWE4NmVjODItNTUwNC00YTU4LTgwZTMtZDRkMzM5YmM2MzFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAyVDExMzcwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyNGE4MzE3YzRmOGJmY2YxM2MwZWFkYTJlYzA4OTFkNzRkY2RjOTAzYTI0Mzc5MDAyNmIxZGU5OGNmM2E0ODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.r6pXtg8YYlFgN7I7xHMBbBoAHFasDjoWBv9E-71tznQ">
> 6. 期望获得的正确结果
> 
> * 应使用StringIO包装r.text
> * 活跃度包含换行符需要处理

感谢反馈问题，已在 AKShare 1.11.86 更新，PR 由于代码修改，暂时关闭，感谢 PR
