### ISSUE TITLE
AKShare 接口问题报告 macro_china_swap_rate失效

### ISSUE THREAD

**Issue by wangjiale1998** [akfamily/akshare#4322]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本
2. Python 版本
3. AKShare 版本
akshare               1.10.93
4. 接口的名称和代码
macro_china_swap_rate
>>> import akshare as ak                                                                            
>>> macro_china_swap_rate_df = ak.macro_china_swap_rate(start_date="20220212", end_date="20220312")
5. 接口报错的截图或代码
![image](https://github.com/akfamily/akshare/assets/34213203/82cab056-38d8-4a5b-8603-d271e65efb69)
![image](https://github.com/akfamily/akshare/assets/34213203/c8e3c592-d21d-4dcb-92f7-5b1282811897)

6. 期望获得的正确结果
![image](https://github.com/akfamily/akshare/assets/34213203/6029698d-5879-4a58-9666-911732fa7410)

**Comment by albertandking** [comment]
> macro_china_swap_rate

接口正常

**Comment by wangjiale1998** [comment]
网站可能做了身份验证，当我访问该网址再运行代码，它确实也是正常的。但是在服务器上使用时，就没办法先用浏览器访问了。
