### ISSUE TITLE
美股基本面数据 异常

### ISSUE THREAD

**Issue by miabyss** [akfamily/akshare#4332]
```
Python 3.9.10 (tags/v3.9.10:f2f3f53, Jan 17 2022, 15:14:21) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import akshare as ak
>>>
>>> stock_us_fundamental_df = ak.stock_us_fundamental(stock="GOOGL", symbol="PB")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python39\lib\site-packages\akshare\stock\stock_us_sina.py", line 234, in stock_us_fundamental
    data_json = json.loads(temp_text)
  File "C:\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**描述遇到的问题**
1. 操作系统版本: Windows 10 专业版 x64 (10.0.19045 Build 19045)
2. Python 版本: 3.9.10
3. AKShare 版本: 1.11.89
4. 接口的名称和代码: 见上文
5. 接口报错的截图或代码: 见上文
6. 期望获得的正确结果: 运行无异常，或从官网移除过时的接口描述

**Comment by albertandking** [comment]
> ```
> Python 3.9.10 (tags/v3.9.10:f2f3f53, Jan 17 2022, 15:14:21) [MSC v.1929 64 bit (AMD64)] on win32
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import akshare as ak
> >>>
> >>> stock_us_fundamental_df = ak.stock_us_fundamental(stock="GOOGL", symbol="PB")
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "C:\Python39\lib\site-packages\akshare\stock\stock_us_sina.py", line 234, in stock_us_fundamental
>     data_json = json.loads(temp_text)
>   File "C:\Python39\lib\json\__init__.py", line 346, in loads
>     return _default_decoder.decode(s)
>   File "C:\Python39\lib\json\decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "C:\Python39\lib\json\decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本: Windows 10 专业版 x64 (10.0.19045 Build 19045)
> 2. Python 版本: 3.9.10
> 3. AKShare 版本: 1.11.89
> 4. 接口的名称和代码: 见上文
> 5. 接口报错的截图或代码: 见上文
> 6. 期望获得的正确结果: 运行无异常，或从官网移除过时的接口描述

感谢反馈问题，已移除相关接口
