### ISSUE TITLE
stock_zh_a_minute 接口最多只能返回1970长度的数据吗？不够用呀

### ISSUE THREAD

**Issue by qiusuor** [akfamily/akshare#4338]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本
2. Python 版本
3. AKShare 版本
4. 接口的名称和代码
5. 接口报错的截图或代码
6. 期望获得的正确结果

**Comment by albertandking** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本
> 2. Python 版本
> 3. AKShare 版本
> 4. 接口的名称和代码
> 5. 接口报错的截图或代码
> 6. 期望获得的正确结果

是的

**Comment by qiusuor** [comment]
你这关issue太快了。。。

**Comment by qiusuor** [comment]
有没有能拉取多点数据的方法，模型训练需要

**Comment by albertandking** [comment]
> 有没有能拉取多点数据的方法，模型训练需要

可以考虑商业数据库
