### ISSUE TITLE
[feature]巨潮公告

### ISSUE THREAD

**Issue by edwardsun** [akfamily/akshare#4346]
您好，
请问akshare有计划 增加巨潮资讯最新消息吗？

http://www.cninfo.com.cn/new/commonUrl/pageOfSearch?url=disclosure/list/search

最好能包括右侧的公告分类等各种详细信息

感谢

**Comment by albertandking** [comment]
> 您好， 请问akshare有计划 增加巨潮资讯最新消息吗？
> 
> http://www.cninfo.com.cn/new/commonUrl/pageOfSearch?url=disclosure/list/search
> 
> 最好能包括右侧的公告分类等各种详细信息
> 
> 感谢

升级到 AKShare 1.11.97 版本，新增 stock_zh_a_disclosure_report_cninfo 接口
