### ISSUE TITLE
建议增加实时行情的复权接口

### ISSUE THREAD

**Issue by xiatian12345** [akfamily/akshare#4347]
比如东方财富网-沪深京 A 股-实时行情数据 接口stock_zh_a_spot_em，增加输入参数adjust，以便于获取实时的复权数据

**Comment by albertandking** [comment]
> 比如东方财富网-沪深京 A 股-实时行情数据 接口stock_zh_a_spot_em，增加输入参数adjust，以便于获取实时的复权数据

需要在本地计算即可
