### ISSUE TITLE
[疑问&建议] stock_zh_a_disclosure_report_cninfo

### ISSUE THREAD

**Issue by edwardsun** [akfamily/akshare#4350]
请问下面两个函数有什么区别？
stock_zh_a_disclosure_report_cninfo
stock_zh_a_disclosure_relation_cninfo
文档中指向的链接都是http://www.cninfo.com.cn/new/commonUrl/pageOfSearch?url=disclosure/list/search

另外， stock_zh_a_disclosure_report_cninfo有几个小建议：
1. 保留日期中的时间部分。
2. 链接的pdf貌似不能直接引用。有没有可能给出的链接是可以直接下载？
3. 能否将symbol设为可选参数：如果不设置symbol，直接搜索给定时间范围内的所有公司?
4. 能否把右侧的分类加入为新的一列数据？
<img width="275" alt="image" src="https://github.com/akfamily/akshare/assets/359830/9cc23a9c-24af-45f7-a849-27368b96f56f">

**Comment by albertandking** [comment]
> 请问下面两个函数有什么区别？ stock_zh_a_disclosure_report_cninfo stock_zh_a_disclosure_relation_cninfo 文档中指向的链接都是http://www.cninfo.com.cn/new/commonUrl/pageOfSearch?url=disclosure/list/search
> 
> 另外， stock_zh_a_disclosure_report_cninfo有几个小建议：
> 
> 1. 保留日期中的时间部分。
> 2. 链接的pdf貌似不能直接引用。有没有可能给出的链接是可以直接下载？
> 3. 能否将symbol设为可选参数：如果不设置symbol，直接搜索给定时间范围内的所有公司?
> 4. 能否把右侧的分类加入为新的一列数据？
> 
> <img alt="image" width="275" src="https://private-user-images.githubusercontent.com/359830/291380653-9cc23a9c-24af-45f7-a849-27368b96f56f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5ODMzMzAsIm5iZiI6MTcwMjk4MzAzMCwicGF0aCI6Ii8zNTk4MzAvMjkxMzgwNjUzLTljYzIzYTljLTI0YWYtNDVmNy1hODQ5LTI3MzY4Yjk2ZjU2Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOVQxMDUwMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mN2NkM2NmMmQxNGZkNDA0NzNiM2E4YzQ4ZTY3NjYzNDRkOGY0YjFjMzU1NmIxNTc0YTk1NDA5MjkwNzdjYzA1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iNOFsCdchA6lMYDJPLZXP0UNvdYoAVEIDE__K9yZaBU">

已新增相关功能，升级到 AKShare 1.11.98 使用
