### ISSUE TITLE
再次建议增加实时行情的复权接口

### ISSUE THREAD

**Issue by xiatian12345** [akfamily/akshare#4351]
* 目的：获取实时数据的后复权数据
* 解决方法
    *  方法零：东财实时行情数据的接口stock_zh_a_spot_em 直接获取【问题：发现无法拿到后复权数据】
    *  方法一：拿到实时数据后除以后复权因子
        * 1.获取实时数据通过 东财实时行情数据的接口stock_zh_a_spot_em
        * 2.获取东财的复权因子，发现stock_zh_a_hist接口但是无法获取复权因子，adjust参数不支持hfq-factor【问题：无法获取后复权因子】
    *  方法二： 同方法一，不过数据从新浪获取
        * 1.获取实时数据通过 新浪实时行情数据的接口stock_zh_a_spot
        * 2.获取新浪的复权因子，发现stock_zh_a_daily接口可以获取复权因子，adjust参数支持hfq-factor，但是该接口有限量，且akshare也推荐使用东财的【问题：接口有限量，容易封ip】
* 综上：建议官方大大
    *  1.东财stock_zh_a_spot_em增加adjust参数以便于直接拿到后复权实时数据
    *  2.东财stock_zh_a_hist接口的adjust参数增加支持 hfq-factor以便于能拿到后复权因子

**Comment by albertandking** [comment]
> * 目的：获取实时数据的后复权数据
> * 解决方法
>   
>   * 方法零：东财实时行情数据的接口stock_zh_a_spot_em 直接获取【问题：发现无法拿到后复权数据】
>   * 方法一：拿到实时数据后除以后复权因子
>     
>     * 1.获取实时数据通过 东财实时行情数据的接口stock_zh_a_spot_em
>     * 2.获取东财的复权因子，发现stock_zh_a_hist接口但是无法获取复权因子，adjust参数不支持hfq-factor【问题：无法获取后复权因子】
>   * 方法二： 同方法一，不过数据从新浪获取
>     
>     * 1.获取实时数据通过 新浪实时行情数据的接口stock_zh_a_spot
>     * 2.获取新浪的复权因子，发现stock_zh_a_daily接口可以获取复权因子，adjust参数支持hfq-factor，但是该接口有限量，且akshare也推荐使用东财的【问题：接口有限量，容易封ip】
> * 综上：建议官方大大
>   
>   * 1.东财stock_zh_a_spot_em增加adjust参数以便于直接拿到后复权实时数据
>   * 2.东财stock_zh_a_hist接口的adjust参数增加支持 hfq-factor以便于能拿到后复权因子

建议在本地实现，接口暂不提供该实现

**Comment by xiatian12345** [comment]
后复权因子获取不到该怎么实现呢

**Comment by xiatian12345** [comment]
两个接口新浪的stock_zh_a_daily和东财的stock_zh_a_hist，都是获取历史数据，但是新浪可以获取复权因子，东财不可以获取，官方又建议用东财的。。。。本地可以实现但是你得提供复权因子啊，否则怎么实现呢
