### ISSUE TITLE
AKShare 接口ak.stock_zh_index_spot问题报告

### ISSUE THREAD

**Issue by eshion** [akfamily/akshare#4355]
stock_zh_index_spot_df = ak.stock_zh_index_spot()

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-6-5ff343b3729a>](https://localhost:8080/#) in <cell line: 1>()
----> 1 stock_zh_index_spot_df = ak.stock_zh_index_spot()
      2 stock_zh_index_spot_df.head()

1 frames
[/usr/local/lib/python3.10/dist-packages/pandas/core/generic.py](https://localhost:8080/#) in __getattr__(self, name)
   5900         ):
   5901             return self[name]
-> 5902         return object.__getattribute__(self, name)
   5903 
   5904     def __setattr__(self, name: str, value) -> None:

AttributeError: 'DataFrame' object has no attribute 'map'

**Comment by albertandking** [comment]
> stock_zh_index_spot_df = ak.stock_zh_index_spot()
> 
> AttributeError Traceback (most recent call last) in <cell line: 1>() ----> 1 stock_zh_index_spot_df = ak.stock_zh_index_spot() 2 stock_zh_index_spot_df.head()
> 
> 1 frames [/usr/local/lib/python3.10/dist-packages/pandas/core/generic.py](https://localhost:8080/#) in **getattr**(self, name) 5900 ): 5901 return self[name] -> 5902 return object.**getattribute**(self, name) 5903 5904 def **setattr**(self, name: str, value) -> None:
> 
> AttributeError: 'DataFrame' object has no attribute 'map'

接口测试正常
