### ISSUE TITLE
hurun_rank()接口报错，请帮忙修复

### ISSUE THREAD

**Issue by tianhaisuifeng** [akfamily/akshare#4357]
akshare最新版本，hurun_rank()接口报错：
hurun_rank_df = hurun_rank(indicator="胡润百富榜", year="2022")
r = requests.get(name_url_map[indicator])
KeyError: '胡润百富榜'

**Comment by albertandking** [comment]
> akshare最新版本，hurun_rank()接口报错： hurun_rank_df = hurun_rank(indicator="胡润百富榜", year="2022") r = requests.get(name_url_map[indicator]) KeyError: '胡润百富榜'

感谢反馈问题，已修复，升级到 AKShare 1.12.2 使用
