### ISSUE TITLE
stock_zh_a_disclosure_report_cninfo_df 接口问题报告

### ISSUE THREAD

**Issue by gapbridger** [akfamily/akshare#4360]
python 3.9.18
akshare 1.12.2

import akshare as ak
stock_zh_a_disclosure_report_cninfo_df = ak.stock_zh_a_disclosure_report_cninfo(symbol="000001", market="沪深京", category="年报", start_date="20230619", end_date="20231220")

![2023-12-22 23-49-20屏幕截图](https://github.com/akfamily/akshare/assets/2617565/8d94016e-fd64-410d-b060-13a1cebb3d55)

**Comment by albertandking** [comment]
> stock_zh_a_disclosure_report_cninfo

接口测试正常，按调用规则使用

**Comment by gapbridger** [comment]
> > stock_zh_a_disclosure_report_cninfo
> 
> 接口测试正常，按调用规则使用

作者你好，这个是我在官方文档中查到的调用方式，我直接复制到python程序中会报错，如果是这个示例没有按照调用规则调用是否可以麻烦你调整一下这个示例？

是否需要我把这个示例的链接给您贴上来？

stock_zh_a_disclosure_report_cninfo_df = ak.stock_zh_a_disclosure_report_cninfo(symbol="000001", market="沪深京", category="公司治理", start_date="20230619", end_date="20231220")
