### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by JiangHan-Ivy** [akfamily/akshare#4361]
以下几个接口有问题：
ak.stock_gdfx_holding_analyse_em()
stock_gdfx_holding_detail_em
<img width="1079" alt="image" src="https://github.com/akfamily/akshare/assets/137281958/09449300-7249-4498-9b60-8f1c1a961936">

ak.stock_gdfx_free_holding_detail_em
<img width="1102" alt="image" src="https://github.com/akfamily/akshare/assets/137281958/09e6ed59-1c85-4d79-a55d-7c38a0fa3792">

**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本
2. Python 版本
3. AKShare 版本
4. 接口的名称和代码
5. 接口报错的截图或代码
6. 期望获得的正确结果

**Comment by albertandking** [comment]
> stock_gdfx_holding_analyse_em

接口正常
