### ISSUE TITLE
基金相关接口，需要限制性代码

### ISSUE THREAD

**Issue by kevinfuture** [akfamily/akshare#4362]
例如以下接口：
ak.amac_member_info
<img width="746" alt="image" src="https://github.com/akfamily/akshare/assets/6711652/3df0fdd2-fee9-4304-b93c-2586bcfc745f">

添加判断代码，似乎更好
  if temp_df.empty:  # 处理获取数据为空的问题
      return pd.DataFrame()

**Comment by albertandking** [comment]
> amac_member_info



> 例如以下接口： ak.amac_member_info <img alt="image" width="746" src="https://private-user-images.githubusercontent.com/6711652/292609268-3df0fdd2-fee9-4304-b93c-2586bcfc745f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1MDM3MjAsIm5iZiI6MTcwMzUwMzQyMCwicGF0aCI6Ii82NzExNjUyLzI5MjYwOTI2OC0zZGYwZmRkMi1mZWU5LTQzMDQtYjkzYy0yNTg2YmNmYzc0NWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjVUMTEyMzQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTQ0YmE0NTRmNzU5NTM5YjNhOGNlYjFkYWI2N2JiNGRmN2NmODFkMjMzYTE1MTU1ZmQ1M2U1YWFmNjg5Njg5NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.SpWP9hXFdaz-QLaFPRO-4ynS-V2vdoeyHsm7uKGFdj0">
> 
> 添加判断代码，似乎更好 if temp_df.empty: # 处理获取数据为空的问题 return pd.DataFrame()

是的
