### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by transformeris** [akfamily/akshare#4363]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本：win10
2. Python 版本：3.8
3. AKShare 版本：'1.12.2'
4. 接口的名称和代码:ak.index_investing_global_area_index_name_url()以及其他与英为财情有关的接口。
5. 接口报错的截图或代码：Traceback (most recent call last):
  File "D:\Anaconda\lib\site-packages\IPython\core\interactiveshell.py", line 3418, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-10-df4491f618e1>", line 1, in <module>
    ak.index_investing_global_from_url(url="https://www.investing.com/indices/ftse-epra-nareit-hong-kong", period="每日", start_date="19900101", end_date="19910909")
  File "C:\Users\aaa\AppData\Roaming\Python\Python38\site-packages\akshare\index\index_investing.py", line 243, in index_investing_global_from_url
    data_text = soup.find("script", attrs={"id": "__NEXT_DATA__"}).text
AttributeError: 'NoneType' object has no attribute 'text'
7. 期望获得的正确结果
文档中只在index_investing_global接口的说明中说明接口不可用，请问是否所有与英为财情有关的接口都不可用？

**Comment by albertandking** [comment]
> 4\. index_investing_global_area_index_name_url

对的

**Comment by transformeris** [comment]
那请问现在有接口能够获取外国指数，例如日经或德国dax指数的吗？
