### ISSUE TITLE
stock_hsgt_fund_flow_summary_em的日期能否更准确？

### ISSUE THREAD

**Issue by bronzebag** [akfamily/akshare#4364]
**Describe the bug**
今天陆股通暂停，stock_hsgt_fund_flow_summary_em仍然可以获取数据，获取的数据，实际是上个交易日的数据，但日期是今天的日期。以后再看，容易造成误解。

**To Reproduce**
>>> df = ak.stock_hsgt_fund_flow_summary_em()
>>> df
          交易日   类型      板块 资金方向  交易状态      成交净买额      资金净流入      当日资金余额  上涨数  持平数  下跌数  相关指数  指数涨跌幅
0  2023-12-25  沪港通     沪股通   北向     4  -4.286213   1.203421  518.796579  584   57  699  上证指数   0.14
1  2023-12-25  沪港通  港股通(沪)   南向     4 -25.879641 -10.560981  430.560981  138   52  365  恒生指数  -1.69
2  2023-12-25  深港通     深股通   北向     4 -20.823640 -14.401541  534.401541  658   51  817  深证成指   0.38
3  2023-12-25  深港通  港股通(深)   南向     4 -16.892113  -5.709817  425.709817  138   52  365  恒生指数  -1.69

**Expected behavior**
希望的结果是，交易日显示成2023-12-22，或者其他消除误解的方法。

**Comment by albertandking** [comment]
> stock_hsgt_fund_flow_summary_em

可以通过 `交易状态` 判断，目前跟数据源接口的数据一致
