### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by nkta3m** [akfamily/akshare#4366]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. windows 10
2. Python 3.10.11
3. AKShare 1.12.3
4. ak.stock_zh_index_spot()
5. 
![2023-12-27 09_57_03-Window](https://github.com/akfamily/akshare/assets/13484700/3af8c656-53d1-4937-83d7-ad698a4a85a8)

6. 获得正确结果

回退到1.11.35，正确运行，没有问题

**Comment by albertandking** [comment]
> 4\. stock_zh_index_spot

接口正常；升级 Pandas 到最新
