### ISSUE TITLE
stock_board_industry_index_ths 接口优化

### ISSUE THREAD

**Issue by Frost2026** [akfamily/akshare#4368]
**描述遇到的问题**
1. 接口的名称和代码
2. 接口报错的截图或代码
3. 期望获得的正确结果
```python
def stock_board_industry_index_ths(
    symbol: str = "半导体及元件",
    start_date: str = "20200101",
    end_date: str = "20211027",
) -> pd.DataFrame:
    """
    同花顺-板块-行业板块-指数数据
    http://q.10jqka.com.cn/gn/detail/code/301558/
    :param start_date: 开始时间
    :type start_date: str
    :param end_date: 结束时间
    :type end_date: str
    :param symbol: 指数数据
    :type symbol: str
    :return: 指数数据
    :rtype: pandas.DataFrame
    """
    code_map = stock_board_industry_name_ths()
    code_map = dict(zip(code_map["name"].values, code_map["code"].values))
    symbol_code = code_map[symbol]
    big_df = pd.DataFrame()
    current_year = datetime.now().year
    for year in tqdm(range(2000, current_year + 1), leave=False):
    ..........
    big_df["日期"] = pd.to_datetime(big_df["日期"]).dt.date
    big_df.index = pd.to_datetime(big_df["日期"])
    big_df = big_df[start_date:end_date]
    big_df.reset_index(drop=True, inplace=True)
    big_df["开盘价"] = pd.to_numeric(big_df["开盘价"], errors="coerce")
    big_df["最高价"] = pd.to_numeric(big_df["最高价"], errors="coerce")
    big_df["最低价"] = pd.to_numeric(big_df["最低价"], errors="coerce")
    big_df["收盘价"] = pd.to_numeric(big_df["收盘价"], errors="coerce")
    big_df["成交量"] = pd.to_numeric(big_df["成交量"], errors="coerce")
    big_df["成交额"] = pd.to_numeric(big_df["成交额"], errors="coerce")
    return big_df
```
stock_board_industry_index_ths接口接受参数start_date和end_date，但采集数据是固定从2000年至今，只有在返回结果时才通过传入的start_date和end_date截取并返回。这样比较低效，建议改为通过传入的时间采集。

**Comment by albertandking** [comment]
> **描述遇到的问题**
> 
> 1. 接口的名称和代码
> 2. 接口报错的截图或代码
> 3. 期望获得的正确结果
> 
> ```python
> def stock_board_industry_index_ths(
>     symbol: str = "半导体及元件",
>     start_date: str = "20200101",
>     end_date: str = "20211027",
> ) -> pd.DataFrame:
>     """
>     同花顺-板块-行业板块-指数数据
>     http://q.10jqka.com.cn/gn/detail/code/301558/
>     :param start_date: 开始时间
>     :type start_date: str
>     :param end_date: 结束时间
>     :type end_date: str
>     :param symbol: 指数数据
>     :type symbol: str
>     :return: 指数数据
>     :rtype: pandas.DataFrame
>     """
>     code_map = stock_board_industry_name_ths()
>     code_map = dict(zip(code_map["name"].values, code_map["code"].values))
>     symbol_code = code_map[symbol]
>     big_df = pd.DataFrame()
>     current_year = datetime.now().year
>     for year in tqdm(range(2000, current_year + 1), leave=False):
>     ..........
>     big_df["日期"] = pd.to_datetime(big_df["日期"]).dt.date
>     big_df.index = pd.to_datetime(big_df["日期"])
>     big_df = big_df[start_date:end_date]
>     big_df.reset_index(drop=True, inplace=True)
>     big_df["开盘价"] = pd.to_numeric(big_df["开盘价"], errors="coerce")
>     big_df["最高价"] = pd.to_numeric(big_df["最高价"], errors="coerce")
>     big_df["最低价"] = pd.to_numeric(big_df["最低价"], errors="coerce")
>     big_df["收盘价"] = pd.to_numeric(big_df["收盘价"], errors="coerce")
>     big_df["成交量"] = pd.to_numeric(big_df["成交量"], errors="coerce")
>     big_df["成交额"] = pd.to_numeric(big_df["成交额"], errors="coerce")
>     return big_df
> ```
> 
> stock_board_industry_index_ths接口接受参数start_date和end_date，但采集数据是固定从2000年至今，只有在返回结果时才通过传入的start_date和end_date截取并返回。这样比较低效，建议改为通过传入的时间采集。

数据源暂不支持

**Comment by Frost2026** [comment]
```python
    for year in tqdm(range(2000, current_year + 1), leave=False):
        url = f"http://d.10jqka.com.cn/v4/line/bk_{symbol_code}/01/{year}.js"
        headers = {
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
            "Referer": "http://q.10jqka.com.cn",
            "Host": "d.10jqka.com.cn",
        }
```
这里的'year'改为start_date的年即可

**Comment by albertandking** [comment]
> ```python
>     for year in tqdm(range(2000, current_year + 1), leave=False):
>         url = f"http://d.10jqka.com.cn/v4/line/bk_{symbol_code}/01/{year}.js"
>         headers = {
>             "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
>             "Referer": "http://q.10jqka.com.cn",
>             "Host": "d.10jqka.com.cn",
>         }
> ```
> 
> 这里的'year'改为start_date的年即可

感谢提供解决方案，已修复该问题，升级到 AKShare 1.12.18 使用
