### ISSUE TITLE
py2matlab issue about transfer python date to matlab char for py.akshare.stock_zh_a_hist

### ISSUE THREAD

**Issue by Gavid323** [akfamily/akshare#4370]
After extracting data by using py.akshare.stock_zh_a_hist, I use py2matlab to transfer python dataframe to matlab table. However, the date cannot be transferred. Can anybody do me a favor? Thank you very much in advance!

![Screenshot 2023-12-30 at 12 09 10](https://github.com/akfamily/akshare/assets/149929988/d2c1c1f0-c224-43ee-9903-5f6462d53573)

**Comment by albertandking** [comment]
> After extracting data by using py.akshare.stock_zh_a_hist, I use py2matlab to transfer python dataframe to matlab table. However, the date cannot be transferred. Can anybody do me a favor? Thank you very much in advance!
> 
> ![Screenshot 2023-12-30 at 12 09 10](https://private-user-images.githubusercontent.com/149929988/293442593-d2c1c1f0-c224-43ee-9903-5f6462d53573.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwMTIxNTQsIm5iZiI6MTcwNDAxMTg1NCwicGF0aCI6Ii8xNDk5Mjk5ODgvMjkzNDQyNTkzLWQyYzFjMWYwLWMyMjQtNDNlZS05OTAzLTVmNjQ2MmQ1MzU3My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjMxMjMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIzMVQwODM3MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZmE5ZWE5ODU0YzQwNjZhYjZjNzg1YTQ2M2FlZmQ2NDAwYWFkMWVlNDcwZTE5YTY0NzI3YjdmM2U4ZDI5MWZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.upf4dzLArK9tykj0sJA0Qi4cqlkGAeQdYtN8yodGMf0)

目前调用正常，请安装较新版本的 matlab

**Comment by onepersononecity** [comment]
我也遇到这问题了，有比较慢的解决办法，但希望找到更快的
bond_zh_us_rate_df = ak.bond_zh_us_rate(start_date="19901219") ;

df = py2matlab(bond_zh_us_rate_df);
 length_df= size(df) ;

for i = 1:1:length_df(1,1)

dates(i) =datetime(double(df.(1){i,1}.year),double(df.(1){i,1}.month),double(df.(1){i,1}.day) );
end

**Comment by onepersononecity** [comment]
解决了吗
