### ISSUE TITLE
AKShare 接口问题报告index_value_hist_funddb

### ISSUE THREAD

**Issue by fweiger** [akfamily/akshare#4371]
index_value_hist_funddb  

和https://funddb.cn/site/index不少接口都挂掉了

https://akshare.akfamily.xyz/data/stock/stock.html#id261

![image](https://github.com/akfamily/akshare/assets/10492719/740deea5-ae0b-4fd8-9873-b107c2146211)

**Comment by albertandking** [comment]
> index_value_hist_funddb

接口测试正常，升级到最新版使用
