### ISSUE TITLE
开放式基金-历史数据-累计收益率走势数据获取不完整

### ISSUE THREAD

**Issue by none2003** [akfamily/akshare#4372]
**描述遇到的问题**
1. 操作系统版本：Win11
2. Python 版本：3.9.16
3. AKShare 版本：1.12.5
4. 接口的名称和代码
```
import akshare as ak

fund_open_fund_info_em_df = ak.fund_open_fund_info_em(fund="710001", indicator="累计收益率走势")
print(fund_open_fund_info_em_df)
```
5. 接口报错的截图或代码
得到的结果是最近6个月的累计收益率，而非全部的。
![image](https://github.com/akfamily/akshare/assets/10540630/fd46ce3f-9e9d-4dd1-b047-47705c1dbb52)

7. 期望获得的正确结果
从天天基金网看，“累计收益率走势”部分，默认是选中“6月”的，估计这也是akshare接口默认只获取到最近6个月数据的原因，但其实可以选择“成立来”，既可以获取全部的累计收益率数据。具体可以看截图和网页：https://fund.eastmoney.com/710001.html
![image](https://github.com/akfamily/akshare/assets/10540630/28e540a7-f1a9-4ed6-a31a-355e25cdfb76)

**Comment by albertandking** [comment]
> **描述遇到的问题**
> 
> 1. 操作系统版本：Win11
> 2. Python 版本：3.9.16
> 3. AKShare 版本：1.12.5
> 4. 接口的名称和代码
> 
> ```
> import akshare as ak
> 
> fund_open_fund_info_em_df = ak.fund_open_fund_info_em(fund="710001", indicator="累计收益率走势")
> print(fund_open_fund_info_em_df)
> ```
> 
> 5. 接口报错的截图或代码
>    得到的结果是最近6个月的累计收益率，而非全部的。
>    ![image](https://private-user-images.githubusercontent.com/10540630/293495382-fd46ce3f-9e9d-4dd1-b047-47705c1dbb52.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwMTQ4NDAsIm5iZiI6MTcwNDAxNDU0MCwicGF0aCI6Ii8xMDU0MDYzMC8yOTM0OTUzODItZmQ0NmNlM2YtOWU5ZC00ZGQxLWIwNDctNDc3MDVjMWRiYjUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMxVDA5MjIyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3NmU0ZTM4NzRkMWU0NDE2ODdkYmI4MTNiNmY2NWVmMmU0NmRjNTE3MjI0ZGU4NGM0NmVjYTA2Zjk0ZmJjNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KHYkYrxGoALh0LKWkvjEMuyzaSvcUsswoLv0nrSxk5U)
> 6. 期望获得的正确结果
>    从天天基金网看，“累计收益率走势”部分，默认是选中“6月”的，估计这也是akshare接口默认只获取到最近6个月数据的原因，但其实可以选择“成立来”，既可以获取全部的累计收益率数据。具体可以看截图和网页：https://fund.eastmoney.com/710001.html
>    ![image](https://private-user-images.githubusercontent.com/10540630/293495506-28e540a7-f1a9-4ed6-a31a-355e25cdfb76.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwMTQ4NDAsIm5iZiI6MTcwNDAxNDU0MCwicGF0aCI6Ii8xMDU0MDYzMC8yOTM0OTU1MDYtMjhlNTQwYTctZjFhOS00ZWQ2LWEzMWEtMzU1ZTI1Y2RmYjc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMxVDA5MjIyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0ZWYxMjYyNzRiNTk1ZjdhN2U0NTNmNGEzNDk5NTNkODhmMmZmOGM2MGE4ODg5ZTI2MDFiODBhMTVlNGY4NzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8vzfJk0xPfLL_iVs2s1s5kcDpLkZ00R4QcIDmRb0qKU)

感谢反馈问题，升级到 AKShare 1.12.6 使用，新增相关字段，请查看文档

**Comment by none2003** [comment]
> > **描述遇到的问题**
> > 
> > 1. 操作系统版本：Win11
> > 2. Python 版本：3.9.16
> > 3. AKShare 版本：1.12.5
> > 4. 接口的名称和代码
> > 
> > ```
> > import akshare as ak
> > 
> > fund_open_fund_info_em_df = ak.fund_open_fund_info_em(fund="710001", indicator="累计收益率走势")
> > print(fund_open_fund_info_em_df)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 5. 接口报错的截图或代码
> >    得到的结果是最近6个月的累计收益率，而非全部的。
> >    ![image](https://private-user-images.githubusercontent.com/10540630/293495382-fd46ce3f-9e9d-4dd1-b047-47705c1dbb52.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwMTQ4NDAsIm5iZiI6MTcwNDAxNDU0MCwicGF0aCI6Ii8xMDU0MDYzMC8yOTM0OTUzODItZmQ0NmNlM2YtOWU5ZC00ZGQxLWIwNDctNDc3MDVjMWRiYjUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMxVDA5MjIyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3NmU0ZTM4NzRkMWU0NDE2ODdkYmI4MTNiNmY2NWVmMmU0NmRjNTE3MjI0ZGU4NGM0NmVjYTA2Zjk0ZmJjNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KHYkYrxGoALh0LKWkvjEMuyzaSvcUsswoLv0nrSxk5U)
> > 6. 期望获得的正确结果
> >    从天天基金网看，“累计收益率走势”部分，默认是选中“6月”的，估计这也是akshare接口默认只获取到最近6个月数据的原因，但其实可以选择“成立来”，既可以获取全部的累计收益率数据。具体可以看截图和网页：https://fund.eastmoney.com/710001.html
> >    ![image](https://private-user-images.githubusercontent.com/10540630/293495506-28e540a7-f1a9-4ed6-a31a-355e25cdfb76.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwMTQ4NDAsIm5iZiI6MTcwNDAxNDU0MCwicGF0aCI6Ii8xMDU0MDYzMC8yOTM0OTU1MDYtMjhlNTQwYTctZjFhOS00ZWQ2LWEzMWEtMzU1ZTI1Y2RmYjc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMxVDA5MjIyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0ZWYxMjYyNzRiNTk1ZjdhN2U0NTNmNGEzNDk5NTNkODhmMmZmOGM2MGE4ODg5ZTI2MDFiODBhMTVlNGY4NzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8vzfJk0xPfLL_iVs2s1s5kcDpLkZ00R4QcIDmRb0qKU)
> 
> 感谢反馈问题，升级到 AKShare 1.12.6 使用，新增相关字段，请查看文档

清仔细检查下是否symbol参数固定传值是710001？

![image](https://github.com/akfamily/akshare/assets/10540630/17845c02-2743-4641-87ed-b8af4c6b2112)
