### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by lenhill** [akfamily/akshare#4375]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本 :   Ubuntu20.4
2. Python 版本  :  3.8
3. AKShare 版本 :  1.12.5
4. 接口的名称和代码  :  stock_hot_rank_wc
                                      stock_hot_rank_wc_df = ak.stock_hot_rank_wc(date="20231229")
                                      print(stock_hot_rank_wc_df)
5. 接口报错的截图或代码
<img width="553" alt="2023-12-31_160411" src="https://github.com/akfamily/akshare/assets/34260429/1d16fe43-3c04-4053-b1dd-4bd3321c2264">
<img width="553" alt="2023-12-31_160630" src="https://github.com/akfamily/akshare/assets/34260429/ffaf1615-c9cf-4794-a1b0-77d8615a24f4">

6. 期望获得的正确结果
单次返回近 5000 个股票的热门排名数据

**Comment by albertandking** [comment]
> 4\. stock_hot_rank_wc_df = ak.stock_hot_rank_wc(date="20231229")
>     print(stock_hot_rank_wc_df)

接口正常，不能频繁调用
