### ISSUE TITLE
开放式基金-历史数据-累计收益率走势数据有误

### ISSUE THREAD

**Issue by none2003** [akfamily/akshare#4376]
**描述遇到的问题**
1. 操作系统版本：Win11
2. Python 版本：3.9.16
3. AKShare 版本：1.12.6
4. 接口的名称和代码
```
import akshare as ak

fund_open_fund_info_em_df = ak.fund_open_fund_info_em(symbol="240018", indicator="累计收益率走势", period='成立来')
fund_open_fund_info_em_df
```
5. 接口报错的截图或代码
无论怎么改变symbol的值，返回的df结果都是一样的。

7. 期望获得的正确结果
看了一眼源代码，貌似固定无论symbol设置什么值，在发送请求之前都被替换成了710001。
![image](https://github.com/akfamily/akshare/assets/10540630/17845c02-2743-4641-87ed-b8af4c6b2112)

**Comment by albertandking** [comment]
> **描述遇到的问题**
> 
> 1. 操作系统版本：Win11
> 2. Python 版本：3.9.16
> 3. AKShare 版本：1.12.6
> 4. 接口的名称和代码
> 
> ```
> import akshare as ak
> 
> fund_open_fund_info_em_df = ak.fund_open_fund_info_em(symbol="240018", indicator="累计收益率走势", period='成立来')
> fund_open_fund_info_em_df
> ```
> 
> 5. 接口报错的截图或代码
>    无论怎么改变symbol的值，返回的df结果都是一样的。
> 6. 期望获得的正确结果
>    看了一眼源代码，貌似固定无论symbol设置什么值，在发送请求之前都被替换成了710001。
>    ![image](https://private-user-images.githubusercontent.com/10540630/293501825-17845c02-2743-4641-87ed-b8af4c6b2112.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxODUxODMsIm5iZiI6MTcwNDE4NDg4MywicGF0aCI6Ii8xMDU0MDYzMC8yOTM1MDE4MjUtMTc4NDVjMDItMjc0My00NjQxLTg3ZWQtYjhhZjRjNmIyMTEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDA4NDEyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExNTRlMTAzYzc0MzkyMzExMzZkOGI0NjFjZDI1NDJhMTBkMjg4MTY2ZGNlYWZlNTZjOWUxOTMzYzgwM2JlYmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RUgXgJLX-qyBnDvu6fs3cmjXSYP-PXH63igX5XwIz3Y)

感谢反馈问题，已修复该问题，升级到 AKShare 1.12.8 使用
