### ISSUE TITLE
建议：新增同花顺特有板块(非行业，非概念)的历史行情数据，如，"同花顺热股"；以及隔夜海外中概股相关指数，如，"纳斯达克金龙中国指数"“HXC”

### ISSUE THREAD

**Issue by xzz4316** [akfamily/akshare#4377]
个人是做主观，尝试自学转量化的。非专业程序员，提问不专业请多多包涵。

A股大盘大行情确实是决定短线收益的一个关键点。有时大盘虽然不好，但短线资金对部分板块做多意愿很强，这时依然是有机会的。除了上涨/下跌股数，涨停总数，"同花顺热股""883910"短期走势强度也是一个我常用的指标；除了分析大盘走势，隔夜的美股中概股行情有时也值得参考，例如"纳斯达克金龙中国指数"，如果走坏可以反映一些盘后利空(如盘后发布的政策，隔夜美联储加息等等)。

我尝试了ak.stock_board_concept_hist_ths和ak.stock_board_industry_index_ths输入"同花顺热股"想查询近期历史数据，它们都显示错误；但是用ak.stock_board_cons_ths，输入"883910"又能准确调出成分股。此外，在"AKshare指数数据"部分似乎也没有找到合适的接口。

自学python只是希望能省一些看盘时间，不清楚量化大佬维护库的具体时间成本，以上只是一些个人的建议和心得。再次感谢大佬的贡献，祝新年快乐财源滚滚。

**Comment by albertandking** [comment]
> 个人是做主观，尝试自学转量化的。非专业程序员，提问不专业请多多包涵。
> 
> A股大盘大行情确实是决定短线收益的一个关键点。有时大盘虽然不好，但短线资金对部分板块做多意愿很强，这时依然是有机会的。除了上涨/下跌股数，涨停总数，"同花顺热股""883910"短期走势强度也是一个我常用的指标；除了分析大盘走势，隔夜的美股中概股行情有时也值得参考，例如"纳斯达克金龙中国指数"，如果走坏可以反映一些盘后利空(如盘后发布的政策，隔夜美联储加息等等)。
> 
> 我尝试了ak.stock_board_concept_hist_ths和ak.stock_board_industry_index_ths输入"同花顺热股"想查询近期历史数据，它们都显示错误；但是用ak.stock_board_cons_ths，输入"883910"又能准确调出成分股。此外，在"AKshare指数数据"部分似乎也没有找到合适的接口。
> 
> 自学python只是希望能省一些看盘时间，不清楚量化大佬维护库的具体时间成本，以上只是一些个人的建议和心得。再次感谢大佬的贡献，祝新年快乐财源滚滚。

感谢支持
