### ISSUE TITLE
fund_open_fund_info_em will crash while temp_df is empty

### ISSUE THREAD

**Issue by liuweijiaCHN** [akfamily/akshare#4378]
akshare/fund/fund_em.py : 366 line:
temp_df["x"], unit="ms", utc=True
raise KeyError(key)
KeyError: 'x'

====================
suggest at 366 line:
if temp_df.empty:
    return pd.DataFrame()

**Comment by albertandking** [comment]
> akshare/fund/fund_em.py : 366 line: temp_df["x"], unit="ms", utc=True raise KeyError(key) KeyError: 'x'
> 
> ==================== suggest at 366 line: if temp_df.empty: return pd.DataFrame()

感谢反馈问题，已修复该问题，升级到 AKShare 1.12.8 使用
