### ISSUE TITLE
坐等更新calendar.json啊

### ISSUE THREAD

**Issue by dominicx** [akfamily/akshare#4379]
**Describe the bug**

2024年第一天，一堆非工作日报错。Today is not working day：20240102
 只要用到了akshare.option.cons 有关calendar的方法 都报错了。

**Comment by dominicx** [comment]
已经创建了#4380 pull，请审核合并。

**Comment by albertandking** [comment]
> **Describe the bug**
> 
> 2024年第一天，一堆非工作日报错。Today is not working day：20240102 只要用到了akshare.option.cons 有关calendar的方法 都报错了。

感谢反馈问题，已修复，升级到 AKShare 1.12.7 使用
