### ISSUE TITLE
筹码分布计算

### ISSUE THREAD

**Issue by ssgmr** [akfamily/akshare#4383]
stock_cyq_em这个方法中，接口请求参数'lmt': 默认是210，调整这个参数可以返回更多的k线数据。但是计算筹码分布的js代码html_str中，该如何修改以支持更多历史数据的筹码分布计算？

**Comment by albertandking** [comment]
> stock_cyq_em

由于该接口是获取到数据后在本地计算完成，如果大量获取会导致计算缓慢，建议根据自己的需求在本地修改代码使用
