### ISSUE TITLE
get_receipt广期所问题

### ISSUE THREAD

**Issue by choir2001** [akfamily/akshare#4384]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
5. 接口报错的截图或代码
ak_data=akshare.get_receipt(start_day='20240102', end_day='20240102', vars_list=['SI'])
2024-01-02

ak_data
Out[9]: 
  var  receipt  receipt_chg      date
0  LC     8240          710  20240102
1  SI    38065            0  20240102

6. 期望获得的正确结果
get_receipt参数中指定广期所任一品种，都会错误返回两个品种的数据。希望只返回一个品种

**Comment by albertandking** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> **描述遇到的问题** 5. 接口报错的截图或代码 ak_data=akshare.get_receipt(start_day='20240102', end_day='20240102', vars_list=['SI']) 2024-01-02
> 
> ak_data Out[9]: var receipt receipt_chg date 0 LC 8240 710 20240102 1 SI 38065 0 20240102
> 
> 6. 期望获得的正确结果
>    get_receipt参数中指定广期所任一品种，都会错误返回两个品种的数据。希望只返回一个品种

感谢反馈问题，已修复该问题，升级到 AKShare 1.12.9 使用
