### ISSUE TITLE
希望加入港股的盈利预测数据

### ISSUE THREAD

**Issue by eshion** [akfamily/akshare#4392]
https://hk.finance.yahoo.com/quote/9999.HK/analysis

https://www.etnet.com.hk/www/sc/stocks/realtime/quote_profit.php?code=9999

**Comment by albertandking** [comment]
> https://hk.finance.yahoo.com/quote/9999.HK/analysis
> 
> https://www.etnet.com.hk/www/sc/stocks/realtime/quote_profit.php?code=9999

已新增 stock_hk_profit_forecast_et 接口，升级到 AKShare 1.12.14 使用；https://hk.finance.yahoo.com/quote/9999.HK/analysis 可以用yfinance
