### ISSUE TITLE
AKShare ak.stock_hk_profit_forecast_et接口问题报告

### ISSUE THREAD

**Issue by eshion** [akfamily/akshare#4396]
ak.stock_hk_profit_forecast_et(symbol='00856',indicator="盈利预测概览")

接口包错：
00856 KeyError '纯利/亏损'
猜测是列名有这些的时候会包错：

纯利/(亏损)(百万港元) | 每股盈利*/(亏损) (港仙) | 每股派息*(港仙)

https://www.etnet.com.hk/www/sc/stocks/realtime/quote_profit.php?code=00856

**Comment by albertandking** [comment]
> ak.stock_hk_profit_forecast_et(symbol='00856',indicator="盈利预测概览")
> 
> 接口包错： 00856 KeyError '纯利/亏损' 猜测是列名有这些的时候会包错：
> 
> 纯利/(亏损)(百万港元) | 每股盈利*/(亏损) (港仙) | 每股派息*(港仙)
> 
> https://www.etnet.com.hk/www/sc/stocks/realtime/quote_profit.php?code=00856

已修复该问题，升级到 AKShare 1.12.15 使用
