### ISSUE TITLE
AKShare 接口问题报告：stock_zh_a_tick_tx只有沪深的A股数据，没有京A的历史分笔数据，为什么？还有其他接口吗？

### ISSUE THREAD

**Issue by JyiHUO** [akfamily/akshare#4401]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
stock_zh_a_tick_tx只有沪深的A股数据，没有京A的历史分笔数据，为什么？

**Comment by jasonudu** [comment]
请问在中国大陆怎么更新？

  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)")': /packages/15/86/6ef05f0b51a36dbec2b260da7a93ed0096dea32e708e127c5051b875af2d/akracer-0.0.13-py3-none-any.whl

**Comment by albertandking** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> **描述遇到的问题** stock_zh_a_tick_tx只有沪深的A股数据，没有京A的历史分笔数据，为什么？

数据源只提供这些
