### ISSUE TITLE
使用接口获取数据，只有到2023年年底的数据，没有今年的数据

### ISSUE THREAD

**Issue by jasonudu** [akfamily/akshare#4402]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. windows11
2. Python3.8.8  64位
3. AKShare 版本  1.11.18
4. 接口的名称和代码
  GFEfutures_daily_df = ak.get_futures_daily(start_date=b_dt, end_date=e_dt, market="GFEX")
5. 接口报错的截图或代码
   获取的时间是2023-12-18到2024-01-05，但得到的数据最新只有2023-12-29日的
6. 期望获得的正确结果
   预期应该包含2024年的数据，但接口似乎只能提取到2023年的数据

**Comment by albertandking** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> **描述遇到的问题**
> 
> 1. windows11
> 2. Python3.8.8  64位
> 3. AKShare 版本  1.11.18
> 4. 接口的名称和代码
>    GFEfutures_daily_df = ak.get_futures_daily(start_date=b_dt, end_date=e_dt, market="GFEX")
> 5. 接口报错的截图或代码
>    获取的时间是2023-12-18到2024-01-05，但得到的数据最新只有2023-12-29日的
> 6. 期望获得的正确结果
>    预期应该包含2024年的数据，但接口似乎只能提取到2023年的数据

升级到最新版

**Comment by jasonudu** [comment]
谢谢，请问国内有镜像么？直接用pip install akshare --upgrade   更新不了
