### ISSUE TITLE
AKShare 接口问题报告 `fund_etf_hist_em`

### ISSUE THREAD

**Issue by JiangJamm** [akfamily/akshare#4403]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本 Mac OS 14.2.1
2. Python 版本 3.10
3. AKShare 版本 1.12.14
4. 接口的名称和代码 fund_etf_spot_em
5. 接口报错的截图或代码
<img width="2447" alt="image" src="https://github.com/akfamily/akshare/assets/39955422/f12bc7d5-ddec-4a37-b054-d0abf9036842">

7. 期望获得的正确结果
较频繁出现但不是必现的代码报错，调用频率不高（仅调用1次），无法确定是接口问题还是网络问题

**Comment by albertandking** [comment]
> 4\. fund_etf_spot_em

接口测试正常，请排查本地网络问题
