### ISSUE TITLE
AKShare  option_current_em 期权实时行情-东方财富  接口完善 

### ISSUE THREAD

**Issue by cedric-cao** [akfamily/akshare#4404]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本  win11
2. Python 版本  3.10.9
3. AKShare 版本   1.12.16
4. 接口的名称和代码    option_current_em   期权实时行情-东方财富

**说明**
在工作中我需要获取6个期货交易所的期权成交量，经过搜寻和查找发现使用option_current_em这个接口是最方便的
但是发现这个接口只能获取其中四个期货交易所的期权实时行情，缺少广期所和上海国际能源中心  经过查看源代码，发现这里的m是控制获取的交易所

源代码路径：D:\Anaconda\Lib\site-packages\akshare\option\option_em.py
源代码开头：
import pandas as pd
import requests

def option_current_em() -> pd.DataFrame:
    """
    东方财富网-行情中心-期权市场
    https://quote.eastmoney.com/center/qqsc.html
    :return: 期权价格
    :rtype: pandas.DataFrame
    """
    url = 'http://23.push2.eastmoney.com/api/qt/clist/get'
    params = {
        'pn': '1',
        'pz': '200000',
        'po': '1',
        'np': '1',
        'ut': 'bd1d9ddb04089700cf9c27f6f7426281',
        'fltt': '2',
        'invt': '2',
        'fid': 'f3',
        'fs': 'm:10,m:140,m:141,m:151,m:226,m:163',   
        #这里由cedric-cao修改于2024-01-08  11：21   这里的m控制获取的交易所，经过查看东方财富该网页的源代码请求，在源代码基础上另外添加 163：上海能源中心  226：广期所两个交易所 
        'fields': 'f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,f12,f13,f14,f15,f16,f17,f18,f20,f21,f23,f24,f25,f22,f28,f11,f62,f128,f136,f115,f152,f133,f108,f163,f161,f162',
        '_': '1606225274063',
    }

经过查看东方财富该网页的源代码请求，查找了一番后终于被我发现了另外两个交易所的代码，163：上海南国际能源中心   226：广期所
将这两个添加进去后，该接口便可获得全部6个期货交易所的期权实时行情

在此分享，以便有共同需求的同志使用

**Comment by albertandking** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本  win11
> 2. Python 版本  3.10.9
> 3. AKShare 版本   1.12.16
> 4. 接口的名称和代码    option_current_em   期权实时行情-东方财富
> 
> **说明** 在工作中我需要获取6个期货交易所的期权成交量，经过搜寻和查找发现使用option_current_em这个接口是最方便的 但是发现这个接口只能获取其中四个期货交易所的期权实时行情，缺少广期所和上海国际能源中心 经过查看源代码，发现这里的m是控制获取的交易所
> 
> 源代码路径：D:\Anaconda\Lib\site-packages\akshare\option\option_em.py 源代码开头： import pandas as pd import requests
> 
> def option_current_em() -> pd.DataFrame: """ 东方财富网-行情中心-期权市场 https://quote.eastmoney.com/center/qqsc.html :return: 期权价格 :rtype: pandas.DataFrame """ url = 'http://23.push2.eastmoney.com/api/qt/clist/get' params = { 'pn': '1', 'pz': '200000', 'po': '1', 'np': '1', 'ut': 'bd1d9ddb04089700cf9c27f6f7426281', 'fltt': '2', 'invt': '2', 'fid': 'f3', 'fs': 'm:10,m:140,m:141,m:151,m:226,m:163', #这里由cedric-cao修改于2024-01-08 11：21 这里的m控制获取的交易所，经过查看东方财富该网页的源代码请求，在源代码基础上另外添加 163：上海能源中心 226：广期所两个交易所 'fields': 'f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,f12,f13,f14,f15,f16,f17,f18,f20,f21,f23,f24,f25,f22,f28,f11,f62,f128,f136,f115,f152,f133,f108,f163,f161,f162', '_': '1606225274063', }
> 
> 经过查看东方财富该网页的源代码请求，查找了一番后终于被我发现了另外两个交易所的代码，163：上海南国际能源中心 226：广期所 将这两个添加进去后，该接口便可获得全部6个期货交易所的期权实时行情
> 
> 在此分享，以便有共同需求的同志使用

感谢反馈问题，已修复该问题，升级到 AKShare 1.12.17 使用
