### ISSUE TITLE
新增接口请求，请帮忙新增获取沪深两市历史成交额之和的接口

### ISSUE THREAD

**Issue by tianhaisuifeng** [akfamily/akshare#4410]
新增接口请求，新增获取沪深两市历史成交额之和的接口
通过一个接口，可以获取某个时间段沪深历史总成交额数据
当然，也可以单独获取沪市或深市

**Comment by albertandking** [comment]
> 新增接口请求，新增获取沪深两市历史成交额之和的接口 通过一个接口，可以获取某个时间段沪深历史总成交额数据 当然，也可以单独获取沪市或深市

在本地组合使用就可以了

**Comment by tianhaisuifeng** [comment]
这个接口stock_zh_index_daily_em()组合一下可用，多谢！
