### ISSUE TITLE
index_investing_global_from_url()接口报错

### ISSUE THREAD

**Issue by tianhaisuifeng** [akfamily/akshare#4411]
最新版本 ，index_investing_global_from_url()接口报错：
data_text = soup.find("script", attrs={"id": "__NEXT_DATA__"}).text
AttributeError: 'NoneType' object has no attribute 'text'

**Comment by albertandking** [comment]
> 最新版本 ，index_investing_global_from_url()接口报错： data_text = soup.find("script", attrs={"id": "**NEXT_DATA**"}).text AttributeError: 'NoneType' object has no attribute 'text'

看文档说明
