### ISSUE TITLE
筹码计算问题

### ISSUE THREAD

**Issue by ssgmr** [akfamily/akshare#4413]
stock_cyq_em()返回的210条数据中，只有后90条是准确的，前120条数据与东财页面展示的结果相差巨大。
筹码计算是需要依赖历史数据的，
根据对比https://quote.eastmoney.com/concept/sz000001.html
页面中的数据和分析其中的js代码可以发现：页面是根据日k线图最左边的日期，往前多取前120个交易日的数据，共210个交易日的数据参与计算，并只展示后90个交易的筹码分布数据。前120日的计算结果因为缺乏足够的历史数据是不准确的

**Comment by albertandking** [comment]
> stock_cyq_em()返回的210条数据中，只有后90条是准确的，前120条数据与东财页面展示的结果相差巨大。 筹码计算是需要依赖历史数据的， 根据对比https://quote.eastmoney.com/concept/sz000001.html 页面中的数据和分析其中的js代码可以发现：页面是根据日k线图最左边的日期，往前多取前120个交易日的数据，共210个交易日的数据参与计算，并只展示后90个交易的筹码分布数据。前120日的计算结果因为缺乏足够的历史数据是不准确的

感谢反馈问题，目前只保留最新 90 条数据，与网站一致；升级到 AKShare 1.12.21 使用
