### ISSUE TITLE
stock_industry_pe_ratio_cninfo()接口报错

### ISSUE THREAD

**Issue by tianhaisuifeng** [akfamily/akshare#4414]
最新版本，stock_industry_pe_ratio_cninfo()接口报错
line 85, in stock_industry_pe_ratio_cninfo
    temp_df = pd.DataFrame(data_json["records"])
KeyError: 'records'

**Comment by albertandking** [comment]
> 最新版本，stock_industry_pe_ratio_cninfo()接口报错 line 85, in stock_industry_pe_ratio_cninfo temp_df = pd.DataFrame(data_json["records"]) KeyError: 'records'

感谢反馈问题，已修复该问题，升级到 AKShare 1.12.21 使用
