### ISSUE TITLE
stock_average_position_legu()接口报错

### ISSUE THREAD

**Issue by tianhaisuifeng** [akfamily/akshare#4415]
stock_average_position_legu()接口报错：
line 4441, in __delitem__
    loc = self.axes[-1].get_loc(key)
line 3798, in get_loc
    raise KeyError(key) from err
KeyError: 'id'

**Comment by albertandking** [comment]
> stock_average_position_legu()接口报错： line 4441, in **delitem** loc = self.axes[-1].get_loc(key) line 3798, in get_loc raise KeyError(key) from err KeyError: 'id'

感谢反馈问题，已移除该接口，升级到 AKShare 1.12.21 使用
