### ISSUE TITLE
stock_hsgt_stock_statistics_em接口报错

### ISSUE THREAD

**Issue by bingtgo** [akfamily/akshare#4416]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
4. 接口的名称和代码
stock_hsgt_stock_statistics_em
6. 接口报错的截图或代码

~\anaconda3\lib\site-packages\pandas\core\internals\base.py in _validate_set_axis(self, axis, new_labels)
     67 
     68         elif new_len != old_len:
---> 69             raise ValueError(
     70                 f"Length mismatch: Expected axis has {old_len} elements, new "
     71                 f"values have {new_len} elements"

ValueError: Length mismatch: Expected axis has 43 elements, new values have 42 elements

8. 期望获得的正确结果
2024/1/11日报错，1/10正常
登录数据源页面https://data.eastmoney.com/hsgtcg/StockStatistics.html
发现源页面包括“近1、3、5、10、30日”，而接口数据中只有“近1、5、10日”
可能是源页面数据结构更新导致的错误

**Comment by albertandking** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> **描述遇到的问题** 4. 接口的名称和代码 stock_hsgt_stock_statistics_em 6. 接口报错的截图或代码
> 
> ~\anaconda3\lib\site-packages\pandas\core\internals\base.py in _validate_set_axis(self, axis, new_labels) 67 68 elif new_len != old_len: ---> 69 raise ValueError( 70 f"Length mismatch: Expected axis has {old_len} elements, new " 71 f"values have {new_len} elements"
> 
> ValueError: Length mismatch: Expected axis has 43 elements, new values have 42 elements
> 
> 8. 期望获得的正确结果
>    2024/1/11日报错，1/10正常
>    登录数据源页面https://data.eastmoney.com/hsgtcg/StockStatistics.html
>    发现源页面包括“近1、3、5、10、30日”，而接口数据中只有“近1、5、10日”
>    可能是源页面数据结构更新导致的错误

感谢反馈问题，已修复该问题，升级到 AKShare 1.12.21 使用
