### ISSUE TITLE
google_index()接口报错

### ISSUE THREAD

**Issue by tianhaisuifeng** [akfamily/akshare#4417]
最新版本，google_index()接口报错：
line 559, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='trends.google.com', port=443): Max retries exceeded with url: /trends/api/explore?hl=en-US&tz=360&req=%7B%22comparisonItem%22%3A+%5B%7B%22keyword%22%3A+%22bitcoin%22%2C+%22time%22%3A+%222000-01-01+2022-03-03%22%2C+%22geo%22%3A+%22%22%7D%5D%2C+%22category%22%3A+0%2C+%22property%22%3A+%22%22%7D (Caused by ProxyError('Cannot connect to proxy.', TimeoutError('_ssl.c:980: The handshake operation timed out')))
在浏览器中打开：https://trends.google.com/trends/explore?date=now%201-d&geo=TW&q=bitcoin&hl=en
可以正常访问
![image](https://github.com/akfamily/akshare/assets/48590872/867f37f9-9de5-4244-8d61-4b56cb97428d)

**Comment by albertandking** [comment]
> 最新版本，google_index()接口报错： line 559, in send raise ProxyError(e, request=request) requests.exceptions.ProxyError: HTTPSConnectionPool(host='trends.google.com', port=443): Max retries exceeded with url: /trends/api/explore?hl=en-US&tz=360&req=%7B%22comparisonItem%22%3A+%5B%7B%22keyword%22%3A+%22bitcoin%22%2C+%22time%22%3A+%222000-01-01+2022-03-03%22%2C+%22geo%22%3A+%22%22%7D%5D%2C+%22category%22%3A+0%2C+%22property%22%3A+%22%22%7D (Caused by ProxyError('Cannot connect to proxy.', TimeoutError('_ssl.c:980: The handshake operation timed out'))) 在浏览器中打开：https://trends.google.com/trends/explore?date=now%201-d&geo=TW&q=bitcoin&hl=en 可以正常访问 ![image](https://private-user-images.githubusercontent.com/48590872/295799940-867f37f9-9de5-4244-8d61-4b56cb97428d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5Njk5NTUsIm5iZiI6MTcwNDk2OTY1NSwicGF0aCI6Ii80ODU5MDg3Mi8yOTU3OTk5NDAtODY3ZjM3ZjktOWRlNS00MjQ0LThkNjEtNGI1NmNiOTc0MjhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDEwNDA1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2ZjBlMGE1M2RmMTA0YmE0OGMyZmUzOGZkNzU0NzViOTY3NmIxZTljN2FjYTZkNTYwZTMyY2NhNzYwNzUxMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lqGGTUS0Vt6DZLmW0YsopHw9DK-v4eF_JBiuIaK0Ric)

感谢反馈问题，目前已移除该接口，升级到 AKShare 1.12.21 使用
