### ISSUE TITLE
baidu_search_index() 接口问题报错

### ISSUE THREAD

**Issue by tianhaisuifeng** [akfamily/akshare#4418]
最新版本，baidu_search_index() 接口问题报错：
ine 491, in baidu_search_index
    all_data = data["userIndexes"][0]["all"]["data"]
TypeError: string indices must be integers

**Comment by albertandking** [comment]
> 最新版本，baidu_search_index() 接口问题报错： ine 491, in baidu_search_index all_data = data["userIndexes"][0]["all"]["data"] TypeError: string indices must be integers

感谢反馈问题，目前已移除该接口，升级到 AKShare 1.12.21 使用
