### ISSUE TITLE
index_weibo_sina() 接口问题报错

### ISSUE THREAD

**Issue by tianhaisuifeng** [akfamily/akshare#4419]
最新版本，index_weibo_sina() 接口问题报错：
line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by albertandking** [comment]
> 最新版本，index_weibo_sina() 接口问题报错： line 975, in json raise RequestsJSONDecodeError(e.msg, e.doc, e.pos) requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

感谢反馈问题，目前已移除该接口，升级到 AKShare 1.12.21 使用
