### ISSUE TITLE
macro_china_bond_public() 接口报错

### ISSUE THREAD

**Issue by tianhaisuifeng** [akfamily/akshare#4420]
最新版本，macro_china_bond_public() 接口报错：
line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by albertandking** [comment]
> 最新版本，macro_china_bond_public() 接口报错： line 975, in json raise RequestsJSONDecodeError(e.msg, e.doc, e.pos) requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

感谢反馈问题，已修复该接口，升级到 AKShare 1.12.21 使用
