### ISSUE TITLE
index_investing_global_from_url() 接口报错

### ISSUE THREAD

**Issue by tianhaisuifeng** [akfamily/akshare#4421]
最新版本，index_investing_global_from_url() 接口报错：
line 243, in index_investing_global_from_url
    data_text = soup.find("script", attrs={"id": "__NEXT_DATA__"}).text
AttributeError: 'NoneType' object has no attribute 'text'

**Comment by albertandking** [comment]
> 最新版本，index_investing_global_from_url() 接口报错： line 243, in index_investing_global_from_url data_text = soup.find("script", attrs={"id": "**NEXT_DATA**"}).text AttributeError: 'NoneType' object has no attribute 'text'

感谢反馈问题，目前已移除该接口，升级到 AKShare 1.12.21 使用
