### ISSUE TITLE
bond_china_close_return()出现403禁止访问（之前的解决方法失效了）

### ISSUE THREAD

**Issue by lizh0019** [akfamily/akshare#4424]
bond_china_close_return 返回403的问题，20231101有解决方法（https://github.com/akfamily/akshare/issues/4299），
bond_china_money.py 里面也相应更新了代码，但是现在又不好用了继续返回403，session = __bond_register_service()那句话又没有用了，只能手动访问chinamoney网站24小时失效，期望有自动解决的方法。

**Comment by albertandking** [comment]
> bond_china_close_return

目前可以正常使用

**Comment by lizh0019** [comment]
I still have the error:
[image: image.png]

Albert King ***@***.***> 于2024年1月12日周五 16:20写道：

**Comment by lizh0019** [comment]
![akshare_bond](https://github.com/akfamily/akshare/assets/3345809/6c013eb2-53f5-49a3-84ee-c0d735656122)
