### ISSUE TITLE
stock_hsgt_board_rank_em获取数据有误

### ISSUE THREAD

**Issue by congcong009** [akfamily/akshare#4425]
**描述遇到的问题**
1. 操作系统版本 aktools-docker
2. Python 版本 3.10
3. AKShare 版本 latest
4. 接口的名称和代码 stock_hsgt_board_rank_em
5. 接口报错的截图或代码
运行stock_hsgt_board_rank_em("北向资金增持行业板块排行")获取数据，结果如下：
![image](https://github.com/akfamily/akshare/assets/2680017/2e6c40bd-3d77-4ad4-833b-d248bb7c312c)

7. 期望获得的正确结果
对照[数据源](https://data.eastmoney.com/hsgt/index.html#lssj)
![image](https://github.com/akfamily/akshare/assets/2680017/da764f14-b0f8-4f2e-8e66-0adf8b0b426d)
可以看到，最近涨跌幅列的数据抓取出错了

**Comment by congcong009** [comment]
这确实很奇怪了，东财的网页在外面和点进去，结果完全不一样···

**Comment by albertandking** [comment]
> 这确实很奇怪了，东财的网页在外面和点进去，结果完全不一样···

是的

**Comment by congcong009** [comment]
那这就只能是东财的bug了··· >.<
