### ISSUE TITLE
bond_china_close_return()返回403禁止访问

### ISSUE THREAD

**Issue by qiuning79** [akfamily/akshare#4454]
去年11月份修复过这一问题。但上周开始session = __bond_register_service()返回的session登录重新出现返回403问题。
使用浏览器手工访问http://www.chinamoney.com.cn后再调用bond_china_close_return()可短时规避这一问题。
可能是http://www.chinamoney.com.cn的注册机制发生了变化，希望能有更新修复，谢谢！

**Comment by albertandking** [comment]
> 去年11月份修复过这一问题。但上周开始session = __bond_register_service()返回的session登录重新出现返回403问题。 使用浏览器手工访问[http://www.chinamoney.com.cn后再调用bond_china_close_return()可短时规避这一问题。](http://www.chinamoney.com.cn%E5%90%8E%E5%86%8D%E8%B0%83%E7%94%A8bond_china_close_return()%E5%8F%AF%E7%9F%AD%E6%97%B6%E8%A7%84%E9%81%BF%E8%BF%99%E4%B8%80%E9%97%AE%E9%A2%98%E3%80%82) 可能是[http://www.chinamoney.com.cn的注册机制发生了变化，希望能有更新修复，谢谢！](http://www.chinamoney.com.cn%E7%9A%84%E6%B3%A8%E5%86%8C%E6%9C%BA%E5%88%B6%E5%8F%91%E7%94%9F%E4%BA%86%E5%8F%98%E5%8C%96%EF%BC%8C%E5%B8%8C%E6%9C%9B%E8%83%BD%E6%9C%89%E6%9B%B4%E6%96%B0%E4%BF%AE%E5%A4%8D%EF%BC%8C%E8%B0%A2%E8%B0%A2%EF%BC%81)

目前测试正常；升级到最新版试试
