### ISSUE TITLE
bond_china_close_return()接口异常

### ISSUE THREAD

**Issue by LittleWorm1** [akfamily/akshare#4456]
最新版本akshare 1.12.35，运行以下用例：
import akshare as ak
bond_china_close_return_df = ak.bond_china_close_return(symbol="国债", period="1", start_date="20231101", end_date="20231101")
print(bond_china_close_return_df)
显示错误：
发生异常: JSONDecodeError
Expecting value: line 1 column 1 (char 0)
StopIteration: 0
During handling of the above exception, another exception occurred:
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
During handling of the above exception, another exception occurred:
  File "D:\code\python\akshare\bond\bond_china_money.py", line 102, in bond_china_close_return_map
    data_json = r.json()
                ^^^^^^^^
  File "D:\code\python\akshare\bond\bond_china_money.py", line 127, in bond_china_close_return
    name_code_df = bond_china_close_return_map()
单步进去发现第101行session.get(url, headers=headers)网站返回403拒绝访问了。
用浏览器手工访问chinamoney主页后，该接口在数小时内可以使用，返回正常结果，正常使用时间不超过12小时，超出时间限制后故障现象同上。

**Comment by albertandking** [comment]
> 最新版本akshare 1.12.35，运行以下用例： import akshare as ak bond_china_close_return_df = ak.bond_china_close_return(symbol="国债", period="1", start_date="20231101", end_date="20231101") print(bond_china_close_return_df) 显示错误： 发生异常: JSONDecodeError Expecting value: line 1 column 1 (char 0) StopIteration: 0 During handling of the above exception, another exception occurred: json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0) During handling of the above exception, another exception occurred: File "D:\code\python\akshare\bond\bond_china_money.py", line 102, in bond_china_close_return_map data_json = r.json() ^^^^^^^^ File "D:\code\python\akshare\bond\bond_china_money.py", line 127, in bond_china_close_return name_code_df = bond_china_close_return_map() 单步进去发现第101行session.get(url, headers=headers)网站返回403拒绝访问了。 用浏览器手工访问chinamoney主页后，该接口在数小时内可以使用，返回正常结果，正常使用时间不超过12小时，超出时间限制后故障现象同上。

已修复，升级到 AKShare 1.12.36 使用
