### ISSUE TITLE
fund_etf_spot_em 接口无法获取511010的实时数据

### ISSUE THREAD

**Issue by teancake** [akfamily/akshare#4457]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本 macOS Monterey 12.4 (21F79)
2. Python 版本 3.10
3. AKShare 版本 1.12.35
4. 接口的名称和代码 fund_etf_spot_em
```
import akshare as ak
df = ak.fund_etf_spot_em()
df[df["代码"]=="511010"]
```
6. 接口报错的截图或代码
![Screen Shot 2024-01-22 at 10 42 44](https://github.com/akfamily/akshare/assets/15646563/db6de7a6-bba3-4755-9086-c3f1c9a3af8e)

8. 期望获得的正确结果
返回东财网站上 511010 etf的实时数据
https://quote.eastmoney.com/sh511010.html

谢谢～

**Comment by albertandking** [comment]
> 4\. fund_etf_spot_em

以文档数据源为准
