### ISSUE TITLE
使用外币历史数据时候报错

### ISSUE THREAD

**Issue by Franklyn1987** [akfamily/akshare#4461]
**Describe the bug**
获取外币历史数据时候报错，按照akshare文档中的提示获取，有错误

**Screenshots**

![image](https://github.com/akfamily/akshare/assets/20518283/86969c78-4c80-487a-8aa6-2f9536218e18)
![image](https://github.com/akfamily/akshare/assets/20518283/819c6fea-58af-48bc-8101-6834460a2cc1)
![image](https://github.com/akfamily/akshare/assets/20518283/bcb0f6bd-7aea-482c-a2a2-8b8e44ded0b6)

**Comment by albertandking** [comment]
> **Describe the bug** 获取外币历史数据时候报错，按照akshare文档中的提示获取，有错误
> 
> **Screenshots**
> 
> ![image](https://private-user-images.githubusercontent.com/20518283/298792419-86969c78-4c80-487a-8aa6-2f9536218e18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5OTU3NzIsIm5iZiI6MTcwNTk5NTQ3MiwicGF0aCI6Ii8yMDUxODI4My8yOTg3OTI0MTktODY5NjljNzgtNGM4MC00ODdhLThhYTYtMmY5NTM2MjE4ZTE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDA3Mzc1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4ZDZhMGQzZDM2OTg2YjViODYzZWE0MjhjY2M4YTE4NDljNTBjMTQ4NWQ5YzVmYmQyN2UyMWJmMzAyNDY5ZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-0REtC4ZqKlbCA2glVmsz8gMQpaR8ZRDUsGMOiC9kiA) ![image](https://private-user-images.githubusercontent.com/20518283/298792616-819c6fea-58af-48bc-8101-6834460a2cc1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5OTU3NzIsIm5iZiI6MTcwNTk5NTQ3MiwicGF0aCI6Ii8yMDUxODI4My8yOTg3OTI2MTYtODE5YzZmZWEtNThhZi00OGJjLTgxMDEtNjgzNDQ2MGEyY2MxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDA3Mzc1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3MzRiNDc2ZDRlNmVkYzMwYzE2ZTRkMzI5NzFiOWE0YWFiMWQzZmYwOWZlMDFiYjkyN2YxNTY1ZWI1NzlhODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0OswfXHbEg-jVsieremZCE127I4I1wPSKzwT1xDtSB4) ![image](https://private-user-images.githubusercontent.com/20518283/298792645-bcb0f6bd-7aea-482c-a2a2-8b8e44ded0b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5OTU3NzIsIm5iZiI6MTcwNTk5NTQ3MiwicGF0aCI6Ii8yMDUxODI4My8yOTg3OTI2NDUtYmNiMGY2YmQtN2FlYS00ODJjLWEyYTItOGI4ZTQ0ZGVkMGI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDA3Mzc1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxODViOTdiMWQxMmQ3ZDMzODQyNzU2N2M4ZmUzN2Y3YTIxMWMyYzJjMjQzNDgwMjc1NWE1YTljNzMzMzNhZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WHK4cIOdELme7RKPQEp5hUwOl-ZUge8qDzVNWv6rPBs)

参阅文档说明
