### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by KerryElwood** [akfamily/akshare#4466]
python-3.8.13
akshare-1.12.41 

stock_news_em收集个股新闻时候，可以正常工作，但是新闻内容不全。

![0209c9e7eca31a4d9912ecd940a808d](https://github.com/akfamily/akshare/assets/45091293/6e385ee6-9196-432d-afcc-81dbffca2c31)
![5e2a8eeddb8062b181b6d77eb465429](https://github.com/akfamily/akshare/assets/45091293/01de9441-e0be-4df6-877f-86c17c0dd8bc)

**Comment by KerryElwood** [comment]
json文件解析没问题，request得到的url获取的内容信息好像有有点不全
![ae352a6899dfc929c237307b50ac539](https://github.com/akfamily/akshare/assets/45091293/e07d7932-25e0-441b-9a73-7156ef781210)

**Comment by albertandking** [comment]
> python-3.8.13 akshare-1.12.41
> 
> stock_news_em收集个股新闻时候，可以正常工作，但是新闻内容不全。
> 
> ![0209c9e7eca31a4d9912ecd940a808d](https://private-user-images.githubusercontent.com/45091293/299576727-6e385ee6-9196-432d-afcc-81dbffca2c31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNzc5OTYsIm5iZiI6MTcwNjE3NzY5NiwicGF0aCI6Ii80NTA5MTI5My8yOTk1NzY3MjctNmUzODVlZTYtOTE5Ni00MzJkLWFmY2MtODFkYmZmY2EyYzMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDEwMTQ1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjNjAwZjY5NGQxNTc5MzRjN2RhMTliYTM3YzE4MWIzNzViODgwMjZiNzM1YjdmZmZlYTNmNzc5ZWExMzdjMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Dz__kk7JU1MVEviVlKopLKn6FJ14Cs9vKmfGX3Va690) ![5e2a8eeddb8062b181b6d77eb465429](https://private-user-images.githubusercontent.com/45091293/299576769-01de9441-e0be-4df6-877f-86c17c0dd8bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNzc5OTYsIm5iZiI6MTcwNjE3NzY5NiwicGF0aCI6Ii80NTA5MTI5My8yOTk1NzY3NjktMDFkZTk0NDEtZTBiZS00ZGY2LTg3N2YtODZjMTdjMGRkOGJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDEwMTQ1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2MWEyYTVhMTlkY2ZkYTBkMGFjZGFmZmRjZDFiZTY1N2ZjMDg0YjhjNWU0NTk3ODNhM2E1NjA5ZTM2NGQzNjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MFDTG0Opli4oVWu3sdoNcgzJ0zN37KwZ6ye3DL5zad8)

完整内容需要通过 url 后自行获取

**Comment by KerryElwood** [comment]
谢谢
