### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by Zhu-Aemon** [akfamily/akshare#4470]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
macOS，Python 3.9，AKShare是最新版本
报错接口：stock_zh_ah_daily
<img width="613" alt="image" src="https://github.com/akfamily/akshare/assets/63136983/e6fd2914-53f4-45f4-ab42-eeee2713f678">
看了一下，原网页要求必须登录后才能查看行情
不知道有没有办法采用别的网页中的数据或者绕开这个限制
辛苦更新

**Comment by albertandking** [comment]
> stock_zh_ah_daily

接口测试正常，升级到最新版使用
