### ISSUE TITLE
ak.stock_xgsglb_em接口有误

### ISSUE THREAD

**Issue by KeenDuang** [akfamily/akshare#4483]
ak.stock_xgsglb_em接口有误
1. 操作系统版本 win11
2. Python 版本 3.9.13
3. AKShare 版本 1.12.48
4. 接口的名称和代码
ak.stock_xgsglb_em(symbol="全部股票")
5. 接口报错的截图或代码
![image](https://github.com/akfamily/akshare/assets/43028419/a97909ea-8f23-4a86-b1e5-df13755df604)

**Comment by albertandking** [comment]
> 4\. stock_xgsglb_em

目前测试正常，升级到最新版使用
