### ISSUE TITLE
stock_zh_a_hist 月线返回多余的非月底的记录

### ISSUE THREAD

**Issue by wangycol** [akfamily/akshare#4486]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本: windows 10

2. Python 版本: python3.10
 
3. AKShare 版本: 1.11.91
 
4. 接口的名称和代码: stock_zh_a_hist

5. 接口报错的截图或代码: 
symbol = "600000"
period = "monthly"
start_date = "20240101"
end_date = "20240131"
adjust = "bfq"
"exchange","symbol","date","open","close","high","low","volume","amount","amplitude","change_pct","change","turnover_rate"
"SSE","600000","2024-01-31",6.63,6.83,6.97,6.36,9535270,6341026211.0,9.21,3.17,0.21,3.25
"SSE","600000","2024-02-02",6.83,6.84,6.92,6.72,1037353,709575270.0,2.93,0.15,0.01,0.35
不应该返回"2024-02-02"的记录

6. 期望获得的正确结果
只能返回"2024-01-31"的记录

**Comment by albertandking** [comment]
> 5\. 20240101

按文档填入相应参数，注意 adjust 参数

**Comment by wangycol** [comment]
需要计算结束日期是月末。和adjust无关。
