### ISSUE TITLE
请问能否加入爬取分钟级别的A港通数据？

### ISSUE THREAD

**Issue by Zhu-Aemon** [akfamily/akshare#4487]
这是可以从东方财富的网站上获取的，地址是：https://data.eastmoney.com/hsgt/hsgtDetail/scgk.html
分钟级别的A港通数据没有表格，html元素只对应了一个canvas，但是当鼠标移动到对应的位置时会出现分钟级别的数据，并且页面中的html元素随着鼠标的移动会一直变：
![image](https://github.com/akfamily/akshare/assets/63136983/a5194fb5-3325-40ff-93f8-ab80ae20c874)
右边颜色加深的部分就是一直在变的部分
请问这个feature能否做到呢？或者请问大佬愿不愿意给一点爬取这种类型数据的指导？

**Comment by albertandking** [comment]
> 这是可以从东方财富的网站上获取的，地址是：https://data.eastmoney.com/hsgt/hsgtDetail/scgk.html 分钟级别的A港通数据没有表格，html元素只对应了一个canvas，但是当鼠标移动到对应的位置时会出现分钟级别的数据，并且页面中的html元素随着鼠标的移动会一直变： ![image](https://private-user-images.githubusercontent.com/63136983/302179895-a5194fb5-3325-40ff-93f8-ab80ae20c874.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMzUzMzEsIm5iZiI6MTcwNzEzNTAzMSwicGF0aCI6Ii82MzEzNjk4My8zMDIxNzk4OTUtYTUxOTRmYjUtMzMyNS00MGZmLTkzZjgtYWI4MGFlMjBjODc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDEyMTAzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxYzExZjZjOTYzM2VhODg4NzU0ZTdmMzMzYTJiNTAxNTZmMmNmNWZmNmZlYTQ5ZWQzMjQ1YWI4NWRkZjU4OWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aJCjab2_Km2_wXgNhMTj1fV9h83prWqxZMCDm1v3N6I) 右边颜色加深的部分就是一直在变的部分 请问这个feature能否做到呢？或者请问大佬愿不愿意给一点爬取这种类型数据的指导？

已新增 stock_hsgt_fund_min_em 到 AKShare 1.12.51，详情查看文档
