### ISSUE TITLE
stock_gpzy_pledge_ratio_detail_em 这个接口有问题

### ISSUE THREAD

**Issue by wuyulong0931** [akfamily/akshare#4496]
stock_gpzy_pledge_ratio_detail_em 调用这个接口报错了:
ValueError: Length mismatch: Expected axis has 42 elements, new values have 41 elements

**Comment by albertandking** [comment]
> stock_gpzy_pledge_ratio_detail_em 调用这个接口报错了: ValueError: Length mismatch: Expected axis has 42 elements, new values have 41 elements

已修复，升级到 AKShare 1.12.54 使用
