### ISSUE TITLE
stock_individual_spot_xq  接口问题报告

### ISSUE THREAD

**Issue by nyndyhx** [akfamily/akshare#4498]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本:  Windows11

2. Python 版本:  3.10.10

3. AKShare 版本:  1.12.53

4. 接口的名称和代码:  stock_individual_spot_xq

stock_individual_spot_xq?symbol=SH600000
```
{
    "error": "请输入正确的参数错误 'data'，请升级 AKShare 到最新版本并在文档中确认该接口的使用方式：https://www.akshare.xyz"
}
```

stock_individual_spot_xq?symbol=SH600000&timeout=5
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\timeout.py", line 150, in _validate_timeout
    if value <= 0:
TypeError: '<=' not supported between instances of 'str' and 'int'

...

ValueError: Timeout value connect was 5, but it must be an int, float or None.
```

**Comment by albertandking** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本:  Windows11
> 2. Python 版本:  3.10.10
> 3. AKShare 版本:  1.12.53
> 4. 接口的名称和代码:  stock_individual_spot_xq
> 
> stock_individual_spot_xq?symbol=SH600000
> 
> ```
> {
>     "error": "请输入正确的参数错误 'data'，请升级 AKShare 到最新版本并在文档中确认该接口的使用方式：https://www.akshare.xyz"
> }
> ```
> 
> stock_individual_spot_xq?symbol=SH600000&timeout=5
> 
> ```
> ERROR:    Exception in ASGI application
> Traceback (most recent call last):
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\timeout.py", line 150, in _validate_timeout
>     if value <= 0:
> TypeError: '<=' not supported between instances of 'str' and 'int'
> 
> ...
> 
> ValueError: Timeout value connect was 5, but it must be an int, float or None.
> ```

已修复，升级到 AKShare 1.12.54 使用
