### ISSUE TITLE
AKShare 接口问题报告 -- 银保监分局本级行政处罚信息无法获取

### ISSUE THREAD

**Issue by fivedang** [akfamily/akshare#4507]
**描述遇到的问题**
1. 操作系统版本
macOS Sonoma 14.2.1

2. Python 版本
Python 3.11.7

3. AKShare 版本
1.12.56

4. 接口的名称和代码
接口的名称：ak.bank_fjcf_table_detail
代码：
bank_fjcf_table_detail_fjbj_df = ak.bank_fjcf_table_detail(page=1931, item="分局本级")
bank_fjcf_table_detail_bj_df = ak.bank_fjcf_table_detail(page=1621, item="本级")
bank_fjcf_table_detail_jg_df = ak.bank_fjcf_table_detail(page=34, item="机关")

5. 接口报错的截图或代码

---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
File ~/anaconda3/lib/python3.11/site-packages/requests/models.py:971, in Response.json(self, **kwargs)
    970 try:
--> 971     return complexjson.loads(self.text, **kwargs)
    972 except JSONDecodeError as e:
    973     # Catch JSON-related errors and raise as requests.JSONDecodeError
    974     # This aliases json.JSONDecodeError and simplejson.JSONDecodeError

File ~/anaconda3/lib/python3.11/json/__init__.py:346, in loads(s, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    343 if (cls is None and object_hook is None and
    344         parse_int is None and parse_float is None and
    345         parse_constant is None and object_pairs_hook is None and not kw):
--> 346     return _default_decoder.decode(s)
    347 if cls is None:

File ~/anaconda3/lib/python3.11/json/decoder.py:337, in JSONDecoder.decode(self, s, _w)
    333 """Return the Python representation of ``s`` (a ``str`` instance
    334 containing a JSON document).
    335 
    336 """
--> 337 obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    338 end = _w(s, end).end()

File ~/anaconda3/lib/python3.11/json/decoder.py:355, in JSONDecoder.raw_decode(self, s, idx)
    354 except StopIteration as err:
--> 355     raise JSONDecodeError("Expecting value", s, err.value) from None
    356 return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

JSONDecodeError                           Traceback (most recent call last)
Cell In[4], line 1
----> 1 bank_fjcf_table_detail_fjbj_df = ak.bank_fjcf_table_detail(page=1931, item="分局本级")
      2 #bank_fjcf_table_detail_fjbj_df.head()

File ~/anaconda3/lib/python3.11/site-packages/akshare/bank/bank_cbirc_2020.py:123, in bank_fjcf_table_detail(page, item, begin)
    109 def bank_fjcf_table_detail(
    110     page: int = 5, item: str = "分局本级", begin: int = 1
    111 ) -> pd.DataFrame:
    112     """
    113     获取 首页-政务信息-行政处罚-银保监分局本级-XXXX行政处罚信息公开表 数据
    114     :param page: 需要获取前 page 页的内容, 总页数请通过 ak.bank_fjcf_total_page() 获取
   (...)
    121     :rtype: pandas.DataFrame
    122     """
--> 123     id_list = bank_fjcf_page_url(page=page, item=item, begin=begin)["docId"]
    124     big_df = pd.DataFrame()
    125     for item in id_list:

File ~/anaconda3/lib/python3.11/site-packages/akshare/bank/bank_cbirc_2020.py:103, in bank_fjcf_page_url(page, item, begin)
     97     params = {
     98         "itemId": item_id_list[item],
     99         "pageSize": "18",
    100         "pageIndex": str(i_page),
    101     }
    102     res = requests.get(main_url, params=params, headers=cbirc_headers)
--> 103     temp_df = pd.concat([temp_df, pd.DataFrame(res.json()["data"]["rows"])])
    104 return temp_df[
    105     ["docId", "docSubtitle", "publishDate", "docFileUrl", "docTitle", "generaltype"]
    106 ]

File ~/anaconda3/lib/python3.11/site-packages/requests/models.py:975, in Response.json(self, **kwargs)
    971     return complexjson.loads(self.text, **kwargs)
    972 except JSONDecodeError as e:
    973     # Catch JSON-related errors and raise as requests.JSONDecodeError
    974     # This aliases json.JSONDecodeError and simplejson.JSONDecodeError
--> 975     raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

6. 期望获得的正确结果

可以正确获取数据。

**Comment by albertandking** [comment]
> 4\. bank_fjcf_table_detail

目前本接口只能获取近期的数据
