### ISSUE TITLE
无法import akshare，提示No module named 'akqmt'

### ISSUE THREAD

**Issue by tonymouse1997** [akfamily/akshare#4519]
**Describe the bug**
无法import akshare，提示No module named 'akqmt'。

**To Reproduce**
1. 创建conda虚拟环境（3.11和3.12都尝试过）
2. 安装pandas，akshare
3. import akshare as ak

**Expected behavior**
不报错

**Screenshots**
![image](https://github.com/akfamily/akshare/assets/33424320/4c863e9f-6f2c-48de-859a-84ba05e55c7e)

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Version [1.12.63]

**Additional context**
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[2], line 5
      3 import zipfile
      4 from pathlib import Path
----> 5 import akshare as ak

File [~\anaconda3\envs\akshare3.11\Lib\site-packages\akshare\__init__.py:5105](http://localhost:8888/lab/tree/~/anaconda3/envs/akshare3.11/Lib/site-packages/akshare/__init__.py#line=5104)
   5100 from akshare.utils.token_process import set_token, get_token
   5102 """
   5103 AKQMT 设置
   5104 """
-> 5105 from akqmt import xt_api
   5108 if __name__ == '__main__':
   5109     pro = xt_api()

ModuleNotFoundError: No module named 'akqmt'

**Comment by eshion** [comment]
同样的问题
Traceback (most recent call last):
    import akshare as ak
  File "/opt/hostedtoolcache/Python/3.12.2/x64/lib/python3.12/site-packages/akshare/__init__.py", line 5105, in <module>
    from akqmt import xt_api
ModuleNotFoundError: No module named 'akqmt'

**Comment by Franklyn1987** [comment]
是的，windows系统中是遇到了这个问题，怎么解决，我在github上下载了源码也不行

**Comment by kaoiki** [comment]
mac + anaconda + py 3.10.x
也是这个问题
`>>> import akshare
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kaoiki/anaconda3/envs/stock-reborn/lib/python3.10/site-packages/akshare/__init__.py", line 5105, in <module>
    from akqmt import xt_api
ModuleNotFoundError: No module named 'akqmt'`
手动安装akqmt后报如下错
`>>> import akshare
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kaoiki/anaconda3/envs/stock-reborn/lib/python3.10/site-packages/akshare/__init__.py", line 5105, in <module>
    from akqmt import xt_api
  File "/Users/kaoiki/anaconda3/envs/stock-reborn/lib/python3.10/site-packages/akqmt/__init__.py", line 28, in <module>
    from akqmt.pro.data_pro import pro_api as xt_api
  File "/Users/kaoiki/anaconda3/envs/stock-reborn/lib/python3.10/site-packages/akqmt/pro/data_pro.py", line 7, in <module>
    from akqmt.pro import client
  File "/Users/kaoiki/anaconda3/envs/stock-reborn/lib/python3.10/site-packages/akqmt/pro/client.py", line 12, in <module>
    from akqmt.xtquant import xtdatacenter, xtdata
  File "/Users/kaoiki/anaconda3/envs/stock-reborn/lib/python3.10/site-packages/akqmt/xtquant/xtdatacenter.py", line 5, in <module>
    from . import datacenter as __dc
ImportError: cannot import name 'datacenter' from 'akqmt.xtquant' (/Users/kaoiki/anaconda3/envs/stock-reborn/lib/python3.10/site-packages/akqmt/xtquant/__init__.py)`

**Comment by glIrving** [comment]
一样的问题

**Comment by albertandking** [comment]
> **Describe the bug** 无法import akshare，提示No module named 'akqmt'。
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. 创建conda虚拟环境（3.11和3.12都尝试过）
> 2. 安装pandas，akshare
> 3. import akshare as ak
> 
> **Expected behavior** 不报错
> 
> **Screenshots** ![image](https://private-user-images.githubusercontent.com/33424320/306681051-4c863e9f-6f2c-48de-859a-84ba05e55c7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1ODIzNjUsIm5iZiI6MTcwODU4MjA2NSwicGF0aCI6Ii8zMzQyNDMyMC8zMDY2ODEwNTEtNGM4NjNlOWYtNmYyYy00OGRlLTg1OWEtODRiYTA1ZTU1YzdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDA2MDc0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmN2NkNjYxM2JlNTlkM2FjZmJlODBlOTQxNTlhMjc1YzNiOGEyZjFmMWIzNzQ2NWU1MzhiZWFlZGVhN2I3YzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l-VDtmIKmjdieE971cE_-RekT6RLxEEA6qZt5lzPMwo)
> 
> **Desktop (please complete the following information):**
> 
> * OS: [Windows 11]
> * Version [1.12.63]
> 
> **Additional context** ModuleNotFoundError Traceback (most recent call last) Cell In[2], line 5 3 import zipfile 4 from pathlib import Path ----> 5 import akshare as ak
> 
> File [~\anaconda3\envs\akshare3.11\Lib\site-packages\akshare__init__.py:5105](http://localhost:8888/lab/tree/~/anaconda3/envs/akshare3.11/Lib/site-packages/akshare/__init__.py#line=5104) 5100 from akshare.utils.token_process import set_token, get_token 5102 """ 5103 AKQMT 设置 5104 """ -> 5105 from akqmt import xt_api 5108 if **name** == '**main**': 5109 pro = xt_api()
> 
> ModuleNotFoundError: No module named 'akqmt'

已修复该问题，升级到 AKShare 1.12.64 使用
