### ISSUE TITLE
[feature]上期所库存周报历史数据

### ISSUE THREAD

**Issue by edwardsun** [akfamily/akshare#4526]
您好，
请问akshare有计划增加上期所库存的历史数据吗？
https://www.shfe.com.cn/statements/dataview.html?paramid=kx
非常感谢

**Comment by albertandking** [comment]
> 您好， 请问akshare有计划增加上期所库存的历史数据吗？ https://www.shfe.com.cn/statements/dataview.html?paramid=kx 非常感谢

新增 futures_stock_shfe_js 接口，升级到 AKShare 1.12.68 使用
