### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by WeskerC** [akfamily/akshare#4529]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
``` 
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本
Win11

2. Python 版本
Python 3.9

3. AKShare 版本
1.12.69

4. 接口的名称和代码
stock_sina_lhb_detail_daily

5. 接口报错的截图或代码
![image](https://github.com/akfamily/akshare/assets/48875935/57248da7-eaaf-4281-a195-bb7133916a70)

6. 期望获得的正确结果
能获取到数据

非常感谢！

**Comment by JiangJamm** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本
>    Win11
> 2. Python 版本
>    Python 3.9
> 3. AKShare 版本
>    1.12.69
> 4. 接口的名称和代码
>    stock_sina_lhb_detail_daily
> 5. 接口报错的截图或代码
>    ![image](https://private-user-images.githubusercontent.com/48875935/307579255-57248da7-eaaf-4281-a195-bb7133916a70.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5MTkzMTAsIm5iZiI6MTcwODkxOTAxMCwicGF0aCI6Ii80ODg3NTkzNS8zMDc1NzkyNTUtNTcyNDhkYTctZWFhZi00MjgxLWExOTUtYmI3MTMzOTE2YTcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI2VDAzNDMzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyMzdiNzRjNjMxNjQyMmQzMWI1ZmEyM2VmZmZlOTNiY2UwMjYyOGY5NzRmMTU3ZTMxNzZmZGY5M2U3MjJjZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JotsKB1gQvWr4nm5v1M57sll0DLMH_hCyPpeTypLV-k)
> 6. 期望获得的正确结果
>    能获取到数据
> 
> 非常感谢！

接口名为`stock_lhb_detail_daily_sina()`

**Comment by WeskerC** [comment]
> > **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> > ```
> > pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **描述遇到的问题**
> > 
> > 1. 操作系统版本
> >    Win11
> > 2. Python 版本
> >    Python 3.9
> > 3. AKShare 版本
> >    1.12.69
> > 4. 接口的名称和代码
> >    stock_sina_lhb_detail_daily
> > 5. 接口报错的截图或代码
> >    ![image](https://private-user-images.githubusercontent.com/48875935/307579255-57248da7-eaaf-4281-a195-bb7133916a70.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5MTkzMTAsIm5iZiI6MTcwODkxOTAxMCwicGF0aCI6Ii80ODg3NTkzNS8zMDc1NzkyNTUtNTcyNDhkYTctZWFhZi00MjgxLWExOTUtYmI3MTMzOTE2YTcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI2VDAzNDMzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyMzdiNzRjNjMxNjQyMmQzMWI1ZmEyM2VmZmZlOTNiY2UwMjYyOGY5NzRmMTU3ZTMxNzZmZGY5M2U3MjJjZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JotsKB1gQvWr4nm5v1M57sll0DLMH_hCyPpeTypLV-k)
> > 6. 期望获得的正确结果
> >    能获取到数据
> > 
> > 非常感谢！
> 
> 接口名为`stock_lhb_detail_daily_sina()`

好的，麻烦也顺便更改一下https://akshare.akfamily.xyz/tutorial.html上的内容

**Comment by albertandking** [comment]
> > > **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> > > ```
> > > pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > **描述遇到的问题**
> > > 
> > > 1. 操作系统版本
> > >    Win11
> > > 2. Python 版本
> > >    Python 3.9
> > > 3. AKShare 版本
> > >    1.12.69
> > > 4. 接口的名称和代码
> > >    stock_sina_lhb_detail_daily
> > > 5. 接口报错的截图或代码
> > >    ![image](https://private-user-images.githubusercontent.com/48875935/307579255-57248da7-eaaf-4281-a195-bb7133916a70.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5MTkzMTAsIm5iZiI6MTcwODkxOTAxMCwicGF0aCI6Ii80ODg3NTkzNS8zMDc1NzkyNTUtNTcyNDhkYTctZWFhZi00MjgxLWExOTUtYmI3MTMzOTE2YTcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI2VDAzNDMzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyMzdiNzRjNjMxNjQyMmQzMWI1ZmEyM2VmZmZlOTNiY2UwMjYyOGY5NzRmMTU3ZTMxNzZmZGY5M2U3MjJjZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JotsKB1gQvWr4nm5v1M57sll0DLMH_hCyPpeTypLV-k)
> > > 6. 期望获得的正确结果
> > >    能获取到数据
> > > 
> > > 非常感谢！
> > 
> > 
> > 接口名为`stock_lhb_detail_daily_sina()`
> 
> 好的，麻烦也顺便更改一下[https://akshare.akfamily.xyz/tutorial.html上的内容](https://akshare.akfamily.xyz/tutorial.html%E4%B8%8A%E7%9A%84%E5%86%85%E5%AE%B9)

已修复
