### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by Nevernamed** [akfamily/akshare#4534]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 系统: MacOS 
2. Python 版本: 3.10.8
3. AKShare 版本: 1.12.70
4. 接口的名称和代码: stock_zh_ah_spot
5. 接口报错的截图或代码: 接口描述中是单次返回所有 A+H 上市公司的实时行情数据, 实际只返回149条数据
6. 期望获得的正确结果: 返回全部A+H上市公司的实时数据

**Comment by albertandking** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> **描述遇到的问题**
> 
> 1. 系统: MacOS
> 2. Python 版本: 3.10.8
> 3. AKShare 版本: 1.12.70
> 4. 接口的名称和代码: stock_zh_ah_spot
> 5. 接口报错的截图或代码: 接口描述中是单次返回所有 A+H 上市公司的实时行情数据, 实际只返回149条数据
> 6. 期望获得的正确结果: 返回全部A+H上市公司的实时数据

感谢反馈问题，已修复该问题，升级到 AKShare 1.12.71 使用
