### ISSUE TITLE
[feature] futures contract details

### ISSUE THREAD

**Issue by edwardsun** [akfamily/akshare#4536]
您好，
请问akshare有计划增加期货合约的详细信息吗？包括历史交割日，最后交易日等。
上期所：https://www.shfe.com.cn/bourseService/businessdata/summaryinquiry/
大商所：http://www.dce.com.cn/dalianshangpin/ywfw/ywcs/jycs/hyxxcx/index.html
郑商所：http://www.czce.com.cn/cn/jysj/cksj/H770322index_1.htm
广期所：http://www.gfex.com.cn/gfex/hyxx/ywcs.shtml
中金所：http://www.cffex.com.cn/jycs/
感谢

**Comment by albertandking** [comment]
> 您好， 请问akshare有计划增加期货合约的详细信息吗？包括历史交割日，最后交易日等。 上期所：https://www.shfe.com.cn/bourseService/businessdata/summaryinquiry/ 大商所：http://www.dce.com.cn/dalianshangpin/ywfw/ywcs/jycs/hyxxcx/index.html 郑商所：http://www.czce.com.cn/cn/jysj/cksj/H770322index_1.htm 广期所：http://www.gfex.com.cn/gfex/hyxx/ywcs.shtml 中金所：http://www.cffex.com.cn/jycs/ 感谢

升级到 AKShare 1.12.74 使用，
1. 新增 futures_contract_info_shfe 接口
2. 新增 futures_contract_info_dce 接口
3. 新增 futures_contract_info_czce 接口
4. 新增 futures_contract_info_gfex 接口
5. 新增 futures_contract_info_cffex 接口
