### ISSUE TITLE
INE futures contract details

### ISSUE THREAD

**Issue by weebffkorkp22** [akfamily/akshare#4540]
您好，合约详情数据能否添加 INE [https://www.ine.cn/bourseService/summary/?name=currinstrumentprop](上海国际能源交易中心)

**Comment by albertandking** [comment]
> 您好，合约详情数据能否添加 INE [https://www.ine.cn/bourseService/summary/?name=currinstrumentprop](%E4%B8%8A%E6%B5%B7%E5%9B%BD%E9%99%85%E8%83%BD%E6%BA%90%E4%BA%A4%E6%98%93%E4%B8%AD%E5%BF%83)

已新增 futures_contract_info_ine 接口，升级到 AKShare 1.12.75 使用
