### ISSUE TITLE
[bug] futures_contract_info_shfe

### ISSUE THREAD

**Issue by edwardsun** [akfamily/akshare#4547]
您好，

futures_contract_info_shfe这个函数好像没有在request里加headers,这样导致了connection closed prematurely错误。加入headers=headers应该可以修复

**Comment by albertandking** [comment]
> 您好，
> 
> futures_contract_info_shfe这个函数好像没有在request里加headers,这样导致了connection closed prematurely错误。加入headers=headers应该可以修复

感谢反馈问题，已修复该问题，升级到 AKShare 1.12.77 使用
