### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by wanghc02** [akfamily/akshare#4561]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本  
Windows 10
2. Python 版本
Python 3.10
3. AKShare 版本
1.12.79
4. 接口的名称和代码
ak.get_futures_daily('20240301','20240301','czce')
5. 接口报错的截图或代码
![1709311293373](https://github.com/akfamily/akshare/assets/24860097/f38afaff-37a6-4575-a931-736c8042dbfc)
5. 期望获得的正确结果
3月1日的郑商所日线数据

**Comment by wanghc02** [comment]
经测试，直接get郑商所的url报502错误，加上headers={"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"}，可正常获取数据

**Comment by albertandking** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本
>    Windows 10
> 2. Python 版本
>    Python 3.10
> 3. AKShare 版本
>    1.12.79
> 4. 接口的名称和代码
>    ak.get_futures_daily('20240301','20240301','czce')
> 5. 接口报错的截图或代码
>    ![1709311293373](https://private-user-images.githubusercontent.com/24860097/309328090-f38afaff-37a6-4575-a931-736c8042dbfc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzNzA5MzcsIm5iZiI6MTcwOTM3MDYzNywicGF0aCI6Ii8yNDg2MDA5Ny8zMDkzMjgwOTAtZjM4YWZhZmYtMzdhNi00NTc1LWE5MzEtNzM2YzgwNDJkYmZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAyVDA5MTAzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4MzgwNzI1YTEwYjQxYzk2ZTBjNDI1Njk0MDQ5Yjk1Yjk4M2ZkNWMxNTI2ZDg2YjZjMzUzNzg4MzhkYWFiMTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GlYXcELekaOpA12HbsYJcm8tYE0BBvdYZMLygowxln8)
> 6. 期望获得的正确结果
>    3月1日的郑商所日线数据

感谢反馈问题及解决方案，已修复该问题，升级到 AKShare 1.12.80 使用
