### ISSUE TITLE
上证指数，没有2024之前的分钟级别历史数据，希望能获取到

### ISSUE THREAD

**Issue by moyu2008** [akfamily/akshare#4562]
index_zh_a_hist_min_em_df = ak.index_zh_a_hist_min_em(symbol="000001", period="5", start_date="2023-03-01 09:30:00", end_date="2023-12-01 19:00:00")
print(index_zh_a_hist_min_em_df)

希望能获取到上证指数2024之前的分钟级别历史数据

**Comment by albertandking** [comment]
> index_zh_a_hist_min_em

按文档说明使用，暂无历史数据
