### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by edwardsun** [akfamily/akshare#4565]
**Describe the bug**
futures_contract_info_czce函数有时候正常有时候出错。比如
正常：ak.futures_contract_info_czce(date='20230306')
出错：ak.futures_contract_info_czce(date='20240216')

期待修复

**Comment by albertandking** [comment]
> **Describe the bug** futures_contract_info_czce函数有时候正常有时候出错。比如 正常：ak.futures_contract_info_czce(date='20230306') 出错：ak.futures_contract_info_czce(date='20240216')
> 
> 期待修复

接口正常，是数据源的问题
