### ISSUE TITLE
AKShare 接口问题报告-stock_tfp_em和news_trade_notify_suspend_baidu

### ISSUE THREAD

**Issue by huangyongde** [akfamily/akshare#4568]
已经更新到最新的版本
pip list |grep akshare
akshare            1.12.81

**描述遇到的问题**
1. mac 
2.python 3.12.1
3. AKShare 版本1.12.81
4. 接口的名称和代码
import akshare as ak
stock_tfp_em_df = ak.stock_tfp_em(date="20220523")
print(stock_tfp_em_df)
news_trade_notify_suspend_baidu_df = ak.news_trade_notify_suspend_baidu(date="20220523")
print(news_trade_notify_suspend_baidu_df)
6. 接口报错的截图或代码

      序号      代码     名称        停牌时间      停牌截止时间  停牌期限       停牌原因      所属市场      预计复牌时间
0      1  603069   海汽集团  2024-02-28  2024-03-05  连续停牌     刊登重要公告     上交所主板  2024-03-06
1      2  002822   ST中装  2024-02-26  2024-02-26  停牌一天     刊登重要公告  深交所风险警示板  2024-02-27
2      3  002873   新天药业  2024-02-23  2024-03-07  连续停牌  拟筹划重大资产重组     深交所主板  2024-03-08
3      4  002089  *ST新海  2024-02-06         NaT  连续停牌     刊登重要公告  深交所风险警示板         NaT
4      5  301502   华阳智能  2024-02-06  2024-02-06  盘中停牌     交易异常波动    深交所创业板         NaT
..   ...     ...    ...         ...         ...   ...        ...       ...         ...
495  496  603052   可川科技  2022-10-11  2022-10-11  盘中停牌     交易异常波动     上交所主板         NaT
496  497  601515   东风股份  2022-10-11  2022-10-18  连续停牌     刊登重要公告     上交所主板  2022-10-19
497  498  603021   山东华鹏  2022-10-10  2022-10-21  连续停牌  拟筹划重大资产重组     上交所主板  2022-10-24
498  499  001255   博菲电气  2022-09-30  2022-09-30  盘中停牌     交易异常波动     深交所主板         NaT
499  500  002716   金贵银业  2022-09-30  2022-10-20  连续停牌  拟筹划重大资产重组     深交所主板  2022-10-21

[500 rows x 9 columns]

Empty DataFrame
Columns: []
Index: []
8. 期望获得的正确结果
ak.stock_tfp_em和ak.news_trade_notify_suspend_baidu可以返回指定日期的两市停复牌数据

**Comment by albertandking** [comment]
> 已经更新到最新的版本 pip list |grep akshare akshare 1.12.81
> 
> **描述遇到的问题**
> 
> 1. mac
>    2.python 3.12.1
> 2. AKShare 版本1.12.81
> 3. 接口的名称和代码
>    import akshare as ak
>    stock_tfp_em_df = ak.stock_tfp_em(date="20220523")
>    print(stock_tfp_em_df)
>    news_trade_notify_suspend_baidu_df = ak.news_trade_notify_suspend_baidu(date="20220523")
>    print(news_trade_notify_suspend_baidu_df)
> 4. 接口报错的截图或代码
>    序号      代码     名称        停牌时间      停牌截止时间  停牌期限       停牌原因      所属市场      预计复牌时间
>    0      1  603069   海汽集团  2024-02-28  2024-03-05  连续停牌     刊登重要公告     上交所主板  2024-03-06
>    1      2  002822   ST中装  2024-02-26  2024-02-26  停牌一天     刊登重要公告  深交所风险警示板  2024-02-27
>    2      3  002873   新天药业  2024-02-23  2024-03-07  连续停牌  拟筹划重大资产重组     深交所主板  2024-03-08
>    3      4  002089  *ST新海  2024-02-06         NaT  连续停牌     刊登重要公告  深交所风险警示板         NaT
>    4      5  301502   华阳智能  2024-02-06  2024-02-06  盘中停牌     交易异常波动    深交所创业板         NaT
>    ..   ...     ...    ...         ...         ...   ...        ...       ...         ...
>    495  496  603052   可川科技  2022-10-11  2022-10-11  盘中停牌     交易异常波动     上交所主板         NaT
>    496  497  601515   东风股份  2022-10-11  2022-10-18  连续停牌     刊登重要公告     上交所主板  2022-10-19
>    497  498  603021   山东华鹏  2022-10-10  2022-10-21  连续停牌  拟筹划重大资产重组     上交所主板  2022-10-24
>    498  499  001255   博菲电气  2022-09-30  2022-09-30  盘中停牌     交易异常波动     深交所主板         NaT
>    499  500  002716   金贵银业  2022-09-30  2022-10-20  连续停牌  拟筹划重大资产重组     深交所主板  2022-10-21
> 
> [500 rows x 9 columns]
> 
> Empty DataFrame Columns: [] Index: [] 8. 期望获得的正确结果 ak.stock_tfp_em和ak.news_trade_notify_suspend_baidu可以返回指定日期的两市停复牌数据

目前 news_trade_notify_suspend_baidu 接口正常
