### ISSUE TITLE
美股财报接口

### ISSUE THREAD

**Issue by aiot-tech** [akfamily/akshare#4570]
你好，请问ak后续有增加美股财报接口的计划不？

**Comment by albertandking** [comment]
> 你好，请问ak后续有增加美股财报接口的计划不？

有合适的数据源会增加

**Comment by aiot-tech** [comment]
自己实现了一个
```
def _get_earnings():
    target_date = (datetime.datetime.now()).strftime("%Y-%m-%d")
    url = f"https://finance.yahoo.com/calendar/earnings?day={target_date}"
    headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:120.0) Gecko/20100101 Firefox/120.0"}
    response = requests.get(url, headers=headers)
    soup = BeautifulSoup(response.content, "html.parser")
    results = soup.find(id="cal-res-table")
    job_elements = results.find_all("tr", class_="simpTblRow")
    earning_list = []
    for element in job_elements:
        td_elements = element.find_all("td")
        symbol = td_elements[0].text
        company_name = td_elements[1].text
        event_name = td_elements[2].text
        earnings_call_time = td_elements[3].text
        eps_estimate = td_elements[4].text
        reported_eps = td_elements[5].text
        surprise = td_elements[6].text
        earning_list.append({"symbol": symbol,
                             "company_name": company_name,
                             "event_name": event_name,
                             "earnings_call_time": earnings_call_time,
                             "eps_estimate": eps_estimate,
                             "reported_eps": reported_eps,
                             "surprise": surprise, })
    df = pd.DataFrame.from_records(earning_list)
    df = df[df["earnings_call_time"] != "TAS"]
    return df
```

**Comment by albertandking** [comment]
> 自己实现了一个
> 
> ```
> def _get_earnings():
>     target_date = (datetime.datetime.now()).strftime("%Y-%m-%d")
>     url = f"https://finance.yahoo.com/calendar/earnings?day={target_date}"
>     headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:120.0) Gecko/20100101 Firefox/120.0"}
>     response = requests.get(url, headers=headers)
>     soup = BeautifulSoup(response.content, "html.parser")
>     results = soup.find(id="cal-res-table")
>     job_elements = results.find_all("tr", class_="simpTblRow")
>     earning_list = []
>     for element in job_elements:
>         td_elements = element.find_all("td")
>         symbol = td_elements[0].text
>         company_name = td_elements[1].text
>         event_name = td_elements[2].text
>         earnings_call_time = td_elements[3].text
>         eps_estimate = td_elements[4].text
>         reported_eps = td_elements[5].text
>         surprise = td_elements[6].text
>         earning_list.append({"symbol": symbol,
>                              "company_name": company_name,
>                              "event_name": event_name,
>                              "earnings_call_time": earnings_call_time,
>                              "eps_estimate": eps_estimate,
>                              "reported_eps": reported_eps,
>                              "surprise": surprise, })
>     df = pd.DataFrame.from_records(earning_list)
>     df = df[df["earnings_call_time"] != "TAS"]
>     return df
> ```

国内无法访问雅虎金融，暂不考虑该数据源
