### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by EnergeticMrMask** [akfamily/akshare#4572]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本:windows11
2. Python 版本:3.11.8
3. AKShare 版本:1.12.82
4. 接口的名称和代码:stock_info_a_code_name_df = ak.stock_info_a_code_name()
5. 接口报错的截图或代码:HTTPSConnectionPool(host='query.sse.com.cn', port=443): Max retries exceeded with url:/sseQuery/commonQuery.doSTOCK_TYPE=1&REG_PROVINCE=&CSRC_CODE=&STOCK_CODE=&sqlId=COMMON_SSE_CP_GPJCTPZ_GPLB_GP_L&COMPANY_STATUS=2%2C4%2C5%2C7%2C8&type=inParams&isPagination=true&pageHelp.cacheSize=1&pageHelp.beginPage=1&pageHelp.pageSize=10000&pageHelp.pageNo=1&pageHelp.endPage=1&_=1653291270045 (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)'))) 
6. 初步调查原因是引用的stock_info_sh_name_code有问题

**Comment by albertandking** [comment]
> 6\. stock_info_sh_name_code

接口测试正常

**Comment by EnergeticMrMask** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
