### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by idontknoowww** [akfamily/akshare#4575]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本 win10 64位
2. Python 版本  3.11.7
3. AKShare 版本 1.12.82
4. 接口的名称和代码  `stock_individual_spot_xq_df = ak.stock_individual_spot_xq(symbol="SH600118")
print(stock_individual_spot_xq_df.dtypes)`
5. 接口报错的截图或代码 `Traceback (most recent call last):
  File "D:\stock_test\stock\views\test.py", line 35, in <module>
    stock_individual_spot_xq_df = ak.stock_individual_spot_xq(symbol="SH600118")
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\L3m0k3\anaconda3\Lib\site-packages\akshare\stock\stock_xq.py", line 80, in stock_individual_spot_xq
    json_data = r.json()["data"]["quote"]
                ~~~~~~~~^^^^^^^^
KeyError: 'data'
`
6. 期望获得的正确结果
看起来雪球系列又炸了？

**Comment by albertandking** [comment]
> 4\. stock_individual_spot_xq

已修复该问题，升级到 AKShare 1.12.83 使用
