### ISSUE TITLE
stock_intraday_em 在 9：00 ~9:15之间调用会报错

### ISSUE THREAD

**Issue by liyqxtu** [akfamily/akshare#4577]
df = ak.stock_intraday_em(symbol=code)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\akshare\stock\stock_intraday_em.py", line 136, in stock_intraday_em
    big_df.columns = ["时间", "成交价", "手数", "-", "买卖盘性质"]
    ^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\pandas\core\generic.py", line 6310, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "C:\Python311\Lib\site-packages\pandas\core\generic.py", line 813, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "C:\Python311\Lib\site-packages\pandas\core\internals\managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "C:\Python311\Lib\site-packages\pandas\core\internals\base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 5 elements

Process finished with exit code 1

**Comment by albertandking** [comment]
> ```
> df = ak.stock_intraday_em(symbol=code)
>      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> ```
> 
> File "C:\Python311\Lib\site-packages\akshare\stock\stock_intraday_em.py", line 136, in stock_intraday_em big_df.columns = ["时间", "成交价", "手数", "-", "买卖盘性质"] ^^^^^^^^^^^^^^ File "C:\Python311\Lib\site-packages\pandas\core\generic.py", line 6310, in **setattr** return object.**setattr**(self, name, value) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.**set** File "C:\Python311\Lib\site-packages\pandas\core\generic.py", line 813, in _set_axis self._mgr.set_axis(axis, labels) File "C:\Python311\Lib\site-packages\pandas\core\internals\managers.py", line 238, in set_axis self._validate_set_axis(axis, new_labels) File "C:\Python311\Lib\site-packages\pandas\core\internals\base.py", line 98, in _validate_set_axis raise ValueError( ValueError: Length mismatch: Expected axis has 0 elements, new values have 5 elements
> 
> Process finished with exit code 1

9：00 ~9:15 为什么会有数据？

**Comment by liyqxtu** [comment]
没数据接口也不应该报错呀，直接返回空也行呀
