### ISSUE TITLE
希望提供期货交割日，期权交割日，富时A50期货交割日等一系列特殊日期的接口

### ISSUE THREAD

**Issue by liyqxtu** [akfamily/akshare#4579]
1、希望提供期货交割日，期权交割日，富时A50期货交割日等一系列特殊日期的接口
2、希望提供每月公布CPI，PPI以及美国每月公布CPI，PPI等一系列特殊日期的接口
3、希望提供美国加息会议日期的接口
4、希望提供获取过去第n个交易日的接口
今天是3月9日，过去第0个交易日就是3月8日，过去第1个交易日就是3月7日
今天是3月10日，过去第0个交易日是3月8日，过去第1个交易日就是3月7日
今天是3月11日，过去第0个交易日是3月11日，过去第1个交易日就是3月8日

**Comment by albertandking** [comment]
> 1、希望提供期货交割日，期权交割日，富时A50期货交割日等一系列特殊日期的接口 2、希望提供每月公布CPI，PPI以及美国每月公布CPI，PPI等一系列特殊日期的接口 3、希望提供美国加息会议日期的接口 4、希望提供获取过去第n个交易日的接口 今天是3月9日，过去第0个交易日就是3月8日，过去第1个交易日就是3月7日 今天是3月10日，过去第0个交易日是3月8日，过去第1个交易日就是3月7日 今天是3月11日，过去第0个交易日是3月11日，过去第1个交易日就是3月8日

有机会可以提供
