### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by wwwcisco** [akfamily/akshare#4581]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本 debian 12
2. Python 版本 3.10
3. AKShare 版本 1.12.82
4. 接口的名称和代码  stock_zh_a_hist
5. 接口报错的截图或代码
    多进程或异步取全量数据时，提示 An error occurred: HTTPConnectionPool(host='push2his.eastmoney.com', port=80): Max retries exceeded with url: /api/qt/stock/kline/ ，已经每次取个股后暂停 5秒了。是否这个接口有总量限制每天取的次数。
另外 是否有 接口 可以按 日期/每天，取 当天的所有个股行情数据，类似tushare pro.daily(trade='date')
7. 期望获得的正确结果
    因为需要导入本地数据，需要取一次全量数据，后期每天更新数据。

**Comment by albertandking** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本 debian 12
> 2. Python 版本 3.10
> 3. AKShare 版本 1.12.82
> 4. 接口的名称和代码  stock_zh_a_hist
> 5. 接口报错的截图或代码
>    多进程或异步取全量数据时，提示 An error occurred: HTTPConnectionPool(host='push2his.eastmoney.com', port=80): Max retries exceeded with url: /api/qt/stock/kline/ ，已经每次取个股后暂停 5秒了。是否这个接口有总量限制每天取的次数。
>    另外 是否有 接口 可以按 日期/每天，取 当天的所有个股行情数据，类似tushare pro.daily(trade='date')
> 6. 期望获得的正确结果
>    因为需要导入本地数据，需要取一次全量数据，后期每天更新数据。

目前接口可以正常使用，不建议用多进程或者异步

**Comment by sourgelp** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本 debian 12
> 2. Python 版本 3.10
> 3. AKShare 版本 1.12.82
> 4. 接口的名称和代码  stock_zh_a_hist
> 5. 接口报错的截图或代码
>    多进程或异步取全量数据时，提示 An error occurred: HTTPConnectionPool(host='push2his.eastmoney.com', port=80): Max retries exceeded with url: /api/qt/stock/kline/ ，已经每次取个股后暂停 5秒了。是否这个接口有总量限制每天取的次数。
>    另外 是否有 接口 可以按 日期/每天，取 当天的所有个股行情数据，类似tushare pro.daily(trade='date')
> 6. 期望获得的正确结果
>    因为需要导入本地数据，需要取一次全量数据，后期每天更新数据。

我和你有相同需求，也是遇到了这个问题，time.sleep(5)配置了没有用，感觉网站对于每天的总次数有限制，次数超过了IP会被封掉，过2天又可以使用，但是现在不晓得这个总次数是好多

**Comment by wwwcisco** [comment]
是的，感觉有总数限制，特别是在调试阶段需要反复调试的情况。后面修订了，感觉是只有不超过7个进程取，每次休息0.01都行了，你可以试试


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "akfamily/akshare"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月30日(星期二) 下午2:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [akfamily/akshare] AKShare 接口问题报告 (Issue #4581)





  
遇到任何问题，请先确认您的 AKShare 版本是最新的
 pip install akshare --upgrade  # Python 版本需要大于等于 3.8  
描述遇到的问题
  
操作系统版本 debian 12
 
Python 版本 3.10
 
AKShare 版本 1.12.82
 
接口的名称和代码  stock_zh_a_hist
 
接口报错的截图或代码
 多进程或异步取全量数据时，提示 An error occurred: HTTPConnectionPool(host='push2his.eastmoney.com', port=80): Max retries exceeded with url: /api/qt/stock/kline/ ，已经每次取个股后暂停 5秒了。是否这个接口有总量限制每天取的次数。
 另外 是否有 接口 可以按 日期/每天，取 当天的所有个股行情数据，类似tushare pro.daily(trade='date')
 
期望获得的正确结果
 因为需要导入本地数据，需要取一次全量数据，后期每天更新数据。
   
我和你有相同需求，也是遇到了这个问题，time.sleep(5)配置了没有用，感觉网站对于每天的总次数有限制，次数超过了IP会被封掉，过2天又可以使用，但是现在不晓得这个总次数是好多
