### ISSUE TITLE
希望添加当日东方财富财经早餐获取接口

### ISSUE THREAD

**Issue by lem0ke** [akfamily/akshare#4595]
经过观察，发现获取当日东财财经早餐链接数据的链接如下：https://np-listapi.eastmoney.com/comm/web/getNewsByColumns?client=web&biz=web_news_col&column=1207&order=1&needInteractData=0&page_index=1&page_size=20&req_trace=1710226498580&fields=code,showTime,title,mediaName,summary,image,url,uniqueUrl,Np_dst&types=1,20

进入详情界面，可发现具体新闻内容在id="ContentBody"的div下。

**Comment by lem0ke** [comment]
另：如有机会，希望可以进一步完善资讯数据-电报中的服务，如东方财富：https://kuaixun.eastmoney.com/  ；新浪财经：https://finance.sina.com.cn/7x24/  ；同花顺：https://news.10jqka.com.cn/realtimenews.html ；富途牛牛：https://news.futunn.com/main/live?lang=zh-cn

**Comment by albertandking** [comment]
已新增相关接口，升级到 AKShare 1.12.91 使用，接口见文档 stock_info_global_em

**Comment by lem0ke** [comment]
🐂
