### ISSUE TITLE
希望提供实时内外盘等数据

### ISSUE THREAD

**Issue by liyqxtu** [akfamily/akshare#4608]
http://quote.eastmoney.com/sh600560.html
右侧的“行情报价”中有内外盘数据

**Comment by albertandking** [comment]
> http://quote.eastmoney.com/sh600560.html 右侧的“行情报价”中有内外盘数据

已经提供相关接口

**Comment by liyqxtu** [comment]
> > http://quote.eastmoney.com/sh600560.html 右侧的“行情报价”中有内外盘数据
> 
> 已经提供相关接口

具体是哪一个接口呀？
![1](https://github.com/akfamily/akshare/assets/4734699/cb8555db-7a4a-4006-a34c-8610725d244d)
