### ISSUE TITLE
AttributeError: 'DataFrame' object has no attribute 'map'.

### ISSUE THREAD

**Issue by l497311987** [akfamily/akshare#4613]
**Describe the bug**
df = ak.stock_zh_index_spot_sina()
stock_zh_index_spot_sina  method uses map instead of applymap, withc causes the error
_index_stock_zh.py  line 73_

**Expected behavior**
replace map method to applymap
big_df = big_df.map(_replace_comma)  => big_df = big_df.applymap(_replace_comma)

**Comment by albertandking** [comment]
> stock_zh_index_spot_sina

升级到 Pandas 2 以上版本使用
