### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by carusyte** [akfamily/akshare#4616]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本:  macOS Monterey v12.7.4
2. Python 版本: 3.12.2
3. AKShare 版本: v1.12.92
4. 接口的名称和代码: fund_etf_spot_em()
5. 接口报错的截图或代码: 
该接口返回 884 条ETF 记录，部分交易所可以交易的ETF没有返回。参考另一个API：fund_exchange_rank_em() 可以返回 892 条ETF记录。
6. 期望获得的正确结果

尝试调整eastmoney API 参数，暂时无果。以下为截止到今天比对发现不一致的记录：
 
**rank包含，spot不包含：**

序号 | 基金代码 | 基金简称 | 类型
-- | -- | -- | --
27 | 159834 | 金ETF | 指数型-股票
30 | 159831 | 嘉实上海金ETF | 指数型-其他
32 | 159812 | 前海开源黄金ETF | 指数型-其他
36 | 159830 | 天弘上海金ETF | 指数型-其他
49 | 159985 | 华夏饲料豆粕期货ETF | 指数型-其他
73 | 511520 | 富国中债7-10年政策性金融债ETF | 指数型-固收
81 | 159981 | 建信易盛能源化工期货ETF | 指数型-其他
83 | 511270 | 海富通上证10年期ETF | 指数型-固收
84 | 511260 | 国泰上证10年期国债ETF | 指数型-固收
86 | 511020 | 平安中证5-10年国债活跃券ETF | 指数型-固收
89 | 511220 | 海富通上证城投债ETF | 指数型-固收
90 | 159972 | 鹏华中证5年地债ETF | 指数型-固收
93 | 511580 | 招商中证政策性金融债3-5年ETF | 指数型-固收
94 | 159980 | 大成有色金属期货ETF | 指数型-其他
96 | 511060 | 海富通上证5年期ETF | 指数型-固收
98 | 511010 | 国泰上证5年期国债ETF | 指数型-固收
99 | 159816 | 鹏华0-4年地方政府债ETF | 指数型-固收
100 | 159649 | 华安中债1-5年国开债ETF | 指数型-固收
102 | 511030 | 平安中债债利差因子ETF | 指数型-固收
103 | 159650 | 博时中债0-3年国开行ETF | 指数型-固收
104 | 159651 | 平安中债-0-3年国开行债券ETF | 指数型-固收
105 | 511360 | 海富通中证短融ETF | 指数型-固收
120 | 511180 | 海富通上证投资级可转债ETF | 指数型-固收
169 | 511380 | 博时可转债ETF | 指数型-固收
734 | 511090 | 鹏扬中债-30年期国债ETF | 指数型-固收
871 | 511100 | 华夏上证基准做市国债ETF | 指数型-固收
880 | 563080 | 易方达中证A50ETF | 指数型-股票
881 | 159589 | 广发中证红利ETF | 指数型-股票
882 | 561230 | 工银瑞信中证A50ETF | 指数型-股票
883 | 159592 | 银华中证A50ETF | 指数型-股票
885 | 159581 | 万家中证红利ETF | 指数型-股票
886 | 563350 | 华泰柏瑞中证A50ETF | 指数型-股票
887 | 562890 | 嘉实中证A50ETF | 指数型-股票
888 | 159586 | 南方中证全指计算机ETF | 指数型-股票
889 | 159591 | 富国中证A50ETF | 指数型-股票
890 | 159595 | 大成中证A50ETF | 指数型-股票
892 | 159596 | 华宝中证A50ETF | 指数型-股票

**spot包含，rank不包含：**

代码 | 名称
-- | --
511830 | 华泰货币ETF
511920 | 广发货币ETF
511700 | 场内货币ETF
511800 | 易方达货币ETF
511880 | 银华日利ETF
511660 | 货币ETF建信添益
511620 | 货币基金ETF
511990 | 华宝添益ETF
511850 | 财富宝ETF
511600 | 货币ETF
511690 | 交易货币ETF
511860 | 保证金货币ETF
159005 | 汇添富快钱ETF
511900 | 富国货币ETF
159001 | 货币ETF
517270 | 沪港深科技TOPETF
512320 | 工银MSCI中国ETF
511980 | 现金添富ETF
511970 | 国寿货币ETF
511960 | 嘉实快线ETF
511930 | 国联日盈货币ETF
511820 | 鹏华添利ETF
511770 | 金鹰增益货币ETF
511650 | 华夏快线ETF
159003 | 招商快线ETF
511810 | 理财金货币ETF
511910 | 融通货币ETF
511670 | 华泰天天金ETF
511950 | 添利货币ETF

**Comment by albertandking** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本:  macOS Monterey v12.7.4
> 2. Python 版本: 3.12.2
> 3. AKShare 版本: v1.12.92
> 4. 接口的名称和代码: fund_etf_spot_em()
> 5. 接口报错的截图或代码:
>    该接口返回 884 条ETF 记录，部分交易所可以交易的ETF没有返回。参考另一个API：fund_exchange_rank_em() 可以返回 892 条ETF记录。
> 6. 期望获得的正确结果
> 
> 尝试调整eastmoney API 参数，暂时无果。以下为截止到今天比对发现不一致的记录：
> 
> **rank包含，spot不包含：**
> 
> 序号	基金代码	基金简称	类型
> 27	159834	金ETF	指数型-股票
> 30	159831	嘉实上海金ETF	指数型-其他
> 32	159812	前海开源黄金ETF	指数型-其他
> 36	159830	天弘上海金ETF	指数型-其他
> 49	159985	华夏饲料豆粕期货ETF	指数型-其他
> 73	511520	富国中债7-10年政策性金融债ETF	指数型-固收
> 81	159981	建信易盛能源化工期货ETF	指数型-其他
> 83	511270	海富通上证10年期ETF	指数型-固收
> 84	511260	国泰上证10年期国债ETF	指数型-固收
> 86	511020	平安中证5-10年国债活跃券ETF	指数型-固收
> 89	511220	海富通上证城投债ETF	指数型-固收
> 90	159972	鹏华中证5年地债ETF	指数型-固收
> 93	511580	招商中证政策性金融债3-5年ETF	指数型-固收
> 94	159980	大成有色金属期货ETF	指数型-其他
> 96	511060	海富通上证5年期ETF	指数型-固收
> 98	511010	国泰上证5年期国债ETF	指数型-固收
> 99	159816	鹏华0-4年地方政府债ETF	指数型-固收
> 100	159649	华安中债1-5年国开债ETF	指数型-固收
> 102	511030	平安中债债利差因子ETF	指数型-固收
> 103	159650	博时中债0-3年国开行ETF	指数型-固收
> 104	159651	平安中债-0-3年国开行债券ETF	指数型-固收
> 105	511360	海富通中证短融ETF	指数型-固收
> 120	511180	海富通上证投资级可转债ETF	指数型-固收
> 169	511380	博时可转债ETF	指数型-固收
> 734	511090	鹏扬中债-30年期国债ETF	指数型-固收
> 871	511100	华夏上证基准做市国债ETF	指数型-固收
> 880	563080	易方达中证A50ETF	指数型-股票
> 881	159589	广发中证红利ETF	指数型-股票
> 882	561230	工银瑞信中证A50ETF	指数型-股票
> 883	159592	银华中证A50ETF	指数型-股票
> 885	159581	万家中证红利ETF	指数型-股票
> 886	563350	华泰柏瑞中证A50ETF	指数型-股票
> 887	562890	嘉实中证A50ETF	指数型-股票
> 888	159586	南方中证全指计算机ETF	指数型-股票
> 889	159591	富国中证A50ETF	指数型-股票
> 890	159595	大成中证A50ETF	指数型-股票
> 892	159596	华宝中证A50ETF	指数型-股票
> **spot包含，rank不包含：**
> 
> 代码	名称
> 511830	华泰货币ETF
> 511920	广发货币ETF
> 511700	场内货币ETF
> 511800	易方达货币ETF
> 511880	银华日利ETF
> 511660	货币ETF建信添益
> 511620	货币基金ETF
> 511990	华宝添益ETF
> 511850	财富宝ETF
> 511600	货币ETF
> 511690	交易货币ETF
> 511860	保证金货币ETF
> 159005	汇添富快钱ETF
> 511900	富国货币ETF
> 159001	货币ETF
> 517270	沪港深科技TOPETF
> 512320	工银MSCI中国ETF
> 511980	现金添富ETF
> 511970	国寿货币ETF
> 511960	嘉实快线ETF
> 511930	国联日盈货币ETF
> 511820	鹏华添利ETF
> 511770	金鹰增益货币ETF
> 511650	华夏快线ETF
> 159003	招商快线ETF
> 511810	理财金货币ETF
> 511910	融通货币ETF
> 511670	华泰天天金ETF
> 511950	添利货币ETF

对的，一个的东方财富网站，一个是天天基金网（这边应该是两个交易所的），数据源不一致
