### ISSUE TITLE
futures_hog_info()接口报错，请帮忙修复，多谢！

### ISSUE THREAD

**Issue by tianhaisuifeng** [akfamily/akshare#4619]
futures_hog_info()接口报错，无法获取最新数据，只能获取去年的历史数据
比如，获取猪肉批发价时，只能获取截至2023-05-24的数据，换了其他几个参数也类似：
date  value
0    2023-01-25  22.88
1    2023-01-26  22.75
2    2023-01-27  22.71
3    2023-01-28  23.24
4    2023-01-29  23.38
..          ...    ...
115  2023-05-20  19.34
116  2023-05-21  19.40
117  2023-05-22  19.40
118  2023-05-23  19.48
119  2023-05-24  19.43

**Comment by albertandking** [comment]
> futures_hog_info()接口报错，无法获取最新数据，只能获取去年的历史数据 比如，获取猪肉批发价时，只能获取截至2023-05-24的数据，换了其他几个参数也类似： date value 0 2023-01-25 22.88 1 2023-01-26 22.75 2 2023-01-27 22.71 3 2023-01-28 23.24 4 2023-01-29 23.38 .. ... ... 115 2023-05-20 19.34 116 2023-05-21 19.40 117 2023-05-22 19.40 118 2023-05-23 19.48 119 2023-05-24 19.43

感谢反馈问题，已修改相关接口，升级到 AKShare 1.12.95 使用，目前主要新增 futures_hog_core, futures_hog_cost,futures_hog_supply 三个接口
