### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by caiy0233** [akfamily/akshare#4620]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本 WINDOWS11
2. Python 版本 3.11
3. AKShare 版本 1.12.93
4. 接口的名称和代码 
ak.stock_hk_index_daily_em(symbol="HSAHP")
6. 接口报错的截图或代码
![image](https://github.com/akfamily/akshare/assets/43733133/fdef6baf-081d-463b-aa21-e283e76c1d83)

7. 期望获得的正确结果
在东方财富网页版的港股指数行情中是有HSAHP指数的，但是在接口中提取不到
![image](https://github.com/akfamily/akshare/assets/43733133/16b79520-dcdf-4a63-94c1-8fe489a4bd0b)

**Comment by wuuuiYan** [comment]
我也遇到了类似的问题，比如我提取不到美股NDX的数据

**Comment by albertandking** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本 WINDOWS11
> 2. Python 版本 3.11
> 3. AKShare 版本 1.12.93
> 4. 接口的名称和代码
>    ak.stock_hk_index_daily_em(symbol="HSAHP")
> 5. 接口报错的截图或代码
>    ![image](https://private-user-images.githubusercontent.com/43733133/313409863-fdef6baf-081d-463b-aa21-e283e76c1d83.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2NzI1MDQsIm5iZiI6MTcxMDY3MjIwNCwicGF0aCI6Ii80MzczMzEzMy8zMTM0MDk4NjMtZmRlZjZiYWYtMDgxZC00NjNiLWFhMjEtZTI4M2U3NmMxZDgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDEwNDMyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5MmViZjEwZWU2OGMxYTA2NzUxY2UwZmEzMGJiNTkwN2JkMDQwOTIwNjlhOTc5YWViNDcxN2Q0Mjg3NDJlNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3bOMD3cz0WkSq4vQwk6ygkQcL9pKlACkkwFMGmqdBVA)
> 6. 期望获得的正确结果
>    在东方财富网页版的港股指数行情中是有HSAHP指数的，但是在接口中提取不到
>    ![image](https://private-user-images.githubusercontent.com/43733133/313409954-16b79520-dcdf-4a63-94c1-8fe489a4bd0b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2NzI1MDQsIm5iZiI6MTcxMDY3MjIwNCwicGF0aCI6Ii80MzczMzEzMy8zMTM0MDk5NTQtMTZiNzk1MjAtZGNkZi00YTYzLTk0YzEtOGZlNDg5YTRiZDBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDEwNDMyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhY2ZmYTNiNzJjYzI5MTFmMzgxZTYzOWFlOGQ0MmYyZjQxMjQyMDY5NTI1ZTY5ZDQwNWE1ZDljNzQwZDUxNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-TpH4NuohCMKeQcAoKnjUpNqD3toYSFsfiXv86YwDFo)

已修复，升级到 AKShare 1.12.94 使用

**Comment by albertandking** [comment]
> 我也遇到了类似的问题，比如我提取不到美股NDX的数据

用 index_us_stock_sina 接口

**Comment by wuuuiYan** [comment]
> > 我也遇到了类似的问题，比如我提取不到美股NDX的数据
> 
> 用 index_us_stock_sina 接口

我在官网上的数据字典分类里面查不到index_us_stock_sina这个函数的使用方法，后来才在知乎上找到了。这个函数不能像其他大部分函数一样指定时间段和K线类型吗？
