### ISSUE TITLE
接口ak.futures_contract_info_shfe使用报错

### ISSUE THREAD

**Issue by jasonudu** [akfamily/akshare#4626]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. windows11
2. 3.8.8
3. AKShare 版本  1.12.93
4. futureinfo_shfe = ak.futures_contract_info_shfe(date='2024314')
5. 接口报错的截图或代码
![image](https://github.com/akfamily/akshare/assets/106946718/c0ac1ef9-3321-4ca7-b1c7-ece6ad3b9310)

7. 期望获得的正确结果

**Comment by albertandking** [comment]
> 4\. futures_contract_info_shfe

按文档说明输入参数
