### ISSUE TITLE
stock_restricted_release_queue_em(symbol='600006') 报错

### ISSUE THREAD

**Issue by liyqxtu** [akfamily/akshare#4629]
stock_restricted_release_queue_em(symbol='600006') 报错如下
![1](https://github.com/akfamily/akshare/assets/4734699/d289e54d-3c22-413d-9386-5d8a028ffc75)

**Comment by albertandking** [comment]
> stock_restricted_release_queue_em(symbol='600006') 报错如下 ![1](https://private-user-images.githubusercontent.com/4734699/313944979-d289e54d-3c22-413d-9386-5d8a028ffc75.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MTk4MzcsIm5iZiI6MTcxMDkxOTUzNywicGF0aCI6Ii80NzM0Njk5LzMxMzk0NDk3OS1kMjg5ZTU0ZC0zYzIyLTQxM2QtOTM4Ni01ZDhhMDI4ZmZjNzUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjBUMDcyNTM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGYyMWYzYzgzYjc4YzgxNGQ3NWMwNTgxMDhiZTRlN2FhYTA2YmJiNjlhYTY2YjRiMTE3NzIwNTNmNjZiZGYxOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.7-h-k8TM5ssFlM6cZoL9FFW2ND8Z32V3Kxw4IgPFe-g)

接口正常，升级到最新版使用

**Comment by liyqxtu** [comment]
ret = ak.stock_restricted_release_queue_em(symbol='600006')
  File "C:\Python310\Lib\site-packages\akshare\stock_fundamental\stock_restricted_em.py", line 209, in stock_restricted_release_queue_em
    temp_df = pd.DataFrame(data_json["result"]["data"])
TypeError: 'NoneType' object is not subscriptable

已经更新了版本，但这个接口还是有问题呀
