### ISSUE TITLE
stock_zh_a_hist_min_em()返回结果中的"最新价"应该是"均价"

### ISSUE THREAD

**Issue by liyqxtu** [akfamily/akshare#4630]
stock_zh_a_hist_min_em()返回结果中的"最新价"应该是"均价"
        temp_df.columns = [
            "时间",
            "开盘",
            "收盘",
            "最高",
            "最低",
            "成交量",
            "成交额",
            "最新价",  # 应该是"均价"
        ]

**Comment by albertandking** [comment]
> stock_zh_a_hist_min_em()返回结果中的"最新价"应该是"均价" temp_df.columns = [ "时间", "开盘", "收盘", "最高", "最低", "成交量", "成交额", "最新价", # 应该是"均价" ]

请问哪个页面的信息？

**Comment by liyqxtu** [comment]
> > stock_zh_a_hist_min_em()返回结果中的"最新价"应该是"均价" temp_df.columns = [ "时间", "开盘", "收盘", "最高", "最低", "成交量", "成交额", "最新价", # 应该是"均价" ]
> 
> 请问哪个页面的信息？

你这里的“最新价”，通过对比数据后发现其实是分时线中的黄线，也就是“均价”

**Comment by liyqxtu** [comment]
ret = ak.stock_restricted_release_queue_em(symbol='600006')
  File "C:\Python310\Lib\site-packages\akshare\stock_fundamental\stock_restricted_em.py", line 209, in stock_restricted_release_queue_em
    temp_df = pd.DataFrame(data_json["result"]["data"])
TypeError: 'NoneType' object is not subscriptable

已经更新了版本，但这个接口还是有问题呀

**Comment by albertandking** [comment]
> stock_zh_a_hist_min_em()返回结果中的"最新价"应该是"均价" temp_df.columns = [ "时间", "开盘", "收盘", "最高", "最低", "成交量", "成交额", "最新价", # 应该是"均价" ]

已修复该问题，升级到 AKShare 1.12.97 使用
