### ISSUE TITLE
stock_bid_ask_em() 建议在行情报价接口中添加内外盘数据

### ISSUE THREAD

**Issue by liyqxtu** [akfamily/akshare#4631]
tick_dict = {
        "sell_5": data_json["data"]["f31"],
        "sell_5_vol": data_json["data"]["f32"] * 100,
        "sell_4": data_json["data"]["f33"],
        "sell_4_vol": data_json["data"]["f34"] * 100,
        "sell_3": data_json["data"]["f35"],
        "sell_3_vol": data_json["data"]["f36"] * 100,
        "sell_2": data_json["data"]["f37"],
        "sell_2_vol": data_json["data"]["f38"] * 100,
        "sell_1": data_json["data"]["f39"],
        "sell_1_vol": data_json["data"]["f40"] * 100,
        "buy_1": data_json["data"]["f19"],
        "buy_1_vol": data_json["data"]["f20"] * 100,
        "buy_2": data_json["data"]["f17"],
        "buy_2_vol": data_json["data"]["f18"] * 100,
        "buy_3": data_json["data"]["f15"],
        "buy_3_vol": data_json["data"]["f16"] * 100,
        "buy_4": data_json["data"]["f13"],
        "buy_4_vol": data_json["data"]["f14"] * 100,
        "buy_5": data_json["data"]["f11"],
        "buy_5_vol": data_json["data"]["f12"] * 100,  # 建议在行情报价接口中添加内外盘数据
        "最新": data_json["data"]["f43"],
        "均价": data_json["data"]["f71"],
        "涨幅": data_json["data"]["f170"],
        "涨跌": data_json["data"]["f169"],
        "总手": data_json["data"]["f47"],
        "金额": data_json["data"]["f48"],
        "换手": data_json["data"]["f168"],
        "量比": data_json["data"]["f50"],
        "最高": data_json["data"]["f44"],
        "最低": data_json["data"]["f45"],
        "今开": data_json["data"]["f46"],
        "昨收": data_json["data"]["f60"],
        "涨停": data_json["data"]["f51"],
        "跌停": data_json["data"]["f52"],
        "外盘": data_json["data"]["f49"],
        "内盘": data_json["data"]["f161"]
    }

**Comment by albertandking** [comment]
> tick_dict = { "sell_5": data_json["data"]["f31"], "sell_5_vol": data_json["data"]["f32"] * 100, "sell_4": data_json["data"]["f33"], "sell_4_vol": data_json["data"]["f34"] * 100, "sell_3": data_json["data"]["f35"], "sell_3_vol": data_json["data"]["f36"] * 100, "sell_2": data_json["data"]["f37"], "sell_2_vol": data_json["data"]["f38"] * 100, "sell_1": data_json["data"]["f39"], "sell_1_vol": data_json["data"]["f40"] * 100, "buy_1": data_json["data"]["f19"], "buy_1_vol": data_json["data"]["f20"] * 100, "buy_2": data_json["data"]["f17"], "buy_2_vol": data_json["data"]["f18"] * 100, "buy_3": data_json["data"]["f15"], "buy_3_vol": data_json["data"]["f16"] * 100, "buy_4": data_json["data"]["f13"], "buy_4_vol": data_json["data"]["f14"] * 100, "buy_5": data_json["data"]["f11"], "buy_5_vol": data_json["data"]["f12"] * 100, # 建议在行情报价接口中添加内外盘数据 "最新": data_json["data"]["f43"], "均价": data_json["data"]["f71"], "涨幅": data_json["data"]["f170"], "涨跌": data_json["data"]["f169"], "总手": data_json["data"]["f47"], "金额": data_json["data"]["f48"], "换手": data_json["data"]["f168"], "量比": data_json["data"]["f50"], "最高": data_json["data"]["f44"], "最低": data_json["data"]["f45"], "今开": data_json["data"]["f46"], "昨收": data_json["data"]["f60"], "涨停": data_json["data"]["f51"], "跌停": data_json["data"]["f52"], "外盘": data_json["data"]["f49"], "内盘": data_json["data"]["f161"] }

已新增相关字段，升级到 AKShare 1.12.97 使用
