### ISSUE TITLE
stock_restricted_release_queue_em(symbol='600006') 报错，解禁数据为空，导致接口返回数据中的data_json["result"]为None

### ISSUE THREAD

**Issue by liyqxtu** [akfamily/akshare#4639]
https://data.eastmoney.com/dxf/q/600006.html  解禁数据为空，导致接口返回数据中的data_json["result"]为None
![1](https://github.com/akfamily/akshare/assets/4734699/c4a83b12-a652-4e2f-a000-e27e21d03cf2)
导致    ret = ak.stock_restricted_release_queue_em(symbol='600006')
  File "C:\Python310\Lib\site-packages\akshare\stock_fundamental\stock_restricted_em.py", line 209, in stock_restricted_release_queue_em
    temp_df = pd.DataFrame(data_json["result"]["data"])
TypeError: 'NoneType' object is not subscriptable

**Comment by albertandking** [comment]
> https://data.eastmoney.com/dxf/q/600006.html 解禁数据为空，导致接口返回数据中的data_json["result"]为None ![1](https://private-user-images.githubusercontent.com/4734699/314463348-c4a83b12-a652-4e2f-a000-e27e21d03cf2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MzE4NzYsIm5iZiI6MTcxMDkzMTU3NiwicGF0aCI6Ii80NzM0Njk5LzMxNDQ2MzM0OC1jNGE4M2IxMi1hNjUyLTRlMmYtYTAwMC1lMjdlMjFkMDNjZjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjBUMTA0NjE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTY3NDY1ZDVhNmZhODZjYTQ1MTJlYTYxYjQ4ODYwZjQ1ZWIyYmI4YTQxNjY3OGEwMzYxMmIyYmYyZjliMmNiOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Q-0ysTf93OBX2uqc2jQUw1fHw1wW49C-4LSI4q7t8N8) 导致 ret = ak.stock_restricted_release_queue_em(symbol='600006') File "C:\Python310\Lib\site-packages\akshare\stock_fundamental\stock_restricted_em.py", line 209, in stock_restricted_release_queue_em temp_df = pd.DataFrame(data_json["result"]["data"]) TypeError: 'NoneType' object is not subscriptable

对的，本地处理下该异常
