### ISSUE TITLE
分红数据并不是太完善

### ISSUE THREAD

**Issue by Minor-babe** [akfamily/akshare#4640]
目前以拥有的分红数据为每股派息，每股派股。

但是找了一圈并没有发现，公司在一年总的派息与派股。

即每年总共用于派息的金额是多少？

**Comment by albertandking** [comment]
> 目前以拥有的分红数据为每股派息，每股派股。
> 
> 但是找了一圈并没有发现，公司在一年总的派息与派股。
> 
> 即每年总共用于派息的金额是多少？

只提供数据源有的相关数据，具体可以参阅文档，可以获取公司具体的分红配送数据，然后自行计算
