### ISSUE TITLE
stock_hk_valuation_baidu接口问题报告

### ISSUE THREAD

**Issue by Luwy1029** [akfamily/akshare#4645]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本
2. Python 版本 3.9.13
3. AKShare 版本 1.13.1
4. 接口的名称和代码
5. 接口报错的截图或代码
![image](https://github.com/akfamily/akshare/assets/164354252/f32ba362-5ad2-4f3e-bf41-a1f026449369)

7. 期望获得的正确结果

**Comment by albertandking** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本
> 2. Python 版本 3.9.13
> 3. AKShare 版本 1.13.1
> 4. 接口的名称和代码
> 5. 接口报错的截图或代码
>    ![image](https://private-user-images.githubusercontent.com/164354252/315305143-f32ba362-5ad2-4f3e-bf41-a1f026449369.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwOTMwMDAsIm5iZiI6MTcxMTA5MjcwMCwicGF0aCI6Ii8xNjQzNTQyNTIvMzE1MzA1MTQzLWYzMmJhMzYyLTVhZDItNGYzZS1iZjQxLWExZjAyNjQ0OTM2OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMlQwNzMxNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMmQzOGMxNmJhMjM2ZGVmMTkwNjIzZDI4ZDViN2M1ODY5MThhNWI2ZTYxMDYyOTkxYzY0MDFkYTdlMjI3MGM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KStTYuqiTdvKv0D_IDz53HrkjagYF4HF3UX-sHb__vI)
> 6. 期望获得的正确结果

接口测试正常，升级到最新版使用
