### ISSUE TITLE
AKShare 接口df = ak.get_futures_daily(start_date=start_date, end_date=end_date, market=market)

### ISSUE THREAD

**Issue by danbo6** [akfamily/akshare#4646]
会产生这个问题：
raise ValueError(ValueError: Excel file format cannot be determined, you must specify an engine manually.

**Comment by albertandking** [comment]
> 会产生这个问题： raise ValueError(ValueError: Excel file format cannot be determined, you must specify an engine manually.

接口测试正常

**Comment by danbo6** [comment]
> > 会产生这个问题： raise ValueError(ValueError: Excel file format cannot be determined, you must specify an engine manually.
> 
> 接口测试正常

你可以print出来测试大于一年实际的截图吗？我知道一个月的数据下载是可以

**Comment by albertandking** [comment]
> > > 会产生这个问题： raise ValueError(ValueError: Excel file format cannot be determined, you must specify an engine manually.
> > 
> > 
> > 接口测试正常
> 
> 你可以print出来测试大于一年实际的截图吗？我知道一个月的数据下载是可以

![image](https://github.com/akfamily/akshare/assets/18234520/6e592f9c-c0b4-4aaf-aee4-497b582bf745)

**Comment by danbo6** [comment]
> > > > 会产生这个问题： raise ValueError(ValueError: Excel file format cannot be determined, you must specify an engine manually.
> > > 
> > > 
> > > 接口测试正常
> > 
> > 
> > 你可以print出来测试大于一年实际的截图吗？我知道一个月的数据下载是可以
> 
> ![image](https://private-user-images.githubusercontent.com/18234520/315930097-6e592f9c-c0b4-4aaf-aee4-497b582bf745.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwOTQ4NzQsIm5iZiI6MTcxMTA5NDU3NCwicGF0aCI6Ii8xODIzNDUyMC8zMTU5MzAwOTctNmU1OTJmOWMtYzBiNC00YWFmLWFlZTQtNDk3YjU4MmJmNzQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDA4MDI1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyNTQzOGQwNzdjYjFkOWFlZWFjNTFiYzMyZmQ0OWJlMTU5YTJiYTg5YzRmMGNiMjkxYWZlNzY3MDQ3M2I5OTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LTiZ4pIIe0wtVkc6ekqxrwUkgyiHK2RobIY_hCocjuA)

我尝试‘DCE’会有问题
