### ISSUE TITLE
雪球的这个接口无法用stock_individual_spot_xq

### ISSUE THREAD

**Issue by hahahajjkttt** [akfamily/akshare#4653]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本：win10 64位
2. Python 版本  3.9
3. AKShare 版本 1.13.1
4. 接口的名称和代码  stock_individual_spot_xq
5. import akshare as ak

stock_individual_spot_xq_df = ak.stock_individual_spot_xq(symbol="SH600000")
print(stock_individual_spot_xq_df)
6. 接口报错的截图或代码Traceback (most recent call last):
  File "D:\My_sys_data\4555454.py", line 3, in <module>
    stock_individual_spot_xq_df = ak.stock_individual_spot_xq(symbol="SH600000")
  File "D:\My_sys_data\.venv\lib\site-packages\akshare\stock\stock_xq.py", line 80, in stock_individual_spot_xq
    json_data = r.json()["data"]["quote"]
KeyError: 'data'
7. 期望获得的正确结果.这个接口是不是不能用了？

**Comment by albertandking** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本：win10 64位
> 2. Python 版本  3.9
> 3. AKShare 版本 1.13.1
> 4. 接口的名称和代码  stock_individual_spot_xq
> 5. import akshare as ak
> 
> stock_individual_spot_xq_df = ak.stock_individual_spot_xq(symbol="SH600000") print(stock_individual_spot_xq_df) 6. 接口报错的截图或代码Traceback (most recent call last): File "D:\My_sys_data\4555454.py", line 3, in stock_individual_spot_xq_df = ak.stock_individual_spot_xq(symbol="SH600000") File "D:\My_sys_data.venv\lib\site-packages\akshare\stock\stock_xq.py", line 80, in stock_individual_spot_xq json_data = r.json()["data"]["quote"] KeyError: 'data' 7. 期望获得的正确结果.这个接口是不是不能用了？

已修复，升级到 AKShare 1.13.4 使用
