### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'mr_free_context' in dockerfile + poetry

### ISSUE THREAD

**Issue by hanxuanliang** [akfamily/akshare#4655]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

question: 

```txt
   import akshare as ak
  File "/app/.venv/lib/python3.12/site-packages/akshare/__init__.py", line 4172, in <module>
    from akshare.stock_feature.stock_a_pe_and_pb import (
  File "/app/.venv/lib/python3.12/site-packages/akshare/stock_feature/stock_a_pe_and_pb.py", line 319, in <module>
    js_functions = py_mini_racer.MiniRacer()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/py_mini_racer/py_mini_racer.py", line 178, in __init__
    self.__class__.ext = _build_ext_handle()
                         ^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/py_mini_racer/py_mini_racer.py", line 125, in _build_ext_handle
    raise RuntimeError("Native library not available at {}".format(EXTENSION_PATH))
RuntimeError: Native library not available at /app/.venv/lib/python3.12/site-packages/py_mini_racer/libmini_racer.glibc.so
Exception ignored in: <function MiniRacer.__del__ at 0xffff6ad39bc0>
Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/py_mini_racer/py_mini_racer.py", line 315, in __del__
    self.ext.mr_free_context(getattr(self, "ctx", None))
    ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'mr_free_context'
make: *** [Makefile:42: vscript] Error 1
```

Currently, the problem still occurs when executing the akshare function. But I have already copied libmini_racer.dylib internally.

OS version:  aarch64

```txt
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

Python version: Python 3.12.2

AKShare version: 1.13.4

question: use dockerfile + poetry to build APP

```dockerfile
FROM python:3.12.2-slim-bookworm as builder

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

# 添加阿里云的镜像源
RUN echo "deb http://mirrors.aliyun.com/debian/ bookworm main non-free contrib" > /etc/apt/sources.list && \
    echo "deb-src http://mirrors.aliyun.com/debian/ bookworm main non-free contrib" >> /etc/apt/sources.list && \
    echo "deb http://mirrors.aliyun.com/debian-security bookworm-security main" >> /etc/apt/sources.list && \
    echo "deb-src http://mirrors.aliyun.com/debian-security bookworm-security main" >> /etc/apt/sources.list

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    curl \
    make \
    build-essential \
    libffi-dev && \
    curl -sSL https://install.python-poetry.org | python3 - && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENV PATH="/root/.local/bin:$PATH"

COPY . .

RUN poetry config virtualenvs.in-project true && \
    poetry install --no-dev --no-interaction --no-ansi && \
    mkdir -p /app/csv/data/stat && \
    mkdir -p /app/csv/data/stock

FROM python:3.12.2-slim-bookworm

RUN apt-get update && \
    apt-get install -y --no-install-recommends make && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY --from=builder /app /app
COPY --from=builder /root/.local /root/.local

COPY ./libmini_racer.dylib /app/.venv/lib/python3.12/site-packages/py_mini_racer/

ENV PATH="/app/.venv/bin:$PATH"

CMD ["bash"]
```

```poetry
[tool.poetry]
name = "aka"
version = "0.1.0"
description = ""
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
adata = "^1.1.1"
stockstats = "^0.6.2"
pandas = "^2.1.2"
polars = "^0.19.12"
rich = "^13.6.0"
gjson = "^1.0.0"
httpx = { extras = ["socks"], version = "^0.26.0" }
pyyaml = "^6.0.1"
pendulum = "^3.0.0"
notion-client = "^2.2.1"
pydantic-settings = "^2.2.1"
icecream = "^2.1.3"
akshare = "^1.13.3"


[[tool.poetry.source]]
name = "mirrors"
url = "https://pypi.tuna.tsinghua.edu.cn/simple/"
priority = "primary"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

**Comment by albertandking** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> question:
> 
> ```
>    import akshare as ak
>   File "/app/.venv/lib/python3.12/site-packages/akshare/__init__.py", line 4172, in <module>
>     from akshare.stock_feature.stock_a_pe_and_pb import (
>   File "/app/.venv/lib/python3.12/site-packages/akshare/stock_feature/stock_a_pe_and_pb.py", line 319, in <module>
>     js_functions = py_mini_racer.MiniRacer()
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/app/.venv/lib/python3.12/site-packages/py_mini_racer/py_mini_racer.py", line 178, in __init__
>     self.__class__.ext = _build_ext_handle()
>                          ^^^^^^^^^^^^^^^^^^^
>   File "/app/.venv/lib/python3.12/site-packages/py_mini_racer/py_mini_racer.py", line 125, in _build_ext_handle
>     raise RuntimeError("Native library not available at {}".format(EXTENSION_PATH))
> RuntimeError: Native library not available at /app/.venv/lib/python3.12/site-packages/py_mini_racer/libmini_racer.glibc.so
> Exception ignored in: <function MiniRacer.__del__ at 0xffff6ad39bc0>
> Traceback (most recent call last):
>   File "/app/.venv/lib/python3.12/site-packages/py_mini_racer/py_mini_racer.py", line 315, in __del__
>     self.ext.mr_free_context(getattr(self, "ctx", None))
>     ^^^^^^^^^^^^^^^^^^^^^^^^
> AttributeError: 'NoneType' object has no attribute 'mr_free_context'
> make: *** [Makefile:42: vscript] Error 1
> ```
> 
> Currently, the problem still occurs when executing the akshare function. But I have already copied libmini_racer.dylib internally.
> 
> OS version: aarch64
> 
> ```
> PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
> NAME="Debian GNU/Linux"
> VERSION_ID="12"
> VERSION="12 (bookworm)"
> VERSION_CODENAME=bookworm
> ID=debian
> HOME_URL="https://www.debian.org/"
> SUPPORT_URL="https://www.debian.org/support"
> BUG_REPORT_URL="https://bugs.debian.org/"
> ```
> 
> Python version: Python 3.12.2
> 
> AKShare version: 1.13.4
> 
> question: use dockerfile + poetry to build APP
> 
> ```dockerfile
> FROM python:3.12.2-slim-bookworm as builder
> 
> WORKDIR /app
> 
> ENV PYTHONDONTWRITEBYTECODE=1 \
>     PYTHONUNBUFFERED=1
> 
> # 添加阿里云的镜像源
> RUN echo "deb http://mirrors.aliyun.com/debian/ bookworm main non-free contrib" > /etc/apt/sources.list && \
>     echo "deb-src http://mirrors.aliyun.com/debian/ bookworm main non-free contrib" >> /etc/apt/sources.list && \
>     echo "deb http://mirrors.aliyun.com/debian-security bookworm-security main" >> /etc/apt/sources.list && \
>     echo "deb-src http://mirrors.aliyun.com/debian-security bookworm-security main" >> /etc/apt/sources.list
> 
> RUN apt-get update && \
>     apt-get install -y --no-install-recommends \
>     curl \
>     make \
>     build-essential \
>     libffi-dev && \
>     curl -sSL https://install.python-poetry.org | python3 - && \
>     apt-get clean && \
>     rm -rf /var/lib/apt/lists/*
> 
> ENV PATH="/root/.local/bin:$PATH"
> 
> COPY . .
> 
> RUN poetry config virtualenvs.in-project true && \
>     poetry install --no-dev --no-interaction --no-ansi && \
>     mkdir -p /app/csv/data/stat && \
>     mkdir -p /app/csv/data/stock
> 
> FROM python:3.12.2-slim-bookworm
> 
> RUN apt-get update && \
>     apt-get install -y --no-install-recommends make && \
>     apt-get clean && \
>     rm -rf /var/lib/apt/lists/*
> 
> WORKDIR /app
> 
> COPY --from=builder /app /app
> COPY --from=builder /root/.local /root/.local
> 
> COPY ./libmini_racer.dylib /app/.venv/lib/python3.12/site-packages/py_mini_racer/
> 
> ENV PATH="/app/.venv/bin:$PATH"
> 
> CMD ["bash"]
> ```
> 
> ```
> [tool.poetry]
> name = "aka"
> version = "0.1.0"
> description = ""
> readme = "README.md"
> 
> [tool.poetry.dependencies]
> python = ">=3.11,<3.13"
> adata = "^1.1.1"
> stockstats = "^0.6.2"
> pandas = "^2.1.2"
> polars = "^0.19.12"
> rich = "^13.6.0"
> gjson = "^1.0.0"
> httpx = { extras = ["socks"], version = "^0.26.0" }
> pyyaml = "^6.0.1"
> pendulum = "^3.0.0"
> notion-client = "^2.2.1"
> pydantic-settings = "^2.2.1"
> icecream = "^2.1.3"
> akshare = "^1.13.3"
> 
> 
> [[tool.poetry.source]]
> name = "mirrors"
> url = "https://pypi.tuna.tsinghua.edu.cn/simple/"
> priority = "primary"
> 
> [build-system]
> requires = ["poetry-core"]
> build-backend = "poetry.core.masonry.api"
> ```

aarch64 can only be used by macOS M chips and Raspberry Pi（Debian）
