### ISSUE TITLE
土耳其股票数据

### ISSUE THREAD

**Issue by NiZerin** [akfamily/akshare#4672]
**Is your feature request related to a problem? Please describe.**
请问能提供土耳其股票数据吗？

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
https://cn.investing.com/equities/turkey

**Comment by albertandking** [comment]
> **Is your feature request related to a problem? Please describe.** 请问能提供土耳其股票数据吗？
> 
> **Describe the solution you'd like**
> 
> **Describe alternatives you've considered**
> 
> **Additional context** https://cn.investing.com/equities/turkey

暂不支持英为财情的数据
