### ISSUE TITLE
option_minute_em() 修改参数避免调用 option_current_em()

### ISSUE THREAD

**Issue by wugifer** [akfamily/akshare#4673]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

1. 用不同的参数连续调用 option_minute_em() 时，每次都会在内部调用 option_current_em()，仅仅是为了获得 option_current_em_df['标识']，这样会增加大量不必要的网络开销。
2. 可以把 option_current_em_df 作为一个可选参数送入 option_current_em()，这样 option_current_em_df 非 None 时可直接使用：
3. 也可以把 symbol, id_ 作为二选一的参数, 有后者后不必再拼接

```
def option_minute_em(symbol: str = "MO2402-C-5400", option_current_em_df = None) -> pd.DataFrame:
    if option_current_em_df is None:
        option_current_em_df = option_current_em()

   ...
```

```
def option_minute_em(symbol: str = "MO2402-C-5400", id_ = None) -> pd.DataFrame:
    if id_ is None:
        option_current_em_df = option_current_em()
        option_current_em_df['标识'] = option_current_em_df['市场标识'].astype(str) + '.' + option_current_em_df['代码']
        id_ = option_current_em_df[option_current_em_df['代码'] == symbol]['标识'].values[0]
```

**Describe alternatives you've considered**

**Additional context**

**Comment by albertandking** [comment]
> **Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> 
> **Describe the solution you'd like** A clear and concise description of what you want to happen.
> 
> 1. 用不同的参数连续调用 option_minute_em() 时，每次都会在内部调用 option_current_em()，仅仅是为了获得 option_current_em_df['标识']，这样会增加大量不必要的网络开销。
> 2. 可以把 option_current_em_df 作为一个可选参数送入 option_current_em()，这样 option_current_em_df 非 None 时可直接使用：
> 3. 也可以把 symbol, id_ 作为二选一的参数, 有后者后不必再拼接
> 
> ```
> def option_minute_em(symbol: str = "MO2402-C-5400", option_current_em_df = None) -> pd.DataFrame:
>     if option_current_em_df is None:
>         option_current_em_df = option_current_em()
> 
>    ...
> ```
> 
> ```
> def option_minute_em(symbol: str = "MO2402-C-5400", id_ = None) -> pd.DataFrame:
>     if id_ is None:
>         option_current_em_df = option_current_em()
>         option_current_em_df['标识'] = option_current_em_df['市场标识'].astype(str) + '.' + option_current_em_df['代码']
>         id_ = option_current_em_df[option_current_em_df['代码'] == symbol]['标识'].values[0]
> ```
> 
> **Describe alternatives you've considered** A clear and concise description of any alternative solutions or features you've considered.
> 
> **Additional context** Add any other context or screenshots about the feature request here.

已新增缓存功能，升级到 AKShare 1.13.11 使用
