### ISSUE TITLE
建议增加汽车统计数据的接口

### ISSUE THREAD

**Issue by tianhaisuifeng** [akfamily/akshare#4679]
目前car_energy_sale_cpca()能获取新能源汽车整体销量情况，建议增加其他的接口，包括：厂商排名、车型大类和国别细分市场等。
盖世汽车的数据car_gasgoo_sale_rank()要落后1个月，建议增加从乘联会获取最新的数据。

**Comment by albertandking** [comment]
> 目前car_energy_sale_cpca()能获取新能源汽车整体销量情况，建议增加其他的接口，包括：厂商排名、车型大类和国别细分市场等。 盖世汽车的数据car_gasgoo_sale_rank()要落后1个月，建议增加从乘联会获取最新的数据。

已新增相关接口，升级到 AKShare 1.13.19 使用，新增     car_market_cate_cpca, car_market_fuel_cpca, car_market_segment_cpca, car_market_country_cpca, car_market_man_rank_cpca, car_market_total_cpca
