### ISSUE TITLE
legu接口大面积报错，stock_a_indicator_lg()、stock_index_pe_lg()

### ISSUE THREAD

**Issue by tianhaisuifeng** [akfamily/akshare#4680]
legu接口大面积报错，stock_a_indicator_lg()、stock_index_pe_lg()等都出错，应该更新了对应的参数，报错如下：
\akshare\stock_feature\stock_a_indicator.py", line 64, in stock_a_indicator_lg
    temp_df["code"] = temp_df["short_url"].str.split("/", expand=True).iloc[:, -1]

akshare\stock_feature\stock_a_indicator.py", line 27, in get_cookie_csrf
    csrf_token = csrf_tag.attrs["content"]
AttributeError: 'NoneType' object has no attribute 'attrs'

**Comment by tianhaisuifeng** [comment]
网站本身问题，接口没有问题

**Comment by tianhaisuifeng** [comment]
网站本身问题，接口没有问题

**Comment by fgheng** [comment]
获取 pe 数据还可以用哪个接口呀
