### ISSUE TITLE
历史行情数据-新浪 ak.stock_zh_a_daily 获取创业板和科创板股票时出现bug

### ISSUE THREAD

**Issue by xzz4316** [akfamily/akshare#4686]
import akshare as ak

stock_zh_a_daily_qfq_df = ak.stock_zh_a_daily(symbol="sz300750", start_date="20200101", end_date="20240329", adjust="")
print(stock_zh_a_daily_qfq_df)

import akshare as ak

stock_zh_a_daily_qfq_df = ak.stock_zh_a_daily(symbol="sh688001", start_date="20200101", end_date="20240329", adjust="")
print(stock_zh_a_daily_qfq_df)

Traceback (most recent call last):
line 85, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 10 elements, new values have 8 elements

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

import akshare as ak

stock_zh_a_daily_qfq_df = ak.stock_zh_a_daily(symbol="sh688891", start_date="20200101", end_date="20240329", adjust="")
print(stock_zh_a_daily_qfq_df)

Traceback (most recent call last):
line 418, in get_loc
    raise KeyError(key)
KeyError: 'date'

**Comment by albertandking** [comment]
> ak.stock_zh_a_daily(symbol="sz300750", start_date="20200101", end_date="20240329", adjust="")

接口测试正常
