### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by YanZixun** [akfamily/akshare#4691]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. MacOS
2. Python 3.8
3. AKShare 0.1.13
4.  fund_individual_detail_info_xq
5. 遍历基金代码获取到的仓位占比都是100，跟实际不符合（比如下面这些，000786
002804
000424
003534
003468
003465
001826
004072
003871
004078）
6. 期望获得的正确结果：应该获取到正确的仓位占比

**Comment by albertandking** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> **描述遇到的问题**
> 
> 1. MacOS
> 2. Python 3.8
> 3. AKShare 0.1.13
> 4. fund_individual_detail_info_xq
> 5. 遍历基金代码获取到的仓位占比都是100，跟实际不符合（比如下面这些，000786
>    002804
>    000424
>    003534
>    003468
>    003465
>    001826
>    004072
>    003871
>    004078）
> 6. 期望获得的正确结果：应该获取到正确的仓位占比

已修复，升级到 AKShare 1.13.17 使用，使用 fund_individual_detail_hold_xq 接口
