### ISSUE TITLE
Python debugger get stucked when import akshare

### ISSUE THREAD

**Issue by frank142857** [akfamily/akshare#4696]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本: CentOS 7.5
2. Python 版本: Python 3.12.2
3. AKShare 版本: 1.13.16

4. 接口的名称和代码: 
from akshare.air.sunrise_tad import sunrise_daily, sunrise_monthly

5. 接口报错的截图或代码: 
在vscode python debugger (debugpy) 在执行import akshare as ak时卡住，无报错。把第4点描述的语句在库的__init__.py中注释掉即可正常debug。

6. 期望获得的正确结果：
修正如上问题。

**Comment by albertandking** [comment]
> 4\. sunrise_monthly

测试后正常
