### ISSUE TITLE
[feature] 金十的一些数据

### ISSUE THREAD

**Issue by edwardsun** [akfamily/akshare#4698]
您好，
请问akshare有没有计划加入一些金十的数据？比如下面一些重要的数据：
lme库存：https://datacenter.jin10.com/reportType/dc_lme_report
cftc持仓：https://datacenter.jin10.com/reportType/dc_cftc_merchant_goods
api库存：https://datacenter.jin10.com/reportType/dc_usa_api_crude_stock
ism pmi:https://datacenter.jin10.com/reportType/dc_usa_ism_pmi

非常感谢

**Comment by albertandking** [comment]
> 您好， 请问akshare有没有计划加入一些金十的数据？比如下面一些重要的数据： lme库存：https://datacenter.jin10.com/reportType/dc_lme_report cftc持仓：https://datacenter.jin10.com/reportType/dc_cftc_merchant_goods api库存：https://datacenter.jin10.com/reportType/dc_usa_api_crude_stock ism pmi:https://datacenter.jin10.com/reportType/dc_usa_ism_pmi
> 
> 非常感谢

已有相关接口
