### ISSUE TITLE
AKShare 接口问题报告macro_china_pmi_yearly()

### ISSUE THREAD

**Issue by xnw176** [akfamily/akshare#4700]
**描述遇到的问题**
1. 操作系统版本.     MAC OS
2. Python 版本.      3.10
3. AKShare 版本.   最新
4. 接口的名称和代码      macro_china_pmi_yearly()
5. 接口报错的截图或代码
<img width="242" alt="image" src="https://github.com/akfamily/akshare/assets/82297022/24291ae8-c98d-493a-bbef-11b155f4dce0">
数据没有取全，缺少21年5月至22年8月数据，而金十网页中有这些数据

<img width="1055" alt="image" src="https://github.com/akfamily/akshare/assets/82297022/778cbdd7-2ad3-43e8-8626-1f7bbc8e8f8f">

7. 期望获得的正确结果   所有的从金十网站上取数的接口都存在类似问题，希望可以进行全面的检查修正。

**Comment by albertandking** [comment]
> **描述遇到的问题**
> 
> 1. 操作系统版本.     MAC OS
> 2. Python 版本.      3.10
> 3. AKShare 版本.   最新
> 4. 接口的名称和代码      macro_china_pmi_yearly()
> 5. 接口报错的截图或代码
> 
> <img alt="image" width="242" src="https://private-user-images.githubusercontent.com/82297022/319026051-24291ae8-c98d-493a-bbef-11b155f4dce0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxNDAwNTIsIm5iZiI6MTcxMjEzOTc1MiwicGF0aCI6Ii84MjI5NzAyMi8zMTkwMjYwNTEtMjQyOTFhZTgtYzk4ZC00OTNhLWJiZWYtMTFiMTU1ZjRkY2UwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDEwMjIzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5NWNjYjkxYWU1Yzk5YjEyZmUxZTU2OGFjYjQ2ZjYzZjM3MmE4MDhmMmFkYWFjOTc2YTg1OGViNTRkMWFmYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xM8ComtJlylMsVm8wOwqDYi5YxHbcx7u8fXW2Sczj0Y"> 数据没有取全，缺少21年5月至22年8月数据，而金十网页中有这些数据 <img alt="image" width="1055" src="https://private-user-images.githubusercontent.com/82297022/319027165-778cbdd7-2ad3-43e8-8626-1f7bbc8e8f8f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxNDAwNTIsIm5iZiI6MTcxMjEzOTc1MiwicGF0aCI6Ii84MjI5NzAyMi8zMTkwMjcxNjUtNzc4Y2JkZDctMmFkMy00M2U4LTg2MjYtMWY3YmJjOGU4ZjhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDEwMjIzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1MjdkZDA3ZDg5OWRjNzE4YjBmZjgxNDQyYjQ1MGYzYmE2ZTQwMTI4NTQyYzRhNDg2Y2M5MThiZWE1NzE0MzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CbUmTS6NOrkseZ-Ih5eaWvXOTsvvY67nFp738UPCumw">
> 7. 期望获得的正确结果   所有的从金十网站上取数的接口都存在类似问题，希望可以进行全面的检查修正。

已修复，升级到 AKShare 1.13.18 使用

**Comment by rambda** [comment]
> > **描述遇到的问题**
> > 
> > 1. 操作系统版本.     MAC OS
> > 2. Python 版本.      3.10
> > 3. AKShare 版本.   最新
> > 4. 接口的名称和代码      macro_china_pmi_yearly()
> > 5. 接口报错的截图或代码
> > 
> > <img alt="image" width="242" src="https://private-user-images.githubusercontent.com/82297022/319026051-24291ae8-c98d-493a-bbef-11b155f4dce0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxNDAwNTIsIm5iZiI6MTcxMjEzOTc1MiwicGF0aCI6Ii84MjI5NzAyMi8zMTkwMjYwNTEtMjQyOTFhZTgtYzk4ZC00OTNhLWJiZWYtMTFiMTU1ZjRkY2UwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDEwMjIzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5NWNjYjkxYWU1Yzk5YjEyZmUxZTU2OGFjYjQ2ZjYzZjM3MmE4MDhmMmFkYWFjOTc2YTg1OGViNTRkMWFmYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xM8ComtJlylMsVm8wOwqDYi5YxHbcx7u8fXW2Sczj0Y"> 数据没有取全，缺少21年5月至22年8月数据，而金十网页中有这些数据 <img alt="image" width="1055" src="https://private-user-images.githubusercontent.com/82297022/319027165-778cbdd7-2ad3-43e8-8626-1f7bbc8e8f8f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxNDAwNTIsIm5iZiI6MTcxMjEzOTc1MiwicGF0aCI6Ii84MjI5NzAyMi8zMTkwMjcxNjUtNzc4Y2JkZDctMmFkMy00M2U4LTg2MjYtMWY3YmJjOGU4ZjhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDEwMjIzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1MjdkZDA3ZDg5OWRjNzE4YjBmZjgxNDQyYjQ1MGYzYmE2ZTQwMTI4NTQyYzRhNDg2Y2M5MThiZWE1NzE0MzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CbUmTS6NOrkseZ-Ih5eaWvXOTsvvY67nFp738UPCumw">
> > 7. 期望获得的正确结果   所有的从金十网站上取数的接口都存在类似问题，希望可以进行全面的检查修正。
> 
> 已修复，升级到 AKShare 1.13.18 使用

在`ak.macro_usa_ism_pmi()`和`ak.macro_usa_ism_non_pmi()`重新出现了这个问题。
