### ISSUE TITLE
申万网站新接口开发需求

### ISSUE THREAD

**Issue by xnw176** [akfamily/akshare#4701]
链接
https://www.swsresearch.com/institute_sw/allIndex/releasedIndex
截图
<img width="1016" alt="image" src="https://github.com/akfamily/akshare/assets/82297022/bcf250b4-02f4-4d45-add2-32c93e9c89d6">
数据页面示例链接
https://www.swsresearch.com/institute_sw/allIndex/releasedIndex/fundDetail?code=808001&name=申万宏源公募沪深300增强基金超额指数
数据页面截图
<img width="657" alt="image" src="https://github.com/akfamily/akshare/assets/82297022/1f38d451-afc3-42a1-9189-677007ea7a9e">

请求开发相关接口

**Comment by albertandking** [comment]
> 链接 https://www.swsresearch.com/institute_sw/allIndex/releasedIndex 截图 <img alt="image" width="1016" src="https://private-user-images.githubusercontent.com/82297022/319033697-bcf250b4-02f4-4d45-add2-32c93e9c89d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxNDAwMjEsIm5iZiI6MTcxMjEzOTcyMSwicGF0aCI6Ii84MjI5NzAyMi8zMTkwMzM2OTctYmNmMjUwYjQtMDJmNC00ZDQ1LWFkZDItMzJjOTNlOWM4OWQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDEwMjIwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2NWI1MDc0YzIxYzI1ZjdjYzE5YjE4ZjE3NTJiNGRiN2EzNjQzODM3ZGU4ZWIwMzQ0ZTdkNTdkY2VmNDg4MDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ng3MsD-i6K0Y9_E5rCAewiJefgRMp_OfnlOg2Hxwb2M"> 数据页面示例链接 [https://www.swsresearch.com/institute_sw/allIndex/releasedIndex/fundDetail?code=808001&name=申万宏源公募沪深300增强基金超额指数](https://www.swsresearch.com/institute_sw/allIndex/releasedIndex/fundDetail?code=808001&name=%E7%94%B3%E4%B8%87%E5%AE%8F%E6%BA%90%E5%85%AC%E5%8B%9F%E6%B2%AA%E6%B7%B1300%E5%A2%9E%E5%BC%BA%E5%9F%BA%E9%87%91%E8%B6%85%E9%A2%9D%E6%8C%87%E6%95%B0) 数据页面截图 <img alt="image" width="657" src="https://private-user-images.githubusercontent.com/82297022/319034292-1f38d451-afc3-42a1-9189-677007ea7a9e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxNDAwMjEsIm5iZiI6MTcxMjEzOTcyMSwicGF0aCI6Ii84MjI5NzAyMi8zMTkwMzQyOTItMWYzOGQ0NTEtYWZjMy00MmExLTkxODktNjc3MDA3ZWE3YTllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDEwMjIwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1NjFlNDRiMzg1YTY1ZjE5MGVjNzAxMGJiYzQ3M2NkYTUyNjUyZjI2ZGI3ZDdjYjRhOTJkZDhkNDIzMzZlY2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nt2eCjz6rDYrASY0iNgT2OPdI4WPckG3eSHhpNz49jk">
> 
> 请求开发相关接口

已新增相关接口，升级到 AKShare 1.13.18 使用 index_hist_fund_sw，index_realtime_fund_sw
