### ISSUE TITLE
[bug]macro_usa_api_crude_stock缺少数据

### ISSUE THREAD

**Issue by edwardsun** [akfamily/akshare#4705]
macro_usa_api_crude_stock 缺少大量数据
![image](https://github.com/akfamily/akshare/assets/359830/33ddf904-c354-4e0a-bf3f-0e4962ab63b7)
而对应的原数据网站（金10）有这些数据
![image](https://github.com/akfamily/akshare/assets/359830/64b86c3b-0111-4670-84cd-58828ffa8a04)

**Comment by edwardsun** [comment]
此类问题同样存在于ak.macro_usa_ism_pmi() （甚至可能其他金10数据）
![image](https://github.com/akfamily/akshare/assets/359830/7f7f2b74-376a-44d9-829a-bab8211b2e3e)
缺少2021年数据。而金10网站上却有。https://datacenter.jin10.com/reportType/dc_usa_ism_pmi
![image](https://github.com/akfamily/akshare/assets/359830/caa4fc0e-9eb2-474a-b968-942be9ddc8ea)

**Comment by edwardsun** [comment]
ak.macro_china_cx_pmi_yearly() 也有上述问题

**Comment by albertandking** [comment]
> macro_usa_api_crude_stock 缺少大量数据 ![image](https://private-user-images.githubusercontent.com/359830/319248412-33ddf904-c354-4e0a-bf3f-0e4962ab63b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMzMzNjYsIm5iZiI6MTcxMjIzMzA2NiwicGF0aCI6Ii8zNTk4MzAvMzE5MjQ4NDEyLTMzZGRmOTA0LWMzNTQtNGUwYS1iZjNmLTBlNDk2MmFiNjNiNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNFQxMjE3NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MTJlMjgxMTVmMmZjYTZiNjIyMTg3ZDhmY2NkODJjZjA1NzQ4MDViYWQ3OTYzOGQ1MjM3MGQ1ZjcyYmNlZDFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rd0DJxJFT0h-55_R3FPEmDnVfcfXg1FbI6MZz-SzzV8) 而对应的原数据网站（金10）有这些数据 ![image](https://private-user-images.githubusercontent.com/359830/319248975-64b86c3b-0111-4670-84cd-58828ffa8a04.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMzMzNjYsIm5iZiI6MTcxMjIzMzA2NiwicGF0aCI6Ii8zNTk4MzAvMzE5MjQ4OTc1LTY0Yjg2YzNiLTAxMTEtNDY3MC04NGNkLTU4ODI4ZmZhOGEwNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNFQxMjE3NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04N2YzNGQxZGFkZWM0ZThlMjZlNzFjMjYzOTBkMTZiNzg3NDA4M2M5OGU0MmIzYmJiMDU4NTEwNTM1NmRkNjIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7tXBePZDOzHQPcU422MyGh3um8YTSeeLSPppQMAolCY)

已修复，升级到 AKShare 1.13.21 使用

**Comment by edwardsun** [comment]
您好，
macro_usa_ism_non_pmi依然有丢失数据问题。 @albertandking

**Comment by albertandking** [comment]
> 您好， macro_usa_ism_non_pmi依然有丢失数据问题。 @albertandking 还有： macro_china_construction_index， macro_usa_nahb_house_market_index macro_usa_house_price_index， macro_usa_cb_consumer_confidence

已修复，升级到 AKShare 1.13.22 使用
