### ISSUE TITLE
在python 3.12.2上debug程序时，只要import akshare就会卡死；非debug的直接执行就没有问题

### ISSUE THREAD

**Issue by shoutrain** [akfamily/akshare#4706]
**描述遇到的问题**

之前是python 3.11，程序一切正常，无论是debug还是直接执行。昨天升级到python 3.12.2后，直接执行没有问题，但debug时会卡死，最后定位卡死在语句“import akshare as ak”上（断点无法过去），没有任何报错信息。如果去除这句以及相关的部分，debug一切顺利

1. 操作系统版本：Windows 11 Pro
2. Python 版本：3.12.2
4. AKShare 版本：1.13.20
5. 接口的名称和代码：import akshare as ak
6. 接口报错的截图或代码：import akshare as ak
7. 期望获得的正确结果：希望在python 3.12.2上也能debug

**Comment by shoutrain** [comment]
补充：我使用的是在最新的vscode上开发和调试python

**Comment by shoutrain** [comment]
再补充：其他版本不变的情况下，切换到Ubuntu 22.04下，问题依旧。

**Comment by albertandking** [comment]
> **描述遇到的问题**
> 
> 之前是python 3.11，程序一切正常，无论是debug还是直接执行。昨天升级到python 3.12.2后，直接执行没有问题，但debug时会卡死，最后定位卡死在语句“import akshare as ak”上（断点无法过去），没有任何报错信息。如果去除这句以及相关的部分，debug一切顺利
> 
> 1. 操作系统版本：Windows 11 Pro
> 2. Python 版本：3.12.2
> 3. AKShare 版本：1.13.20
> 4. 接口的名称和代码：import akshare as ak
> 5. 接口报错的截图或代码：import akshare as ak
> 6. 期望获得的正确结果：希望在python 3.12.2上也能debug

可以用 pycharm 开发，应该是 vscode 插件的问题

**Comment by shoutrain** [comment]
今天更新到akshare 1.13.75，问题消失。

**Comment by albertandking** [comment]
> 今天更新到akshare 1.13.75，问题消失。

已经移除 pypinyin 的库
