### ISSUE TITLE
stock_cyq_em问题报告

### ISSUE THREAD

**Issue by tbcdfr** [akfamily/akshare#4707]
**描述遇到的问题**
1. 操作系统版本
2. Python 版本 3.11.8
3. AKShare 版本 1.13.17
4. 接口的名称和代码
- akshare\stock_feature\stock_cyq_em.py
5. 接口报错的截图或代码
- 由于html_str里的this.range没有值，导致计算结果与东财页面不同，官方页面的值是120，修改后正常。

**Comment by albertandking** [comment]
> **描述遇到的问题**
> 
> 1. 操作系统版本
> 2. Python 版本 3.11.8
> 3. AKShare 版本 1.13.17
> 4. 接口的名称和代码
> 
> * akshare\stock_feature\stock_cyq_em.py
> 
> 5. 接口报错的截图或代码
> 
> * 由于html_str里的this.range没有值，导致计算结果与东财页面不同，官方页面的值是120，修改后正常。

目前接口是正常的
