### ISSUE TITLE
市场热度-用户关注指数 stock_comment_detail_scrd_focus_em 返回错误数据

### ISSUE THREAD

**Issue by fanchemao** [akfamily/akshare#4708]
**市场热度-用户关注指数 stock_comment_detail_scrd_focus_em 返回错误数据**

1. 当不输入参数时，默认为股票代码600000
```
def run_ak():
    pd.set_option('display.max_columns', None)
    df = pd.DataFrame(ak.stock_comment_detail_scrd_focus_em())
    print(df.head(2))
```
  今天是2024年4月4日，但是返回未来的2024-07-17数据。
<img width="411" alt="Screenshot 2024-04-04 at 12 02 46" src="https://github.com/akfamily/akshare/assets/9508122/4ce8e4df-5ca0-41e4-9955-85bec3821336">
<br>
2. 当输入股票代码参数如"000002"时，直接报错，错误可稳定复现。因为爬取失败了吗？（注：未连接vpn，非多次频繁请求）

<img width="1252" alt="Screenshot 2024-04-04 at 12 01 10" src="https://github.com/akfamily/akshare/assets/9508122/95d6b6f9-619a-445a-b779-e3854ff66a55">

**Comment by albertandking** [comment]
> **市场热度-用户关注指数 stock_comment_detail_scrd_focus_em 返回错误数据**
> 
> 1. 当不输入参数时，默认为股票代码600000
> 
> ```
> def run_ak():
>     pd.set_option('display.max_columns', None)
>     df = pd.DataFrame(ak.stock_comment_detail_scrd_focus_em())
>     print(df.head(2))
> ```
> 
> 今天是2024年4月4日，但是返回未来的2024-07-17数据。 <img alt="Screenshot 2024-04-04 at 12 02 46" width="411" src="https://private-user-images.githubusercontent.com/9508122/319439059-4ce8e4df-5ca0-41e4-9955-85bec3821336.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMzMzNDAsIm5iZiI6MTcxMjIzMzA0MCwicGF0aCI6Ii85NTA4MTIyLzMxOTQzOTA1OS00Y2U4ZTRkZi01Y2EwLTQxZTQtOTk1NS04NWJlYzM4MjEzMzYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDRUMTIxNzIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjlkYjUzNjI3MDAxNWVhNzc2MTM5MjkxZmQ4ZDdmZWQzYjQ5ZDc5YWRlNDQwZmM5YTYyYzQ0MzJhYmQ2NWQyZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.HT_rk0LfwFMB49P42UsSwxe3-BFL84ckpixmjkol1a0"> 2. 当输入股票代码参数如"000002"时，直接报错，错误可稳定复现。因为爬取失败了吗？（注：未连接vpn，非多次频繁请求）
> 
> <img alt="Screenshot 2024-04-04 at 12 01 10" width="1252" src="https://private-user-images.githubusercontent.com/9508122/319438850-95d6b6f9-619a-445a-b779-e3854ff66a55.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMzMzNDAsIm5iZiI6MTcxMjIzMzA0MCwicGF0aCI6Ii85NTA4MTIyLzMxOTQzODg1MC05NWQ2YjZmOS02MTlhLTQ0NWEtYjc3OS1lMzg1NGZmNjZhNTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDRUMTIxNzIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGQ4YTg1NjE4NDdiZDFiZmM3ZDkyYjE3M2Y0NzEwNDVjNTNmZjAzMjg4YWNkNGY1MDc4NDVmNjE4ZDdkZDRkMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.4MIFrbPLgSqfTuWc1_TAdX8HgdXYWmIitAZPMz60dKA">

已修复，升级到 AKShare 1.13.21 使用
