### ISSUE TITLE
stock_em_qbzf接口不存在

### ISSUE THREAD

**Issue by fanchemao** [akfamily/akshare#4710]
在https://akshare.akfamily.xyz/tutorial.html 里描述的增发接口stock_em_qbzf不存在
![Screenshot 2024-04-04 at 16 01 30](https://github.com/akfamily/akshare/assets/9508122/b54829a6-3043-47a0-97b2-e88b458663ae)

IDE报错为：
<img width="784" alt="Screenshot 2024-04-04 at 15 59 51" src="https://github.com/akfamily/akshare/assets/9508122/83a3abbd-7128-4197-94b9-12148844d938">

**Comment by albertandking** [comment]
> stock_em_qbzf

已修复，修改为 stock_qbzf_em
