### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by idontknoowww** [akfamily/akshare#4720]
遇到任何问题，请先确认您的 AKShare 版本是最新的

pip install akshare --upgrade  # Python 版本需要大于等于 3.8
描述遇到的问题

操作系统版本 win10 64位
Python 版本 3.11.7
AKShare 版本 1.13.25
接口的名称和代码 stock_individual_spot_xq_df = ak.stock_individual_spot_xq(symbol="SH600118") print(stock_individual_spot_xq_df.dtypes)
接口报错的截图或代码 Traceback (most recent call last):   File "D:\stock_test\stock\views\test.py", , line 31, in <module>
    stock_individual_spot_xq_df = ak.stock_individual_spot_xq(symbol="SH600118") ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "C:\Users\L3m0k3\anaconda3\Lib\site-packages\akshare\stock\stock_xq.py", line 81, in stock_individual_spot_xq
    json_data = r.json()["data"]["quote"]
                ~~~~~~~~^^^^^^^^
KeyError: 'data'
期望获得的正确结果
看起来雪球系列又又炸了？

**Comment by albertandking** [comment]
只是需要定期更新 cookie 你可以在源代码替换 cookie 就可以

**Comment by idontknoowww** [comment]
> 只是需要定期更新 cookie 你可以在源代码替换 cookie 就可以

确实可以了，感谢

**Comment by WheatMaThink** [comment]
刚刚提交了一个解决方法，大家可以测试一下。 #4729
