### ISSUE TITLE
获取雪球数据返回400，

### ISSUE THREAD

**Issue by WheatMaThink** [akfamily/akshare#4729]
1.Describe the bug**
```
# 调用雪球数据， r = requests.get() 返回400 ，查看本地浏览器cookie，
# 填写 "Cookie":"xqat=4b8bc7136c9fd7b4395f9ca0a65c38363243df2b", 成功，

stock_individual_spot_xq_df = stock_individual_spot_xq(symbol="SH000001")
print(stock_individual_spot_xq_df)

```
-----  

2.  akshare Version v1.13.30. 

3.查看相关资料，雪球反爬虫 cookie 进行了加密，具体信息请查看：  

https://blog.csdn.net/m0_59585734/article/details/134074988

4.解决方案如下：(其他雪球接口，没有测试，如果也有问题，以此类推)
```
def stock_individual_spot_xq(
        symbol: str = "SH600000",
        timeout: float = None,
) -> pd.DataFrame:
    """
    雪球-行情中心-个股
    https://xueqiu.com/S/SH600000
    :param symbol: 证券代码，可以是 A 股代码，A 股场内基金代码，A 股指数，美股代码, 美股指数
    :type symbol: str
    :param timeout: choice of None or a positive float number
    :type timeout: float
    :return: 证券最新行情
    :rtype: pandas.DataFrame
    """

    # 自动处理cookie爬取雪球网
    session = requests.Session()
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
    }
    # 向雪球网首页发送一条请求,获取cookie
    session.get(url="https://xueqiu.com", headers=headers)

    url = f"https://stock.xueqiu.com/v5/stock/quote.json?symbol={symbol}&extend=detail"
    r = session.get(url, headers=headers, timeout=timeout)
   ...

```

**Comment by albertandking** [comment]
> 1.Describe the bug**
> 
> ```
> # 调用雪球数据， r = requests.get() 返回400 ，查看本地浏览器cookie，
> # 填写 "Cookie":"xqat=4b8bc7136c9fd7b4395f9ca0a65c38363243df2b", 成功，
> 
> stock_individual_spot_xq_df = stock_individual_spot_xq(symbol="SH000001")
> print(stock_individual_spot_xq_df)
> ```
> 
> 2. akshare Version v1.13.30.
> 
> 3.查看相关资料，雪球反爬虫 cookie 进行了加密，具体信息请查看：
> 
> https://blog.csdn.net/m0_59585734/article/details/134074988
> 
> 4.解决方案如下：(其他雪球接口，没有测试，如果也有问题，以此类推)
> 
> ```
> def stock_individual_spot_xq(
>         symbol: str = "SH600000",
>         timeout: float = None,
> ) -> pd.DataFrame:
>     """
>     雪球-行情中心-个股
>     https://xueqiu.com/S/SH600000
>     :param symbol: 证券代码，可以是 A 股代码，A 股场内基金代码，A 股指数，美股代码, 美股指数
>     :type symbol: str
>     :param timeout: choice of None or a positive float number
>     :type timeout: float
>     :return: 证券最新行情
>     :rtype: pandas.DataFrame
>     """
> 
>     # 自动处理cookie爬取雪球网
>     session = requests.Session()
>     headers = {
>         "User-Agent": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
>     }
>     # 向雪球网首页发送一条请求,获取cookie
>     session.get(url="https://xueqiu.com", headers=headers)
> 
>     url = f"https://stock.xueqiu.com/v5/stock/quote.json?symbol={symbol}&extend=detail"
>     r = session.get(url, headers=headers, timeout=timeout)
>    ...
> ```

感谢反馈问题并提供解决方案，已修复该问题，升级到 AKShare 1.13.31 使用

**Comment by WheatMaThink** [comment]
感谢作者，提供这么优秀的开源项目。
