### ISSUE TITLE
futures_comm_info 接口报错

### ISSUE THREAD

**Issue by wuyulong0931** [akfamily/akshare#4734]
接口futures_comm_info调用失败, 报错如下:
SSLError: HTTPSConnectionPool(host='[www.9qihuo.com](https://file+.vscode-resource.vscode-cdn.net/d%3A/%E9%87%8F%E5%8C%96%E6%8A%95%E7%A0%94/%E9%87%8F%E5%8C%96%E7%AD%96%E7%95%A5/www.9qihuo.com)', port=443): Max retries exceeded with url: /qihuoshouxufei (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)')))

**Comment by albertandking** [comment]
> 接口futures_comm_info调用失败, 报错如下: SSLError: HTTPSConnectionPool(host='[www.9qihuo.com](https://file+.vscode-resource.vscode-cdn.net/d%3A/%E9%87%8F%E5%8C%96%E6%8A%95%E7%A0%94/%E9%87%8F%E5%8C%96%E7%AD%96%E7%95%A5/www.9qihuo.com)', port=443): Max retries exceeded with url: /qihuoshouxufei (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)')))

感谢反馈问题，已修复该问题，升级到 AKShare 1.13.32 使用
