### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by YanZixun** [akfamily/akshare#4744]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. macos
2. 3.8
3. 1.13.35
4. stock_hsgt_north_net_flow_in_em_df
5.stock_hsgt_north_net_flow_in_em_df = ak.stock_hsgt_north_net_flow_in_em(symbol="北上")， 4.12北向金额显示-505513.20万元
6. 实际上应该为-73.85亿元

**Comment by albertandking** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> **描述遇到的问题**
> 
> 1. macos
> 2. 3.8
> 3. 1.13.35
> 4. stock_hsgt_north_net_flow_in_em_df
>    5.stock_hsgt_north_net_flow_in_em_df = ak.stock_hsgt_north_net_flow_in_em(symbol="北上")， 4.12北向金额显示-505513.20万元
> 5. 实际上应该为-73.85亿元

已修复，升级到 AKShare 1.13.37 使用，调用 stock_hsgt_hist_em
