### ISSUE TITLE
AKShare 接口问题报告 stock_hsgt_individual_detail_em 接口错误

### ISSUE THREAD

**Issue by wwwcisco** [akfamily/akshare#4756]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本 linux 
2. Python 版本 3.10
3. AKShare 版本 1.13.38
4. 接口的名称和代码 df=ak.stock_hsgt_individual_detail_em(symbol='000801',start_date="20240401", end_date="20240415")

6. 接口报错的截图或代码 HTTPConnectionPool(host='datacenter-web.eastmoney.com', port=80): Max retries exceeded with url: /api/data/v1/get?sortColumns=HOLD_DATE&sortTypes=-1&pageSize=500&pageNumber=1&reportName=RPT_MUTUAL_HOLD_DET&columns=ALL&source=WEB&client=WEB&filter=%28SECURITY_CODE%3D%22000801%22%29%28MARKET_CODE%3D%22003%22%29%28HOLD_DATE%3E%3D%272024-04-01%27%29%28HOLD_DATE%3C%3D%272024-04-15%27%29 (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f83452ad9f0>: Failed to resolve 'datacenter-web.eastmoney.com' ([Errno -3] Temporary failure in name resolution)"))
7. 期望获得的正确结果 接口失效

**Comment by albertandking** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本 linux
> 2. Python 版本 3.10
> 3. AKShare 版本 1.13.38
> 4. 接口的名称和代码 df=ak.stock_hsgt_individual_detail_em(symbol='000801',start_date="20240401", end_date="20240415")
> 5. 接口报错的截图或代码 HTTPConnectionPool(host='datacenter-web.eastmoney.com', port=80): Max retries exceeded with url: /api/data/v1/get?sortColumns=HOLD_DATE&sortTypes=-1&pageSize=500&pageNumber=1&reportName=RPT_MUTUAL_HOLD_DET&columns=ALL&source=WEB&client=WEB&filter=%28SECURITY_CODE%3D%22000801%22%29%28MARKET_CODE%3D%22003%22%29%28HOLD_DATE%3E%3D%272024-04-01%27%29%28HOLD_DATE%3C%3D%272024-04-15%27%29 (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f83452ad9f0>: Failed to resolve 'datacenter-web.eastmoney.com' ([Errno -3] Temporary failure in name resolution)"))
> 6. 期望获得的正确结果 接口失效

接口测试正常
