### ISSUE TITLE
请问为什么删除了关于北向和南向资金的几个函数

### ISSUE THREAD

**Issue by USTCmyw** [akfamily/akshare#4757]
akshare.stock_feature.stock_hsgt_em中删除了北向和南向资金的几个函数:
    stock_hsgt_north_acc_flow_in_em,
    stock_hsgt_north_cash_em,
    stock_hsgt_north_net_flow_in_em,
    stock_hsgt_south_acc_flow_in_em,
    stock_hsgt_south_cash_em,
    stock_hsgt_south_net_flow_in_em.
    请问是为什么呢?

**Comment by albertandking** [comment]
> akshare.stock_feature.stock_hsgt_em中删除了北向和南向资金的几个函数: stock_hsgt_north_acc_flow_in_em, stock_hsgt_north_cash_em, stock_hsgt_north_net_flow_in_em, stock_hsgt_south_acc_flow_in_em, stock_hsgt_south_cash_em, stock_hsgt_south_net_flow_in_em. 请问是为什么呢?

接口失效，已经移除

**Comment by USTCmyw** [comment]
> > akshare.stock_feature.stock_hsgt_em中删除了北向和南向资金的几个函数: stock_hsgt_north_acc_flow_in_em, stock_hsgt_north_cash_em, stock_hsgt_north_net_flow_in_em, stock_hsgt_south_acc_flow_in_em, stock_hsgt_south_cash_em, stock_hsgt_south_net_flow_in_em. 请问是为什么呢?
> 
> 接口失效，已经移除

我自己测试的接口是可以使用的

**Comment by albertandking** [comment]
> > > akshare.stock_feature.stock_hsgt_em中删除了北向和南向资金的几个函数: stock_hsgt_north_acc_flow_in_em, stock_hsgt_north_cash_em, stock_hsgt_north_net_flow_in_em, stock_hsgt_south_acc_flow_in_em, stock_hsgt_south_cash_em, stock_hsgt_south_net_flow_in_em. 请问是为什么呢?
> > 
> > 
> > 接口失效，已经移除
> 
> 我自己测试的接口是可以使用的

可以用 stock_hsgt_hist_em 接口
