### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by prophetss** [akfamily/akshare#4762]
AKShare 版本 1.13.39
akshare.futures_return_index_nh("NHECI") 2023-04-11数据重复

**Comment by albertandking** [comment]
> AKShare 版本 1.13.39 akshare.futures_return_index_nh("NHECI") 2023-04-11数据重复

感谢反馈问题，已核对，确实存在该问题，目前跟数据源返回的数据是一致的，建议手动处理下
