### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by lilaboc** [akfamily/akshare#4764]
index_fear_greed_funddb 恐贪指数接口生效, 疑似韭圈儿更新了前端代码

**Comment by Alien-hwx** [comment]
有懂前端的大大佬吗？解决下，我试了一下午没解决

**Comment by albertandking** [comment]
> index_fear_greed_funddb 恐贪指数接口生效, 疑似韭圈儿更新了前端代码

已修复，升级到 AKShare 1.13.40 使用
