### ISSUE TITLE
接口index_fear_greed_funddb调用异常

### ISSUE THREAD

**Issue by wuyulong0931** [akfamily/akshare#4766]
index_fear_greed_funddb 接口调用异常, 报错如下:
JSEvalException: Uncaught Error: Malformed UTF-8 data at undefined:479:20
Error: Malformed UTF-8 data
    at Object.stringify (<anonymous>:479:27)
    at WordArray.init.toString (<anonymous>:216:41)
    at my_decode (<anonymous>:6000:22)
    at <anonymous>:1:46
    at <anonymous>:1:20974

**Comment by albertandking** [comment]
> index_fear_greed_funddb 接口调用异常, 报错如下: JSEvalException: Uncaught Error: Malformed UTF-8 data at undefined:479:20 Error: Malformed UTF-8 data at Object.stringify (:479:27) at WordArray.init.toString (:216:41) at my_decode (:6000:22) at :1:46 at :1:20974

已修复，升级到 AKShare 1.13.40 使用
