### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by Alien-hwx** [akfamily/akshare#4767]
akshare/index/index_fear_greed_funddb.py 的mcode = js_code.call("my_decode", data_json)报错
报错内容：Uncaught Error: Malformed UTF-8 data at undefined:479:20
Error: Malformed UTF-8 data
    at Object.stringify (<anonymous>:479:27)
    at WordArray.init.toString (<anonymous>:216:41)
    at my_decode (<anonymous>:6000:22)
    at <anonymous>:1:46
    at <anonymous>:1:20974

好像是https://api.jiucaishuo.com/v2/kjtl/kjtlconnect            返回的值解密后，并非恐惧贪婪指数了
![image](https://github.com/akfamily/akshare/assets/109501324/d3908b26-5d4b-409c-8d22-4b4e2474d60e)

**Comment by albertandking** [comment]
> akshare/index/index_fear_greed_funddb.py 的mcode = js_code.call("my_decode", data_json)报错 报错内容：Uncaught Error: Malformed UTF-8 data at undefined:479:20 Error: Malformed UTF-8 data at Object.stringify (:479:27) at WordArray.init.toString (:216:41) at my_decode (:6000:22) at :1:46 at :1:20974
> 
> 好像是https://api.jiucaishuo.com/v2/kjtl/kjtlconnect 返回的值解密后，并非恐惧贪婪指数了 ![image](https://private-user-images.githubusercontent.com/109501324/323897108-d3908b26-5d4b-409c-8d22-4b4e2474d60e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2Njg1NjEsIm5iZiI6MTcxMzY2ODI2MSwicGF0aCI6Ii8xMDk1MDEzMjQvMzIzODk3MTA4LWQzOTA4YjI2LTVkNGItNDA5Yy04ZDIyLTRiNGUyNDc0ZDYwZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMVQwMjU3NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wODc1NzZkYTg0NTY3MDU5MGNjZTA4MmM0ZGU1YzE3MTA1YmJhZjdjYTJkODRhNTJmMTA2NWY3NzI1OTJmZjZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dPewrN2MP5hQCruh3hF6tHqZ1SvyqGg6Xd4hanI5B9k)

已修复，升级到 AKShare 1.13.40 使用
