### ISSUE TITLE
[FR] 越来越多的网站会检测JavaScript或者Cookies，是否可以加入类似WebDriver的技术栈来获取这些数据

### ISSUE THREAD

**Issue by carusyte** [akfamily/akshare#4770]
**Is your feature request related to a problem? Please describe.**
E.g. currency_hist() API

**Describe the solution you'd like**
E.g. introducing `selenium` to drive Chrome browser in headless mode

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by albertandking** [comment]
> **Is your feature request related to a problem? Please describe.** E.g. currency_hist() API
> 
> **Describe the solution you'd like** E.g. introducing `selenium` to drive Chrome browser in headless mode
> 
> **Describe alternatives you've considered** N/A
> 
> **Additional context** N/A

建议在用户本地使用类似的技术栈，接口库目前保持轻便为主
