### ISSUE TITLE
AKShare 接口问题报告-akshare.stock_lhb_stock_statistic_em() 方法返回数据只有500行

### ISSUE THREAD

**Issue by fenglingzhang** [akfamily/akshare#4775]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本：windows 10 专业版 21H2
2. Python 版本：Python 3.9.16
3. AKShare 版本：1.13.43
4. 接口的名称和代码：
接口名称：akshare.stock_lhb_stock_statistic_em(
代码：
df = akshare.stock_lhb_stock_statistic_em(symbol="近三月")
print(df)
5. 接口报错的截图或代码
执行时间：20240421 返回记录只有 500 行。
![image](https://github.com/akfamily/akshare/assets/26130205/9d2b0330-6429-4e38-9de7-8be21edb4a3f)

7. 期望获得的正确结果
执行时间：20240421 调用  akshare.stock_lhb_stock_statistic_em(symbol="近三月") 实际数据有 1870 行

**Comment by albertandking** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本：windows 10 专业版 21H2
> 2. Python 版本：Python 3.9.16
> 3. AKShare 版本：1.13.43
> 4. 接口的名称和代码：
>    接口名称：akshare.stock_lhb_stock_statistic_em(
>    代码：
>    df = akshare.stock_lhb_stock_statistic_em(symbol="近三月")
>    print(df)
> 5. 接口报错的截图或代码
>    执行时间：20240421 返回记录只有 500 行。
>    ![image](https://private-user-images.githubusercontent.com/26130205/324262616-9d2b0330-6429-4e38-9de7-8be21edb4a3f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NjY5NDMsIm5iZiI6MTcxMzc2NjY0MywicGF0aCI6Ii8yNjEzMDIwNS8zMjQyNjI2MTYtOWQyYjAzMzAtNjQyOS00ZTM4LTlkZTctOGJlMjFlZGI0YTNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDA2MTcyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2ZWQ3Nzc0NTM0OGZiYTI1YTc2NTg0Njg0ZjM0MGJlNThiYmY2MDI1Yzk5ZDYzYjFlYzEwNmRjYzFlNjg1YzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.20CL8e9xQYQJmCrA__p7weOaYOkt2JR8yC9yw0Bz8go)
> 6. 期望获得的正确结果
>    执行时间：20240421 调用  akshare.stock_lhb_stock_statistic_em(symbol="近三月") 实际数据有 1870 行

感谢反馈问题，已修复该问题，升级到 AKShare 1.13.44 使用
