### ISSUE TITLE
最新版本，stock_index_pb_lg()接口报错

### ISSUE THREAD

**Issue by tianhaisuifeng** [akfamily/akshare#4782]
最新版本，stock_index_pb_lg()接口报错，报错内容如下：
csrf_token = csrf_tag.attrs["content"]
AttributeError: 'NoneType' object has no attribute 'attrs'

**Comment by albertandking** [comment]
> 最新版本，stock_index_pb_lg()接口报错，报错内容如下： csrf_token = csrf_tag.attrs["content"] AttributeError: 'NoneType' object has no attribute 'attrs'

已修复，升级到 AKShare 1.13.47 使用
