### ISSUE TITLE
ak.stock_a_indicator_lg 报错

### ISSUE THREAD

**Issue by matthewxuda** [akfamily/akshare#4787]
**Describe the bug**

**To Reproduce**
>>> import akshare as ak
>>> 
>>> stock_a_indicator_lg_df = ak.stock_a_indicator_lg(symbol="000001")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/[Python.framework/Versions/3.8/lib/python3.8/site-packages/akshare/stock_feature/stock_a_indicator.py](https://github.com/akfamily/akshare/issues/Python.framework/Versions/3.8/lib/python3.8/site-packages/akshare/stock_feature/stock_a_indicator.py)", line 75, in stock_a_indicator_lg
    **get_cookie_csrf(url="https://legulegu.com/"),
  File "/Library/Frameworks/[Python.framework/Versions/3.8/lib/python3.8/site-packages/akshare/stock_feature/stock_a_indicator.py](https://github.com/akfamily/akshare/issues/Python.framework/Versions/3.8/lib/python3.8/site-packages/akshare/stock_feature/stock_a_indicator.py)", line 27, in get_cookie_csrf
    csrf_token = csrf_tag.attrs["content"]
AttributeError: 'NoneType' object has no attribute 'attrs'
**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by albertandking** [comment]
> **Describe the bug** A clear and concise description of what the bug is.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> > > > import akshare as ak
> > > > stock_a_indicator_lg_df = ak.stock_a_indicator_lg(symbol="000001")
> > > > Traceback (most recent call last):
> > > > File "", line 1, in 
> > > > File "/Library/Frameworks/[Python.framework/Versions/3.8/lib/python3.8/site-packages/akshare/stock_feature/stock_a_indicator.py](https://github.com/akfamily/akshare/issues/Python.framework/Versions/3.8/lib/python3.8/site-packages/akshare/stock_feature/stock_a_indicator.py)", line 75, in stock_a_indicator_lg
> > > > **get_cookie_csrf(url="https://legulegu.com/"),
> > > > File "/Library/Frameworks/[Python.framework/Versions/3.8/lib/python3.8/site-packages/akshare/stock_feature/stock_a_indicator.py](https://github.com/akfamily/akshare/issues/Python.framework/Versions/3.8/lib/python3.8/site-packages/akshare/stock_feature/stock_a_indicator.py)", line 27, in get_cookie_csrf
> > > > csrf_token = csrf_tag.attrs["content"]
> > > > AttributeError: 'NoneType' object has no attribute 'attrs'
> > > > **Expected behavior**
> > > > A clear and concise description of what you expected to happen.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
> * OS: [e.g. iOS]
> * Browser [e.g. chrome, safari]
> * Version [e.g. 22]
> 
> **Smartphone (please complete the following information):**
> 
> * Device: [e.g. iPhone6]
> * OS: [e.g. iOS8.1]
> * Browser [e.g. stock browser, safari]
> * Version [e.g. 22]
> 
> **Additional context** Add any other context about the problem here.

接口正常
