### ISSUE TITLE
建议将时间的.astype(str)去掉

### ISSUE THREAD

**Issue by liyqxtu** [akfamily/akshare#4792]
建议所有接口中的
temp_df["时间"] = pd.to_datetime(temp_df["时间"]).astype(str)
改为
temp_df["时间"] = pd.to_datetime(temp_df["时间"])

**Comment by albertandking** [comment]
> 建议所有接口中的 temp_df["时间"] = pd.to_datetime(temp_df["时间"]).astype(str) 改为 temp_df["时间"] = pd.to_datetime(temp_df["时间"])

astype 主要是为了考虑兼容性

**Comment by liyqxtu** [comment]
理由是用户通过接口拿到时间后，如果是个字符串的话，无法实现时间的比较之类的，用户拿到字符串后，还是需要将其转为datetime，而且通过测试可知，这个转换还是相当耗时的呀

**Comment by liyqxtu** [comment]
> 理由是用户通过接口拿到时间后，如果是个字符串的话，无法实现时间的比较之类的，用户拿到字符串后，还是需要将其转为datetime，而且通过测试可知，这个转换还是相当耗时的呀



> 理由是用户通过接口拿到时间后，如果是个字符串的话，无法实现时间的比较之类的，用户拿到字符串后，还是需要将其转为datetime，而且通过测试可知，这个转换还是相当耗时的呀

**Comment by liyqxtu** [comment]
> > 建议所有接口中的 temp_df["时间"] = pd.to_datetime(temp_df["时间"]).astype(str) 改为 temp_df["时间"] = pd.to_datetime(temp_df["时间"])
> 
> astype 主要是为了考虑兼容性

理由是用户通过接口拿到时间后，如果是个字符串的话，无法实现时间的比较之类的，用户拿到字符串后，还是需要将其转为datetime，而且通过测试可知，这个转换还是相当耗时的呀
