### ISSUE TITLE
恐惧贪婪指数index_fear_greed_funddb()接口失效

### ISSUE THREAD

**Issue by fadeout1983** [akfamily/akshare#4796]
恐惧贪婪指数index_fear_greed_funddb()接口失效

**描述遇到的问题**
1. 操作系统版本：win10
2. Python 版本：3.10.10
3. AKShare 版本：1.13.51 
4. 接口的名称和代码：
恐惧贪婪指数 
import akshare as ak
index_fear_greed_funddb_df = ak.index_fear_greed_funddb(symbol="上证指数")
print(index_fear_greed_funddb_df)
5. 接口报错的截图或代码
![报错](https://github.com/akfamily/akshare/assets/88786301/22450e14-fdf3-4c6a-b703-e60690518bac)
6. 期望获得的正确结果
接口不报错

**Comment by albertandking** [comment]
> 恐惧贪婪指数index_fear_greed_funddb()接口失效
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本：win10
> 2. Python 版本：3.10.10
> 3. AKShare 版本：1.13.51
> 4. 接口的名称和代码：
>    恐惧贪婪指数
>    import akshare as ak
>    index_fear_greed_funddb_df = ak.index_fear_greed_funddb(symbol="上证指数")
>    print(index_fear_greed_funddb_df)
> 5. 接口报错的截图或代码
>    ![报错](https://private-user-images.githubusercontent.com/88786301/325862247-22450e14-fdf3-4c6a-b703-e60690518bac.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMTY0NTYsIm5iZiI6MTcxNDExNjE1NiwicGF0aCI6Ii84ODc4NjMwMS8zMjU4NjIyNDctMjI0NTBlMTQtZmRmMy00YzZhLWI3MDMtZTYwNjkwNTE4YmFjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDA3MjIzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiNDFjZmM3MjBjMDQzYjNkZjViNTk2YzFkMTRjZTFkMTYzY2FhYTliMzIyMjQzOGM3NzczM2VkZmM1NWYyNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XZGl3pFhS6gob2W8eztlCXPZfg5muSav7jlOkTNzXVw)
> 6. 期望获得的正确结果
>    接口不报错

接口正常

**Comment by fadeout1983** [comment]
1.报错信息显示在执行 JavaScript 解码操作时出现了“Malformed UTF-8 data”的错误。这个问题是由 py_mini_racer 执行 JavaScript 代码时，遇到了格式不正确的 UTF-8 数据。
![2](https://github.com/akfamily/akshare/assets/88786301/d5b58020-3f96-413a-990c-e5cc2b30a6e7)

2.之前使用了较长时间一直正常，报错了2周了，特提交。我的环境应该没有什么变化。更新了akshare和py_mini_racer到最新版本，还是无法解决。接口正常，为什么还是报错，报错内容看上去也不像是我的环境问题。求助求助。
![3](https://github.com/akfamily/akshare/assets/88786301/df08247e-d0bc-4446-a993-641b8ffce780)

**Comment by yulongg1** [comment]
>>> import akshare as ak
>>> print(ak.__version__)
1.16.44
>>> index_fear_greed_funddb_df = ak.index_fear_greed_funddb(symbol="上证指数")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'akshare' has no attribute 'index_fear_greed_funddb'
你好，为什么我的akshare好像连这个接口都找不到呢
