### ISSUE TITLE
指数市盈率接口stock_index_pe_lg()失效

### ISSUE THREAD

**Issue by fadeout1983** [akfamily/akshare#4797]
指数市盈率接口stock_index_pe_lg()失效

**描述遇到的问题**
1. 操作系统版本:win10
2. Python 版本:3.10.10
3. AKShare 版本:1.13.51
4. 接口的名称和代码:
指数市盈率
import akshare as ak
stock_index_pe_lg_df = ak.stock_index_pe_lg(symbol="上证50")
print(stock_index_pe_lg_df)
6. 接口报错的截图或代码
![报错](https://github.com/akfamily/akshare/assets/88786301/44c2fa50-a867-43ac-9daa-0d123c12c493)

7. 期望获得的正确结果
接口不报错

**Comment by albertandking** [comment]
> stock_index_pe_lg

接口正常

**Comment by fadeout1983** [comment]
接口正常，为什么一直报错呢。这个报错的是csrf令牌，不像是我环境的问题。
![1](https://github.com/akfamily/akshare/assets/88786301/d139dea8-33ab-47b4-962b-8dd64a854e6f)
该代码我之前几个月几乎每天运行一次，没有发现报错，最近几天出现的，尝试了升级库到最新版本还是无法解决。求助。

**Comment by lilaboc** [comment]
1.13.53 测试正常

**Comment by albertandking** [comment]
> 接口正常，为什么一直报错呢。这个报错的是csrf令牌，不像是我环境的问题。 ![1](https://private-user-images.githubusercontent.com/88786301/326240911-d139dea8-33ab-47b4-962b-8dd64a854e6f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzMDMxOTMsIm5iZiI6MTcxNDMwMjg5MywicGF0aCI6Ii84ODc4NjMwMS8zMjYyNDA5MTEtZDEzOWRlYTgtMzNhYi00N2I0LTk2MmItOGRkNjRhODU0ZTZmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDExMTQ1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4YjVkYjhlYzVkZjcyMzhjOThkOWZiNThlOTRkN2ExZGM1OTU1OTMwY2ViNmEzNTRmYjRhZmQ0NzU5YTJhZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oeg4f07xxXPIogvnWQrJGK-w398VLsdRYwGdfp0VyvY) 该代码我之前几个月几乎每天运行一次，没有发现报错，最近几天出现的，尝试了升级库到最新版本还是无法解决。求助。

应该是你本地环境的问题，没有更新到最新版

**Comment by fadeout1983** [comment]
是的，感谢您的回复。
1.一上来我的akshanre 通过 pip install akshare --upgrade没有一次更新到最新版本，仅更新到了1.13.51。后来重复该命令才更新到最新版本的akshare即1.13.53版本。但遗憾的是还是一样的报错。
2.我的理解：问题应该是akshare升级后，导致最某个库的依赖变化引起，我继续尝试看看是哪个依赖库导致的。issue里看到有另一位朋友也碰到了我相似的问题，应该不是我一个人碰到了此问题。




在 2024-04-28 19:15:53，"Albert King" ***@***.***> 写道：

接口正常，为什么一直报错呢。这个报错的是csrf令牌，不像是我环境的问题。 该代码我之前几个月几乎每天运行一次，没有发现报错，最近几天出现的，尝试了升级库到最新版本还是无法解决。求助。

应该是你本地环境的问题，没有更新到最新版

**Comment by fadeout1983** [comment]
问题已解决。python版本问题。解释器为3.10.10版本就会报错如上。换成python3.8版本的可以正常运行。换成了3.12版本也可以正常运行。
