### ISSUE TITLE
两市停复牌ak.stock_tfp_em()数据不完整

### ISSUE THREAD

**Issue by wangzhengli** [akfamily/akshare#4802]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本
fedora 39
3. Python 版本
3.9
5. AKShare 版本
1.13.53
7. 接口的名称和代码
ak.stock_tfp_em(date="20221109")
9. 接口报错的截图或代码
数据不完整，只有网页https://data.eastmoney.com/tfpxx/上第一页的数据
![image](https://github.com/akfamily/akshare/assets/68560657/f0636123-ff6b-41a5-bdf2-c80611535893)

11. 期望获得的正确结果
希望能得到完整的数据
![image](https://github.com/akfamily/akshare/assets/68560657/b9cbd3ac-9aaf-4592-b19b-ea8e6885560f)

**Comment by albertandking** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本
>    fedora 39
> 2. Python 版本
>    3.9
> 3. AKShare 版本
>    1.13.53
> 4. 接口的名称和代码
>    ak.stock_tfp_em(date="20221109")
> 5. 接口报错的截图或代码
>    数据不完整，只有网页[https://data.eastmoney.com/tfpxx/上第一页的数据](https://data.eastmoney.com/tfpxx/%E4%B8%8A%E7%AC%AC%E4%B8%80%E9%A1%B5%E7%9A%84%E6%95%B0%E6%8D%AE)
>    ![image](https://private-user-images.githubusercontent.com/68560657/326256321-f0636123-ff6b-41a5-bdf2-c80611535893.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzMTUxOTAsIm5iZiI6MTcxNDMxNDg5MCwicGF0aCI6Ii82ODU2MDY1Ny8zMjYyNTYzMjEtZjA2MzYxMjMtZmY2Yi00MWE1LWJkZjItYzgwNjExNTM1ODkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDE0MzQ1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwN2E4ZGQwNjY0YzhmYjQ3MGZkYTdiNmE5OGM1OTVlYjAxMDlmMWM4ZjhlOTkyY2I1NDdjMzYxOWEwYjJjY2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gkq4BG-A9tHayYCyrjHsFtE9UFV4UCa7kzPF1Jfxt-M)
> 6. 期望获得的正确结果
>    希望能得到完整的数据
>    ![image](https://private-user-images.githubusercontent.com/68560657/326256375-b9cbd3ac-9aaf-4592-b19b-ea8e6885560f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzMTUxOTAsIm5iZiI6MTcxNDMxNDg5MCwicGF0aCI6Ii82ODU2MDY1Ny8zMjYyNTYzNzUtYjljYmQzYWMtOWFhZi00NTkyLWIxOWItZWE4ZTY4ODU1NjBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDE0MzQ1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiNDFmZGRlZDFhMDE4ZDNjMDY0MzcyYzdiNmYyNjY4YmMyNjdlMjE4OTQ0MzkwZDY3MGYyZmZmZWY3NTNjZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dgtpj_l_rmYgUFc8wKFSbsxinWiV5BA5-DYS151T-3c)

感谢反馈问题，已修复该问题，升级到 AKShare 1.13.54 使用
