### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by LeeLi0708** [akfamily/akshare#4807]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本 centos 7.9
2. Python 版本 3.11
3. AKShare 版本 1.13.54
4. 接口的名称和代码 currency_boc_safe_df = ak.currency_boc_safe()
5. 接口报错的截图或代码 ImportError: Can't connect to HTTPS URL because the SSL module is not available.
6. 期望获得的正确结果

**Comment by albertandking** [comment]
> 4\. currency_boc_safe

感谢反馈问题，已修复该问题，升级到 AKShare 1.13.58 使用
