### ISSUE TITLE
stock_a_below_net_asset_statistics()接口报错

### ISSUE THREAD

**Issue by fadeout1983** [akfamily/akshare#4809]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**

**描述遇到的问题**
stock_a_below_net_asset_statistics()接口报错

1. 操作系统版本：win10
2. Python 版本:3.12.3
3. AKShare 版本:1.13.56
![image](https://github.com/akfamily/akshare/assets/88786301/2e4b99a1-8312-41a0-b6a0-970f00c11d76)

4. 接口的名称和代码
破净股统计
import akshare as ak
stock_a_below_net_asset_statistics_df = ak.stock_a_below_net_asset_statistics(symbol="沪深300")
print(stock_a_below_net_asset_statistics_df)
5. 接口报错的截图或代码
![image](https://github.com/akfamily/akshare/assets/88786301/eeb3425a-c4f6-4b0e-8143-2b06fada9167)
6. 期望获得的正确结果
不报错

**Comment by fadeout1983** [comment]
报错截图没截全，补上如下：
![image](https://github.com/akfamily/akshare/assets/88786301/7c84015f-8db6-4187-90c8-8d8ec4dd305c)

**Comment by albertandking** [comment]
> 4\. stock_a_below_net_asset_statistics

感谢反馈问题，已修复该问题，升级到 AKShare 1.13.58 使用
