### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by sourgelp** [akfamily/akshare#4814]
ak.stock_a_indicator_lg 这个接口调用频率限制是好多啊？现在经常报requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='legulegu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000016306F5C400>, 'Connection to legulegu.com timed out. (connect timeout=None)'))

**Comment by albertandking** [comment]
> stock_a_indicator_lg

接口正常
