### ISSUE TITLE
stock_zh_a_disclosure_report_cninfo返回结果的时间列需要保留具体时间

### ISSUE THREAD

**Issue by welaunchcn** [akfamily/akshare#4816]
有些公告会在盘中发布，返回的JSON中会有具体时间，代码中只保留了日期部分
    big_df["公告时间"] = big_df["公告时间"].dt.tz_convert("Asia/Shanghai").dt.date

**Comment by albertandking** [comment]
> [welaunchcn](/welaunchcn)

跟目标网站格式保持一致

**Comment by welaunchcn** [comment]
目标网站上是有时间的，请参见截图
![cninfo-ann](https://github.com/akfamily/akshare/assets/50825988/c0e3c2f6-78f3-4739-92cf-a77b123cfcaf)

**Comment by albertandking** [comment]
已添加时间字段，升级到 AKShare 1.13.60 使用
