### ISSUE TITLE
获取现货数据

### ISSUE THREAD

**Issue by jasonudu** [akfamily/akshare#4820]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

我们功能当中缺失现货的数据，请帮忙提供一个接口，获取下面网页中的数据https://www.100ppi.com/sf/day-2024-04-30.html
非常感谢！

**Comment by albertandking** [comment]
> **Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> 
> **Describe the solution you'd like** A clear and concise description of what you want to happen.
> 
> **Describe alternatives you've considered** A clear and concise description of any alternative solutions or features you've considered.
> 
> **Additional context** Add any other context or screenshots about the feature request here.
> 
> 我们功能当中缺失现货的数据，请帮忙提供一个接口，获取下面网页中的数据https://www.100ppi.com/sf/day-2024-04-30.html 非常感谢！

已有相关数据

**Comment by jasonudu** [comment]
请告知是那个接口获取？谢谢
