### ISSUE TITLE
AKShare 接口问题报告 - stock_board_concept_name_ths 返回不是最新数据

### ISSUE THREAD

**Issue by divefox** [akfamily/akshare#4824]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
返回概念指数数据与同花顺不一致，不是最新数据

同花顺返回：
<img width="670" alt="Snipaste_2024-05-05_09-09-29" src="https://github.com/akfamily/akshare/assets/2367779/650eb220-5db5-499f-88e2-cfa89b584046">

ak返回
<img width="723" alt="Snipaste_2024-05-05_09-09-42" src="https://github.com/akfamily/akshare/assets/2367779/7afd4682-739e-4820-b803-e8d20623e9ca">

**Comment by albertandking** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> **描述遇到的问题** 返回概念指数数据与同花顺不一致，不是最新数据
> 
> 同花顺返回： <img alt="Snipaste_2024-05-05_09-09-29" width="670" src="https://private-user-images.githubusercontent.com/2367779/327982721-650eb220-5db5-499f-88e2-cfa89b584046.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4NzU1ODUsIm5iZiI6MTcxNDg3NTI4NSwicGF0aCI6Ii8yMzY3Nzc5LzMyNzk4MjcyMS02NTBlYjIyMC01ZGI1LTQ5OWYtODhlMi1jZmE4OWI1ODQwNDYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDVUMDIxNDQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWY4YzgxYTdjMWVhMzNiYTRiMTk1MjNjOTEzOWMzMzIwMzViMzc4NDQ1MzM0NGFjOThiOWQ5ZDU5ZjMxMmRmZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.W1Ma_leTZ-ErawKkXJQ8dJnkLpluGYW-p2JigDntJOw">
> 
> ak返回 <img alt="Snipaste_2024-05-05_09-09-42" width="723" src="https://private-user-images.githubusercontent.com/2367779/327982724-7afd4682-739e-4820-b803-e8d20623e9ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4NzU1ODUsIm5iZiI6MTcxNDg3NTI4NSwicGF0aCI6Ii8yMzY3Nzc5LzMyNzk4MjcyNC03YWZkNDY4Mi03MzllLTQ4MjAtYjgwMy1lOGQyMDYyM2U5Y2EucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDVUMDIxNDQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmUzZjExODgxNmU0ZGM5MTcyMWRkMzg0OTAyMTE5ZTc3NGM5ZWE5MzE0OWI1YTg1MzdlYWIxMWIxNTU2OWJiNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.pJIokW2cd8C4q6ZiZM-1tnzZBTVSLlQM6gD1DdEEre8">

接口正常，升级到最新版使用
