### ISSUE TITLE
AKShare 接口问题报告 stock_ipo_benefit_ths

### ISSUE THREAD

**Issue by digger-yu** [akfamily/akshare#4827]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```
Successfully installed akshare-1.13.62
PS D:\git\test> & d:/git/test/.venv/Scripts/python.exe d:/git/test/11.py
Traceback (most recent call last):
  File "d:\git\test\11.py", line 3, in <module>
    stock_ipo_benefit_ths_df = ak.stock_ipo_benefit_ths()
  File "D:\git\test\.venv\lib\site-packages\akshare\stock_feature\stock_board_industry_ths.py", line 562, in stock_ipo_benefit_ths
    page_num = soup.find("span", attrs={"class": "page_info"}).text.split("/")[1]
AttributeError: 'NoneType' object has no attribute 'text'

**描述遇到的问题**
1. 操作系统版本 win10
2. Python 版本 3.10.11
3. AKShare 版本 1.13.62
4. 接口的名称和代码stock_ipo_benefit_ths ```
import akshare as ak

stock_ipo_benefit_ths_df = ak.stock_ipo_benefit_ths()
print(stock_ipo_benefit_ths_df)
#log
Successfully installed akshare-1.13.62
PS D:\git\test> & d:/git/test/.venv/Scripts/python.exe d:/git/test/11.py
Traceback (most recent call last):
  File "d:\git\test\11.py", line 3, in <module>
    stock_ipo_benefit_ths_df = ak.stock_ipo_benefit_ths()
  File "D:\git\test\.venv\lib\site-packages\akshare\stock_feature\stock_board_industry_ths.py", line 562, in stock_ipo_benefit_ths
    page_num = soup.find("span", attrs={"class": "page_info"}).text.split("/")[1]
AttributeError: 'NoneType' object has no attribute 'text'
```
7. 接口报错的截图或代码
8. 期望获得的正确结果

**Comment by JiangJamm** [comment]
![image](https://github.com/akfamily/akshare/assets/39955422/de9dba82-6df0-4b6c-bdb8-b6c15231699f)
网站无数据

**Comment by albertandking** [comment]
> ![image](https://private-user-images.githubusercontent.com/39955422/328115495-de9dba82-6df0-4b6c-bdb8-b6c15231699f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5ODg4NDUsIm5iZiI6MTcxNDk4ODU0NSwicGF0aCI6Ii8zOTk1NTQyMi8zMjgxMTU0OTUtZGU5ZGJhODItNmRmMC00YjZjLWJkYjgtYjZjMTUyMzE2OTlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDA5NDIyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlMjI0NjhkYTJjOTY5Zjk0YTNmMWNmYTBhNWU3NzJlMDEwOWQzMDQxZWM1MzJkNTZjNTkzZTk5YmIyYTI3NGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6TMBTvPBH-PYqsUdA-9e43iRSclJZAPucCazyntL5qU) 网站无数据

对的
