### ISSUE TITLE
stock_sy_em return TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by jasonlic** [akfamily/akshare#4828]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本
win10 
2. Python 版本
python 3.9 and python3.12.1
3. AKShare 版本
akshare-1.13.62
4. 接口的名称和代码
import akshare as ak

stock_sy_em_df = ak.stock_sy_em(date="20230331")
print(stock_sy_em_df)

5. 接口报错的截图或代码
Traceback (most recent call last):
  File "D:\share\project\exchangetool\AKShareggsy.py", line 4, in <module>
    stock_sy_em_df = ak.stock_sy_em(date="20230331")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jason\miniconda3\Lib\site-packages\akshare\stock_feature\stock_sy_em.py", line 314, in stock_sy_em
    total_page = int(data_json["result"]["pages"])
                     ~~~~~~~~~~~~~~~~~~~^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

8. 期望获得的正确结果

**Comment by JiangJamm** [comment]
![image](https://github.com/akfamily/akshare/assets/39955422/7ad6da62-9522-45e2-80f6-3bd4727fa817)
要填这里面的日期
