### ISSUE TITLE
stock_hk_valuation_baidu 出现问题

### ISSUE THREAD

**Issue by WoonbunLau** [akfamily/akshare#4832]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本
win10
3. Python 版本
3.9.2
5. AKShare 版本
akshare 1.13.63
7. 接口的名称和代码
接口名称：stock_hk_valuation_baidu
代码：values = akshare.stock_hk_valuation_baidu(symbol="01177", indicator="总市值", period="近一年")
9. 接口报错的截图或代码
![1](https://github.com/akfamily/akshare/assets/66934941/c3aa82d6-2322-4d31-9135-a22922efaacb)

Traceback (most recent call last):
  File "C:\Users\86188\Desktop\20240422数据分析\test3.py", line 78, in <module>
    values = akshare.stock_hk_valuation_baidu(symbol="01177", indicator="总市值", period="近一年")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86188\AppData\Local\Programs\Python\Python312\Lib\site-packages\akshare\stock_feature\stock_hk_valuation_baidu.py", line 43, in stock_hk_valuation_baidu
    temp_df = pd.DataFrame(data_json["Result"]["chartInfo"][0]["body"])
                           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
TypeError: list indices must be integers or slices, not str
11. 期望获得的正确结果
修复出错问题

**Comment by albertandking** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本
>    win10
> 2. Python 版本
>    3.9.2
> 3. AKShare 版本
>    akshare 1.13.63
> 4. 接口的名称和代码
>    接口名称：stock_hk_valuation_baidu
>    代码：values = akshare.stock_hk_valuation_baidu(symbol="01177", indicator="总市值", period="近一年")
> 5. 接口报错的截图或代码
>    ![1](https://private-user-images.githubusercontent.com/66934941/328258938-c3aa82d6-2322-4d31-9135-a22922efaacb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNjQyMTUsIm5iZiI6MTcxNTA2MzkxNSwicGF0aCI6Ii82NjkzNDk0MS8zMjgyNTg5MzgtYzNhYTgyZDYtMjMyMi00ZDMxLTkxMzUtYTIyOTIyZWZhYWNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDA2MzgzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0MzkxMzg5ODg2YTVkZWQzNDc3OTIxZWU2ODAwNGZmNWZiMzA2ODY1OTRhMmE2MjgyNzdkOGFmNDc0ODBhZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.e2Ijfpk53-HepFKXz9Ghfa7Nar4it9_yjeD95ArpXIw)
> 
> Traceback (most recent call last): File "C:\Users\86188\Desktop\20240422数据分析\test3.py", line 78, in values = akshare.stock_hk_valuation_baidu(symbol="01177", indicator="总市值", period="近一年") ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\86188\AppData\Local\Programs\Python\Python312\Lib\site-packages\akshare\stock_feature\stock_hk_valuation_baidu.py", line 43, in stock_hk_valuation_baidu temp_df = pd.DataFrame(data_json["Result"]["chartInfo"][0]["body"]) ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^ TypeError: list indices must be integers or slices, not str 11. 期望获得的正确结果 修复出错问题

接口测试正常
