### ISSUE TITLE
AKShare 接口问题报告: bond_info_cm()

### ISSUE THREAD

**Issue by yellowbean** [akfamily/akshare#4838]
**描述遇到的问题**
1. 操作系统版本
Mac OS
3. Python 版本
![Screenshot 2024-05-10 at 14 03 12](https://github.com/akfamily/akshare/assets/1008321/3ce95a8c-9cbb-41ae-b580-09803b1151e3)

4. AKShare 版本
![Screenshot 2024-05-10 at 14 02 53](https://github.com/akfamily/akshare/assets/1008321/c0151269-4640-4b3e-afc5-75a5025867ef)

5. 接口的名称和代码

    bond_info_cm_df = ak.bond_info_cm(bond_name="", bond_code="", bond_issue="", 
    bond_type="短期融资券", coupon_type="零息式", issue_year="2019", grade="A-1", 
    underwriter="重庆农村商业银行股份有限公司")

7. 接口报错的截图或代码

代码： 调取 
    
    bond_info_cm_df = ak.bond_info_cm(bond_name="", bond_code="", bond_issue="", bond_type="短期融资券", coupon_type="零息式", issue_year="2019", grade="A-1", underwriter="重庆农村商业银行股份有限公司")

![Screenshot 2024-05-10 at 14 04 38](https://github.com/akfamily/akshare/assets/1008321/6396b50e-694c-4597-ad37-add06e99cd99)

9. 期望获得的正确结果

**Comment by JiangJamm** [comment]
测试了一下，手动访问一下网站再执行代码就可以跑通，有点奇怪

**Comment by yellowbean** [comment]
> 测试了一下，手动访问一下网站再执行代码就可以跑通，有点奇怪

可能对面server 记录浏览器什么内容，针对这个IP就暂时放宽了.. :(

**Comment by albertandking** [comment]
稍后修复

---- 回复的原邮件 ----
| 发件人 | Shawn ***@***.***> |
| 发送日期 | 2024年05月10日 18:34 |
| 收件人 | akfamily/akshare ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | Re: [akfamily/akshare] AKShare 接口问题报告: bond_info_cm() (Issue #4838) |

测试了一下，手动访问一下网站再执行代码就可以跑通，有点奇怪

可能对面server 记录浏览器什么内容，针对这个IP就暂时放宽了.. :(

**Comment by albertandking** [comment]
> **描述遇到的问题**
> 
> 1. 操作系统版本
>    Mac OS
> 2. Python 版本
>    ![Screenshot 2024-05-10 at 14 03 12](https://private-user-images.githubusercontent.com/1008321/329475466-3ce95a8c-9cbb-41ae-b580-09803b1151e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MzkyODAsIm5iZiI6MTcxNTQzODk4MCwicGF0aCI6Ii8xMDA4MzIxLzMyOTQ3NTQ2Ni0zY2U5NWE4Yy05Y2JiLTQxYWUtYjU4MC0wOTgwM2IxMTUxZTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTFUMTQ0OTQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWY1ZTc3N2U5YWZiNTQyY2UwMjg2N2Y3MzRjODYwMGY0NzU1YjgwZGYxOTQ3MGFmYzRmYmFhZGFmNWRlY2YyNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.fK9fc-xrv0BXgiowi9pSgTJ2pqeHD8yhEIPJWCg3pao)
> 3. AKShare 版本
>    ![Screenshot 2024-05-10 at 14 02 53](https://private-user-images.githubusercontent.com/1008321/329475411-c0151269-4640-4b3e-afc5-75a5025867ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MzkyODAsIm5iZiI6MTcxNTQzODk4MCwicGF0aCI6Ii8xMDA4MzIxLzMyOTQ3NTQxMS1jMDE1MTI2OS00NjQwLTRiM2UtYWZjNS03NWE1MDI1ODY3ZWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTFUMTQ0OTQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTkyZjc5Y2YwMTI5ZTg4ZjU3YjhlZDIyNGE3ZmY2NWNiMzI3NGU1ZmIwNDM3NDdhZTEyNWFmYWE4NjY5NjIzNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ._wvKVTV8LoNA8iFsbFKkMS38gZAsu0Unguk7NYOm-SU)
> 4. 接口的名称和代码
>    bond_info_cm_df = ak.bond_info_cm(bond_name="", bond_code="", bond_issue="",
>    bond_type="短期融资券", coupon_type="零息式", issue_year="2019", grade="A-1",
>    underwriter="重庆农村商业银行股份有限公司")
> 5. 接口报错的截图或代码
> 
> 代码： 调取
> 
> ```
> bond_info_cm_df = ak.bond_info_cm(bond_name="", bond_code="", bond_issue="", bond_type="短期融资券", coupon_type="零息式", issue_year="2019", grade="A-1", underwriter="重庆农村商业银行股份有限公司")
> ```
> 
> ![Screenshot 2024-05-10 at 14 04 38](https://private-user-images.githubusercontent.com/1008321/329475719-6396b50e-694c-4597-ad37-add06e99cd99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MzkyODAsIm5iZiI6MTcxNTQzODk4MCwicGF0aCI6Ii8xMDA4MzIxLzMyOTQ3NTcxOS02Mzk2YjUwZS02OTRjLTQ1OTctYWQzNy1hZGQwNmU5OWNkOTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTFUMTQ0OTQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWY4MmQyN2JkZDlmNDdlYTQwNWMxNDZiZjczMzVjZjBiYjYxNDAwZWM1YTY1ZGZjYjliNDNlN2IyYTUzOTBmMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.2fUgKZuZzkxot0LGVu77wBg_5itIpYwoldTXGlEbz4s)
> 
> 9. 期望获得的正确结果

已修复，升级到 AKShare 1.13.69 使用
