### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by meislzhua** [akfamily/akshare#4840]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本: ubuntu 24.04.04
2. Python 版本: 3.10
3. AKShare 版本: Successfully installed akshare-1.13.67
4. 接口的名称和代码: stock_zh_a_hist_min_em
5. 接口报错的截图或代码
![image](https://github.com/akfamily/akshare/assets/8063591/f542a03c-49ac-437c-8d93-ed3928fabe5d)
![image](https://github.com/akfamily/akshare/assets/8063591/125bbd3e-4f2a-47a2-a31e-e6efe3592256)

6. 期望获得的正确结果
![image](https://github.com/akfamily/akshare/assets/8063591/392eb84a-1267-45a8-8c63-60c0d0fd0062)

是否能获取5日的数据量?数据页面上疑似有5日的数据量?如果API已经出问题,是否能修改一下文档,感谢

**Comment by JiangJamm** [comment]
![image](https://github.com/akfamily/akshare/assets/39955422/16c3b501-e0b8-49eb-a83c-7169ec058f95)
注意参数类型为str
```python
import akshare as ak

stock_zh_a_hist_min_em_df = ak.stock_zh_a_hist_min_em(symbol="000584", period='1', start_date='2024-05-07 09:32:00')
print(stock_zh_a_hist_min_em_df)
```

**Comment by meislzhua** [comment]
感谢,问题已经解决
