### ISSUE TITLE
AKShare 接口问题报告: stock_zh_a_hist_min_em

### ISSUE THREAD

**Issue by meislzhua** [akfamily/akshare#4841]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
1. 操作系统版本: ubuntu 24.04.04
2. Python 版本: 3.10
3. AKShare 版本: Successfully installed akshare-1.13.67
4. 接口的名称和代码: stock_zh_a_hist_min_em
5. 接口报错的截图或代码
![image](https://github.com/akfamily/akshare/assets/8063591/406f70e5-7f40-4bc9-bbb5-b5f235952a53)
(非当天数据,开盘价全部为0)

6. 期望获得的正确结果
正常获取非当天数据的开盘价

**Comment by meislzhua** [comment]
突然发现代码没截图完毕

# 使用东方财经的分时获取
stock_zh_a_hist_min_em_df = ak.stock_zh_a_hist_min_em(symbol="603344", start_date="2024-05-07 09:00:00", period="1")
print(stock_zh_a_hist_min_em_df)

**Comment by albertandking** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本: ubuntu 24.04.04
> 2. Python 版本: 3.10
> 3. AKShare 版本: Successfully installed akshare-1.13.67
> 4. 接口的名称和代码: stock_zh_a_hist_min_em
> 5. 接口报错的截图或代码
>    ![image](https://private-user-images.githubusercontent.com/8063591/329547222-406f70e5-7f40-4bc9-bbb5-b5f235952a53.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0Mzc0NDUsIm5iZiI6MTcxNTQzNzE0NSwicGF0aCI6Ii84MDYzNTkxLzMyOTU0NzIyMi00MDZmNzBlNS03ZjQwLTRiYzktYmJiNS1iNWYyMzU5NTJhNTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTFUMTQxOTA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWQ3ZTQ2ZTBkNGE0YzFhY2Q3MjA1NzYyODliMTkzOTBiODhjMDI4ZjMwNDZkMzY5ZTQ5NTE1ZTM1M2UzZWNkZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.UHSL2yKcJTvkTETQDygYTIiS2v4UV-Mh0KFebGyV0XI)
>    (非当天数据,开盘价全部为0)
> 6. 期望获得的正确结果
>    正常获取非当天数据的开盘价

看文档说明
