### ISSUE TITLE
返回当前所有同花顺概念信息的接口

### ISSUE THREAD

**Issue by divefox** [akfamily/akshare#4842]
目前接口stock_board_concept_info_ths 只能获取 单个 概念数据信息，如果是所有概念，就需要遍历获取（这样性能太差），是否可以开发一个获取所有概念信息数据的接口？类似行业的接口stock_board_industry_summary_ths，或者东财的概念接口stock_board_concept_name_em
另外，stock_board_concept_info_ths  能否加上换手率的数据？

**Comment by albertandking** [comment]
> 目前接口stock_board_concept_info_ths 只能获取 单个 概念数据信息，如果是所有概念，就需要遍历获取（这样性能太差），是否可以开发一个获取所有概念信息数据的接口？类似行业的接口stock_board_industry_summary_ths，或者东财的概念接口stock_board_concept_name_em 另外，stock_board_concept_info_ths 能否加上换手率的数据？

暂时不能
