### ISSUE TITLE
AKShare 接口问题报告：get_futures_daily()

### ISSUE THREAD

**Issue by YjWoo** [akfamily/akshare#4843]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**
5月10日，get_futures_daily()无法获取上海交易所（SHFE）数据
1. 操作系统版本
win11
2. Python 版本
python310
3. AKShare 版本
1.13.66
4. 接口的名称和代码
get_futures_daily(start_date='20240510',end_date='20240510',market='SHFE')
5. 接口报错的截图或代码
<img width="844" alt="get_futuresDaily" src="https://github.com/akfamily/akshare/assets/26670168/3079abcc-3e3c-421f-812a-16bc56ffd592">
6. 期望获得的正确结果
获得上海交易所每日数据

**Comment by bruce198982** [comment]
上期所网页改版了，导致行情数据抓取有误，希望及时修复啊！

**Comment by bruce198982** [comment]
上期所行情持仓量字段发生变更，跟以前的不一样，现在改成 持仓量 / 持仓变化量 导致接口数据格式报错 请知悉

**Comment by albertandking** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> **描述遇到的问题** 5月10日，get_futures_daily()无法获取上海交易所（SHFE）数据
> 
> 1. 操作系统版本
>    win11
> 2. Python 版本
>    python310
> 3. AKShare 版本
>    1.13.66
> 4. 接口的名称和代码
>    get_futures_daily(start_date='20240510',end_date='20240510',market='SHFE')
> 5. 接口报错的截图或代码
> 
> <img alt="get_futuresDaily" width="844" src="https://private-user-images.githubusercontent.com/26670168/329582738-3079abcc-3e3c-421f-812a-16bc56ffd592.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MzkyNzAsIm5iZiI6MTcxNTQzODk3MCwicGF0aCI6Ii8yNjY3MDE2OC8zMjk1ODI3MzgtMzA3OWFiY2MtM2UzYy00MjFmLTgxMmEtMTZiYzU2ZmZkNTkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDE0NDkzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1MWU4ZmUxZGZlM2E5MjQ1M2U0MjY4ZDVlZWEzY2Q4N2VhYjI2NjQxMzFlYmUxYWE3MDdiYjY2Y2QyNzA0ZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6EHYxTtvkBkSw9sQrV560rVxI8Va0t7gs6ZBOj3teXA"> 6. 期望获得的正确结果 获得上海交易所每日数据

已修复，升级到 AKShare 1.13.69 使用
