### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by 903296615** [akfamily/akshare#4845]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

**描述遇到的问题**

你好呀这个bug需要怎么修改,有点看不懂

![2024 5 11,六-155354](https://github.com/akfamily/akshare/assets/33972825/4e8aff03-0153-4518-a813-de150fdd4744)

1. 操作系统版本  :centos8
2. Python 版本    3.12
3. AKShare 版本  :最新版
4. 接口的名称和代码 :stock_zh_a_gdhs_detail_em(601298)
5. 接口报错的截图或代码 :返回条数只有一条6. 期望获得的正确结果 
![2024 5 11,六-154858](https://github.com/akfamily/akshare/assets/33972825/041416ed-f47b-48d5-ac7d-9457fb2d10db)

**Comment by 903296615** [comment]
![2024 5 11,六-155103](https://github.com/akfamily/akshare/assets/33972825/fe8cd7d5-5470-46a3-a2f0-3c88de768522)

**Comment by 903296615** [comment]
![2024 5 11,六-160047](https://github.com/akfamily/akshare/assets/33972825/d9199c7c-0be8-42fe-a352-fddc0f0ab724)
debug是返回的结果只有一条

**Comment by JiangJamm** [comment]
![image](https://github.com/akfamily/akshare/assets/39955422/4795a177-1fb5-4a32-844a-577c4a1d90d8)
网页本身就只有一条数据

**Comment by albertandking** [comment]
> 4\. 601298

接口正常

**Comment by 903296615** [comment]
哈哈哈,可是上面曲线不只有一个
