### ISSUE TITLE
调用ak.sw_index_first_info()的错误

### ISSUE THREAD

**Issue by bilepython** [akfamily/akshare#4846]
File "C:\Users\Administrator\Python310\lib\site-packages\akshare\index\index_sw.py", line 24, in sw_index_first_info
    code_raw = soup.find("div", attrs={"id": "level1Items"}).find_all(

AttributeError: 'NoneType' object has no attribute 'find_all'

**Comment by albertandking** [comment]
> File "C:\Users\Administrator\Python310\lib\site-packages\akshare\index\index_sw.py", line 24, in sw_index_first_info code_raw = soup.find("div", attrs={"id": "level1Items"}).find_all(
> 
> AttributeError: 'NoneType' object has no attribute 'find_all'

接口测试正常

**Comment by rambda** [comment]
> > File "C:\Users\Administrator\Python310\lib\site-packages\akshare\index\index_sw.py", line 24, in sw_index_first_info code_raw = soup.find("div", attrs={"id": "level1Items"}).find_all(
> > AttributeError: 'NoneType' object has no attribute 'find_all'
> 
> 接口测试正常

我遇到了一样的问题，原因是返回 403。我在 `requests.get` 加上了一个普通的 User-Agent `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36` 遂允许访问。
