### ISSUE TITLE
stock_board_concept_cons_ths接口建议

### ISSUE THREAD

**Issue by walkerxyz** [akfamily/akshare#4849]
**描述遇到的问题**
1. Python 版本 3.8.5
2. AKShare 版本  1.13.67
3 接口的名称和代码
stock_board_concept_cons_ths
` stock_board_ths_map_df = stock_board_concept_name_ths()
    symbol = (
        stock_board_ths_map_df[stock_board_ths_map_df["概念名称"] == symbol]["网址"]
        .values[0]
        .split("/")[-2]
    )`
4. 描述
该接口每次都去获取所有概念的列表，再匹配出概念唯一id。建议接受概念唯一id为参数，这样接口功能明确且效率高些。id可以由使用者自己通过stock_board_concept_name_ths接口获取到。且上面匹配代码部分处理返回数据并不严谨容易出错，当参数为'蒙脱石散'时报错。

**Comment by albertandking** [comment]
> 3\. '蒙脱石散

stock_board_concept_name_ths 接口已做缓存处理

**Comment by walkerxyz** [comment]
当参数为'蒙脱石散'时报错
  File "C:\Users\60320\AppData\Local\Programs\Python\Python38\lib\site-packages\akshare\stock_feature\stock_board_concept_ths.py", line 181, in stock_board_concept_cons_ths
    stock_board_ths_map_df[stock_board_ths_map_df["概念名称"] == symbol]["网址"]
IndexError: index 0 is out of bounds for axis 0 with size 0
