### ISSUE TITLE
stock_fhps_detail_ths warning

### ISSUE THREAD

**Issue by chekaiyin** [akfamily/akshare#4862]
warning内容：
.venv/lib/python3.10/site-packages/akshare/stock_feature/stock_fhps_ths.py:29: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  temp_df = pd.read_html(r.text)[0]

运行环境：
Python 3.10.12
akshare            1.13.70
pandas             2.2.2

**Comment by albertandking** [comment]
> warning内容： .venv/lib/python3.10/site-packages/akshare/stock_feature/stock_fhps_ths.py:29: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object. temp_df = pd.read_html(r.text)[0]
> 
> 运行环境： Python 3.10.12 akshare 1.13.70 pandas 2.2.2

感谢反馈问题，已修复该问题，升级到 AKShare 1.13.71 使用
