### ISSUE TITLE
期货上期所获取期货合约信息函数报错futures_contract_info_shfe

### ISSUE THREAD

**Issue by bruce198982** [akfamily/akshare#4864]
1、akshare 版本 ：1.13.71

2、接口报错示例：
day = '20240510'
df = ak.futures_contract_info_shfe(date=day)

3、. 接口报错的截图或描述
![image](https://github.com/akfamily/akshare/assets/20902822/32eb2908-cabe-4b94-bd9a-eddded7eef64)
![image](https://github.com/akfamily/akshare/assets/20902822/fc068004-b1ec-4168-8165-c6ed7cf0ecfa)

**Comment by jasonudu** [comment]
SHFfutures_daily_df = ak.get_futures_daily(start_date=f_dt, end_date=e_dt, market="SHFE")，这个接口也报错，估计都得改

**Comment by albertandking** [comment]
> 1、akshare 版本 ：1.13.71
> 
> 2、接口报错示例： day = '20240510' df = ak.futures_contract_info_shfe(date=day)
> 
> 3、. 接口报错的截图或描述 ![image](https://private-user-images.githubusercontent.com/20902822/329969650-32eb2908-cabe-4b94-bd9a-eddded7eef64.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1OTk4NDMsIm5iZiI6MTcxNTU5OTU0MywicGF0aCI6Ii8yMDkwMjgyMi8zMjk5Njk2NTAtMzJlYjI5MDgtY2FiZS00Yjk0LWJkOWEtZWRkZGVkN2VlZjY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDExMjU0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlODNhNzgwOTQ4OTMzNzEzN2FkZTdjM2MwY2UyNTQ1MWFiZDRmMGRmMmE4NDQ3ODEzMDMxNjExNjQxZjU0M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yj37UHa5gnddtcD3bKVTZ-mnmeU_Su8gF4hiZwMG1tY) ![image](https://private-user-images.githubusercontent.com/20902822/329969751-fc068004-b1ec-4168-8165-c6ed7cf0ecfa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1OTk4NDMsIm5iZiI6MTcxNTU5OTU0MywicGF0aCI6Ii8yMDkwMjgyMi8zMjk5Njk3NTEtZmMwNjgwMDQtYjFlYy00MTY4LTgxNjUtYzZlZDdjZjBlY2ZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDExMjU0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlYTk1MWFkMWQzMTVlNTg3NTBhNGQzNWVkNmRmMjRmY2YwM2EyYWFkOTcwOGU0YWE5ZTc1ZGEyMzY0ZjcyNDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3k_VN1w1sqfF0EJsvuidqlnCgpRNFjmCZallD61t0so)



> 1、akshare 版本 ：1.13.71
> 
> 2、接口报错示例： day = '20240510' df = ak.futures_contract_info_shfe(date=day)
> 
> 3、. 接口报错的截图或描述 ![image](https://private-user-images.githubusercontent.com/20902822/329969650-32eb2908-cabe-4b94-bd9a-eddded7eef64.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1OTk4NDMsIm5iZiI6MTcxNTU5OTU0MywicGF0aCI6Ii8yMDkwMjgyMi8zMjk5Njk2NTAtMzJlYjI5MDgtY2FiZS00Yjk0LWJkOWEtZWRkZGVkN2VlZjY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDExMjU0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlODNhNzgwOTQ4OTMzNzEzN2FkZTdjM2MwY2UyNTQ1MWFiZDRmMGRmMmE4NDQ3ODEzMDMxNjExNjQxZjU0M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yj37UHa5gnddtcD3bKVTZ-mnmeU_Su8gF4hiZwMG1tY) ![image](https://private-user-images.githubusercontent.com/20902822/329969751-fc068004-b1ec-4168-8165-c6ed7cf0ecfa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1OTk4NDMsIm5iZiI6MTcxNTU5OTU0MywicGF0aCI6Ii8yMDkwMjgyMi8zMjk5Njk3NTEtZmMwNjgwMDQtYjFlYy00MTY4LTgxNjUtYzZlZDdjZjBlY2ZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDExMjU0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlYTk1MWFkMWQzMTVlNTg3NTBhNGQzNWVkNmRmMjRmY2YwM2EyYWFkOTcwOGU0YWE5ZTc1ZGEyMzY0ZjcyNDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3k_VN1w1sqfF0EJsvuidqlnCgpRNFjmCZallD61t0so)

已修复该问题，升级到 AKShare 1.13.72 使用
