### ISSUE TITLE
个股新闻查询-AKShare 接口问题报告

### ISSUE THREAD

**Issue by ssgmr** [akfamily/akshare#4865]
1. 操作系统版本：Windows 11 22631.3447
2. Python 版本： 3.9.13
3. AKShare 版本： 1.13.70
4. 接口的名称和相应的调用代码：
stock_news_em_df = ak.stock_news_em(symbol="300059")
print(stock_news_em_df)
5. 接口报错的截图或描述：
temp_df = pd.DataFrame(data_json["result"]["cmsArticleWebOld"])
KeyError: 'cmsArticleWebOld'
http请求入参中param参数似乎没生效，导致所有股票返回的新闻数据都是一样的，且没有cmsArticleWebOld字段。参数编码问题？
6. 期望获得的正确结果：
正常返回个股新闻数据

**Comment by albertandking** [comment]
> 4\. stock_news_em

接口测试正常
