### ISSUE TITLE
上期所数据获取问题及其解决

### ISSUE THREAD

**Issue by cedric-cao** [akfamily/akshare#4866]
1. win11
2. Python3.10.9
3. AKShare 1.12.80 
4. get_futures_daily
5. 接口报错没有数据，经过尝试发现是关于上期所的部分无法获取数据，同时联想到5月11日上期所官网进行了大改版，感觉应当是url进行了大改。
经过搜寻源代码和观察上期所官网源代码，发现应当将    D:\Anaconda\Lib\site-packages\akshare\futures\cons.py文件的   SHFE_DAILY_URL = "http://www.shfe.com.cn/data/dailydata/kx/kx%s.dat"     修改为     SHFE_DAILY_URL = "https://www.shfe.com.cn/data/tradedata/future/dailydata/kx%s.dat"
经过尝试，问题解决
供各位好兄弟参考

**Comment by JiangJamm** [comment]
`get_futures_daily`更新到最新版可使用

**Comment by cedric-cao** [comment]
> `get_futures_daily`更新到最新版可使用
我刚在closed的issue中看到了您的相关修改，但是有个小问题，https://tsite.shfe.com.cn/是上期所的旧网址，会不会过一段时间就被废弃了

**Comment by albertandking** [comment]
> 1. win11
> 2. Python3.10.9
> 3. AKShare 1.12.80
> 4. get_futures_daily
> 5. 接口报错没有数据，经过尝试发现是关于上期所的部分无法获取数据，同时联想到5月11日上期所官网进行了大改版，感觉应当是url进行了大改。
>    经过搜寻源代码和观察上期所官网源代码，发现应当将    D:\Anaconda\Lib\site-packages\akshare\futures\cons.py文件的   SHFE_DAILY_URL = "http://www.shfe.com.cn/data/dailydata/kx/kx%s.dat"     修改为     SHFE_DAILY_URL = "https://www.shfe.com.cn/data/tradedata/future/dailydata/kx%s.dat"
>    经过尝试，问题解决
>    供各位好兄弟参考



> 1. win11
> 2. Python3.10.9
> 3. AKShare 1.12.80
> 4. get_futures_daily
> 5. 接口报错没有数据，经过尝试发现是关于上期所的部分无法获取数据，同时联想到5月11日上期所官网进行了大改版，感觉应当是url进行了大改。
>    经过搜寻源代码和观察上期所官网源代码，发现应当将    D:\Anaconda\Lib\site-packages\akshare\futures\cons.py文件的   SHFE_DAILY_URL = "http://www.shfe.com.cn/data/dailydata/kx/kx%s.dat"     修改为     SHFE_DAILY_URL = "https://www.shfe.com.cn/data/tradedata/future/dailydata/kx%s.dat"
>    经过尝试，问题解决
>    供各位好兄弟参考

已修复该问题，升级到 AKShare 1.13.72 使用

**Comment by bruce198982** [comment]
为啥 我改了 还是报错啊？
经过搜寻源代码和观察上期所官网源代码，发现应当将 D:\Anaconda\Lib\site-packages\akshare\futures\cons.py文件的 SHFE_DAILY_URL = "http://www.shfe.com.cn/data/dailydata/kx/kx%s.dat" 修改为 SHFE_DAILY_URL = "https://www.shfe.com.cn/data/tradedata/future/dailydata/kx%s.dat"

**Comment by JiangJamm** [comment]
> > `get_futures_daily`更新到最新版可使用
> > 我刚在closed的issue中看到了您的相关修改，但是有个小问题，[https://tsite.shfe.com.cn/是上期所的旧网址，会不会过一段时间就被废弃了](https://tsite.shfe.com.cn/%E6%98%AF%E4%B8%8A%E6%9C%9F%E6%89%80%E7%9A%84%E6%97%A7%E7%BD%91%E5%9D%80%EF%BC%8C%E4%BC%9A%E4%B8%8D%E4%BC%9A%E8%BF%87%E4%B8%80%E6%AE%B5%E6%97%B6%E9%97%B4%E5%B0%B1%E8%A2%AB%E5%BA%9F%E5%BC%83%E4%BA%86)

感觉有可能，但是这是一个比较高效的过渡解决方法了，欢迎提pr呀
