### ISSUE TITLE
AKShare 沪深股通数据接口 stock_hsgt_hist_em 返回数据异常

### ISSUE THREAD

**Issue by ustcxmwu** [akfamily/akshare#4868]
## 接口 stock_hsgt_hist_em 

返回数据貌似是不对的，当日资金流入跟其他软件看到的不一致，是不是网页改版之后数据错乱了

**Comment by albertandking** [comment]
> ## 接口 stock_hsgt_hist_em
> 返回数据貌似是不对的，当日资金流入跟其他软件看到的不一致，是不是网页改版之后数据错乱了

以目标网站为准
