### ISSUE TITLE
上期所获取合约信息函数报错，更改网址仍然失效 ak.futures_contract_info_shfe(date=day)

### ISSUE THREAD

**Issue by bruce198982** [akfamily/akshare#4871]
python 版本 3.10.9
akshare 版本 1.13.71

报错案例：
day = '20240513'
ak.futures_contract_info_shfe(date=day)

报错截图：
![image](https://github.com/akfamily/akshare/assets/20902822/a9eb7ece-394a-447f-b35c-c4de945ca90c)

源代码排查：
可能是\akshare\futures_derivative\futures_contract_info_shfe.py这个配置文件里面有错，请排查
![image](https://github.com/akfamily/akshare/assets/20902822/3b80ed33-3a17-42c4-8b65-042fc8cfaf16)

**Comment by albertandking** [comment]
> futures_contract_info_shfe

**Comment by jasonudu** [comment]
这个问题解决了么？
