### ISSUE TITLE
需求：华尔街见闻的宏观日历

### ISSUE THREAD

**Issue by firezym** [akfamily/akshare#4873]
- 页面：
https://wallstreetcn.com/calendar

- 页面中的API，其中start和end都是时间戳：
https://api-one-wscn.awtmt.com/apiv1/finance/macrodatas?start=1715788800&end=1715875199

- 返回所有字段的df或json都可，按照akshare的通用格式

**Comment by albertandking** [comment]
> * 页面：
>   https://wallstreetcn.com/calendar
> * 页面中的API，其中start和end都是时间戳：
>   https://api-one-wscn.awtmt.com/apiv1/finance/macrodatas?start=1715788800&end=1715875199
> * 返回所有字段的df或json都可，按照akshare的通用格式



> * 页面：
>   https://wallstreetcn.com/calendar
> * 页面中的API，其中start和end都是时间戳：
>   https://api-one-wscn.awtmt.com/apiv1/finance/macrodatas?start=1715788800&end=1715875199
> * 返回所有字段的df或json都可，按照akshare的通用格式

已新增 macro_info_ws 接口，升级到 AKShare 1.13.74 使用

**Comment by firezym** [comment]
谢谢，效率真高！
