### ISSUE TITLE
接口问题报告:同花顺行业板块实时信息接口 数据延迟

### ISSUE THREAD

**Issue by zxyyzx** [akfamily/akshare#4875]
1. 操作系统版本：macos 14.4
2. Python 版本：3.12
3. AKShare 版本：最新

在调用stock_board_industry_summary_ths()接口获取同花顺行业板块实时信息的时候，发现各板块的涨跌幅似乎都是有延迟的（相比较于手机端同花顺的行业板块信息，延迟可能有1-2分钟，手机端刷新的速度是秒级）。 我尝试访问原网页https://q.10jqka.com.cn/thshy/
重复刷新页面，发现数据也不是实时刷新。这是受限于网站的某些缓存策略吗？能否针对这个接口做一些特殊处理来绕过缓存策略？

**Comment by zxyyzx** [comment]
另外，感谢维护者的开源贡献，极大地方便了我的数据分析

**Comment by albertandking** [comment]
> 1. 操作系统版本：macos 14.4
> 2. Python 版本：3.12
> 3. AKShare 版本：最新
> 
> 在调用stock_board_industry_summary_ths()接口获取同花顺行业板块实时信息的时候，发现各板块的涨跌幅似乎都是有延迟的（相比较于手机端同花顺的行业板块信息，延迟可能有1-2分钟，手机端刷新的速度是秒级）。 我尝试访问原网页https://q.10jqka.com.cn/thshy/ 重复刷新页面，发现数据也不是实时刷新。这是受限于网站的某些缓存策略吗？能否针对这个接口做一些特殊处理来绕过缓存策略？

感谢支持，目前都是采集 web 端的数据，暂无其他办法
