### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by guogongbo** [akfamily/akshare#4882]
> 欢迎加入《数据科学实战》知识星球，交流财经数据与量化投资相关内容，
> 详细信息参考：https://akshare.akfamily.xyz/learn.html

## 前提

遇到任何问题，请先将您的 AKShare 版本升级到**最新版**，可以通过如下命令升级：

```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

## 如何提交问题

提交问题的同时，请提交以下相关信息，以便于解决问题

**详细描述遇到的问题**

1. 操作系统版本，目前只支持 64 位操作系统
2. Python 版本，目前只支持 3.8 以上的版本
3. AKShare 版本，请升级到最新版
4. 接口的名称和相应的调用代码
```
import akshare as ak
import pandas as pd
stock_financial_analysis_indicator_df = ak.stock_profit_sheet_by_yearly_em(symbol="300670")
print(stock_financial_analysis_indicator_df)
```
5.接口报错的截图或代码
company_type = soup.find(attrs={"id": "hidctype"})["value"]
TypeError: 'NoneType' object is not subscriptable
6.期望获得的正确结果
查看源码时发现：company_type = _stock_balance_sheet_by_report_ctype_em(symbol=symbol)
    url = "https://emweb.securities.eastmoney.com/PC_HSF10/NewFinanceAnalysis/lrbDateAjaxNew"
    params = {
        "companyType": company_type,
        "reportDateType": "1",
        "code": symbol,
    }中url失效
![屏幕截图 2024-05-16 215850](https://github.com/akfamily/akshare/assets/128171658/a6882b8b-5aef-4799-8242-436eb90f0865)

**Comment by albertandking** [comment]
> stock_profit_sheet_by_yearly_em



> > 欢迎加入《数据科学实战》知识星球，交流财经数据与量化投资相关内容，
> > 详细信息参考：https://akshare.akfamily.xyz/learn.html
> 
> ## 前提
> 遇到任何问题，请先将您的 AKShare 版本升级到**最新版**，可以通过如下命令升级：
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> ## 如何提交问题
> 提交问题的同时，请提交以下相关信息，以便于解决问题
> 
> **详细描述遇到的问题**
> 
> 1. 操作系统版本，目前只支持 64 位操作系统
> 2. Python 版本，目前只支持 3.8 以上的版本
> 3. AKShare 版本，请升级到最新版
> 4. 接口的名称和相应的调用代码
> 
> ```
> import akshare as ak
> import pandas as pd
> stock_financial_analysis_indicator_df = ak.stock_profit_sheet_by_yearly_em(symbol="300670")
> print(stock_financial_analysis_indicator_df)
> ```
> 
> 5.接口报错的截图或代码 company_type = soup.find(attrs={"id": "hidctype"})["value"] TypeError: 'NoneType' object is not subscriptable 6.期望获得的正确结果 查看源码时发现：company_type = _stock_balance_sheet_by_report_ctype_em(symbol=symbol) url = "https://emweb.securities.eastmoney.com/PC_HSF10/NewFinanceAnalysis/lrbDateAjaxNew" params = { "companyType": company_type, "reportDateType": "1", "code": symbol, }中url失效 ![屏幕截图 2024-05-16 215850](https://private-user-images.githubusercontent.com/128171658/331236929-a6882b8b-5aef-4799-8242-436eb90f0865.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NjgzMjAsIm5iZiI6MTcxNTg2ODAyMCwicGF0aCI6Ii8xMjgxNzE2NTgvMzMxMjM2OTI5LWE2ODgyYjhiLTVhZWYtNDc5OS04MjQyLTQzNmViOTBmMDg2NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNlQxNDAwMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ODMzMmIxZWRlODk3NTVjODY4OTUxYTA0ODRhYzFjZGNjMjdiZmVkNTg2NjVmMWJmMDQ3MWIxN2E3MzVhMjkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MsMQ9sQpwZ8KOKF7ej8H82YgjkZ5cFDNd9QKso5PPoc)

接口正常，按说明文档使用
