### ISSUE TITLE
stock_zh_a_hist_min_em的1分钟返回数据的open为0

### ISSUE THREAD

**Issue by liyqxtu** [akfamily/akshare#4884]
df=ak.stock_zh_a_hist_min_em(symbol="603777", start_date="2024-05-13 09:30:00", period="1", adjust="")
print(df)
                       时间            开盘   收盘   最高   最低  成交量  成交额   均价
0     2024-05-13 09:30:00   0.00  11.30  11.30  11.30  132  149160.0  11.300
1     2024-05-13 09:31:00   0.00  11.26  11.34  11.21  494  557776.0  11.293
2     2024-05-13 09:32:00   0.00  11.24  11.28  11.23  354  398357.0  11.279
3     2024-05-13 09:33:00   0.00  11.25  11.27  11.25  275  309664.0  11.275
4     2024-05-13 09:34:00   0.00  11.27  11.28  11.23  532  598979.0  11.270

**Comment by albertandking** [comment]
> df=ak.stock_zh_a_hist_min_em(symbol="603777", start_date="2024-05-13 09:30:00", period="1", adjust="") print(df) 时间 开盘 收盘 最高 最低 成交量 成交额 均价 0 2024-05-13 09:30:00 0.00 11.30 11.30 11.30 132 149160.0 11.300 1 2024-05-13 09:31:00 0.00 11.26 11.34 11.21 494 557776.0 11.293 2 2024-05-13 09:32:00 0.00 11.24 11.28 11.23 354 398357.0 11.279 3 2024-05-13 09:33:00 0.00 11.25 11.27 11.25 275 309664.0 11.275 4 2024-05-13 09:34:00 0.00 11.27 11.28 11.23 532 598979.0 11.270

参见文档说明
