### ISSUE TITLE
AKShare 接口问题报告ak.stock_news_em()

### ISSUE THREAD

**Issue by Dbgsaoge** [akfamily/akshare#4885]
**详细描述遇到的问题**

1. 操作系统版本: windows11
2. Python 版本，3.10.9
3. AKShare 版本，1.13.76
4. 接口的名称: 
keyword = "300059"
stock_news_em_df = ak.stock_news_em(symbol=keyword)
![Y7W {9365)YJTNGKT79N906](https://github.com/akfamily/akshare/assets/98277821/7923f169-d5e4-4732-8b67-164e3ff93a30)

接口不能正常调用

**Comment by JiangJamm** [comment]
发现不管传入什么，返回的都是达利食品。尝试添加headers和cookies无法解决
<img width="2041" alt="image" src="https://github.com/akfamily/akshare/assets/39955422/7844471d-73b6-4d8f-aa0e-ec61d07351b2">

**Comment by Dbgsaoge** [comment]
> 发现不管传入什么，返回的都是达利食品。尝试添加headers和cookies无法解决 <img alt="image" width="2000" src="https://private-user-images.githubusercontent.com/39955422/331771168-7844471d-73b6-4d8f-aa0e-ec61d07351b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwMTQwODksIm5iZiI6MTcxNjAxMzc4OSwicGF0aCI6Ii8zOTk1NTQyMi8zMzE3NzExNjgtNzg0NDQ3MWQtNzNiNi00ZDhmLWFhMGUtZWM2MWQwNzM1MWIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDA2Mjk0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhNGZkYmJhMmY1NDNmNWY2NjBhNjNhNDA3ODZjZWEyNTI0NmIzODJlM2JhMThjMWIyOGQ1ZGNmODAzZDI0NDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GM6HO4x8ewjoi4j15OA_2PNwLXodTafs_5GPEukw3ZA">

你这个是在windows下跑的吗，它默认的symbol就是300059，我现在直接就报错keyerror然后就结束了

**Comment by albertandking** [comment]
> **详细描述遇到的问题**
> 
> 1. 操作系统版本: windows11
> 2. Python 版本，3.10.9
> 3. AKShare 版本，1.13.76
> 4. 接口的名称:
>    keyword = "300059"
>    stock_news_em_df = ak.stock_news_em(symbol=keyword)
>    ![Y7W {9365)YJTNGKT79N906](https://private-user-images.githubusercontent.com/98277821/331692017-7923f169-d5e4-4732-8b67-164e3ff93a30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxMTEzNTMsIm5iZiI6MTcxNjExMTA1MywicGF0aCI6Ii85ODI3NzgyMS8zMzE2OTIwMTctNzkyM2YxNjktZDVlNC00NzMyLThiNjctMTY0ZTNmZjkzYTMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE5VDA5MzA1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1ODI5MmQzZDU1MDAyMjIxZDViMjNkMmM1YWYxM2I3MDQ0NWY1OWY4YTZiNzRlMzJmMjI0MDY4Mzg4NDM4Y2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HLUuOKOI4AwLUg3oBgu-IRxzAghN9TOT1G6QqDa6Byg)
> 
> 接口不能正常调用

接口测试正常

**Comment by onceCWJ** [comment]
@Dbgsaoge 哥们确实可以，我在windows上不行，但是在linux上就可以了感觉不是接口的问题？
