### ISSUE TITLE
AKShare 获取持仓排名

### ISSUE THREAD

**Issue by nekoman233** [akfamily/akshare#4891]
python 3.11
akshare-1.13.80
问题描述：
获取持仓排名的时候，无论是大商所还是上期所都会出现以下报错：
![image](https://github.com/akfamily/akshare/assets/45714639/5ae012ab-5da2-4532-892d-2d77e45c0380)
经查验，是cot.py文件中获取排名方法中获取end_list方法不对，之前是“总计”，现在数据为“合计”，改为“合计”后，end_list分出的三个索引还是缺少最后一个索引，于是添加上最后一个索引，结果还是报错

**Comment by imagemoon0406** [comment]
同样的问题，get_rank_sum_daily报错

**Comment by albertandking** [comment]
> python 3.11 akshare-1.13.80 问题描述： 获取持仓排名的时候，无论是大商所还是上期所都会出现以下报错： ![image](https://private-user-images.githubusercontent.com/45714639/332048823-5ae012ab-5da2-4532-892d-2d77e45c0380.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyNzI3MzAsIm5iZiI6MTcxNjI3MjQzMCwicGF0aCI6Ii80NTcxNDYzOS8zMzIwNDg4MjMtNWFlMDEyYWItNWRhMi00NTMyLTg5MmQtMmQ3N2U0NWMwMzgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDA2MjAzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4ZjYzODI5ZjllZGUwYWE5NTQzZjQ0ZDc5MTc4ZGNkODlkNDYzYjUzNzA0ZTBlMmY0ZGQ1MGJhMTI3MTkyZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sAB1xyuV65aCOXDBAWWDukFzoXmokrkoNQmM7xbIv6A) 经查验，是cot.py文件中获取排名方法中获取end_list方法不对，之前是“总计”，现在数据为“合计”，改为“合计”后，end_list分出的三个索引还是缺少最后一个索引，于是添加上最后一个索引，结果还是报错

已修复，升级到 AKShare 1.13.82 使用
