### ISSUE TITLE
获取东财三大报表时接口报错

### ISSUE THREAD

**Issue by voguke** [akfamily/akshare#4894]
> 欢迎加入《数据科学实战》知识星球，交流财经数据与量化投资相关内容，
> 详细信息参考：https://akshare.akfamily.xyz/learn.html

## 前提

遇到任何问题，请先将您的 AKShare 版本升级到**最新版**，可以通过如下命令升级：

```
已升级到最新版本
```

## 如何提交问题

提交问题的同时，请提交以下相关信息，以便于解决问题

**详细描述遇到的问题**

1. 操作系统版本，目前只支持 64 位操作系统
3. Python 版本，目前只支持 3.8 以上的版本
4. AKShare 版本，请升级到最新版
5. 接口的名称和相应的调用代码
6. 接口报错的截图或描述
7. 期望获得的正确结果

操作系统
Alibaba Cloud Linux release 3 (Soaring Falcon)

Python版本
Python 3.11.2

AKShare版本
akshare-1.13.82

接口名称及相应的调用代码
<img width="895" alt="截屏2024-05-21 20 09 11" src="https://github.com/akfamily/akshare/assets/16192201/dc110767-30bb-4e9a-b493-c300501ac97a">

接口报错的截图或描述
<img width="1505" alt="截屏2024-05-21 20 08 40" src="https://github.com/akfamily/akshare/assets/16192201/6df71e47-b285-428b-a55a-eb31bf120d2b">

期望获得的正确结果
通过东财接口获取三大报表时能正确返回结果

**Comment by albertandking** [comment]
> > 欢迎加入《数据科学实战》知识星球，交流财经数据与量化投资相关内容，
> > 详细信息参考：https://akshare.akfamily.xyz/learn.html
> 
> ## 前提
> 遇到任何问题，请先将您的 AKShare 版本升级到**最新版**，可以通过如下命令升级：
> 
> ```
> 已升级到最新版本
> ```
> 
> ## 如何提交问题
> 提交问题的同时，请提交以下相关信息，以便于解决问题
> 
> **详细描述遇到的问题**
> 
> 1. 操作系统版本，目前只支持 64 位操作系统
> 2. Python 版本，目前只支持 3.8 以上的版本
> 3. AKShare 版本，请升级到最新版
> 4. 接口的名称和相应的调用代码
> 5. 接口报错的截图或描述
> 6. 期望获得的正确结果
> 
> 操作系统 Alibaba Cloud Linux release 3 (Soaring Falcon)
> 
> Python版本 Python 3.11.2
> 
> AKShare版本 akshare-1.13.82
> 
> 接口名称及相应的调用代码 <img alt="截屏2024-05-21 20 09 11" width="895" src="https://private-user-images.githubusercontent.com/16192201/332418284-dc110767-30bb-4e9a-b493-c300501ac97a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzMDE1NzksIm5iZiI6MTcxNjMwMTI3OSwicGF0aCI6Ii8xNjE5MjIwMS8zMzI0MTgyODQtZGMxMTA3NjctMzBiYi00ZTlhLWI0OTMtYzMwMDUwMWFjOTdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDE0MjExOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0MmIxYmEyNDczN2E4NDVhNjAxOThiZjdmZDUwNDdmNWM4MDhkYTZmZmJhMjViN2M1MWJjZTgyYjBiYTc0MDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Dr0kFhf0oCi9EhWyuZRUeQfMYdIy0Jil6ETZjVIRLcs">
> 
> 接口报错的截图或描述 <img alt="截屏2024-05-21 20 08 40" width="1505" src="https://private-user-images.githubusercontent.com/16192201/332418149-6df71e47-b285-428b-a55a-eb31bf120d2b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzMDE1NzksIm5iZiI6MTcxNjMwMTI3OSwicGF0aCI6Ii8xNjE5MjIwMS8zMzI0MTgxNDktNmRmNzFlNDctYjI4NS00MjhiLWE1NWEtZWIzMWJmMTIwZDJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDE0MjExOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwMTFjYmU0YzFjNjI2MmFmM2U0ZmQxNzQ2MWM3NTYzZjE4MjJkOGE5N2JjY2YyZjJmNzQxMWM1ZDllYmE3ZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wRkj0dOemHIGns8bCIwNaBAA53IuiMRHjnw_mbP_1gk">
> 
> 期望获得的正确结果 通过东财接口获取三大报表时能正确返回结果

接口测试正常
