### ISSUE TITLE
申万行情接口 index_realtime_sw 报错

### ISSUE THREAD

**Issue by callcter** [akfamily/akshare#4896]
1. 操作系统版本，目前只支持 64 位操作系统
没问题
2. Python 版本，目前只支持 3.8 以上的版本
v3.11
3. AKShare 版本，请升级到最新版
已最新
4. 接口的名称和相应的调用代码
sw_index_c1_df = ak.index_realtime_sw(symbol="一级行业")
5. 接口报错的截图或描述
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.swhyresearch.com', port=443): Max retries exceeded with url: /institute-sw/api/index_publish/current/?page=1&page_size=50&indextype=%E4%B8%80%E7%BA%A7%E8%A1%8C%E4%B8%9A (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)')))
6. 期望获得的正确结果
正确返回结果

**Comment by albertandking** [comment]
> 1. 操作系统版本，目前只支持 64 位操作系统
>    没问题
> 2. Python 版本，目前只支持 3.8 以上的版本
>    v3.11
> 3. AKShare 版本，请升级到最新版
>    已最新
> 4. 接口的名称和相应的调用代码
>    sw_index_c1_df = ak.index_realtime_sw(symbol="一级行业")
> 5. 接口报错的截图或描述
>    urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.swhyresearch.com', port=443): Max retries exceeded with url: /institute-sw/api/index_publish/current/?page=1&page_size=50&indextype=%E4%B8%80%E7%BA%A7%E8%A1%8C%E4%B8%9A (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)')))
> 6. 期望获得的正确结果
>    正确返回结果

感谢反馈问题，已修复该问题，升级到 AKShare 1.13.84 使用

**Comment by xnw176** [comment]
申万升级反爬机制，过于频繁调用会被封IP较长时间。
