### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by gcy950912** [akfamily/akshare#4900]
**详细描述遇到的问题**
1. Win11
2. python3.11.4
3. akshare 1.13.85
4. 接口：futures_foreign_commodity_realtime报错
import akshare as ak
print(ak.futures_foreign_commodity_realtime("XAU")) #伦敦金
5. 错误定位：
网页爬到的数据不包含人名币报价，导致pd的Dataframe寻找字段错误
7. 期望获得的正确结果
返回的DataFrame去掉有关字段，或留空

**Comment by albertandking** [comment]
> 4\. futures_foreign_commodity_realtime

感谢反馈问题，已修复该问题，升级到 AKShare 1.13.86 使用
