### ISSUE TITLE
AKShare 接口问题报告 - index_analysis_daily_sw

### ISSUE THREAD

**Issue by park** [akfamily/akshare#4901]
- Ubuntu 20.04 & PopOS
- Python 3.10 & 3.10
- akshare 1.13.85

ak.index_analysis_daily_sw(symbol="一级行业", start_date="20240506", end_date="20240523")
出现错误
ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

**Comment by xnw176** [comment]
申万已对单一IP调用次数加以限制，会封IP较长时间，好像至少8小时，所以不要过量使用申万相关接口。

**Comment by albertandking** [comment]
> * Ubuntu 20.04 & PopOS
> * Python 3.10 & 3.10
> * akshare 1.13.85
> 
> ak.index_analysis_daily_sw(symbol="一级行业", start_date="20240506", end_date="20240523") 出现错误 ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

接口测试正常，按@xnw176 说的操作
