### ISSUE TITLE
AKShare 接口问题报告ak.index_detail_cni()接口报错

### ISSUE THREAD

**Issue by wangzhengli** [akfamily/akshare#4904]
> 欢迎加入《数据科学实战》知识星球，交流财经数据与量化投资相关内容，
> 详细信息参考：https://akshare.akfamily.xyz/learn.html

## 前提

遇到任何问题，请先将您的 AKShare 版本升级到**最新版**，可以通过如下命令升级：

```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

## 如何提交问题

提交问题的同时，请提交以下相关信息，以便于解决问题

**详细描述遇到的问题**

1. 操作系统版本，目前只支持 64 位操作系统
2. fedora 39
3. Python 版本，目前只支持 3.8 以上的版本
4. 3.9
5. AKShare 版本，请升级到最新版
6. 1.13.86
7. 接口的名称和相应的调用代码
8. ak.index_detail_cni(symbol='399001', date='202011')
9. 接口报错的截图或描述
10. 
![image](https://github.com/akfamily/akshare/assets/68560657/7ae204c3-1d8a-4689-ac40-9417d2212ba9)

11. 期望获得的正确结果

**Comment by wangzhengli** [comment]
相关的还有ak.index_detail_hist_cni(symbol='399005', date='202201')，ak.index_detail_hist_adjust_cni(symbol='399005')

**Comment by albertandking** [comment]
> > 欢迎加入《数据科学实战》知识星球，交流财经数据与量化投资相关内容，
> > 详细信息参考：https://akshare.akfamily.xyz/learn.html
> 
> ## 前提
> 遇到任何问题，请先将您的 AKShare 版本升级到**最新版**，可以通过如下命令升级：
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> ## 如何提交问题
> 提交问题的同时，请提交以下相关信息，以便于解决问题
> 
> **详细描述遇到的问题**
> 
> 1. 操作系统版本，目前只支持 64 位操作系统
> 2. fedora 39
> 3. Python 版本，目前只支持 3.8 以上的版本
> 4. 3.9
> 5. AKShare 版本，请升级到最新版
> 6. 1.13.86
> 7. 接口的名称和相应的调用代码
> 8. ak.index_detail_cni(symbol='399001', date='202011')
> 9. 接口报错的截图或描述
> 
> ![image](https://private-user-images.githubusercontent.com/68560657/333772254-7ae204c3-1d8a-4689-ac40-9417d2212ba9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3OTU5OTgsIm5iZiI6MTcxNjc5NTY5OCwicGF0aCI6Ii82ODU2MDY1Ny8zMzM3NzIyNTQtN2FlMjA0YzMtMWQ4YS00Njg5LWFjNDAtOTQxN2QyMjEyYmE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDA3NDEzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyYmY1ZTFmM2YyODUxMzE4MDViYzFkMDBjNGQ4M2M4MDQ2NjIzNTM5Y2FlMDYyODc1M2JhYzE5YjViODMzYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rYZGYkHzj5kVQ47CMOSUjaL0CfliR2sy0xRMqlD0pQ8)
> 
> 11. 期望获得的正确结果

感谢反馈问题，已修复该问题，升级到 AKShare 1.13.87 使用
