### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by ElShaarawyS** [akfamily/akshare#4908]
python 版本3.11.3
AKShare 版本 1.13.87

接口 ak.bond_china_close_return() 报错 KeyError: 'newDateValue'
![1716808298295](https://github.com/akfamily/akshare/assets/150638553/8163e515-821e-4f41-af53-256b4d78f0c2)
![1716808375636](https://github.com/akfamily/akshare/assets/150638553/089e8df8-1521-4447-98ce-c30e3077b080)

**Comment by albertandking** [comment]
> bond_china_close_return

按文档获取

**Comment by ElShaarawyS** [comment]
> > bond_china_close_return
> 
> 按文档获取

我的图片里就是复制的文档里的示例
