### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by liningbo** [akfamily/akshare#4910]
python 3.8 
akshare版本  ：1.1.68
接口：index_detail_hist_cni 
报错信息：
ValueError: Length mismatch: Expected axis has 10 elements, new values have 11 elements

**Comment by albertandking** [comment]
> python 3.8 akshare版本 ：1.1.68 接口：index_detail_hist_cni 报错信息： ValueError: Length mismatch: Expected axis has 10 elements, new values have 11 elements

接口正常；升级到最新版使用
