### ISSUE TITLE
ak.stock_zh_index_daily(symbol="sh000005") 获取数据异常，只能获取到5月24日

### ISSUE THREAD

**Issue by Hanyu96** [akfamily/akshare#4912]
import akshare as ak
df = ak.stock_zh_index_daily(symbol="sh000005")

**Comment by albertandking** [comment]
> import akshare as ak df = ak.stock_zh_index_daily(symbol="sh000005")

接口测试正常

**Comment by Hanyu96** [comment]
> > import akshare as ak df = ak.stock_zh_index_daily(symbol="sh000005")
> 
> 接口测试正常

能正常获取到5月27号的数据吗
