### ISSUE TITLE
AKShare 接口问题报告：stock_zt_pool_em_df 报错Length mismatch

### ISSUE THREAD

**Issue by zhengbcao** [akfamily/akshare#4914]
**详细描述遇到的问题**

1. 详细阅读文档对应接口的使用方式：https://akshare.akfamily.xyz
2. 操作系统版本，目前只支持 64 位操作系统
3. Python 版本，目前只支持 3.8 以上的版本
4. AKShare 版本，请升级到最新版
5. 接口的名称和相应的调用代码
6. 接口报错的截图或描述
7. 期望获得的正确结果

![image](https://github.com/akfamily/akshare/assets/115263158/6b6be2b8-a36e-46e0-a047-8c4beb7350ea)

环境
最新版本akshare

代码：
import akshare as ak
stock_zt_pool_em_df = ak.stock_zt_pool_em(date='20240525')
print(stock_zt_pool_em_df)

报错信息：
ValueError: Length mismatch: Expected axis has 1 elements, new values have 17 elements

**Comment by albertandking** [comment]
> stock_zt_pool_em

接口正常
