### ISSUE TITLE
期望支持A股关键指标获取

### ISSUE THREAD

**Issue by voguke** [akfamily/akshare#4915]
目前AKshare支持使用stock_zh_valuation_baidu从百度股市通获取估值指标，包含：总市值, 市盈率(TTM), 市盈率(静), 市净率, 市现率。

百度股市通同时提供关键指标https://gushitong.baidu.com/stock/ab-002044，
包含：ROE，ROA，每股收益，每股净资产毛利率，负债率，每股现金流净利润率指标。

这些指标较为常用，目前AKshare没有直接的接口提供，需要自行计算。能否提供类似于stock_zh_valuation_baidu的接口获取这些关键指标？

感谢AKshare工程师！

**Comment by albertandking** [comment]
> 关键指标

已有相关数据接口
