### ISSUE TITLE
申万一级行业网页实时行情缺失

### ISSUE THREAD

**Issue by wongkasing** [akfamily/akshare#4916]
今天引用申万宏源研究的申万指数实时行情，接口是 index_realtime_sw，
打印结果只有29个行业，缺失了两个行业。
查看申万宏源研究官网，发现是网页上也是缺失的。（31个行业，应该分4页，页面中只有3页）
![申万一级行业实时行情缺失](https://github.com/akfamily/akshare/assets/105487013/4f54c448-c314-4159-9e20-e23d21506e09)

所以我在想能不能改到从分时行情接口 index_min_sw 的目标地址上去获取实时行情；

**Comment by albertandking** [comment]
> 今天引用申万宏源研究的申万指数实时行情，接口是 index_realtime_sw， 打印结果只有29个行业，缺失了两个行业。 查看申万宏源研究官网，发现是网页上也是缺失的。（31个行业，应该分4页，页面中只有3页） ![申万一级行业实时行情缺失](https://private-user-images.githubusercontent.com/105487013/334751016-4f54c448-c314-4159-9e20-e23d21506e09.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNjAxODksIm5iZiI6MTcxNzA1OTg4OSwicGF0aCI6Ii8xMDU0ODcwMTMvMzM0NzUxMDE2LTRmNTRjNDQ4LWMzMTQtNDE1OS05ZTIwLWUyM2QyMTUwNmUwOS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMFQwOTA0NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mOTkwMjJjZWE0YWIxYzIxZjI3YTg1NDg1MDYxMTljNmRjMTlmY2Q3NWVmYzdmMzc1ZWFiOGE5OWIwNDc5MjE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.euOUsO9Qapp2Ualybc7MuSc_it7wm2q2kIz7Hyuxn6g)
> 
> 所以我在想能不能改到从分时行情接口 index_min_sw 的目标地址上去获取实时行情；

保持与目标网站一致
