### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by EnergeticMrMask** [akfamily/akshare#4922]
> 欢迎加入《数据科学实战》知识星球，交流财经数据与量化投资相关内容，
> 详细信息参考：https://akshare.akfamily.xyz/learn.html

## 前提

遇到任何问题，请先将您的 AKShare 版本升级到**最新版**，可以通过如下命令升级：

```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

## 如何提交问题

提交问题的同时，请提交以下相关信息，以便于解决问题

**详细描述遇到的问题**

1. 详细阅读文档对应接口的使用方式：https://akshare.akfamily.xyz
2. 操作系统版本，目前只支持 64 位操作系统
win11
3. Python 版本，目前只支持 3.8 以上的版本
3.11.9
4. AKShare 版本，请升级到最新版
![image](https://github.com/akfamily/akshare/assets/93405923/75ce0aea-3f79-4439-93d5-7a611f594a12)

5. 接口的名称和相应的调用代码
6. 接口报错的截图或描述
<img width="641" alt="屏幕截图 2024-06-04 164146" src="https://github.com/akfamily/akshare/assets/93405923/e6615c7a-386d-476e-be9b-4933f072f7e5">
7. 期望获得的正确结果

**Comment by albertandking** [comment]
> > 欢迎加入《数据科学实战》知识星球，交流财经数据与量化投资相关内容，
> > 详细信息参考：https://akshare.akfamily.xyz/learn.html
> 
> ## 前提
> 遇到任何问题，请先将您的 AKShare 版本升级到**最新版**，可以通过如下命令升级：
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> ## 如何提交问题
> 提交问题的同时，请提交以下相关信息，以便于解决问题
> 
> **详细描述遇到的问题**
> 
> 1. 详细阅读文档对应接口的使用方式：https://akshare.akfamily.xyz
> 2. 操作系统版本，目前只支持 64 位操作系统
>    win11
> 3. Python 版本，目前只支持 3.8 以上的版本
>    3.11.9
> 4. AKShare 版本，请升级到最新版
>    ![image](https://private-user-images.githubusercontent.com/93405923/336375403-75ce0aea-3f79-4439-93d5-7a611f594a12.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1MDA2MjIsIm5iZiI6MTcxNzUwMDMyMiwicGF0aCI6Ii85MzQwNTkyMy8zMzYzNzU0MDMtNzVjZTBhZWEtM2Y3OS00NDM5LTkzZDUtN2E2MTFmNTk0YTEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDExMjUyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxMTE3MmMzZjJkZDIyM2Y5NzljYzBiZmQ0NDViMmRhN2YwN2VjMWFkNjRhNzEyYjI4YWQyZjRmMjBlN2EzMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vEnJ7_ctLxDOG85wbn_FG-YXQeR-oM3876XIVBM2Hjo)
> 5. 接口的名称和相应的调用代码
> 6. 接口报错的截图或描述
> 
> <img alt="屏幕截图 2024-06-04 164146" width="641" src="https://private-user-images.githubusercontent.com/93405923/336374622-e6615c7a-386d-476e-be9b-4933f072f7e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1MDA2MjIsIm5iZiI6MTcxNzUwMDMyMiwicGF0aCI6Ii85MzQwNTkyMy8zMzYzNzQ2MjItZTY2MTVjN2EtMzg2ZC00NzZlLWJlOWItNDkzM2YwNzJmN2U1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDExMjUyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3OGFkMjZhODE2Y2UzMzJhMzA5MjcwMTVlZmM5OGQwOWZjMjVjMDJmNDIzNzMzZjM4ZjM1NmMwNzk1N2MwZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BtpSI6RE0Qw-tzz6s4JwX35nvvdQr2M7AIQjJFVl5tY"> 7. 期望获得的正确结果

已修复，升级到 AKShare 1.13.94 使用
