### ISSUE TITLE
macro_china_nbs_nation_df的问题

### ISSUE THREAD

**Issue by raphaelxiao** [akfamily/akshare#4923]
调用国家统计局接口
macro_china_nbs_nation_df = ak.macro_china_nbs_nation(kind="月度数据", path="工业 > 工业企业主要经济指标", period="1949-")
print(macro_china_nbs_nation_df)

会提示

Traceback (most recent call last):
  File "c:\Users\Raphael\Desktop\Developer\IntelData\body\data\nbs\test.py", line 3, in <module>
    macro_china_nbs_nation_df = ak.macro_china_nbs_nation(kind="月度数据", path="工业 > 工业企业主要经济指标", period="1949-")
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Raphael\.conda\envs\IntelData\Lib\site-packages\akshare\economic\macro_china_nbs.py", line 139, in macro_china_nbs_nation
    data_ndarray = np.reshape(temp_df["data"], (len(row_name), len(column_name)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Raphael\.conda\envs\IntelData\Lib\site-packages\numpy\core\fromnumeric.py", line 285, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Raphael\.conda\envs\IntelData\Lib\site-packages\numpy\core\fromnumeric.py", line 56, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Raphael\.conda\envs\IntelData\Lib\site-packages\numpy\core\fromnumeric.py", line 45, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: cannot reshape array of size 25559 into shape (76,497)

是因为数据量太大了么？

**Comment by albertandking** [comment]
> 调用国家统计局接口 macro_china_nbs_nation_df = ak.macro_china_nbs_nation(kind="月度数据", path="工业 > 工业企业主要经济指标", period="1949-") print(macro_china_nbs_nation_df)
> 
> 会提示
> 
> Traceback (most recent call last): File "c:\Users\Raphael\Desktop\Developer\IntelData\body\data\nbs\test.py", line 3, in macro_china_nbs_nation_df = ak.macro_china_nbs_nation(kind="月度数据", path="工业 > 工业企业主要经济指标", period="1949-") ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\Raphael.conda\envs\IntelData\Lib\site-packages\akshare\economic\macro_china_nbs.py", line 139, in macro_china_nbs_nation data_ndarray = np.reshape(temp_df["data"], (len(row_name), len(column_name))) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\Raphael.conda\envs\IntelData\Lib\site-packages\numpy\core\fromnumeric.py", line 285, in reshape return _wrapfunc(a, 'reshape', newshape, order=order) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\Raphael.conda\envs\IntelData\Lib\site-packages\numpy\core\fromnumeric.py", line 56, in _wrapfunc return _wrapit(obj, method, *args, **kwds) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\Raphael.conda\envs\IntelData\Lib\site-packages\numpy\core\fromnumeric.py", line 45, in _wrapit result = getattr(asarray(obj), method)(*args, **kwds) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ValueError: cannot reshape array of size 25559 into shape (76,497)
> 
> 是因为数据量太大了么？

是的
