### ISSUE TITLE
stock_fhps_detail_em调用报错

### ISSUE THREAD

**Issue by Dnastar16** [akfamily/akshare#4926]
使用stock_fhps_detail_em获取股票分红信息时有时会报错，debug发现问题出在下面这段code:
    r = requests.get(url, params=params)
    data_json = r.json()
    total_pages = int(data_json["result"]["pages"])
如果所输入股票代码返回不到相应分红信息时会报错：
    total_pages = int(data_json["result"]["pages"])
   TypeError: 'NoneType' object is not subscriptable

可用下面code重现问题：    div_tmp = ak.stock_fhps_detail_em(symbol=“000005”)

希望即使没有分红信息也可以返回空的DataFrame ，目前暂时做了下面调整避免报错：
    r = requests.get(url, params=params)
    data_json = r.json()
    if data_json["code"] != "0":
        print("Could not get information for" + symbol)
        return pd.DataFrame()
    total_pages = int(data_json["result"]["pages"])

期望新版改进。

**Comment by albertandking** [comment]
> 使用stock_fhps_detail_em获取股票分红信息时有时会报错，debug发现问题出在下面这段code: r = requests.get(url, params=params) data_json = r.json() total_pages = int(data_json["result"]["pages"]) 如果所输入股票代码返回不到相应分红信息时会报错： total_pages = int(data_json["result"]["pages"]) TypeError: 'NoneType' object is not subscriptable
> 
> 可用下面code重现问题： div_tmp = ak.stock_fhps_detail_em(symbol=“000005”)
> 
> 希望即使没有分红信息也可以返回空的DataFrame ，目前暂时做了下面调整避免报错： r = requests.get(url, params=params) data_json = r.json() if data_json["code"] != "0": print("Could not get information for" + symbol) return pd.DataFrame() total_pages = int(data_json["result"]["pages"])
> 
> 期望新版改进。

目前接口是正常的；没有数据默认返回是报错的，可以在本地 try...except 处理
