### ISSUE TITLE
巨潮资讯接口问题报告

### ISSUE THREAD

**Issue by EnergeticMrMask** [akfamily/akshare#4927]
1. 详细阅读文档对应接口的使用方式：https://akshare.akfamily.xyz
2. 操作系统版本，目前只支持 64 位操作系统
win11
3. Python 版本，目前只支持 3.8 以上的版本
3.11.9
4. AKShare 版本，请升级到最新版
1.13.94
5. 接口的名称和相应的调用代码
6. 接口报错的截图或描述
![image](https://github.com/akfamily/akshare/assets/93405923/10f2fa1b-d6ac-453e-9282-32446703a945)
## 巨潮资讯相关的接口可能都有同样的问题，昨天是stock_share_change_cninfo，今天是stock_profile_cninfo，我还挑了ak.stock_allotment_cninfo(symbol="600030", start_date="19900101", end_date="20221008")试验，报错一致。
7. 期望获得的正确结果

**Comment by albertandking** [comment]
> 1. 详细阅读文档对应接口的使用方式：https://akshare.akfamily.xyz
> 2. 操作系统版本，目前只支持 64 位操作系统
>    win11
> 3. Python 版本，目前只支持 3.8 以上的版本
>    3.11.9
> 4. AKShare 版本，请升级到最新版
>    1.13.94
> 5. 接口的名称和相应的调用代码
> 6. 接口报错的截图或描述
>    ![image](https://private-user-images.githubusercontent.com/93405923/336731873-10f2fa1b-d6ac-453e-9282-32446703a945.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NjcxMzksIm5iZiI6MTcxNzY2NjgzOSwicGF0aCI6Ii85MzQwNTkyMy8zMzY3MzE4NzMtMTBmMmZhMWItZDZhYy00NTNlLTkyODItMzI0NDY3MDNhOTQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDA5NDAzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiNzYzNWQwZTZhYjgxNTUyNTdjZDc1MWJiMDY0ZTViMzY5NzMzODEzNThmYWYyNWRjMGNjOTNhNWRlMmEwNjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Qc5dT7kRB4cmg-b8IU9F3iKjNO8RsNXalfLPcxcbDcA)
> 
> ## 巨潮资讯相关的接口可能都有同样的问题，昨天是stock_share_change_cninfo，今天是stock_profile_cninfo，我还挑了ak.stock_allotment_cninfo(symbol="600030", start_date="19900101", end_date="20221008")试验，报错一致。
> 7. 期望获得的正确结果

已修复该问题，升级到 AKShare 1.13.96 使用
