### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by kvleezli** [akfamily/akshare#4932]
**详细描述遇到的问题**

请问类似“stock_financial_analysis_indicator”获取关键信息的接口，是否可以返回一个public date？
否则很容易引入未来数据吧？目前我想到的是获取季频快报数据 ，里面有pubdate，再计算，有些复杂；

**Comment by albertandking** [comment]
> stock_financial_analysis_indicator

没有相关字段
