### ISSUE TITLE
下载财务数据时，去除进度条的建议

### ISSUE THREAD

**Issue by garyLiuxh** [akfamily/akshare#4941]
显示进度条，对于批量下载时，由于日志太多，显示并不友好。

![图片](https://github.com/akfamily/akshare/assets/78151537/04a13a14-c564-48d2-b7c3-e460dcd44aa2)

**Comment by albertandking** [comment]
> 显示进度条，对于批量下载时，由于日志太多，显示并不友好。
> 
> ![图片](https://private-user-images.githubusercontent.com/78151537/338595176-04a13a14-c564-48d2-b7c3-e460dcd44aa2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNTUyMTYsIm5iZiI6MTcxODM1NDkxNiwicGF0aCI6Ii83ODE1MTUzNy8zMzg1OTUxNzYtMDRhMTNhMTQtYzU2NC00OGQyLWI3YzMtZTQ2MGRjZDQ0YWEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDA4NDgzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmZDNiMzlmM2RhOWYxN2E0OTYwYTZjODg4ZmExNmFkZTZkOTU3NGYyOGVkYzUxOGFjNTYzNzM3MWFhZGU4NTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FtF5wwjKzQGFTNLTU1xgZl2Sm06YC0a5PugOqw-DYmg)

按量调取
