### ISSUE TITLE
外盘-品种代码表 输出参数新增字段建议

### ISSUE THREAD

**Issue by zhangbyes** [akfamily/akshare#4942]
外盘-品种代码表
接口: futures_hq_subscribe_exchange_symbol
目标地址: https://finance.sina.com.cn/money/future/hf.html

该接口可以加上基本资料内的：交易品种、交易单位、报价单位、上市交易所

**Comment by albertandking** [comment]
> 外盘-品种代码表 接口: futures_hq_subscribe_exchange_symbol 目标地址: https://finance.sina.com.cn/money/future/hf.html
> 
> 该接口可以加上基本资料内的：交易品种、交易单位、报价单位、上市交易所

已有相关接口
