### ISSUE TITLE
AKShare 接口问题报告 - stock_board_cons_ths访问403

### ISSUE THREAD

**Issue by xiongyifan** [akfamily/akshare#4946]
接口名称：stock_board_cons_ths
调用代码：```stock_board_cons_ths_df = stock_board_cons_ths(symbol="881121")```
接口报错：stock_board_cons_ths.py的第382行，请求报403
期望结果：正常请求

我尝试了一下操作：
1. 浏览器直接访问url，访问正常。
```
https://q.10jqka.com.cn/thshy/detail/field/199112/order/desc/page/1/ajax/1/code/881121
```
2. 将浏览器中的Cookie替换到代码中的v_code变量中，第382行访问正常，但会在后面循环中报403，可能是因为v_code在循环中会生成新的，所以写死会导致后面报错。

**Comment by slzheng2017** [comment]
同样，昨晚开始就不行了。有人解决了吗

**Comment by albertandking** [comment]
> 接口名称：stock_board_cons_ths 调用代码：`stock_board_cons_ths_df = stock_board_cons_ths(symbol="881121")` 接口报错：stock_board_cons_ths.py的第382行，请求报403 期望结果：正常请求
> 
> 我尝试了一下操作：
> 
> 1. 浏览器直接访问url，访问正常。
> 
> ```
> https://q.10jqka.com.cn/thshy/detail/field/199112/order/desc/page/1/ajax/1/code/881121
> ```
> 
> 2. 将浏览器中的Cookie替换到代码中的v_code变量中，第382行访问正常，但会在后面循环中报403，可能是因为v_code在循环中会生成新的，所以写死会导致后面报错。

目前测试应该是目标网站的问题

**Comment by xiongyifan** [comment]
替换cookie就能访问，是不是cookie生成规则发生了变化啊？

**Comment by divefox** [comment]
感觉是同花顺网站规则变了，stock_board_concept_name_ths这个接口也不行了

**Comment by akshare0613** [comment]
我用旧版本的代码试了下，跑不通了，大概率是同花顺网站规则变了，辛苦开发帮忙维护下

**Comment by XX-Trader** [comment]
我调试了接口，应该是有cookies的验证，如果没有cookies会先进入这个页面，然后cookies里面会生成一个参数v，有这个cookies就能访问了，但是目前这个地址返回的是混淆后的代码，有没有高手逆向下http://s.thsi.cn/js/chameleon/chameleon.1.6.min.1718269.js

**Comment by albertandking** [comment]
目前不能调用该数据，会移除相关接口

**Comment by g3wang** [comment]
这里存在两个问题：
1. 同花顺概念代码，需要替换成内部代码, 比如885611 阿里巴巴概念, 对应的cid：301558，这样网址是：https://q.10jqka.com.cn/gn/detail/field/199112/order/desc/page/1/ajax/1/code/301558，这个网页是可以打开的。
2. 动态cookie会在访问多次网页会更换，而一般一个概念成分股需要超过6个网页，这样就会因为cookie改变而出问题。
希望高手有办法，谢谢！

**Comment by XX-Trader** [comment]
打开第6页开始，就需要登录了，登录后的coookies可以保存7天，这期间，参数不会变。还有个参数v，是变化的，没有办法解决。登录方面还需要过滑块验证，也非常有难度（可手动登录后复制cookies）。
不过我自己调试了下接口，只要访问频率过快，就算是网页中点下一页，很多时候都打不开，提示错误码401未授权。
目前能想到的方式，
1、就是用selenium存储cookies，写方法去读取。
2、降低访问ths接口的频率
3、获取板块的K线数据，直接改成传板块的代码，不传名称，去掉开头的获取所有板块信息（进一步降低访问频率）

**Comment by franktrue** [comment]
> 目前不能调用该数据，会移除相关接口

这个接口废弃了吗？目前同花顺板块相关的API均报错。
<img width="1134" alt="image" src="https://github.com/akfamily/akshare/assets/10108380/87b7ac6d-c61c-45c6-92a2-d825718635fc">
