### ISSUE TITLE
最新版本1.14 stock_board_industry_cons_ths 接口报错

### ISSUE THREAD

**Issue by themoneyevo** [akfamily/akshare#4951]
使用最新版本1.14.2，调用接口stock_board_industry_cons_ths ，返回错误
···
ValueError: No tables found
···

**Comment by albertandking** [comment]
目前不能调用该数据，会移除相关接口

**Comment by themoneyevo** [comment]
还会有板块及板块对用的个股的数据结构吗？

**Comment by forvenus** [comment]
> 后续还有提供板块及板块对应个股的接口吗？

同问，不行转tushare了
