### ISSUE TITLE
stock_board_cons_ths函数报错

### ISSUE THREAD

**Issue by xiaopge** [akfamily/akshare#4965]
warnings.warn(
Traceback (most recent call last):
  File "E:\quant\sbTrade\example\查个股所属行业.py", line 40, in <module>
    df1 = ak.stock_board_cons_ths(symbol="881121")
  File "E:\quant\sbTrade\venv\lib\site-packages\akshare\stock_feature\stock_board_concept_ths.py", line 406, in stock_board_cons_ths
    temp_df = pd.read_html(StringIO(r.text))[0]
  File "E:\quant\sbTrade\venv\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "E:\quant\sbTrade\venv\lib\site-packages\pandas\io\html.py", line 1098, in read_html
    return _parse(
  File "E:\quant\sbTrade\venv\lib\site-packages\pandas\io\html.py", line 926, in _parse
    raise retained
  File "E:\quant\sbTrade\venv\lib\site-packages\pandas\io\html.py", line 906, in _parse
    tables = p.parse_tables()
  File "E:\quant\sbTrade\venv\lib\site-packages\pandas\io\html.py", line 222, in parse_tables
    tables = self._parse_tables(self._build_doc(), self.match, self.attrs)
  File "E:\quant\sbTrade\venv\lib\site-packages\pandas\io\html.py", line 552, in _parse_tables
    raise ValueError("No tables found")
ValueError: No tables found
大佬，似乎返回数据没拿到

**Comment by albertandking** [comment]
> warnings.warn( Traceback (most recent call last): File "E:\quant\sbTrade\example\查个股所属行业.py", line 40, in df1 = ak.stock_board_cons_ths(symbol="881121") File "E:\quant\sbTrade\venv\lib\site-packages\akshare\stock_feature\stock_board_concept_ths.py", line 406, in stock_board_cons_ths temp_df = pd.read_html(StringIO(r.text))[0] File "E:\quant\sbTrade\venv\lib\site-packages\pandas\util_decorators.py", line 311, in wrapper return func(*args, **kwargs) File "E:\quant\sbTrade\venv\lib\site-packages\pandas\io\html.py", line 1098, in read_html return _parse( File "E:\quant\sbTrade\venv\lib\site-packages\pandas\io\html.py", line 926, in _parse raise retained File "E:\quant\sbTrade\venv\lib\site-packages\pandas\io\html.py", line 906, in _parse tables = p.parse_tables() File "E:\quant\sbTrade\venv\lib\site-packages\pandas\io\html.py", line 222, in parse_tables tables = self._parse_tables(self._build_doc(), self.match, self.attrs) File "E:\quant\sbTrade\venv\lib\site-packages\pandas\io\html.py", line 552, in _parse_tables raise ValueError("No tables found") ValueError: No tables found 大佬，似乎返回数据没拿到

参见说明文档

**Comment by xiaopge** [comment]
大佬，你的案例也没跑通，我没修改过你的代码啊




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Albert ***@***.***&gt;; 
发送时间: 2024年6月18日(星期二) 晚上6:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [akfamily/akshare] stock_board_cons_ths函数报错 (Issue #4965)





  
warnings.warn( Traceback (most recent call last): File "E:\quant\sbTrade\example\查个股所属行业.py", line 40, in df1 = ak.stock_board_cons_ths(symbol="881121") File "E:\quant\sbTrade\venv\lib\site-packages\akshare\stock_feature\stock_board_concept_ths.py", line 406, in stock_board_cons_ths temp_df = pd.read_html(StringIO(r.text))[0] File "E:\quant\sbTrade\venv\lib\site-packages\pandas\util_decorators.py", line 311, in wrapper return func(*args, **kwargs) File "E:\quant\sbTrade\venv\lib\site-packages\pandas\io\html.py", line 1098, in read_html return _parse( File "E:\quant\sbTrade\venv\lib\site-packages\pandas\io\html.py", line 926, in _parse raise retained File "E:\quant\sbTrade\venv\lib\site-packages\pandas\io\html.py", line 906, in _parse tables = p.parse_tables() File "E:\quant\sbTrade\venv\lib\site-packages\pandas\io\html.py", line 222, in parse_tables tables = self._parse_tables(self._build_doc(), self.match, self.attrs) File "E:\quant\sbTrade\venv\lib\site-packages\pandas\io\html.py", line 552, in _parse_tables raise ValueError("No tables found") ValueError: No tables found 大佬，似乎返回数据没拿到
  
参见说明文档
 
&mdash;
