### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by jasonlic** [akfamily/akshare#4967]
> 欢迎加入《数据科学实战》知识星球，交流财经数据与量化投资相关内容，
> 详细信息参考：https://akshare.akfamily.xyz/learn.html

## 前提

遇到任何问题，请先将您的 AKShare 版本升级到**最新版**，可以通过如下命令升级：

```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

## 如何提交问题

提交问题的同时，请提交以下相关信息，以便于解决问题

**详细描述遇到的问题**
stock_industry_pe_ratio_cninfo 函数错误。
http://webapi.cninfo.com.cn/api/sysapi/p_sysapi1087 返回错误

1. 详细阅读文档对应接口的使用方式：https://akshare.akfamily.xyz
2. 操作系统版本，目前只支持 64 位操作系统
3. Python 版本，目前只支持 3.8 以上的版本
4. AKShare 版本，请升级到最新版
5. 接口的名称和相应的调用代码
6. 接口报错的截图或描述
7. 期望获得的正确结果

**Comment by albertandking** [comment]
> > 欢迎加入《数据科学实战》知识星球，交流财经数据与量化投资相关内容，
> > 详细信息参考：https://akshare.akfamily.xyz/learn.html
> 
> ## 前提
> 遇到任何问题，请先将您的 AKShare 版本升级到**最新版**，可以通过如下命令升级：
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> ## 如何提交问题
> 提交问题的同时，请提交以下相关信息，以便于解决问题
> 
> **详细描述遇到的问题** stock_industry_pe_ratio_cninfo 函数错误。 http://webapi.cninfo.com.cn/api/sysapi/p_sysapi1087 返回错误
> 
> 1. 详细阅读文档对应接口的使用方式：https://akshare.akfamily.xyz
> 2. 操作系统版本，目前只支持 64 位操作系统
> 3. Python 版本，目前只支持 3.8 以上的版本
> 4. AKShare 版本，请升级到最新版
> 5. 接口的名称和相应的调用代码
> 6. 接口报错的截图或描述
> 7. 期望获得的正确结果

接口正常，只能获取近期的数据
