### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by tcil718** [akfamily/akshare#4968]
> 欢迎加入《数据科学实战》知识星球，交流财经数据与量化投资相关内容，
> 详细信息参考：https://akshare.akfamily.xyz/learn.html

## 前提

遇到任何问题，请先将您的 AKShare 版本升级到**最新版**，可以通过如下命令升级：

```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

## 如何提交问题

提交问题的同时，请提交以下相关信息，以便于解决问题

**详细描述遇到的问题**

1. 详细阅读文档对应接口的使用方式：https://akshare.akfamily.xyz
2. 操作系统版本，目前只支持 64 位操作系统
3. Python 版本，目前只支持 3.8 以上的版本
4. AKShare 版本，请升级到最新版
以上都符合
6. 接口的名称和相应的调用代码
实时行情数据[](https://akshare.akfamily.xyz/data/bond/bond.html#id17)
接口: bond_zh_hs_spot

目标地址: https://vip.stock.finance.sina.com.cn/mkt/#hs_z

描述: 新浪财经-债券-沪深债券-实时行情数据

限量: 单次返回所有沪深债券的实时行情数据
8. 接口报错的截图或描述

Exception has occurred: JSONDecodeError
Can not decode value starting with character '<'

10. 期望获得的正确结果
希望查明报错原因，并修正

**Comment by albertandking** [comment]
> > 欢迎加入《数据科学实战》知识星球，交流财经数据与量化投资相关内容，
> > 详细信息参考：https://akshare.akfamily.xyz/learn.html
> 
> ## 前提
> 遇到任何问题，请先将您的 AKShare 版本升级到**最新版**，可以通过如下命令升级：
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> ## 如何提交问题
> 提交问题的同时，请提交以下相关信息，以便于解决问题
> 
> **详细描述遇到的问题**
> 
> 1. 详细阅读文档对应接口的使用方式：https://akshare.akfamily.xyz
> 2. 操作系统版本，目前只支持 64 位操作系统
> 3. Python 版本，目前只支持 3.8 以上的版本
> 4. AKShare 版本，请升级到最新版
>    以上都符合
> 5. 接口的名称和相应的调用代码
>    实时行情数据[](https://akshare.akfamily.xyz/data/bond/bond.html#id17)
>    接口: bond_zh_hs_spot
> 
> 目标地址: https://vip.stock.finance.sina.com.cn/mkt/#hs_z
> 
> 描述: 新浪财经-债券-沪深债券-实时行情数据
> 
> 限量: 单次返回所有沪深债券的实时行情数据 8. 接口报错的截图或描述
> 
> Exception has occurred: JSONDecodeError Can not decode value starting with character '<'
> 
> 10. 期望获得的正确结果
>     希望查明报错原因，并修正

已在文档新增相关筛选的参数，可以通过参数来分批获取
