### ISSUE TITLE
建议更新Python依赖

### ISSUE THREAD

**Issue by zx31415** [akfamily/akshare#4969]
py-mini-racer包已不再更新，linux系统下易出现libmini_racer.glibc.so丢失问题，需手动解决。

2024年3月PyMiniRacer有了新的fork，并开始常规更新：https://github.com/bpcreech/PyMiniRacer

建议将Python依赖更换为新PyPI包 mini-racer。

**Comment by albertandking** [comment]
> py-mini-racer包已不再更新，linux系统下易出现libmini_racer.glibc.so丢失问题，需手动解决。
> 
> 2024年3月PyMiniRacer有了新的fork，并开始常规更新：https://github.com/bpcreech/PyMiniRacer
> 
> 建议将Python依赖更换为新PyPI包 mini-racer。

libmini_racer.glibc.so 目前依赖 akracer 来获取，近期测试未发现相关问题；感谢提供新的 fork 库，后续稳定后考虑切换过来

**Comment by albertandking** [comment]
> py-mini-racer包已不再更新，linux系统下易出现libmini_racer.glibc.so丢失问题，需手动解决。
> 
> 2024年3月PyMiniRacer有了新的fork，并开始常规更新：https://github.com/bpcreech/PyMiniRacer
> 
> 建议将Python依赖更换为新PyPI包 mini-racer。

已修复，升级到 AKShare 1.14.37 使用，感谢反馈新的依赖库
