### ISSUE TITLE
同花顺板块成分股接口 无法获取数据

### ISSUE THREAD

**Issue by WhiteK0912** [akfamily/akshare#4974]
疑似同花顺修改了相关接口

stock_board_cons_ths_df = ak.stock_board_cons_ths(symbol="885611")
print(stock_board_cons_ths_df)

![QQ20240619-165808](https://github.com/akfamily/akshare/assets/106294721/2fec76b3-3174-4d8d-80ba-ac497c5ed6bf)

**Comment by albertandking** [comment]
> 疑似同花顺修改了相关接口
> 
> stock_board_cons_ths_df = ak.stock_board_cons_ths(symbol="885611") print(stock_board_cons_ths_df)
> 
> ![QQ20240619-165808](https://private-user-images.githubusercontent.com/106294721/341001308-2fec76b3-3174-4d8d-80ba-ac497c5ed6bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4MDkwMTMsIm5iZiI6MTcxODgwODcxMywicGF0aCI6Ii8xMDYyOTQ3MjEvMzQxMDAxMzA4LTJmZWM3NmIzLTMxNzQtNGQ4ZC04MGJhLWFjNDk3YzVlZDZiZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOVQxNDUxNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NWY4ZWRiYjNjNWZjNDJlODYwMmE1ODNkMTY3MzliZGE2NmFkODliMWRkYmNkYTEzZmY0YmE0MThmM2E1MmEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lQgQCBRNuLBnEzst9q6G8IHymNBevkSfgYYbrqlMjUA)

参见接口文档
