### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by lilaboc** [akfamily/akshare#4980]
fund_etf_spot_em 这个函数是取自东财, 但是东财的数据只有937个, 一些etf比如豆粕etf(159985)都没有
而同花顺 https://fund.10jqka.com.cn/datacenter/sy/kfs/etf/ 的接口 https://fund.10jqka.com.cn/data/Net/info/ETF_F009_desc_0_0_1_9999_0_0_0_jsonp_g.html
可以拿到984条数据, 个人感觉比东财靠谱
我给东财打过电话报bug, 但是接电话的人明显不懂我是在说啥

可不可以新加一个函数?

**Comment by albertandking** [comment]
> fund_etf_spot_em 这个函数是取自东财, 但是东财的数据只有937个, 一些etf比如豆粕etf(159985)都没有 而同花顺 https://fund.10jqka.com.cn/datacenter/sy/kfs/etf/ 的接口 https://fund.10jqka.com.cn/data/Net/info/ETF_F009_desc_0_0_1_9999_0_0_0_jsonp_g.html 可以拿到984条数据, 个人感觉比东财靠谱 我给东财打过电话报bug, 但是接电话的人明显不懂我是在说啥
> 
> 可不可以新加一个函数?

已新增 fund_etf_spot_ths 接口，升级到 AKShare 1.14.13 使用

**Comment by lilaboc** [comment]
感谢!
