### ISSUE TITLE
获取同花顺概念板块成分股接口-蠢办法修改后可正常访问的建议

### ISSUE THREAD

**Issue by tiaolaidage** [akfamily/akshare#4984]
ak.stock_board_cons_ths(symbol=‘881158‘)

我python水平比较菜，看不懂源码中的cookies那个语句，但问题似乎是出在cookies那里；
我通过手工添加我在浏览器里复制出来的cookie到源码中，可以正常访问，需要的朋友可以**救个急**；
原本的代码比较高级在我能力之外，**我这个笨办法不是个长久之计**

![微信截图_20240622040230](https://github.com/akfamily/akshare/assets/123301773/3847b76e-f3ca-4333-ad14-890aadbede9f)

只是好像现在同花顺对这块是不是有一些更严格的管理，访问频率被压的很低，稍微频繁一点就又会返回空值

原本的代码获得cookies的方式有点高级（代码小白实不敢妄测），瞎说之处请多原谅（抱拳）

**Comment by albertandking** [comment]
> ak.stock_board_cons_ths(symbol=‘881158‘)
> 
> 我python水平比较菜，看不懂源码中的cookies那个语句，但问题似乎是出在cookies那里； 我通过手工添加我在浏览器里复制出来的cookie到源码中，可以正常访问，需要的朋友可以**救个急**； 原本的代码比较高级在我能力之外，**我这个笨办法不是个长久之计**
> 
> ![微信截图_20240622040230](https://private-user-images.githubusercontent.com/123301773/341879693-3847b76e-f3ca-4333-ad14-890aadbede9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwNDgzODEsIm5iZiI6MTcxOTA0ODA4MSwicGF0aCI6Ii8xMjMzMDE3NzMvMzQxODc5NjkzLTM4NDdiNzZlLWYzY2EtNDMzMy1hZDE0LTg5MGFhZGJlZGU5Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMlQwOTIxMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOTQ4OWFjYTAzNzIxMzM5OWY4MGNiZmQ5OTE0MmZjMTYxYWE3ZDk5OTZhMDFlNTY0NTEwNDMyODkyZDdmZDM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cMelT9U5is7k5bJdtV3xEQKMvNQSILeH94JhFzO9n0M)
> 
> 只是好像现在同花顺对这块是不是有一些更严格的管理，访问频率被压的很低，稍微频繁一点就又会返回空值
> 
> 原本的代码获得cookies的方式有点高级（代码小白实不敢妄测），瞎说之处请多原谅（抱拳）

近期会移除相关接口

**Comment by Junffzz** [comment]
这个接口为什么没有了
