### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by callcter** [akfamily/akshare#4985]
**详细问题描述**

1. 请先详细阅读文档对应接口的使用方式：https://akshare.akfamily.xyz：已阅
2. 操作系统版本，目前只支持 64 位操作系统：macOS
3. Python 版本，目前只支持 3.8 以上的版本：3.11
4. AKShare 版本，请升级到最新版：1.14.13
5. 接口的名称和相应的调用代码
申万指数 index_realtime_sw、index_hist_sw 2个接口
6. 接口报错的截图或描述
正常请求时：Connection to www.swhyresearch.com timed out. 不是知道是不是IP被ban了
我换了个 ip，报错成了：Expecting value: line 1 column 1 (char 0)
7. 期望获得的正确结果
正常请求

**Comment by MarsFengXinjie** [comment]
调用index_hist_sw接口时也报错了，报错的内容是unable to get local issuer certificate

**Comment by albertandking** [comment]
目前应该是网站没有数据
