### ISSUE TITLE
东方财富-指数

### ISSUE THREAD

**Issue by adamchenEpm** [akfamily/akshare#4988]
stock_board_concept_hist_em_df = ak.stock_board_concept_hist_em(symbol="车联网", period="daily", start_date="20220101", end_date="20221128", adjust="")

用不了

> 欢迎加入《数据科学实战》知识星球，交流财经数据与量化投资相关内容，
> 详细信息参考：https://akshare.akfamily.xyz/learn.html

## 前提

遇到任何问题，请先将您的 AKShare 版本升级到**最新版**，可以通过如下命令升级：

```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

## 如何提交问题

提交问题的同时，请提交以下相关信息，不符合提交规范的 issues 会被关闭！

**详细问题描述**

1. 请先详细阅读文档对应接口的使用方式：https://akshare.akfamily.xyz
2. 操作系统版本，目前只支持 64 位操作系统
3. Python 版本，目前只支持 3.8 以上的版本
4. AKShare 版本，请升级到最新版
5. 接口的名称和相应的调用代码
6. 接口报错的截图或描述
7. 期望获得的正确结果

**Comment by albertandking** [comment]
> stock_board_concept_hist_em_df = ak.stock_board_concept_hist_em(symbol="车联网", period="daily", start_date="20220101", end_date="20221128", adjust="")
> 
> 用不了
> 
> > 欢迎加入《数据科学实战》知识星球，交流财经数据与量化投资相关内容，
> > 详细信息参考：https://akshare.akfamily.xyz/learn.html
> 
> ## 前提
> 遇到任何问题，请先将您的 AKShare 版本升级到**最新版**，可以通过如下命令升级：
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> ## 如何提交问题
> 提交问题的同时，请提交以下相关信息，不符合提交规范的 issues 会被关闭！
> 
> **详细问题描述**
> 
> 1. 请先详细阅读文档对应接口的使用方式：https://akshare.akfamily.xyz
> 2. 操作系统版本，目前只支持 64 位操作系统
> 3. Python 版本，目前只支持 3.8 以上的版本
> 4. AKShare 版本，请升级到最新版
> 5. 接口的名称和相应的调用代码
> 6. 接口报错的截图或描述
> 7. 期望获得的正确结果

参见文档
