### ISSUE TITLE
energy_carbon_gz相关接口问题

### ISSUE THREAD

**Issue by fcgzhb** [akfamily/akshare#4991]
碳交易接口，启动ak程序后，第一次 能返回最新数据。隔天后数据接口就不更新了，只有重启程序再次请求就返回新数据了，这个是不是 @lru_cache() 缓存导致的？

**Comment by albertandking** [comment]
> 碳交易接口，启动ak程序后，第一次 能返回最新数据。隔天后数据接口就不更新了，只有重启程序再次请求就返回新数据了，这个是不是 @lru_cache() 缓存导致的？

已修复该问题，升级到 AKShare 1.14.15 使用；请根据 issues 模板提交问题
