### ISSUE TITLE
新增接口请求：帮忙新增“财联社”的接口

### ISSUE THREAD

**Issue by tianhaisuifeng** [akfamily/akshare#4992]
帮忙新增“财联社”的接口
在财联社网站上https://www.cls.cn/telegraph，有很多有价值的财经内容，建议新增一个接口。
1、获取最近1天或2天的内容，时间可定制
2、返回内容包括标题、对应链接和回帖数量，通过回帖数量，可以判断是否是热帖

**Comment by albertandking** [comment]
> https://www.cls.cn/telegraph

已有相关接口
