### ISSUE TITLE
ak.stock_us_hist(symbol = symbol, period='daily',adjust='hfq') 复权数据错误

### ISSUE THREAD

**Issue by rohou** [akfamily/akshare#4998]
ak.stock_us_hist(symbol = symbol, period='daily',adjust='hfq')获取TQQQ和SQQQ的数据时，获得的数据没有后复权。
这个问题昨天还没有，今天发现获得数据没有后复权。
TQQQ历史数据
       datetime    open   close     high      low    volume           成交额  \
0    2011-01-26  165.52  167.01  168.560  163.990    257571  0.000000e+00   
1    2011-01-27  168.97  170.23  171.650  168.050    285928  0.000000e+00   
2    2011-01-28  170.29  157.39  170.610  155.130    657382  0.000000e+00   
3    2011-01-31  158.01  159.72  160.920  154.500    414372  0.000000e+00   
4    2011-02-01  163.40  168.59  169.700  162.780    527831  0.000000e+00   
...         ...     ...     ...      ...      ...       ...           ...   
3341 2024-06-18   76.83   76.90   77.232   76.060  33216648  2.549655e+09   
3342 2024-06-20   77.46   75.09   77.660   74.221  52727537  3.998342e+09   
3343 2024-06-21   74.90   74.40   75.530   73.722  38856467  2.899493e+09   
3344 2024-06-24   73.82   71.88   74.630   71.800  46877274  3.431956e+09   
3345 2024-06-25   72.79   73.39   73.570   72.370  14491024  1.058205e+09

**Comment by albertandking** [comment]
> ak.stock_us_hist(symbol = symbol, period='daily',adjust='hfq')获取TQQQ和SQQQ的数据时，获得的数据没有后复权。 这个问题昨天还没有，今天发现获得数据没有后复权。 TQQQ历史数据 datetime open close high low volume 成交额 0 2011-01-26 165.52 167.01 168.560 163.990 257571 0.000000e+00 1 2011-01-27 168.97 170.23 171.650 168.050 285928 0.000000e+00 2 2011-01-28 170.29 157.39 170.610 155.130 657382 0.000000e+00 3 2011-01-31 158.01 159.72 160.920 154.500 414372 0.000000e+00 4 2011-02-01 163.40 168.59 169.700 162.780 527831 0.000000e+00 ... ... ... ... ... ... ... ... 3341 2024-06-18 76.83 76.90 77.232 76.060 33216648 2.549655e+09 3342 2024-06-20 77.46 75.09 77.660 74.221 52727537 3.998342e+09 3343 2024-06-21 74.90 74.40 75.530 73.722 38856467 2.899493e+09 3344 2024-06-24 73.82 71.88 74.630 71.800 46877274 3.431956e+09 3345 2024-06-25 72.79 73.39 73.570 72.370 14491024 1.058205e+09

请按 issues 格式提交问题
