### ISSUE TITLE
接口问题：stock_info_global_cls()接口获取数据不全

### ISSUE THREAD

**Issue by tianhaisuifeng** [akfamily/akshare#5004]
stock_info_global_cls()接口中，通过循环获取数据，但时间用的是modified_time，导致获取数据不全，建议用ctime
next_time = temp_df["ctime"].values[-1]

**Comment by albertandking** [comment]
> stock_info_global_cls()接口中，通过循环获取数据，但时间用的是modified_time，导致获取数据不全，建议用ctime next_time = temp_df["ctime"].values[-1]

请按 issues 模板提交问题，谢谢；已修复该问题，升级到 AKShare 使用
