### ISSUE TITLE
南华期货网站新接口开发需求

### ISSUE THREAD

**Issue by xnw176** [akfamily/akshare#5005]
南华网站和模式改版和更新导致目前所有相关接口失效，如下
<img width="154" alt="image" src="https://github.com/akfamily/akshare/assets/82297022/40b38a14-3b1d-4cc3-9166-e91003be5c7d">

希望能开发如下新接口
1. 指数总览接口，链接如下
https://webhq.nanhua.net/#/market?nav=南华指数
页面截图
<img width="809" alt="image" src="https://github.com/akfamily/akshare/assets/82297022/09d6430d-a7ec-4997-aafe-65425af8bc80">
2.单只指数详情，链接如下
https://webhq.nanhua.net/#/quote/M_NH
页面截图
<img width="1144" alt="image" src="https://github.com/akfamily/akshare/assets/82297022/7da4476e-b1f5-4c00-8f03-87b2b887c577">

非常感谢～

**Comment by albertandking** [comment]
> 南华网站和模式改版和更新导致目前所有相关接口失效，如下 <img alt="image" width="154" src="https://private-user-images.githubusercontent.com/82297022/344014326-40b38a14-3b1d-4cc3-9166-e91003be5c7d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4Mjk3MDUsIm5iZiI6MTcxOTgyOTQwNSwicGF0aCI6Ii84MjI5NzAyMi8zNDQwMTQzMjYtNDBiMzhhMTQtM2IxZC00Y2MzLTkxNjYtZTkxMDAzYmU1YzdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDEwMjMyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1YmI2NDk2MjA3ZmMwYjBjZjRiOTRjM2ZiNjE1MjliM2RmYWU0MGZmOWNjZWViZjljOWU3M2UwZjEwNjA0MGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0IFnZluxa_yPPhZNWRt8cEyTfK_xKYrc6T8e9F5Ogg8">
> 
> 希望能开发如下新接口
> 
> 1. 指数总览接口，链接如下
>    [https://webhq.nanhua.net/#/market?nav=南华指数](https://webhq.nanhua.net/#/market?nav=%E5%8D%97%E5%8D%8E%E6%8C%87%E6%95%B0)
>    页面截图
> 
> <img alt="image" width="809" src="https://private-user-images.githubusercontent.com/82297022/344015095-09d6430d-a7ec-4997-aafe-65425af8bc80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4Mjk3MDUsIm5iZiI6MTcxOTgyOTQwNSwicGF0aCI6Ii84MjI5NzAyMi8zNDQwMTUwOTUtMDlkNjQzMGQtYTdlYy00OTk3LWFhZmUtNjU0MjVhZjhiYzgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDEwMjMyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlZTE0N2Y1Mzc4MzdkM2JhMzUwMjAwODZjMTBmOTUzYWM5MjNkNTliZjI4YjMwMTM3NmQ3ZjU3Zjc1ZGUxZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XNEhq3IRjAJNEmUFx_JIx55DWsDBoLL6fzu9LG9bGdI"> 2.单只指数详情，链接如下 https://webhq.nanhua.net/#/quote/M_NH 页面截图 <img alt="image" width="1144" src="https://private-user-images.githubusercontent.com/82297022/344015404-7da4476e-b1f5-4c00-8f03-87b2b887c577.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4Mjk3MDUsIm5iZiI6MTcxOTgyOTQwNSwicGF0aCI6Ii84MjI5NzAyMi8zNDQwMTU0MDQtN2RhNDQ3NmUtYjFmNS00YzAwLThmMDMtODdiMmI4ODdjNTc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDEwMjMyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3ODA1ZmQ2MWEyYTBhNjQxZjY3YzlhNGY5YjZmOTJkNTQxNTJlYmE5ZjEyODkyZWM3N2FmOTljMmQ0ZGY5YTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Xu5AImQiPHBUEaHQVkxs-0YGEEpN9Wps0GvSKElK19s">
> 非常感谢～

暂不考虑 ws 的接口
