### ISSUE TITLE
AKShare 接口问题报告 macro_china_nbs_nation_df

### ISSUE THREAD

**Issue by raphaelxiao** [akfamily/akshare#5010]
**详细问题描述**

1. 请先详细阅读文档对应接口的使用方式：https://akshare.akfamily.xyz（确认）
2. 操作系统版本，目前只支持 64 位操作系统（确认）
3. Python 版本，目前只支持 3.8 以上的版本（确认）
4. AKShare 版本，请升级到最新版（确认）
5. 接口的名称和相应的调用代码

import akshare as ak

macro_china_nbs_nation_df = ak.macro_china_nbs_nation(kind="月度数据", path="工业 > 工业分大类行业出口交货值(2018-至今) > 废弃资源综合利用业", period="LAST5")
print(macro_china_nbs_nation_df)

7. 接口报错的截图或描述

    macro_china_nbs_nation_df = ak.macro_china_nbs_nation(kind="月度数据", path="工业 > 工业分大类行业出口交货值(2018-至今) > 废弃资源综合利用业", period="LAST5")
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Raphael\.conda\envs\IntelData\Lib\site-packages\akshare\economic\macro_china_nbs.py", line 115, in macro_china_nbs_nation
    data_json = r.json()
                ^^^^^^^^
  File "C:\Users\Raphael\.conda\envs\IntelData\Lib\site-packages\requests\models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

9. 期望获得的正确结果

返回正确的数据

**Comment by albertandking** [comment]
> 工业 > 工业分大类行业出口交货值(2018-至今) > 废弃资源综合利用业

接口测试正常；注意访问频率
