### ISSUE TITLE
同花顺概念和成分股api接口没有了？

### ISSUE THREAD

**Issue by and0202** [akfamily/akshare#5018]
大佬好：

    1.14版本的同花顺概念和成分股api接口去掉了？后期还会添加吗？
        同花顺行业成分股也没有了，后期还会添加吗？
       感谢大佬。

<img width="1026" alt="截屏2024-07-03 20 28 52" src="https://github.com/akfamily/akshare/assets/3023527/a9c866a7-a1ad-43c1-8d7b-89dbf5b88b52">
<img width="287" alt="截屏2024-07-03 20 32 47" src="https://github.com/akfamily/akshare/assets/3023527/82948260-2d24-4388-8d74-10e1b60fd84c">
<img width="287" alt="截屏2024-07-03 20 32 47" src="https://github.com/akfamily/akshare/assets/3023527/723dbfc5-9bad-41cc-9636-59e6b6b1942c">

**Comment by albertandking** [comment]
> 大佬好：
> 
> ```
> 1.14版本的同花顺概念和成分股api接口去掉了？后期还会添加吗？
>     同花顺行业成分股也没有了，后期还会添加吗？
>    感谢大佬。
> ```
> 
> <img alt="截屏2024-07-03 20 28 52" width="1026" src="https://private-user-images.githubusercontent.com/3023527/345422080-a9c866a7-a1ad-43c1-8d7b-89dbf5b88b52.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNzI5MjQsIm5iZiI6MTcyMDA3MjYyNCwicGF0aCI6Ii8zMDIzNTI3LzM0NTQyMjA4MC1hOWM4NjZhNy1hMWFkLTQzYzEtOGQ3Yi04OWRiZjViODhiNTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDRUMDU1NzA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Zjk2NzgxZTkzMzU3MGFiNzFiNGJmYjQ3NDg2YTlhMTIwMjI1ZTE4ZDhjNjhlYTZmYzUwOTNkZWZhZjYzMDAwNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.HNBwHyWlGHOU0MzzOCHFa0Pe4WkgLa1qd1eXJV2sRz4"> <img alt="截屏2024-07-03 20 32 47" width="287" src="https://private-user-images.githubusercontent.com/3023527/345422095-82948260-2d24-4388-8d74-10e1b60fd84c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNzI5MjQsIm5iZiI6MTcyMDA3MjYyNCwicGF0aCI6Ii8zMDIzNTI3LzM0NTQyMjA5NS04Mjk0ODI2MC0yZDI0LTQzODgtOGQ3NC0xMGUxYjYwZmQ4NGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDRUMDU1NzA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzlkYjU4ODRjNmI1ZWE4NDY0M2NlYTY1YzNlNTYxNmZlYTg3NGNhMThkY2I3MzJjYTViOWMwODYwOGU0MWFmOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.8Vxhy-F4tNu9wCJbN0OVMvKLknV74DcvPXN_7HjUy5w"> <img alt="截屏2024-07-03 20 32 47" width="287" src="https://private-user-images.githubusercontent.com/3023527/345422096-723dbfc5-9bad-41cc-9636-59e6b6b1942c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNzI5MjQsIm5iZiI6MTcyMDA3MjYyNCwicGF0aCI6Ii8zMDIzNTI3LzM0NTQyMjA5Ni03MjNkYmZjNS05YmFkLTQxY2MtOTYzNi01OWU2YjZiMTk0MmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDRUMDU1NzA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTFmY2QwNTAyNGM1MTg4YjBkNGMzMDJjNGYwYjhmMjJkMzhmZWZjODBmN2ZhMDEzOGE2M2RiYTRiZWI2ZGQzMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.8pHu-9Y_CeO46kITdxfJh8OI3V4hrLHRzxhJ4sGsY0M">

同花顺的数据需要登录，已经移除相关接口

**Comment by thunder951413** [comment]
@and0202 用webdriver写

**Comment by shunlisun** [comment]
@thunder951413 这块您实现了吗
