### ISSUE TITLE
【南华期货-南华指数所有品种一览表】响应报错

### ISSUE THREAD

**Issue by hugsk** [akfamily/akshare#5025]
调用示例：`ak.futures_return_index_nh('NHCI')`；

报错原因：调用函数接口`futures_index_symbol_table_nh`中的南华期货数据网址`https://www.nanhua.net/ianalysis/plate-variety.json`
无法得到响应数据。

**Comment by albertandking** [comment]
> 调用示例：`ak.futures_return_index_nh('NHCI')`；
> 
> 报错原因：调用函数接口`futures_index_symbol_table_nh`中的南华期货数据网址`https://www.nanhua.net/ianalysis/plate-variety.json` 无法得到响应数据。

参见说明文档；请按 issues 格式提交问题
