### ISSUE TITLE
news_trade_notify_dividend_baidu接口超过100条会分页

### ISSUE THREAD

**Issue by 3sy11** [akfamily/akshare#5026]
版本1.14.27

以2024年6月21日数据为例
第一页
https://finance.pae.baidu.com/api/financecalendar?start_date=2024-06-21&end_date=2024-06-21&market=&cate=notify_divide&finClientType=pc
第二页
https://finance.pae.baidu.com/api/financecalendar?start_date=2024-06-21&end_date=2024-06-21&market=&cate=notify_divide&rn=50&pn=100&finClientType=pc

![image](https://github.com/akfamily/akshare/assets/24854346/eb2394b6-23aa-4481-b5b7-be86bd8771d2)

**Comment by albertandking** [comment]
> 版本1.14.27
> 
> 以2024年6月21日数据为例 第一页 https://finance.pae.baidu.com/api/financecalendar?start_date=2024-06-21&end_date=2024-06-21&market=&cate=notify_divide&finClientType=pc 第二页 https://finance.pae.baidu.com/api/financecalendar?start_date=2024-06-21&end_date=2024-06-21&market=&cate=notify_divide&rn=50&pn=100&finClientType=pc
> 
> ![image](https://private-user-images.githubusercontent.com/24854346/346792742-eb2394b6-23aa-4481-b5b7-be86bd8771d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1OTcxODAsIm5iZiI6MTcyMDU5Njg4MCwicGF0aCI6Ii8yNDg1NDM0Ni8zNDY3OTI3NDItZWIyMzk0YjYtMjNhYS00NDgxLWI1YjctYmU4NmJkODc3MWQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDA3MzQ0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1MzYxYjAxZjM5Njc5NjQ0OTJhODkzOGZmOWVhNjA1ZmYwMTUxM2Q0OTc0YjY3MWIyZTVhZTg3ZDE2NWVmMjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eKPM68hot4op_gmYeCfh7JyRPJoyoTqp7OuLLqIE858)

感谢反馈问题，已修复该问题，升级到 AKShare 1.14.28 使用；后续请按 issues 格式提交问题，便于解决 bug
