### ISSUE TITLE
【南华期货-南华指数所有品种一览表】响应报错

### ISSUE THREAD

**Issue by hugsk** [akfamily/akshare#5027]
1. 操作系统版本：x64-based
2. python版本：3.9.13
3. KAShare版本：1.14.25
4. 接口名称：`futures_return_index_nh`，调用代码`data = ak.futures_return_index_nh('NHCI')`
5. 报错描述：`requests.exceptions.JSONDecodeError: Expecting value: line 2 column 1 (char 2)`
6. 期望正确结果：column分别为date和value的数据帧；由于其他API一直调用该接口，时间长了，现在也不太清楚原本的返回结果是什么。

**Comment by albertandking** [comment]
> 4\. futures_return_index_nh

参见文档说明
