### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by leonexue** [akfamily/akshare#5028]
描述遇到的问题

1.操作系统版本 winser2012 x64
2.Python 版本 Python3.8.1
3.AKShare 版本 1.10.57
4.接口的名称和代码 fund_etf_hist_em
5.接口报错的截图或代码
    df=ak.fund_lof_hist_em(symbol=etf,period="daily",start_date=start_date,end_d
ate=end_date,adjust="qfq")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-p
ackages\akshare\fund\fund_lof_em.py", line 155, in fund_lof_hist_em
    "secid": f"{code_id_dict[symbol]}.{symbol}",
KeyError: '159985'
6.期望获得的正确结果
该基金链接：http://quote.eastmoney.com/sz159985.html
与该接口说明的链接相同，但无法被查出

**Comment by albertandking** [comment]
> fund_lof_hist_em

接口测试正常

**Comment by leonexue** [comment]
我前面可能意思没表达清楚，接口测试是正常的，但是查不到我要的这个etf的信息，159985是个etf应该用fund_etf_hist_em接口查询，但是目前好像查不到。我用ak.fund_etf_spot_em()和ak.fund_lof_spot_em()  详细查了下清单发现159985都不在里面，能不能把这个etf增加进fund_etf_hist_em清单里
