### ISSUE TITLE
实时行情数据-雪球 stock_individual_spot_xq 能否麻烦加个时间戳

### ISSUE THREAD

**Issue by Yirenxs** [akfamily/akshare#5031]
实时行情数据-雪球
接口: stock_individual_spot_xq
目标地址: https://xueqiu.com/S/SH513520

这个地址能否加个实时的时间呢，我看雪球网页上是有这个时间的，谢谢。

![image](https://github.com/user-attachments/assets/31ccd03d-5e0d-4a18-8a53-a5d1a2c9bc79)

**Comment by albertandking** [comment]
> 实时行情数据-雪球 接口: stock_individual_spot_xq 目标地址: https://xueqiu.com/S/SH513520
> 
> 这个地址能否加个实时的时间呢，我看雪球网页上是有这个时间的，谢谢。
> 
> ![image](https://private-user-images.githubusercontent.com/49506362/348061211-31ccd03d-5e0d-4a18-8a53-a5d1a2c9bc79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3ODA2MjgsIm5iZiI6MTcyMDc4MDMyOCwicGF0aCI6Ii80OTUwNjM2Mi8zNDgwNjEyMTEtMzFjY2QwM2QtNWUwZC00YTE4LThhNTMtYTVkMWEyYzliYzc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDEwMzIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1ZjNjMjk5MjZmZDRiMTRhYWIxYmE1MzhmZmY5YjM5OTAxOTc5MDUzYzdiNzcwZDg1ODRjMWU1OWJkODk5NTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.arT1dxEjqGMa_BZH8tkmnW2KbDe4mDuahInUauFDErM)

已新增时间字段，升级到 AKShare 1.14.29 使用
