### ISSUE TITLE
ak.stock_us_hist_min_em 接口能获得美股 period 的分时数据吗

### ISSUE THREAD

**Issue by OkabeRintarou** [akfamily/akshare#5033]
当前 akshare.stock_us_hist_min_em 只能返回 1min 级别的数据，有办法增加 period 参数，获得例如 15min, 30min 周期的数据吗

**Comment by albertandking** [comment]
> 当前 akshare.stock_us_hist_min_em 只能返回 1min 级别的数据，有办法增加 period 参数，获得例如 15min, 30min 周期的数据吗

是的，请按 issues 要求格式提交问题
