### ISSUE TITLE
AKShare 官方文档回档请求

### ISSUE THREAD

**Issue by Because66666** [akfamily/akshare#5038]
我不知道发生了什么，但是官方的在线文档https://akshare.akfamily.xyz/ 已经大部分都看不到了，造成了很大的不方便，希望能够回档
![image](https://github.com/user-attachments/assets/8a85ba13-d5d3-40b7-8900-3c5f49a50471)
![image](https://github.com/user-attachments/assets/a0e40106-b5ee-4faa-ad57-712da727c548)

**Comment by albertandking** [comment]
> 我不知道发生了什么，但是官方的在线文档https://akshare.akfamily.xyz/ 已经大部分都看不到了，造成了很大的不方便，希望能够回档 ![image](https://private-user-images.githubusercontent.com/110363085/348726213-8a85ba13-d5d3-40b7-8900-3c5f49a50471.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNTM2NDMsIm5iZiI6MTcyMTA1MzM0MywicGF0aCI6Ii8xMTAzNjMwODUvMzQ4NzI2MjEzLThhODViYTEzLWQ1ZDMtNDBiNy04OTAwLTNjNWY0OWE1MDQ3MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNVQxNDIyMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZGJlYTUwNjUyNjc2MTNmN2E1OTJiMDI0ZmE2NzJjZThkZDJiZjI1NmUxYzczY2Y2NDhmOGRhMDc4MGZmZDAwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YdG8xPqTot8svW8_jKBuoizdOwfU9vqkeiGXjELGO5w) ![image](https://private-user-images.githubusercontent.com/110363085/348726284-a0e40106-b5ee-4faa-ad57-712da727c548.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNTM2NDMsIm5iZiI6MTcyMTA1MzM0MywicGF0aCI6Ii8xMTAzNjMwODUvMzQ4NzI2Mjg0LWEwZTQwMTA2LWI1ZWUtNGZhYS1hZDU3LTcxMmRhNzI3YzU0OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNVQxNDIyMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMGQyNjhmOTk3MzQ3ZjUxMjE1MTIxZmFkOGU5Mjg4N2ZiMGU3NjYwZjMxMTM2YTI3NTU2M2ZhOGNlMTgwOTQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.d48ALH6mwMiBTpiI7hFj6XAS6oLqGH2pcchp80FrOoQ)

已修复，是第三方依赖库 sphinx 的问题导致的
