### ISSUE TITLE
能否新增基金规模接口

### ISSUE THREAD

**Issue by lightcax** [akfamily/akshare#5041]
地址：https://fundf10.eastmoney.com/FundArchivesDatas.aspx?type=gmbd&mode=0&code=159865
原雪球基金规模很多基金都查不到
谢谢

**Comment by albertandking** [comment]
> 地址：https://fundf10.eastmoney.com/FundArchivesDatas.aspx?type=gmbd&mode=0&code=159865 原雪球基金规模很多基金都查不到 谢谢

已有相关接口，请按 issues 模板规则提问
