### ISSUE TITLE
同花顺-数据中心-资金流向-概念资金流  接口实际返回结果与文档描述不一致

### ISSUE THREAD

**Issue by aqingGitHub** [akfamily/akshare#5048]
**详细问题描述**

1. 请先详细阅读文档对应接口的使用方式：https://akshare.akfamily.xyz
2. 操作系统版本： 64 位操作系统
3. Python 版本： 3.12.1
4. AKShare 版本：1.14.34
5. 接口的名称和相应的调用代码
```
stock_fund_flow_concept_df = ak.stock_fund_flow_concept(symbol="即时")
print(stock_fund_flow_concept_df)
```
7. 接口报错的截图或描述
返回结果与文档定义不一致  
https://akshare.akfamily.xyz/data/stock/stock.html#id368  
![image](https://github.com/user-attachments/assets/eda8844a-164f-431b-aea7-d21f583a47c2)

9. 期望获得的正确结果
![image](https://github.com/user-attachments/assets/38963989-81ff-4271-9427-4c77e75a5470)

**Comment by albertandking** [comment]
> **详细问题描述**
> 
> 1. 请先详细阅读文档对应接口的使用方式：https://akshare.akfamily.xyz
> 2. 操作系统版本： 64 位操作系统
> 3. Python 版本： 3.12.1
> 4. AKShare 版本：1.14.34
> 5. 接口的名称和相应的调用代码
> 
> ```
> stock_fund_flow_concept_df = ak.stock_fund_flow_concept(symbol="即时")
> print(stock_fund_flow_concept_df)
> ```
> 
> 7. 接口报错的截图或描述
>    返回结果与文档定义不一致
>    https://akshare.akfamily.xyz/data/stock/stock.html#id368
>    ![image](https://private-user-images.githubusercontent.com/29811999/349856099-eda8844a-164f-431b-aea7-d21f583a47c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyOTM0MzIsIm5iZiI6MTcyMTI5MzEzMiwicGF0aCI6Ii8yOTgxMTk5OS8zNDk4NTYwOTktZWRhODg0NGEtMTY0Zi00MzFiLWFlYTctZDIxZjU4M2E0N2MyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDA4NTg1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxMmEyMWIzZjc5NzhmNDExMWQwNjM4NWU3ZGIyZWVlOGY3ZGVlYjdjZTlmODdiN2EyNzIxMjU2YWQwNWQyNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kcikmZ7e8mN62vxTx2M3bTRSdf_9onvAqlThBDRJpBA)
> 8. 期望获得的正确结果
>    ![image](https://private-user-images.githubusercontent.com/29811999/349855530-38963989-81ff-4271-9427-4c77e75a5470.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyOTM0MzIsIm5iZiI6MTcyMTI5MzEzMiwicGF0aCI6Ii8yOTgxMTk5OS8zNDk4NTU1MzAtMzg5NjM5ODktODFmZi00MjcxLTk0MjctNGM3N2U3NWE1NDcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDA4NTg1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3NDYxNzAwZmM0YzQ1NzRmYWQ3MDlkMjc0NGIxOTAzMjIyMThkY2M0NzI0NzNhMDk4ZGZlM2IwOWEzZWI2ZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WP4h6zN4B3vI7JFM4PAJw1OLCDDa8ycL7dFwBS90XUs)



> **详细问题描述**
> 
> 1. 请先详细阅读文档对应接口的使用方式：https://akshare.akfamily.xyz
> 2. 操作系统版本： 64 位操作系统
> 3. Python 版本： 3.12.1
> 4. AKShare 版本：1.14.34
> 5. 接口的名称和相应的调用代码
> 
> ```
> stock_fund_flow_concept_df = ak.stock_fund_flow_concept(symbol="即时")
> print(stock_fund_flow_concept_df)
> ```
> 
> 7. 接口报错的截图或描述
>    返回结果与文档定义不一致
>    https://akshare.akfamily.xyz/data/stock/stock.html#id368
>    ![image](https://private-user-images.githubusercontent.com/29811999/349856099-eda8844a-164f-431b-aea7-d21f583a47c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyOTM0MzIsIm5iZiI6MTcyMTI5MzEzMiwicGF0aCI6Ii8yOTgxMTk5OS8zNDk4NTYwOTktZWRhODg0NGEtMTY0Zi00MzFiLWFlYTctZDIxZjU4M2E0N2MyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDA4NTg1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxMmEyMWIzZjc5NzhmNDExMWQwNjM4NWU3ZGIyZWVlOGY3ZGVlYjdjZTlmODdiN2EyNzIxMjU2YWQwNWQyNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kcikmZ7e8mN62vxTx2M3bTRSdf_9onvAqlThBDRJpBA)
> 8. 期望获得的正确结果
>    ![image](https://private-user-images.githubusercontent.com/29811999/349855530-38963989-81ff-4271-9427-4c77e75a5470.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyOTM0MzIsIm5iZiI6MTcyMTI5MzEzMiwicGF0aCI6Ii8yOTgxMTk5OS8zNDk4NTU1MzAtMzg5NjM5ODktODFmZi00MjcxLTk0MjctNGM3N2U3NWE1NDcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDA4NTg1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3NDYxNzAwZmM0YzQ1NzRmYWQ3MDlkMjc0NGIxOTAzMjIyMThkY2M0NzI0NzNhMDk4ZGZlM2IwOWEzZWI2ZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WP4h6zN4B3vI7JFM4PAJw1OLCDDa8ycL7dFwBS90XUs)

接口返回一致
