### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by AZ-bytte999** [akfamily/akshare#5059]
**详细问题描述**
 "stock_industry_clf_hist_sw"  # 申万宏源研究-行业分类-全部行业分类 获取报错。
win7-64位
python-3.8
akshare-1.14.34

接口报错的截图或描述
![22](https://github.com/user-attachments/assets/be152dc9-8c8a-4313-84f1-d51f4850e752)
![21](https://github.com/user-attachments/assets/81a94b0d-2dd1-47c5-ac31-4a98d1f9bae5)
![23](https://github.com/user-attachments/assets/bb978832-b385-4319-966c-7487325e0782)

**Comment by albertandking** [comment]
> **详细问题描述** "stock_industry_clf_hist_sw" # 申万宏源研究-行业分类-全部行业分类 获取报错。 win7-64位 python-3.8 akshare-1.14.34
> 
> 接口报错的截图或描述 ![22](https://private-user-images.githubusercontent.com/176253772/350810226-be152dc9-8c8a-4313-84f1-d51f4850e752.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2NDU5NzEsIm5iZiI6MTcyMTY0NTY3MSwicGF0aCI6Ii8xNzYyNTM3NzIvMzUwODEwMjI2LWJlMTUyZGM5LThjOGEtNDMxMy04NGYxLWQ1MWY0ODUwZTc1Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMlQxMDU0MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ODk3YzI1ZTVmZjAyMTI4OTQwNzEwODUxMTQ3M2UyM2Y2ZTZiOGQwOTIwMDk3MGVjZmZlNzAwNDU0ZTRjNTYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BNcXjyryFrohY34iJZNXYSb057aIg4cKfHFopduWwf0) ![21](https://private-user-images.githubusercontent.com/176253772/350810235-81a94b0d-2dd1-47c5-ac31-4a98d1f9bae5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2NDU5NzEsIm5iZiI6MTcyMTY0NTY3MSwicGF0aCI6Ii8xNzYyNTM3NzIvMzUwODEwMjM1LTgxYTk0YjBkLTJkZDEtNDdjNS1hYzMxLTRhOThkMWY5YmFlNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMlQxMDU0MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZTgzNzE1YWYzMjBhODgyNzNjNjM3MjMwMjY4NWQ3ZTI4MWVkNzY0NTVhZjRmZjE4NzQyNTJiNmRkZGVhYTliJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jCrI2uOoj3bwMafNc0MiSRU06VaOoqF45rcEowG-5qs) ![23](https://private-user-images.githubusercontent.com/176253772/350810387-bb978832-b385-4319-966c-7487325e0782.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2NDU5NzEsIm5iZiI6MTcyMTY0NTY3MSwicGF0aCI6Ii8xNzYyNTM3NzIvMzUwODEwMzg3LWJiOTc4ODMyLWIzODUtNDMxOS05NjZjLTc0ODczMjVlMDc4Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMlQxMDU0MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZDliZmQ2NTEyYjYxODJmOTQzMDA0MmY1NThkMjQ5YTVlNzQ2OWRlODE1MTMwZDY3MTA4ZmJiYjU1ODgyYzA1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Pj-OiDtlupYdVmhnB081raKqh_mi6Pd_j6abfNE2Pac)

已修复该问题，升级到 AKShare 1.14.39 使用，请按 issues 提交问题
