### ISSUE TITLE
AKShare 数据更新问题报告

### ISSUE THREAD

**Issue by AZ-bytte999** [akfamily/akshare#5060]
**详细问题描述**
数据库数据没有更新到最新

win7 -64
python 3.8
akshare 1.14.37

ak.stock_info_sh_name_code()，
ak.stock_info_sz_name_code()，
ak.sw_index_third_info()，
这3个接口的数据没有更新到最新，ak.sw_index_third_info()还是23年9月份的数据。

期望获得的正确结果

更新数据库

**Comment by albertandking** [comment]
> **详细问题描述** 数据库数据没有更新到最新
> 
> win7 -64 python 3.8 akshare 1.14.37
> 
> ak.stock_info_sh_name_code()， ak.stock_info_sz_name_code()， ak.sw_index_third_info()， 这3个接口的数据没有更新到最新，ak.sw_index_third_info()还是23年9月份的数据。
> 
> 期望获得的正确结果
> 
> 更新数据库

请按 issues 提交问题
