### ISSUE TITLE
AKShare 接口问请教

### ISSUE THREAD

**Issue by aqingGitHub** [akfamily/akshare#5061]
你好！请问在技术指标中能加入MACD、KDJ等一些常用技术指标吗，  另外能否开通github的Discussions功能？ 感谢！

**Comment by albertandking** [comment]
> 你好！请问在技术指标中能加入MACD、KDJ等一些常用技术指标吗， 另外能否开通github的Discussions功能？ 感谢！

可以使用其他第三方指标库计算即可
