### ISSUE TITLE
Python3.10 pip install AKShare 报错

### ISSUE THREAD

**Issue by changjialiBRY** [akfamily/akshare#5065]
【操作背景】
1. Python3.10虚拟环境中引入akshare；

【报错信息】
1. 
2. 

【尝试解决步骤】
1.  返回Failed connect to chromium.goolesource.com:443; connection timed out；尝试pip install akshare -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host=mirrors.aliyun.com  --upgrade，返回
.[0:45:12] Started.
      [0:45:12]
      
      ________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://chromium.googlesource.com/external/github.com/google/fuzztest.git /tmp/pip-install-tpnl40du/mini-racer_cb0f83585df940f09a0a78cd0cdb2748/v8_workspace/v8/third_party/fuzztest/_gclient_src_asxzj_ek' in '/tmp/pip-install-tpnl40du/mini-racer_cb0f83585df940f09a0a78cd0cdb2748/v8_workspace'
      
      [0:45:12] Cloning into '/tmp/pip-install-tpnl40du/mini-racer_cb0f83585df940f09a0a78cd0cdb2748/v8_workspace/v8/third_party/fuzztest/_gclient_src_asxzj_ek'...
      [0:45:15] error: RPC failed; result=22, HTTP code = 400
      [0:45:15] fatal: The remote end hung up unexpectedly

3. 尝试使用代理未生效；依旧报错
4. 尝试设置git的缓存大小，也报错

**Comment by albertandking** [comment]
> 【操作背景】
> 
> 1. Python3.10虚拟环境中引入akshare；
> 
> 【报错信息】 1. 2.
> 
> 【尝试解决步骤】
> 
> 1. 返回Failed connect to chromium.goolesource.com:443; connection timed out；尝试pip install akshare -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host=mirrors.aliyun.com  --upgrade，返回
>    .[0:45:12] Started.
>    [0:45:12]
>    ________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://chromium.googlesource.com/external/github.com/google/fuzztest.git /tmp/pip-install-tpnl40du/mini-racer_cb0f83585df940f09a0a78cd0cdb2748/v8_workspace/v8/third_party/fuzztest/_gclient_src_asxzj_ek' in '/tmp/pip-install-tpnl40du/mini-racer_cb0f83585df940f09a0a78cd0cdb2748/v8_workspace'
>    [0:45:12] Cloning into '/tmp/pip-install-tpnl40du/mini-racer_cb0f83585df940f09a0a78cd0cdb2748/v8_workspace/v8/third_party/fuzztest/_gclient_src_asxzj_ek'...
>    [0:45:15] error: RPC failed; result=22, HTTP code = 400
>    [0:45:15] fatal: The remote end hung up unexpectedly
> 2. 尝试使用代理未生效；依旧报错
> 3. 尝试设置git的缓存大小，也报错

测试正常；请调试本地环境
