### ISSUE TITLE
AKShare数据更新问题报告

### ISSUE THREAD

**Issue by AZ-bytte999** [akfamily/akshare#5068]
**详细问题描述**
一、ak.stock_info_sh_name_code()数据未更新。请求更新数据。

![52](https://github.com/user-attachments/assets/bfffcde0-5db8-46b8-a99e-9466ca9f5fd3)
![53](https://github.com/user-attachments/assets/6cf70547-7100-4cff-bfd2-c4a9c94d77d9)

2. 操作系统版本，win7-64 位操作系统
3. Python 版本，python3.8
4. AKShare 版本1.14.37
5. 请求更新到最新数据。

二、ak.sw_index_third_cons()数据未更新。请求更新数据。
![55](https://github.com/user-attachments/assets/71f7d0e6-2486-40da-a375-140d83554d42)
![56](https://github.com/user-attachments/assets/f131657a-4b75-428e-a1d0-b3a8d1cab49b)

2. 操作系统版本，win7-64 位操作系统
3. Python 版本，python3.8
4. AKShare 版本1.14.37
5. 请求更新到最新数据。

**Comment by albertandking** [comment]
> **详细问题描述** 一、ak.stock_info_sh_name_code()数据未更新。请求更新数据。
> 
> ![52](https://private-user-images.githubusercontent.com/176253772/351157415-bfffcde0-5db8-46b8-a99e-9466ca9f5fd3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3OTk5MTUsIm5iZiI6MTcyMTc5OTYxNSwicGF0aCI6Ii8xNzYyNTM3NzIvMzUxMTU3NDE1LWJmZmZjZGUwLTVkYjgtNDZiOC1hOTllLTk0NjZjYTlmNWZkMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNFQwNTQwMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZDA1YTMwN2QwYzQ2ZGVlNTFkMGZiMTk3ODRhMDY1YWVjNjFlZTMyM2M1NjhmZTU5ZDFiYjJhZDIyN2M2MWVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.803PiDkNNHBhIgAO8-6HKB50cimJm7cHrQ_-Smuht7g) ![53](https://private-user-images.githubusercontent.com/176253772/351157422-6cf70547-7100-4cff-bfd2-c4a9c94d77d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3OTk5MTUsIm5iZiI6MTcyMTc5OTYxNSwicGF0aCI6Ii8xNzYyNTM3NzIvMzUxMTU3NDIyLTZjZjcwNTQ3LTcxMDAtNGNmZi1iZmQyLWM0YTljOTRkNzdkOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNFQwNTQwMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OGYzMDg1OWMyYTdmZGE0ZTk4Y2NlMTE3OWY0MmIyNDYxMTBjNmJjMjNkYjE2MmNiNjk2YTgxZjZjNjdlNGMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ifyCLgkILDpZB_iWcx4RPIKwyzu-6gp_w21KstMeRtA)
> 
> 2. 操作系统版本，win7-64 位操作系统
> 3. Python 版本，python3.8
> 4. AKShare 版本1.14.37
> 5. 请求更新到最新数据。
> 
> 二、ak.sw_index_third_cons()数据未更新。请求更新数据。 ![55](https://private-user-images.githubusercontent.com/176253772/351255382-71f7d0e6-2486-40da-a375-140d83554d42.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3OTk5MTUsIm5iZiI6MTcyMTc5OTYxNSwicGF0aCI6Ii8xNzYyNTM3NzIvMzUxMjU1MzgyLTcxZjdkMGU2LTI0ODYtNDBkYS1hMzc1LTE0MGQ4MzU1NGQ0Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNFQwNTQwMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ODk5YTY2ZjU1OTlmM2RiNWI4Mjg3YTUxNWM0MzYzNWFiMjRjNDI4YWQ4OTQ2MDM5NjllOGRhYzNjZDVjNGM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.F1wLBlcHRVJ_p8-S2RHfgJn8tMAK2aSUR28W9fs8XHU) ![56](https://private-user-images.githubusercontent.com/176253772/351255510-f131657a-4b75-428e-a1d0-b3a8d1cab49b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3OTk5MTUsIm5iZiI6MTcyMTc5OTYxNSwicGF0aCI6Ii8xNzYyNTM3NzIvMzUxMjU1NTEwLWYxMzE2NTdhLTRiNzUtNDI4ZS1hMWQwLWIzYThkMWNhYjQ5Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNFQwNTQwMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYmY0Y2Y2MTllZGQ5MDg2MGFhMjQ5MDZiMzM3N2VmYmFiZTJjMjk4YWZhM2NhMjg4YTNhNDdjYWM2NjU3YjkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oeArHMTBZicGHMo4XFHlhWeBH7H36zJFoMGx8b7RpZo)
> 
> 2. 操作系统版本，win7-64 位操作系统
> 3. Python 版本，python3.8
> 4. AKShare 版本1.14.37
> 5. 请求更新到最新数据。

跟数据源一致的
