### ISSUE TITLE
AKShare 接口问题报告:昨日股票涨停池api接口异常

### ISSUE THREAD

**Issue by and0202** [akfamily/akshare#5077]
=================================
版本：'1.14.42'
接口api：ak.stock_zt_pool_previous_em(date='20240415')
异常情况：
--> 135 temp_df.columns = [
    136     "序号",
    137     "代码",
    138     "_",
    139     "名称",
    140     "最新价",
    141     "涨停价",
    142     "涨跌幅",
    143     "成交额",
    144     "流通市值",
    145     "总市值",
    146     "换手率",
    147     "振幅",
    148     "涨速",
    149     "昨日封板时间",
    150     "昨日连板数",
    151     "所属行业",
    152     "涨停统计",
    153 ]
    154 temp_df["涨停统计"] = (
    155     temp_df["涨停统计"].apply(lambda x: dict(x)["days"]).astype(str)
    156     + "/"
    157     + temp_df["涨停统计"].apply(lambda x: dict(x)["ct"]).astype(str)
    158 )
    159 temp_df = temp_df[
    160     [
    161         "序号",
   (...)
    177     ]
    178 ]

File ~/anaconda3/envs/base_new/lib/python3.10/site-packages/pandas/core/generic.py:6310, in NDFrame.__setattr__(self, name, value)
   6308 try:
   6309     object.__getattribute__(self, name)
-> 6310     return object.__setattr__(self, name, value)
   6311 except AttributeError:
   6312     pass

<img width="1024" alt="截屏2024-07-25 16 48 49" src="https://github.com/user-attachments/assets/57915f3d-094d-4248-9c87-94b8966e85a5">

ValueError: Length mismatch: Expected axis has 1 elements, new values have 17 elements

**Comment by albertandking** [comment]
> stock_zt_pool_previous_em

按文档说明操作
