### ISSUE TITLE
历史股票日线数据请求输出preclose

### ISSUE THREAD

**Issue by quantcn** [akfamily/akshare#5086]
目前，只能输出ohlc等历史价格，不能输出preclose。
我们需要利用preclose来自己进行复权。akshare提供的复权数据有些事错误的，所以需要自己复权。

**Comment by albertandking** [comment]
> 目前，只能输出ohlc等历史价格，不能输出preclose。 我们需要利用preclose来自己进行复权。akshare提供的复权数据有些事错误的，所以需要自己复权。

数据源没有相关字段
