### ISSUE TITLE
接口问题报告,stock_intraday_em()

### ISSUE THREAD

**Issue by danpianji** [akfamily/akshare#5087]
获取的数据和实际对不上
以sz301198为例
获取的到的数据如下
---------------------------
65    09:24:39   8.92   9700   中性盘
66    09:24:48   8.92  11002   中性盘
67    09:24:57   8.89  15583   中性盘
68    09:25:00   8.75  17100    买盘
69    09:30:00   8.78  12476    买盘
70    09:30:03   8.87   3165    买盘
71    09:30:06   8.90    625    买盘
72    09:30:09   8.90   1069    买盘
73    09:30:12   8.91   1982    卖盘
74    09:30:15   8.92   1000    买盘
75    09:30:18   8.92   3865    卖盘
76    09:30:21   8.90   1750    卖盘
---------------------------------------------------
https://quote.eastmoney.com/f1.html?newcode=0.301198
的截图如下
![Image 20240730113732-001](https://github.com/user-attachments/assets/2ff3f39e-6bbc-41f7-b011-fcded31c32d8)

问题:价格和手数,时间是对的,但是箭头的判断不对

**Comment by danpianji** [comment]
数据为24年7月30日,代码sz301198

**Comment by albertandking** [comment]
> ## 获取的数据和实际对不上
> 以sz301198为例
> 获取的到的数据如下
> ## 65 09:24:39 8.92 9700 中性盘
> 66 09:24:48 8.92 11002 中性盘
> 67 09:24:57 8.89 15583 中性盘
> 68 09:25:00 8.75 17100 买盘
> 69 09:30:00 8.78 12476 买盘
> 70 09:30:03 8.87 3165 买盘
> 71 09:30:06 8.90 625 买盘
> 72 09:30:09 8.90 1069 买盘
> 73 09:30:12 8.91 1982 卖盘
> 74 09:30:15 8.92 1000 买盘
> 75 09:30:18 8.92 3865 卖盘
> 76 09:30:21 8.90 1750 卖盘
> https://quote.eastmoney.com/f1.html?newcode=0.301198 的截图如下 ![Image 20240730113732-001](https://private-user-images.githubusercontent.com/25237166/353304232-2ff3f39e-6bbc-41f7-b011-fcded31c32d8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzNDAxNzgsIm5iZiI6MTcyMjMzOTg3OCwicGF0aCI6Ii8yNTIzNzE2Ni8zNTMzMDQyMzItMmZmM2YzOWUtNmJiYy00MWY3LWIwMTEtZmNkZWQzMWMzMmQ4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDExNDQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2MjA4ZWI0MGVmMDg4OTNmZWIxZDAwMzYwZjVkZGI4YmRjYzg2NWQ1YzRjM2VjOWNmMGI4ZjFlYzAwMzdkNGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.V51JS1NUBnPbsKu_rRi5ozTSYyRYjskijKy3ogVlL1I)
> 
> 问题:价格和手数,时间是对的,但是箭头的判断不对

应该是每家的计算方式不同；请按 issues 模板提交问题
