### ISSUE TITLE
AKShare 接口问题报告：option_lhb_em

### ISSUE THREAD

**Issue by imagemoon0406** [akfamily/akshare#5088]
接口名称：期权龙虎榜-金融期权
接口函数：option_lhb_em
错误描述：在20240712（含）以后，对于symbol="159919", indicator="期权持仓情况-认购持仓量"的参数输入，返回结果中最后两列“净持仓量”和“占总交易量比例”位置串了。
![image](https://github.com/user-attachments/assets/2cc002f7-8735-4eff-8510-539423bdf680)

**Comment by albertandking** [comment]
> 接口名称：期权龙虎榜-金融期权 接口函数：option_lhb_em 错误描述：在20240712（含）以后，对于symbol="159919", indicator="期权持仓情况-认购持仓量"的参数输入，返回结果中最后两列“净持仓量”和“占总交易量比例”位置串了。 ![image](https://private-user-images.githubusercontent.com/57887740/353396086-2cc002f7-8735-4eff-8510-539423bdf680.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzNDE0MDcsIm5iZiI6MTcyMjM0MTEwNywicGF0aCI6Ii81Nzg4Nzc0MC8zNTMzOTYwODYtMmNjMDAyZjctODczNS00ZWZmLTg1MTAtNTM5NDIzYmRmNjgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDEyMDUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwNGMwZDYxOTYzZjkyNjIyMjM5NDM5OTE0MTQ0Y2IxYzUzNzA4YzBhM2NlMzk0OWYyYzMxNjAyMmZlZjgyYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MHUKVHcW9OpWuym_mcBkIG_AIg0oA7-ZpkUMRrHjuOM)

已修复，升级到 AKShare 1.14.45 使用
