### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by stiff-c** [akfamily/akshare#5110]
1. 请先详细阅读文档对应接口的使用方式：https://akshare.akfamily.xyz
2. 操作系统版本，目前只支持 64 位操作系统   【Win11】
3. Python 版本，目前只支持 3.8 以上的版本  【 v3.9】
4. AKShare 版本，请升级到最新版   【v1.14.53】
5. 接口的名称和相应的调用代码   **【ak.stock_zh_a_hist】**
6. 接口报错的截图或描述
    **从8月5日开始调取此接口获取东财沪深A股历史行情数据时，拉不到几条就会报错，有时一条也拉不到。在此之前是没问题的。**
    报错信息如下：
![image](https://github.com/user-attachments/assets/206dfe4d-34a4-4254-b2bd-bfcbf7a60a7d)

7. 期望获得的正确结果

**Comment by albertandking** [comment]
> 5\. stock_zh_a_hist

接口测试稳定
