### ISSUE TITLE
CentOS 7.9安装失败

### ISSUE THREAD

**Issue by random-heap** [akfamily/akshare#5112]
阿里云服务器，Python3.11 CentOS 7.9 安装失败，报错的原因是去Google拉取
depot_tools，无法访问。

![image](https://github.com/user-attachments/assets/052abe22-7870-4ed3-9072-84dcdbf98d86)

请问能否去掉这个，在Windows11是可以安装的。

**Comment by johnlau123** [comment]
> 阿里云服务器，Python3.11 CentOS 7.9安装失败,报错的原因是去谷歌拉取仓库_工具，无法访问。
> 
> ![image](https://private-user-images.githubusercontent.com/54488034/355701763-052abe22-7870-4ed3-9072-84dcdbf98d86.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMDk3OTgsIm5iZiI6MTcyMzEwOTQ5OCwicGF0aCI6Ii81NDQ4ODAzNC8zNTU3MDE3NjMtMDUyYWJlMjItNzg3MC00ZWQzLTkwNzItODRkY2RiZjk4ZDg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDA5MzEzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlMWQ3MWNhZDhlZjAwMTViNDBiMWNkMWUxZWExNjlkYmY0YzA5NTRlZDI3NjEyN2M2MDA2YzQwYTBhMTUxMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Wke1FoCVc3aqIT5DF9GrFuJ4CyeU2u9-diV3cTJYV0Y)
> 
> 请问能否去掉这个,在窗口11是可以安装的。

请问这个问题你解决了吗？求方法

**Comment by li1287044700** [comment]
我也遇到了同样的问题，请问解决没，解决了请告诉我一下 ，谢谢

**Comment by albertandking** [comment]
> 我也遇到了同样的问题，请问解决没，解决了请告诉我一下 ，谢谢

可以安装下 pip install akracer 试试

**Comment by li1287044700** [comment]
> > 我也遇到了同样的问题，请问解决没，解决了请告诉我一下 ，谢谢
> 
> 可以安装下 pip install akracer 试试

akracer 安装成功了，然后我再执行pip install aktools  还是会报同意的错误，环境是阿里云的centos7,python3.9
![image](https://github.com/user-attachments/assets/aeb8bc13-1ebc-484d-bba6-9850b0a1ed18)

**Comment by albertandking** [comment]
> > > 我也遇到了同样的问题，请问解决没，解决了请告诉我一下 ，谢谢
> > 
> > 
> > 可以安装下 pip install akracer 试试
> 
> akracer 安装成功了，然后我再执行pip install aktools 还是会报同意的错误，环境是阿里云的centos7,python3.9 ![image](https://private-user-images.githubusercontent.com/39544878/363901096-aeb8bc13-1ebc-484d-bba6-9850b0a1ed18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNTY2NDAsIm5iZiI6MTcyNTM1NjM0MCwicGF0aCI6Ii8zOTU0NDg3OC8zNjM5MDEwOTYtYWViOGJjMTMtMWViYy00ODRkLWJiYTYtOTg1MGIwYTFlZDE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDA5MzkwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyNDg3MWM5ZmFiZWFlNThmMGJiYzBkNTM4OWJkOWIzZWI2NTZjNmQ4MTI3YTczZTUxY2JiNDFhYWM2Y2YwZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pM0InsZ55wtjHIWeMdfflaa4yvrM9kH7B-PfF5YVV1Q)

已修复，升级到 AKShare 1.14.70 使用
