### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by lixiang2017** [akfamily/akshare#5114]
1. 请先详细阅读文档对应接口的使用方式：https://akshare.akfamily.xyz/

2. 操作系统版本，目前只支持 64 位操作系统 win 64

```bash
 cat /etc/os-release                                                                                         
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

3. Python 版本，目前只支持 3.8 以上的版本 3.10.7
  python3.11.1

4. AKShare 版本，请升级到最新版
已经是最新版本
```bash
pip list  |grep -i akshare
akshare                 1.14.53

[notice] A new release of pip is available: 23.3.1 -> 24.2
[notice] To update, run: pip install --upgrade pip
```

5. 接口的名称和相应的调用代码

```python
❯ python3.11                
Python 3.11.1 (main, Mar 20 2023, 11:38:32) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import akshare as ak
>>> day = '20240801'
>>> ak.stock_zt_pool_em(day)
```

6. 接口报错的截图或描述

![image](https://github.com/user-attachments/assets/121867c8-911c-4ca6-b66d-96b6eeeec3b9)

7. 期望获得的正确结果
    期望获得数据。

**Comment by albertandking** [comment]
> 1. 请先详细阅读文档对应接口的使用方式：https://akshare.akfamily.xyz/
> 2. 操作系统版本，目前只支持 64 位操作系统 win 64
> 
> ```shell
>  cat /etc/os-release                                                                                         
> NAME="Ubuntu"
> VERSION="20.04.6 LTS (Focal Fossa)"
> ID=ubuntu
> ID_LIKE=debian
> PRETTY_NAME="Ubuntu 20.04.6 LTS"
> VERSION_ID="20.04"
> HOME_URL="https://www.ubuntu.com/"
> SUPPORT_URL="https://help.ubuntu.com/"
> BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
> PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
> VERSION_CODENAME=focal
> UBUNTU_CODENAME=focal
> ```
> 
> 3. Python 版本，目前只支持 3.8 以上的版本 3.10.7
>    python3.11.1
> 4. AKShare 版本，请升级到最新版
>    已经是最新版本
> 
> ```shell
> pip list  |grep -i akshare
> akshare                 1.14.53
> 
> [notice] A new release of pip is available: 23.3.1 -> 24.2
> [notice] To update, run: pip install --upgrade pip
> ```
> 
> 5. 接口的名称和相应的调用代码
> 
> ```python
> ❯ python3.11                
> Python 3.11.1 (main, Mar 20 2023, 11:38:32) [GCC 9.4.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import akshare as ak
> >>> day = '20240801'
> >>> ak.stock_zt_pool_em(day)
> ```
> 
> 6. 接口报错的截图或描述
> 
> ![image](https://private-user-images.githubusercontent.com/25242627/355737319-121867c8-911c-4ca6-b66d-96b6eeeec3b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxOTI2MjEsIm5iZiI6MTcyMzE5MjMyMSwicGF0aCI6Ii8yNTI0MjYyNy8zNTU3MzczMTktMTIxODY3YzgtOTExYy00Y2E2LWI2NmQtOTZiNmVlZWVjM2I5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDA4MzIwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4MzY4N2U0NTE2NjgwZGYzZGRkNTg0ZTVkNDVmYmU2YzA0ODQ2YTg1NTRlZjVmMTQwYmY3ODk5NmZjNTk1Y2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3ACWlmNybj6_Zh74lbOY8NmLk3858qQ4eXvEb4sO2xw)
> 
> 7. 期望获得的正确结果
>    期望获得数据。

接口测试正常
