### ISSUE TITLE
同花顺 - 概念板块系列接口不再提供？

### ISSUE THREAD

**Issue by xzz4316** [akfamily/akshare#5116]
礼貌问问，同花顺概念板块相关的接口是都不再提供了吗？

更新akshare版本为1.14.54，运行显示no attribute，查看akshare数据字典也找不到相关接口了。

import  akshare as ak

# 获取同花顺概念板块名单
stock_board_concept_name_ths = ak.stock_board_concept_name_ths()
print(stock_board_concept_name_ths)

# 获取概念历史数据
stock_board_concept_hist_ths = ak.stock_board_concept_hist_ths(start_year=2024, symbol='低空经济')
print(stock_board_concept_hist_ths)

AttributeError: module 'akshare' has no attribute 'stock_board_concept_hist_ths'

隔壁东财的好像还能用，但同一个概念，比如低空经济，比同顺创建的晚了将近两个月。感觉还是同顺在这方面的更新更勤快点。

请心地善良的大佬帮忙检查一下，真的很爱用这个接口

**Comment by albertandking** [comment]
> 礼貌问问，同花顺概念板块相关的接口是都不再提供了吗？
> 
> 更新akshare版本为1.14.54，运行显示no attribute，查看akshare数据字典也找不到相关接口了。
> 
> import akshare as ak
> 
> # 获取同花顺概念板块名单
> stock_board_concept_name_ths = ak.stock_board_concept_name_ths() print(stock_board_concept_name_ths)
> 
> # 获取概念历史数据
> stock_board_concept_hist_ths = ak.stock_board_concept_hist_ths(start_year=2024, symbol='低空经济') print(stock_board_concept_hist_ths)
> 
> AttributeError: module 'akshare' has no attribute 'stock_board_concept_hist_ths'
> 
> 隔壁东财的好像还能用，但同一个概念，比如低空经济，比同顺创建的晚了将近两个月。感觉还是同顺在这方面的更新更勤快点。
> 
> 请心地善良的大佬帮忙检查一下，真的很爱用这个接口

已经移除相关接口
