### ISSUE TITLE
etf的历史溢价数据

### ISSUE THREAD

**Issue by akuri-cyber** [akfamily/akshare#5117]
开发者，你好，我看了文档，没有看到 etf的历史折溢价数据，只有 fund_etf_spot_em() 中有实时折溢价，不知能否提供该数据呢？ 谢谢

**Comment by albertandking** [comment]
> 开发者，你好，我看了文档，没有看到 etf的历史折溢价数据，只有 fund_etf_spot_em() 中有实时折溢价，不知能否提供该数据呢？ 谢谢

有相关数据会更新，可以关注相关开发进度
