### ISSUE TITLE
同花顺-数据中心-资金流向-个股资金流即时接口偶尔会返回13个字段产生错误，建议适配

### ISSUE THREAD

**Issue by samuel-lyu** [akfamily/akshare#5130]
1. 接口的名称和相应的调用代码
```
flow_df = ak.stock_fund_flow_individual(symbol="即时")
```
2. 接口报错的截图或描述
stock_fund_flow_individual接口在开盘日9:30~9:40左右容易出现返回字段个数不匹配错误

```
ValueError: Length mismatch: Expected axis has 13 elements, new values have 10 elements

  File "/opt/quant/app/quant_auto/assets/stock_m_assets.py", line 97, in stock_flow_m_ths
    stock_fund_flow_df = stock_fund_flow_individual_ths()
  File "/opt/quant/app/quant_auto/handlers/akshare_handler.py", line 88, in stock_fund_flow_individual_ths
    flow_df = ak.stock_fund_flow_individual(symbol=symbol)
  File "/usr/local/lib/python3.10/site-packages/akshare/stock_feature/stock_fund_flow.py", line 110, in stock_fund_flow_individual
    big_df.columns = [
  File "/usr/local/lib/python3.10/site-packages/pandas/core/generic.py", line 6002, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/usr/local/lib/python3.10/site-packages/pandas/core/generic.py", line 730, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/usr/local/lib/python3.10/site-packages/pandas/core/internals/managers.py", line 225, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/usr/local/lib/python3.10/site-packages/pandas/core/internals/base.py", line 70, in _validate_set_axis
    raise ValueError(
```
4. 期望获得的正确结果
建议判断返回字段个数，如果超过10个字段，仅截取前10个字段
```
    if symbol == "即时":
        if big_df.shape[1] > 10:
            big_df = big_df.iloc[:, :10]
        big_df.columns = [
            "序号",
            "股票代码",
            "股票简称",
            "最新价",
            "涨跌幅",
            "换手率",
            "流入资金",
            "流出资金",
            "净额",
            "成交额",
        ]
```

**Comment by albertandking** [comment]
> stock_fund_flow_individual



> 1. 接口的名称和相应的调用代码
> 
> ```
> flow_df = ak.stock_fund_flow_individual(symbol="即时")
> ```
> 
> 2. 接口报错的截图或描述
>    stock_fund_flow_individual接口在开盘日9:30~9:40左右容易出现返回字段个数不匹配错误
> 
> ```
> ValueError: Length mismatch: Expected axis has 13 elements, new values have 10 elements
> 
>   File "/opt/quant/app/quant_auto/assets/stock_m_assets.py", line 97, in stock_flow_m_ths
>     stock_fund_flow_df = stock_fund_flow_individual_ths()
>   File "/opt/quant/app/quant_auto/handlers/akshare_handler.py", line 88, in stock_fund_flow_individual_ths
>     flow_df = ak.stock_fund_flow_individual(symbol=symbol)
>   File "/usr/local/lib/python3.10/site-packages/akshare/stock_feature/stock_fund_flow.py", line 110, in stock_fund_flow_individual
>     big_df.columns = [
>   File "/usr/local/lib/python3.10/site-packages/pandas/core/generic.py", line 6002, in __setattr__
>     return object.__setattr__(self, name, value)
>   File "pandas/_libs/properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
>   File "/usr/local/lib/python3.10/site-packages/pandas/core/generic.py", line 730, in _set_axis
>     self._mgr.set_axis(axis, labels)
>   File "/usr/local/lib/python3.10/site-packages/pandas/core/internals/managers.py", line 225, in set_axis
>     self._validate_set_axis(axis, new_labels)
>   File "/usr/local/lib/python3.10/site-packages/pandas/core/internals/base.py", line 70, in _validate_set_axis
>     raise ValueError(
> ```
> 
> 4. 期望获得的正确结果
>    建议判断返回字段个数，如果超过10个字段，仅截取前10个字段
> 
> ```
>     if symbol == "即时":
>         if big_df.shape[1] > 10:
>             big_df = big_df.iloc[:, :10]
>         big_df.columns = [
>             "序号",
>             "股票代码",
>             "股票简称",
>             "最新价",
>             "涨跌幅",
>             "换手率",
>             "流入资金",
>             "流出资金",
>             "净额",
>             "成交额",
>         ]
> ```

可以在本地处理
