### ISSUE TITLE
stock_a_indicator_lg出现ValueError: could not convert string to float: 'null'

### ISSUE THREAD

**Issue by Eric20210907** [akfamily/akshare#5134]
我已经更新到最新版本，但还是出现了这个问题
akshare==1.14.61
python==3.8.18

`---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[3], line 2
      1 import akshare as ak
----> 2 print(ak.stock_a_indicator_lg("000001"))

File ~/anaconda3/envs/AKShare/lib/python3.8/site-packages/akshare/stock_feature/stock_a_indicator.py:86, in stock_a_indicator_lg(symbol)
     81 temp_df = pd.DataFrame(
     82     temp_json["data"]["items"],
     83     columns=temp_json["data"]["fields"],
     84 )
     85 temp_df["trade_date"] = pd.to_datetime(temp_df["trade_date"]).dt.date
---> 86 temp_df[temp_df.columns[1:]] = temp_df[temp_df.columns[1:]].astype(float)
     87 temp_df.sort_values(by=["trade_date"], inplace=True, ignore_index=True)
     88 if len(set(temp_df["trade_date"])) <= 0:

File ~/anaconda3/envs/AKShare/lib/python3.8/site-packages/pandas/core/generic.py:6324, in NDFrame.astype(self, dtype, copy, errors)
   6317     results = [
   6318         self.iloc[:, i].astype(dtype, copy=copy)
   6319         for i in range(len(self.columns))
   6320     ]
   6322 else:
   6323     # else, only a single dtype is given
-> 6324     new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
   6325     return self._constructor(new_data).__finalize__(self, method="astype")
   6327 # GH 33113: handle empty frame or series

File ~/anaconda3/envs/AKShare/lib/python3.8/site-packages/pandas/core/internals/managers.py:451, in BaseBlockManager.astype(self, dtype, copy, errors)
    448 elif using_copy_on_write():
    449     copy = False
--> 451 return self.apply(
    452     "astype",
    453     dtype=dtype,
    454     copy=copy,
    455     errors=errors,
    456     using_cow=using_copy_on_write(),
    457 )

File ~/anaconda3/envs/AKShare/lib/python3.8/site-packages/pandas/core/internals/managers.py:352, in BaseBlockManager.apply(self, f, align_keys, **kwargs)
    350         applied = b.apply(f, **kwargs)
    351     else:
--> 352         applied = getattr(b, f)(**kwargs)
    353     result_blocks = extend_blocks(applied, result_blocks)
    355 out = type(self).from_blocks(result_blocks, self.axes)

File ~/anaconda3/envs/AKShare/lib/python3.8/site-packages/pandas/core/internals/blocks.py:511, in Block.astype(self, dtype, copy, errors, using_cow)
    491 """
    492 Coerce to the new dtype.
    493 
   (...)
    507 Block
    508 """
    509 values = self.values
--> 511 new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
    513 new_values = maybe_coerce_values(new_values)
    515 refs = None

File ~/anaconda3/envs/AKShare/lib/python3.8/site-packages/pandas/core/dtypes/astype.py:242, in astype_array_safe(values, dtype, copy, errors)
    239     dtype = dtype.numpy_dtype
    241 try:
--> 242     new_values = astype_array(values, dtype, copy=copy)
    243 except (ValueError, TypeError):
    244     # e.g. _astype_nansafe can fail on object-dtype of strings
    245     #  trying to convert to float
    246     if errors == "ignore":

File ~/anaconda3/envs/AKShare/lib/python3.8/site-packages/pandas/core/dtypes/astype.py:187, in astype_array(values, dtype, copy)
    184     values = values.astype(dtype, copy=copy)
    186 else:
--> 187     values = _astype_nansafe(values, dtype, copy=copy)
    189 # in pandas we don't store numpy str dtypes, so convert to object
    190 if isinstance(dtype, np.dtype) and issubclass(values.dtype.type, str):

File ~/anaconda3/envs/AKShare/lib/python3.8/site-packages/pandas/core/dtypes/astype.py:138, in _astype_nansafe(arr, dtype, copy, skipna)
    134     raise ValueError(msg)
    136 if copy or is_object_dtype(arr.dtype) or is_object_dtype(dtype):
    137     # Explicit copy, or required since NumPy can't view from / to object.
--> 138     return arr.astype(dtype, copy=True)
    140 return arr.astype(dtype, copy=copy)

ValueError: could not convert string to float: 'null'
`

请问这是接口的问题么，还是什么情况

**Comment by albertandking** [comment]
> 我已经更新到最新版本，但还是出现了这个问题 akshare==1.14.61 python==3.8.18
> 
> `--------------------------------------------------------------------------- ValueError Traceback (most recent call last) Cell In[3], line 2 1 import akshare as ak ----> 2 print(ak.stock_a_indicator_lg("000001"))
> 
> File ~/anaconda3/envs/AKShare/lib/python3.8/site-packages/akshare/stock_feature/stock_a_indicator.py:86, in stock_a_indicator_lg(symbol) 81 temp_df = pd.DataFrame( 82 temp_json["data"]["items"], 83 columns=temp_json["data"]["fields"], 84 ) 85 temp_df["trade_date"] = pd.to_datetime(temp_df["trade_date"]).dt.date ---> 86 temp_df[temp_df.columns[1:]] = temp_df[temp_df.columns[1:]].astype(float) 87 temp_df.sort_values(by=["trade_date"], inplace=True, ignore_index=True) 88 if len(set(temp_df["trade_date"])) <= 0:
> 
> File ~/anaconda3/envs/AKShare/lib/python3.8/site-packages/pandas/core/generic.py:6324, in NDFrame.astype(self, dtype, copy, errors) 6317 results = [ 6318 self.iloc[:, i].astype(dtype, copy=copy) 6319 for i in range(len(self.columns)) 6320 ] 6322 else: 6323 # else, only a single dtype is given -> 6324 new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors) 6325 return self._constructor(new_data).**finalize**(self, method="astype") 6327 # GH 33113: handle empty frame or series
> 
> File ~/anaconda3/envs/AKShare/lib/python3.8/site-packages/pandas/core/internals/managers.py:451, in BaseBlockManager.astype(self, dtype, copy, errors) 448 elif using_copy_on_write(): 449 copy = False --> 451 return self.apply( 452 "astype", 453 dtype=dtype, 454 copy=copy, 455 errors=errors, 456 using_cow=using_copy_on_write(), 457 )
> 
> File ~/anaconda3/envs/AKShare/lib/python3.8/site-packages/pandas/core/internals/managers.py:352, in BaseBlockManager.apply(self, f, align_keys, **kwargs) 350 applied = b.apply(f, **kwargs) 351 else: --> 352 applied = getattr(b, f)(**kwargs) 353 result_blocks = extend_blocks(applied, result_blocks) 355 out = type(self).from_blocks(result_blocks, self.axes)
> 
> File ~/anaconda3/envs/AKShare/lib/python3.8/site-packages/pandas/core/internals/blocks.py:511, in Block.astype(self, dtype, copy, errors, using_cow) 491 """ 492 Coerce to the new dtype. 493 (...) 507 Block 508 """ 509 values = self.values --> 511 new_values = astype_array_safe(values, dtype, copy=copy, errors=errors) 513 new_values = maybe_coerce_values(new_values) 515 refs = None
> 
> File ~/anaconda3/envs/AKShare/lib/python3.8/site-packages/pandas/core/dtypes/astype.py:242, in astype_array_safe(values, dtype, copy, errors) 239 dtype = dtype.numpy_dtype 241 try: --> 242 new_values = astype_array(values, dtype, copy=copy) 243 except (ValueError, TypeError): 244 # e.g. _astype_nansafe can fail on object-dtype of strings 245 # trying to convert to float 246 if errors == "ignore":
> 
> File ~/anaconda3/envs/AKShare/lib/python3.8/site-packages/pandas/core/dtypes/astype.py:187, in astype_array(values, dtype, copy) 184 values = values.astype(dtype, copy=copy) 186 else: --> 187 values = _astype_nansafe(values, dtype, copy=copy) 189 # in pandas we don't store numpy str dtypes, so convert to object 190 if isinstance(dtype, np.dtype) and issubclass(values.dtype.type, str):
> 
> File ~/anaconda3/envs/AKShare/lib/python3.8/site-packages/pandas/core/dtypes/astype.py:138, in _astype_nansafe(arr, dtype, copy, skipna) 134 raise ValueError(msg) 136 if copy or is_object_dtype(arr.dtype) or is_object_dtype(dtype): 137 # Explicit copy, or required since NumPy can't view from / to object. --> 138 return arr.astype(dtype, copy=True) 140 return arr.astype(dtype, copy=copy)
> 
> ValueError: could not convert string to float: 'null' `
> 
> 请问这是接口的问题么，还是什么情况

应该是数据源没有数据

**Comment by Eric20210907** [comment]
用多个网络的多个电脑尝试了一下，legulegu网站已经403了。应该是这个问题
