### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by bigbone1** [akfamily/akshare#5144]
（1）环境信息：widows10, python3.8, akshare-1.14.63

（2）运行示例代码，如下：
    stock_board_industry_spot_em_df = stock_board_industry_spot_em(symbol="小金属")
    print(stock_board_industry_spot_em_df)
    stock_board_industry_cons_em_df = stock_board_industry_cons_em(
        symbol="小金属"
    )
    print(stock_board_industry_cons_em_df)

（3）报错信息：均有几率出现相同报错，信息如下：
![image](https://github.com/user-attachments/assets/d8e6acfb-7f5f-4e4d-b969-12dd84dc6a1c)
报错几率较大，偶尔能跑通，原因不详

**Comment by albertandking** [comment]
> stock_board_industry_cons_em

接口测试正常，注意调用频率

**Comment by xiaopge** [comment]
大佬，有的正常有的不正常，有几十个更新的行业是不能正常调用的，我试了一下有49个，下面这些都不能正常调用。
['油气开采及服务', '煤炭开采加工', '机场航运', '零售', '物流', '公路铁路运输', '互联网电商', '服装家纺', '港口航运', '纺织制造', '农产品加工', '养殖业', '种植业与林业', '石油加工贸易', '造纸', '建筑装饰', '其他电子', '贸易', '厨卫电器', '饮料制造', '电力', '小家电', '其他社会服务', '工业金属', '黑色家电', '白色家电', '金属新材料', '自动化设备', '食品加工制造', '包装印刷', '综合', '建筑材料', '钢铁', 'IT服务', '白酒', '环境治理', '影视院线', '房地产', '家居用品', '旅游及酒店', '汽车服务及其他', '元件', '轨交设备', '其他电源设备', '军工电子', '环保设备', '农化制品', '军工装备', '化学纤维']





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "akfamily/akshare"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月23日(星期五) 下午5:48
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [akfamily/akshare] AKShare 接口问题报告 (Issue #5144)





  
stock_board_industry_cons_em
  
接口测试正常，注意调用频率
