### ISSUE TITLE
调用案例程序出现以下问题

### ISSUE THREAD

**Issue by chenke456** [akfamily/akshare#5153]
![接口问题](https://github.com/user-attachments/assets/e27bb2c0-3ca2-4d58-9ffd-d6895267cd4c)

**Comment by albertandking** [comment]
> ![接口问题](https://private-user-images.githubusercontent.com/26496120/362524819-e27bb2c0-3ca2-4d58-9ffd-d6895267cd4c.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MTk0MjksIm5iZiI6MTcyNDkxOTEyOSwicGF0aCI6Ii8yNjQ5NjEyMC8zNjI1MjQ4MTktZTI3YmIyYzAtM2NhMi00ZDU4LTlmZmQtZDY4OTUyNjdjZDRjLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDA4MTIwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxYzExMGQ2YzU1MTNkZDdmNjk1OGM5NDliZGQzNzEyZTBlMzQwY2YyY2M3ZDRlMmY0MWNkNDk1YmM0NDdmOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xD6cnnS7APm3TTapMtd4OGKVGbdcEoG3S6a-wiZ1Xjo)

请按 issues 要求填写问题
