### ISSUE TITLE
AKShare 接口问题报告 ak.fund_scale_open_sina

### ISSUE THREAD

**Issue by wangzhengli** [akfamily/akshare#5157]
> 欢迎加入《数据科学实战》知识星球，交流财经数据与量化投资相关内容，
> 详细信息参考：https://akshare.akfamily.xyz/learn.html

## 前提

遇到任何问题，请先将您的 AKShare 版本升级到**最新版**，可以通过如下命令升级：

```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

## 如何提交问题

提交问题的同时，请提交以下相关信息，以更精准的解决问题。

**不符合提交规范的 issues 会被关闭！**

**详细问题描述**

1. 请先详细阅读文档对应接口的使用方式：https://akshare.akfamily.xyz
2. 操作系统版本，目前只支持 64 位操作系统
fedora 39
4. Python 版本，目前只支持 3.8 以上的版本
3.10
6. AKShare 版本，请升级到最新版
1.14.67
8. 接口的名称和相应的调用代码
ak.fund_scale_open_sina(symbol='股票型基金')
10. 接口报错的截图或描述
![image](https://github.com/user-attachments/assets/fc047b4b-913a-4054-b8f1-5ec6966abbbd)
12. 期望获得的正确结果

**Comment by albertandking** [comment]
> > 欢迎加入《数据科学实战》知识星球，交流财经数据与量化投资相关内容，
> > 详细信息参考：https://akshare.akfamily.xyz/learn.html
> 
> ## 前提
> 遇到任何问题，请先将您的 AKShare 版本升级到**最新版**，可以通过如下命令升级：
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> ## 如何提交问题
> 提交问题的同时，请提交以下相关信息，以更精准的解决问题。
> 
> **不符合提交规范的 issues 会被关闭！**
> 
> **详细问题描述**
> 
> 1. 请先详细阅读文档对应接口的使用方式：https://akshare.akfamily.xyz
> 2. 操作系统版本，目前只支持 64 位操作系统
>    fedora 39
> 3. Python 版本，目前只支持 3.8 以上的版本
>    3.10
> 4. AKShare 版本，请升级到最新版
>    1.14.67
> 5. 接口的名称和相应的调用代码
>    ak.fund_scale_open_sina(symbol='股票型基金')
> 6. 接口报错的截图或描述
>    ![image](https://private-user-images.githubusercontent.com/68560657/363426401-fc047b4b-913a-4054-b8f1-5ec6966abbbd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxODAyMjMsIm5iZiI6MTcyNTE3OTkyMywicGF0aCI6Ii82ODU2MDY1Ny8zNjM0MjY0MDEtZmMwNDdiNGItOTEzYS00MDU0LWI4ZjEtNWVjNjk2NmFiYmJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAxVDA4Mzg0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxZDA1N2M5NjA1MDdlZDA1MTEwNWQ1NzMxZGYzYzkwMjQxZDkxNDQ3MGNlZjE4N2M5NDY3ZjVjNWIzNmU2ZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.55XKpx9L3jmsJRekcUBTyAJlPj7GFJ5OpFPrqY3j9Qk)
> 7. 期望获得的正确结果

注意数据调用的频率
