### ISSUE TITLE
AKShare 股票 - 深圳中小板与主板合并

### ISSUE THREAD

**Issue by raphaelxiao** [akfamily/akshare#5158]
> 欢迎加入《数据科学实战》知识星球，交流财经数据与量化投资相关内容，
> 详细信息参考：https://akshare.akfamily.xyz/learn.html

## 前提

遇到任何问题，请先将您的 AKShare 版本升级到**最新版**，可以通过如下命令升级：

```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

## 如何提交问题

提交问题的同时，请提交以下相关信息，以更精准的解决问题。

**不符合提交规范的 issues 会被关闭！**

**详细问题描述**

1. 请先详细阅读文档对应接口的使用方式：https://akshare.akfamily.xyz
2. 操作系统版本，目前只支持 64 位操作系统
windows 11

3. Python 版本，目前只支持 3.8 以上的版本
3.11

4. AKShare 版本，请升级到最新版
最新版本

5. 接口的名称和相应的调用代码
接口: stock_szse_summary

目标地址: http://www.szse.cn/market/overview/index.html

描述: 深圳证券交易所-市场总貌-证券类别统计

限量: 单次返回指定 date 的市场总貌数据-证券类别统计(当前交易日的数据需要交易所收盘后统计)

6. 接口报错的截图或描述
因为主板和中小板合并了，所以目标地址的页面内容变了。
目标地址: http://www.szse.cn/market/overview/index.html

7. 期望获得的正确结果

**Comment by albertandking** [comment]
> > 欢迎加入《数据科学实战》知识星球，交流财经数据与量化投资相关内容，
> > 详细信息参考：https://akshare.akfamily.xyz/learn.html
> 
> ## 前提
> 遇到任何问题，请先将您的 AKShare 版本升级到**最新版**，可以通过如下命令升级：
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> ## 如何提交问题
> 提交问题的同时，请提交以下相关信息，以更精准的解决问题。
> 
> **不符合提交规范的 issues 会被关闭！**
> 
> **详细问题描述**
> 
> 1. 请先详细阅读文档对应接口的使用方式：https://akshare.akfamily.xyz
> 2. 操作系统版本，目前只支持 64 位操作系统
>    windows 11
> 3. Python 版本，目前只支持 3.8 以上的版本
>    3.11
> 4. AKShare 版本，请升级到最新版
>    最新版本
> 5. 接口的名称和相应的调用代码
>    接口: stock_szse_summary
> 
> 目标地址: http://www.szse.cn/market/overview/index.html
> 
> 描述: 深圳证券交易所-市场总貌-证券类别统计
> 
> 限量: 单次返回指定 date 的市场总貌数据-证券类别统计(当前交易日的数据需要交易所收盘后统计)
> 
> 6. 接口报错的截图或描述
>    因为主板和中小板合并了，所以目标地址的页面内容变了。
>    目标地址: http://www.szse.cn/market/overview/index.html
> 7. 期望获得的正确结果

接口测试正常
