### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by adm1n007** [akfamily/akshare#5161]
AttributeError: module 'akshare' has no attribute 'stock_zh_a_tick_163'

> 历史分笔数据[](https://akshare.akfamily.xyz/data/stock/stock.html#id30)
> 腾讯财经[](https://akshare.akfamily.xyz/data/stock/stock.html#id31)
> 接口: stock_zh_a_tick_tx
> 
> 目标地址: http://gu.qq.com/sz300494/gp/detail(示例)
> 
> **描述: 每个交易日 16:00 提供当日数据; 如遇到数据缺失, 请使用 ak.stock_zh_a_tick_163() 接口(注意数据会有一定差异)**

**Comment by albertandking** [comment]
> AttributeError: module 'akshare' has no attribute 'stock_zh_a_tick_163'
> 
> > 历史分笔数据[](https://akshare.akfamily.xyz/data/stock/stock.html#id30)
> > 腾讯财经[](https://akshare.akfamily.xyz/data/stock/stock.html#id31)
> > 接口: stock_zh_a_tick_tx
> > 目标地址: [http://gu.qq.com/sz300494/gp/detail(示例)](http://gu.qq.com/sz300494/gp/detail(%E7%A4%BA%E4%BE%8B))
> > **描述: 每个交易日 16:00 提供当日数据; 如遇到数据缺失, 请使用 ak.stock_zh_a_tick_163() 接口(注意数据会有一定差异)**

请按 issues 要求填写，方便 debug

**Comment by George-Duan** [comment]
> AttributeError: module 'akshare' has no attribute 'stock_zh_a_tick_163'
> 
> > 历史分笔数据[](https://akshare.akfamily.xyz/data/stock/stock.html#id30)
> > 腾讯财经[](https://akshare.akfamily.xyz/data/stock/stock.html#id31)
> > 接口: stock_zh_a_tick_tx
> > 目标地址: [http://gu.qq.com/sz300494/gp/detail(示例)](http://gu.qq.com/sz300494/gp/detail(%E7%A4%BA%E4%BE%8B))
> > **描述: 每个交易日 16:00 提供当日数据; 如遇到数据缺失, 请使用 ak.stock_zh_a_tick_163() 接口(注意数据会有一定差异)**

我也遇到这个问题了，我去翻了一下源码，发现方法名是：ak.stock_zh_a_tick_tx_js(symbol="sz000001")
