### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by minilunas** [akfamily/akshare#5166]
1. AKShare 版本，1.14.71
2. 接口的名称 接口: stock_individual_spot_xq

目标地址: https://xueqiu.com/S/SH513520

描述: 雪球-行情中心-个股

3.  相应的调用代码
ak.stock_individual_spot_xq(symbol='SZ000014',timeout=10)
4. 接口报错的截图或描述
无法获取数据，看文档里的测试地址，应该时雪球加了弹框导致
![image](https://github.com/user-attachments/assets/ac793abb-0551-48e9-91ad-af0dcf38deb1)
6. 期望获得的正确结果
能获取数据

**Comment by yq007-rc** [comment]
有解决办法吗

**Comment by albertandking** [comment]
> 1. AKShare 版本，1.14.71
> 2. 接口的名称 接口: stock_individual_spot_xq
> 
> 目标地址: https://xueqiu.com/S/SH513520
> 
> 描述: 雪球-行情中心-个股
> 
> 3. 相应的调用代码
>    ak.stock_individual_spot_xq(symbol='SZ000014',timeout=10)
> 4. 接口报错的截图或描述
>    无法获取数据，看文档里的测试地址，应该时雪球加了弹框导致
>    ![image](https://private-user-images.githubusercontent.com/18046045/364250988-ac793abb-0551-48e9-91ad-af0dcf38deb1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NTExMTYsIm5iZiI6MTcyNTQ1MDgxNiwicGF0aCI6Ii8xODA0NjA0NS8zNjQyNTA5ODgtYWM3OTNhYmItMDU1MS00OGU5LTkxYWQtYWYwZGNmMzhkZWIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDExNTMzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjYzQ2MDY2NmY3MjZhZTMzYTBiOTFlYzBiZDcyY2E4YzE1NmE0MDgxNDJjMzdkOWY0YzlkN2QyNGVhY2IyZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GS3XA9SKp1Bl6rA9Jk3ivYvBldWRFVPMVy2romhmhaM)
> 5. 期望获得的正确结果
>    能获取数据

已修复，升级到 AKShare 1.14.72 使用
