### ISSUE TITLE
能否新增雪球历史行情数据

### ISSUE THREAD

**Issue by inspirits** [akfamily/akshare#5169]
当前已有接口 stock_individual_spot_xq 获取雪球实时行情数据，请问能否增加接口获取雪球历史行情数据？
数据源链接：https://stock.xueqiu.com/v5/stock/chart/kline.json?symbol=SPY&begin=1725598487223&period=day&type=before&count=-284&indicator=kline
谢谢。

**Comment by albertandking** [comment]
> 当前已有接口 stock_individual_spot_xq 获取雪球实时行情数据，请问能否增加接口获取雪球历史行情数据？ 数据源链接：https://stock.xueqiu.com/v5/stock/chart/kline.json?symbol=SPY&begin=1725598487223&period=day&type=before&count=-284&indicator=kline 谢谢。

已有东财和新浪的
