### ISSUE TITLE
像是内存溢出

### ISSUE THREAD

**Issue by liusw02** [akfamily/akshare#5173]
使用 代码     stock_cyq_em_df = ak.stock_cyq_em(symbol=F, adjust="")
版本号
Name: akshare
Version: 1.14.72
python 版本 3.8
错误代码
<--- Last few GCs --->

[9840:000003E722DD6000]     1230 ms: Mark-Compact 17.1 (30.3) -> 15.8 (32.5) MB, pooled: 0 MB, 3.27 / 0.00 ms  (+ 18.5 ms in 0 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 60 ms) (average mu = 0.971, current mu = 0.94[9840:000003E722DD6000]     1295 ms: Mark-Compact 17.0 (32.8) -> 15.8 (32.5) MB, pooled: 0 MB, 27.21 / 0.00 ms  (average mu = 0.934, current mu = 0.579) allocation failure; GC in old space requested

<--- JS stacktrace --->

#
# Fatal JavaScript out of memory: MarkCompactCollector: young object promotion failed
#
<--- Last few GCs --->

[9840:000003ED07F6D000]     1036 ms: Scavenge (interleaved) 18.8 (28.8) -> 14.5 (29.5) MB, pooled: 0 MB, 2.12 / 0.00 ms  (average mu = 0.983, current mu = 0.983) task; 
[9840:000003ED07F6D000]     1145 ms: Mark-Compact 18.7 (30.5) -> 16.2 (33.0) MB, pooled: 0 MB, 4.96 / 0.00 ms  (+ 18.9 ms in 0 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 52 ms) (average mu = 0.968, current mu = 0.93

<--- JS stacktrace --->

#
# Fatal JavaScript out of memory: MarkCompactCollector: young object promotion failed
#
==== C stack trace ===============================

	(No symbol) [0x00007FF8D1EF2D6B]
	(No symbol) [0x00007FF8D1E69E47]
	(No symbol) [0x00007FF8D1E62F7A]
	(No symbol) [0x00007FF8D0E9DC9C]
	(No symbol) [0x00007FF8D10538F7]
	(No symbol) [0x00007FF8D1090B91]
	(No symbol) [0x00007FF8D1090480]
	(No symbol) [0x00007FF8D1090060]
	(No symbol) [0x00007FF8D109ECA8]
	(No symbol) [0x00007FF8D1EF3924]
	(No symbol) [0x00007FF8D1EF3CE2]
	(No symbol) [0x00007FF8D1092620]
	(No symbol) [0x00007FF8D107FD4F]
	(No symbol) [0x00007FF8D10794D4]
	(No symbol) [0x00007FF8D1056C54]
	(No symbol) [0x00007FF8D10562C7]
	(No symbol) [0x00007FF8D106BED0]
	(No symbol) [0x00007FF8D106B9A4]
	(No symbol) [0x00007FF8D18035E5]

进程已结束,退出代码-2147483645

**Comment by albertandking** [comment]
> 使用 代码 stock_cyq_em_df = ak.stock_cyq_em(symbol=F, adjust="") 版本号 Name: akshare Version: 1.14.72 python 版本 3.8 错误代码 <--- Last few GCs --->
> 
> [9840:000003E722DD6000] 1230 ms: Mark-Compact 17.1 (30.3) -> 15.8 (32.5) MB, pooled: 0 MB, 3.27 / 0.00 ms (+ 18.5 ms in 0 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 60 ms) (average mu = 0.971, current mu = 0.94[9840:000003E722DD6000] 1295 ms: Mark-Compact 17.0 (32.8) -> 15.8 (32.5) MB, pooled: 0 MB, 27.21 / 0.00 ms (average mu = 0.934, current mu = 0.579) allocation failure; GC in old space requested
> 
> <--- JS stacktrace --->
> 
> # Fatal JavaScript out of memory: MarkCompactCollector: young object promotion failed
> <--- Last few GCs --->
> 
> [9840:000003ED07F6D000] 1036 ms: Scavenge (interleaved) 18.8 (28.8) -> 14.5 (29.5) MB, pooled: 0 MB, 2.12 / 0.00 ms (average mu = 0.983, current mu = 0.983) task; [9840:000003ED07F6D000] 1145 ms: Mark-Compact 18.7 (30.5) -> 16.2 (33.0) MB, pooled: 0 MB, 4.96 / 0.00 ms (+ 18.9 ms in 0 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 52 ms) (average mu = 0.968, current mu = 0.93
> 
> <--- JS stacktrace --->
> 
> # Fatal JavaScript out of memory: MarkCompactCollector: young object promotion failed
> ==== C stack trace ===============================
> 
> ```
> (No symbol) [0x00007FF8D1EF2D6B]
> (No symbol) [0x00007FF8D1E69E47]
> (No symbol) [0x00007FF8D1E62F7A]
> (No symbol) [0x00007FF8D0E9DC9C]
> (No symbol) [0x00007FF8D10538F7]
> (No symbol) [0x00007FF8D1090B91]
> (No symbol) [0x00007FF8D1090480]
> (No symbol) [0x00007FF8D1090060]
> (No symbol) [0x00007FF8D109ECA8]
> (No symbol) [0x00007FF8D1EF3924]
> (No symbol) [0x00007FF8D1EF3CE2]
> (No symbol) [0x00007FF8D1092620]
> (No symbol) [0x00007FF8D107FD4F]
> (No symbol) [0x00007FF8D10794D4]
> (No symbol) [0x00007FF8D1056C54]
> (No symbol) [0x00007FF8D10562C7]
> (No symbol) [0x00007FF8D106BED0]
> (No symbol) [0x00007FF8D106B9A4]
> (No symbol) [0x00007FF8D18035E5]
> ```
> 
> 进程已结束,退出代码-2147483645

目前该接口测试正常；注意传入的 symbol
