### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by HolyLl** [akfamily/akshare#5179]
stock_zh_a_hist这个接口无法获取沪深300的数据,这是一个指数数据，现在的接口访问000300会直接报错，腾讯的接口可以通过sh000300获取到沪深300数据，但是每天更新的很慢
    stock_zh_a_hist_tx_df = ak.stock_zh_a_hist_tx(symbol="sh000300", start_date="20240911",
                                                  end_date="20240911",
                                                  adjust="qfq")

    stock_zh_a_hist_df = ak.stock_zh_a_hist(symbol="000300", period="daily", start_date="20240911", end_date="20240911",
                                            adjust="qfq")
![获取000300数据](https://github.com/user-attachments/assets/c9d44cbc-4265-49e5-a249-b265463df23c)
![普通历史数据](https://github.com/user-attachments/assets/fc422fc7-0c62-4745-876a-a18cd9bf94f8)
![腾讯获取000300](https://github.com/user-attachments/assets/1ea57902-6408-42b9-a66c-459cbfdd175f)
![指数历史数据](https://github.com/user-attachments/assets/b927ffb2-066d-43d0-8066-f2c0b50e2923)
希望可以新增https://quote.eastmoney.com/zs000300.html东财的指数历史股票数据接口

**Comment by HolyLl** [comment]
https://quote.eastmoney.com/zs000300.html           是这个连接

**Comment by albertandking** [comment]
> stock_zh_a_hist这个接口无法获取沪深300的数据,这是一个指数数据，现在的接口访问000300会直接报错，腾讯的接口可以通过sh000300获取到沪深300数据，但是每天更新的很慢 stock_zh_a_hist_tx_df = ak.stock_zh_a_hist_tx(symbol="sh000300", start_date="20240911", end_date="20240911", adjust="qfq")
> 
> ```
> stock_zh_a_hist_df = ak.stock_zh_a_hist(symbol="000300", period="daily", start_date="20240911", end_date="20240911",
>                                         adjust="qfq")
> ```
> 
> ![获取000300数据](https://private-user-images.githubusercontent.com/81008724/366755943-c9d44cbc-4265-49e5-a249-b265463df23c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMjY3MTcsIm5iZiI6MTcyNjEyNjQxNywicGF0aCI6Ii84MTAwODcyNC8zNjY3NTU5NDMtYzlkNDRjYmMtNDI2NS00OWU1LWEyNDktYjI2NTQ2M2RmMjNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDA3MzMzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmOGZjMjQ2MGIwY2ZiZWFiYzc3OTdjYTNmZWZmNzRkNzY0ZjA5Y2EwOGVjNDMwNjZlMGEyZGQ1ODllYTVjMGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SiRWUjEsEYZm0ROw3LekmIS-sQP9cBJhoy0kXGUm91I) ![普通历史数据](https://private-user-images.githubusercontent.com/81008724/366755953-fc422fc7-0c62-4745-876a-a18cd9bf94f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMjY3MTcsIm5iZiI6MTcyNjEyNjQxNywicGF0aCI6Ii84MTAwODcyNC8zNjY3NTU5NTMtZmM0MjJmYzctMGM2Mi00NzQ1LTg3NmEtYTE4Y2Q5YmY5NGY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDA3MzMzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyY2UxNDAyYTExZjY5ZmM4MjA4ZGI5Njc3ZjBmNjA4NjIxYjc3ZWNlYzQwYWU0NzdjZTVmNzhhMDVjMjZiOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Qnb6vo8u80MdhoRa5R8v7nQx_GbTQjgv_W3CKe3wQGo) ![腾讯获取000300](https://private-user-images.githubusercontent.com/81008724/366755963-1ea57902-6408-42b9-a66c-459cbfdd175f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMjY3MTcsIm5iZiI6MTcyNjEyNjQxNywicGF0aCI6Ii84MTAwODcyNC8zNjY3NTU5NjMtMWVhNTc5MDItNjQwOC00MmI5LWE2NmMtNDU5Y2JmZGQxNzVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDA3MzMzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5OTgzNjAyZjhjNDYyYmJlOWI5NzgwM2U1YjViYWViMWEwZTExZWM4NmUwZDgwOWNkY2RhMWM5OWZjYzViNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eeLHfn1ammYE5fbPGgFe35sehNaEYJkGK6f68kwKLyc) ![指数历史数据](https://private-user-images.githubusercontent.com/81008724/366755968-b927ffb2-066d-43d0-8066-f2c0b50e2923.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMjY3MTcsIm5iZiI6MTcyNjEyNjQxNywicGF0aCI6Ii84MTAwODcyNC8zNjY3NTU5NjgtYjkyN2ZmYjItMDY2ZC00M2QwLTgwNjYtZjJjMGI1MGUyOTIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDA3MzMzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyOTNmYjkwOTMzMzg0NTVmZWVlZjE3NDU0NmQxZTc3MjRlOWZjZjBmYmEyNDY4MTFiNTJkYmE4Njg3YzRjNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AKL731Jp4wWPcWe3SAAkwgUqHYQw1y5dU4yu3ImpNjE) 希望可以新增[https://quote.eastmoney.com/zs000300.html东财的指数历史股票数据接口](https://quote.eastmoney.com/zs000300.html%E4%B8%9C%E8%B4%A2%E7%9A%84%E6%8C%87%E6%95%B0%E5%8E%86%E5%8F%B2%E8%82%A1%E7%A5%A8%E6%95%B0%E6%8D%AE%E6%8E%A5%E5%8F%A3)

请按 issues 格式提交
