### ISSUE TITLE
AKShare 接口问题报告index_value_hist_funddb无法使用

### ISSUE THREAD

**Issue by sourgelp** [akfamily/akshare#5182]
1. AKShare 已升级至1.14.74

index_value_hist_funddb和index_value_name_funddb 均无法使用

![微信截图_20240913164648](https://github.com/user-attachments/assets/c3406091-3712-42fc-a953-84aa83a31fa6)

**Comment by albertandking** [comment]
> 1. AKShare 已升级至1.14.74
> 
> index_value_hist_funddb和index_value_name_funddb 均无法使用
> 
> ![微信截图_20240913164648](https://private-user-images.githubusercontent.com/37536592/367219793-c3406091-3712-42fc-a953-84aa83a31fa6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMTgwODUsIm5iZiI6MTcyNjIxNzc4NSwicGF0aCI6Ii8zNzUzNjU5Mi8zNjcyMTk3OTMtYzM0MDYwOTEtMzcxMi00MmZjLWE5NTMtODRhYTgzYTMxZmE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDA4NTYyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkOWNmNTBhMWM0OTQ4MjAwNWYzMWU4NjFjOWJkMThmMGM0NjRkY2M0NmY5ODdlYTQ1N2YxY2NjYWJlMjQzY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yJuqA0KLDEYZkd7GSXf2Z4AT_EGcrAKhA1n3SGJwP0Q)

请按 issues 格式提交问题
