### ISSUE TITLE
获取B股时出现bug

### ISSUE THREAD

**Issue by jasonudu** [akfamily/akshare#5185]
**详细问题描述**

2. 操作系统版本，目前只支持 64 位操作系统   
    Win11
4. Python 版本，目前只支持 3.8 以上的版本
    3.10.10
6. AKShare 版本，请升级到最新版
     1.14.16
8. 接口的名称和相应的调用代码
接口：   
def stock_zh_b_daily(
    symbol: str = "sh900901",
    start_date: str = "19900101",
    end_date: str = "21000118",
    adjust: str = "",
) -> pd.DataFrame:     

错误的地方：

    temp_df = pd.merge(
        data_df, amount_data_df, left_index=True, right_index=True, how="outer"
    )
    try:
        # try for pandas >= 2.1.0
        temp_df.ffill(inplace=True)
    except Exception as e:
        try:
        # try for pandas < 2.1.0          
            temp_df.fillna(method="ffill", inplace=True)
        except Exception as e:
                print("Error:", e)
    temp_df = temp_df.astype(float)
    temp_df["amount"] = temp_df["amount"] * 10000
    temp_df["turnover"] = temp_df["volume"] / temp_df["amount"]
    temp_df.columns = [
        "open",
        "high",
        "low",
        "close",
        "volume",
        "outstanding_share",
        "turnover",
    ]

10. 接口报错的截图或描述
      错误代码   ：
    temp_df["amount"] = temp_df["amount"] * 10000

     提示找不到字段“amount”
      
     错误原因分析：应该是这个merge语句中两个表data_df，amount_data_df都有amount，所以合并后默认变为amount_x和amount_y，估计是网页格式变化，新增了列amount所致。
       temp_df = pd.merge(
        data_df, amount_data_df, left_index=True, right_index=True, how="outer"
    )

   

12. 期望获得的正确结果

**Comment by albertandking** [comment]
> **详细问题描述**
> 
> 2. 操作系统版本，目前只支持 64 位操作系统
>    Win11
> 3. Python 版本，目前只支持 3.8 以上的版本
>    3.10.10
> 4. AKShare 版本，请升级到最新版
>    1.14.16
> 5. 接口的名称和相应的调用代码
>    接口：
>    def stock_zh_b_daily(
>    symbol: str = "sh900901",
>    start_date: str = "19900101",
>    end_date: str = "21000118",
>    adjust: str = "",
>    ) -> pd.DataFrame:
> 
> 错误的地方：
> 
> ```
> temp_df = pd.merge(
>     data_df, amount_data_df, left_index=True, right_index=True, how="outer"
> )
> try:
>     # try for pandas >= 2.1.0
>     temp_df.ffill(inplace=True)
> except Exception as e:
>     try:
>     # try for pandas < 2.1.0          
>         temp_df.fillna(method="ffill", inplace=True)
>     except Exception as e:
>             print("Error:", e)
> temp_df = temp_df.astype(float)
> temp_df["amount"] = temp_df["amount"] * 10000
> temp_df["turnover"] = temp_df["volume"] / temp_df["amount"]
> temp_df.columns = [
>     "open",
>     "high",
>     "low",
>     "close",
>     "volume",
>     "outstanding_share",
>     "turnover",
> ]
> ```
> 
> 10. 接口报错的截图或描述
>     错误代码   ：
>     temp_df["amount"] = temp_df["amount"] * 10000
>     提示找不到字段“amount”
>     错误原因分析：应该是这个merge语句中两个表data_df，amount_data_df都有amount，所以合并后默认变为amount_x和amount_y，估计是网页格式变化，新增了列amount所致。
>     temp_df = pd.merge(
>     data_df, amount_data_df, left_index=True, right_index=True, how="outer"
>     )
> 11. 期望获得的正确结果

最新版接口测试正常
