### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by OkabeRintarou** [akfamily/akshare#5189]
AKShare 版本，1.14.72
接口的名称 接口: stock_individual_spot_xq
目标地址: https://xueqiu.com/S/SH513520

描述: 雪球-行情中心-个股

相应的调用代码
ak.stock_individual_spot_xq(symbol='SZ000014',timeout=10)
接口报错的截图或描述
无法获取数据.

**Comment by albertandking** [comment]
> AKShare 版本，1.14.72 接口的名称 接口: stock_individual_spot_xq 目标地址: https://xueqiu.com/S/SH513520
> 
> 描述: 雪球-行情中心-个股
> 
> 相应的调用代码 ak.stock_individual_spot_xq(symbol='SZ000014',timeout=10) 接口报错的截图或描述 无法获取数据.

感谢反馈问题，升级到 AKShare 1.14.78 使用
