### ISSUE TITLE
AKShare 美股接口含义疑问

### ISSUE THREAD

**Issue by DeadCardassian** [akfamily/akshare#5193]
我没有软件问题，但我不清楚stock_us_spot_em_df = ak.stock_us_spot_em()获得的股票代码前缀的含义，比如105.AAPL，106.NVO，105,106,和107分别代表什么？

**Comment by albertandking** [comment]
> 我没有软件问题，但我不清楚stock_us_spot_em_df = ak.stock_us_spot_em()获得的股票代码前缀的含义，比如105.AAPL，106.NVO，105,106,和107分别代表什么？

应该是东方财富内部的代码，可以问下东财

**Comment by DeadCardassian** [comment]
请问东财的联系方式是？
