### ISSUE TITLE
AKShare 接口需求，新增北京交易所财务数据下载

### ISSUE THREAD

**Issue by jasonudu** [akfamily/akshare#5194]
2. 操作系统版本，目前只支持 64 位操作系统
    win11
4. Python 版本，目前只支持 3.8 以上的版本
    3.10.10
6. AKShare 版本，请升级到最新版
    akshare-1.14.78
8. 接口的名称和相应的调用代码    
    stock_zcfz_em_df = ak.stock_zcfz_em(date='20240630')
  
10. 接口报错的截图或描述
    接口只返回沪深两市的数据，没有北京交易所的股票数据
    
    经过核实，是因为网站上把沪深和北京分成两个页面展示

12. 期望获得的正确结果
    希望能够新增功能，或者合并功能，能够获得所有a股的相关数据

**Comment by albertandking** [comment]
> 2. 操作系统版本，目前只支持 64 位操作系统
>    win11
> 3. Python 版本，目前只支持 3.8 以上的版本
>    3.10.10
> 4. AKShare 版本，请升级到最新版
>    akshare-1.14.78
> 5. 接口的名称和相应的调用代码
>    stock_zcfz_em_df = ak.stock_zcfz_em(date='20240630')
> 6. 接口报错的截图或描述
>    接口只返回沪深两市的数据，没有北京交易所的股票数据
>    经过核实，是因为网站上把沪深和北京分成两个页面展示
> 7. 期望获得的正确结果
>    希望能够新增功能，或者合并功能，能够获得所有a股的相关数据

感谢反馈问题，新增 stock_zcfz_bj_em 接口，升级到 AKShare 1.14.79 使用
