### ISSUE TITLE
AKShare 接口问题报告(股票热度-问财数据只能返回最多5000只股票结果)

### ISSUE THREAD

**Issue by triplesuper** [akfamily/akshare#5197]
**详细问题描述**

1. 操作系统版本：win10 64位
2. Python 版本：python3.9
3. AKShare 版本：akshare-1.14.79
4. 接口的名称和相应的调用代码：股票热度数据，ak.stock_hot_rank_wc()
5. 接口报错的截图或描述：问财的股票热度数据只能返回最多5000个结果，而实际结果目前有5359个
6. 期望获得的正确结果：返回全部的股票热度数据。

**Comment by albertandking** [comment]
> **详细问题描述**
> 
> 1. 操作系统版本：win10 64位
> 2. Python 版本：python3.9
> 3. AKShare 版本：akshare-1.14.79
> 4. 接口的名称和相应的调用代码：股票热度数据，ak.stock_hot_rank_wc()
> 5. 接口报错的截图或描述：问财的股票热度数据只能返回最多5000个结果，而实际结果目前有5359个
> 6. 期望获得的正确结果：返回全部的股票热度数据。

跟数据源是一致的
