### ISSUE TITLE
AKShare 沪港深通 接口问题报告

### ISSUE THREAD

**Issue by lawrencesun1011** [akfamily/akshare#5199]
2. 操作系统版本，目前只支持 64 位操作系统：
macos
4. Python 版本，目前只支持 3.8 以上的版本
python3.11
6. AKShare 版本，请升级到最新：
最新版本akshare-1.14.80
8. 接口的名称和相应的调用代码：
ak.stock_hsgt_hist_em(symbol="北向资金")
10. 接口报错的截图或描述: 
8.16号后数据没有了，应该是北向披露规则变了，接口换了
<img width="901" alt="image" src="https://github.com/user-attachments/assets/e723a0bf-c7d8-42dd-ba91-ce1d3e4b1a60">

12. 期望获得的正确结果
能够获取全面的北向历史数据

**Comment by albertandking** [comment]
> 2. 操作系统版本，目前只支持 64 位操作系统：
>    macos
> 3. Python 版本，目前只支持 3.8 以上的版本
>    python3.11
> 4. AKShare 版本，请升级到最新：
>    最新版本akshare-1.14.80
> 5. 接口的名称和相应的调用代码：
>    ak.stock_hsgt_hist_em(symbol="北向资金")
> 6. 接口报错的截图或描述:
>    8.16号后数据没有了，应该是北向披露规则变了，接口换了
> 
> <img alt="image" width="901" src="https://private-user-images.githubusercontent.com/148425920/369795940-e723a0bf-c7d8-42dd-ba91-ce1d3e4b1a60.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNDcyMTksIm5iZiI6MTcyNzM0NjkxOSwicGF0aCI6Ii8xNDg0MjU5MjAvMzY5Nzk1OTQwLWU3MjNhMGJmLWM3ZDgtNDJkZC1iYTkxLWNlMWQzZTRiMWE2MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNlQxMDM1MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMjM5MmNmNTk1NTIzNDc2NGVmZWRlNjZlY2Q1Yzk5OTdjNTQ4OGUxZDQ4YjQzZDg4MmE4N2NlNzc1NTY3ZmUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ku2gAdJ3Izu87scQ_yEBGhRn3YUjfxhUd7qLNRivvGg">
> 12. 期望获得的正确结果
>     能够获取全面的北向历史数据

应该是的
