### ISSUE TITLE
akshare wci issue 

### ISSUE THREAD

**Issue by ericwbzhang** [akfamily/akshare#5203]
ak.drewry_wci_index() does not work. 

Python 3.11.5 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:26:23) [MSC v.1916 64 bit (AMD64)] on win32
import akshare as ak
ak.__version__
'1.14.83'
ak.drewry_wci_index()
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2023.3.6\plugins\python\helpers\pydev\pydevconsole.py", line 364, in runcode
    coro = func()
           ^^^^^^
  File "<input>", line 1, in <module>
  File "C:\Users\ericw\anaconda3\envs\sysa4\Lib\site-packages\akshare\index\index_drewry.py", line 40, in drewry_wci_index
    temp_df = pd.DataFrame(data_json["elements"][2]["data"][symbol_map[symbol]])
                           ~~~~~~~~~~~~~~~~~~~~~^^^
KeyError: 2

**Comment by albertandking** [comment]
> ak.drewry_wci_index() does not work.
> 
> Python 3.11.5 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:26:23) [MSC v.1916 64 bit (AMD64)] on win32 import akshare as ak ak.**version** '1.14.83' ak.drewry_wci_index() Traceback (most recent call last): File "C:\Program Files\JetBrains\PyCharm 2023.3.6\plugins\python\helpers\pydev\pydevconsole.py", line 364, in runcode coro = func() ^^^^^^ File "", line 1, in File "C:\Users\ericw\anaconda3\envs\sysa4\Lib\site-packages\akshare\index\index_drewry.py", line 40, in drewry_wci_index temp_df = pd.DataFrame(data_json["elements"][2]["data"][symbol_map[symbol]]) ~~~~~~~~~~~~~~~~~~~~~^^^ KeyError: 2

已修复该问题，升级到 AKShare 1.14.84 使用，提交 issues 请按模板反馈
