### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by zjzlovezjz** [akfamily/akshare#5211]
#### 问题描述
+ 我是一个java开发期货策略的程序员，在使用aktools的时候，我需要调用futures_zh_spot接口获取期货的实时行情数据，在本地开发调试的时候一切顺利，部署到服务器的时候，调用接口获取期货行情数据时报错，报错内容如下：
+ Microsoft Windows [版本 6.3.9600]
(c) 2013 Microsoft Corporation。保留所有权利。

C:\Users\Administrator>python -m aktools
请访问：http://127.0.0.1:8080/version 来获取最新的库版本信息，确保使用最新版本的
 AKShare 和 AKTools
当前的 AKTools 版本为：0.0.86，AKShare 版本为：1.14.64
点击打开 HTTP API 主页：http://127.0.0.1:8080/
点击打开接口导览：http://127.0.0.1:8080/docs
[32mINFO[0m:     Started server process [[36m2456[0m]
[32mINFO[0m:     Waiting for application startup.
[32mINFO[0m:     Application startup complete.
[32mINFO[0m:     Uvicorn running on [1mhttp://127.0.0.1:8080[0m (Press CTRL+
C to quit)
[32mINFO[0m:     127.0.0.1:50388 - "[1mGET /api/public/futures_zh_spot?symbol
=C2411&market=CF&adjust=0 HTTP/1.1[0m" [91m500 Internal Server Error[0m
[31mERROR[0m:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-
packages\uvicorn\protocols\http\h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-
packages\uvicorn\middleware\proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-
packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-
packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-
packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-
packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-
packages\starlette\middleware\cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-
packages\starlette\middleware\exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-
packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-
packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-
packages\starlette\routing.py", line 754, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-
packages\starlette\routing.py", line 774, in app
    await route.handle(scope, receive, send)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-
packages\starlette\routing.py", line 295, in handle
    await self.app(scope, receive, send)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-
packages\starlette\routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-
packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-
packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-
packages\starlette\routing.py", line 74, in app
    response = await f(request)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-
packages\fastapi\routing.py", line 297, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-
packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-
packages\starlette\concurrency.py", line 42, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-
packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-
packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-
packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-
packages\aktools\core\api.py", line 162, in root
    received_df = eval("ak." + item_id + f"({eval_str})")
  File "<string>", line 1, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-
packages\akshare\futures\futures_zh_sina.py", line 241, in futures_zh_spot
    [
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-
packages\akshare\futures\futures_zh_sina.py", line 242, in <listcomp>
    item.strip().split("=")[1].split(",")
IndexError: list index out of range
#### 核心报错内容是
+  Exception in ASGI application
#### 目前未解决，请求解答，谢谢。

**Comment by zjzlovezjz** [comment]
服务器使用的是windows server 2012 其他使用aktools的其他接口不受影响，就是获取期货行情数据的接口会有这个问题，本地开发调试没事，部署到服务器的时候，生产环境会报错。

**Comment by albertandking** [comment]
> #### 问题描述
> * 我是一个java开发期货策略的程序员，在使用aktools的时候，我需要调用futures_zh_spot接口获取期货的实时行情数据，在本地开发调试的时候一切顺利，部署到服务器的时候，调用接口获取期货行情数据时报错，报错内容如下：
> * Microsoft Windows [版本 6.3.9600]
>   (c) 2013 Microsoft Corporation。保留所有权利。
> 
> C:\Users\Administrator>python -m aktools 请访问：http://127.0.0.1:8080/version 来获取最新的库版本信息，确保使用最新版本的 AKShare 和 AKTools 当前的 AKTools 版本为：0.0.86，AKShare 版本为：1.14.64 点击打开 HTTP API 主页：http://127.0.0.1:8080/ 点击打开接口导览：http://127.0.0.1:8080/docs �[32mINFO�[0m: Started server process [�[36m2456�[0m] �[32mINFO�[0m: Waiting for application startup. �[32mINFO�[0m: Application startup complete. �[32mINFO�[0m: Uvicorn running on �[1mhttp://127.0.0.1:8080�[0m (Press CTRL+ C to quit) �[32mINFO�[0m: 127.0.0.1:50388 - "�[1mGET /api/public/futures_zh_spot?symbol =C2411&market=CF&adjust=0 HTTP/1.1�[0m" �[91m500 Internal Server Error�[0m �[31mERROR�[0m: Exception in ASGI application Traceback (most recent call last): File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site- packages\uvicorn\protocols\http\h11_impl.py", line 406, in run_asgi result = await app( # type: ignore[func-returns-value] File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site- packages\uvicorn\middleware\proxy_headers.py", line 70, in **call** return await self.app(scope, receive, send) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site- packages\fastapi\applications.py", line 1054, in **call** await super().**call**(scope, receive, send) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site- packages\starlette\applications.py", line 123, in **call** await self.middleware_stack(scope, receive, send) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site- packages\starlette\middleware\errors.py", line 186, in **call** raise exc File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site- packages\starlette\middleware\errors.py", line 164, in **call** await self.app(scope, receive, _send) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site- packages\starlette\middleware\cors.py", line 85, in **call** await self.app(scope, receive, send) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site- packages\starlette\middleware\exceptions.py", line 65, in **call** await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site- packages\starlette_exception_handler.py", line 64, in wrapped_app raise exc File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site- packages\starlette_exception_handler.py", line 53, in wrapped_app await app(scope, receive, sender) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site- packages\starlette\routing.py", line 754, in **call** await self.middleware_stack(scope, receive, send) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site- packages\starlette\routing.py", line 774, in app await route.handle(scope, receive, send) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site- packages\starlette\routing.py", line 295, in handle await self.app(scope, receive, send) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site- packages\starlette\routing.py", line 77, in app await wrap_app_handling_exceptions(app, request)(scope, receive, send) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site- packages\starlette_exception_handler.py", line 64, in wrapped_app raise exc File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site- packages\starlette_exception_handler.py", line 53, in wrapped_app await app(scope, receive, sender) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site- packages\starlette\routing.py", line 74, in app response = await f(request) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site- packages\fastapi\routing.py", line 297, in app raw_response = await run_endpoint_function( File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site- packages\fastapi\routing.py", line 212, in run_endpoint_function return await run_in_threadpool(dependant.call, **values) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site- packages\starlette\concurrency.py", line 42, in run_in_threadpool return await anyio.to_thread.run_sync(func, *args) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site- packages\anyio\to_thread.py", line 56, in run_sync return await get_async_backend().run_sync_in_worker_thread( File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site- packages\anyio_backends_asyncio.py", line 2177, in run_sync_in_worker_thread return await future File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site- packages\anyio_backends_asyncio.py", line 859, in run result = context.run(func, *args) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site- packages\aktools\core\api.py", line 162, in root received_df = eval("ak." + item_id + f"({eval_str})") File "", line 1, in File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site- packages\akshare\futures\futures_zh_sina.py", line 241, in futures_zh_spot [ File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site- packages\akshare\futures\futures_zh_sina.py", line 242, in item.strip().split("=")[1].split(",") IndexError: list index out of range
> 
> #### 核心报错内容是
> * Exception in ASGI application
> 
> #### 目前未解决，请求解答，谢谢。

目前接口测试是正常的；该接口不能频繁访问，会被封禁 IP 一段时间，建议控制调用的频率；另外可以考虑升级下系统，会不会是依赖库有冲突！
