### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by nbnc003** [akfamily/akshare#5213]
接口都挂了？今天所有的接口都提示：
ConnectionError: HTTPConnectionPool(host='80.push2.eastmoney.com', port=80): Max retries exceeded with url: /api/qt/clist/get?pn=1&pz=50000&po=1&np=1&ut=bd1d9ddb04089700cf9c27f6f7426281&fltt=2&invt=2&fid=f3&fs=m%3A1+t%3A2%2Cm%3A1+t%3A23&fields=f12&_=1623833739532 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002080C5C3C70>: Failed to establish a new connection: [WinError 10051] 向一个无法连接的网络尝试了一个套接字操作。'))

**Comment by nbnc003** [comment]
我知道了，貌似现在所有的接口都被墙了？我开了机场可以使用了……顺便问一句，有没有地址可以让我配置机场用于强制走代理？现在走全局有点难受

**Comment by albertandking** [comment]
> 接口都挂了？今天所有的接口都提示： ConnectionError: HTTPConnectionPool(host='80.push2.eastmoney.com', port=80): Max retries exceeded with url: /api/qt/clist/get?pn=1&pz=50000&po=1&np=1&ut=bd1d9ddb04089700cf9c27f6f7426281&fltt=2&invt=2&fid=f3&fs=m%3A1+t%3A2%2Cm%3A1+t%3A23&fields=f12&_=1623833739532 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002080C5C3C70>: Failed to establish a new connection: [WinError 10051] 向一个无法连接的网络尝试了一个套接字操作。'))

请按 issues 模板提交问题，目前测试正常
