### ISSUE TITLE
如何获取某个基金的最近一个月内的单位净值等数据？

### ISSUE THREAD

**Issue by retioa11** [akfamily/akshare#5216]
`fund_open_fund_info_em_df = ak.fund_open_fund_info_em(symbol="710001", indicator="单位净值走势", period="1月")`
使用上面的代码，period="1月"，结果获取的是成立来的。
![4498d3379f671fae7b77f4ebdfbbda7](https://github.com/user-attachments/assets/8cae6957-4d2b-4b9d-8e6b-4c283cbe75e9)

**Comment by albertandking** [comment]
> `fund_open_fund_info_em_df = ak.fund_open_fund_info_em(symbol="710001", indicator="单位净值走势", period="1月")` 使用上面的代码，period="1月"，结果获取的是成立来的。 ![4498d3379f671fae7b77f4ebdfbbda7](https://private-user-images.githubusercontent.com/81463532/372397538-8cae6957-4d2b-4b9d-8e6b-4c283cbe75e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4ODIyMTIsIm5iZiI6MTcyNzg4MTkxMiwicGF0aCI6Ii84MTQ2MzUzMi8zNzIzOTc1MzgtOGNhZTY5NTctNGQyYi00YjlkLThlNmItNGMyODNjYmU3NWU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAyVDE1MTE1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyMTY5ZTVlOGFkZTRkNmYxNmIwOTBlNzVlMzA5MGNmY2JiZmViMGIzMjYyN2Y5NDhmYmU2NGFjYzVjNGNhM2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.v3WZCrV8NEndBMGx7Bnp9b7ZiiGfqoX8CeXwTACFA90)

目前是默认返回所有数据，这个参数是对历史累计的 indicator 来作用的
