### ISSUE TITLE
AKShare以后会考虑增加集思录上的T+0 QDII数据（分为欧美市场和亚洲市场）吗？

### ISSUE THREAD

**Issue by yong900630** [akfamily/akshare#5220]
我看AKShare目前只有集思录的可转债数据，还无法获取T+0 QDII数据（分为欧美市场和亚洲市场），未来会考虑加上吗？

**Comment by albertandking** [comment]
> 我看AKShare目前只有集思录的可转债数据，还无法获取T+0 QDII数据（分为欧美市场和亚洲市场），未来会考虑加上吗？

已修复该问题，升级到 AKShare 1.14.92 使用，新增 qdii_a_index_jsl 等数据
