### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by BobWong0624** [akfamily/akshare#5221]
本人使用Windows系统，尝试使用`option_czce_daily`函数调取红枣期权数据，然而返回的是AP期权数据，经查验为源代码中未添加红枣的branch。建议添加该branch，并将查询参数错误时返回值设为特殊提示而非AP期权数据。

**Comment by albertandking** [comment]
> 本人使用Windows系统，尝试使用`option_czce_daily`函数调取红枣期权数据，然而返回的是AP期权数据，经查验为源代码中未添加红枣的branch。建议添加该branch，并将查询参数错误时返回值设为特殊提示而非AP期权数据。

已修复该问题，升级到 AKShare 1.14.92 使用
