### ISSUE TITLE
the interface of stock_individual_spot_xq occur error

### ISSUE THREAD

**Issue by ykpercy** [akfamily/akshare#5222]
akshare==1.14.91
here is the example code:

```
stock_individual_spot_xq_df = ak.stock_individual_spot_xq(symbol="BJ430139")
stock_individual_spot_xq_df
```

the error info is following:
KeyError                                  Traceback (most recent call last)
/tmp/ipykernel_235/3556804286.py in <cell line: 1>()
----> 1 stock_individual_spot_xq_df = ak.stock_individual_spot_xq(symbol="BJ430139")
      2 stock_individual_spot_xq_df

~/.conda/envs/default/lib/python3.9/site-packages/akshare/stock/stock_xq.py in stock_individual_spot_xq(symbol, timeout)
    103     }
    104     json_data = r.json()
--> 105     temp_df = pd.json_normalize(json_data["data"]["quote"])
    106     temp_df.columns = [
    107         *map(

KeyError: 'data'

**Comment by albertandking** [comment]
> akshare==1.14.91 here is the example code:
> 
> ```
> stock_individual_spot_xq_df = ak.stock_individual_spot_xq(symbol="BJ430139")
> stock_individual_spot_xq_df
> ```
> 
> the error info is following: KeyError Traceback (most recent call last) /tmp/ipykernel_235/3556804286.py in <cell line: 1>() ----> 1 stock_individual_spot_xq_df = ak.stock_individual_spot_xq(symbol="BJ430139") 2 stock_individual_spot_xq_df
> 
> ~/.conda/envs/default/lib/python3.9/site-packages/akshare/stock/stock_xq.py in stock_individual_spot_xq(symbol, timeout) 103 } 104 json_data = r.json() --> 105 temp_df = pd.json_normalize(json_data["data"]["quote"]) 106 temp_df.columns = [ 107 *map(
> 
> KeyError: 'data'

已修复该问题，升级到 AKShare 1.14.92 使用
