### ISSUE TITLE
AKShare 接口问题报告 - stock_board_industry_index_ths

### ISSUE THREAD

**Issue by jiataocai** [akfamily/akshare#5227]
**详细问题描述**

1. 请先详细阅读文档对应接口的使用方式：https://akshare.akfamily.xyz
2. 操作系统版本:Win11 64位
3. Python 版本：3.8 以上的版本
4. AKShare 版本：最新版
5. 接口的名称和相应的调用代码
接口名称：stock_board_industry_index_ths
调用：http://127.0.0.1:8080/api/public/stock_board_industry_index_ths?symbol=元件&start_date=20100930&end_date=20241009
7. 接口报错的截图或描述
其他的接口调用没有问题，只有这个接口一直报错：
raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?

<img width="892" alt="error" src="https://github.com/user-attachments/assets/bb8824da-b24b-4a52-8fb7-ad60abb824f2">

9. 期望获得的正确结果
显示行业数据

**Comment by albertandking** [comment]
> **详细问题描述**
> 
> 1. 请先详细阅读文档对应接口的使用方式：https://akshare.akfamily.xyz
> 2. 操作系统版本:Win11 64位
> 3. Python 版本：3.8 以上的版本
> 4. AKShare 版本：最新版
> 5. 接口的名称和相应的调用代码
>    接口名称：stock_board_industry_index_ths
>    调用：[http://127.0.0.1:8080/api/public/stock_board_industry_index_ths?symbol=元件&start_date=20100930&end_date=20241009](http://127.0.0.1:8080/api/public/stock_board_industry_index_ths?symbol=%E5%85%83%E4%BB%B6&start_date=20100930&end_date=20241009)
> 6. 接口报错的截图或描述
>    其他的接口调用没有问题，只有这个接口一直报错：
>    raise FeatureNotFound(
>    bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
> 
> <img alt="error" width="892" src="https://private-user-images.githubusercontent.com/41246044/374180203-bb8824da-b24b-4a52-8fb7-ad60abb824f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNzg0NTIsIm5iZiI6MTcyODM3ODE1MiwicGF0aCI6Ii80MTI0NjA0NC8zNzQxODAyMDMtYmI4ODI0ZGEtYjI0Yi00YTUyLThmYjctYWQ2MGFiYjgyNGYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDA5MDIzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3OWRhNzE4ODcwM2RkZjA3MDE4M2RjN2YyNGFjNmZlZTUzZDY2YzRjZGYwYjBmMzY2NWVjZWJkNTU0OTI1NDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JCYVmjHQsCA_QjxKj0khaEwnQkuAQZ0TNwMqS5mIpus">
> 9. 期望获得的正确结果
>    显示行业数据

目前 AKShare 库本身正常，看错误提示应该是环境中缺少 lxml 库，可以通过 pip install lxml 安装后再尝试

**Comment by jiataocai** [comment]
通过 pip install lxml 安装后不能解决问题，升级到python 3.9, 发现除了“http://127.0.0.1:8080/api/public/stock_board_industry_index_ths?symbol=%E9%9B%B6%E5%94%AE&start_date=20230930&end_date=20241009” 可以正常获取数据，其他在https://q.10jqka.com.cn/thshy/detail/code/881121/ 的这些行业，大部分报错：raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 12 elements
