### ISSUE TITLE
AKShare 接口问题报告： 成交持仓  //  接口: futures_hold_pos_sina  //  无法正常使用

### ISSUE THREAD

**Issue by userssgithub** [akfamily/akshare#5233]
您好，非常感谢您们提供的AKShare。

我在使用您们“**成交持仓**”时，发现了一个问题。

https://akshare.akfamily.xyz/data/futures/futures.html#id48)

接口: futures_hold_pos_sina

目标地址: https://vip.stock.finance.sina.com.cn/q/view/vFutures_Positions_cjcc.php

**问题描述：**

现在您们的这个接口，只可以获取最新一日的螺纹钢的数据。无法获取指定日期，或者指定期货品种的成交持仓数据。

希望您们检查更新。

再次感谢您们的AKShare。

顺颂商祺

祝愿您们越办越好！

Simon

**Comment by albertandking** [comment]
> 您好，非常感谢您们提供的AKShare。
> 
> 我在使用您们“**成交持仓**”时，发现了一个问题。
> 
> https://akshare.akfamily.xyz/data/futures/futures.html#id48)
> 
> 接口: futures_hold_pos_sina
> 
> 目标地址: https://vip.stock.finance.sina.com.cn/q/view/vFutures_Positions_cjcc.php
> 
> **问题描述：**
> 
> 现在您们的这个接口，只可以获取最新一日的螺纹钢的数据。无法获取指定日期，或者指定期货品种的成交持仓数据。
> 
> 希望您们检查更新。
> 
> 再次感谢您们的AKShare。
> 
> 顺颂商祺
> 
> 祝愿您们越办越好！
> 
> Simon

感谢支持，接口测试正常，注意调用频率
