### ISSUE TITLE
AKShare 接口问题报告：stock_individual_spot_xq返回结果为空

### ISSUE THREAD

**Issue by shateng** [akfamily/akshare#5235]
akshare版本：
# Name                    Version                   Build  Channel
akshare                   1.14.95                  pypi_0    pypi

import akshare as ak
stock_individual_spot_xq_df = ak.stock_individual_spot_xq(symbol="SPY")
print(stock_individual_spot_xq_df.dtypes)
返回结果为空：
item     object
value    object
dtype: object

**Comment by albertandking** [comment]
> akshare版本：
> 
> # Name Version Build Channel
> akshare 1.14.95 pypi_0 pypi
> 
> import akshare as ak stock_individual_spot_xq_df = ak.stock_individual_spot_xq(symbol="SPY") print(stock_individual_spot_xq_df.dtypes) 返回结果为空： item object value object dtype: object

接口正常；请按issue模板提交问题
