### ISSUE TITLE
不同 python 版本，不同 akshare 版本获取数据速度差别很大！有哪些原因呢？

### ISSUE THREAD

**Issue by 92hackers** [akfamily/akshare#5242]
## 问题描述：
分别用 docker 镜像和再本地 `pip install` 安装的 akshare，两种方式获取数据的速度，差别很大。

## 详细信息：
根据项目 `readme.md` 下载的 docker image 中的 akshare 版本为 `1.7.35`，python 版本为 `3.8.14`。
而本地 python 版本为：3.10.12，akshare 为最新版本：1.14.97。

经过实际测试，在运行以下代码时：
```pyhton
stock_zh_a_hist_df = ak.stock_zh_a_hist(symbol="000001", period="daily", start_date="20230301", end_date='20231022', adjust="")
```
docker 镜像中的版本运行飞快，1s 左右能返回结果，而本地的最新版本就很慢，至少要 10s 才能拿到结果。

所有测试都是在本机上跑的，网络情况相同，且经过多次测试均是如上结果。

想问问具体是哪块的问题，以及如何修复，或者是一些最佳实践，比如要尽快拉取所有股票的历史价格数据等等场景。

谢谢！

**Comment by albertandking** [comment]
> ## 问题描述：
> 分别用 docker 镜像和再本地 `pip install` 安装的 akshare，两种方式获取数据的速度，差别很大。
> 
> ## 详细信息：
> 根据项目 `readme.md` 下载的 docker image 中的 akshare 版本为 `1.7.35`，python 版本为 `3.8.14`。 而本地 python 版本为：3.10.12，akshare 为最新版本：1.14.97。
> 
> 经过实际测试，在运行以下代码时：
> 
> ```
> stock_zh_a_hist_df = ak.stock_zh_a_hist(symbol="000001", period="daily", start_date="20230301", end_date='20231022', adjust="")
> ```
> 
> docker 镜像中的版本运行飞快，1s 左右能返回结果，而本地的最新版本就很慢，至少要 10s 才能拿到结果。
> 
> 所有测试都是在本机上跑的，网络情况相同，且经过多次测试均是如上结果。
> 
> 想问问具体是哪块的问题，以及如何修复，或者是一些最佳实践，比如要尽快拉取所有股票的历史价格数据等等场景。
> 
> 谢谢！

应该你本地网络配置的问题，目前该接口返回 1s 左右
