### ISSUE TITLE
请问现在接口stock_zh_a_hist数据不是实时更新吗？

### ISSUE THREAD

**Issue by ZL221B** [akfamily/akshare#5244]
> 欢迎加入《数据科学实战》知识星球，交流财经数据与量化投资相关内容，
> 详细信息参考：https://akshare.akfamily.xyz/learn.html

**详细问题描述**

python3.12.5 64bit 
akshare 1.14.97
stock_zh_a_hist 获取数据只到一周结束，并不是到当日数据，比如：
今天2024.10.16 但是我所获取的数据还在10.11
这是bug还是现在都按整周返回数据，不再返回实时数据？谢谢！

**Comment by albertandking** [comment]
> > 欢迎加入《数据科学实战》知识星球，交流财经数据与量化投资相关内容，
> > 详细信息参考：https://akshare.akfamily.xyz/learn.html
> 
> **详细问题描述**
> 
> python3.12.5 64bit akshare 1.14.97 stock_zh_a_hist 获取数据只到一周结束，并不是到当日数据，比如： 今天2024.10.16 但是我所获取的数据还在10.11 这是bug还是现在都按整周返回数据，不再返回实时数据？谢谢！

默认返回最新的数据，注意调用时间在收盘后

**Comment by ZL221B** [comment]
意思是盘中调用没有用了？比如现在调用就不行？
还有没有哪个接口返回实时数据呢？
