### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by UK0W** [akfamily/akshare#5257]
接口的名称：stock_cyq_em
相应的调用代码：params = {
        "secid": f"{code_id_dict[symbol]}.{symbol}",
        "ut": "fa5fd1943c7b386f172d6893dbfba10b",
        "fields1": "f1,f2,f3,f4,f5,f6",
        "fields2": "f51,f52,f53,f54,f55,f56,f57,f58,f59,f60,f61",
        "klt": "101",
        "fqt": adjust_dict[adjust],
        "end": datetime.now().date().strftime("%Y%m%d"),
        "lmt": "210",
        "cb": "quote_jp1",
    }

接口问题描述：仅能获得股票90日的筹码分布

 期望获得正确结果：能获取东财全部的筹码分布数据

尝试了https://push2his.eastmoney.com/api/qt/stock/kline/get?secid=0.000001&ut=fa5fd1943c7b386f172d6893dbfba10b&fields1=f1%2Cf2%2Cf3%2Cf4%2Cf5%2Cf6&fields2=f51%2Cf52%2Cf53%2Cf54%2Cf55%2Cf56%2Cf57%2Cf58%2Cf59%2Cf60%2Cf61&klt=101&fqt=1&end=20241020&lmt=99999&cb=quote_jp5，可以返回1991年4月3日到最近的数据
能否修改 "lmt": "210"参数，以扩大数据爬取范围，感谢~

**Comment by albertandking** [comment]
> stock_cyq_em

只能计算近期的数据
