### ISSUE TITLE
stock_board_industry_index_ths大部分报错

### ISSUE THREAD

**Issue by jiataocai** [akfamily/akshare#5258]
通过 pip install lxml 安装后不能解决问题，升级到python 3.9, 发现除了“http://127.0.0.1:8080/api/public/stock_board_industry_index_ths?symbol=%E9%9B%B6%E5%94%AE&start_date=20230930&end_date=20241009” 可以正常获取数据，其他在https://q.10jqka.com.cn/thshy/detail/code/881121/ 的这些行业，大部分报错：raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 12 elements
<img width="986" alt="image" src="https://github.com/user-attachments/assets/621336d9-ed5e-400a-9b45-7705513077e4">

_Originally posted by @jiataocai in https://github.com/akfamily/akshare/issues/5227#issuecomment-2407499257_

**Comment by albertandking** [comment]
> ```
>           通过 pip install lxml 安装后不能解决问题，升级到python 3.9, 发现除了“http://127.0.0.1:8080/api/public/stock_board_industry_index_ths?symbol=%E9%9B%B6%E5%94%AE&start_date=20230930&end_date=20241009” 可以正常获取数据，其他在https://q.10jqka.com.cn/thshy/detail/code/881121/ 的这些行业，大部分报错：raise ValueError(
> ```
> 
> ValueError: Length mismatch: Expected axis has 0 elements, new values have 12 elements <img alt="image" width="986" src="https://private-user-images.githubusercontent.com/41246044/375784638-621336d9-ed5e-400a-9b45-7705513077e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0MTY2NTgsIm5iZiI6MTcyOTQxNjM1OCwicGF0aCI6Ii80MTI0NjA0NC8zNzU3ODQ2MzgtNjIxMzM2ZDktZWQ1ZS00MDBhLTliNDUtNzcwNTUxMzA3N2U0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIwVDA5MjU1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkODFmYmUzZDkxMTJkMDgwNDcxMzdkZTk4N2I2ZTQ3ZTc1ZWEzOWQ1MzFlM2E0NGYzNGE2YWRlOTllZDU0ZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ZFzPfX2taLHpHDRuwR51droROf6FFjwSQp9iFrCrUWM">
> 
> _Originally posted by @jiataocai in [#5227 (comment)](https://github.com/akfamily/akshare/issues/5227#issuecomment-2407499257)_

注意数据待用的频率
