### ISSUE TITLE
AKShare 接口数据问题报告

### ISSUE THREAD

**Issue by MeetCappuccino** [akfamily/akshare#5260]
> 欢迎加入《数据科学实战》知识星球，交流财经数据与量化投资相关内容，
> 详细信息参考：https://akshare.akfamily.xyz/learn.html

## 前提

遇到任何问题，请先将您的 AKShare 版本升级到**最新版**，可以通过如下命令升级：

```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

## 如何提交问题

提交问题的同时，请提交以下相关信息，以更精准的解决问题。

**不符合提交规范的 issues 会被关闭！**

**详细问题描述**

1. 请先详细阅读文档对应接口的使用方式：https://akshare.akfamily.xyz
2. 操作系统版本，目前只支持 64 位操作系统--> Windows 64
3. Python 版本，目前只支持 3.8 以上的版本--> Python 3.9.13
4. AKShare 版本，请升级到最新版-->1.15.2
5. 接口的名称和相应的调用代码--> fund_open_fund_info_em_df = ak.fund_open_fund_info_em(symbol=502010, indicator="累计净值走势", period="成立来") 
6. 接口报错的截图或描述--> 程序接口没有报错，但是502010的返回值中间部分缺少了几年的净值数据

**Comment by albertandking** [comment]
> > 欢迎加入《数据科学实战》知识星球，交流财经数据与量化投资相关内容，
> > 详细信息参考：https://akshare.akfamily.xyz/learn.html
> 
> ## 前提
> 遇到任何问题，请先将您的 AKShare 版本升级到**最新版**，可以通过如下命令升级：
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8
> ```
> 
> ## 如何提交问题
> 提交问题的同时，请提交以下相关信息，以更精准的解决问题。
> 
> **不符合提交规范的 issues 会被关闭！**
> 
> **详细问题描述**
> 
> 1. 请先详细阅读文档对应接口的使用方式：https://akshare.akfamily.xyz
> 2. 操作系统版本，目前只支持 64 位操作系统--> Windows 64
> 3. Python 版本，目前只支持 3.8 以上的版本--> Python 3.9.13
> 4. AKShare 版本，请升级到最新版-->1.15.2
> 5. 接口的名称和相应的调用代码--> fund_open_fund_info_em_df = ak.fund_open_fund_info_em(symbol=502010, indicator="累计净值走势", period="成立来")
> 6. 接口报错的截图或描述--> 程序接口没有报错，但是502010的返回值中间部分缺少了几年的净值数据

接口测试正常；可以参考数据源的目标网站
