### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by zhengchong** [akfamily/akshare#5264]
Python - 3.12.4
AKShare - 2024.10.21安装，最新
Windows 11，64 bit

以下两段代码，分别调用，得到不同的结果：
**代码段1：**
输入-
_stock_financial_abstract_ths_df = ak.stock_financial_abstract_ths(symbol="430489", indicator="按报告期")
print(stock_financial_abstract_ths_df.columns)_
输出- 
Index(['报告期', '净利润', '净利润同比增长率', '扣非净利润', '扣非净利润同比增长率', '营业总收入', '营业总收入同比增长率',
       '基本每股收益', '每股净资产', '每股资本公积金', '每股未分配利润', '每股经营现金流', '销售净利率', '销售毛利率',
       '净资产收益率', '净资产收益率-摊薄', '营业周期', '存货周转率', '存货周转天数', '应收账款周转天数', '流动比率',
       '速动比率', '保守速动比率', '产权比率', '资产负债率'],
      dtype='object')
**代码段2：**
输入-
_stock_financial_abstract_ths_df = ak.stock_financial_abstract_ths(symbol="601162", indicator="按报告期")
print(stock_financial_abstract_ths_df.columns)_
输出- 
Index(['报告期', '净利润', '净利润同比增长率', '扣非净利润', '扣非净利润同比增长率', '营业总收入', '营业总收入同比增长率',
       '基本每股收益', '每股净资产', '每股资本公积金', '每股未分配利润', '每股经营现金流', '销售净利率', '净资产收益率',
       '净资产收益率-摊薄', '产权比率', '资产负债率'],
      dtype='object')
从以上两段代码可看出，同一个接口，不同的symbol参数输入会导致返回数据的列数不同，而我需要循环遍历所有沪深京股票symbol并对每个symbol对应的数据进行进一步操作，比如下面一段代码：
_for code in stock_code_list:
    stock_financial_abstract_ths_df = ak.stock_financial_abstract_ths(code, "按年度")
    yearly_temp = stock_financial_abstract_ths_df.drop(columns=['保守速动比率'])_

这段代码在drop的过程中就由于列数不同而报错，无法统一进行drop操作，这样处理数据非常不便利，希望能够修复这个问题。

**Comment by albertandking** [comment]
> Python - 3.12.4 AKShare - 2024.10.21安装，最新 Windows 11，64 bit
> 
> 以下两段代码，分别调用，得到不同的结果： **代码段1：** 输入- _stock_financial_abstract_ths_df = ak.stock_financial_abstract_ths(symbol="430489", indicator="按报告期") print(stock_financial_abstract_ths_df.columns)_ 输出- Index(['报告期', '净利润', '净利润同比增长率', '扣非净利润', '扣非净利润同比增长率', '营业总收入', '营业总收入同比增长率', '基本每股收益', '每股净资产', '每股资本公积金', '每股未分配利润', '每股经营现金流', '销售净利率', '销售毛利率', '净资产收益率', '净资产收益率-摊薄', '营业周期', '存货周转率', '存货周转天数', '应收账款周转天数', '流动比率', '速动比率', '保守速动比率', '产权比率', '资产负债率'], dtype='object') **代码段2：** 输入- _stock_financial_abstract_ths_df = ak.stock_financial_abstract_ths(symbol="601162", indicator="按报告期") print(stock_financial_abstract_ths_df.columns)_ 输出- Index(['报告期', '净利润', '净利润同比增长率', '扣非净利润', '扣非净利润同比增长率', '营业总收入', '营业总收入同比增长率', '基本每股收益', '每股净资产', '每股资本公积金', '每股未分配利润', '每股经营现金流', '销售净利率', '净资产收益率', '净资产收益率-摊薄', '产权比率', '资产负债率'], dtype='object') 从以上两段代码可看出，同一个接口，不同的symbol参数输入会导致返回数据的列数不同，而我需要循环遍历所有沪深京股票symbol并对每个symbol对应的数据进行进一步操作，比如下面一段代码： _for code in stock_code_list: stock_financial_abstract_ths_df = ak.stock_financial_abstract_ths(code, "按年度") yearly_temp = stock_financial_abstract_ths_df.drop(columns=['保守速动比率'])_
> 
> 这段代码在drop的过程中就由于列数不同而报错，无法统一进行drop操作，这样处理数据非常不便利，希望能够修复这个问题。

目前接口与数据源保持一致，你可以检查下跟数据源否是返回一致，其次会不会是两个交易所的区别，建议在本地处理

**Comment by zhengchong** [comment]
我一直是在本地处理的，看上去是交易所的差别，但按程序设计原理，像这样交易所的区别会造成返回数据列数不同，那不适合放在同个接口来返回吧？建议最好将来源数据做预处理，让几个交易所的数据格式统一起来，不然用户按照官网写的返回值格式来调用，每次运行起来都得来检查这个出问题点。
