### ISSUE TITLE
AKShare 申万对应的接口使用的url无法访问

### ISSUE THREAD

**Issue by pibbo88** [akfamily/akshare#5265]
在文件index_research_sw.py中的函数，如index_hist_sw使用的url对应的域名为swhyresearch.com.
```
def index_hist_sw(symbol: str = "801030", period: str = "day") -> pd.DataFrame:
    """
    申万宏源研究-指数发布-指数详情-指数历史数据
    https://www.swhyresearch.com/institute_sw/allIndex/releasedIndex/releasedetail?code=801001&name=%E7%94%B3%E4%B8%8750
    :param symbol: 指数代码
    :type symbol: str
    :param period: choice of {"day", "week", "month"}
    :type period: str
    :return: 指数历史数据
    :rtype: pandas.DataFrame
    """
```

[https://www.swhyresearch.com]无法访问，导致函数接口报错。如将其换成[https://www.swsresearch.com], 则可以访问，且函数可以正确运行。

**Comment by albertandking** [comment]
> 在文件index_research_sw.py中的函数，如index_hist_sw使用的url对应的域名为swhyresearch.com.
> 
> ```
> def index_hist_sw(symbol: str = "801030", period: str = "day") -> pd.DataFrame:
>     """
>     申万宏源研究-指数发布-指数详情-指数历史数据
>     https://www.swhyresearch.com/institute_sw/allIndex/releasedIndex/releasedetail?code=801001&name=%E7%94%B3%E4%B8%8750
>     :param symbol: 指数代码
>     :type symbol: str
>     :param period: choice of {"day", "week", "month"}
>     :type period: str
>     :return: 指数历史数据
>     :rtype: pandas.DataFrame
>     """
> ```
> 
> [https://www.swhyresearch.com]无法访问，导致函数接口报错。如将其换成[https://www.swsresearch.com], 则可以访问，且函数可以正确运行。

感谢反馈问题，已修改该问题，升级到 AKShare 1.15.7 使用
