### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by wgliang** [akfamily/akshare#5268]
> 欢迎加入《数据科学实战》知识星球，交流财经数据与量化投资相关内容，
> 详细信息参考：https://akshare.akfamily.xyz/learn.html

## 前提

遇到任何问题，请先将您的 AKShare 版本升级到**最新版**，可以通过如下命令升级：

```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8
```

## 如何提交问题

提交问题的同时，请提交以下相关信息，以更精准的解决问题。

**不符合提交规范的 issues 会被关闭！**

**详细问题描述**
stock_zh_a_hist_min_em_df = ak.stock_zh_a_hist_min_em(symbol="000002", start_date="2024-10-16 09:30:00", end_date="2024-10-16  15:00:00", period="1", adjust="hfq")
print(stock_zh_a_hist_min_em_df)

把period="1"改为period="5"，数据从：
0    2024-10-23 09:30:00  9.22  9.22  9.22  9.22   7558   6968476.0  9.220
1    2024-10-23 09:31:00  9.20  9.22  9.24  9.18  38035  35009849.0  9.207
2    2024-10-23 09:32:00  9.22  9.25  9.26  9.22  20780  19194075.0  9.216
3    2024-10-23 09:33:00  9.24  9.18  9.24  9.18  13646  12566539.0  9.215
4    2024-10-23 09:34:00  9.19  9.19  9.19  9.16  12117  11119352.0  9.210
..                   ...   ...   ...   ...   ...    ...         ...    ...
236  2024-10-23 14:56:00  9.33  9.34  9.34  9.33  14804  13816749.0  9.353
237  2024-10-23 14:57:00  9.33  9.33  9.34  9.33  17074  15936669.0  9.353
238  2024-10-23 14:58:00  9.33  9.33  9.33  9.33   2194   2047204.0  9.353
239  2024-10-23 14:59:00  9.33  9.33  9.33  9.33      0         0.0  9.353
240  2024-10-23 15:00:00  9.33  9.33  9.33  9.33  26900  25097700.0  9.352

变成了：

                   时间       开盘       收盘       最高       最低   涨跌幅    涨跌额     成交量          成交额    振幅   换手率
0   2024-10-23 09:35:00  2377.50  2376.19  2382.74  2369.65 -0.17  -3.93   99763   91872580.0  0.55  0.10
1   2024-10-23 09:40:00  2376.19  2391.90  2393.21  2376.19  0.66  15.71  129528  120140744.0  0.72  0.13
2   2024-10-23 09:45:00  2390.59  2381.43  2391.90  2380.12 -0.44 -10.47   81197   75464563.0  0.49  0.08
3   2024-10-23 09:50:00  2382.74  2377.50  2385.36  2376.19 -0.17  -3.93   66374   61336422.0  0.39  0.07
4   2024-10-23 09:55:00  2378.81  2381.43  2384.05  2376.19  0.17   3.93   53407   49354173.0  0.33  0.05
5   2024-10-23 10:00:00  2382.74  2387.97  2387.97  2381.43  0.27   6.54   49340   45765599.0  0.27  0.05
6   2024-10-23 10:05:00  2387.97  2407.61  2407.61  2385.36  0.82  19.64  259333  242872258.0  0.93  0.27
7   2024-10-23 10:10:00  2407.61  2404.99  2410.23  2397.14 -0.11  -2.62  159292  150233816.0  0.54  0.16
8   2024-10-23 10:15:00  2404.99  2398.45  2404.99  2394.52 -0.27  -6.54   80586   75689398.0  0.44  0.08
9   2024-10-23 10:20:00  2397.14  2395.83  2398.45  2391.90 -0.11  -2.62   62850   58824373.0  0.27  0.06
10  2024-10-23 10:25:00  2395.83  2402.37  2407.61  2395.83  0.27   6.54   93506   87976083.0  0.49  0.10
11  2024-10-23 10:30:00  2402.37  2395.83  2407.61  2395.83 -0.27  -6.54   87579   82421074.0  0.49  0.09
12  2024-10-23 10:35:00  2395.83  2395.83  2398.45  2394.52  0.00   0.00   28802   26957327.0  0.16  0.03
13  2024-10-23 10:40:00  2394.52  2395.83  2397.14  2391.90  0.00   0.00   34979   32692576.0  0.22  0.04
14  2024-10-23 10:45:00  2395.83  2390.59  2395.83  2389.28 -0.22  -5.24   34924   32573691.0  0.27  0.04
15  2024-10-23 10:50:00  2390.59  2391.90  2391.90  2387.97  0.05   1.31   29647   27613750.0  0.16  0.03
16  2024-10-23 10:55:00  2391.90  2386.66  2391.90  2386.66 -0.22  -5.24   37852   35223268.0  0.22  0.04
17  2024-10-23 11:00:00  2386.66  2389.28  2389.28  2385.36  0.11   2.62   18780   17462980.0  0.16  0.02

1. 请先详细阅读文档对应接口的使用方式：https://akshare.akfamily.xyz
2. 操作系统版本，目前只支持 64 位操作系统
3. Python 版本，目前只支持 3.8 以上的版本
4. AKShare 版本，请升级到最新版
5. 接口的名称和相应的调用代码
6. 接口报错的截图或描述
7. 期望获得的正确结果

**Comment by albertandking** [comment]
> stock_zh_a_hist_min_em_df = ak.stock_zh_a_hist_min_em(symbol="000002", start_date="2024-10-16 09:30:00", end_date="2024-10-16 15:00:00", period="1", adjust="hfq")

看文档中关于该接口的使用说明有标注
