### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by BoostersEngaged** [akfamily/akshare#5270]
市场成本
接口: stock_comment_detail_scrd_cost_em

目标地址: https://data.eastmoney.com/stockcomment/stock/600000.html

描述: 东方财富网-数据中心-特色数据-千股千评-市场热度-市场成本

限量: 单次获取所有数据

接口报错的截图或描述:![image](https://github.com/user-attachments/assets/433be106-c1bc-4728-bdd6-08c5ad43f868)
描述：只能获得最晚2023-04-07的数据
期望获得：最新的up-to-date的结果

**Comment by albertandking** [comment]
> 市场成本 接口: stock_comment_detail_scrd_cost_em
> 
> 目标地址: https://data.eastmoney.com/stockcomment/stock/600000.html
> 
> 描述: 东方财富网-数据中心-特色数据-千股千评-市场热度-市场成本
> 
> 限量: 单次获取所有数据
> 
> 接口报错的截图或描述:![image](https://private-user-images.githubusercontent.com/148531048/379536289-433be106-c1bc-4728-bdd6-08c5ad43f868.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NjE5MTAsIm5iZiI6MTcyOTg2MTYxMCwicGF0aCI6Ii8xNDg1MzEwNDgvMzc5NTM2Mjg5LTQzM2JlMTA2LWMxYmMtNDcyOC1iZGQ2LTA4YzVhZDQzZjg2OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNVQxMzA2NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZmQ5YTkyYTk1ZmRlZGE1MWM0MDQxMjEwN2YwM2ZmZjRmZDIyMDFmOWI0NTNlMTJhNzM3MjIxNzgwOWI3YzE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.4zzYJUUa4s3SAOnNjxDDG_o8K5Gq2MwQTXIAMJH-mQM) 描述：只能获得最晚2023-04-07的数据 期望获得：最新的up-to-date的结果

目标数据源没有相关数据，后期会移除该接口
