### ISSUE TITLE
两个指数实时行情接口缺少中证A500指数，代码000510

### ISSUE THREAD

**Issue by carusyte** [akfamily/akshare#5271]
接口：
stock_zh_index_spot_em
stock_zh_index_spot_sina

目标历史数据样例：
https://quote.eastmoney.com/zs000510.html#fullScreenChart

**Comment by albertandking** [comment]
> 接口： stock_zh_index_spot_em stock_zh_index_spot_sina
> 
> 目标历史数据样例： https://quote.eastmoney.com/zs000510.html#fullScreenChart

数据源没有提供相应的数据，在 stock_zh_index_daily 可以获取日频率的数据
