### ISSUE TITLE
AKShare 接口问题报告 | AKShare Interface Issue Report

### ISSUE THREAD

**Issue by Luffy-Zhu** [akfamily/akshare#5276]
问题说明：
fund_xq.py文件中的 fund_individual_basic_info_xq 函数，在基金停止销售时，未针对xq返回的非标准json做处理。
未销售基金，xq返回：{'result_code': 600001, 'message': '该基金暂不销售,基金代码：013926'}
从而导致执行：json_data = r.json()["data"]
出现“KeyError”

修复建议：针对基金停售case做处理。

背景信息：
2. 操作系统版本：此问题和操作系统无关；
3. Python 版本： 3.10.14
4. AKShare 版本：1.14.95

**Comment by albertandking** [comment]
> 问题说明： fund_xq.py文件中的 fund_individual_basic_info_xq 函数，在基金停止销售时，未针对xq返回的非标准json做处理。 未销售基金，xq返回：{'result_code': 600001, 'message': '该基金暂不销售,基金代码：013926'} 从而导致执行：json_data = r.json()["data"] 出现“KeyError”
> 
> 修复建议：针对基金停售case做处理。
> 
> 背景信息： 2. 操作系统版本：此问题和操作系统无关； 3. Python 版本： 3.10.14 4. AKShare 版本：1.14.95

这块取不到数据就会返回错误，可以在本地 try...except 下
