### ISSUE TITLE
AKShare 接口问题报告 | 接口ak.stock_zt_pool_em无法使用

### ISSUE THREAD

**Issue by zyzisastudyreallyhardguy** [akfamily/akshare#5284]
**详细问题描述** | Detailed Problem Description

1. 请先详细阅读文档对应接口的使用方式: 已阅读 无法解决
2. 操作系统版本: MacOS Ventura 13.5.1
3. Python版本: 11.8
4. AKShare 版本，请升级到最新版 | 已经是最新版本 1.15.8
5. 接口的名称和相应的调用代码 | 
接口名称: stock_zt_pool_em
调用代码: stock_zt_pool_em_df = ak.stock_zt_pool_em(date='20240105') 只有非常近的日期才能出结果(近两个星期)
6. 接口报错的截图或描述 | Screenshot or description of the error
<img width="1037" alt="image" src="https://github.com/user-attachments/assets/eb538187-697a-437d-acd2-abf72742008b">
7. 期望获得的正确结果 | 想要获得近5年的涨停板数据

**Comment by albertandking** [comment]
> **详细问题描述** | Detailed Problem Description
> 
> 1. 请先详细阅读文档对应接口的使用方式: 已阅读 无法解决
> 2. 操作系统版本: MacOS Ventura 13.5.1
> 3. Python版本: 11.8
> 4. AKShare 版本，请升级到最新版 | 已经是最新版本 1.15.8
> 5. 接口的名称和相应的调用代码 |
>    接口名称: stock_zt_pool_em
>    调用代码: stock_zt_pool_em_df = ak.stock_zt_pool_em(date='20240105') 只有非常近的日期才能出结果(近两个星期)
> 6. 接口报错的截图或描述 | Screenshot or description of the error
> 
> <img alt="image" width="1037" src="https://private-user-images.githubusercontent.com/75228223/380902593-eb538187-697a-437d-acd2-abf72742008b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyMDczNDUsIm5iZiI6MTczMDIwNzA0NSwicGF0aCI6Ii83NTIyODIyMy8zODA5MDI1OTMtZWI1MzgxODctNjk3YS00MzdkLWFjZDItYWJmNzI3NDIwMDhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDEzMDQwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4YTRlNTY4NGM5ZmY5Y2Q5NmJjZTIxZTNmMjA5M2Q1MjQyODg0NDdiZmQ2ZDE3NWQxOGQwZGY5OGNmNjRhOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1Zr6P8o5puReOGn-fH0p9vAsu1_blSl8N7D5KEMiYd0"> 7. 期望获得的正确结果 | 想要获得近5年的涨停板数据

最能获取近期的数据
