### ISSUE TITLE
提取数据有冲突和错误

### ISSUE THREAD

**Issue by jasonudu** [akfamily/akshare#5287]
操作系统版本，目前只支持 64 位操作系统
win11

Python 版本，目前只支持 3.8 以上的版本
3.10.10

AKShare 版本，请升级到最新版
akshare-1.14.78

接口的名称和相应的调用代码
        code = '000002'
        b_cdt = '2021-03-01'
        e_cdt = '2024-03-31'
        kline = ak.stock_zh_a_hist(symbol=code, period="daily", start_date=b_cdt.replace('-', ''), end_date=e_cdt.replace('-', ''), adjust='')
        klineHfq = ak.stock_zh_a_hist(symbol=code, period="daily", start_date=b_cdt.replace('-', ''), end_date=e_cdt.replace('-', ''), adjust='hfq')

接口报错的截图或描述
![image](https://github.com/user-attachments/assets/9583879d-a4e3-4295-9ff8-c8a1987048df)

通过上诉代码获取股票的后复权和不复权数据，正常情况下，同一交易日的涨跌幅应该是相同的。但返回的数据显示，涨跌幅存在明显差异，请帮忙查找原因并修正。

期望获得的正确结果
希望能够获得所有a股的相关数据

**Comment by albertandking** [comment]
> 操作系统版本，目前只支持 64 位操作系统 win11
> 
> Python 版本，目前只支持 3.8 以上的版本 3.10.10
> 
> AKShare 版本，请升级到最新版 akshare-1.14.78
> 
> 接口的名称和相应的调用代码 code = '000002' b_cdt = '2021-03-01' e_cdt = '2024-03-31' kline = ak.stock_zh_a_hist(symbol=code, period="daily", start_date=b_cdt.replace('-', ''), end_date=e_cdt.replace('-', ''), adjust='') klineHfq = ak.stock_zh_a_hist(symbol=code, period="daily", start_date=b_cdt.replace('-', ''), end_date=e_cdt.replace('-', ''), adjust='hfq')
> 
> 接口报错的截图或描述 ![image](https://private-user-images.githubusercontent.com/106946718/381363003-9583879d-a4e3-4295-9ff8-c8a1987048df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzMDA3NDMsIm5iZiI6MTczMDMwMDQ0MywicGF0aCI6Ii8xMDY5NDY3MTgvMzgxMzYzMDAzLTk1ODM4NzlkLWE0ZTMtNDI5NS05ZmY4LWM4YTE5ODcwNDhkZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMFQxNTAwNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ODcwYjg5NTFjZGMwNjdlNDNhNWQwNGEwMDNlNTRjYjU4ZTBmYWI1MzM5YzYzNjExNzAwZTQwYjU2Yjc4YmRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.aqcvUwcPiLKdY8d1rXa-F_dNRXlWMRxInjTrI4OB-gY)
> 
> 通过上诉代码获取股票的后复权和不复权数据，正常情况下，同一交易日的涨跌幅应该是相同的。但返回的数据显示，涨跌幅存在明显差异，请帮忙查找原因并修正。
> 
> 期望获得的正确结果 希望能够获得所有a股的相关数据

数据以数据源为准，可以核对对应的目标网站

**Comment by cravo123** [comment]
Hi @albertandking,
同意 @jasonudu，上述情况似乎普遍存在于 ak.stock_zh_a_hist()接口，东方财富的hfq 数据是错误的！
如果某天没有分红或者拆股，那么不复权和后复权应该有相同的daily return.但是如果我们比较新浪和东方财富的万科A 历史日回报，会发现discrepancy. 或者我们不应该推荐使用东方财富的接口。
<img width="689" alt="Screenshot 2024-11-19 at 23 14 11" src="https://github.com/user-attachments/assets/bb49a38d-4b97-46b7-9bc2-a4f53858a930">

**Comment by cravo123** [comment]
格力电器也是同样的情况。新浪的接口起码不复权与后复权的daily return接近，东方财富则差的有点多...
<img width="692" alt="Screenshot 2024-11-19 at 23 17 57" src="https://github.com/user-attachments/assets/2f8a4817-a484-4398-988e-264ed737cb62">

**Comment by albertandking** [comment]
推荐东方财富接口主要原因是该接口访问没有限制，且使用人数较多；每家公司的复权方式及计算方式都有差异，你再对比下 wind 的数据（想对比较权威），方便的话，可以列出里面差异较大的股票代码
