### ISSUE TITLE
如何配置本地http或socks代理

### ISSUE THREAD

**Issue by 1amfine2333** [akfamily/akshare#5292]
如何配置本地http或socks代理，全局用PySocks吗？

**Comment by albertandking** [comment]
> 如何配置本地http或socks代理，全局用PySocks吗？

目前可以通过配置本地代理；部分接口开始支持代理设置

**Comment by cryptocat2333** [comment]
你好，我在使用文档里找了，没有看到有配置代理的地方；前段时间那哥们更新配置的代码没有通过；然后你这里说部分接口开始支持代理设置，但是使用者是一脸懵的，请问在哪里能看到使用方法示例
