### ISSUE TITLE
AKShare 接口问题报告 | AKShare Interface Issue Report

### ISSUE THREAD

**Issue by notanymore** [akfamily/akshare#5296]
在调用 stock_zt_pool_previous_em() 接口的时候，偶尔会随机出现以下的错误：

 stock_zt_pool_previous_em_df = ak.stock_zt_pool_previous_em(date=current_date_str)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jian\anaconda3\Lib\site-packages\akshare\stock_feature\stock_ztb_em.py", line 131, in stock_zt_pool_previous_em
    data_json = r.json()
                ^^^^^^^^
  File "C:\Users\Jian\anaconda3\Lib\site-packages\requests\models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

也许是转码的问题，希望可以修补，谢谢。

**Comment by congcong009** [comment]
```shell
    stock_zt_pool_previous_em('20241101')

Got:
          序号      代码    名称       涨跌幅    最新价  ...         振幅  昨日封板时间  昨日连板数  涨停统计  所属行业
    0      1  002571  德力股份 -8.317215   4.74  ...  19.535784  093512      1   2/1  家用轻工
    1      2  603061   金海通 -5.806528  79.65  ...   8.928572  143439      1   2/1   半导体
    2      3  002044  美年健康 -1.263158   4.69  ...   5.894737  135212      1   2/1  医疗服务
    3      4  002919  名臣健康  0.739247  14.99  ...   7.459678  101327      1   2/1    游戏
    4      5  002247  聚力文化 -8.480565   2.59  ...  19.081272  110115      2   5/3  装修装饰
    ..   ...     ...   ...       ...    ...  ...        ...     ...    ...   ...   ...
    165  166  002634  棒杰股份 -9.657948   4.49  ...  20.120726  100218      2   7/5  纺织服装
    166  167  601002  晋亿实业 -1.590909   4.33  ...  11.590909  093903      2   3/2  通用设备
    167  168  600331  宏达股份 -4.608295   8.28  ...  13.018434  145551      1   2/1  有色金属
    168  169  600651  飞乐音响 -8.470588   3.89  ...  16.470589  145617      1   2/1  光学光电
    169  170  002717  岭南股份 -5.405406   3.50  ...  20.000000  093224      6   9/7  环保行业
    <BLANKLINE>
    [170 rows x 16 columns]
```

最好多描述下什么情况，不然都复现不出来呢

**Comment by albertandking** [comment]
> 在调用 stock_zt_pool_previous_em() 接口的时候，偶尔会随机出现以下的错误：
> 
> stock_zt_pool_previous_em_df = ak.stock_zt_pool_previous_em(date=current_date_str) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\Jian\anaconda3\Lib\site-packages\akshare\stock_feature\stock_ztb_em.py", line 131, in stock_zt_pool_previous_em data_json = r.json() ^^^^^^^^ File "C:\Users\Jian\anaconda3\Lib\site-packages\requests\models.py", line 978, in json raise RequestsJSONDecodeError(e.msg, e.doc, e.pos) requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 
> 也许是转码的问题，希望可以修补，谢谢。

只能获取近期的数据
