### ISSUE TITLE
stock_individual_spot_xq interface error

### ISSUE THREAD

**Issue by chenyu-vmware** [akfamily/akshare#5297]
1. 操作系统版本： windows
3. Python 版本: 3.12.7
4. AKShare 版本:  akshare-1.15.9

interface: stock_individual_spot_xq

Traceback (most recent call last):
  File "C:\Users\user\akshare\today.py", line 115, in <module>
    print_company("688050")
  File "C:\Users\user\akshare\today.py", line 104, in print_company
    data = ak.stock_individual_spot_xq(symbol=f"{code}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\akshare\stock\stock_xq.py", line 101, in stock_individual_spot_xq
    temp_df = pd.json_normalize(json_data["data"]["quote"])
                                ~~~~~~~~~^^^^^^^^
KeyError: 'data'

**Comment by albertandking** [comment]
> 1. 操作系统版本： windows
> 2. Python 版本: 3.12.7
> 3. AKShare 版本:  akshare-1.15.9
> 
> interface: stock_individual_spot_xq
> 
> Traceback (most recent call last): File "C:\Users\user\akshare\today.py", line 115, in print_company("688050") File "C:\Users\user\akshare\today.py", line 104, in print_company data = ak.stock_individual_spot_xq(symbol=f"{code}") ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\akshare\stock\stock_xq.py", line 101, in stock_individual_spot_xq temp_df = pd.json_normalize(json_data["data"]["quote"]) ~~~~~~~~~^^^^^^^^ KeyError: 'data'

感谢反馈问题，已修复，升级到 AKShare 1.15.11 使用
