### ISSUE TITLE
AKShare 接口问题报告 | AKShare Interface Issue Report

### ISSUE THREAD

**Issue by z382556318** [akfamily/akshare#5300]
1. 接口的名称和相应的调用代码 | Interface name and corresponding code
ak.stock_individual_spot_xq(symbol=code_prefix + code)获取雪球信息报错
2. 接口报错的截图或描述 | Screenshot or description of the error
![image](https://github.com/user-attachments/assets/bba097a5-da2b-47df-b8f4-e453f6a74d4e)
3. 期望获得的正确结果 | Expected correct results
期望返回雪球的股票详细信息。

**Comment by albertandking** [comment]
> 1. stock_individual_spot_xq

接口正常，升级到最新版使用
