### ISSUE TITLE
AKShare 接口问题报告 | stock_industry_change_cninfo

### ISSUE THREAD

**Issue by Luffy-Zhu** [akfamily/akshare#5301]
使用stock_industry_change_cninfo，如果股票退市，会因为数据为空导致报错。

###期望输出：
能够在接口中跳过退市股票。

###具体错误信息：

###测试退市股票：000413，出现如下错误：

Traceback (most recent call last):
  File "./tmp3.py", line 87, in get_stock_category
    stock_industry_change_cninfo_df = ak.stock_industry_change_cninfo(symbol=code, start_date="19000101", end_date="20241103")
  File "./stock_industry_cninfo.py", line 170, in stock_industry_change_cninfo
    temp_df["变更日期"] = pd.to_datetime(temp_df["变更日期"]).dt.date
  File "./frame.py", line 4090, in __getitem__
    indexer = self.columns.get_loc(key)
  File "./base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: '变更日期'

####系统信息如下：

2. 操作系统版本，macOS 14.5
3. Python 版本，3.10
4. AKShare 版本，1.15.12

**Comment by albertandking** [comment]
> 使用stock_industry_change_cninfo，如果股票退市，会因为数据为空导致报错。
> 
> ###期望输出： 能够在接口中跳过退市股票。
> 
> ###具体错误信息：
> 
> ###测试退市股票：000413，出现如下错误：
> 
> Traceback (most recent call last): File "./tmp3.py", line 87, in get_stock_category stock_industry_change_cninfo_df = ak.stock_industry_change_cninfo(symbol=code, start_date="19000101", end_date="20241103") File "./stock_industry_cninfo.py", line 170, in stock_industry_change_cninfo temp_df["变更日期"] = pd.to_datetime(temp_df["变更日期"]).dt.date File "./frame.py", line 4090, in **getitem** indexer = self.columns.get_loc(key) File "./base.py", line 3812, in get_loc raise KeyError(key) from err KeyError: '变更日期'
> 
> ####系统信息如下：
> 
> 2. 操作系统版本，macOS 14.5
> 3. Python 版本，3.10
> 4. AKShare 版本，1.15.12

在本地用 try...except 判断
