### ISSUE TITLE
AKShare 接口问题报告 | AKShare Interface Issue Report

### ISSUE THREAD

**Issue by ShadowGuan** [akfamily/akshare#5303]
**详细问题描述** | Detailed Problem Description

- Win11 64位
- Python 3.13.0
- AKShare 版本: 1.15.12
- 接口的名称: index_value_hist_funddb

- 相应的调用代码: 

```
    index_value_hist_funddb_df = index_value_hist_funddb(
        symbol="中证A500", indicator="股息率"
    )
```

- 接口报错的截图或描述 | Screenshot or description of the error

> Traceback (most recent call last):
>   File "I:\work_space\JasStockTools\.venv\Lib\site-packages\akshare\index\index_stock_zh_csindex.py", line 476, in <module>
>     index_value_hist_funddb_df = index_value_hist_funddb(
>         symbol="中证A500", indicator="股息率"
>     )
>   File "I:\work_space\JasStockTools\.venv\Lib\site-packages\akshare\index\index_stock_zh_csindex.py", line 437, in index_value_hist_funddb
>     data_json["data"]["tubiao"]["series"][0]["data"],
>     ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
> KeyError: 'series'
> 

这个接口在获取中证A500的股息率历史信息时，就会出错。换做中证A500的市盈率和市净率就是正确的。换做沪深300的股息率也是正确的。
我稍微调试了一下，index_value_hist_funddb方法中，当获取中证A500的股息率历史信息时，从服务端返回的data_json就不对。

我直接访问数据源韭菜圈，中证A500的详情页里的股息率历史图表看起来没问题，也就是说，韭菜圈自己的后台数据应该是正确的。是不是数据接口有更新或者是出现了bug？
![image](https://github.com/user-attachments/assets/350d8623-3aa7-4f56-ba0b-fe6307c554aa)

**Comment by ShadowGuan** [comment]
更新一下，我发现韭菜圈中，中证A500的股息率历史信息，选择**所有**时，韭菜圈会显示暂无数据。
选择3年5年或10年时，都会有数据。
![image](https://github.com/user-attachments/assets/3b166704-4616-4a0b-ae27-6c4033256f80)

看来是韭菜圈的数据源问题。

请问一下，有没有任何临时解决方案，可以选择年份来获得相关数据呢？
或者怎么临时修改以下代码的参数，以获取10年的数据？

```
    url = "https://api.jiucaishuo.com/v2/guzhi/newtubiaolinedata"
    get_current_timestamp_ms_str = __get_current_timestamp_ms()
    encode_params = __create_encode(
        act_time=str(get_current_timestamp_ms_str),
        authtoken="",
        gu_code=name_code_map[symbol],
        pe_category=indicator_map[indicator],
        type="pc",
        ver="new",
        version="2.2.7",
        year=-1,
    )
    payload = {
        "gu_code": name_code_map[symbol],
        "pe_category": indicator_map[indicator],
        "year": -1,
        "ver": "new",
        "type": "pc",
        "version": "2.2.7",
        "authtoken": "",
        "act_time": str(get_current_timestamp_ms_str),
    }
    payload.update(encode_params)
    r = requests.post(url, json=payload)
    data_json = r.json()
```

**Comment by ShadowGuan** [comment]
摸索出来了，把year改成10就可以了。

**Comment by ShadowGuan** [comment]
但是遇到空数据时抛出异常也是不对的程序行为，我还是open这个issue。
需要处理空数据。

**Comment by albertandking** [comment]
> **详细问题描述** | Detailed Problem Description
> 
> * Win11 64位
> * Python 3.13.0
> * AKShare 版本: 1.15.12
> * 接口的名称: index_value_hist_funddb
> * 相应的调用代码:
> 
> ```
>     index_value_hist_funddb_df = index_value_hist_funddb(
>         symbol="中证A500", indicator="股息率"
>     )
> ```
> 
> * 接口报错的截图或描述 | Screenshot or description of the error
> 
> > Traceback (most recent call last):
> > File "I:\work_space\JasStockTools.venv\Lib\site-packages\akshare\index\index_stock_zh_csindex.py", line 476, in 
> > index_value_hist_funddb_df = index_value_hist_funddb(
> > symbol="中证A500", indicator="股息率"
> > )
> > File "I:\work_space\JasStockTools.venv\Lib\site-packages\akshare\index\index_stock_zh_csindex.py", line 437, in index_value_hist_funddb
> > data_json["data"]["tubiao"]["series"][0]["data"],
> > ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
> > KeyError: 'series'
> 
> 这个接口在获取中证A500的股息率历史信息时，就会出错。换做中证A500的市盈率和市净率就是正确的。换做沪深300的股息率也是正确的。 我稍微调试了一下，index_value_hist_funddb方法中，当获取中证A500的股息率历史信息时，从服务端返回的data_json就不对。
> 
> 我直接访问数据源韭菜圈，中证A500的详情页里的股息率历史图表看起来没问题，也就是说，韭菜圈自己的后台数据应该是正确的。是不是数据接口有更新或者是出现了bug？ ![image](https://private-user-images.githubusercontent.com/21018699/382586872-350d8623-3aa7-4f56-ba0b-fe6307c554aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MDIwNDIsIm5iZiI6MTczMDgwMTc0MiwicGF0aCI6Ii8yMTAxODY5OS8zODI1ODY4NzItMzUwZDg2MjMtM2FhNy00ZjU2LWJhMGItZmU2MzA3YzU1NGFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA1VDEwMTU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjYTVkMzE3NzY3N2U2NjcxZjZjYzQ0NzJhZmQ4OGRlOGRjODc0ODkxNjA0MWEzY2I2ZDRhY2ViYzU0ZWZlN2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hGozgSu58y1VXt3TlpPJuP7zAhPZpO3e4EAEvULo-sw)

已经在该接口新增 year 参数，升级到 AKShare 1.15.14 使用，另外目前获取不到数据默认返回异常，后期会统一处理
