### ISSUE TITLE
能否新增乐咕乐咕的申万行业数据？

### ISSUE THREAD

**Issue by Yirenxs** [akfamily/akshare#5304]
翻了akshare的文档，发现并没有乐咕乐咕的申万行业数据，如果可以的话希望能增加下，谢谢。

输入参数: 申万行业代码如 850135.SI
请求网址为 https://legulegu.com/stockdata/sw-industry-2021?industryCode=850135.SI

**Comment by albertandking** [comment]
> 翻了akshare的文档，发现并没有乐咕乐咕的申万行业数据，如果可以的话希望能增加下，谢谢。
> 
> 输入参数: 申万行业代码如 850135.SI 请求网址为 https://legulegu.com/stockdata/sw-industry-2021?industryCode=850135.SI

已有相关数据

**Comment by Yirenxs** [comment]
@albertandking 可能您弄错了，我翻了文档涉及乐咕的申万行业只有下面这4个接口 sw_index_first_info, sw_index_second_info, sw_index_third_info, sw_index_third_cons 而这4个接口都不是我上面提到的数据接口。同时，我以 sw-industry-2021 为关键字搜了akshare里面的代码，没有搜到相关结果。

如果可以的话，您可以试一下我上面提到的这个网址，取得的数据会更加丰富全面，并包含历史数据，而目前有的这4个申万行业数据是没有历史数据的，只有昨日1天的数据。
