### ISSUE TITLE
AKShare 接口问题报告 | 主要央行利率获取出错

### ISSUE THREAD

**Issue by peleusj** [akfamily/akshare#5306]
Python 版本: 3.11
AKShare 版本: 1.5.12

接口的名称和相应的调用代码
```python
import akshare as ak

macro_bank_usa_interest_rate_df = ak.macro_bank_usa_interest_rate()
print(macro_bank_usa_interest_rate_df)
```

接口报错的截图或描述
```python
Traceback (most recent call last):
  File "C:\Users\Albert\anaconda3\envs\future\Lib\site-packages\requests\models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Albert\anaconda3\envs\future\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Albert\anaconda3\envs\future\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Albert\anaconda3\envs\future\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Albert\repos\akshare\test.py", line 12, in <module>
    macro_bank_usa_interest_rate_df = ak.macro_bank_usa_interest_rate()
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Albert\anaconda3\envs\future\Lib\site-packages\akshare\economic\macro_bank.py", line 62, in macro_bank_usa_interest_rate
    data_json = r.json()
                ^^^^^^^^
  File "C:\Users\Albert\anaconda3\envs\future\Lib\site-packages\requests\models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

PS: 原始页面有中国人民银行利率报告，是否能新增对应接口？感谢。

**Comment by albertandking** [comment]
> Python 版本: 3.11 AKShare 版本: 1.5.12
> 
> 接口的名称和相应的调用代码
> 
> ```python
> import akshare as ak
> 
> macro_bank_usa_interest_rate_df = ak.macro_bank_usa_interest_rate()
> print(macro_bank_usa_interest_rate_df)
> ```
> 
> 接口报错的截图或描述
> 
> ```python
> Traceback (most recent call last):
>   File "C:\Users\Albert\anaconda3\envs\future\Lib\site-packages\requests\models.py", line 974, in json
>     return complexjson.loads(self.text, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Albert\anaconda3\envs\future\Lib\json\__init__.py", line 346, in loads
>     return _default_decoder.decode(s)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Albert\anaconda3\envs\future\Lib\json\decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Albert\anaconda3\envs\future\Lib\json\decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "c:\Users\Albert\repos\akshare\test.py", line 12, in <module>
>     macro_bank_usa_interest_rate_df = ak.macro_bank_usa_interest_rate()
>                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Albert\anaconda3\envs\future\Lib\site-packages\akshare\economic\macro_bank.py", line 62, in macro_bank_usa_interest_rate
>     data_json = r.json()
>                 ^^^^^^^^
>   File "C:\Users\Albert\anaconda3\envs\future\Lib\site-packages\requests\models.py", line 978, in json
>     raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
> requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> ```
> 
> PS: 原始页面有中国人民银行利率报告，是否能新增对应接口？感谢。

感谢反馈问题，已修复该问题并新增中国央行利率报告，升级到 AKShare 1.15.15 使用
