### ISSUE TITLE
AKShare 接口问题报告 | AKShare Interface Issue Report

### ISSUE THREAD

**Issue by noob0604** [akfamily/akshare#5314]
操作系统版本：Windows 10.0.19045  64位
Python版本：Python3.11
AKShare版本：1.15.16
接口名称：news_trade_notify_suspend_baidu
调用代码：news_trade_notify_suspend_baidu_df = ak.news_trade_notify_suspend_baidu(date="20220513")
print(news_trade_notify_suspend_baidu_df)
接口结果描述：无报错，只返回为空dataframe 测试多个日期结果相同为：Empty DataFrame
Columns: []
Index: []
7.期望获得的正确结果：包含正常数据
![图片](https://github.com/user-attachments/assets/7829e947-5c45-4ff2-a7f1-d46a63bd9b1b)

**Comment by albertandking** [comment]
> 操作系统版本：Windows 10.0.19045 64位 Python版本：Python3.11 AKShare版本：1.15.16 接口名称：news_trade_notify_suspend_baidu 调用代码：news_trade_notify_suspend_baidu_df = ak.news_trade_notify_suspend_baidu(date="20220513") print(news_trade_notify_suspend_baidu_df) 接口结果描述：无报错，只返回为空dataframe 测试多个日期结果相同为：Empty DataFrame Columns: [] Index: [] 7.期望获得的正确结果：包含正常数据 ![图片](https://private-user-images.githubusercontent.com/157415257/383842229-7829e947-5c45-4ff2-a7f1-d46a63bd9b1b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5NzIwOTgsIm5iZiI6MTczMDk3MTc5OCwicGF0aCI6Ii8xNTc0MTUyNTcvMzgzODQyMjI5LTc4MjllOTQ3LTVjNDUtNGZmMi1hN2YxLWQ0NmE2M2JkOWIxYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwN1QwOTI5NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NmM2ZGFhM2RiZmJhYmUwMmQyOWZhN2Q0NzhiYzI4Y2YwMDlmZGQ2ZTcyNWQyM2VjNDBmYjY2YTgwNzcxNzIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.8zKAOuFJWm8JoyCxTOQlFiVHzV2Em7pmKzpoe161UlE)

感谢反馈问题，已修复该问题，升级到 AKShare 1.15.17 使用
