### ISSUE TITLE
帮忙新增一个批量股本数据

### ISSUE THREAD

**Issue by jasonudu** [akfamily/akshare#5316]
原有代码中确实没有股本批量数据，我这里写了一个，麻烦增加到新版本更新中

def stock_hold_change_cninfo(symbol: str = "全部") -> pd.DataFrame:
    """
    巨潮资讯-数据中心-专题统计-股东股本-实际控制人持股变动
    https://webapi.cninfo.com.cn/#/thematicStatistics
    :param symbol: choice of {"深市主板", "沪市", "创业板", "科创板", "北交所", "全部"}; 从 2010 开始
    :type symbol: str
    :return: 实际控制人持股变动
    :rtype: pandas.DataFrame
    """
    symbol_map = {
        "深市主板": "012002",
        "沪市": "012001",
        "创业板": "012015",
        "科创板": "012029",
        "北交所": "012046",
        "全部": "",
    }
    #https://webapi.cninfo.com.cn/api/sysapi/p_sysapi1029?market=012002
    url = "https://webapi.cninfo.com.cn/api/sysapi/p_sysapi1029"
    js_code = py_mini_racer.MiniRacer()
    js_content = _get_file_content_cninfo("cninfo.js")
    js_code.eval(js_content)
    mcode = js_code.call("getResCode1")
    headers = {
        "Accept": "*/*",
        "Accept-Enckey": mcode,
        "Accept-Encoding": "gzip, deflate",
        "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
        "Cache-Control": "no-cache",
        "Content-Length": "0",
        "Host": "webapi.cninfo.com.cn",
        "Origin": "https://webapi.cninfo.com.cn",
        "Pragma": "no-cache",
        "Proxy-Connection": "keep-alive",
        "Referer": "https://webapi.cninfo.com.cn/",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/93.0.4577.63 Safari/537.36",
        "X-Requested-With": "XMLHttpRequest",
    }    
    params = {
        "market": symbol_map[symbol],
    }
    r = requests.get(url, headers=headers, params=params)
    data_json = r.json()
    temp_df = pd.DataFrame(data_json["records"])
    temp_df.columns = [
        "已流通股份(万股)",
        "总股本(万股)",
        "交易市场",
        "证券简称",
        "公告日期",
        "变动原因",
        "证券代码",
        "变动日期",
        "流通受限股份(万股)",
        "已流通比例(%)",
    ]
    temp_df = temp_df[
        [
            "证券代码",
            "证券简称",
            "交易市场",
            "公告日期",
            "变动日期",
            "变动原因",
            "总股本(万股)",
            "已流通股份(万股)",
            "已流通比例(%)",
            "流通受限股份(万股)",
        ]
    ]
    temp_df["变动日期"] = pd.to_datetime(temp_df["变动日期"], errors="coerce").dt.date
    temp_df["公告日期"] = pd.to_datetime(temp_df["公告日期"], errors="coerce").dt.date
    temp_df["总股本(万股)"] = pd.to_numeric(temp_df["总股本(万股)"], errors="coerce")
    temp_df["已流通股份(万股)"] = pd.to_numeric(temp_df["已流通股份(万股)"], errors="coerce")
    temp_df["已流通比例(%)"] = pd.to_numeric(temp_df["已流通比例(%)"], errors="coerce")
    temp_df["流通受限股份(万股)"] = pd.to_numeric(temp_df["流通受限股份(万股)"], errors="coerce")
    return temp_df

**Comment by albertandking** [comment]
> 原有代码中确实没有股本批量数据，我这里写了一个，麻烦增加到新版本更新中
> 
> def stock_hold_change_cninfo(symbol: str = "全部") -> pd.DataFrame: """ 巨潮资讯-数据中心-专题统计-股东股本-实际控制人持股变动 https://webapi.cninfo.com.cn/#/thematicStatistics :param symbol: choice of {"深市主板", "沪市", "创业板", "科创板", "北交所", "全部"}; 从 2010 开始 :type symbol: str :return: 实际控制人持股变动 :rtype: pandas.DataFrame """ symbol_map = { "深市主板": "012002", "沪市": "012001", "创业板": "012015", "科创板": "012029", "北交所": "012046", "全部": "", } #https://webapi.cninfo.com.cn/api/sysapi/p_sysapi1029?market=012002 url = "https://webapi.cninfo.com.cn/api/sysapi/p_sysapi1029" js_code = py_mini_racer.MiniRacer() js_content = _get_file_content_cninfo("cninfo.js") js_code.eval(js_content) mcode = js_code.call("getResCode1") headers = { "Accept": "_/_", "Accept-Enckey": mcode, "Accept-Encoding": "gzip, deflate", "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8", "Cache-Control": "no-cache", "Content-Length": "0", "Host": "webapi.cninfo.com.cn", "Origin": "https://webapi.cninfo.com.cn", "Pragma": "no-cache", "Proxy-Connection": "keep-alive", "Referer": "https://webapi.cninfo.com.cn/", "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) " "Chrome/93.0.4577.63 Safari/537.36", "X-Requested-With": "XMLHttpRequest", } params = { "market": symbol_map[symbol], } r = requests.get(url, headers=headers, params=params) data_json = r.json() temp_df = pd.DataFrame(data_json["records"]) temp_df.columns = [ "已流通股份(万股)", "总股本(万股)", "交易市场", "证券简称", "公告日期", "变动原因", "证券代码", "变动日期", "流通受限股份(万股)", "已流通比例(%)", ] temp_df = temp_df[ [ "证券代码", "证券简称", "交易市场", "公告日期", "变动日期", "变动原因", "总股本(万股)", "已流通股份(万股)", "已流通比例(%)", "流通受限股份(万股)", ] ] temp_df["变动日期"] = pd.to_datetime(temp_df["变动日期"], errors="coerce").dt.date temp_df["公告日期"] = pd.to_datetime(temp_df["公告日期"], errors="coerce").dt.date temp_df["总股本(万股)"] = pd.to_numeric(temp_df["总股本(万股)"], errors="coerce") temp_df["已流通股份(万股)"] = pd.to_numeric(temp_df["已流通股份(万股)"], errors="coerce") temp_df["已流通比例(%)"] = pd.to_numeric(temp_df["已流通比例(%)"], errors="coerce") temp_df["流通受限股份(万股)"] = pd.to_numeric(temp_df["流通受限股份(万股)"], errors="coerce") return temp_df

谢谢，可以提交 PR 后合并代码
