### ISSUE TITLE
AKShare 接口中的期货数据里关于会员持仓排名在AKTools工具中不能正常使用

### ISSUE THREAD

**Issue by dahong38** [akfamily/akshare#5321]
问题简述：
         关于AKShare在使用AKTooks工具实现后，某些接口不能正常获取到数据，目前发现期货数据里关于“会员持仓排名”的全部接口（https://akshare.akfamily.xyz/data/futures/futures.html#id30）， 在使用AKTools中无法获取到数据，而且都是返回信息为：Invalid HTTP request received.；但若是在Python环境下，直接引用AKShare通过这些接口取数是正常的。
       **注：目前使用AKShare及AKTools的版本每次都是升至最后的**
       上述问题测试的环境截图：
![6b5df831972e521575fae867d20c1975_](https://github.com/user-attachments/assets/dcfc065f-6fc1-4b18-8861-04bb5728bf04)
**以下是Postman测试结果：**
![858212404169d82fdd5eadad585b2f9](https://github.com/user-attachments/assets/783d912d-7597-4f9c-b230-95d20b89d451)

**目前发现发下接口都存在上述问题：**
get_cffex_rank_table
get_czce_rank_table
futures_dce_position_rank
get_shfe_rank_table
futures_gfex_position_rank

请问上述问题是否能够解决？解决的结果希望这些有问题的接口能在AKTools工具配套下能正常使用获取到相关数据。由于本人是使用非Python语言环境作开发使用AKShare接口获取相应的数据作策略分析的，故急需要解决上述这部分接口无法通过AKTools工具后使用的问题！感谢！！！

**Comment by albertandking** [comment]
> 问题简述： 关于AKShare在使用AKTooks工具实现后，某些接口不能正常获取到数据，目前发现期货数据里关于“会员持仓排名”的全部接口（[https://akshare.akfamily.xyz/data/futures/futures.html#id30），](https://akshare.akfamily.xyz/data/futures/futures.html#id30%EF%BC%89%EF%BC%8C) 在使用AKTools中无法获取到数据，而且都是返回信息为：Invalid HTTP request received.；但若是在Python环境下，直接引用AKShare通过这些接口取数是正常的。 **注：目前使用AKShare及AKTools的版本每次都是升至最后的** 上述问题测试的环境截图： ![6b5df831972e521575fae867d20c1975_](https://private-user-images.githubusercontent.com/129848366/384588877-dcfc065f-6fc1-4b18-8861-04bb5728bf04.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyMTIwMDAsIm5iZiI6MTczMTIxMTcwMCwicGF0aCI6Ii8xMjk4NDgzNjYvMzg0NTg4ODc3LWRjZmMwNjVmLTZmYzEtNGIxOC04ODYxLTA0YmI1NzI4YmYwNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMFQwNDA4MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMTdhODhkYWZlMmZjNDRiNTBhNzRlZmMxMjQ4M2NlZWQ3ODk2MTFkNmM4MmU3MWEwYjk0NmRiNjRjY2Q4OTg2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.1yM-f2DAhl-kHX4bCrMhBCZ1-lyauQVSCvn4GIQVaQQ) **以下是Postman测试结果：** ![858212404169d82fdd5eadad585b2f9](https://private-user-images.githubusercontent.com/129848366/384588926-783d912d-7597-4f9c-b230-95d20b89d451.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyMTIwMDAsIm5iZiI6MTczMTIxMTcwMCwicGF0aCI6Ii8xMjk4NDgzNjYvMzg0NTg4OTI2LTc4M2Q5MTJkLTc1OTctNGY5Yy1iMjMwLTk1ZDIwYjg5ZDQ1MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMFQwNDA4MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MDgxNmI3YzlhZWViZTAyZTMxNGQwYzg4OTdhN2E2ZmY2YjE0OTMzZWJkZjYxN2QzMGY3NWQwYTMzM2Q2YmIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.NljjqrLxpClRy6G6zfbr9DTUkCRKE5FsoP0KCbHmoY4)
> 
> **目前发现发下接口都存在上述问题：** get_cffex_rank_table get_czce_rank_table futures_dce_position_rank get_shfe_rank_table futures_gfex_position_rank
> 
> 请问上述问题是否能够解决？解决的结果希望这些有问题的接口能在AKTools工具配套下能正常使用获取到相关数据。由于本人是使用非Python语言环境作开发使用AKShare接口获取相应的数据作策略分析的，故急需要解决上述这部分接口无法通过AKTools工具后使用的问题！感谢！！！

目前不是返回 pandas.DataFrame 的格式都不能正常返回

**Comment by albertandking** [comment]
> 问题简述： 关于AKShare在使用AKTooks工具实现后，某些接口不能正常获取到数据，目前发现期货数据里关于“会员持仓排名”的全部接口（[https://akshare.akfamily.xyz/data/futures/futures.html#id30），](https://akshare.akfamily.xyz/data/futures/futures.html#id30%EF%BC%89%EF%BC%8C) 在使用AKTools中无法获取到数据，而且都是返回信息为：Invalid HTTP request received.；但若是在Python环境下，直接引用AKShare通过这些接口取数是正常的。 **注：目前使用AKShare及AKTools的版本每次都是升至最后的** 上述问题测试的环境截图： ![6b5df831972e521575fae867d20c1975_](https://private-user-images.githubusercontent.com/129848366/384588877-dcfc065f-6fc1-4b18-8861-04bb5728bf04.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyMTIwMDAsIm5iZiI6MTczMTIxMTcwMCwicGF0aCI6Ii8xMjk4NDgzNjYvMzg0NTg4ODc3LWRjZmMwNjVmLTZmYzEtNGIxOC04ODYxLTA0YmI1NzI4YmYwNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMFQwNDA4MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMTdhODhkYWZlMmZjNDRiNTBhNzRlZmMxMjQ4M2NlZWQ3ODk2MTFkNmM4MmU3MWEwYjk0NmRiNjRjY2Q4OTg2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.1yM-f2DAhl-kHX4bCrMhBCZ1-lyauQVSCvn4GIQVaQQ) **以下是Postman测试结果：** ![858212404169d82fdd5eadad585b2f9](https://private-user-images.githubusercontent.com/129848366/384588926-783d912d-7597-4f9c-b230-95d20b89d451.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyMTIwMDAsIm5iZiI6MTczMTIxMTcwMCwicGF0aCI6Ii8xMjk4NDgzNjYvMzg0NTg4OTI2LTc4M2Q5MTJkLTc1OTctNGY5Yy1iMjMwLTk1ZDIwYjg5ZDQ1MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMFQwNDA4MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MDgxNmI3YzlhZWViZTAyZTMxNGQwYzg4OTdhN2E2ZmY2YjE0OTMzZWJkZjYxN2QzMGY3NWQwYTMzM2Q2YmIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.NljjqrLxpClRy6G6zfbr9DTUkCRKE5FsoP0KCbHmoY4)
> 
> **目前发现发下接口都存在上述问题：** get_cffex_rank_table get_czce_rank_table futures_dce_position_rank get_shfe_rank_table futures_gfex_position_rank
> 
> 请问上述问题是否能够解决？解决的结果希望这些有问题的接口能在AKTools工具配套下能正常使用获取到相关数据。由于本人是使用非Python语言环境作开发使用AKShare接口获取相应的数据作策略分析的，故急需要解决上述这部分接口无法通过AKTools工具后使用的问题！感谢！！！

目前不是返回 pandas.DataFrame 的格式都不能正常返回

**Comment by dahong38** [comment]
pandas.DataFrame格式应该也是在Python环境下使用吧？我的项目就是因为不使用Python环境才使用AKTools工具在第三方开发语言里能使用到AKShare接口获取财经数据。所以，简单而言，只要通过AKTools工具后，能在Postman中正常获取到数据就可以了。目前就是出现了上述问题。

**Comment by dahong38** [comment]
确实在AKTools下无法正常返回pandas.DataFrame格式的数据。
