### ISSUE TITLE
AKShare 接口问题报告 | AKShare Interface Issue Report

### ISSUE THREAD

**Issue by xpwang0925** [akfamily/akshare#5325]
AKShare 已升级到最新版本 1.15.20
调用的接口： get_futures_daily 
代码如下： 
current_time = datetime.now()
formatted_now = current_time.strftime("%Y-%m-%d %H:%M:%S")
curret_date = current_time.strftime("%Y-%m-%d")
curret_date_f6 = current_time.strftime("%Y%m")
print(ak.__version__)

get_futures_daily_df = ak.get_futures_daily(start_date='20200101', end_date='20200101', market="DCE")
print(get_futures_daily_df)

报错信息：
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[1], line 344
    342 curret_date_f6 = current_time.strftime("%Y%m")
    343 logger.info("开始获取: 交割统计-大连商品交易所")
--> 344 get_futures_daily_df = ak.get_futures_daily(start_date='20200101', end_date='20200101', market="DCE")
    345 print(get_futures_daily_df)
    346 # print(formatted_now)
    347 # get_futures_daily_df['etl_time'] = formatted_now
    348 # db_util.df_save_to_mysql(df=get_futures_daily_df, table_name='dce_futures_daily')
   (...)
    419     # print("start_date: " + str(start_date))
    420     # print(futures_dce_wh_receipt_df)

File [~/miniconda3/lib/python3.11/site-packages/akshare/futures/futures_daily_bar.py:677](http://10.1.118.134:8082/lab/tree/root/outerdata/outerdata/~/miniconda3/lib/python3.11/site-packages/akshare/futures/futures_daily_bar.py#line=676), in get_futures_daily(start_date, end_date, market)
    675 if len(df_list) > 0:
    676     temp_df = pd.concat(df_list).reset_index(drop=True)
--> 677     temp_df = temp_df[~temp_df["symbol"].str.contains("efp")]
    678     return temp_df

File [~/miniconda3/lib/python3.11/site-packages/pandas/core/frame.py:4102](http://10.1.118.134:8082/lab/tree/root/outerdata/outerdata/~/miniconda3/lib/python3.11/site-packages/pandas/core/frame.py#line=4101), in DataFrame.__getitem__(self, key)
   4100 if self.columns.nlevels > 1:
   4101     return self._getitem_multilevel(key)
-> 4102 indexer = self.columns.get_loc(key)
   4103 if is_integer(indexer):
   4104     indexer = [indexer]

File [~/miniconda3/lib/python3.11/site-packages/pandas/core/indexes/range.py:417](http://10.1.118.136:8082/lab/tree/root/outerdata/outerdata/~/miniconda3/lib/python3.11/site-packages/pandas/core/indexes/range.py#line=416), in RangeIndex.get_loc(self, key)
    415         raise KeyError(key) from err
    416 if isinstance(key, Hashable):
--> 417     raise KeyError(key)
    418 self._check_indexing_error(key)
    419 raise KeyError(key)

KeyError: 'symbol'

期望获得的结果： 之前在1.13.7  上执行是正常的。 升级版本后报错。期望执行结果不要报错，可以继续使用

**Comment by albertandking** [comment]
> AKShare 已升级到最新版本 1.15.20 调用的接口： get_futures_daily 代码如下： current_time = datetime.now() formatted_now = current_time.strftime("%Y-%m-%d %H:%M:%S") curret_date = current_time.strftime("%Y-%m-%d") curret_date_f6 = current_time.strftime("%Y%m") print(ak.**version**)
> 
> get_futures_daily_df = ak.get_futures_daily(start_date='20200101', end_date='20200101', market="DCE") print(get_futures_daily_df)
> 
> ## 报错信息：
> KeyError Traceback (most recent call last) Cell In[1], line 344 342 curret_date_f6 = current_time.strftime("%Y%m") 343 logger.info("开始获取: 交割统计-大连商品交易所") --> 344 get_futures_daily_df = ak.get_futures_daily(start_date='20200101', end_date='20200101', market="DCE") 345 print(get_futures_daily_df) 346 # print(formatted_now) 347 # get_futures_daily_df['etl_time'] = formatted_now 348 # db_util.df_save_to_mysql(df=get_futures_daily_df, table_name='dce_futures_daily') (...) 419 # print("start_date: " + str(start_date)) 420 # print(futures_dce_wh_receipt_df)
> 
> File [~/miniconda3/lib/python3.11/site-packages/akshare/futures/futures_daily_bar.py:677](http://10.1.118.134:8082/lab/tree/root/outerdata/outerdata/~/miniconda3/lib/python3.11/site-packages/akshare/futures/futures_daily_bar.py#line=676), in get_futures_daily(start_date, end_date, market) 675 if len(df_list) > 0: 676 temp_df = pd.concat(df_list).reset_index(drop=True) --> 677 temp_df = temp_df[~temp_df["symbol"].str.contains("efp")] 678 return temp_df
> 
> File [~/miniconda3/lib/python3.11/site-packages/pandas/core/frame.py:4102](http://10.1.118.134:8082/lab/tree/root/outerdata/outerdata/~/miniconda3/lib/python3.11/site-packages/pandas/core/frame.py#line=4101), in DataFrame.**getitem**(self, key) 4100 if self.columns.nlevels > 1: 4101 return self._getitem_multilevel(key) -> 4102 indexer = self.columns.get_loc(key) 4103 if is_integer(indexer): 4104 indexer = [indexer]
> 
> File [~/miniconda3/lib/python3.11/site-packages/pandas/core/indexes/range.py:417](http://10.1.118.136:8082/lab/tree/root/outerdata/outerdata/~/miniconda3/lib/python3.11/site-packages/pandas/core/indexes/range.py#line=416), in RangeIndex.get_loc(self, key) 415 raise KeyError(key) from err 416 if isinstance(key, Hashable): --> 417 raise KeyError(key) 418 self._check_indexing_error(key) 419 raise KeyError(key)
> 
> KeyError: 'symbol'
> 
> 期望获得的结果： 之前在1.13.7 上执行是正常的。 升级版本后报错。期望执行结果不要报错，可以继续使用

接口测试正常

**Comment by xpwang0925** [comment]
请问最新的版本是： 1.15.20  吗？ 我这没有任何逻辑啊
