### ISSUE TITLE
AKShare 接口问题报告 | AKShare Interface Issue Report

### ISSUE THREAD

**Issue by blackwatch1998** [akfamily/akshare#5336]
操作系统版本：Windows 10.0.19045 64位
Python版本：Python3.11
AKShare版本：1.15.22
接口名称：ak.stock_sector_fund_flow_summary
调用代码：ak.stock_sector_fund_flow_summary(symbol="文化传媒", indicator="今日")
我查看了东方财富对应的界面，文化传媒板块中个股的资金流数据是大于50个的，但是接口只返回了第一页的数据，即前50个，有部分数据是丢失。其他板块中个股数量多于50个的也有类似的情况。

**Comment by albertandking** [comment]
> 操作系统版本：Windows 10.0.19045 64位 Python版本：Python3.11 AKShare版本：1.15.22 接口名称：ak.stock_sector_fund_flow_summary 调用代码：ak.stock_sector_fund_flow_summary(symbol="文化传媒", indicator="今日") 我查看了东方财富对应的界面，文化传媒板块中个股的资金流数据是大于50个的，但是接口只返回了第一页的数据，即前50个，有部分数据是丢失。其他板块中个股数量多于50个的也有类似的情况。

已修复，升级到 AKShare 1.15.23 使用
