### ISSUE TITLE
option_dce_daily获取 鸡蛋期权\玉米淀粉期权\生猪期权 字段问题

### ISSUE THREAD

**Issue by dadunu** [akfamily/akshare#5341]
版本-- akshare-1.15.25
环境-- python3.10

通过 option_dce_daily 获取 鸡蛋期权\玉米淀粉期权\生猪期权 
"合约系列"字段的内容返回都是 苯乙烯期权 的内容, 请见附图
![snap_20241118164141](https://github.com/user-attachments/assets/7270a7dc-33ca-4b30-890b-db1bf2328a56)
![snap_20241118164405](https://github.com/user-attachments/assets/dfbedba5-acdc-478f-b54b-3c788752307b)
![snap_20241118164436](https://github.com/user-attachments/assets/aa3a84d8-d995-449b-a3c6-b1936fd507ed)

**Comment by albertandking** [comment]
> 版本-- akshare-1.15.25 环境-- python3.10
> 
> 通过 option_dce_daily 获取 鸡蛋期权\玉米淀粉期权\生猪期权 "合约系列"字段的内容返回都是 苯乙烯期权 的内容, 请见附图 ![snap_20241118164141](https://private-user-images.githubusercontent.com/50010355/387133871-7270a7dc-33ca-4b30-890b-db1bf2328a56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5MjA1MTQsIm5iZiI6MTczMTkyMDIxNCwicGF0aCI6Ii81MDAxMDM1NS8zODcxMzM4NzEtNzI3MGE3ZGMtMzNjYS00YjMwLTg5MGItZGIxYmYyMzI4YTU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE4VDA4NTY1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjYTlkNDkxOTJiYmY1ZGRiZDI0NGI1MDMyMDNjY2JlMjc3YjVjNjY1ZTkwN2JhMDgxYjIzYmI2NmE5ZDEwODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7v_LuHieZGaxfHxGF9teYcy3R7tyvU18-RDWZoeDmVc) ![snap_20241118164405](https://private-user-images.githubusercontent.com/50010355/387134724-dfbedba5-acdc-478f-b54b-3c788752307b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5MjA1MTQsIm5iZiI6MTczMTkyMDIxNCwicGF0aCI6Ii81MDAxMDM1NS8zODcxMzQ3MjQtZGZiZWRiYTUtYWNkYy00NzhmLWI1NGItM2M3ODg3NTIzMDdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE4VDA4NTY1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhOTA2NTBhZjJmMDAxYWM4MmJjMWY0ZDg3ZWJhZjRmZTBjMmZiOThjZDcyZDVkMDQ0YzgxMzljZDk0MjIwOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.TtAdjTApJ2j-0jF4goL_zO2NR02fVqdP5yhRsWHl52k) ![snap_20241118164436](https://private-user-images.githubusercontent.com/50010355/387134775-aa3a84d8-d995-449b-a3c6-b1936fd507ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5MjA1MTQsIm5iZiI6MTczMTkyMDIxNCwicGF0aCI6Ii81MDAxMDM1NS8zODcxMzQ3NzUtYWEzYTg0ZDgtZDk5NS00NDliLWEzYzYtYjE5MzZmZDUwN2VkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE4VDA4NTY1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2Y2ZlNjZhNmU0NmViNzA1N2E1ZDM1NTVkZWQ0N2Q5M2MwN2YyNDZhN2Q1ZmUxNTIzMmY5ZTU4MThmN2U3OTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nU5T7kSfSGxWFGXK84EcUQITj5Ao2SlG_rUKxQIj5pY)

感谢反馈问题，已修复该问题，升级到 AKShare 1.15.26 使用
