### ISSUE TITLE
AKShare 接口问题报告 | AKShare Interface Issue Report

### ISSUE THREAD

**Issue by Yzx-1024** [akfamily/akshare#5345]
原木期货在大连商品交易所上市了，代码需要同步更新。本地akshare版本已升级到1.15.23。
运行ak.get_futures_daily报错如下截图。
![捕获](https://github.com/user-attachments/assets/5b22a7fa-5d8d-419d-8e4c-6e51be8d6345)

谢谢支持。

**Comment by albertandking** [comment]
> 原木期货在大连商品交易所上市了，代码需要同步更新。本地akshare版本已升级到1.15.23。 运行ak.get_futures_daily报错如下截图。 ![捕获](https://private-user-images.githubusercontent.com/177444434/387159827-5b22a7fa-5d8d-419d-8e4c-6e51be8d6345.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5MjM2ODEsIm5iZiI6MTczMTkyMzM4MSwicGF0aCI6Ii8xNzc0NDQ0MzQvMzg3MTU5ODI3LTViMjJhN2ZhLTVkOGQtNDE5ZC04ZTRjLTZlNTFiZThkNjM0NS5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExOFQwOTQ5NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYThiZDNlYjVhZWE4YWUyMzVlNTc5ZTkwZjJjYjA2ZmFkNzMwZjhhMWJkYzZjNzA4ZWZlYjQ5ZmYyMTgzYTkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.TBVVaseNWFHEDNSuViwjdH6Gehos_g--yNmP8Ragu2s)
> 
> 谢谢支持。

接口测试正常

**Comment by Yzx-1024** [comment]
a = ak.get_futures_daily(start_date='20241118', end_date='20241118', market='DCE') 是测试的这个接口？日期是今天，加了新品种，字典里没有这个。

**Comment by albertandking** [comment]
> a = ak.get_futures_daily(start_date='20241118', end_date='20241118', market='DCE') 是测试的这个接口？日期是今天，加了新品种，字典里没有这个。

最新版已经支持
