### ISSUE TITLE
请增加获取北证50数据接口

### ISSUE THREAD

**Issue by simon-yanghl** [akfamily/akshare#5346]
经过阅读文档、查看原网页，发现只能获取上证指数和深证成指两个重要指数指标，没有获取北证50的接口
在网页[连接](https://quote.eastmoney.com/center/hszs.html)中可以看到
![image](https://github.com/user-attachments/assets/7d44b66a-4704-4f01-8563-20ed3aa101cb)
上证指数、深证成指和北证50是排在最前面的三个指数

烦请添加北证50的获取接口，谢谢
如已有接口，请指出。

**Comment by simon-yanghl** [comment]
补充说明：在东财的接口里 ak.stock_zh_index_spot_em(symbol="上证系列指数")是需要分别使用"上证系列指数", "深证系列指数", "指数成份", "中证系列指数"来获取相应数据，但是在[网页](https://quote.eastmoney.com/center/hszs.html)下面的沪深重要指数可以一次获取大部分重要指数数据，是否可以一并添加相关接口？

**Comment by albertandking** [comment]
> 经过阅读文档、查看原网页，发现只能获取上证指数和深证成指两个重要指数指标，没有获取北证50的接口 在网页[连接](https://quote.eastmoney.com/center/hszs.html)中可以看到 ![image](https://private-user-images.githubusercontent.com/63163745/387300894-7d44b66a-4704-4f01-8563-20ed3aa101cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMTk0NTQsIm5iZiI6MTczMjAxOTE1NCwicGF0aCI6Ii82MzE2Mzc0NS8zODczMDA4OTQtN2Q0NGI2NmEtNDcwNC00ZjAxLTg1NjMtMjBlZDNhYTEwMWNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE5VDEyMjU1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwZTFjYTQzNmI0NzYzYTEwMjNjZWY4OTk0NDM2ZDY3MjFlZjZhMjY3N2M3YjU1NzAxYmM1MDYwMzMwMjBmMDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vGQaiUOtCwq8MrsrlvcDhY7Kf4uo_o3QcsIGQmu9uW4) 上证指数、深证成指和北证50是排在最前面的三个指数
> 
> 烦请添加北证50的获取接口，谢谢 如已有接口，请指出。

已新增相关的 symbol 字段，请参考文档获取，升级到 AKShare 1.15.27 使用
