### ISSUE TITLE
AKShare 接口需求

### ISSUE THREAD

**Issue by yyri** [akfamily/akshare#5351]
首先，感谢提供大家这么好用的一个工具，提一个小需求。

申万行业分类的接口  sw_index_second_info，目前是直接提供了各级的行业名称列表，但是没有二级一级或者三级和二级的关联关系，不知道可否加上？其实在目前的数据源上是有这个信息的。

感谢！

**Comment by albertandking** [comment]
> 首先，感谢提供大家这么好用的一个工具，提一个小需求。
> 
> 申万行业分类的接口 sw_index_second_info，目前是直接提供了各级的行业名称列表，但是没有二级一级或者三级和二级的关联关系，不知道可否加上？其实在目前的数据源上是有这个信息的。
> 
> 感谢！

已在相关接口增加字段，升级到 AKShare 1.15.28 使用

**Comment by yyri** [comment]
> > 首先，感谢提供大家这么好用的一个工具，提一个小需求。
> > 申万行业分类的接口 sw_index_second_info，目前是直接提供了各级的行业名称列表，但是没有二级一级或者三级和二级的关联关系，不知道可否加上？其实在目前的数据源上是有这个信息的。
> > 感谢！
> 
> 已在相关接口增加字段，升级到 AKShare 1.15.28 使用

感谢感谢
