### ISSUE TITLE
AKShare 接口问题报告 | AKShare Interface Issue Report

### ISSUE THREAD

**Issue by Thalesoflaf** [akfamily/akshare#5353]
接口：

港股估值指标

接口: stock_hk_valuation_baidu

目标地址: https://gushitong.baidu.com/stock/hk-06969

描述: 百度股市通-港股-财务报表-估值数据

限量: 单次获取指定 symbol 的指定 indicator 的特定 period 的历史数据

stock_hk_valuation_baidu_df = ak.stock_hk_valuation_baidu(symbol="02358", indicator="总市值", period="近一年")

问题：给出的数据是港股流通市值，而不是总市值。

00921给出的市值
![image](https://github.com/user-attachments/assets/9cc52a97-7ccd-40e1-822f-05fb68e2ba1e)

雪球显示给出的是港股流通市值，是总市值的1/3左右
![image](https://github.com/user-attachments/assets/c56f3b95-9c74-4bb4-a845-44a2e2ffcf06)

**Comment by albertandking** [comment]
> 接口：
> 
> 港股估值指标
> 
> 接口: stock_hk_valuation_baidu
> 
> 目标地址: https://gushitong.baidu.com/stock/hk-06969
> 
> 描述: 百度股市通-港股-财务报表-估值数据
> 
> 限量: 单次获取指定 symbol 的指定 indicator 的特定 period 的历史数据
> 
> stock_hk_valuation_baidu_df = ak.stock_hk_valuation_baidu(symbol="02358", indicator="总市值", period="近一年")
> 
> 问题：给出的数据是港股流通市值，而不是总市值。
> 
> 00921给出的市值 ![image](https://private-user-images.githubusercontent.com/189190152/388340326-9cc52a97-7ccd-40e1-822f-05fb68e2ba1e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxODM3NTEsIm5iZiI6MTczMjE4MzQ1MSwicGF0aCI6Ii8xODkxOTAxNTIvMzg4MzQwMzI2LTljYzUyYTk3LTdjY2QtNDBlMS04MjJmLTA1ZmI2OGUyYmExZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMVQxMDA0MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NTAxMjNkNzA2ZjNiYTdmZTk0OGE1NDU2MDM3YmE0N2ZhZmY0OWI4MWExYjk5NTc4ZjA0OTdlMzg3NThmMzM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.eyzptsgZZFslsId6opyyczeGMc4P0iknhoHDLUHQoUg)
> 
> 雪球显示给出的是港股流通市值，是总市值的1/3左右 ![image](https://private-user-images.githubusercontent.com/189190152/388340627-c56f3b95-9c74-4bb4-a845-44a2e2ffcf06.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxODM3NTEsIm5iZiI6MTczMjE4MzQ1MSwicGF0aCI6Ii8xODkxOTAxNTIvMzg4MzQwNjI3LWM1NmYzYjk1LTljNzQtNGJiNC1hODQ1LTQ0YTJlMmZmY2YwNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMVQxMDA0MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MDMwZTY1YjgzYTk1YWJlZThlYmQ5YjkyYjMxZGYyNmFlNzI0YzVjOWM1Nzk5NjM1YWI5ZGE1ZjEzZmIzNzA5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.YPXdf3utRM3kzRIbXRvejW57CKPLtcz7A46C65_qIcE)

以数据源提供的数据为准，目前修改相关接口，你可以测试下，升级到 AKShare 1.15.28 使用
