### ISSUE TITLE
AKShare 接口问题报告 | AKShare Interface Issue Report

### ISSUE THREAD

**Issue by Wa-JHH** [akfamily/akshare#5359]
**详细问题描述** | Detailed Problem Description
操作系统版版本: Debian12 
Python版本: 3.11.x
AKShare版本: 1.15.26
接口名称: fund_etf_category_sina

调用代码
fund_etf_category_sina_df = ak.fund_etf_category_sina(symbol="ETF基金")

该接的参数
params = {
        "page": "1",
        **"num": "1000",**  #这个接口限制了只返回1000行数据
        "sort": "symbol",
        "asc": "0",
        "node": fund_map[symbol],
        "[object HTMLDivElement]": "qvvne",
    }

实际上目前ETF已经超过1000个，我尝试过改为2000，就可以正常获取全部ETF名称和代码

**Comment by albertandking** [comment]
> **详细问题描述** | Detailed Problem Description 操作系统版版本: Debian12 Python版本: 3.11.x AKShare版本: 1.15.26 接口名称: fund_etf_category_sina
> 
> 调用代码 fund_etf_category_sina_df = ak.fund_etf_category_sina(symbol="ETF基金")
> 
> 该接的参数 params = { "page": "1", **"num": "1000",** #这个接口限制了只返回1000行数据 "sort": "symbol", "asc": "0", "node": fund_map[symbol], "[object HTMLDivElement]": "qvvne", }
> 
> 实际上目前ETF已经超过1000个，我尝试过改为2000，就可以正常获取全部ETF名称和代码

已修复，升级到 AKShare 1.15.30 使用
