### ISSUE TITLE
下载了最新版akshare库1.15.32，为什么执行失败，怎么解决呢

### ISSUE THREAD

**Issue by Yuan-li123** [akfamily/akshare#5367]
下载了最新版akshare库1.15.32，为什么执行失败，怎么解决呢，接口也是1.15.32文档里的
![1](https://github.com/user-attachments/assets/ef92bcee-6090-40d1-953f-c6cda39ccf5a)
![2](https://github.com/user-attachments/assets/e6078fad-6bf4-4520-947e-015368f4d6bb)

**Comment by albertandking** [comment]
> 下载了最新版akshare库1.15.32，为什么执行失败，怎么解决呢，接口也是1.15.32文档里的 ![1](https://private-user-images.githubusercontent.com/181586671/389264569-ef92bcee-6090-40d1-953f-c6cda39ccf5a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0NjI2ODgsIm5iZiI6MTczMjQ2MjM4OCwicGF0aCI6Ii8xODE1ODY2NzEvMzg5MjY0NTY5LWVmOTJiY2VlLTYwOTAtNDBkMS05NTNmLWM2Y2RhMzljY2Y1YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNFQxNTMzMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYTI4MmE3ZDEzNjQ5MDI2MjVhZTZlNTE0ZDJlZWYwYWZhYTJiOWFjMGY5ZjMwZWU1NjEzMzhlOTJlMTExZDViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.rojXHfXbd0cxLSmPJJtssyRVVeKkPmAfW0FT4ywuZ98) ![2](https://private-user-images.githubusercontent.com/181586671/389264574-e6078fad-6bf4-4520-947e-015368f4d6bb.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0NjI2ODgsIm5iZiI6MTczMjQ2MjM4OCwicGF0aCI6Ii8xODE1ODY2NzEvMzg5MjY0NTc0LWU2MDc4ZmFkLTZiZjQtNDUyMC05NDdlLTAxNTM2OGY0ZDZiYi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNFQxNTMzMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MGU2Y2RhNmE3OTc1MWRjNDA5YTFjYjRmY2FlOGZiNjE5MTFjODM3NjA0YzZiMTU1ZTNiY2ZmOTc3MTllMWNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.H_huQr-7EqyxhDGhXxN_puPtfPEKy_w_nZ1qPRd-tWU)

![image](https://github.com/user-attachments/assets/0cb6867e-7b14-4e65-b4be-62911344754e)
切换路径名

**Comment by Yuan-li123** [comment]
> > 下载了最新版akshare库1.15.32，为什么执行失败，怎么解决呢，接口也是1.15.32文档里的![1](https://private-user-images.githubusercontent.com/181586671/389264569-ef92bcee-6090-40d1-953f-c6cda39ccf5a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0NjI2ODgsIm5iZiI6MTczMjQ2MjM4OCwicGF0aCI6Ii8xODE1ODY2NzEvMzg5MjY0NTY5LWVmOTJiY2VlLTYwOTAtNDBkMS05NTNmLWM2Y2RhMzljY2Y1YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNFQxNTMzMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYTI4MmE3ZDEzNjQ5MDI2MjVhZTZlNTE0ZDJlZWYwYWZhYTJiOWFjMGY5ZjMwZWU1NjEzMzhlOTJlMTExZDViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.rojXHfXbd0cxLSmPJJtssyRVVeKkPmAfW0FT4ywuZ98) ![2](https://private-user-images.githubusercontent.com/181586671/389264574-e6078fad-6bf4-4520-947e-015368f4d6bb.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0NjI2ODgsIm5iZiI6MTczMjQ2MjM4OCwicGF0aCI6Ii8xODE1ODY2NzEvMzg5MjY0NTc0LWU2MDc4ZmFkLTZiZjQtNDUyMC05NDdlLTAxNTM2OGY0ZDZiYi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNFQxNTMzMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MGU2Y2RhNmE3OTc1MWRjNDA5YTFjYjRmY2FlOGZiNjE5MTFjODM3NjA0YzZiMTU1ZTNiY2ZmOTc3MTllMWNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.H_huQr-7EqyxhDGhXxN_puPtfPEKy_w_nZ1qPRd-tWU)
> 
> ![图像](https://private-user-images.githubusercontent.com/18234520/389285269-0cb6867e-7b14-4e65-b4be-62911344754e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0NjMwMTcsIm5iZiI6MTczMjQ2MjcxNywicGF0aCI6Ii8xODIzNDUyMC8zODkyODUyNjktMGNiNjg2N2UtN2IxNC00ZTY1LWI0YmUtNjI5MTEzNDQ3NTRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI0VDE1MzgzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0ZmViYTE0YTFiZGUxMDU2MjFkYjkwOWIzMjgzYjE4MjgwMDc4YWQzMDk3OGIxMDk0MmI3ZjU0MmNiMmE1MjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Z0vxZv2WUw--0wkezry2p569YzA5gdP7i26PfjsvlnA)切换路径名

我已经解决了，谢谢！
