### ISSUE TITLE
AKShare 接口问题报告 | AKShare Interface Issue Report

### ISSUE THREAD

**Issue by vercity** [akfamily/akshare#5368]
Mac Sequoia 15.1
最新版AKShare
电报-财联社接口不返回新数据，最新数据停止在 2024.11.22 20:19:00 左右

调用方式
stock_info_global_cls_df = ak.stock_info_global_cls(symbol="全部")

![image](https://github.com/user-attachments/assets/1f3821e8-acd0-4f4f-8de8-266b9d8acf15)

**Comment by albertandking** [comment]
> stock_info_global_cls

升级到最新版使用

**Comment by vercity** [comment]
就是升级到最新使用stock_info_global_cls，还是没返回最新的，如1L截图
