### ISSUE TITLE
通过akshare获取可转债的日线数据和赎回信息

### ISSUE THREAD

**Issue by Yuan-li123** [akfamily/akshare#5369]
通过akshare获取可转债的日线数据和赎回信息，计算2024年10月1日2024年11月23日，计算可转债每日债转股数据，债权余额，数据库用mysql，开发语言用python
![1](https://github.com/user-attachments/assets/6e9ad0dc-acac-4b95-b84a-72d28c736b03)
![2](https://github.com/user-attachments/assets/d79eddeb-65db-46a4-8884-b3a08addff78)
![3](https://github.com/user-attachments/assets/778b5d92-2fdd-46f4-ba4f-1d93d913c151)
![4](https://github.com/user-attachments/assets/8152ebdb-9d4a-4ae7-bb53-34ce0e93066d)
根据这个题目，我需要使用的接口是哪些啊，以上代码有哪些地方是需要修改的呢

**Comment by albertandking** [comment]
> 通过akshare获取可转债的日线数据和赎回信息，计算2024年10月1日2024年11月23日，计算可转债每日债转股数据，债权余额，数据库用mysql，开发语言用python ![1](https://private-user-images.githubusercontent.com/181586671/389286154-6e9ad0dc-acac-4b95-b84a-72d28c736b03.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1MTY3MTEsIm5iZiI6MTczMjUxNjQxMSwicGF0aCI6Ii8xODE1ODY2NzEvMzg5Mjg2MTU0LTZlOWFkMGRjLWFjYWMtNGI5NS1iODRhLTcyZDI4YzczNmIwMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNVQwNjMzMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMTllZmUwMTZmYmVjMTE5MzRlN2I1Y2RjNTczOWMwMmZjNGJkMTFhNzEzZTNmZGQ5MWUyZWE1ZDMzZjQ4NDY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.GnBEHCBdV6tXCI6B-orjMd4oYGTZ3Igk6Fy3KlTfDOE) ![2](https://private-user-images.githubusercontent.com/181586671/389286158-d79eddeb-65db-46a4-8884-b3a08addff78.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1MTY3MTEsIm5iZiI6MTczMjUxNjQxMSwicGF0aCI6Ii8xODE1ODY2NzEvMzg5Mjg2MTU4LWQ3OWVkZGViLTY1ZGItNDZhNC04ODg0LWIzYTA4YWRkZmY3OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNVQwNjMzMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03Yjc1Nzk0ZmRlM2Y2YjcyYWJhOGM2MGU5Y2U0ZmM1OWYxMzFkOGFmN2JiMDI1MDU4MzgyZTVmZmYxYTVkMGI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.aqlj62gwuVkuJntDbFkP9b_s_l5bCUTGMeJOOEpWrzo) ![3](https://private-user-images.githubusercontent.com/181586671/389286162-778b5d92-2fdd-46f4-ba4f-1d93d913c151.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1MTY3MTEsIm5iZiI6MTczMjUxNjQxMSwicGF0aCI6Ii8xODE1ODY2NzEvMzg5Mjg2MTYyLTc3OGI1ZDkyLTJmZGQtNDZmNC1iYTRmLTFkOTNkOTEzYzE1MS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNVQwNjMzMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MzVlNjQ1NDU4ZjA1MDcwM2Q2MmU4NjZjMDRjMmYwMzRjOGUyYzFlOThkMTY4YmY1MDlkNWU2NjhhZWJlMmIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.wHLYL_h-b7afimUnJtJwCvpSFHNqu1F4kGII48Xn8mY) ![4](https://private-user-images.githubusercontent.com/181586671/389286166-8152ebdb-9d4a-4ae7-bb53-34ce0e93066d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1MTY3MTEsIm5iZiI6MTczMjUxNjQxMSwicGF0aCI6Ii8xODE1ODY2NzEvMzg5Mjg2MTY2LTgxNTJlYmRiLTlkNGEtNGFlNy1iYjUzLTM0Y2UwZTkzMDY2ZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNVQwNjMzMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NDZhNmNjMWZlZGVhNThmMmE3M2Q4YzUzYTgwMmRmYjI4ZTc4Y2RjZDEzZTc3Njc4YjJkNGMwMmU0ZDlmOTI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.TFGLwUmZ0PAAbLt_v48e9q1qR0HMPCVYE4fQ6fXCKtc) 根据这个题目，我需要使用的接口是哪些啊，以上代码有哪些地方是需要修改的呢

issues 只关注接口本身的问题
