### ISSUE TITLE
stock_zh_a_spot间隔有什么缓存的方法

### ISSUE THREAD

**Issue by caihua** [akfamily/akshare#5370]
stock_data = ak.stock_zh_a_spot()
print(stock_data)

你的 IP 存在异常访问(例如: 爬虫/攻击/探测 等), 已被新浪安全部门封禁.

这个接口我想调试下程序，所以需要不停的执行，
目前看连续执行2次就被封了，

而且每次执行还要进度条，特别慢，

既然需要间隔15分钟，本来也没法连续执行，是否可以增加缓存，第二次就判断缓存时间，超过时间才取，
超过15分钟才取最新的。
有没有什么缓存的办法？

**Comment by albertandking** [comment]
> stock_data = ak.stock_zh_a_spot() print(stock_data)
> 
> 你的 IP 存在异常访问(例如: 爬虫/攻击/探测 等), 已被新浪安全部门封禁.
> 
> 这个接口我想调试下程序，所以需要不停的执行， 目前看连续执行2次就被封了，
> 
> 而且每次执行还要进度条，特别慢，
> 
> 既然需要间隔15分钟，本来也没法连续执行，是否可以增加缓存，第二次就判断缓存时间，超过时间才取， 超过15分钟才取最新的。 有没有什么缓存的办法？

可以在本地处理
