### ISSUE TITLE
AKShare stock_share_change_cninfo错误问题

### ISSUE THREAD

**Issue by webbery** [akfamily/akshare#5372]
![image](https://github.com/user-attachments/assets/65d5638c-041a-4094-99ce-7ecd93440aa8)

最新版本输出错误，请帮忙查看

**Comment by albertandking** [comment]
> ![image](https://private-user-images.githubusercontent.com/5257853/389802033-65d5638c-041a-4094-99ce-7ecd93440aa8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2MTUxMTEsIm5iZiI6MTczMjYxNDgxMSwicGF0aCI6Ii81MjU3ODUzLzM4OTgwMjAzMy02NWQ1NjM4Yy0wNDFhLTQwOTQtOTljZS03ZWNkOTM0NDBhYTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjZUMDk1MzMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWZhMmZlZjAxZjQwMjMzODlhZDVhNmE3MGNiNTJmNDAzYTI3YTQzM2I1YzNjYmQ4ZDk3YzRkNDVkMmM2NjVmMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.h1IOdH4CbRgP7qBXRyU4yT5mM64IZOCFe8SubDGmcGk)
> 
> 最新版本输出错误，请帮忙查看

请按 issues 提交信息
