### ISSUE TITLE
可以增加一个估值分析的数据吗？

### ISSUE THREAD

**Issue by raymond8023** [akfamily/akshare#5373]
目标：https://data.eastmoney.com/gzfx/detail/300766.html
可以获取历史上每天的估值分析数据

**Comment by albertandking** [comment]
> 目标：https://data.eastmoney.com/gzfx/detail/300766.html 可以获取历史上每天的估值分析数据

新增 stock_value_em 接口，升级到 AKShare 1.15.33 使用
