### ISSUE TITLE
似乎找不到一些基础信息

### ISSUE THREAD

**Issue by caihua** [akfamily/akshare#5375]
A股股票，例如公司地址，所属省份，所有制性质，员工人数，等基础信息。

**Comment by albertandking** [comment]
> A股股票，例如公司地址，所属省份，所有制性质，员工人数，等基础信息。

可以在文档搜索下

**Comment by albertandking** [comment]
升级到 AKShare 1.16.40 新增 stock_individual_basic_info_xq 接口

**Comment by albertandking** [comment]
> A股股票，例如公司地址，所属省份，所有制性质，员工人数，等基础信息。

升级到 AKShare 1.16.40 新增 stock_individual_basic_info_xq 接口
