### ISSUE TITLE
AKShare 加密货币数据 crypto_hist 不能正常使用

### ISSUE THREAD

**Issue by Onebirdie** [akfamily/akshare#5376]
出现  ValueError: No tables found
根据我的分析好像是在 https://cn.investing.com/crypto/ethereum/historical-data 接口获取的时候出现403导致的。
这个是对方网站的接口修改了吗

**Comment by albertandking** [comment]
> 出现 ValueError: No tables found 根据我的分析好像是在 https://cn.investing.com/crypto/ethereum/historical-data 接口获取的时候出现403导致的。 这个是对方网站的接口修改了吗

已移除相关接口
