### ISSUE TITLE
fund_open_fund_rank_em  根据参数不同，结果不一致，

### ISSUE THREAD

**Issue by iridescentGray** [akfamily/akshare#5377]
操作系统版本：Windows 11 
Python版本：Python3.12.5
AKShare版本：1.15.33
接口目录：AKShare公募基金数据\基金排行\开放式基金排行
接口名称：fund_open_fund_rank_em 
调用代码：
``` python

a=len(ak.fund_open_fund_rank_em(symbol="混合型"))
b=len(ak.fund_open_fund_rank_em(symbol="股票型"))
c=len(ak.fund_open_fund_rank_em(symbol="指数型"))
d=len(ak.fund_open_fund_rank_em(symbol="债券型"))
e=len(ak.fund_open_fund_rank_em(symbol="QDII"))
f=len(ak.fund_open_fund_rank_em(symbol="FOF"))
a+b+c+d+e+f   # 返回 16237
```

``` python

len(ak.fund_open_fund_rank_em(symbol="全部"))    # 返回 16239
```

按理说两个应该同样长吧？疑惑

仔细对比下基金的内容，如果传"全部",会多两个基金, '019005', '161226'

``` python

a=set(ak.fund_open_fund_rank_em(symbol="混合型")["基金代码"])
b=set(ak.fund_open_fund_rank_em(symbol="股票型")["基金代码"])
c=set(ak.fund_open_fund_rank_em(symbol="指数型")["基金代码"])
d=set(ak.fund_open_fund_rank_em(symbol="债券型")["基金代码"])
e=set(ak.fund_open_fund_rank_em(symbol="QDII")["基金代码"])
f=set(ak.fund_open_fund_rank_em(symbol="FOF")["基金代码"])
common_codes = a | b | c | d | e | f

all_code = set(ak.fund_open_fund_rank_em(symbol="全部")["基金代码"])
r = print(all_code - common_codes)   # 返回  {'019005', '161226'}
```

**Comment by albertandking** [comment]
> 操作系统版本：Windows 11 Python版本：Python3.12.5 AKShare版本：1.15.33 接口目录：AKShare公募基金数据\基金排行\开放式基金排行 接口名称：fund_open_fund_rank_em 调用代码：
> 
> ```python
> a=len(ak.fund_open_fund_rank_em(symbol="混合型"))
> b=len(ak.fund_open_fund_rank_em(symbol="股票型"))
> c=len(ak.fund_open_fund_rank_em(symbol="指数型"))
> d=len(ak.fund_open_fund_rank_em(symbol="债券型"))
> e=len(ak.fund_open_fund_rank_em(symbol="QDII"))
> f=len(ak.fund_open_fund_rank_em(symbol="FOF"))
> a+b+c+d+e+f   # 返回 16237
> ```
> 
> ```python
> len(ak.fund_open_fund_rank_em(symbol="全部"))    # 返回 16239
> ```
> 
> 按理说两个应该同样长吧？疑惑
> 
> 仔细对比下基金的内容，如果传"全部",会多两个基金, '019005', '161226'
> 
> ```python
> a=set(ak.fund_open_fund_rank_em(symbol="混合型")["基金代码"])
> b=set(ak.fund_open_fund_rank_em(symbol="股票型")["基金代码"])
> c=set(ak.fund_open_fund_rank_em(symbol="指数型")["基金代码"])
> d=set(ak.fund_open_fund_rank_em(symbol="债券型")["基金代码"])
> e=set(ak.fund_open_fund_rank_em(symbol="QDII")["基金代码"])
> f=set(ak.fund_open_fund_rank_em(symbol="FOF")["基金代码"])
> common_codes = a | b | c | d | e | f
> 
> all_code = set(ak.fund_open_fund_rank_em(symbol="全部")["基金代码"])
> r = print(all_code - common_codes)   # 返回  {'019005', '161226'}
> ```

目前跟接口跟数据源是一致的
