### ISSUE TITLE
AKShare 接口问题报告 | AKShare Interface Issue Report

### ISSUE THREAD

**Issue by yong900630** [akfamily/akshare#5379]
操作系统版本：Windows 11 22631.4541 64位
Python版本：Python3.12.6
AKShare版本：1.15.33
接口目录：AKShare期货数据\期货行情数据\外盘-实时行情数据-东财
接口名称：futures_global_em
调用代码：ak.futures_global_em() # 返回的全部是相同的数据，不会变化，不属于实时报价

下面是详细的代码：
import time
import datetime
import akshare as ak
# 用于在某个范围内随机生成一个数，用于查询间睡眠，防止被雪球封ip
import random
print(ak.__version__)

for _ in range(10):
    国际期货 = ak.futures_global_em()
    print(国际期货)
    时间 = datetime.datetime.now()

    纳指100期货 = 国际期货.loc[国际期货['代码'] == 'NQ00Y', '最新价'].values[0]
    print(f'{时间}，NQ00Y期货的最新价 = {纳指100期货}')

    标普500 = 国际期货.loc[国际期货['代码'] == 'ES00Y', '最新价'].values[0]
    print(f'{时间}，ES00Y期货的最新价 = {标普500}')
    随机时间 = random.randint(100, 200)
    print(f'睡眠{随机时间}s')  # 输出时间差值的秒数
    time.sleep(随机时间)
    
下面是输出结果：
1.15.33
      序号      代码          名称     最新价    涨跌额  ...      昨结    成交量    买盘    卖盘    持仓量
0      1   TF25N  20号合成胶2507  207.80   8.60  ...  199.20      5     0     5   1983
1      2   TF00Y  20号合成胶当月连续  208.20   6.60  ...  192.10    727   418   309  16025
2      3   TF25G  20号合成胶2502  208.20   6.60  ...  192.10    727   418   309  16025
3      4   TF25F  20号合成胶2501  205.50   6.50  ...  190.40    399   257   142  10681
4      5   TF25K  20号合成胶2505  208.30   6.30  ...  194.80    159   106    53   7377
..   ...     ...         ...     ...    ...  ...     ...    ...   ...   ...    ...
615  616    G25V     重柴油2510  666.25 -11.00  ...  670.50   2231  1737   494  20307
616  617    G25Z     重柴油2512  663.50 -11.00  ...  667.25  10317  5111  5206  49027
617  618  JAG25V     日白银2510  149.00  -2.50  ...  151.00      3     3     0     25
618  619    G25U     重柴油2509  664.75 -11.25  ...  669.50   3796  2352  1444  30708
619  620    G25Q     重柴油2508  665.00 -11.50  ...  669.25   1532   825   707  24886

[620 rows x 14 columns]
2024-11-28 08:28:32.898974，NQ00Y期货的最新价 = 20852.0
2024-11-28 08:28:32.898974，ES00Y期货的最新价 = 6022.75
睡眠160s
      序号      代码          名称     最新价    涨跌额  ...      昨结    成交量    买盘    卖盘    持仓量
0      1   TF25N  20号合成胶2507  207.80   8.60  ...  199.20      5     0     5   1983
1      2   TF25F  20号合成胶2501  205.50   6.80  ...  190.40    401   259   142  10681
2      3   TF00Y  20号合成胶当月连续  208.20   6.80  ...  192.10    730   421   309  16025
3      4   TF25G  20号合成胶2502  208.20   6.80  ...  192.10    730   421   309  16025
4      5   TF25J  20号合成胶2504  209.70   6.70  ...  194.00    301   138   163   9474
..   ...     ...         ...     ...    ...  ...     ...    ...   ...   ...    ...
615  616    G25V     重柴油2510  666.25 -11.00  ...  670.50   2231  1737   494  20307
616  617    G25Z     重柴油2512  663.50 -11.00  ...  667.25  10317  5111  5206  49027
617  618  JAG25V     日白银2510  149.00  -2.50  ...  151.00      3     3     0     25
618  619    G25U     重柴油2509  664.75 -11.25  ...  669.50   3796  2352  1444  30708
619  620    G25Q     重柴油2508  665.00 -11.50  ...  669.25   1532   825   707  24886

[620 rows x 14 columns]
2024-11-28 08:31:15.608132，NQ00Y期货的最新价 = 20852.25
2024-11-28 08:31:15.608132，ES00Y期货的最新价 = 6022.75
睡眠151s
      序号      代码          名称     最新价    涨跌额  ...      昨结    成交量    买盘    卖盘    持仓量
0      1   TF25N  20号合成胶2507  207.80   8.60  ...  199.20      5     0     5   1983
1      2   TF25F  20号合成胶2501  205.50   6.80  ...  190.40    401   259   142  10681
2      3   TF00Y  20号合成胶当月连续  208.20   6.80  ...  192.10    730   421   309  16025
3      4   TF25G  20号合成胶2502  208.20   6.80  ...  192.10    730   421   309  16025
4      5   TF25J  20号合成胶2504  209.70   6.70  ...  194.00    301   138   163   9474
..   ...     ...         ...     ...    ...  ...     ...    ...   ...   ...    ...
615  616    G25V     重柴油2510  666.25 -11.00  ...  670.50   2231  1737   494  20307
616  617    G25Z     重柴油2512  663.50 -11.00  ...  667.25  10317  5111  5206  49027
617  618  JAG25V     日白银2510  149.00  -2.50  ...  151.00      3     3     0     25
618  619    G25U     重柴油2509  664.75 -11.25  ...  669.50   3796  2352  1444  30708
619  620    G25Q     重柴油2508  665.00 -11.50  ...  669.25   1532   825   707  24886

[620 rows x 14 columns]
2024-11-28 08:33:49.315856，NQ00Y期货的最新价 = 20852.25
2024-11-28 08:33:49.315856，ES00Y期货的最新价 = 6022.75
睡眠192s

返回的信息都是一样的，不会变化

**Comment by albertandking** [comment]
> 操作系统版本：Windows 11 22631.4541 64位 Python版本：Python3.12.6 AKShare版本：1.15.33 接口目录：AKShare期货数据\期货行情数据\外盘-实时行情数据-东财 接口名称：futures_global_em 调用代码：ak.futures_global_em() # 返回的全部是相同的数据，不会变化，不属于实时报价
> 
> 下面是详细的代码： import time import datetime import akshare as ak
> 
> # 用于在某个范围内随机生成一个数，用于查询间睡眠，防止被雪球封ip
> import random print(ak.**version**)
> 
> for _ in range(10): 国际期货 = ak.futures_global_em() print(国际期货) 时间 = datetime.datetime.now()
> 
> ```
> 纳指100期货 = 国际期货.loc[国际期货['代码'] == 'NQ00Y', '最新价'].values[0]
> print(f'{时间}，NQ00Y期货的最新价 = {纳指100期货}')
> 
> 标普500 = 国际期货.loc[国际期货['代码'] == 'ES00Y', '最新价'].values[0]
> print(f'{时间}，ES00Y期货的最新价 = {标普500}')
> 随机时间 = random.randint(100, 200)
> print(f'睡眠{随机时间}s')  # 输出时间差值的秒数
> time.sleep(随机时间)
> ```
> 
> 下面是输出结果： 1.15.33 序号 代码 名称 最新价 涨跌额 ... 昨结 成交量 买盘 卖盘 持仓量 0 1 TF25N 20号合成胶2507 207.80 8.60 ... 199.20 5 0 5 1983 1 2 TF00Y 20号合成胶当月连续 208.20 6.60 ... 192.10 727 418 309 16025 2 3 TF25G 20号合成胶2502 208.20 6.60 ... 192.10 727 418 309 16025 3 4 TF25F 20号合成胶2501 205.50 6.50 ... 190.40 399 257 142 10681 4 5 TF25K 20号合成胶2505 208.30 6.30 ... 194.80 159 106 53 7377 .. ... ... ... ... ... ... ... ... ... ... ... 615 616 G25V 重柴油2510 666.25 -11.00 ... 670.50 2231 1737 494 20307 616 617 G25Z 重柴油2512 663.50 -11.00 ... 667.25 10317 5111 5206 49027 617 618 JAG25V 日白银2510 149.00 -2.50 ... 151.00 3 3 0 25 618 619 G25U 重柴油2509 664.75 -11.25 ... 669.50 3796 2352 1444 30708 619 620 G25Q 重柴油2508 665.00 -11.50 ... 669.25 1532 825 707 24886
> 
> [620 rows x 14 columns] 2024-11-28 08:28:32.898974，NQ00Y期货的最新价 = 20852.0 2024-11-28 08:28:32.898974，ES00Y期货的最新价 = 6022.75 睡眠160s 序号 代码 名称 最新价 涨跌额 ... 昨结 成交量 买盘 卖盘 持仓量 0 1 TF25N 20号合成胶2507 207.80 8.60 ... 199.20 5 0 5 1983 1 2 TF25F 20号合成胶2501 205.50 6.80 ... 190.40 401 259 142 10681 2 3 TF00Y 20号合成胶当月连续 208.20 6.80 ... 192.10 730 421 309 16025 3 4 TF25G 20号合成胶2502 208.20 6.80 ... 192.10 730 421 309 16025 4 5 TF25J 20号合成胶2504 209.70 6.70 ... 194.00 301 138 163 9474 .. ... ... ... ... ... ... ... ... ... ... ... 615 616 G25V 重柴油2510 666.25 -11.00 ... 670.50 2231 1737 494 20307 616 617 G25Z 重柴油2512 663.50 -11.00 ... 667.25 10317 5111 5206 49027 617 618 JAG25V 日白银2510 149.00 -2.50 ... 151.00 3 3 0 25 618 619 G25U 重柴油2509 664.75 -11.25 ... 669.50 3796 2352 1444 30708 619 620 G25Q 重柴油2508 665.00 -11.50 ... 669.25 1532 825 707 24886
> 
> [620 rows x 14 columns] 2024-11-28 08:31:15.608132，NQ00Y期货的最新价 = 20852.25 2024-11-28 08:31:15.608132，ES00Y期货的最新价 = 6022.75 睡眠151s 序号 代码 名称 最新价 涨跌额 ... 昨结 成交量 买盘 卖盘 持仓量 0 1 TF25N 20号合成胶2507 207.80 8.60 ... 199.20 5 0 5 1983 1 2 TF25F 20号合成胶2501 205.50 6.80 ... 190.40 401 259 142 10681 2 3 TF00Y 20号合成胶当月连续 208.20 6.80 ... 192.10 730 421 309 16025 3 4 TF25G 20号合成胶2502 208.20 6.80 ... 192.10 730 421 309 16025 4 5 TF25J 20号合成胶2504 209.70 6.70 ... 194.00 301 138 163 9474 .. ... ... ... ... ... ... ... ... ... ... ... 615 616 G25V 重柴油2510 666.25 -11.00 ... 670.50 2231 1737 494 20307 616 617 G25Z 重柴油2512 663.50 -11.00 ... 667.25 10317 5111 5206 49027 617 618 JAG25V 日白银2510 149.00 -2.50 ... 151.00 3 3 0 25 618 619 G25U 重柴油2509 664.75 -11.25 ... 669.50 3796 2352 1444 30708 619 620 G25Q 重柴油2508 665.00 -11.50 ... 669.25 1532 825 707 24886
> 
> [620 rows x 14 columns] 2024-11-28 08:33:49.315856，NQ00Y期货的最新价 = 20852.25 2024-11-28 08:33:49.315856，ES00Y期货的最新价 = 6022.75 睡眠192s
> 
> 返回的信息都是一样的，不会变化

已修复，主要是【最新价】字段匹配的问题，升级到 AKS hare 1.15.35 使用
