### ISSUE TITLE
issue of stock_individual_spot_xq interface

### ISSUE THREAD

**Issue by chenyu-vmware** [akfamily/akshare#5384]
with latest akshare version, looks stock_individual_spot_xq can't work as expected, please help to check.

C:\Users\tester\akshare>python3
Python 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import akshare as ak
>>> data = ak.stock_individual_spot_xq(symbol="SZ300760")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\chenyu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\akshare\stock\stock_xq.py", line 101, in stock_individual_spot_xq
    temp_df = pd.json_normalize(json_data["data"]["quote"])
                                ~~~~~~~~~^^^^^^^^
KeyError: 'data'

**Comment by albertandking** [comment]
> with latest akshare version, looks stock_individual_spot_xq can't work as expected, please help to check.
> 
> C:\Users\tester\akshare>python3 Python 3.12.7 (tags/v3.12.7:0b05ead, Oct 1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)] on win32 Type "help", "copyright", "credits" or "license" for more information.
> 
> > > > import akshare as ak
> > > > data = ak.stock_individual_spot_xq(symbol="SZ300760")
> > > > Traceback (most recent call last):
> > > > File "", line 1, in 
> > > > File "C:\Users\chenyu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\akshare\stock\stock_xq.py", line 101, in stock_individual_spot_xq
> > > > temp_df = pd.json_normalize(json_data["data"]["quote"])
> > > > ~~~~~~~~~^^^^^^^^
> > > > KeyError: 'data'

已修复，升级到 AKShare 1.15.37 使用
