### ISSUE TITLE
能源交易所的合约信息返回为空，请核查接口

### ISSUE THREAD

**Issue by jasonudu** [akfamily/akshare#5386]
https://www.ine.cn/data/instrument/ContractBaseInfo20241129.dat

2. 操作系统版本，win11
3. Python 版本，3.10.10
4. AKShare 版本，请升级到最新版 | AKShare version (please upgrade to latest)
5. 接口的名称和相应的调用代码 | 
调用接口futures_contract_info_ine，接口中通过网址https://www.ine.cn/data/instrument/ContractBaseInfo20241129.dat获取合约信息
网页可能有修改，返回错误。可能是地址有更改所致。

8. 期望获得的正确结果 | 
   请帮忙修正，并获得正确的数据

**Comment by jasonudu** [comment]
https://www.ine.cn/data/dailydata/kx/kx20241111.dat
还有获取行情的网址也变动了

**Comment by albertandking** [comment]
> https://www.ine.cn/data/instrument/ContractBaseInfo20241129.dat
> 
> 2. 操作系统版本，win11
> 3. Python 版本，3.10.10
> 4. AKShare 版本，请升级到最新版 | AKShare version (please upgrade to latest)
> 5. 接口的名称和相应的调用代码 |
>    调用接口futures_contract_info_ine，接口中通过网址[https://www.ine.cn/data/instrument/ContractBaseInfo20241129.dat获取合约信息](https://www.ine.cn/data/instrument/ContractBaseInfo20241129.dat%E8%8E%B7%E5%8F%96%E5%90%88%E7%BA%A6%E4%BF%A1%E6%81%AF)
>    网页可能有修改，返回错误。可能是地址有更改所致。
> 6. 期望获得的正确结果 |
>    请帮忙修正，并获得正确的数据

已修复该问题，升级到 AKShare 1.15.38 使用
