### ISSUE TITLE
futures_zh_minute_sina 接口返回数据不完整

### ISSUE THREAD

**Issue by Yzx-1024** [akfamily/akshare#5387]
Python: 3.10
Akshare: 1.15.27
重现代码：
import akshare as ak
data = ak.futures_zh_minute_sina("RB2501", "60")
print(data)
打印结果见截图。
![捕获](https://github.com/user-attachments/assets/4f8ad103-d2e5-44fe-9848-e1fbb032cf89)
合约RB2501最新数据应该是2024-11-30，而不是2024-4-18。是数据源接口没有返回最新数据？

谢谢支持。

**Comment by albertandking** [comment]
> Python: 3.10 Akshare: 1.15.27 重现代码： import akshare as ak data = ak.futures_zh_minute_sina("RB2501", "60") print(data) 打印结果见截图。 ![捕获](https://private-user-images.githubusercontent.com/177444434/391219783-4f8ad103-d2e5-44fe-9848-e1fbb032cf89.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5NjQxMzksIm5iZiI6MTczMjk2MzgzOSwicGF0aCI6Ii8xNzc0NDQ0MzQvMzkxMjE5NzgzLTRmOGFkMTAzLWQyZTUtNDRmZS05ODQ4LWUxZmJiMDMyY2Y4OS5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEzMFQxMDUwMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NjdmNjI0MWFkOGZjMGMzZTc3YWM4MDZkOTNiZjcxMDJjODAxYzNiNTM3OTZkNzk3NDAzY2JmZWJiZjE5NjljJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.SnTdGeUw9toqHyrfKCkwhnjC60wM6GKR38uCCE--36g) 合约RB2501最新数据应该是2024-11-30，而不是2024-4-18。是数据源接口没有返回最新数据？
> 
> 谢谢支持。

接口测试正常
