### ISSUE TITLE
python打包后报错缺少mini_racer.dll​​​​​​​和calendar.json 的问题

### ISSUE THREAD

**Issue by raymond8023** [akfamily/akshare#5398]
应该是普遍存在的问题，可以通过打包时--add-data来解决，能不能从根源上解决一下？或者出一个官方的建议？为什么这么久了都没优化呢？

**Comment by albertandking** [comment]
> 应该是普遍存在的问题，可以通过打包时--add-data来解决，能不能从根源上解决一下？或者出一个官方的建议？为什么这么久了都没优化呢？

这个不是项目本身的问题，可以依照网上相关文章的方案处理
