### ISSUE TITLE
基金持仓接口调用报错

### ISSUE THREAD

**Issue by orange1949** [akfamily/akshare#5400]
def get_fund_hold_detail():
    fund_list = ak.fund_name_em()['基金代码'].tolist()
    for fund in fund_list:
        df = ak.fund_portfolio_hold_em(symbol=fund, date="2024")
        df = df[['股票代码', '股票名称','持股数', '持仓市值', '季度']]
        df.columns = ['StockCode','StockName','HoldNum','HoldAmt','HoldQtr']
        df['HoldQtr'] = df['HoldQtr'].apply(lambda x:x.replace('股票投资明细',''))
        print(df)

get_fund_hold_detail()

![1733207711181](https://github.com/user-attachments/assets/d79e4c25-fa24-427e-90c7-00b02ba0eeb4)

**Comment by albertandking** [comment]
> def get_fund_hold_detail(): fund_list = ak.fund_name_em()['基金代码'].tolist() for fund in fund_list: df = ak.fund_portfolio_hold_em(symbol=fund, date="2024") df = df[['股票代码', '股票名称','持股数', '持仓市值', '季度']] df.columns = ['StockCode','StockName','HoldNum','HoldAmt','HoldQtr'] df['HoldQtr'] = df['HoldQtr'].apply(lambda x:x.replace('股票投资明细','')) print(df)
> 
> get_fund_hold_detail()
> 
> ![1733207711181](https://private-user-images.githubusercontent.com/87799601/391840575-d79e4c25-fa24-427e-90c7-00b02ba0eeb4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyMjMwMjIsIm5iZiI6MTczMzIyMjcyMiwicGF0aCI6Ii84Nzc5OTYwMS8zOTE4NDA1NzUtZDc5ZTRjMjUtZmEyNC00MjdlLTkwYzctMDBiMDJiYTBlZWI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAzVDEwNDUyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxZTdlYmI5NDI4OGIxZGNhMGI0YjNmYTM0ZGMyNzA3ZDFhZjA0Zjg2ODk0MDY4NzkyMzhjMjZlZjEzMTUxMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.aAPzsAhemFP0uKUtzVOxVPxj5ZZtM3qJLB_yl1u6qe8)

请按 issues 模板提交问题
