### ISSUE TITLE
AKShare 计算展期收益率错误

### ISSUE THREAD

**Issue by gaizoule** [akfamily/akshare#5406]
akshare 1.15.41
futures_roll_yield.py 第 72 行错误：
......
    if c > 0:
        **return math.log(close2 / close1) / c * 12, symbol2, symbol1         # 这里应该 math.log(close1 / close2)**
    else:
        return math.log(close2 / close1) / c * 12, symbol1, symbol2
......

**Comment by albertandking** [comment]
> akshare 1.15.41 futures_roll_yield.py 第 72 行错误： ...... if c > 0: **return math.log(close2 / close1) / c * 12, symbol2, symbol1 # 这里应该 math.log(close1 / close2)** else: return math.log(close2 / close1) / c * 12, symbol1, symbol2 ......

感谢反馈问题，已修复，升级到 AKShare 1.15.42

**Comment by gaizoule** [comment]
> > akshare 1.15.41 futures_roll_yield.py 第 72 行错误： ...... if c > 0: **return math.log(close2 / close1) / c * 12, symbol2, symbol1 # 这里应该 math.log(close1 / close2)** else: return math.log(close2 / close1) / c * 12, symbol1, symbol2 ......
> 
> 感谢反馈问题，已修复，升级到 AKShare 1.15.42

不好意思，我没说全，下面这个也要改，因为 c  < 0,
akshare 1.15.42
futures_roll_yield.py 第 72 行错误：
......
if c > 0:
return math.log(close2 / close1) / c * 12, symbol2, symbol1 # 这里应该 math.log(close1 / close2)
else:
return math.log(close2 / close1) / c * 12, symbol1, symbol2  # 下面这个也要改成 math.log(close1 / close2)  
......

**Comment by gaizoule** [comment]
> > akshare 1.15.41 futures_roll_yield.py 第 72 行错误： ...... if c > 0: **return math.log(close2 / close1) / c * 12, symbol2, symbol1 # 这里应该 math.log(close1 / close2)** else: return math.log(close2 / close1) / c * 12, symbol1, symbol2 ......
> 
> 感谢反馈问题，已修复，升级到 AKShare 1.15.42
    a = re.sub(r"\D", "", symbol1)
    a_1 = int(a[:-2])
    a_2 = int(a[-2:])
    b = re.sub(r"\D", "", symbol2)
    b_1 = int(b[:-2])
    b_2 = int(b[-2:])
    c = (a_1 - b_1) * 12 + (a_2 - b_2)

还有一个可能会出问题的地方，郑商所三位代码可能会导致计算 c 错误： 比如 symbol1 FG910（2019年10月到期） symbol FG001（2020年1月到期）

**Comment by gaizoule** [comment]
> > akshare 1.15.41 futures_roll_yield.py 第 72 行错误： ...... if c > 0: **return math.log(close2 / close1) / c * 12, symbol2, symbol1 # 这里应该 math.log(close1 / close2)** else: return math.log(close2 / close1) / c * 12, symbol1, symbol2 ......
> 
> 感谢反馈问题，已修复，升级到 AKShare 1.15.42
    a = re.sub(r"\D", "", symbol1)
    a_1 = int(a[:-2])
    a_2 = int(a[-2:])
    b = re.sub(r"\D", "", symbol2)
    b_1 = int(b[:-2])
    b_2 = int(b[-2:])
    c = (a_1 - b_1) * 12 + (a_2 - b_2)

还有一个可能会出问题的地方，郑商所三位代码可能会导致计算 c 错误： 比如 symbol1 FG910（2019年10月到期） symbol2 FG001（2020年1月到期）
