### ISSUE TITLE
十大流通股东的接口能否取最新的十大数据呢？

### ISSUE THREAD

**Issue by caihua** [akfamily/akshare#5412]
stock_gdfx_free_top_10_em，该接口传入date。
但是很多股会不定时更新数据，也就是说季报之后，年报之前的某天会更新数据，
例如回购股票时会公告当时的最新十大流通股东。
而这个date是不确定的，例如 SH603160 最新的数据是2024-11-22日，(十大股东也存在类似问题）
对该接口而言，其实最新的数据更重要一些。
所以是否有办法取得最新的数据，而不需要逐个股票填写不同的日期？毕竟这个日期在网页上是有值的，取最前面那个就行。

**Comment by albertandking** [comment]
> stock_gdfx_free_top_10_em，该接口传入date。 但是很多股会不定时更新数据，也就是说季报之后，年报之前的某天会更新数据， 例如回购股票时会公告当时的最新十大流通股东。 而这个date是不确定的，例如 SH603160 最新的数据是2024-11-22日，(十大股东也存在类似问题） 对该接口而言，其实最新的数据更重要一些。 所以是否有办法取得最新的数据，而不需要逐个股票填写不同的日期？毕竟这个日期在网页上是有值的，取最前面那个就行。

目前只能依赖数据源的接口来设计
