### ISSUE TITLE
AKShare 接口问题报告 | ak.stock_jgdy_detail_em 函数报错

### ISSUE THREAD

**Issue by quanplex** [akfamily/akshare#5413]
**详细问题描述** | Detailed Problem Description

使用 stock_jgdy_detail_em 函数下载机构调研明细数据，函数报错
1. Python 版本为3.9.12
2. AKShare 版本更新至最新版

ak.stock_jgdy_detail_em('20241209')

报错信息如下：
 line 131, in stock_jgdy_detail_em
 total_page = data_json['result']['pages']
TypeError: 'NoneType' object is not subscriptable

**Comment by albertandking** [comment]
> **详细问题描述** | Detailed Problem Description
> 
> 使用 stock_jgdy_detail_em 函数下载机构调研明细数据，函数报错
> 
> 1. Python 版本为3.9.12
> 2. AKShare 版本更新至最新版
> 
> ak.stock_jgdy_detail_em('20241209')
> 
> 报错信息如下： line 131, in stock_jgdy_detail_em total_page = data_json['result']['pages'] TypeError: 'NoneType' object is not subscriptable

已修复该问题，升级到 AKShare 1.15.45 使用
