### ISSUE TITLE
AKShare的接口get_futures_daily在条件market='INE'时获取2018年3月以前的数据出错问题

### ISSUE THREAD

**Issue by dahong38** [akfamily/akshare#5420]
**本人执行环境：Python 3.13.0，AKShare版本为1.15.45，AKTools版本为0.0.89，运行环境为64位的Windows 10** 
**imoprt akshare as ak
df = ak.get_futures_daily(start_date='20180301', end_date='20180331', market='INE')

执行后出现如下错误（部分内容）：**

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\core\indexes\base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\\_libs\\hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\\_libs\\hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'PRODUCTGROUPID'

**AKShare的接口get_futures_daily（）在条件market=‘INE' 日期范围在2018年3月以前的，执行后都出现上术错误，之前发issue反映过此问题，但回复接口正常就关了，实际一执行指定条件（上述已说明了）就出错。若是接口正常，是否我目前的运行环境条件问题？还是接口确实在上述特定的条件会出现Bug的问题？
感谢解决！**

**Comment by albertandking** [comment]
> **本人执行环境：Python 3.13.0，AKShare版本为1.15.45，AKTools版本为0.0.89，运行环境为64位的Windows 10** **imoprt akshare as ak df = ak.get_futures_daily(start_date='20180301', end_date='20180331', market='INE')
> 
> 执行后出现如下错误（部分内容）：**
> 
> Traceback (most recent call last): File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\core\indexes\base.py", line 3805, in get_loc return self._engine.get_loc(casted_key) ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^ File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc File "pandas\_libs\hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item File "pandas\_libs\hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item KeyError: 'PRODUCTGROUPID'
> 
> **AKShare的接口get_futures_daily（）在条件market=‘INE' 日期范围在2018年3月以前的，执行后都出现上术错误，之前发issue反映过此问题，但回复接口正常就关了，实际一执行指定条件（上述已说明了）就出错。若是接口正常，是否我目前的运行环境条件问题？还是接口确实在上述特定的条件会出现Bug的问题？ 感谢解决！**

请核对数据源

**Comment by dahong38** [comment]
> > **本人执行环境：Python 3.13.0，AKShare版本为1.15.45，AKTools版本为0.0.89，运行环境为64位的Windows 10** **imoprt akshare as ak df = ak.get_futures_daily(start_date='20180301', end_date='20180331', market='INE')
> > 执行后出现如下错误（部分内容）：**
> > Traceback (most recent call last): File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\core\indexes\base.py", line 3805, in get_loc return self._engine.get_loc(casted_key) ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^ File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc File "pandas_libs\hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item File "pandas_libs\hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item KeyError: 'PRODUCTGROUPID'
> > **AKShare的接口get_futures_daily（）在条件market=‘INE' 日期范围在2018年3月以前的，执行后都出现上术错误，之前发issue反映过此问题，但回复接口正常就关了，实际一执行指定条件（上述已说明了）就出错。若是接口正常，是否我目前的运行环境条件问题？还是接口确实在上述特定的条件会出现Bug的问题？ 感谢解决！**
> 
> 请核对数据源

 不好意思，由于本人对Python语言使用不太熟悉，所以在使用AKShare接口时，本人是兼用了AKTools工具转到第三方语言开发使用的，所以，这个“核对数据源”是什么意思？在哪里核实？
