### ISSUE TITLE
通过stock_zh_a_hist获取的股票数据涨跌额与实际涨跌额并不匹配

### ISSUE THREAD

**Issue by AZ5394** [akfamily/akshare#5422]
python版本:3.13
akshare版本:1.15.37
图中的涨跌额(测试)是用WPS的公式C2-B2再下拉算出来的
<img width="960" alt="Snipaste_2024-12-15_09-33-37" src="https://github.com/user-attachments/assets/96853e6d-00b9-4d2a-9960-7e2b680a100b" />
<img width="960" alt="Snipaste_2024-12-15_09-34-17" src="https://github.com/user-attachments/assets/0b857818-2883-4e35-9afd-b89350ffebaf" />

**Comment by albertandking** [comment]
> python版本:3.13 akshare版本:1.15.37 图中的涨跌额(测试)是用WPS的公式C2-B2再下拉算出来的 <img alt="Snipaste_2024-12-15_09-33-37" width="960" src="https://private-user-images.githubusercontent.com/103622688/395826509-96853e6d-00b9-4d2a-9960-7e2b680a100b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyNjk3MzEsIm5iZiI6MTczNDI2OTQzMSwicGF0aCI6Ii8xMDM2MjI2ODgvMzk1ODI2NTA5LTk2ODUzZTZkLTAwYjktNGQyYS05OTYwLTdlMmI2ODBhMTAwYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNVQxMzMwMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OGFlMmVjM2M1YTQ2NGNmOTAyNjUwYTM0ZmI0YzA0ZWFkNDE3ZTNlNWQ5Zjc5Y2ZmM2Q1YzdhMGY1N2RlZGMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2dlkUruwS5nq9E-Z8YkFKF8bh0Tt0x71yF-cT0ZKaTk"> <img alt="Snipaste_2024-12-15_09-34-17" width="960" src="https://private-user-images.githubusercontent.com/103622688/395826511-0b857818-2883-4e35-9afd-b89350ffebaf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyNjk3MzEsIm5iZiI6MTczNDI2OTQzMSwicGF0aCI6Ii8xMDM2MjI2ODgvMzk1ODI2NTExLTBiODU3ODE4LTI4ODMtNGUzNS05YWZkLWI4OTM1MGZmZWJhZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNVQxMzMwMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YjIwYWI5ZWFkMTIzMTE5ZGIwYWI2OTk3ZjUzMjkzOTIzNDZmZGJiYzBmYmQ4ZmNhMGYzNjUzOTUyOGViYzg0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.9eJqgkgH3yhnB4I9jwJZODu4ZiAXteLAxTfRInOaCwg">

以数据源提供的数据为准
