### ISSUE TITLE
AKShare 接口问题报告(stock_individual_spot_xq)

### ISSUE THREAD

**Issue by linuxyan** [akfamily/akshare#5423]
1. 请先详细阅读文档对应接口的使用方式 | Please read the documentation thoroughly for the
relevant interface：https://akshare.akfamily.xyz
2. 操作系统版本，目前只支持 64 位操作系统 | Operating system version (64-bit only supported)
    ubuntu 24  x64
4. Python 版本，目前只支持 3.8 以上的版本 | Python version (must be 3.8 or above)
    `3.10.15`
5. AKShare 版本，请升级到最新版 | AKShare version (please upgrade to latest)
  ` Installing akshare (1.15.21)`
6. 接口的名称和相应的调用代码 | Interface name and corresponding code
```
          # 获取股票日数据指标数据
          indicator_data = ak.stock_individual_spot_xq(symbol='SH600519')

```
7. 接口报错的截图或描述
```
Traceback (most recent call last):
  File "/home/runner/work/investment/investment/data_day.py", line 29, in get_stock_day_data
Get day data : ['600519', '贵州茅台']
    indicator_data = ak.stock_individual_spot_xq(symbol='SH600519')
  File "/home/runner/work/investment/investment/.venv/lib/python3.10/site-packages/akshare/stock/stock_xq.py", line 99, in stock_individual_spot_xq
    temp_df = pd.json_normalize(json_data["data"]["quote"])
KeyError: 'data'

```
8. 期望获得的正确结果 
正常应该返回对应股票的每日数据指标

**Comment by albertandking** [comment]
> 1. 请先详细阅读文档对应接口的使用方式 | Please read the documentation thoroughly for the
>    relevant interface：https://akshare.akfamily.xyz
> 2. 操作系统版本，目前只支持 64 位操作系统 | Operating system version (64-bit only supported)
>    ubuntu 24  x64
> 3. Python 版本，目前只支持 3.8 以上的版本 | Python version (must be 3.8 or above)
>    `3.10.15`
> 4. AKShare 版本，请升级到最新版 | AKShare version (please upgrade to latest)
>    ` Installing akshare (1.15.21)`
> 5. 接口的名称和相应的调用代码 | Interface name and corresponding code
> 
> ```
>           # 获取股票日数据指标数据
>           indicator_data = ak.stock_individual_spot_xq(symbol='SH600519')
> ```
> 
> 7. 接口报错的截图或描述
> 
> ```
> Traceback (most recent call last):
>   File "/home/runner/work/investment/investment/data_day.py", line 29, in get_stock_day_data
> Get day data : ['600519', '贵州茅台']
>     indicator_data = ak.stock_individual_spot_xq(symbol='SH600519')
>   File "/home/runner/work/investment/investment/.venv/lib/python3.10/site-packages/akshare/stock/stock_xq.py", line 99, in stock_individual_spot_xq
>     temp_df = pd.json_normalize(json_data["data"]["quote"])
> KeyError: 'data'
> ```
> 
> 8. 期望获得的正确结果
>    正常应该返回对应股票的每日数据指标

已修复，升级到 AKShare 1.15.47 使用
