### ISSUE TITLE
AKShare 接口问题报告 | AKShare Interface Issue Report

### ISSUE THREAD

**Issue by LuoHua430** [akfamily/akshare#5427]
操作系统版本：Windows 11 64位
Python 版本：3.10.14
AKShare 版本：1.15.47
接口的名称和相应的调用代码：ak.fund_etf_fund_info_em
代码：
import akshare as ak

# 定义常量
DATE_INIT = "20200101"
DATE_TODAY = '20241212'
etf_code = '511880'
fund_etf_fund_info_em_df = ak.fund_etf_fund_info_em(fund=etf_code, start_date=DATE_INIT, end_date=DATE_TODAY)
print(fund_etf_fund_info_em_df)

接口报错的截图或描述：
Traceback (most recent call last):
  File "g:\Works\python\Low Risk ETF\test.py", line 7, in <module>
    fund_etf_fund_info_em_df = ak.fund_etf_fund_info_em(fund=etf_code, start_date=DATE_INIT, end_date=DATE_TODAY)
  File "E:\Programming\anaconda3\envs\finance\lib\site-packages\akshare\fund\fund_em.py", line 958, in fund_etf_fund_info_em
    temp_df = pd.DataFrame(data_json["Data"]["LSJZList"])
TypeError: 'NoneType' object is not subscriptable

期望获得的正确结果：获取包括净值数据的dataframe

**Comment by albertandking** [comment]
> 511880

接口测试正常
