### ISSUE TITLE
stock_hsgt_hist_em 北向资金缺失

### ISSUE THREAD

**Issue by ssz25** [akfamily/akshare#5448]
stock_hsgt_hist_em 北向资金缺失  ，南向资金是有的

https://data.eastmoney.com/hsgt/index.html  是有北向按日数据的，只是没有当日实时

**Comment by albertandking** [comment]
> stock_hsgt_hist_em 北向资金缺失 ，南向资金是有的
> 
> https://data.eastmoney.com/hsgt/index.html 是有北向按日数据的，只是没有当日实时

数据源没有提供
