### ISSUE TITLE
12月26日多晶硅要在广期所上市了，会出现上次原木上市代码没更新就报异常的情况吗？

### ISSUE THREAD

**Issue by Yzx-1024** [akfamily/akshare#5452]
新品种上市，最好同步数据不要报异常。

新闻来源：
http://www.gfex.com.cn/gfex/mtjj/202412/69404d76bb1c49b9bc879bc9d1578ced.shtml

谢谢支持。

**Comment by albertandking** [comment]
> 新品种上市，最好同步数据不要报异常。
> 
> 新闻来源： http://www.gfex.com.cn/gfex/mtjj/202412/69404d76bb1c49b9bc879bc9d1578ced.shtml
> 
> 谢谢支持。

具体会影响哪几个接口？

**Comment by Yzx-1024** [comment]
俩月前原木品种上市时get_futures_daily这个接口直接抛异常，其它的没有测试。

**Comment by Yzx-1024** [comment]
应该是代码里有常量dict，新品种需要维护进去。但从健壮性考量，数据源有变化最好不要直接throw exception。

**Comment by Yzx-1024** [comment]
上次处理原木更新后的代码可以适应交易所新品种（广期所的多晶硅）代码。
