### ISSUE TITLE
1.15.52 移除了funddb的相关接口

### ISSUE THREAD

**Issue by lilaboc** [akfamily/akshare#5454]
1.15.52 fix: fix stock_zh_index_hist_csindex interface

1. 修复 stock_zh_index_hist_csindex 接口
2. 移除 funddb 相关接口

请问一下为什么, 有些代码以来funddb的数据

谢谢!

**Comment by albertandking** [comment]
> 1.15.52 fix: fix stock_zh_index_hist_csindex interface
> 
> 1. 修复 stock_zh_index_hist_csindex 接口
> 2. 移除 funddb 相关接口
> 
> 请问一下为什么, 有些代码以来funddb的数据
> 
> 谢谢!

可以用老版本的代码来获取
