### ISSUE TITLE
AKShare 接口问题报告 | AKShare Interface Issue Report | index_value_name_funddb()

### ISSUE THREAD

**Issue by lgb54335** [akfamily/akshare#5457]
> 欢迎加入《数据科学实战》知识星球，交流财经数据与量化投资相关内容 |
> Welcome to join "Data Science in Practice" Knowledge
> Community for discussions on financial data and quantitative investment.
>
> 详细信息参考 | For detailed information, please visit:：https://akshare.akfamily.xyz/learn.html

## 前提 | Prerequisites

遇到任何问题，请先将您的 AKShare 版本升级到**最新版**，可以通过如下命令升级 | Before reporting any issues, please upgrade
your AKShare to the **latest version** using the following command:：

```
pip install akshare --upgrade  # Python 版本需要大于等于 3.8 | Python version requirement ≥ 3.8
```

## 如何提交问题 | How to Submit an Issue

提交问题的同时，请提交以下相关信息，以更精准的解决问题。| Please provide the following information when
submitting an issue for more accurate problem resolution.

**不符合提交规范的 issues 会被关闭！** | **Issues that don't follow these guidelines will be closed!**

**详细问题描述** | Detailed Problem Description

1. 请先详细阅读文档对应接口的使用方式 | Please read the documentation thoroughly for the
relevant interface：https://akshare.akfamily.xyz
2. 操作系统版本，目前只支持 64 位操作系统 | Operating system version (64-bit only supported) | **windows11-x64**
3. Python 版本，目前只支持 3.8 以上的版本 | Python version (must be 3.8 or above) | **python3.12.8**
4. AKShare 版本，请升级到最新版 | AKShare version (please upgrade to latest) | **akshare version 1.15.53**
5. 接口的名称和相应的调用代码 | Interface name and corresponding code | **ak_lut_df = ak.index_value_name_funddb()**
6. 接口报错的截图或描述 | Screenshot or description of the error 
![图片](https://github.com/user-attachments/assets/ac8fd23d-de54-4794-9ea7-d0c98d864926)
**无法调用index_value_name_funddb接口**
7. 期望获得的正确结果 | Expected correct results | **期望返回dataframe包含各指数的市净率**

**Comment by albertandking** [comment]
> > 欢迎加入《数据科学实战》知识星球，交流财经数据与量化投资相关内容 |
> > Welcome to join "Data Science in Practice" Knowledge
> > Community for discussions on financial data and quantitative investment.
> > 详细信息参考 | For detailed information, please visit:：https://akshare.akfamily.xyz/learn.html
> 
> ## 前提 | Prerequisites
> 遇到任何问题，请先将您的 AKShare 版本升级到**最新版**，可以通过如下命令升级 | Before reporting any issues, please upgrade your AKShare to the **latest version** using the following command:：
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于等于 3.8 | Python version requirement ≥ 3.8
> ```
> 
> ## 如何提交问题 | How to Submit an Issue
> 提交问题的同时，请提交以下相关信息，以更精准的解决问题。| Please provide the following information when submitting an issue for more accurate problem resolution.
> 
> **不符合提交规范的 issues 会被关闭！** | **Issues that don't follow these guidelines will be closed!**
> 
> **详细问题描述** | Detailed Problem Description
> 
> 1. 请先详细阅读文档对应接口的使用方式 | Please read the documentation thoroughly for the
>    relevant interface：https://akshare.akfamily.xyz
> 2. 操作系统版本，目前只支持 64 位操作系统 | Operating system version (64-bit only supported) | **windows11-x64**
> 3. Python 版本，目前只支持 3.8 以上的版本 | Python version (must be 3.8 or above) | **python3.12.8**
> 4. AKShare 版本，请升级到最新版 | AKShare version (please upgrade to latest) | **akshare version 1.15.53**
> 5. 接口的名称和相应的调用代码 | Interface name and corresponding code | **ak_lut_df = ak.index_value_name_funddb()**
> 6. 接口报错的截图或描述 | Screenshot or description of the error
>    ![图片](https://private-user-images.githubusercontent.com/176120973/398178539-ac8fd23d-de54-4794-9ea7-d0c98d864926.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwMzAzNjgsIm5iZiI6MTczNTAzMDA2OCwicGF0aCI6Ii8xNzYxMjA5NzMvMzk4MTc4NTM5LWFjOGZkMjNkLWRlNTQtNDc5NC05ZWE3LWQwYzk4ZDg2NDkyNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNFQwODQ3NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mM2I5NDYyZmNjOTY0NTk3NzVlZTg5NzNmYzlhNWE1NWNiNGY3MmE5YTEwNmQ1NWM3M2Q5Zjk5MTBlNTQxOGU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.OnL4uaesOpIznvbUgnHilBZulSGTYhcClgWWiZJJE9w)
>    **无法调用index_value_name_funddb接口**
> 7. 期望获得的正确结果 | Expected correct results | **期望返回dataframe包含各指数的市净率**

已移除相关接口，可以利用老版本获取

**Comment by xnw176** [comment]
是韭圈要求关闭的么？这家数据不是太好还特小气，网站天天改来改去。
