### ISSUE TITLE
match_main_contract这个接口好像出了点问题

### ISSUE THREAD

**Issue by skysunsun** [akfamily/akshare#5460]
`dce_text = ak.match_main_contract(symbol="dce")`
返回
`pvc_qh 无主力合约
zly_qh 无主力合约
de_qh 无主力合约
dp_qh 无主力合约
tks_qh 无主力合约
jd_qh 无主力合约
lldpe_qh 无主力合约
jbx_qh 无主力合约
xwb_qh 无主力合约
jhb_qh 无主力合约
dy_qh 无主力合约
hym_qh 无主力合约
dd_qh 无主力合约
jt_qh 无主力合约
jm_qh 无主力合约
ymdf_qh 无主力合约
yec_qh 无主力合约
RR2502
byx_qh 无主力合约
pg_qh 无主力合约
lh_qh 无主力合约
lg_qh 无主力合约
dce主力合约获取成功
RR2502`

**Comment by U-369956** [comment]
+10086

今天下午开始出现问题的

**Comment by skysunsun** [comment]
> +10086
> 
> 今天下午开始出现问题的

应该是新浪那边变了什么

**Comment by U-369956** [comment]
> > +10086
> > 今天下午开始出现问题的
> 
> 应该是新浪那边变了什么

作者一般多久能帮忙处理？我第一次提问

**Comment by albertandking** [comment]
> `dce_text = ak.match_main_contract(symbol="dce")` 返回 `pvc_qh 无主力合约 zly_qh 无主力合约 de_qh 无主力合约 dp_qh 无主力合约 tks_qh 无主力合约 jd_qh 无主力合约 lldpe_qh 无主力合约 jbx_qh 无主力合约 xwb_qh 无主力合约 jhb_qh 无主力合约 dy_qh 无主力合约 hym_qh 无主力合约 dd_qh 无主力合约 jt_qh 无主力合约 jm_qh 无主力合约 ymdf_qh 无主力合约 yec_qh 无主力合约 RR2502 byx_qh 无主力合约 pg_qh 无主力合约 lh_qh 无主力合约 lg_qh 无主力合约 dce主力合约获取成功 RR2502`

经测试，已经恢复正常，应该是昨天新浪数据异常导致的，连续合约根具体的合约匹配不到，导致代码出错
