### ISSUE TITLE
AKShare 接口问题报告 | AKShare Interface Issue Report

### ISSUE THREAD

**Issue by Wa-JHH** [akfamily/akshare#5462]
操作系统版本 debian 12
Python 版本 3.13
AKShare 版本 1.15.54

接口的名称和相应的调用代码 
**东财获取ETF fund_etf_spot_em**

调用代码
ak.fund_etf_spot_em()

**该接口目前只能获取1000个ETF的信息，并没有1次返回所有**

接口报错的截图或描述 | Screenshot or description of the error
![image](https://github.com/user-attachments/assets/e702b7d5-2506-4f4e-8179-fd2d55e086a8)

期望获得的正确结果 | Expected correct results
**希望可以一次返回所有数据**

**Comment by albertandking** [comment]
> 操作系统版本 debian 12 Python 版本 3.13 AKShare 版本 1.15.54
> 
> 接口的名称和相应的调用代码 **东财获取ETF fund_etf_spot_em**
> 
> 调用代码 ak.fund_etf_spot_em()
> 
> **该接口目前只能获取1000个ETF的信息，并没有1次返回所有**
> 
> 接口报错的截图或描述 | Screenshot or description of the error ![image](https://private-user-images.githubusercontent.com/32030753/398589703-e702b7d5-2506-4f4e-8179-fd2d55e086a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyMTAxNzAsIm5iZiI6MTczNTIwOTg3MCwicGF0aCI6Ii8zMjAzMDc1My8zOTg1ODk3MDMtZTcwMmI3ZDUtMjUwNi00ZjRlLTgxNzktZmQyZDU1ZTA4NmE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI2VDEwNDQzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyM2EzMjQwMWQwMzU0ZmNiY2JiNTY5NDBhNTRkNzhhM2JlYTMxZDU4YWEwNDU4N2FlNmEyYmZjMmExMjA4OTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.kbZcGVaSS8VaagH9xupkw1uVXBZrIqCHNvy1bn7iX9c)
> 
> 期望获得的正确结果 | Expected correct results **希望可以一次返回所有数据**

已修复，升级到 AKShare 1.15.55 使用
