### ISSUE TITLE
AKShare 接口问题报告 | CNINFO（巨潮）数据获取失败报错

### ISSUE THREAD

**Issue by LIKEHAM** [akfamily/akshare#5472]
**详细问题描述**
2. 操作系统版本：64 位操作系统, 基于 x64 的处理器；
3. Python 版本：Python 3.13；
4. AKShare 版本：原用1.12.95没问题，更新到1.15.58后报错后 ，已退回安装1.12.95；
5. 接口的名称和相应的调用代码：
截止目前已发现：
（1）ak.stock_dividend_cninfo
（2）ak.stock_share_change_cninfo
6. 接口报错的截图或描述：
因为报错导致系统不可用，已退回原可用版本，目前暂无法提供截图，简单说就是报了大意为错误package的问题；
（1）具体描述可用Akshare网站数据字典的示例即可得到：
import akshare as ak
stock_dividend_cninfo_df = ak.stock_dividend_cninfo(symbol="600009")
print(stock_dividend_cninfo_df)
（2）具体描述可用Akshare网站数据字典的示例即可得到：
import akshare as ak
stock_share_change_cninfo_df = ak.stock_share_change_cninfo(symbol="002594", start_date="20091227", end_date="20241021")
print(stock_share_change_cninfo_df)
7. 期望获得的正确结果：可用；

**Comment by albertandking** [comment]
> **详细问题描述** 2. 操作系统版本：64 位操作系统, 基于 x64 的处理器； 3. Python 版本：Python 3.13； 4. AKShare 版本：原用1.12.95没问题，更新到1.15.58后报错后 ，已退回安装1.12.95； 5. 接口的名称和相应的调用代码： 截止目前已发现： （1）ak.stock_dividend_cninfo （2）ak.stock_share_change_cninfo 6. 接口报错的截图或描述： 因为报错导致系统不可用，已退回原可用版本，目前暂无法提供截图，简单说就是报了大意为错误package的问题； （1）具体描述可用Akshare网站数据字典的示例即可得到： import akshare as ak stock_dividend_cninfo_df = ak.stock_dividend_cninfo(symbol="600009") print(stock_dividend_cninfo_df) （2）具体描述可用Akshare网站数据字典的示例即可得到： import akshare as ak stock_share_change_cninfo_df = ak.stock_share_change_cninfo(symbol="002594", start_date="20091227", end_date="20241021") print(stock_share_change_cninfo_df) 7. 期望获得的正确结果：可用；

已修复，升级到 AKShare 1.15.60 使用

**Comment by LIKEHAM** [comment]
Roger that, tks.
----- Original Message -----
From: Albert King ***@***.***>
To: akfamily/akshare ***@***.***>
Cc: LIKEHAM ***@***.***>,  Author ***@***.***>
Subject: Re:_[akfamily/akshare]_AKShare_接口问题报告_|_CNINFO（巨潮）数据获取失败报错_(Issue_#5472)
Date: 2024-12-30 16:23



详细问题描述 2. 操作系统版本：64 位操作系统, 基于 x64 的处理器； 3. Python 版本：Python 3.13； 4. AKShare 版本：原用1.12.95没问题，更新到1.15.58后报错后 ，已退回安装1.12.95； 5. 接口的名称和相应的调用代码： 截止目前已发现： （1）ak.stock_dividend_cninfo （2）ak.stock_share_change_cninfo 6. 接口报错的截图或描述： 因为报错导致系统不可用，已退回原可用版本，目前暂无法提供截图，简单说就是报了大意为错误package的问题； （1）具体描述可用Akshare网站数据字典的示例即可得到： import akshare as ak stock_dividend_cninfo_df = ak.stock_dividend_cninfo(symbol="600009") print(stock_dividend_cninfo_df) （2）具体描述可用Akshare网站数据字典的示例即可得到： import akshare as ak stock_share_change_cninfo_df = ak.stock_share_change_cninfo(symbol="002594", start_date="20091227", end_date="20241021") print(stock_share_change_cninfo_df) 7. 期望获得的正确结果：可用；

已修复，升级到 AKShare 1.15.60 使用
