### ISSUE TITLE
数据字典文档内容错误

### ISSUE THREAD

**Issue by FreeZIngMoon11** [akfamily/akshare#5473]
AkShare指数数据 - A股股票指数数据 - 历史行情数据-东方财富 - 接口: stock_zh_index_daily_em
symbol参数 “csi + id” 应为中证指数

![image](https://github.com/user-attachments/assets/8fc900be-2c94-40fc-81b0-9704496e8806)

**Comment by albertandking** [comment]
> AkShare指数数据 - A股股票指数数据 - 历史行情数据-东方财富 - 接口: stock_zh_index_daily_em symbol参数 “csi + id” 应为中证指数
> 
> ![image](https://private-user-images.githubusercontent.com/56440183/399134635-8fc900be-2c94-40fc-81b0-9704496e8806.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1NDcyODgsIm5iZiI6MTczNTU0Njk4OCwicGF0aCI6Ii81NjQ0MDE4My8zOTkxMzQ2MzUtOGZjOTAwYmUtMmM5NC00MGZjLTgxYjAtOTcwNDQ5NmU4ODA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMwVDA4MjMwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyMDYyOTE1MDcyYjlkOGJkMzAyODFjNjBlZGEyNzlmZDEwMGE0NDU5NDlhMjg0MmIzOWM5NWIzZWRmOTk4ZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GfDEJHvotRZ31m7XepN_GZYrr1URDvDZ1JGUY2gzo4o)

已修复，升级到 AKShare 1.15.60 使用
