### ISSUE TITLE
同样板的概念板块对应的热度值不一样

### ISSUE THREAD

**Issue by lk1983823** [akfamily/akshare#5474]
我使用ak.stock_hot_keyword_em搜索个股所属的板块以及对应的热度，发现不同的股票对应相同的板块，但是热度值不一样？ 是不是有错误？
比如:
![image](https://github.com/user-attachments/assets/6525657e-f6e5-4fe3-b5a5-62928b881a94)
![image](https://github.com/user-attachments/assets/3924e64c-d6b6-4c02-94ed-04a49e92ed2c)
请问这是什么原因？

**Comment by albertandking** [comment]
> stock_hot_keyword_em

是针对股票而言的
