### ISSUE TITLE
futures_comm_info接口问题

### ISSUE THREAD

**Issue by CrackerLee** [akfamily/akshare#5476]
调用ak.futures_comm_info(symbol="所有")出错，是因为"https://www.9qihuo.com/qihuoshouxufei“的反爬虫机制？

**Comment by kidultff** [comment]
同样的问题，好像开了宝塔waf，会把python requests的请求识别为恶意请求

**Comment by albertandking** [comment]
> 调用ak.futures_comm_info(symbol="所有")出错，是因为"[https://www.9qihuo.com/qihuoshouxufei“的反爬虫机制？](https://www.9qihuo.com/qihuoshouxufei%E2%80%9C%E7%9A%84%E5%8F%8D%E7%88%AC%E8%99%AB%E6%9C%BA%E5%88%B6%EF%BC%9F)

可以正常获取
