### ISSUE TITLE
stock_zt_pool_strong_em接口返回的 ‘入选理由’字段是数字

### ISSUE THREAD

**Issue by Hanchers** [akfamily/akshare#5478]
目前是最新版本：1.15.60

请求接口stock_zt_pool_strong_em

返回：
```
      序号      代码    名称        涨跌幅    最新价  ...  是否新高        量比  涨停统计  入选理由  所属行业
0      1  301202  朗威股份  19.994860  46.69  ...     1  2.298022   1/1     1  通用设备
1      2  002629  仁智股份  10.103627   4.25  ...     0  1.863184   2/2     2  采掘行业
2      3  002361  神剑股份  10.101010   5.45  ...     1  8.426764   3/3     3  塑料制品
3      4  002442  龙星化工  10.073260   6.01  ...     1  1.979328   1/1     1  橡胶制品
```

实际入选理由是 一串文案
![image](https://github.com/user-attachments/assets/1e6bc511-aa1d-4311-8b63-bcab82ee8798)

**Comment by albertandking** [comment]
> 目前是最新版本：1.15.60
> 
> 请求接口stock_zt_pool_strong_em
> 
> 返回：
> 
> ```
>       序号      代码    名称        涨跌幅    最新价  ...  是否新高        量比  涨停统计  入选理由  所属行业
> 0      1  301202  朗威股份  19.994860  46.69  ...     1  2.298022   1/1     1  通用设备
> 1      2  002629  仁智股份  10.103627   4.25  ...     0  1.863184   2/2     2  采掘行业
> 2      3  002361  神剑股份  10.101010   5.45  ...     1  8.426764   3/3     3  塑料制品
> 3      4  002442  龙星化工  10.073260   6.01  ...     1  1.979328   1/1     1  橡胶制品
> ```
> 
> 实际入选理由是 一串文案 ![image](https://private-user-images.githubusercontent.com/26269682/399431435-1e6bc511-aa1d-4311-8b63-bcab82ee8798.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU2NTU4MDYsIm5iZiI6MTczNTY1NTUwNiwicGF0aCI6Ii8yNjI2OTY4Mi8zOTk0MzE0MzUtMWU2YmM1MTEtYWExZC00MzExLThiNjMtYmNhYjgyZWU4Nzk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMxVDE0MzE0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5ZDAwY2UxNTkzNjlkODljNWNmNjM1N2QzNGZjODJlZWJmZDZiOTA3NWQ3MWFmNmY5NzU4MWU2ZTZkMjMxNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.aTSamUgMIqx8tTgk9-trjXx9afnwwNkkCBP-pvhyJEk)

已修复，升级到 AKShare 1.15.61 使用
